### ISSUE TITLE
Example 1.js doesn't work

### ISSUE THREAD

**Issue by davidweisss** [ipfs/js-ipfs#1014]
The basic example doesn't return anything.
![2017-09-11-092353_442x319_scrot](https://user-images.githubusercontent.com/1084645/30267921-992d960e-96d3-11e7-873f-3b48f3c757d5.png)
Best-

- **Version**:
- **Platform**:
- **Subsystem**:

**Comment by diasdavid** [comment]
Since you are running the example on the node REPL, you are opening yourself to a race condition on the action "listening to the ready event" and the "new IPFS()" call.

To run the example, avoid using the node REPL (not designed to work there) and just do: `node 1.js`

**Comment by diasdavid** [comment]
Did that work for you? I see a thumbs up but just want to make sure it is ok to close this issue :)

**Comment by davidweisss** [comment]
Yes, thanks!
