### ISSUE TITLE
node.on('ready') won't trigger when reinstall ipfs  

### ISSUE THREAD

**Issue by EasonWang01** [ipfs/js-ipfs#1015]
- **Version**:  nodejs 6.11.3    ipfs: lastest
- **Platform**: ubuntu 16.04

Because npm issue,so when I install other dependence the ipfs modue been deleted,so I install ipfs again.

But when execute the code below again will not happen anything after reinstall ipfs using`npm install ipfs` or `yarn add ipfs.`
trying to remove node_module and reinstall but still not works.

but there is a node object for  `console.log(node)` 

```js
const IPFS = require('ipfs')
const fs = require('fs');

const node = new IPFS()
node.on('ready', () => {
  node.files.add({
    path: '',
    content: fs.createReadStream('./sample.txt')
  }, (err, result) => {
    if (err) { throw err }

    console.log('\nAdded file:', result[0].path, result[0].hash)
  })
})
```

**Comment by diasdavid** [comment]
Are you sure it is the `ready` event? Add a console log before the node.files.add.

**Comment by EasonWang01** [comment]
Yes,this code works before https://github.com/ipfs/js-ipfs/issues/1000

**Comment by EasonWang01** [comment]
I found out the error is

```
Error: can't lock file /home/xblockchain9/.jsipfs/repo.lock: has non-zero size
    at fs.stat (/home/xblockchain9/node_modules/lock-me/src/unix.js:11:19)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by diasdavid** [comment]
looks like the lock was left behind. just remove that file :)

**Comment by EasonWang01** [comment]
Thanks,do you know which situation will generate this lock file.

**Comment by diasdavid** [comment]
Glad that worked :) 

The lock file is generated every time to start the node. You need to shutdown the node graciously (with .stop) to remove it. If you kill the process, then you have to remove it manually.
