### ISSUE TITLE
Win10 64b - binding.fcntl is not a function

### ISSUE THREAD

**Issue by negamaxi** [ipfs/js-ipfs#1016]
- **Version**: 0.26.0
- **Platform**: Windows 10 64bit
- **Subsystem**:

#### Description:
```
e:\Projects\clear>node test.js
e:\Projects\clear\node_modules\fs-ext\fs-ext.js:106
 return binding.fcntl(fd, cmd, arg, callback);
                ^

TypeError: binding.fcntl is not a function
   at Object.exports.fcntl (e:\Projects\clear\node_modules\fs-ext\fs-ext.js:106:18)
   at waterfall (e:\Projects\clear\node_modules\lock-me\src\unix.js:17:20)
   at nextTask (e:\Projects\clear\node_modules\async\waterfall.js:16:14)
   at next (e:\Projects\clear\node_modules\async\waterfall.js:23:9)
   at e:\Projects\clear\node_modules\async\internal\onlyOnce.js:12:16
   at FSReqWrap.oncomplete (fs.js:135:15)
```
#### Steps to reproduce the error:
```javascript
const IPFS = require('ipfs')
const ipfs = new IPFS()
```

**Comment by diasdavid** [comment]
@negamaxi we really don't support Windows at the moment. See https://github.com/ipfs/js-ipfs/issues/1017

**Comment by VictorBjelkholm** [comment]
Try removing `node_modules\fs-ext` as it's a optional dependency and you should at least be able to start the daemon.

**Comment by dignifiedquire** [comment]
I published a new version of `lock-me` which should fix this: https://github.com/dignifiedquire/lock-me

**Comment by diasdavid** [comment]
## Windows support is here! Celebrate with us at https://github.com/ipfs/js-ipfs/issues/1017#issuecomment-343568369
