### ISSUE TITLE
Npm package js-ipfs doesn't work on Safari.

### ISSUE THREAD

**Issue by alexsicart** [ipfs/js-ipfs#1035]
- **Version**: Safari Versión 11.0 (13604.1.38.1.6)
- **Platform**: Mac OSx

#### Severity:
  Critical - System crash, application panic.

#### Description:
WebKitSubtleCrypto is deprecated. Please use SubtleCrypto instead.
<img width="719" alt="captura de pantalla 2017-10-07 a las 23 47 46" src="https://user-images.githubusercontent.com/20609184/31312048-fc4b0d84-abb9-11e7-9b84-a939e2d0f5f4.png">

https://decentralized.cloud/ works on Chrome perfectly, but on Safari, displays a white page for some packages, js-ipfs needs. 

#### Steps to reproduce the error:
Going to https://decentralized.cloud/, opening the console.

**Comment by VictorBjelkholm** [comment]
Thanks for the report! We have a issue for Safari support already ( https://github.com/ipfs/js-ipfs/issues/995 ). Will close this one so we can track all that work in one place.

**Comment by diasdavid** [comment]
Safari support is here now! https://github.com/ipfs/js-ipfs/issues/995#issuecomment-341693735
