### ISSUE TITLE
Unable to install js-ipfs --> Windows, Webstorm

### ISSUE THREAD

**Issue by JonasDev99** [ipfs/js-ipfs#1037]
- **Version**:
0.26.0
- **Platform**:
Windows
- **IDE**:
Webstorm

#### Type:
Bug
#### Severity:
Low
#### Description:
Installing ipfs worked but this error appeared:

> C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install ipfs
> 
> Standard error:
> npm WARN deprecated ipld-eth-star@1.4.1: deprecated in favor of js-ipld-ethereum https://github.com/ipld/js-ipld-ethereum
> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
> npm WARN lifecycle npm is using C:\Program Files\nodejs\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@1.0.0 (node_modules\fs-ext):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@1.0.0 install: `node-gyp configure build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.0.2 (node_modules\gc-stats):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.0.2 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! leveldown@1.9.0 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the leveldown@1.9.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Jonas\AppData\Roaming\npm-cache\_logs\2017-10-11T15_58_12_138Z-debug.log
> 
> 
> Standard output:
> 
> > fs-ext@1.0.0 install C:\Users\Jonas\WebstormProjects\untitled\node_modules\fs-ext
> > node-gyp configure build
> 
> 
> C:\Users\Jonas\WebstormProjects\untitled\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build ) 
> 
> > gc-stats@1.0.2 install C:\Users\Jonas\WebstormProjects\untitled\node_modules\gc-stats
> > node-pre-gyp install --fallback-to-build
> 
> 
> > keccak@1.3.0 install C:\Users\Jonas\WebstormProjects\untitled\node_modules\keccak
> > prebuild-install || node-gyp rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."
> 
> 
> C:\Users\Jonas\WebstormProjects\untitled\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
> "Keccak bindings compilation fail. Pure JS implementation will be used."
> 
> > leveldown@1.9.0 install C:\Users\Jonas\WebstormProjects\untitled\node_modules\leveldown
> > prebuild-install || node-gyp rebuild
> 
> 
> C:\Users\Jonas\WebstormProjects\untitled\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
> 
> 
> Process finished with exit code 1

#### Steps to reproduce the error:
Creating a express project in Webstorm 2017.
Installing ipfs via package.json or npm package manager.

**Comment by diasdavid** [comment]
See #1017

**Comment by barnendu** [comment]
I had same issue, jsipfs was giving me error while installing. Its has been solved after using
npm install --global --production windows-build-tools in windows 10 run power shell has admin. Then 
run  npm install ipfs --global
