### ISSUE TITLE
Please add to browser example how to "put" Blobs with filename 

### ISSUE THREAD

**Issue by muksihs** [ipfs/js-ipfs#1053]
Please add to browser example how to  "put" several Javascript data Blobs with filename sequentially with a final hash that represents a folder containing all the Blobs put.
Thanks!

**Comment by diasdavid** [comment]
@muksihs wanna try to give it a stab with the latest Files API? See docs here https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md

**Comment by diasdavid** [comment]
@muksihs, @achingbrain just shipped an example with exactly what you were looking for :) Check it out at https://github.com/ipfs/js-ipfs/tree/master/examples/browser-add-readable-stream
