### ISSUE TITLE
Repo interop tests failing due to different repo versions

### ISSUE THREAD

**Issue by dryajov** [ipfs/js-ipfs#1059]
- **Version**: latest master
- **Platform**: Mac OS/Linux
- **Subsystem**: 

#### Steps to reproduce the error: `npm run test:interop`

<img width="910" alt="screen shot 2017-11-05 at 3 18 29 pm" src="https://user-images.githubusercontent.com/1094341/32420301-acf0738e-c23c-11e7-91da-6477c5f46b4c.png">

**Comment by diasdavid** [comment]
@dryajov you should be able to update the repo version in js-ipfs-repo
