### ISSUE TITLE
Impl the http endpoints and cli cmds for PubSub

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#1068]
https://github.com/ipfs/js-ipfs/pull/610 never really added support for PubSub to the http-api and the cli, just for core. 

We do have tests and the impl is underway which should make things easier for someone to pick it up. To try it out you can  enable these tests:

- https://github.com/ipfs/js-ipfs/blob/master/test/http-api/spec/pubsub.js
- https://github.com/ipfs/js-ipfs/blob/master/test/http-api/interface/pubsub.js
- https://github.com/ipfs/js-ipfs/blob/master/test/cli/pubsub.js

**Comment by richardschneider** [comment]
@diasdavid There are incompatibilities between `go` and `js` in the published message that is sent by `pubsub publish`.

- js has renamed the field `topicIDs` to `topicCIDs`
- js encodes the field `from` in base58 whereas `go` uses base64

See the [code](https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/index.js#L262) in `libp2p-floodsub`.

**Comment by richardschneider** [comment]
Note that none of the above tests check a published message.

Also the test for [pubsub ls](https://github.com/ipfs/js-ipfs/blob/master/test/http-api/spec/pubsub.js#L98) is skipped.

**Comment by richardschneider** [comment]
Changes will have to be made
- [ ] [flood-sub](https://github.com/libp2p/js-libp2p-floodsub)
- [ ] [ipfs](https://github.com/ipfs/js-ipfs)

**Comment by diasdavid** [comment]
@richardschneider great catch!

- https://github.com/libp2p/go-floodsub/blob/master/pb/rpc.proto
- https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/message/rpc.proto.js

No idea how did this happen. This will be a breaking change. Wanna ship it in time for js-ipfs 0.27? An interop test would also be welcome

**Comment by richardschneider** [comment]
Working on changes now.  when is js-ipfs 0.27 scheduled to ship.

**Comment by diasdavid** [comment]
@richardschneider once I finish https://github.com/ipfs/interface-ipfs-core/pull/162 which should be this week (so releasing next week)

**Comment by richardschneider** [comment]
No worries, will have changes in tonight/tomorrow.

Will the release include `jsipfs files ls ...`?

**Comment by diasdavid** [comment]
@richardschneider it will :)

**Comment by richardschneider** [comment]
@diasdavid I need [PR 49](https://github.com/libp2p/js-libp2p-floodsub/pull/49) reviewed and released before I begin the tasks.

**Comment by diasdavid** [comment]
@richardschneider you should be able to `npm link` to do more testing. To make sure that all bugs are detected, could you add some interop tests for pubsub as well? Thank you!

**Comment by richardschneider** [comment]
Yes, adding/changing tests in `interface-ipfs-code`.

I don't use `npm link`, will read up on it.  Typically, use `npm install` to the github branch for testing other packages that are net yet ready for prime time.

But to run these tests, I need to use `js-ipfs`; which somewhere in the DLL hell uses `libp2p-fload-sub`.

**Comment by diasdavid** [comment]
@richardschneider you should not need to change tests in interface-ipfs-core for interop, you should just to add some to this set https://github.com/ipfs/js-ipfs/tree/master/test/interop, they are run with https://github.com/ipfs/js-ipfs/blob/master/package.json#L36

**Comment by richardschneider** [comment]
`interface-ipfs-core` is WRONG. I'm making test changes to interface-ipfs-core because its checking for the wrong published message field name.

see https://github.com/ipfs/interface-ipfs-core/commit/e750afe4fa61facd52fb15a7d54ca0be551c3044

**Comment by diasdavid** [comment]
Understood! :)

**Comment by richardschneider** [comment]
@diasdavid I think pubsub is truely broken.  I enabled https://github.com/ipfs/js-ipfs/blob/master/test/http-api/interface/pubsub.js and most tests fail.

**Comment by richardschneider** [comment]
After a few hours, pubsub is NOT broken. The tests need to enable the pubsub experiment.
