### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs#1074]
When building many packages, the compile of SHA3 produces the following errors
```
C:\projects\js-ipfsd-ctl\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cpp
  displayIntermediateValues.cpp
  KeccakF-1600-reference.cpp
  KeccakNISTInterface.cpp
  KeccakSponge.cpp
  win_delay_load_hook.cc
..\src\addon.cpp(49): warning C4316: 'SHA3Hash': object allocated on the heap may not be aligned 32 [C:\projects\js-ipfsd-ctl\node_modules\sha3\build\sha3.vcxproj]
..\src\addon.cpp(59): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\projects\js-ipfsd-ctl\node_modules\sha3\build\sha3.vcxproj]
  c:\users\appveyor\.node-gyp\6.11.5\include\node\v8.h(3272): note: see declaration of 'v8::Function::NewInstance'
     Creating library C:\projects\js-ipfsd-ctl\node_modules\sha3\build\Release\sha3.lib and object C:\projects\js-ipfsd-ctl\node_modules\sha3\build\Release\sha3.exp
  Generating code
  Finished generating code
  sha3.vcxproj -> C:\projects\js-ipfsd-ctl\node_modules\sha3\build\Release\\sha3.node
  sha3.vcxproj -> C:\projects\js-ipfsd-ctl\node_modules\sha3\build\Release\sha3.pdb (Full PDB)
```
See [this](https://stackoverflow.com/questions/20104815/warning-c4316-object-allocated-on-the-heap-may-not-be-aligned-16) for `C4316`

**Comment by dryajov** [comment]
There seem to be a fix for the deprecated `NewInstance` referenced here - https://github.com/phusion/node-sha3/issues/29, tho there doesn't seem to be a PR yet.

**Comment by dryajov** [comment]
This seems relevant to the misalignment issue - https://github.com/g-truc/glm/issues/235.

**Comment by richardschneider** [comment]
@dryajov @whyrusleeping Should we even be using this library.  This is a [Kecccak](https://github.com/phusion/node-sha3/issues/14) implementation and not NIST SHA-3.

What does GO use?

**Comment by whyrusleeping** [comment]
@richardschneider take it up with the ethereum devs. They decided to use keccak-that-isnt-actually-sha3

**Comment by diasdavid** [comment]
@richardschneider that module uses a native dep by default and a fallback to pure JS if the native dep fails. You should be fine running this on Windows, although if the native dep compiled it would be faster.

**Comment by richardschneider** [comment]
@diasdavid It would be nice to get a version that compiles cleanly. SHA3 (really keccak) doesn't seem to be actively maintained.  Perhaps we should fork.

**Comment by richardschneider** [comment]
Another approach is to remove the dependency on `sha3` and use https://github.com/cryptocoinjs/keccak.  It supports keccak, sha3 and blake.  It also supports 'pure JS' when running in the browser.

**Comment by diasdavid** [comment]
@richardschneider is keccak really a issue here? It should default to a JS implementation. 

Once https://github.com/ipfs/js-ipfs/pull/1103 is complete, everything should be _proven_ fine :)
