### ISSUE TITLE
Tests on Windows

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs#1075]
The path `/tmp/...` does not exist on windows. Use `path.join(os.tmpdir(), '...')`.

See some [possible bad tests](https://github.com/ipfs/js-ipfs/search?q=tmp&type=Code&utf8=%E2%9C%93)

**Comment by diasdavid** [comment]
@richardschneider Now that you pushed Windows support, do you want to share an update here on your plans to fix the tests to make sure Appveyor is happy?

**Comment by richardschneider** [comment]
First, I'll change all tests not to use `/tmp/...`.

Next change is harder.  It seems that NPM likes to randomly throw EPERM every now and then.  I've even seen it once or twice on my local machine.

According to https://github.com/Medium/phantomjs/issues/19 it may be Windows Anti-Virus software; which I consider a virus in itself.

**Comment by richardschneider** [comment]
Also https://github.com/npm/npm/issues/18380#issuecomment-326813399 suggests downgrading  NPM

**Comment by richardschneider** [comment]
@VictorBjelkholm have you seen any of these EPERM errors on Jenkins Windows build?

**Comment by VictorBjelkholm** [comment]
@richardschneider yes indeed I've seen those errors that happened every once in a while. The only reliable solution I've found is to turn off real time protection in Windows Defender. 

In Powershell, you can disable it like this:

https://github.com/ipfs/jenkins/blob/a73cb56893a80427ce0e87601ef1dcb8326222f0/worker/main.tf#L220

**Comment by VictorBjelkholm** [comment]
For the record, ended up going with Yarn as it handles concurrent installs better than npm. But, got those errors with Yarn as well, unless turning off the real-time protection.

**Comment by diasdavid** [comment]
Lot's of work happening on https://github.com/ipfs/js-ipfs/pull/1103
