### ISSUE TITLE
Promisify stop()?

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#1076]
We currently return from `stop()` with a [callback](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/stop.js#L5).

In order to stop IPFS properly, we write:
```javascript
ipfs.stop(() => {
// do other shutdown things
})
```

I find myself often preferring to use Promises and more recently await. As per IPFS api functions, we return a Promise (or callback) and I find it confusing that `stop()` is only callback.

If we returned a Promise, we would write:
```javascript
ipfs.stop().then(() => {
// do other shutdown things
})

// Or:
await ipfs.stop()
// do other shutdown things
```

**I'd like to propose we promisify the stop function.**

We would keep the original callback in addition to returning a Promise, same as we do for [API functions](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/files.js#L63) and the [start()](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js#L10) function.

How does everyone feel about this?

I'd be happy to PR this, but this would be a great task for **first contributors** if someone wants to work on it!

**Comment by mitra42** [comment]
Absolutely - the functions with only callbacks add substantial weirdness to building anything on top of it.  (Block.get and Block.put are two others that I have to promisify in my code).

**Comment by diasdavid** [comment]
@haadcode sounds good! Seems that we missed that one. Wanna submit that as a PR?

**Comment by diasdavid** [comment]
@mitra42 just noticed that indeed block.get and block.put are not promisified, wanna add a PR with that? https://github.com/ipfs/js-ipfs/blob/master/src/core/components/block.js#L11-L15

**Comment by mitra42** [comment]
All we are doing is 
```
    _makepromises() {
        this.promisified = { ipfs: { block: {
            put: promisify(this.ipfs.block.put),
            get: promisify(this.ipfs.block.get)
        }}}
    }
```
Then call 
```
await this.promisified.ipfs.block.get(cid)
```
as part of the workaround to the bug in https://github.com/ipfs/js-ipfs/issues/1049
Which i don't think is what you want for a PR. 

Anyway ... I haven't done any PRs for IPFS because given all the multiple repositories etc I have zero confidence in finding accurate docs to do the full cycle - clone; edit; test; submit PR.

**Comment by haadcode** [comment]
PR for promisifying stop is here https://github.com/ipfs/js-ipfs/pull/1082. cc @diasdavid

**Comment by haadcode** [comment]
@mitra42 @diasdavid I went ahead and PRed the promisified block functions here https://github.com/ipfs/js-ipfs/pull/1085. We also need updated tests from https://github.com/ipfs/interface-ipfs-core/pull/170 to merge it.

**Comment by diasdavid** [comment]
thank you so much @haadcode 🌟

@mitra42 if you happen to have the intention to try, I'm happy to provide you pointers and help when you get blocked. Right now, you can check how @haadcode submitted this PRs so that you can learn what was necessary.
