### ISSUE TITLE
'jsipfs ls' subfolders

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs#1079]
`jsipfs ls` is not processing a path with a sub-folder.  Compare the outputs from js and go

```
>node src\cli\bin.js ls /ipfs/QmRCJXG7HSmprrYwDrK1GctXHgbV7EYpVcJPQPwevoQuqF/test
QmNtpA5TBNqHrKf3cLQ1AiUKXiE4JmUodbG5gXrajg8wdv 277 test/

>ipfs ls /ipfs/QmRCJXG7HSmprrYwDrK1GctXHgbV7EYpVcJPQPwevoQuqF/test
QmTz3oc4gdpRMKP2sdGUPZTAGRngqjsi99BPoztyP53JMM 12  bar
QmX1ebVUtfY11ZCpVmqyE5mDoN62SpLd8eLPpg5GGV1ABt 114 baz/
QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6 12  foo
```

Detected in https://github.com/ipfs/js-ipfs/pull/1078

**Comment by richardschneider** [comment]
I think the problem is [here](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/files.js#L130)
```
        exporter(ipfsPath, self._ipldResolver, { maxDepth: 1 }),
        pull.filter((node) => node.depth === 1),
```
Instead of `1` use the number of components in `ipfsPath`, excluding the optional `/ipfs/`

**Comment by diasdavid** [comment]
thanks for the report @richardschneider. @pgte mind looking into this?
