### ISSUE TITLE
Event Log Endpoint

### ISSUE THREAD

**Issue by frrist** [ipfs/js-ipfs#1099]
**I would like to propose adding an event log endpoint.**

Currently `go-ipfs` supports event logging at the endpoint: `api/v0/log/tail`. Services like `ipfs-metrics` make use of this to gather metrics about events occurring in the different systems of ipfs. 

https://ipfs.io/docs/api/#apiv0logtail

Ideally the event logs will be easy to add (as it is not imminently clear where they need to be placed in the code), in json format, and contain the following:
  - `time`
    - when the event occurred
  - `system`
    - System responsible for the event, e.g. `DHT`
  - `event`
    - The name of the event, e.g. `getClosestPeers`
  - `duration`
    - Time since the event was created.
    - Similar to [EventBegin in go-log](https://github.com/ipfs/go-log/blob/master/log.go#L83)
  - `requestId`
    - based on the event context, e.g. all events created from the command `jsipfs add` contain this ID
  - `subsystem`
    - If applicable
  - Logging Metadata (K,V)
    - i.e. errors if the event was unsuccessful, CID of data being fetch
    - Similar to the interface implemented by [go-log](https://github.com/ipfs/go-log/blob/master/metadata.go)

What does everyone think?

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Helia does not follow the Kubo API so this endpoint will not be implemented.

To call the same endpoints on Kubo you should switch out `ipfs-http-client` for `kubo-rpc-client`.

Similar metrics can be extracted from libp2p directly by configuring a metrics implementation such as `@libp2p/prometheus-metrics`.
