### ISSUE TITLE
Submodule Structure

### ISSUE THREAD

**Issue by mappum** [ipfs/js-ipfs#11]
I understand you want to modularize the project, but breaking up into a huge tree of git submodules is a little insane. Node already uses a module system by default, so we can put the same module structure you designed into directories. Each one as its own repo just makes the project a pain to maintain and to contribute to. If we move the modules into directories we will barely need to change the code, since the modules can still be loaded via `require`.

There are projects with similar scope/size, and they all work great with the standard Node way of organizing modules. (E.g. [Dat](https://github.com/maxogden/dat), which I know you've contributed to).

Overall, the current structure adds painful management overhead, will likely scare off contributors, and doesn't provide anything over the built-in Node module system. Should I go ahead and refactor?

**Comment by Latrasis** [comment]
Hey Guys, is this the official repo? If so i'd be happy to help on reformatting to a more npm friendly structure. No git submodule voodoo magic.

There's two ways: 

Seperate Repo way:
1. Get rid of git submodules, don't need them.
2. Seperate each submodule to a seperate repo and register to the npm registry.
3. Then have node-ipfs as a seperate repo that fetches each module in package.json from npm.

Simple file.js Way:
1. Get rid of git submodules, don't need them.
2. Remove File List: /ipts-* to ipfs.js and rename submodules to lib
3. Have just one package.json in index and have all node_modules automatically installed.

If you guys want to look at good example of a npm formats i know:
https://github.com/feross/webtorrent
https://github.com/sintaxi/surge
https://github.com/sintaxi/harp

Good Resources:
https://docs.npmjs.com/getting-started/creating-node-modules
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by Latrasis** [comment]
In terms of a README alternative, using github's wiki is a good option.

**Comment by diasdavid** [comment]
Going to close this issue as it respects to the (waay waay) old js-ipfs :) 

@Latrasis if you have free cycles to help ship js-ipfs, join the :ship: ! :D
