### ISSUE TITLE
Problems with  ipfs-101/i.js

### ISSUE THREAD

**Issue by kidinamoto01** [ipfs/js-ipfs#1110]
- **Version**: 0.26
- **Platform**: macOS
- **Subsystem**:

#### Description:

I tested 1.js, but found out the content cannot be retrieved. 
` process.stdout(data)` should be `process.stdout.write(data)`
then 
`File content:
net.js:695
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:695:11)
    at node.files.cat (/Users/b/Documents/ipfs-wp/1.js:30:20))`
#### Steps to reproduce the error:

node 1.js

**Comment by diasdavid** [comment]
Hi @kidinamoto01, the example is already prepared for the next version release and you are probably installing ipfs 0.26.0. Once #1095 is done you won't see this problem anymore. Otherwise, try do a `npm link`at the root of the js-ipfs folder to get the latest as global.

**Comment by diasdavid** [comment]
Hi @kidinamoto01, fixed this example with https://github.com/ipfs/js-ipfs/pull/1112, you shouldn't have any trouble anymore :) just fetch the latest commit
