### ISSUE TITLE
FAQ: pubsub, peers in the same room name served by different http servers.  

### ISSUE THREAD

**Issue by shd101wyy** [ipfs/js-ipfs#1118]
Hi there,

I watched [this youtube video](https://www.youtube.com/watch?v=Nv_Teb--1zg) and the `pubsub` feature looks fascinating. 

A user asked the following question, which I am also very curious:

> If multiple http-servers are offering this application (using the same room name), will the peers be able to chat all together in the same room?﻿

So what is the answer?

Thank you

**Comment by pgte** [comment]
Yes, they will be able to see each-others messages if they’re on the same channel.

**Comment by shd101wyy** [comment]
Thank you!
