### ISSUE TITLE
Docs: Explain that "Interval" value in MDNS config options is seconds

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#1123]
Not sure where to do this, but we should document the MDNS "Interval" option that it is in seconds. I've always thought it's milliseconds:
https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/config-nodejs.json#L13

Would be happy to PR this if someone can tell where we should do this :)

**Comment by deltab** [comment]
How about including it in the name, as "IntervalSeconds"?

**Comment by achingbrain** [comment]
This is documented as being in seconds - https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md#mdns
