### ISSUE TITLE
Node security

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs#1128]
The CI build is reporting [12 vulnerabilities found](https://nodesecurity.io/orgs/ipfs/projects/f983c9d5-424b-436a-ae6f-733dddb9ad08/1126).  They are all `Sandbox Breakout` and come from `protons@1.0.0 > brfs@1.4.3 > static-module@1.5.0 > static-eval@0.2.4`.

The recommendation is to upgrade  `static-module` to v2.0.0 or later
> dependency updates, most notably static-eval to v2.0.0 which fixes a security vulnerability.

**Comment by richardschneider** [comment]
There's a [PR](https://github.com/browserify/brfs/pull/83) to upgrade `bfrs` to the latest version of `static-module`.  It's build is failing!

**Comment by richardschneider** [comment]
Once `brfs` is upgraded, then `protons` should be upgraded.  All dependents (bitswap, unixfs, ...) should be upgraded.  Or make the new `protons` version just a patch (1.0.1) and dependents will just get it.

**Comment by richardschneider** [comment]
It appears that https://github.com/dignifiedquire/protons/pull/3 will remove `bfrs` from `protons` and then all the security notifications will be resolved.

@dignifiedquire @thisconnect can we get some progress on the PR?

**Comment by diasdavid** [comment]
Seems that everything is ready, @dignifiedquire just needs to merge and release :)

**Comment by diasdavid** [comment]
Back to green

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1211152/33739724-12dd609a-db96-11e7-8926-2a755186c37a.png">

@richardschneider thanks for pushing on this one :)
