### ISSUE TITLE
jsipfs cat on a directory not working correctly

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1142]
- **Version**: 0.27.3
- **Platform**: macOS 10.13.1
- **Subsystem**: files

#### Type:
Bug

#### Severity:
High

#### Description:
`ipfs cat` on a directory displays the contents of a file in a sub directory, not the error "this dag node is a directory"

#### Steps to reproduce the error:

```sh
$ jsipfs init
initializing ipfs node at /Users/alan/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmU8eJXWVYudzSrV5fxQuptmK1haqMG6E1eKP47xuF4e1K
to get started, enter:

	 jsipfs files cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme
```
lets cat that directory:
```sh
$ jsipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr
WIP

# 0.0 - Introduction

Welcome to IPFS! This tour will guide you through a few of the
features of this tool, and the most common commands. Then, it will
immerse you into the world of merkledags and the amazing things
you can do with them.

...
```
Wait, I was expecting some sort of directory error...
```sh
$ ipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr
Error: this dag node is a directory
```
...yeah like that
```sh
$ ipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/tour/0.0-intro
WIP

# 0.0 - Introduction

Welcome to IPFS! This tour will guide you through a few of the
features of this tool, and the most common commands. Then, it will
immerse you into the world of merkledags and the amazing things
you can do with them.

...
```
weirdness, it is displaying a file in a sub folder...

**Comment by diasdavid** [comment]
This is an issue on js-ipfs-unixfs-engine. @pgte is this something you could take a look? Also, let's make sure to add a test to interface-ipfs-core.

**Comment by pgte** [comment]
On it.

**Comment by pgte** [comment]
Tests here: https://github.com/ipfs/interface-ipfs-core/pull/182

**Comment by diasdavid** [comment]
@alanshaw test out `js-ipfs 0.27.4`  and let me know how it goes :)

**Comment by alanshaw** [comment]
I'm getting `Uncaught TypeError: Cannot read property ‘content’ of undefined` when `ipfs.files.cat` on a directory now.

<img width="1392" alt="screen shot 2017-12-14 at 11 35 24" src="https://user-images.githubusercontent.com/152863/33990642-9afb3f42-e0c3-11e7-88ea-85a0fbd552f4.png">

**Comment by Usman-Qasim** [comment]
ipfs cat /ipfs/QmeZZkwN****zNgz38RBhH***xmbCLH8UoUGQ*****6fcERe
Error: this dag node is a directory

Can someone tell me how to solve this issue?

    let file = fs.readFileSync(path);
    let varr = { path: path, content: file };
    let fileAdded = await ipfs.add(varr);
    let fileHash = fileAdded.cid;

**Comment by Usman-Qasim** [comment]
> ipfs cat /ipfs/QmeZZkwN*_**zNgz38RBhH**_xmbCLH8UoUGQ*****6fcERe
> Error: this dag node is a directory
> 
> Can someone tell me how to solve this issue?
> 
> ```
> let file = fs.readFileSync(path);
> let varr = { path: path, content: file };
> let fileAdded = await ipfs.add(varr);
> let fileHash = fileAdded.cid;
> ```

ipfs cat /ipfs/QmeZZkwN*zNgz38RBhHxmbCLH8UoUGQ*****6fcERe/fileName.extenstion
