### ISSUE TITLE
Browser peer can't connect to Node.js peer

### ISSUE THREAD

**Issue by jyang** [ipfs/js-ipfs#1149]
- **Version**: 0.27.3
- **Platform**: Linux
- **Subsystem**:

#### Description:

I am running js-ipfs in two peers: one runs the Node.js version and the other the browser version.

**The Node.js version** is installed by ``npm install -g ipfs``. I added the following to ``Addresses.Swarm`` in ``~/.jsipfs/config``:
```
"/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star"
```
Then I started it with ``jsipfs daemon``, which shows addresses that include this one:
```
/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/ipfs/QmbDZ6adneKWnPn57rUnR26TJbHTZwdZ7CkH4pcSW4fVEH
```
**The browser version** is using the example [exchange-files-in-browser](https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser) whose ``public/js/app.js`` includes the WebRTC multiaddress above. When it's started it shows its id as ``QmSAt1pnh4BajEXDUMWnkEWQDo4g5HPfP8jwnC5fMcnTUj``.

Now I can do the following to let the Node.js peer connect to the browser peer:
```
jsipfs id QmSAt1pnh4BajEXDUMWnkEWQDo4g5HPfP8jwnC5fMcnTUj
```
I can see the browser peer's id info.

But then if I add the Node.js peer's address to the browser peer, I get this error:
```
Error: Could not dial in any of the transports or relays
    at dialCircuit (http://127.0.0.1:12345/js/bundle.js:59677:25)
    at dialCircuit (http://127.0.0.1:12345/js/bundle.js:59719:16)
    at nextTransport (http://127.0.0.1:12345/js/bundle.js:59675:18)
    at swarm.transport.dial (http://127.0.0.1:12345/js/bundle.js:59687:20)
    ...
```

#### Steps to reproduce the error:

See description above.

**Comment by jyang** [comment]
Today I tried to reproduce the bug and found that this step above:
```
jsipfs id QmSAt1pnh4BajEXDUMWnkEWQDo4g5HPfP8jwnC5fMcnTUj
```
always prints out the id of the current node running locally, not the remote node whose id is given there, unlike the go-ipfs version. So the connectivity from a Node.js peer to a browser peer is also not verified.

**Comment by diasdavid** [comment]
Hi @jyang, did you happen to find this item on the FAQ https://github.com/ipfs/js-ipfs#is-there-webrtc-support-for-js-ipfs-with-nodejs ?

**Comment by jyang** [comment]
@diasdavid Yes, David, I am aware of that item in the FAQ. But I am not using any code to create my node. I simply did ``jsipfs init``, added ``p2p-webrtc-star`` to ``~/.jsipfs/config`` and then ``jsipfs daemon`` to create my node. Is doing it this way supposed to work with the WebRTC transport?

**Comment by diasdavid** [comment]
@jyang I pointed you to the FAQ because you can find [Is there WebRTC support for js-ipfs with Node.js?](https://github.com/ipfs/js-ipfs#is-there-webrtc-support-for-js-ipfs-with-nodejs), tl;dr; you have to install an extra module, it will be unstable though as there is currently no WebRTC implementation available outside of the Browser that is stable.

**Comment by jyang** [comment]
@diasdavid Thanks, David. I'd really like the browser peer to work. So one path is to add support for saving  files in the file system rather than IndexedDB (which has various limitations). The "server" side browser can run in headless mode. What do you think?

This bug can be marked as a duplicate of WebRTC being unreliable for Node.js peer. Or I can simply close it.

**Comment by diasdavid** [comment]
Have you tried the next alternative? [Is there a more stable alternative to webrtc-star that offers a similar functionality?](https://github.com/ipfs/js-ipfs#is-there-a-more-stable-alternative-to-webrtc-star-that-offers-a-similar-functionality)

Also, good news, when things like #1063 Circuit Relay ship, you won't have to worry about these details :)

**Comment by jyang** [comment]
Bandwidth requirement between my peers is high. Relaying means the data will go through it and not only the signalling part, right? Then it probably won't work for me too well. Thanks for your suggestion!
