### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by paralin** [ipfs/js-ipfs#1166]
Are there TypeScript typings written for this module, and if not, can we write / include them in the js-ipfs repo?

**Comment by survirtual** [comment]
Here are some unofficial typings: [https://github.com/survirtual/types-ipfs](https://github.com/survirtual/types-ipfs)

Feel free to contribute as needed :)

Would also be interested in seeing an officially supported version.

**Comment by roo2** [comment]
I'm looking into these at the moment and will update this comment if I can get them working without issues https://github.com/zabirauf/ipfs-types

**Comment by GrandSchtroumpf** [comment]
hi, any news on this topic since?

**Comment by vishalkuo** [comment]
There's been a [long chain of forking going on for ipfs types](https://github.com/vishalkuo/types-ipfs) as most repos go unmaintained. Would you be willing to accept a PR into this repo and have one centralized, visible, location to expose this?

**Comment by beenotung** [comment]
I would appreciate if someone can help to put https://github.com/beenotung/typestub-ipfs into https://github.com/DefinitelyTyped/DefinitelyTyped, their setting is quite complicated to me.

If ipfs can put the .d.ts along with .js, that will be even greater as it should be most updated.

**Comment by wlegate** [comment]
> I would appreciate if someone can help to put https://github.com/beenotung/typestub-ipfs into https://github.com/DefinitelyTyped/DefinitelyTyped, their setting is quite complicated to me.
> 
> If ipfs can put the .d.ts along with .js, that will be even greater as it should be most updated.

I'd be interested in helping out on this if IPFS isn't going to add typings to this repo

**Comment by carsonfarmer** [comment]
I'd just like to bump this one a bit. I'd be happy to help maintain the definitions if someone wants to merge https://github.com/beenotung/typestub-ipfs into `js-ipfs`? I think that's better than adding to DefinitelyTyped...

**Comment by andylim0221** [comment]
Is there anyone working on with this? Woud like to help out on maintaining this too

**Comment by bluelovers** [comment]
https://github.com/bluelovers/ws-ipfs/tree/master/packages/ipfs-types

**Comment by achingbrain** [comment]
This has shipped with `0.51.0`!

**Comment by achingbrain** [comment]
See the tracking issue: #2945
