### ISSUE TITLE
ipfs.stop leaves process hanging

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1168]
- **Version**: 0.27.5
- **Platform**: Node.js
- **Subsystem**: n/a

#### Type:
Bug

#### Severity:
High

#### Description:
`ipfs.stop(cb)` calls `cb` but does not completely stop the node.

[`wtfnode`](https://www.npmjs.com/package/wtfnode) says that the following interval is still active:

```
- Intervals:
  - (3600000 ~ 60 min) (anonymous) @ /Users/alan/Code/protocol-labs/ipfs-postmsg-proxy/node_modules/libp2p-kad-dht/src/providers.js:203
```

Note `libp2p-kad-dht/src/providers.js:203` sets up a function to "cleanup" every hour, but this cannot be canceled.

#### Steps to reproduce the error:
Create a new js-ipfs instance and call `stop`, your Node.js process will not exit.

**Comment by VictorBjelkholm** [comment]
I think I've seen this a couple of times in the test, as aegir refuses to completely exit after finishing running all the tests.

**Comment by VictorBjelkholm** [comment]
Code for reproducing (should be testing with lots of different configs though, as the kad-dht issue doesn't show up with default config):

```
const wtfnode = require('wtfnode')
const ipfs = require('./src/core')

const node = new ipfs()

node.on('ready', () => {
  console.log('node ready, stopping in five seconds')
  setTimeout(node.stop, 5000)
})

node.on('stop', () => {
  console.log('node stopped')
  setTimeout(wtfnode.dump, 1000)
})
```

**Comment by diasdavid** [comment]
@VictorBjelkholm try using `.once`, otherwise, those event listeners will never cleared

**Comment by VictorBjelkholm** [comment]
@diasdavid hm, seemed to work fine after fixing https://github.com/libp2p/js-libp2p-mdns/pull/63, the event listener doesn't show up and the process exists successfully.

```
➜  js-ipfs git:(master) ✗ node forever2.js
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmcVAXh8piydnLxZB67fTuhQuaWCWvJf9HPTix2wnirv8V
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmcVAXh8piydnLxZB67fTuhQuaWCWvJf9HPTix2wnirv8V
Swarm listening on /ip4/10.0.13.14/tcp/4002/ipfs/QmcVAXh8piydnLxZB67fTuhQuaWCWvJf9HPTix2wnirv8V
node ready, stopping in five seconds
node stopped
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Timers:
  - (2000 ~ 2 s) (anonymous) @ /home/user/projects/ipfs/js-ipfs/node_modules/libp2p-tcp/src/listener.js:64
```

**Comment by alanshaw** [comment]
Is there something I can test out to help?

**Comment by alanshaw** [comment]
Script to reproduce:

```js
const wtf = require('wtfnode')
const IPFS = require('ipfs')

console.log('IPFS node starting')

const node = new IPFS({
  init: { bits: 1024 },
  config: {
    Addresses: {
      Swarm: [
        '/ip4/127.0.0.1/tcp/0'
      ],
      API: '/ip4/127.0.0.1/tcp/0',
      Gateway: '/ip4/127.0.0.1/tcp/0'
    },
    Version: {
      Current: 'jsipfs-dev',
      Check: 'error',
      CheckDate: '0001-01-01T00:00:00Z',
      CheckPeriod: '172800000000000',
      AutoUpdate: 'minor'
    },
    Discovery: {
      MDNS: {
        Enabled: false,
        Interval: 10
      },
      webRTCStar: {
        Enabled: false
      }
    },
    Bootstrap: [],
    API: {
      HTTPHeaders: null
    }
  },
  EXPERIMENTAL: {
    pubsub: true,
    dht: true
  }
})

node.once('ready', () => {
  console.log('IPFS node ready')
  node.stop(() => {
    console.log('IPFS node stopped')
    setTimeout(() => wtf.dump(), 5000)
  })
})

/*
OUTPUT:

IPFS node starting
Swarm listening on /ip4/127.0.0.1/tcp/49645/ipfs/QmU8eJXWVYudzSrV5fxQuptmK1haqMG6E1eKP47xuF4e1K
IPFS node ready
IPFS node stopped
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Intervals:
  - (3600000 ~ 60 min) (anonymous) @ /Users/alan/Desktop/test/node_modules/libp2p-kad-dht/src/providers.js:203
  */
```

**Comment by sagivo** [comment]
having the same issue here.

**Comment by dryajov** [comment]
@alanshaw I believe you have to call `process.exit()` yourself as stop only stops the in-process daemon, but doesn't exit the process itself - https://github.com/ipfs/js-ipfs/blob/master/src/core/components/stop.js

**Comment by richardschneider** [comment]
@dryajov  Should **not** have to call `process.exit()`, as node will exit when there is nothing on the event loop,

**Comment by sagivo** [comment]
yeah, calling exit is not a good solution.

**Comment by dryajov** [comment]
good point @richardschneider @sagivo

**Comment by richardschneider** [comment]
@diasdavid Need to release `js-libp2p-mdns` to NPM and then update deps in `js-ipfs`.

**Comment by richardschneider** [comment]
Did a search of all `libp2p repos` for `setInterval` and it looks like they all `clearInterval`!

**Comment by diasdavid** [comment]
@richardschneider released libp2p-mdns as patch release. You should get it on your next fresh npm install

**Comment by alanshaw** [comment]
Fixes the issue for me also, thanks @richardschneider

**Comment by sagivo** [comment]
yep, looking good

**Comment by mitra42** [comment]
I'm seeing ipfs.stop() never calling its callback. I notice the examples above use event listeners, but the API defines it as having a callback . Should that be a new issue, or does it look like this one needs reopening ?

**Comment by alanshaw** [comment]
New issue please @mitra42 😄 - please could you provide reproducable example code? Its the stop even emitted but not the callback called? Also please could you provide JS IPFS version and config you're using?

**Comment by mitra42** [comment]
Ok detailed new issue at #1806
I don't know if the stop event is emitted - I'm not using event listeners,
