### ISSUE TITLE
How can I make a service on windows?

### ISSUE THREAD

**Issue by haroldTlan** [ipfs/js-ipfs#1177]
I am run jsipfs in ubuntu.
version:0.27.7.
I want to make an minimum EXE on windows.
What should I do?

**Comment by diasdavid** [comment]
js-ipfs uses Node.js, you can install it the same way you install in Ubuntu, through npm. You can also check the work done at https://github.com/ipfs/js-ipfs/pull/1007 to get a "binary" of js-ipfs, however, that is not recommended. 

Is there any reason why you want a binary and not run it with Node.js?

**Comment by richardschneider** [comment]
Perhaps https://www.npmjs.com/package/node-windows can help.

**Comment by diasdavid** [comment]
@haroldTlan let us know if you still have questions. Closing this one meanwhile.
