### ISSUE TITLE
Add wrap-with-directory support (HTTP API and Core)

### ISSUE THREAD

**Issue by nunofmn** [ipfs/js-ipfs#1178]
Related to https://github.com/ipfs-shipyard/ipfs-companion/issues/349

Right now, the `wrap-with-directory` option only works in _CLI_ and support in  _HTTP API_ and _Core_ is missing

I already have a working solution that uses the `wrap` option in [js-ipfs-unixfs-engine Importer API](https://github.com/ipfs/js-ipfs-unixfs-engine#const-import--new-importerdag--options).

_Question:_ it is necessary add support to this option in [interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core) beforehand? (or maybe at least add a tracking issue)

I'm looking forward to open a PR 👍

**Comment by diasdavid** [comment]
Hey @nunofmn o/ Yeah, add it to interface-ipfs-core. You can submit both PRs at the same time :)

**Comment by diasdavid** [comment]
@nunofmn ping :) Still interested in submitting that PR?

**Comment by musicsmithnz** [comment]
I am quite interested in this feature, as it allows to use the human readable filenames and also to have the filename extension which is useful for [browsers?] recognizing the mime type.

**Comment by wraithgar** [comment]
I'm attempting to work on this on the js side of things.  Just getting started ramping up here so your patience is very much appreciated!

**Comment by musicsmithnz** [comment]
I've been looking at a workaround which uses the recursive options and passes in a directory. I have been having trouble with this and I'm not sure exactly why, it might be something to do with asynchronous loading of the files.

**Comment by wraithgar** [comment]
Took a stab at this, see the three PRs linked to above.

**Comment by diasdavid** [comment]
@wraithgar looking good! I'll handle merging and releasing those soon (probably earlier tomorrow) :) Thank you!

**Comment by musicsmithnz** [comment]
Thanks guys I'm looking forward to seeing this.

**Comment by hacdias** [comment]
Closing this since https://github.com/ipfs/js-ipfs/pull/1329 was merged.
