### ISSUE TITLE
web socket connection to ws-star.discovery.libp2p.io failed

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#1185]
<img width="1215" alt="flipchart_and_flipchart" src="https://user-images.githubusercontent.com/47910/35291238-a0a63652-0064-11e8-9623-30e4d6b999b6.png">

**Comment by mkg20001** [comment]
Seems like it crashed. Temp fix would be to use `ws-star-signal-2.servep2p.com` instead

**Comment by VictorBjelkholm** [comment]
It's up and running again: https://ws-star.discovery.libp2p.io/

Was killed because instance ran out of memory apparently and somehow it wasn't gracefully recovered. Created issue about possible memory leak here: https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/issues/12

**Comment by noxonsu** [comment]
please restart :)

**Comment by CerratoA** [comment]
I have a question, can I trust this web socket for a production application?
or how can I create my own transport and a discovery service?

**Comment by tyvdh** [comment]
Happening again. 502 Bad Gateway
