### ISSUE TITLE
Start gateway from NodeJS

### ISSUE THREAD

**Issue by paulogr** [ipfs/js-ipfs#1187]
I've been looking at code but haven't found a way to start the gateway from NodeJS.

`new IPFS()` only starts the IPFS node but not the gateway.

Thanks

**Comment by VictorBjelkholm** [comment]
Something like this should work (it also starts a js-ipfs node for using with the gateway):

```
const Gateway = require('ipfs/src/http')

const gateway = new Gateway('./path-to-ipfs-repo')
gateway.start(true, () => {
  console.log('Gateway now running')
})
```

**Comment by paulogr** [comment]
Thank you for awswer.

I saw this class `HttpApi`, but isn't exposed to be consumed, right?
Is there any reason?

**Comment by diasdavid** [comment]
@paulogr you can use https://github.com/ipfs/js-ipfsd-ctl to spawn js-ipfs daemons which then expose the gateway. Would that work for you?

**Comment by paulogr** [comment]
Proprably it works for me, yeah. 
I'll make some tests, closing for now.

Thank you for you answer.
