### ISSUE TITLE
TCP 0 addr port, doesn't get correctly resolved to a final address

### ISSUE THREAD

**Issue by dryajov** [ipfs/js-ipfs#1203]
- **Version**: 0.27.7
- **Platform**: all
- **Subsystem**: ipfs-api, libp2p, libp2p-tcp

#### Steps to reproduce the error:

- Create an ipfs node with a `0.0.0.0:0` addr
- Connect to ipfs with `ipfs-api` and call the `id` method

Expected results:

The `addresses` field of the resulting object should contain addresses with resolved 0 addrs, however the tcp port does not get correctly resolved.

**Comment by dryajov** [comment]
This seems to be related - https://github.com/libp2p/js-libp2p-swarm/pull/227

**Comment by diasdavid** [comment]
@dryajov can you create a test please?

**Comment by daviddias** [comment]
@jacobheun @vasco-santos can you confirm if this is still a bug or link to a tracking issue on libp2p land?

**Comment by jacobheun** [comment]
This works for both TCP and Websockets.

For example, updating your Swarm config to:
```json
"Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/0",
      "/ip4/0.0.0.0/tcp/0/ws"
    ],
    ...
}
```
Will get you something like:
```log
$ jsipfs swarm addrs local
/ip4/127.0.0.1/tcp/64365/ipfs/Qm
/ip4/192.168.x.x/tcp/64365/ipfs/Qm
/ip4/127.0.0.1/tcp/64366/ws/ipfs/Qm
/ip4/192.168.x.x/tcp/64366/ws/ipfs/Qm

```
