### ISSUE TITLE
Can't connect to ipfs daemon from node 'ready' callback.

### ISSUE THREAD

**Issue by 10thfloor** [ipfs/js-ipfs#1207]
- **Version**: js-ipfs version: 0.27.7
- **Platform**: 17.3.0 Darwin Kernel Version 17.3.0: root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

#### Description:
Hello, I have a question about the intended functionality of the ```ipfs``` node instance.
```

const IPFS = require('ipfs');
const API = require('ipfs-api')

const node = new IPFS()

node.on('ready', () => {

    const ipfs = API('localhost', '5002', { protocol: 'http' })
   
    // Attempt to ask the API for anything. 
    // ipfs.id is used as an example here but all other methods fail.

    ipfs.id(function (err, identity) {
      if (err) {
        throw err
      }
      console.log(identity)
    })
})
```

#### Steps to reproduce the error:
Running the above code with `node` produces:
```
{ Error: connect ECONNREFUSED 127.0.0.1:5002
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5002 }
```
I'm wondering if the ```ipfs``` constructor starts an ipfs daemon, or if the daemon must be started manually, from the cli?

Does ```new IPFS()``` start the ipfs daemon? The docs are unclear about this. (At least for me).

Thanks! ✌️

**Comment by 10thfloor** [comment]
Excellent. The ```ipfs-ctl``` module is what I was looking for. It works perfectly. Thank you!

**Comment by diasdavid** [comment]
Awesome :)
