### ISSUE TITLE
New UI Good UI

### ISSUE THREAD

**Issue by manjula91** [ipfs/js-ipfs#1211]
I would like to contribute to give a new look and feel and UI. Let me know if this sounds good to you :)

**Comment by f50c1ty** [comment]
JS-ipfs is IPFS protocol javascript implementation. It's like a npm package whom you can use it for communicating with IPFS network. It doesn't need UI.

**Comment by diasdavid** [comment]
@manjula91 it does sound good, but which UI are you mentioning? WebUI https://github.com/ipfs-shipyard/ipfs-webui ?

**Comment by manjula91** [comment]
Yes :)

**Comment by diasdavid** [comment]
@manjula91 I say _go for it_ :D Also, check out the [Working Group IPFS in Web Browsers](https://github.com/ipfs/in-web-browsers), @lidel and @olizilla can help you get ramped up :)

**Comment by manjula91** [comment]
cool thanks I will start on this soon any UI you have in mind as of now?

**Comment by lidel** [comment]
Hi @manjula91!  Some links to you may find super helpful to get you up to speed:

- GUI-related work across all things IPFS in [pm-ipfs-gui](https://github.com/ipfs-shipyard/pm-ipfs-gui)  (repo for high level planning)
  - get familiar with docs and links in README, and existing [pm-ipfs-gui/issues](https://github.com/ipfs-shipyard/pm-ipfs-gui/issues)
    - Current focus is to work on Style Guide – see mockups and discussion at https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/7: 
      > We want to unify looks and feel across all apps, right now Style Guide and UI Kit is being fleshed out, so this is good place to start by looking at this discussion to **make sure there is no duplicated effort** :)
- If you have questions, ideas or need access to some Google Docs or Zeplin project, let us know by creating issue in  [pm-ipfs-gui/issues](https://github.com/ipfs-shipyard/pm-ipfs-gui/issues)
- When it comes to UX suggestions for  WebUI there is a good writeup at https://github.com/ipfs-shipyard/ipfs-webui/issues/622 – feel free to reuse/extend it if you have more ideas.

**Comment by diasdavid** [comment]
@manjula91 did you get @lidel's message? Let me know if you need any other help or info. Closing this issue.

**Comment by manjula91** [comment]
@diasdavid which thread would be best to talk about this further or some slack channel

**Comment by diasdavid** [comment]
@manjula91 see @lidel's comment https://github.com/ipfs/js-ipfs/issues/1211#issuecomment-364926257
