### ISSUE TITLE
Add IPFS_PATH to CLI help

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#1213]
It's possible to init a repository at a different location (other than the default `~/.jsipfs`) with setting the `IPFS_PATH` environment variable. This isn't clear from the CLI help. `go-ipfs` has this information:

```
ipfs uses a repository in the local file system. By default, the repo is
located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
environment variable:

    export IPFS_PATH=/path/to/ipfsrepo
```

Add this to the js-ipfs CLI as well.

**Comment by vmx** [comment]
This isn't as easy as expected as it needs an change on the upstream argument parser package. See https://github.com/yargs/yargs/issues/924 for more information.

**Comment by bvand** [comment]
@vmx I'm new to ipfs, looking to help out on an issue like this to get started.

It seems like the final comment in the yargs issue you have linked proposes using an epilog, but I believe you and @diasdavid are looking for a prologue?
I noticed another issue in yargs that also asked for some way to add a prologue: https://github.com/yargs/yargs/issues/401. They suggest using either the [.usage() method](http://yargs.js.org/docs/#api-usage-desc-builder-handler), or simply console.log...

I'd like to attempt the first option (.usage()) to solve this problem. Which of the cli commands' information would you like the IPFS_PATH help to be prepended to?
Am I missing anything here?

**Comment by bvand** [comment]
@vmx I created https://github.com/ipfs/js-ipfs/pull/1274, which just logs the help message before the yargs output. Are there any other commands the help message should happen for? e.g. should it show up when just running
```
jsipfs --help
```
on its own?

**Comment by vmx** [comment]
@bvand I think having it in `init` is enough. It also matches what go-ipfs is doing.

**Comment by vasco-santos** [comment]
@vmx the `go-ipfs` also reports the `IPFS_PATH` usage on the help menu. Should we add it? Otherwise, this issue is accomplished, right?

**Comment by vmx** [comment]
@vasco-santos You are right, I've missed that `IPFS_PATH` is also shown on `ipfs --help`. It also shows up on `ipfs daemon --help`. I guess that ideally we display it whenever go-ipfs displays it (whenever that is).

**Comment by vasco-santos** [comment]
Ok, I will add it then @vmx 😃
