### ISSUE TITLE
Can't connect nodejs and browser nodes

### ISSUE THREAD

**Issue by JoseMiguelHerrera** [ipfs/js-ipfs#1219]
I know this has been discussed many times, but my app is dependant on this functionality and after days of testing I can't get it to work.

First I tried connecting my go-ipfs node with the browser node, to no avail. I did this by attempting the reverse proxy nginx method (using websockets), but I could not get it to connect.

Right now I'm trying the the nodejs node using p2p-websocket-star as I've seen being mentioned.

My server node config: 
```
    "Addresses": {
        "Swarm": [
            "/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star"
        ],
        "API": "/ip4/127.0.0.1/tcp/5002",
        "Gateway": "/ip4/127.0.0.1/tcp/9090"
    },
```

My browser config:

```
const node = new IPFS({
  "Addresses": {
    "Swarm": [
    ],
    "API": "",
    "Gateway": ""
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false,
      "Interval": 10
    },
    "webRTCStar": {
      "Enabled": true
    }
  },
  "Bootstrap": [
    "/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmVNqmWGV248kCZpJq2yXSYzTQi5the7vxs82HLfZj3tcK"
  ]
});
```

I don't really care how, but I need to get my browser node detecting the server node to fetch objects.

Help would GREATLY be appreciated.

**Comment by diasdavid** [comment]
@JoseMiguelHerrera you have switch the Bootstrap with Swarm addrs.

You just need for your browser config:

```
const node = new IPFS({
  "Addresses": {
     "Swarm": [
       "/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star
    ]
  }
})
```

They will find each other from there.

**Comment by diasdavid** [comment]
Closing, let us know if it didn't work for you.

**Comment by nezzard** [comment]
It's not working for me. Add to browser node and trying to ipfs cat hash at go node

**Comment by aphelionz** [comment]
I am also having trouble getting browser node content on public gateways... running 0.35 RC

**Comment by eh-93** [comment]
Having the same issue
