### ISSUE TITLE
Missing shutdown route

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs#1224]
The NPM v0.27.7 release is missing the `shutdown` route.  

https://unpkg.com/ipfs@0.27.7/src/http/api/routes/ is missing shutdown.js!

Can we get a new release

**Comment by richardschneider** [comment]
Just noticed that `stats` is also missing.

**Comment by diasdavid** [comment]
It's not "missing" it just hasn't been release. All of that will come out with the next version. Will start the release dance this week.

**Comment by richardschneider** [comment]
ipfs v0.28.0 is released with the `shudown` route.
