### ISSUE TITLE
swarm.peers return type is different in js-ipfs and js-ipfs-api

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1248]
`swarm.peers` returns an object with a `peer` property. In the [spec it says this will be a `PeerInfo` object](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/SWARM.md#peers), and it [is in js-ipfs](https://github.com/ipfs/js-ipfs/blob/5b40b41f26573856b206e6b21be89cfc67ef39b4/src/core/components/swarm.js#L27-L34), but if you call via js-ipfs-api you'll [get back a `PeerId`](https://github.com/ipfs/js-ipfs-api/blob/78ba320573ab73ff4224740f59e82e2e504d7881/src/swarm/peers.js#L48) (js-ipfs http [converts the PeerInfo to a PeerId](https://github.com/ipfs/js-ipfs/blob/5b40b41f26573856b206e6b21be89cfc67ef39b4/src/http/api/resources/swarm.js#L54)).

Just wondering if this is expected, and if not, what is the desired result?

**Comment by lidel** [comment]
Seems that we have a running tradition of breaking changes  in `swarm.peers` :upside_down_face: 

FYSA there was a time when `Peers` was named `Strings` in `go-ipfs` and `js-ipfs-api` still ships with workaround for that: [js-ipfs-api/src/swarm/peers.js](https://github.com/ipfs/js-ipfs-api/blob/2970c9f81efef28b55aba0ba0be40d7f604c1ec6/src/swarm/peers.js)

Not sure how useful is this data point, but I imagine we should handle all such cases in similar fashion.

**Comment by diasdavid** [comment]
> we should handle all such cases in similar fashion, for consistency's sake.

Absolutely. We have https://github.com/ipfs/interface-ipfs-core to keep us in check but it seems that was missed.

@alanshaw can you double check the SPEC -- https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/SWARM.md -- and update/write the tests accordingly on https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/swarm.js?

**Comment by alanshaw** [comment]
I'm happy to sort the tests, but I'll need to know what _should_ `peer` be?

Spec says the following:

<img width="843" alt="screen shot 2018-03-06 at 11 56 08" src="https://user-images.githubusercontent.com/152863/37031165-a5de4a46-2135-11e8-8528-d2b06c22b37d.png">

I'm not familiar with the syntax of `[PeerInfo]()`...I took it to mean a `PeerInfo` instance...

FYI, if it should be a `PeerInfo` then it'll need changes to js-ipfs, js-ipfs-api and go-ipfs but if it should be a `PeerId` it'll just need one small change to js-ipfs.

**Comment by diasdavid** [comment]
It can be just a PeerId. The reason why I made it a PeerInfo in the past was because I was trying to expose more useful information through the swarm command. Now that folks now that the internal instance of libp2p is also available to use, it is less of a problem that the swarm command is limited.

**Comment by alanshaw** [comment]
Roger roger 👍
