### ISSUE TITLE
Proposal to move to move to Flow types

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#1260]
[Flow](https://flow.org/) types will be introduced into the js-ipfs stack. We'll start with some smaller libraries and see how it goes. The goal is that it doesn't break existing things and the libraries can be used as before. If we find problems with that APIs due to adding types, those of course will be fixed.

If a new workflow is needed, it will be documented. Starting to contribute to a js-ipfs project shouldn't be any harder than it is now.

The tooling will change a bit. We introduce [Prettier](https://prettier.io/) for automated code formatting as based on @Gozala's experience [standardJS](https://standardjs.com/) doesn't play that nice with Flow types. Though we will use the [prettier-standard](https://github.com/sheerun/prettier-standard) version so that the existing code base doesn't need to be changed too much and people used to coding in standardJS won't see their code reformatted too heavily.

The npm commands like `test`, `lint`, `release` are expected to work as usual. They might not use [AEgir](https://github.com/ipfs/aegir) from the start, but eventually the tools/code needed will be merged into AEgir.

Let's stick to the original plan and get `js-cid` Flow types. In order to achieve that, port all the multiformats projects before that:

- [ ] js-multihash - https://github.com/multiformats/js-multihash/pull/49
- [ ] https://github.com/multiformats/js-multiaddr/pull/51
- [ ] https://github.com/multiformats/js-multihashing/pull/27
- [ ] https://github.com/multiformats/js-multibase
- [ ] https://github.com/multiformats/js-multistream-select
- [ ] https://github.com/multiformats/js-multihashing-async
- [ ] https://github.com/multiformats/js-multicodec
- [ ] https://github.com/ipld/js-cid (needs almost all the above)

This awesome endeavor is lead by @vmx.

References:

 - Initial discussions: https://github.com/ipfs/community/issues/278
 - Discussions on the first PR implementing it in js-multihash: https://github.com/multiformats/js-multihash/pull/47

**Comment by olizilla** [comment]
I'd like to get my hands dirty on this. Would anyone with experience of flow be up for running a workshop / walkthrough of converting one of the libs listed, or otherwise? Or, lower set up cost... perhaps folk who are already comfortable using flow could buddy up with someone to pair (via zoom, or whatever works) on converting one of the listed libs.

I'd like to have a go at `js-multibase` if it's not already being worked on.

**Comment by Gozala** [comment]
@olizilla I'm happy to help as long as we can work out time that will work with my schedule.

**Comment by diasdavid** [comment]
@vmx thank you so much for taking the lead on pushing this endeavor forward and @Gozala for starting it in the first place ❤️.

@olizilla I love that idea! Remote Pair Programming has worked really well in the past and I'm down to try it again. I feel that session should be js-multibase + js-cid and if everyone is comfortable, we should record it so that we can use it as an educational tool.

1 hour (including questions) should be enough, right? Wanna do Friday at 5pm UTC?

**Comment by Gozala** [comment]
Friday time would work for me. Unfortunately I won't have much time to prepare, if you have specific things you'd like me to cover knowing them ahead would help as well.

Can anyone send me the link to zoom meeting if that's what we going to use.

**Comment by garrensmith** [comment]
Would it be worth adding in flow support to aegir, that way we won't need to do so much project setup for each repo?

**Comment by garrensmith** [comment]
I think it might be nice to implement it in AEgir once https://github.com/multiformats/js-multihash/pull/47 is merged in. That should give us a nice base in terms of how we want flow to work. I think implementing it on a branch as a first attempt would be a good start.

The reason I bring this us is I was looking at adding flow to multihashing, add I'm doing fair bit of copy and pasting initially just to get set up. It's not major but its always nice to avoid it if we can.

But saying all of that I would say having it in AEgir is probably more of a nice to have than something that would be critical.

**Comment by fahrradflucht** [comment]
I could help with this endeavour but I'm still unclear on what the plan looks like. 

https://github.com/multiformats/js-multihash/pull/47 introduces a build step. [While this could bring good things with it](https://github.com/multiformats/js-multihash/pull/47/files#r173730943) the [struggle in the past sounds](https://github.com/ipfs/community/issues/278#issuecomment-357262897) horrible.

I can't find a clear decision on building vs using comments style flow which is what the `datastore` projects seem to be using.

**Comment by vmx** [comment]
@fahrradflucht The current plan is:

 - Have this additional build step
 - Don't use prettier, instead adapt the standardjs liniting to make it work

Current PRs that are work in progress on adding types are:

 - That one is kind of the template for other PRs: https://github.com/multiformats/js-multihash/pull/49 (driven by @Gozala)
 - https://github.com/multiformats/js-multihashing/pull/27 (driven by @garrensmith)

I try to make sure that AEgir works with all this. The current work happend on the [flow branch](https://github.com/ipfs/aegir/tree/flow).

So feel free to review those PRs or pick one of those modules mentioned on the original and have a try with adding types. Any help is appreciated, especially comments if we should do things differently based on your experience.

**Comment by fahrradflucht** [comment]
@vmx alright, thanks for the clarifications 😃.

Then I will start working on [multiformats/js-multibase](https://github.com/multiformats/js-multibase).

BTW: I noticed that there is no PR for the flow branch on AEgir. Maybe that would a good place for the tooling setup discussion to happen. It is kind of all over the place at the moment.

**Comment by vmx** [comment]
@fahrradflucht: Good point, I've created a PR on AEgir: https://github.com/ipfs/aegir/pull/213

**Comment by vmx** [comment]
As much as I love Flow, it really makes sense to move on t o TypeScript definitions, which is tracked here: https://github.com/ipfs/js-ipfs/issues/2945. Though it's still the same idea that we use pure JS and add definitions in comments.
