### ISSUE TITLE
examples/browser-video-streaming demo throws TypeError

### ISSUE THREAD

**Issue by kyledrake** [ipfs/js-ipfs#1284]
https://ipfs.io/ipfs/QmfZBFWJsL3sUbKkfTMXRwpKyjRAqi2h2cTmcUS5ubGeHJ/

![browser-video-streaming-error](https://user-images.githubusercontent.com/28153/37999401-8cd2e2f2-31d7-11e8-8d2c-c999bd7ee092.png)

**Comment by alanshaw** [comment]
This was fixed recently by #1427
