### ISSUE TITLE
Data Reading is not correct

### ISSUE THREAD

**Issue by moda20** [ipfs/js-ipfs#1287]
- **Version**: 0.27.7
- **Platform**: Zen ArchLinux
- **Subsystem**:

#### Description: 

Data returned by `Ipfs.object.data()` is not the same as the one got from the `Read-Only gateway`

#### Steps to reproduce the error:
run `jsipfs daemon`
create a node from the existing ports `localIpfs`
call `localIpfs.files.add(Buffer.from("TEXT"))` returns `Hash`
call `localIpfs.object.data(Hash)`returns something like `[]*^TEXT` ( is the same text but with ascii characters before it and maybe somewhere in the middle)
It is bad if i am transferring base64 image data.

**Comment by richardschneider** [comment]
`ipfs.object.data(Hash)` returns the data portion of the Merkle DAG which is not the same as file's data.

Use `ipfs.cat(Hash)` to get the data of the file.

**Comment by moda20** [comment]
I see, If it is an image in what format i will be getting it ? base64 ?

**Comment by richardschneider** [comment]
IPFS does not care about the format of the data, it is returned via `ipfs.cat` exactly as it was passed to `ipfs.add`.

**Comment by moda20** [comment]
Thank you, it worked. I am closing this then.
