### ISSUE TITLE
Server Profile

### ISSUE THREAD

**Issue by nothingismagick** [ipfs/js-ipfs#1288]
- **Version**: "ipfs": "^0.28.2",
- **Platform**: ubuntu / docker
- **Subsystem**: init I guess

#### Description: 
I got bit by the "server profile" dragon again, in which local/reserved IPs are being pinged from within a datacenter. I already started a discussion over at go-ipfs about this - because there it was happening within go: 

- https://github.com/ipfs/go-ipfs/issues/4843
- https://github.com/ipfs/go-ipfs/pull/4846
- https://github.com/ipfs/go-ipfs/issues/4877

[Here is the oldest issue](https://github.com/ipfs/go-ipfs/issues/1226) I could find about this.

I built a stub of an ipfs app on my mac and wanted to run a docker integration test on a machine with a public-ip at a data-center. I really should have known better (because this has happened before), but literally seconds after I `docker-compose build` my project on the datacenter machine, I get an email from Hetzner (the owner of the datacenter) warning me of network abuse, giving me 24 hours to resolve the problem or face the NIC banhammer. I looked at the list, showing me a MASSIVE flood of connection requests to  10.12.21.145, 10.131.217.239, 192.168.1.107 etc. 

I don't think that having an interactive mode in ipfs.js (when it is running in a node app, for example) is going to work here - it really needs to be configured. Furthermore, I wonder about the security implications here, because it seems that private IPs are being leaked...

I have two requests:
1. Can you please warn about this dragon in the README
2. Consider reversing the logic - where the default behaviour is to NOT be promiscuous in pinging the local network and the user should configure for "private networks" if that is the behaviour that they want.
3. Provide us with some method or approach with which we can track from within IPFS regarding the IP addresses it is reaching out to. That would be much more useful to me than base58 flying by (like in this screenshot of the activity log from ipfs-pack)
![screen shot 2018-04-02 at 03 58 01](https://user-images.githubusercontent.com/35242872/38180075-2075f304-362a-11e8-9411-a4a3d6c49e15.png)

**Comment by hsanjuan** [comment]
I see `jsipfs` provides a `server` profile. Closing. @ipfs/wg-js-core reopen if I'm wrong.
