### ISSUE TITLE
http api not validating if content-type header is present.

### ISSUE THREAD

**Issue by wraithgar** [ipfs/js-ipfs#1291]
The 'add files' endpoint of the http api passes the content-type header down into `ipfs-multipart`, which passes it down into the `content` library which was not checking for that header's presence before trying to parse it, resulting in a traceback and 500 error.

This has been patched in `content` and a pr for `ipfs-multipart` has been opened here: https://github.com/fbaiodias/ipfs-multipart/pull/1

When that PR is either merged or the issue addressed manually we can then update the ipfs-multipart dependency in this repo and close this issue.

**Comment by alanshaw** [comment]
Closing as https://github.com/ipfs/js-ipfs-multipart/pull/1 has been merged
