### ISSUE TITLE
Info: Fails to build a minified create-react-app with ipfs

### ISSUE THREAD

**Issue by fsdiogo** [ipfs/js-ipfs#1321]
There are a lot of issues regarding `create-react-app` and `js-ipfs`, let's keep that discussion in this one, as well as options to make them play well together. 

## ✅ js-ipfs minified version 
The minified version of IPFS (when you run `npm run build` and outputs to `dist/index.min.js`) wasn't being uglified (compressed and mangled) due to the way we were doing some type checks. This has been solved and will be available in the [0.29.0 release](https://github.com/ipfs/js-ipfs/issues/1320).

## ℹ️ create-react-app
For those who are using `create-react-app` with IPFS, you'll still encounter some issues when trying to build a production version. The problem comes from `create-react-app` itself and not IPFS, because it uses UglifyJS that still doesn't support ES6. As IPFS doesn't offer a transpiled version, trying to build a production version of a CRA with IPFS will fail to minify. A new version of CRA is being [worked on](https://github.com/facebook/create-react-app/issues/3815), using `uglify-es` that supports ES6. Until then, developers have a few options:

- Eject and change the webpack configs to use `uglify-es` intead of `uglify-js`
  - Until the 0.29.0 release lands, you'll have to follow these  configs: https://github.com/ipfs/js-ipfs/issues/1321#issuecomment-387748304
- Import the IPFS with a script tag
  - After the 0.29.0 release you'll be able to import the bundled & minified version
- Use [this trick](https://github.com/facebook/create-react-app/issues/2108#issuecomment-347623672) that @fazo96 pointed out

**Comment by eugenioclrc** [comment]
Hi! i saw your bounty in gitcoin. I have try to replicate the error with no success.

What version of node are you using? have you try with the latest LTS (v8.11.1)

![captura de pantalla de 2018-05-06 16-48-22](https://user-images.githubusercontent.com/332426/39677221-935db80a-514d-11e8-8d4e-a8fe8ac96e88.png)
![captura de pantalla de 2018-05-06 16-48-22](https://user-images.githubusercontent.com/332426/39677222-95ce06ee-514d-11e8-9767-46b70081aef3.png)

**Comment by abitrolly** [comment]
@eugenioclrc thanks for the heads up, I believe we used `yarn rum build`. @Pechalka can you confirm that the problem with building the project is solved now?

I am going to award the bounty to @fsdiogo anyway for dealing with webpack bundling [the proper way](https://github.com/ipld/js-cid/issues/38#issuecomment-378611680). @fsdiogo, can you plese go to https://gitcoin.co/issue/ipld/js-cid/38/121 and claim the Bounty?

Also thanks @AquiGorka and @dimkk for putting effort into solving the build issue. I wish I had more funds to split for everyone involved, and I think we all agree that @fsdiogo did a good job here.

**Comment by fsdiogo** [comment]
Hey @abitrolly, I fixed the uglify issue in `js-ipfs` that will be available in the `0.29.0` release.

But, the bundling of `js-ipfs` with a `create-react-app` didn't get fixed, we'll have to wait for a new CRA release which will use `uglify-es`. Until then you can use the solutions in the first comment.

I'll gladly collect the bounty, but only if I solved your problem 🙂

**Comment by Timer** [comment]
Just to set expectations, we're in no rush to get `create-react-app` 2.0 out (I expect a few months yet). The best way to deal with this is to compile your package if you wish for people to use it in the browser.

**Comment by fsdiogo** [comment]
Thanks for the input @Timer.

Yes, we're already discussing a way to offer a compiled version of js-ipfs, we'll see how that goes!

**Comment by olizilla** [comment]
> Eject and change the webpack configs to use uglify-es intead of uglify-js

Until the 0.29 release lands, you do still need to provide config to the UglifyJsPlugin (which now uses uglify-es) to get it to compress IPFS without breaking things. Here is what we're using in peer-pad webpack config now:

```js
new UglifyJsPlugin({
  // see: https://github.com/webpack-contrib/uglifyjs-webpack-plugin#options
  parallel: require('os').cpus().length,
  extractComments: true,
  // see: https://github.com/mishoo/UglifyJS2/tree/harmony#minify-options
  uglifyOptions: {
    // IPFS only comes in ecma 6 flavour.
    ecma: 6,
    compress: {
      // Needed to minify js-ipfs until v0.29 see: https://github.com/ipfs/js-ipfs/issues/1321
      keep_classnames: true,
      keep_fnames: true,
      // Disabled because of an issue with Uglify breaking seemingly valid code:
      // https://github.com/facebookincubator/create-react-app/issues/2376
      // Pending further investigation:
      // https://github.com/mishoo/UglifyJS2/issues/2011
      comparisons: false,
      // don't display warnings when dropping unreachable code
      warnings: false,
    },
    mangle: {
      // Needed to minify js-ipfs until v0.29 see: https://github.com/ipfs/js-ipfs/issues/1321
      keep_classnames: true,
      keep_fnames: true,
      safari10: true,
    },
    output: {
      comments: false,
      // Turned on because emoji and regex is not minified properly using default
      // https://github.com/facebookincubator/create-react-app/issues/2488
      ascii_only: true,
    },
    sourceMap: shouldUseSourceMap,
  }
}),
```

that's a merge of the ejected `create-react-app` recommendations with the tweaks to preserve js-ipfs

See: https://github.com/ipfs-shipyard/peer-pad/blob/1f6bb61a1abe2fe0a76a343156c7bbc79346f3e3/config/webpack.config.prod.js#L268-L302

**Comment by fsdiogo** [comment]
Many thanks for the input @olizilla. I'll update the first post to clear that up 👍

**Comment by amaurymartiny** [comment]
As a workaround, I am currently using [`react-app-rewired`](https://github.com/timarney/react-app-rewired).

My `config-overrides.js` looks like this:
```javascript
module.exports = function override(config, env) {
  if (env === 'production') {
    // Remove UglifyJsPlugin
    config.plugins.splice(3, 1);
  }
  return config;
};
```

You can of course replace the item at index 3 in `config.plugins` with the config above.

IMO it's cleaner than [this trick](https://github.com/facebook/create-react-app/issues/2108#issuecomment-347623672) proposed in the 1st post.

**Comment by louismerlin** [comment]
I tried to create a new app with create-react-app and then adding IPFS v.0.29, that just came out.

It **starts** if installed with node < 10, but still won't **build** because of `cids`...

**Comment by olizilla** [comment]
@hugomrdias I just tested out your fix on a new project, and it works great! Let's get it merged and add some info about it here.

**Comment by olizilla** [comment]
@louismerlin fixes for node@10 are about to land https://github.com/ipfs/js-ipfs/pull/1358

**Comment by hugomrdias** [comment]
🔥🔥🔥  cool !!  
Let's get this https://github.com/libp2p/js-libp2p-switch/pull/259 merged and released :) 

Temporary instructions to use IPFS on a CRA

```bash
$ # Create a new application
$ npx create-react-app@next --scripts-version=2.0.0-next.66cc7a90
$ # Upgrade an existing application
$ yarn upgrade react-scripts@2.0.0-next.66cc7a90
```

add this to package.json
```js
"resolutions": {
        "libp2p-switch": "libp2p/js-libp2p-switch#feat/swap-quick-lru"
}
```
re-install deps using **yarn** i don't think npm supports `resolutions`

```bash
rm node_modules
yarn
```

References:
https://github.com/facebook/create-react-app/issues/3815

**Comment by Timer** [comment]
> https://github.com/ipfs/js-ipfs/issues/1321#issuecomment-392935357

I highly suggest to **not** do this, you are disabling minification and dead-code elimination which will result in a very slow React application in production and potential for secrets to be leaked.

**Comment by blake41** [comment]
Apologies if this is a n00b question.  I followed https://github.com/ipfs/js-ipfs/issues/1321#issuecomment-393112809

My CRA had already been created, so i didn't do the first step (npx create-react-app@next --scripts-version=2.0.0-next.66cc7a90), just started at the next step installing yarn and running the update command.  I'm still getting the same error.  Am I missing something obvious?

**Comment by hugomrdias** [comment]
@blake41 did you run yarn instead of npm? and also have you done a clean re-install ?

**Comment by blake41** [comment]
@hugomrdias i did use yarn, but was able to figure out a solution, thanks for responding!

**Comment by abax1** [comment]
Thanks @hugomrdias, [this](https://github.com/ipfs/js-ipfs/issues/1321#issuecomment-393112809) worked for me.

**Comment by alanshaw** [comment]
Closing this now that a solution has been found. Tracking adding working examples for various bundlers in https://github.com/ipfs/js-ipfs/issues/1436
