### ISSUE TITLE
ipfs.dht.findprovs is passing cb in timeout position to libp2p findProviders

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#1322]
- **Version**: 0.28.2
- **Platform**: all
- **Subsystem**: dht

#### Description: 

`ipfs.dht.findprovs` is passing `cb` in `timeout` position to libp2p `findProviders`, and so the call fails to return anything.

In the dht component in js-ipfs https://github.com/ipfs/js-ipfs/blob/37801c191ad60df12ecd3cb98c52192975e725c8/src/core/components/dht.js#L64

and the js-libp2p findProviders impl https://github.com/libp2p/js-libp2p/blob/03faf69212b0f3501291527f85b2bb85a8c5427e/src/content-routing.js#L5

#### Steps to reproduce the error:

In a browser with ipfs-companion installed and pointing at an embedded ipfs node:
```js
ipfs.dht.findprovs('QmYPNmahJAvkMTU6tDx5zvhEkoLzEFeTDz6azDCSNqzKkW', console.log)
// Error: callback is not a function at Object.findProviders
```

```shell
jsipfs findprovs QmYPNmahJAvkMTU6tDx5zvhEkoLzEFeTDz6azDCSNqzKkW
// returns nothing, but exits cleanly
```

**Comment by diasdavid** [comment]
@olizilla wanna submit a PR to fix that? thanks for reporting :)

**Comment by olizilla** [comment]
Sure! I think an ideal fix for this would result in a change to the
interface; the caller to findprovs should be able to pass in options to
specify a timeout duration.

Is that a reasonable approach @diasdavid ? What's the proceedure for
proposing an interface change?

**Comment by PascalPrecht** [comment]
@olizilla have you started implementing this already, or do you need any help with this?

**Comment by olizilla** [comment]
@PascalPrecht I haven't started on this, please feel free to PR it if you're looking at it!

**Comment by PascalPrecht** [comment]
@olizilla I'll do that.

@diasdavid just to clarify the API. We wanna turn:

```
    findprovs: promisify((key, callback) => {
```
to
```
    findprovs: promisify((key, options, callback) => {
```
where `options` can have a `timeout` property, is that correct?

**Comment by PascalPrecht** [comment]
I guess on that note, we will have to introduce a decent default for `timeout`

**Comment by PascalPrecht** [comment]
@alanshaw do you know what the `timeout` default has to be here? 

As https://github.com/libp2p/js-libp2p/blob/03faf69212b0f3501291527f85b2bb85a8c5427e/src/content-routing.js#L5 expects `timeout` in any case, we should have a default when `callback` is passed but no `options`.

I would also updated `interface-ipfs-core`'s spec accordingly (which doesn't provide that information either).

**Comment by alanshaw** [comment]
Unless we want to explicitly set a default when not provided (IMHO I don't think we need to) I'd leave it to the implementation to set an appropriate value (you can pass `null`).

https://github.com/libp2p/js-libp2p-kad-dht/blob/012d2c3b30f3eb59a2ed68606090cd9757bfde52/src/index.js#L177-L197

**Comment by PascalPrecht** [comment]
Ah perfect, okay. Thanks!
