### ISSUE TITLE
wrapWithDirectory test fails

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#1328]
The test `interface-ipfs-core tests .files .add wrapWithDirectory` on master fails. To reproduce the issue, simply run `npx mocha --exit test/core/interface/files.js` from within the js-ipfs root directory.

I make this a P0 as it prevent CI from passing.

**Comment by vmx** [comment]
It seems that the test is correct as https://github.com/ipfs/js-ipfs-api/pull/750/files#diff-438d3282bfe7cdd71c3818dfce192cb6R167 also checks for two elements in the result.

**Comment by VictorBjelkholm** [comment]
Test that broke ipfs/js-ipfs#master was added here: https://github.com/ipfs/interface-ipfs-core/pull/251 and interface-ipfs-core version 0.60.1 was released without testing with js-ipfs first

**Comment by VictorBjelkholm** [comment]
Agree that tests seems correct, but js-ipfs doesn't have the "wrap with directory" functionality yet

**Comment by VictorBjelkholm** [comment]
There is a pending PR here though: https://github.com/ipfs/js-ipfs/pull/1290

**Comment by diasdavid** [comment]
Thank you for fixing this in a timely manner, @VictorBjelkholm :)
