### ISSUE TITLE
Error: invalid block

### ISSUE THREAD

**Issue by Jonybang** [ipfs/js-ipfs#1331]
- **Version**:
```
js-ipfs version: 0.28.2-
Repo version: 6
System version: x64/linux
Node.js version: v9.11.1
```
- **Platform**:
```
Linux common 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- **Code**::
```
const IPFSFactory = require('ipfsd-ctl');

IPFSFactory
   .create({ type: 'proc', exec: IPFS })
   .spawn({ disposable: false }, async (err, ipfsd) => {

      ipfsd.init({}); // <-- Throw error
   })
```
#### Description:
I'm getting invalid block error on init ipfs:
```
Error: invalid block
    at setImmediate (/home/jonybang/ipfs-service/node_modules/ipfsd-ctl/node_modules/ipfs-repo/src/blockstore.js:90:20)
    at Immediate.<anonymous> (/home/jonybang/ipfs-service/node_modules/async/internal/setImmediate.js:27:16)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Emitted 'error' event at:
    at done (/home/jonybang/ipfs-service/node_modules/ipfs/src/core/components/init.js:21:14)
    at /home/jonybang/ipfs-service/node_modules/async/internal/once.js:12:16
    at next (/home/jonybang/ipfs-service/node_modules/async/waterfall.js:21:29)
    at /home/jonybang/ipfs-service/node_modules/async/internal/onlyOnce.js:12:16
    at parallel (/home/jonybang/ipfs-service/node_modules/ipfs/src/core/components/init.js:99:13)
    at /home/jonybang/ipfs-service/node_modules/async/internal/parallel.js:39:9
    at /home/jonybang/ipfs-service/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/home/jonybang/ipfs-service/node_modules/async/eachOf.js:58:13)
    at /home/jonybang/ipfs-service/node_modules/async/internal/onlyOnce.js:12:16
    at /home/jonybang/ipfs-service/node_modules/async/internal/parallel.js:36:13
```

#### Steps to reproduce the error:
I'm just running code, and i'm don't know why it crashes on my server.

**Comment by diasdavid** [comment]
@dryajov mind checking what's up here?

**Comment by travisperson** [comment]
See https://github.com/ipfs/js-ipfsd-ctl/issues/223#issuecomment-385803451

`js-ipfsd-ctl` uses a different version of `js-ipfs-repo` which is resulting in this compatibility issue.

**Comment by diasdavid** [comment]
@vasco-santos once you update deps on ipfsd-ctl and release a new version, can you update here so that @Jonybang can test it? Thanks!

**Comment by vasco-santos** [comment]
`ipfsd-ctl` needs [PR 262](https://github.com/ipfs/js-ipfsd-ctl/pull/262), in order to have CI green. 
Meanwhile, @Jonybang  ipfsd-ctl has `js-ipfs` updated in branch `chore/upgrade-ipfs-version` [PR 262](https://github.com/ipfs/js-ipfsd-ctl/pull/262) and will be merged asap

**Comment by Jonybang** [comment]
ok, i will test this today

**Comment by Jonybang** [comment]
I can't test this issue because of ipfs installation via npm failed:

```
npm i --save ipfsd-ctl # done
npm i --save ipfs # error
```
Output:
```
WARN tar ENOENT: no such file or directory, open '/Users/jonybang/workspace/orbit-test/test-ipfs/node_modules/.staging/minimist-7b3bbede/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/jonybang/workspace/orbit-test/test-ipfs/node_modules/.staging/minimist-7b3bbede/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/jonybang/workspace/orbit-test/test-ipfs/node_modules/.staging/minimist-7b3bbede/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/jonybang/workspace/orbit-test/test-ipfs/node_modules/.staging/minimist-7b3bbede/.travis.yml'

npm ERR! code EINTEGRITY
npm ERR! sha512-57RAHqbMMcVLEkbzx6PlMs7LnwsfMJrzjjNCNAsQuN2wcT8Abm09UIjo2P36x0leYMNIG2SWiyr1H5OLSKn74Q== integrity checksum failed when using sha512: wanted sha512-57RAHqbMMcVLEkbzx6PlMs7LnwsfMJrzjjNCNAsQuN2wcT8Abm09UIjo2P36x0leYMNIG2SWiyr1H5OLSKn74Q== but got sha512-YtyTkU17VoRDdvtad8VO6d4PMVoKPt2LKdXp49y/ogWEk5R1hYvIaWGWfxf46qZTRoyC0RVjujprSfKVzjfXXA==. (27347 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonybang/.npm/_logs/2018-06-01T14_32_48_476Z-debug.log
```
/Users/jonybang/.npm/_logs/2018-06-01T14_32_48_476Z-debug.log:
https://pastebin.com/SUcDnTed

**Comment by Jonybang** [comment]
After reinit npm and installing ipfs first there was this problem:
https://github.com/ipfs/js-ipfs/issues/1347#issuecomment-393991182

And then similar errors if I execute this command:
```
npm i --save https://github.com/ipfs/js-ipfsd-ctl
```

**Comment by fsdiogo** [comment]
@Jonybang can you confirm this is still a problem with the latest version of `ipfsd-ctl` and `js-ipfs`?

**Comment by Jonybang** [comment]
Now all working fine by this code:
```
const IPFSFactory = require('ipfsd-ctl');
const IPFS = require('ipfs');

IPFSFactory
    .create({ type: 'proc', exec: IPFS })
    .spawn({ disposable: false }, async (err, ipfsd) => {
        ipfsd.start({}, (err) => {
                if(err) {
                        console.log("Error", err);
                }
        })
    })
```
if i'm trying to call `init` instead of `start`: ipfsd throwing error `Error Error: Not able to init from state: stopped`, but i'm think this is fine.

**Comment by aphelionz** [comment]
This error seems to have returned, somehow... you can reproduce it by:
1. Checking out the latest commit from https://github.com/orbitdb/orbit-db-test-utils/pull/11 
2. Running `npm install`
3. Running `npm test`

**Comment by aphelionz** [comment]
Edited the above comment.

This is actually pretty interesting, wondering what changed in the package-lock.json to break this! I tried removing a ton of extraneous dependencies to see if something else got smuggled in, to no avail. Something in the dependencies listed above is causing it :/

**Comment by aphelionz** [comment]
Got it in a sandbox, making a new issue: https://codesandbox.io/s/invalid-block-demo-d4oty?file=/src/index.js
