### ISSUE TITLE
onlyHash does not work for new file

### ISSUE THREAD

**Issue by heekyu** [ipfs/js-ipfs#1356]
- **Version**:
0.28.2
- **Platform**:
Mac 10.13.2(17C88)
- **Subsystem**:

#### Steps to reproduce the error:

WORK:
1. add new file
2. and then add same file with onlyHash: true

`
file = fs.readFileSync('a.txt');
node.on('ready', () => {
  console.log('ready');
  node.files.add(file, (err1, res1) => {
    node.files.add(file, { onlyHash: true }, (err, res) => {
      console.log('only hash');
      console.log(err);
      console.log(res);
    });
  })
});`

result:
node ipfs.js 
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
Swarm listening on /ip4/10.193.7.157/tcp/4002/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
Swarm listening on /ip4/169.254.38.232/tcp/4002/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
ready
only hash
null
[ { path: 'QmVdqk9w4eLXSLt9CHVhsmidAng3GweFGPyMqPedWz4gd1',
    hash: 'QmVdqk9w4eLXSLt9CHVhsmidAng3GweFGPyMqPedWz4gd1',
    size: 13 } ]

DO NOT WORK(BUG):
1. add new file with onlyHash: true
=> callback does not called

`
var fs = require('fs');
var ipfs = require('ipfs');
node = new ipfs();

file = fs.readFileSync('a.txt');
node.on('ready', () => {
  console.log('ready');
  node.files.add(file, { onlyHash: true }, (err, res) => {
    console.log('only hash');
    console.log(err);
    console.log(res);
  });
});
`

result:
node ipfs.js 
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
Swarm listening on /ip4/10.193.7.157/tcp/4002/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
Swarm listening on /ip4/169.254.38.232/tcp/4002/ipfs/QmNa9QLbD4JbkVLy6ERc42jwMZnV5hb2uo5mSUXKxsLrNL
ready

**Comment by gabcoh** [comment]
This issue seems to have been solved in a recent update. I just ran the snippet and I believe everything worked correctly.
![screen shot 2018-06-08 at 12 12 37 pm](https://user-images.githubusercontent.com/16101778/41171198-4a31158c-6b15-11e8-823a-1baf2f321a16.png)
I am using ipfs version 0.29.3

**Comment by fsdiogo** [comment]
Hi @heekyu, I've tried your snippets in versions `0.28.2` and `0.29.3`, both are working fine.

I'm closing this now, but feel free to post your full code here if you need further assistance.
