### ISSUE TITLE
Changelog for 0.29 missed breaking change

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs#1368]
In the latest release (0.29 - https://github.com/ipfs/js-ipfs/releases/tag/v0.29.0) there is only one breaking change while in reality there is two, "changes peer prop in return value from swarm.peers to be a PeerId (#1252) (e174866)" also changes the API and should therefore be considered a breaking change.

**Comment by diasdavid** [comment]
@VictorBjelkholm mind updating it? Also, better point it to the release highlights #1320

**Comment by VictorBjelkholm** [comment]
I now realize there is more changes, listed under the "release highlights" as "API Changes" but not existing in the actual changelog. Should just copy-paste that into the changelog.

Both the tag + the commit has been signed by you and has a signoff from @alanshaw, so not sure if editing is the right way to go here... Should we just change the GitHub release and make a new commit instead? Won't be included in the npm package in that case though, unless we do another release...

**Comment by diasdavid** [comment]
I've added the release highlights to the top so that users that are coming and checking the changelog can find all the highlights. 

Can you do a post-mortem on why the changelog failed and what needs to happen to fix it?

**Comment by diasdavid** [comment]
@VictorBjelkholm with https://github.com/ipfs/aegir/issues/225 in mind, it would actually be good to have a PR for the release with a special commit message that would give us access to the changelog for review before merging the release commit.

**Comment by alanshaw** [comment]
That would be great, I was going to suggest a dry run where you can see what's going to be done before it all happens, but a PR would give us that preview step and also allow us to tweak things before actual release.

**Comment by alanshaw** [comment]
I've sent a PR to amend the changelog here https://github.com/ipfs/js-ipfs/pull/1370

I'll be more vigilant when reviewing PRs in the future to ensure commits feature "BREAKING CHANGE" message when breaking changes are made.
