### ISSUE TITLE
can't override all the transports

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#1382]
In the context of [scaling Peer-Pad](https://github.com/ipfs-shipyard/peer-pad/issues/180), I'd like to replace all the libp2p transports by a custom app-specific transport (which, internally, wraps a websocket-start transport). I want the other transports that ship with js-ipfs to not be used.

One option would be to create an app-specific protocol name, so that the existing transports would not use them. Currently, id I try to do that with this config:

```js
const ipfs = new IPFS({
    repo: options && options.repo,
    EXPERIMENTAL: {
      pubsub: true
    },
    config: {
      Addresses: {
        Swarm: (options && options.swarm) || [
          '/dns4/ws-star1.par.dwebops.pub/tcp/443/wss/peer-star-websocket-star'
        ]
      }
    }
  })
```

I get the error:

```
[1] "0" no protocol with name: peer-star-websocket-star
      at Object.exports.process (node_modules/joi/lib/errors.js:196:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:670:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:140:23)
      at module.exports.internals.Any.root.attempt (node_modules/joi/lib/index.js:169:29)
      at Object.module.exports.validate (node_modules/ipfs/src/core/config.js:43:43)
```

But it looks like I need to add this protocol to the multiaddr package, which is being included here. I don't think this is a good options, as multiaddr should not have to care about this.

Another option would be to remove the default transports. But, it doesn't look like I can currently do that: https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/libp2p-browser.js#L17-L24

**Comment by diasdavid** [comment]
What you want to do is:

```
const ipfs = new IPFS({
    libp2p: {
      modules: {
        transport: [
          // insert your transports to override the default ones.
        ]
      }
    }
})
```

See https://github.com/ipfs/js-ipfs#ipfs-constructor

**Comment by pgte** [comment]
By looking at the js-ipfs runtime libp2p code I though the modules were additive. Sorry, I should have tried first..
