### ISSUE TITLE
Fail to establish websocket connection in Chrome

### ISSUE THREAD

**Issue by guoliu** [ipfs/js-ipfs#1387]
- **Version**: 0.29.2
- **Platform**: macOS 10.12.6, Chrome 66.0

#### Severity:
Critical

#### Description: 
On creating a new instance in Chrome, IPFS errors with:
```
WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
``` 

However, it works fine with firefox. Any help is appreciated! Thank you.

#### Steps to reproduce the error: 

Simply do `const ipfs = new IPFS()` and load the page in Chrome.

**Comment by fsdiogo** [comment]
Hi @guoliu 👋

I can't seem to be able to reproduce the error. It's working fine on Chrome here.

What version of `js-ipfs` are you using?

**Comment by alanshaw** [comment]
@guoliu there [was an issue with that rendezvous server](https://github.com/ipfs/infrastructure/issues/412) around the time you posted this issue. It's been resolved now so I'm going to close this. Shout if it's still not working for you.

**Comment by guoliu** [comment]
Hi @fsdiogo and @alanshaw , thank you for your reply. Yes it was due to the issue with rendezvous server. It's working now.

Thanks again for your swift responses 😝
