### ISSUE TITLE
Calling the state() function of state hangs the command line even after retuning a value

### ISSUE THREAD

**Issue by devzl** [ipfs/js-ipfs#1390]
- **Platform**: Linux
- **Version**: 0.29.3 (latest) 

#### Type: 
bug?

#### Severity: 
Medium

#### Description: 
Calling the state() function of the state variable in a IPFS instance, returns a value but hen hangs the command line (need to press Cmd + C on Linux to interrupt the execution)

My only goal is to check the state of a running node, maybe I'm not using the right function?

#### Steps to reproduce the error:

Install IPFS normally `yarn add ipfs`

Query the state:

    const IPFS = require('ipfs')

    const node = new IPFS()
    console.log(node.state.state())

**Comment by fsdiogo** [comment]
Hey @devzl, when running this snippet:

```js
const IPFS = require('ipfs');

const node = new IPFS();

console.log('State:', node.state.state());

node.on('ready', () => {
  console.log('node ready');
  console.log('State:', node.state.state());
});
```

You get this result:
```sh
State: uninitalized
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmahoxtSzJBuMDquK9fVWP1RuaefBbBVYTJvbG4kiYJQU3
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmahoxtSzJBuMDquK9fVWP1RuaefBbBVYTJvbG4kiYJQU3
Swarm listening on /ip4/192.168.2.92/tcp/4002/ipfs/QmahoxtSzJBuMDquK9fVWP1RuaefBbBVYTJvbG4kiYJQU3
Node ready.
State: running
```

So I'm pretty sure this is the function you're looking for.

The terminal "hangs" because the [IPFS node is an instance of Node EventEmitter](https://github.com/ipfs/js-ipfs#events).

If you [stop](https://github.com/ipfs/js-ipfs#nodestopcallback) the node the program will end:

```js
const IPFS = require('ipfs');

const node = new IPFS();

console.log('State:', node.state.state());

node.on('ready', () => {
  console.log('node ready');
  console.log('State:', node.state.state());
  node.stop();
});
```
