### ISSUE TITLE
How do I know the progress of getting a large file

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfs#1394]
`files.get` or `files.cat` . How do I know the progress of getting a large file(video or image). The optional parameters described in the document are offset and length.

**Comment by alanshaw** [comment]
This is not currently spec'd and is not implemented in js-ipfs or go-ipfs implementations. @diasdavid do you know if this is planned/possible?

Note that if you `catReadableStream` or `catPullStream` you'll know how much you have as you get streamed chunks, but you'll not know the total file size.

You can probably use `object.stat` to get the total size beforehand but in the future hopefully `files.stat` will support both MFS as well as IPFS path and you'll be able to use that.

**Comment by diasdavid** [comment]
Nothing planned but this seems like good feedback for https://github.com/ipfs/interface-ipfs-core/issues/284. Thanks for bringing it up, @xuruijing
