### ISSUE TITLE
Is there a detailed description of the err parameter type in the callback function？

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfs#1402]
Many callback functions in the API have the err parameter, where is the type of this parameter described in detail? For example, hashcode does not exist or timeout error messages

**Comment by alanshaw** [comment]
`err` objects are currently just the built in type `Error`. There is discussion and work in progress for adding error codes to messages so that they can be dealt with appropriately: https://github.com/ipfs/interface-ipfs-core/issues/300
