### ISSUE TITLE
Repo version mismatch message confusing

### ISSUE THREAD

**Issue by parkan** [ipfs/js-ipfs#1411]
The go-ipfs error for old repo version is relatively helpful: `ipfs repo needs migration`

however, the js-ipfs error doesn't tell you *what* needs to be upgraded, for example here the user could easily think that their *node* version is the issue:
```
/Users/arkadiy/.nvm/versions/node/v6.5.0/lib/node_modules/ipfs/src/cli/utils.js:67
    throw err
    ^

Error: version mismatch: expected v6, found v5
    at get (/Users/arkadiy/.nvm/versions/node/v6.5.0/lib/node_modules/ipfs/node_modules/ipfs-repo/src/version.js:57:27)
    at store.get (/Users/arkadiy/.nvm/versions/node/v6.5.0/lib/node_modules/ipfs/node_modules/ipfs-repo/src/version.js:31:9)
    at /Users/arkadiy/.nvm/versions/node/v6.5.0/lib/node_modules/ipfs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

as far as I can tell, repo upgrades in js are still an unsolved problem (https://github.com/ipfs/js-ipfs/issues/1071), but it's good to understand that the issue concerns the repo specifically -- would change the text to be more consistent with the go-ipfs message

**Comment by diasdavid** [comment]
Thanks for reporting this @parkan, totally agree that the help text is not super helpful. Fun thing is that for Node.js, you should be actually able to use the fs-repo-migrations from go as well. https://github.com/ipfs/js-ipfs/issues/1115 is just for when you are running in the Browser.
