### ISSUE TITLE
`jsipfs init` creates a repo that is not compatible with go-ipfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#142]
```
 ⭠ feature/swarm ⮀ ~/code/_ipfs/js/js-ipfs ⮀
» IPFS_PATH=~/.jsipfs jsipfs init
 ⭠ feature/swarm ⮀ ~/code/_ipfs/js/js-ipfs ⮀
» IPFS_PATH=~/.jsipfs ipfs daemon
Initializing daemon...
Error: no ipfs repo found in /Users/david/.jsipfs.
please run: ipfs init
```

I believe this is due go-ipfs does `datastore` (the LevelDB thing) checks, which we never implemented (since we didn't needed until we have the DHT going). Is there a way to create that folder eitherway so that a `js-ipfs` generated repo does work for a go-ipfs daemon? Simply dropping the same default `datastore` that go-ipfs generates should do the trick, not sure if there would be any concern there.

@noffle since you made `js-ipfs init`, would you like to look at this one? Thank you

**Comment by noffle** [comment]
I already have a PR waiting for merge. :D  https://github.com/ipfs/go-ipfs/pull/2497

**Comment by diasdavid** [comment]
Is it better to make the go-ipfs more loose? Or make js-ipfs more compliant? @whyrusleeping ?

**Comment by noffle** [comment]
Good Q. Is `datastore` mandatory for all IPFS repos?

**Comment by diasdavid** [comment]
@noffle if we had the DHT that go-ipfs implements, yes, it would be.

**Comment by whyrusleeping** [comment]
making the go-ipfs daemon more loose on its requirements is good, but datastores are a mandatory thing, otherwise how will you store data?

(the 'datastore' directory itself is not required, as long as you have *a* datastore of some kind)

**Comment by diasdavid** [comment]
@whyrusleeping we have the datastore that stores blocks, not the datastore that stores DHT records (levelDB)

**Comment by whyrusleeping** [comment]
theyre the same really, we just have a single datastore in go-ipfs. Its just a mounted datastore that stores certain key prefixes in one place and other key prefixes elsewhere.

I'm going to be changing the datastore config code soon, heres a preview of what our current setup looks like in that new format: https://gist.github.com/whyrusleeping/0252846bc655632449b1

**Comment by noffle** [comment]
So, it sounds like we're for looser reqs + non-mandatory `datastore` directory? If so, let's go ahead and get https://github.com/ipfs/go-ipfs/pull/2497 in.

**Comment by noffle** [comment]
Tested this with latest `go-ipfs` -- it works!

**Comment by diasdavid** [comment]
awesome! :D thank you!
