### ISSUE TITLE
What does it mean to start an IPFS node?

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1438]
Is there any info on what my expectations should be when I construct a new IPFS node but don't start it? What APIs can I call? What network activity happens?

I'm just wondering, because right now, if I construct a node but don't start it, the node is **stopped** but the repo is left **open**. If I then start it and stop it the repo is **closed**, until I start it again...

**Comment by diasdavid** [comment]
A node can be either `online` or `offline` in terms of connecting to the outside world, nevertheless, if it exists and it _attaches itself to a repo_ the repo should be locked for it so that there are no other race conditions with other nodes.

I'm feeling that we need better words to describe these stats rather than `start/stop`.

**Comment by vasco-santos** [comment]
I still think that the state machine has some inconsistencies, at least with the naming that we use. Anyway, I think it would be nice to have a graphical representation of the state machine.

**Comment by alanshaw** [comment]
If start/stop essentially means online/offline then I think that's ok. That **was** my assumption but I didn't know for sure!

We just need to communicate/document better what it means.

Also, go through each API call and define our expectations in online/offline mode. This will allow us to write tests and document what you can and can't do in offline mode.

If the repo should still be open (locked) when the node is **stopped** we need to fix that inconsistency.

i.e. when you manually stop a node you end up with a closed repo but if you instantiate a node with `start: false` it is stopped, but the repo is open (locked).

In which case we probably need a `destroy` method to allow people to close the repo.

**Comment by mikeal** [comment]
One thing that is sort of confusing because of how the docs read, it looks like you have to "start" the node in order to write/read data locally, which I don't believe is the case.

**Comment by daviddias** [comment]
I feel this needs an illustration, getting #1061 would make it even simpler to visualize.
