### ISSUE TITLE
a cat file performance question

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfs#1466]
There are 3 ways to cat files in the API, 
`ipfs.files.cat(ipfsPath, [options], [callback]).
ipfs.files.catPullStream(ipfsPath, [options])
ipfs.files.catReadableStream(ipfsPath, [options])`
so which one performs best (I want to get a small portion from a large file)

**Comment by alanshaw** [comment]
They all use `catPullStream` under the hood. Remember to use `offset` and `length` options rather than reading the whole file and slicing out the bits you need. https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filescat

HTH
