### ISSUE TITLE
Remove bootstrap peers wss0 and wss1

### ISSUE THREAD

**Issue by lgierth** [ipfs/js-ipfs#1474]
These two will be shut down, and their private keys and PeerIDs moved over to the new preloader hosts which were added in #1464:

To remove:
```
/dns4/wss0.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic
/dns4/wss1.bootstrap.libp2p.io/tcp/443/wss/ipfs/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6
```

https://github.com/ipfs/js-ipfs/search?q=wss0

**Comment by diasdavid** [comment]
Done with:
- https://github.com/ipfs/js-ipfs/commit/90e9f68db1c74e05af7e6edaf9863bae3c012a72
- https://github.com/ipfs/js-ipfs/commit/e3868f48d209f1985579b6be8b00beeccca0c319
