### ISSUE TITLE
object.put(dagNode) gives error: links is immutable, but object.put(dagNode.toJSON().data) works

### ISSUE THREAD

**Issue by fazo96** [ipfs/js-ipfs#1484]
- **Version**: 0.31
- **Platform**: latest nodejs 8 on Linux x64
- **Subsystem**: Object API (from JS, not HTTP)

#### Description:

See https://github.com/ChluNetwork/chlu-ipfs-support/pull/112/commits/2bd6d4c86f76f849dcd7b8efac3c32245ec3c5eb#diff-a8513da2877ad6ccd1d7f8af480d9b21R135

In short, `ipfs.object.put(dagNode)` where `dagNode` is an instance of DAGNode used to work fine. Now it throws an `links is immutable` error.

However, doing `ipfs.object.put(dagNode.toJSON().data)` works fine and looks like it produces the same result.

#### Steps to reproduce the error:

Something like:

```javascript

async function createDAGNode(buf) {esolve, reject) => {
        // DAGNode from ipld-dag-pb
        DAGNode.create(buf, [], (err, dagNode) => {
            if (err) reject(err); else resolve(dagNode);
        });
    });
}

const dagNode = await createDAGNode(Buffer.from('helloo'))

// this works
const multihash = await ipfs.object.put(dagNode.toJSON().data)

// this does not work, but the API Spec supports it and it worked in 0.28.2
const multihash2 = await ipfs.object.put(dagNode)
```

**Comment by marti1125** [comment]
I would like to work in this issue 👍

**Comment by vmx** [comment]
Works on master, got fixed by https://github.com/ipfs/js-ipfs/commit/a82a5dcf7151fc900998578d0e03b3ab522fa244#diff-98e868a7effb24c7531c970fa7e3cd96R186.
