### ISSUE TITLE
version(0.31.4) on windows  not able to install the package.

### ISSUE THREAD

**Issue by ajendrana** [ipfs/js-ipfs#1498]
c:\WAjen\node_ws2>npm install ipfs --global
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
C:\Program Files\node-v8.11.3-win-x64\jsipfs -> C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\src\cli\bin.js

> git-validate@2.2.4 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\git-validate
> node bin/install

WARNING: Unable to find a .git directory for this project, installation aborted.

> fs-ext@1.2.1 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\fs-ext
> node-gyp configure build

C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\node-v8.11.3-win-x64\\node.exe" "C:\\Program Files\\node-v8.11.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\fs-ext
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> gc-stats@1.2.0 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\gc-stats
> node-pre-gyp install --fallback-to-build

[gc-stats] Success: "C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\gc-stats\build\gcstats\v1.2.0\Release\node-v57-win32-x64\gcstats.node" is installed via remote

> keccak@1.4.0 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\keccak
> node-gyp rebuild

C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\node-v8.11.3-win-x64\\node.exe" "C:\\Program Files\\node-v8.11.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\keccak
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ajen\AppData\Roaming\npm-cache\_logs\2018-08-09T16_22_16_928Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 rebuild C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\secp256k1
> node-gyp rebuild

C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\node-v8.11.3-win-x64\\node.exe" "C:\\Program Files\\node-v8.11.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\secp256k1
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.5.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ajen\AppData\Roaming\npm-cache\_logs\2018-08-09T16_22_18_820Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> leveldown@3.0.2 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\leveldown
> prebuild-install || node-gyp rebuild

> rabin@1.6.0 install C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\rabin
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.3 runtime=node arch=x64 platform=win32)

C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\rabin>if not defined npm_config_node_gyp (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\node-v8.11.3-win-x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\node-v8.11.3-win-x64\\node.exe" "C:\\Program Files\\node-v8.11.3-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\node-v8.11.3-win-x64\node_modules\ipfs\node_modules\rabin
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN dirty-chai@2.0.1 requires a peer of chai@>=2.2.1 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@1.2.1 (node_modules\ipfs\node_modules\fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@1.2.1 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rabin@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rabin@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ajen\AppData\Roaming\npm-cache\_logs\2018-08-09T16_22_35_880Z-debug.log

- **Version**:
- **Platform**:
- **Subsystem**:

**Comment by diasdavid** [comment]
@alanshaw @achingbrain we had achieved good UX for Windows, we simply can't break it. 

`rabin` needs to be an optional dependency and checked if it exists when used.

**Comment by ajendrana** [comment]
Thanks @alanshaw , its done.
