### ISSUE TITLE
files.add incorrectly calls importer function

### ISSUE THREAD

**Issue by vijayee** [ipfs/js-ipfs#150]
The call is erroneous:
https://github.com/ipfs/js-ipfs/blob/master/src/core/index.js#L337-L341
when compared to:
https://github.com/ipfs/js-ipfs-data-importing/blob/master/src/index.js#L18
it should be:
```js
this.files = {
    add: (path, options, callback) => {
      importer(path, dagS, options, callback)
    }
  }
```
will pr later to fix

**Comment by nginnever** [comment]
Hey vijayee! 

This was noticed by @bdrieder as well and he created a <a href="https://github.com/ipfs/js-ipfs/pull/104">PR</a> already which opened up a whole can of discussion, mostly about <a href="https://github.com/ipfs/js-ipfs-data-importing/pull/25">data-exporting</a> which I am currently working on . Ultimately we will want to restructure the way data-importing is done as well to match things like sharding in go-ipfs

**Comment by diasdavid** [comment]
> There has also been an idea from @diasdavid to extract the FS things out of the importer and make the importer only take in streams.

I wouldn't call it an 'idea', it is the plan :) ipfs-core shouldn't have to handle fs directly if used programatically. The file streams will come through the http-api, just like go-ipfs handles it.

**Comment by diasdavid** [comment]
Seems that this is fixed now, thank you for reporting :)
