### ISSUE TITLE
Already piped error prevents me to use IPFS

### ISSUE THREAD

**Issue by sorleone** [ipfs/js-ipfs#1502]
I am still getting this error:

https://github.com/libp2p/js-libp2p-switch/issues/235

 with version 0.31.4, is it possible to fix it? Version 0.31.3 seems work better, however it's preventing me to use IPFS because it crashes after a while. This is what I get:

```
js-ipfs/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
```

**Comment by alanshaw** [comment]
dupe of https://github.com/ipfs/js-ipfs/issues/1502

**Comment by alanshaw** [comment]
@sorleone not discarding this issue at all, just keeping the issue count down!
