### ISSUE TITLE
IPFS extension protocol?

### ISSUE THREAD

**Issue by oleiba** [ipfs/js-ipfs#1504]
Question:
Is there any out-of-the-box way to plugin an extension to the usual IPFS wire protocol?
For example, some way to imitate BitTorrent's [BEP010](http://www.bittorrent.org/beps/bep_0010.html) extension protocol.

**Comment by alanshaw** [comment]
AFAIK there's no way to do this right now in js-ipfs. @diasdavid are you able to confirm?

Perhaps @Stebalien knows if something like this exists or has been considered in go-ipfs?

**Comment by alanshaw** [comment]
Of course! Considering this answered @oleiba - shout if you have any other queries!
