### ISSUE TITLE
Webui's BUG:Unexpected token o in JSON at position.

### ISSUE THREAD

**Issue by zy445566** [ipfs/js-ipfs#1511]
![image](https://user-images.githubusercontent.com/14976489/44183509-dac1a180-a13d-11e8-91fd-0da1eaa9c826.png)
Maybe not use "toString" but "JSON.stringify"?
report this error when `jsipfs daemon`

**Comment by alanshaw** [comment]
thanks @zy445566, I've reposted it [here](https://github.com/ipfs-shipyard/ipfs-webui/issues/747) for the GUI team to take care of
