### ISSUE TITLE
Disconnect From Pubsub Peer

### ISSUE THREAD

**Issue by sorleone** [ipfs/js-ipfs#1517]
Since Pubsub topics are open, I'd love to be able to disconnect from a peer that's sending a lot of spam. I have tried `ipfs.swarm.disconnect` or `ipfs._libp2pNode.hangUp` but they doesn't seem to work since I keep getting messages from the peer I disconnect. What can I do?

**Comment by alanshaw** [comment]
I don't believe there's any controls to do this. Disconnecting from the node that sent the message won't work if any of the other nodes you're connected to are also connected to it.

**Comment by sorleone** [comment]
@alanshaw I read that making pubsub topics private or protected by passwords is kind of hard... So can't you guys give us the possibility to disconnect from peers who spam? What's the purpose of `ipfs.swarm.disconnect` or `ipfs._libp2pNode.hangUp` then? In the meantime do you think that having random/hard to guess topic names could be a way to protect from this?

**Comment by alanshaw** [comment]
> So can't you guys give us the possibility to disconnect from peers who spam?

You can do that with `ipfs.swarm.disconnect`, but pubsub messages don't always come directly from the peer who sent them, they are propagated around the network by other peers. So disconnecting from a node that is doing spamming isn't necessarily going to stop messages that they send from getting to you.

This feature needs a different pubsub implementation, which has been in the pipeline for a while now but has unfortunately not yet bubbled up to the top of the priority list. Take a look at https://ipfs.io/blog/25-pubsub/. I'd guess that the "authenticated mode for pubsub topics" is close to what you're looking for!

Hope that helps!
