### ISSUE TITLE
Without a daemon running we cant ipfs cat an non-local cid with the CLI.

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#1527]
- **Version**: all
- **Platform**: all
- **Subsystem**: CLI

#### Description:
Without a daemon running we cant ipfs cat an non-local cid with the CLI.
Should we start a node in the cli code path?
https://github.com/ipfs/js-ipfs/blob/1fb71f2fe9182e95db913504ed7b933d3b7ca4a4/src/cli/utils.js#L47-L73

I think this worked before but that might have been a bug that is now fixed. Go cli also needs a daemon running.
If we keep this as is we need to change https://js.ipfs.io getting started section. Check below.

#### Steps to reproduce the error:
Go to https://js.ipfs.io and try to follow the getting started section, right now when you try to run the CLI part you would need an extra step to start a local daemon manually.

**Comment by diasdavid** [comment]
@hugomrdias good question. There isn't a clear agreement on what it should do. 

I've experience go-ipfs sometimes turning on the daemon, others just saying that the daemon is not on. @Stebalien could you comment?
