### ISSUE TITLE
Adding files with cid version 1 breaks `pin ls`

### ISSUE THREAD

**Issue by victorb** [ipfs/js-ipfs#1531]
- **Version**:  js-ipfs version: 0.31.7 (46222e1093b8919f572fd948612bd436a4376e31)
- **Platform**: Linux niue 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: CID,pin

#### Type:
Bug

#### Severity:
Medium

#### Description:

Adding files with `--cid-version=1` specified makes running `pin ls` output error `Invalid version, must be a number equal to 1 or 0`

#### Steps to reproduce the error:

```console
$ export IPFS_PATH=$(mktemp -d)

$ node src/cli/bin.js init
initializing ipfs node at /tmp/tmp.ymsJeqqGem
generating 2048-bit RSA keypair...done
peer identity: QmSjwLPSR54YspcuLLQEvbUvDJyNBQLCGmAvtmLqSfwUFn
to get started, enter:

        jsipfs files cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme


$ node src/cli/bin.js add -r --cid-version=1 test/fixtures/greater-than-default-max-chunk-size
added zdj7WbyyZoWVifUHUe58SNS184PpN8qAuCP6HpAY91iA8CveT greater-than-default-max-chunk-size

$ node src/cli/bin.js pin ls
/home/user/projects/ipfs/js-ipfs/node_modules/cids/src/index.js:235
      throw new Error(errorMsg)
      ^

Error: Invalid version, must be a number equal to 1 or 0
    at Function.validateCID (/home/user/projects/ipfs/js-ipfs/node_modules/cids/src/index.js:235:13)
    at new CID (/home/user/projects/ipfs/js-ipfs/node_modules/cids/src/index.js:105:9)
    at toB58String (/home/user/projects/ipfs/js-ipfs/src/core/components/pin.js:26:10)
    at nodes.map (/home/user/projects/ipfs/js-ipfs/src/core/components/pin.js:60:35)
    at Array.map (<anonymous>
    at dag._getRecursive (/home/user/projects/ipfs/js-ipfs/src/core/components/pin.js:60:12)
    at mapAsync (/home/user/projects/ipfs/js-ipfs/src/core/components/dag.js:160:11)
    at /home/user/projects/ipfs/js-ipfs/node_modules/async/internal/map.js:32:9
    at /home/user/projects/ipfs/js-ipfs/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/home/user/projects/ipfs/js-ipfs/node_modules/async/eachOf.js:60:13)

```

**Comment by alanshaw** [comment]
@VictorBjelkholm do you know if this happens in master? We fixed https://github.com/ipfs/js-ipfs/issues/1518 recently - it might have effected it.

**Comment by VictorBjelkholm** [comment]
@alanshaw yes, this happens on current master (commit 46222e1093b8919f572fd948612bd436a4376e31)

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
