### ISSUE TITLE
Is it possible to setup a private IPFS network ?

### ISSUE THREAD

**Issue by maroodb** [ipfs/js-ipfs#1545]
I am developing a focused enterprise application that needs to distribute data and p2p file sharing, 
I want to know if is it possible to setup a private IPFS network?

**Comment by alanshaw** [comment]
@maroodb what do you mean by private exactly? You can completely customise the libp2p stack for your IPFS node, so you could in theory disable any discovery mechanisms that would allow your IPFS node to connect to nodes outside of your "network". See https://github.com/ipfs/js-ipfs#optionslibp2p.

Does that answer your question?
