### ISSUE TITLE
Reset config

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#1547]
Is there an api for resetting the repo config file to it's default value?  For when you've really stuffed things up but haven't restarted the daemon and want to reset to a known good state.

**Comment by alanshaw** [comment]
Not that I'm aware of but I think it's a good idea - @Stebalien & @diasdavid what do you reckon?

**Comment by diasdavid** [comment]
I like this! When resetting, keep the current config with config.json.bak so that users have a way to recover from a reset.

**Comment by olizilla** [comment]
How about moving this to https://github.com/ipfs/interface-ipfs-core so we can start to consolidate all the api proposals in one place?

**Comment by achingbrain** [comment]
Closing in favour of https://github.com/ipfs/interface-ipfs-core/issues/372
