### ISSUE TITLE
Files.cat is never getting called in watcher - Also no error!

### ISSUE THREAD

**Issue by patientplatypus** [ipfs/js-ipfs#1555]
Hi! I am getting very strange behaviour where a watcher on a variable can not trigger a  `this.ipfs.files.cat` command, but it does elsewhere. So this appears to be a `non-symmetric` error that is behaving very strangely. For the full code example please see this stackoverflow post: https://stackoverflow.com/questions/52262863/ipfs-files-cat-is-never-getting-called. I am calling this a problem with the library (as far as I can tell) because if the function is being called there needs to at least be error handling if something wrong is occurring.

If anyone can comment, please let me know! Thanks!

**Comment by alanshaw** [comment]
My guess is that `files.cat` _is_ being called but it cannot find the CID you're providing it. What version of js-ipfs are you using?

**Comment by patientplatypus** [comment]
Ah! Somehow it is now working - there is some significant lag time in retrieving the data (3-4 seconds depending on size) and I must have fixed a previous error, saw that it was not loading and continued thinking there was a bug. Apologies, and thanks for getting back to me.
