### ISSUE TITLE
Cannot create so many PeerConnections Error

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#1561]
- **Version**: 0.32 & 0.31
- **Platform**: Chrome

#### Description: 

Leaving js-ipfs running in Chrome while working on ipld-explorer, I've just started seeing lots of

**Uncaught DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections**

```
index.js:88 Uncaught DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Peer (http://localhost:3000/static/js/0.chunk.js:212931:14)
    at ClassIsWrapper.dial (http://localhost:3000/static/js/0.chunk.js:106314:21)
    at timeout (http://localhost:3000/static/js/0.chunk.js:97790:30)
    at http://localhost:3000/static/js/0.chunk.js:6579:12
    at http://localhost:3000/static/js/bundle.js:8182:12
    at DialQueue._dialWithTimeout (http://localhost:3000/static/js/0.chunk.js:97797:25)
    at DialQueue._doWork (http://localhost:3000/static/js/0.chunk.js:97752:10)
    at DialQueue.queue.queue (http://localhost:3000/static/js/0.chunk.js:97736:12)
```

The instance is still functional, but it's one of those error messages that will worry people as it's large and red.

<img width="1088" alt="screenshot 2018-09-13 17 54 10" src="https://user-images.githubusercontent.com/58871/45503210-0f953880-b77e-11e8-8ff1-3aae88ebf141.png">

#### Steps to reproduce the error:

Create a js-ipfs instance in the browser, passing no custom opts. Leave it running for 5mins.

**Comment by olizilla** [comment]
> This is a leak in Google Chrome which started to manifest in version 65.0.3300.0.

- https://github.com/webtorrent/webtorrent/issues/1349#issuecomment-418003136
- https://bugs.chromium.org/p/chromium/issues/detail?id=825576#c24

**Comment by olizilla** [comment]
What is interesting is i can leave https://explore.ipld.io open for > 10mins in a chrome tab with 0 errors, but working on it locally the errors show up after a couple of minutes. The significant differences between the two are https vs localhost and minified code vs unminified.

**Comment by alanshaw** [comment]
@jacobheun would you be able to look into this one?

**Comment by jacobheun** [comment]
@alanshaw I can take a look.

**Comment by jacobheun** [comment]
@olizilla do you know how many peers your node had? I've had a basic client running the latest ipfs in chrome for a couple of hours and haven't hit the error. I do see lots of websocket errors though (which also need to get addressed).

My peer count is currently floating around 320.

**Comment by olizilla** [comment]
huh. Running ipld-explorer locally I start getting those error after ~2 mins and with 8 peers.

**Comment by olizilla** [comment]
ipld-explorer inits js-ipfs like this
https://github.com/ipfs-shipyard/ipld-explorer/blob/d17e6f5d3ee32ab63bc6be94d72455018f24c07e/src/bundles/ipfs.js#L96-L103

It uses a dynamic import to load in the bundle once we're sure it's needed, and then passes any user opts to it at instantiation, which will just be an empty object if there is nothing under the `ipfsOpts` key in `localStorage`, which is the case when I get these errors.

**Comment by jacobheun** [comment]
Okay, if I can't replicate with a basic instance, I will grab the explorer code and give that a go.

**Comment by jacobheun** [comment]
In order to replicate this with a basic js-ipfs instance I needed to add the wrtc star discovery server address to the swarm list.

```js
const ipfs = new Ipfs({
  config: {
    Addresses: {
      Swarm: [ '/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star' ]
    }
  }
})
```

I've got a fix for catching these errors at https://github.com/libp2p/js-libp2p-webrtc-star/pull/157

**Comment by jacobheun** [comment]
libp2p-webrtc-star@0.15.5 is now live and resolves this.

**Comment by arnWolff** [comment]
Catching errors but still not be able to create new webrtc connections until GC strike isn't a proper fix IMHO.
Invoking GC by revoking some data buffers placeholder seems a better one:

[create & revoke ObjectURL](https://stackoverflow.com/questions/66546934/how-to-clear-closed-rtcpeerconnection)
