### ISSUE TITLE
key problems on new Ipfs

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1568]
async function mkPeerId() {
            //pks8 format
            var keyPEM = "-----BEGIN ENCRYPTED PRIVATE KEY-----\n" +
                "MIIFODBiBgkqhkiG9w0BBQ0wVTA0BgkqhkiG9w0BBQwwJwQQ9/ZfKn7qG9Rw1SaG\n" +
                "osVErQICJxACASAwDAYIKoZIhvcNAgsFADAdBglghkgBZQMEASoEEIoxnUthPDsV\n" +
                "LqqkYIJQBLcEggTQbYE0ZYjYI+BHF+SsF5wLWjmC4VyPyMGsl58CTOXwpNTi081d\n" +
                "CPQTWGnmkQbAwM3YtDkNRL5m5r1uucK13CfsqIbZikhtJN1dKkrMLE+Wl06nRdJN\n" +
                "p+v7Nc7mXs/txkn07X0QHjETx3EbGnaoKau2YnnK2t0JivICVtgA1CgQ7H2bsch1\n" +
                "d0auKyBad0mHQx04X6iXhOuuaYlccfAblEuoznpjEurkSkPVMEFcdDwkI4VvH4ZK\n" +
                "lJfY66yrAibIzQGYQHRh046MYdWS2AyWdKdjDHL8ELcZL7B+vWhmJbeTWkbNonCL\n" +
                "zeZuWY70SN6ykpPH4l+2XLvRxdtOqxrGjv7cR57nrCP0WnZhJwR0o8wmTXX+DLR1\n" +
                "2QxUghtULFjJH1jlycYVjPvdbQlD5ARUR5qbelWW+pRVh3cwkU7TEgp3kUCgyq3i\n" +
                "WuYF7ycUgzSZUBx4BjKEdePTOtXzlIiVC7SD+WYxGa4nF0J0JtIGVIFCT5rcBGmO\n" +
                "dERC1KkhsaXGQmPp+vsxTnG9sMrFBp02Ci5DWYns1+A7Cetqxa2YbCdSjH1Iu0wn\n" +
                "kk5VasRj2w9PvpGwKnp/yKDeRIkY9Nwqg86wEPqmPk85eFYeKPprB/Vi1HhGHUue\n" +
                "ai+I9gYSd055PyWoU0fXMX2fIfnkEI2jpaeOPodqak3ld5WDjiC9aGmUluBNzKVD\n" +
                "ZwItrIzJqFBvjirGT79SJyCr3SgUokR1PXB70s56l3Mm0/AHTBbl29G/WT+3p4NA\n" +
                "CHXHVOBYU0QWv7KzbSsrxChXQbjdeLIAl0n3j2tLZWa3wtsJxISpJMTY3Vbs8fxm\n" +
                "xvPfhDqM7LwdtU3mScBchDo/jyuQBYx8MEPcPbnbUUciMv2gf62ZEPCXRTPZClHu\n" +
                "3ijx4J4Pr4u5RTmuS82mmKLXLB60hnje/gvWDlfkKfYvIAfrBF0UnGTOsrposz/9\n" +
                "e0lgmZfG30WBJiIUwSDn8AsdnQCSUarP5d0PJtbY/iwZAWz38GH9ijs/lqfrCZVp\n" +
                "XwhSVoEqvdPyrWwyC6O8j87IeOm6f32iZwtyhwiZ1wHZo2kk19QZ67gIG/FnX7Il\n" +
                "zFNinFKJibma/sAgD6BIM88Jt3slGzw4fASYUeJKIdQdcei4uQZl0dmzmcafKA8m\n" +
                "p+fDOfP+FK0ZSmCZ5JmjiiuU3+n2KVZ5PkWnc/eyG3sUxvf81ePhrXrkmxGfeY/j\n" +
                "H6kVCW0ip+vwalQOssStsyz5WhOhSffkAVd9jvOQmaNaDMeMDIAIPXV5kA6JWQ7V\n" +
                "EWDV6w1qSDk/B+lnzcdoJXVhBHDykD8rZediQNZzmOhKjKq6YL65yuy18WnarhPT\n" +
                "nfFUj7IkYAljGSmutZd+nUsVspAsLJvo7UFu/8IwzXpVLZDC/Cj06VnokptUxqd6\n" +
                "H+Y8e5dv/CCmaShs42uQmpeDg1lsDcYm3IJ7L2NKNc9jFG3GcHCZb3iaUufD1G+C\n" +
                "91xjP4k9Jq2gy3WgXE7n09SScnhVvW/5wqWTqrO39O93Qjsv0ebpRUwFw+f37tVv\n" +
                "WHZ+s0W2XtoAtta88jDTHOl+a8J3XgyERi2on6voxppTGnBlDVb5oXnBRMEXezxk\n" +
                "6ToZxZaZnPTgg/g3dCLGN01KmPGlB8nbNO/yCWHhdceoH3uGrrDqTHTlqpc=\n" +
                "-----END ENCRYPTED PRIVATE KEY-----";
            var tmpIpfs = new Ipfs({
                start: false
            });
            tmpIpfs.util.crypto.keys.asyncImport = Promise.promisify(tmpIpfs.util.crypto.keys.import);
            var oKey = await tmpIpfs.util.crypto.keys.asyncImport(keyPEM, "12345678901234567890");
            tmpIpfs.types.PeerId.asyncMkPeerId = Promise.promisify(tmpIpfs.types.PeerId.createFromPrivKey);
            return await tmpIpfs.types.PeerId.asyncMkPeerId(oKey.bytes);
        };

        var ipfsNode=new Ipfs({pass:"12345678901234567890",init:{privateKey:await mkPeerId()}});

      i expect that the node would use my private and public key from the pem ,but not in fact!!why?

**Comment by alanshaw** [comment]
@mccoysc what version of js-ipfs are you using? How are you verifying your `privateKey` is not being used?

**Comment by mccoysc** [comment]
@alanshaw 0.32 version.
in my mind,every time if i use the same PEM file to new IPFS,the node id sdould be nerver changed.but it's changed per new IPFS

**Comment by mccoysc** [comment]
and also i have saw that in the localStorage,ipfs module saved a key-value named with the ipfs node's Id,it's changed every i new IPFS

**Comment by alanshaw** [comment]
@mkg20001 do you have any time to look into this bug report?

**Comment by mccoysc** [comment]
is the bug fixed?

**Comment by mccoysc** [comment]
i have fixed this bug:
if new Ipfs({init:{privateKey:peerId}}) and peerId is an instance of PeerId object,
the extend function in IPFS constructor only copy the data part of options object, those non-data-fields would be lost, __prototype__ ,eg.
so,some field which really is an object should be set value with more attentions
