### ISSUE TITLE
Is there any way to store mutable objects in ipfs?

### ISSUE THREAD

**Issue by ajayrao80** [ipfs/js-ipfs#1569]

**Comment by alanshaw** [comment]
@ajayrao80 the two ways you cna do this are through MFS (https://docs.ipfs.io/guides/concepts/mfs/) and [IPNS](https://docs.ipfs.io/guides/concepts/ipns/). In js-ipfs we don't have a full IPNS implementation yet but you can use MFS now and it works really well :D [API docs for MFS are here](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#mutable-file-system). Hope that helps.

**Comment by ajayrao80** [comment]
Well, I added files like this:

```
const files = [
  {
    path: '/file.txt',
    content: Buffer.from("Content")
  }
]

ipfs.files.add(files, function (err, files) {
  console.log(files) })
```
files was an object containing path "/file.txt" and the hash.

Then I tried to write to it like this:

```
ipfs.files.write('/ajfile.txt', Buffer.from('Hello, world!'), (err) => {
  console.log(err)
})
```
Got an error saying file does not exist.
