### ISSUE TITLE
How control file access in IPFS?

### ISSUE THREAD

**Issue by maroodb** [ipfs/js-ipfs#1577]
I can't find  a way to control read/write access in IPFS,
so how to control access ?

**Comment by alanshaw** [comment]
For read, content in your IPFS repository is accessible to all connected peers as long as they know the hash. There's currently no way to restrict this, but you could encrypt the content yourself and share the decryption key with the peers you want to have access. Note this facility is not provided by IPFS. Check out https://github.com/jbenet/ipfs-senc for an example.

By default, write access is restricted to the CLI on your local computer and the HTTP API binds to 127.0.0.1 so is not accessible to the outside world. There's currently no HTTP auth provided by IPFS - if you want expose the API to the internet and restrict access you'll need to set that up yourself.

Hope that helps.

**Comment by maroodb** [comment]
Encryption doesn't solve the problem:
for example when **A** share the key with **B**, there is **no guarantee** that **B** dont share the key with others nodes without A permission's.
Thank you :)
