### ISSUE TITLE
Mutable file system issue

### ISSUE THREAD

**Issue by ajayrao80** [ipfs/js-ipfs#1579]
#### Description:
I was working with MFS. I created a file like this.

```
let opts = {
  truncate: true,    
  create: true       
}

ipfs.files.write('/a.txt', Buffer.from('Hello, world!'), opts, (err) => {
  console.log(err)
})
```
I could change the values and read the changed values on the instance I was working with but not on different machine/instance.
How do I get the IPFS link of the mutable file or how can I put it in IPFS network ?

**Comment by ajayrao80** [comment]
Ok. I solved the above problem but the problem is as soon as I write the content to a mutable file, it's hash changes (including the hash of the directory). How do I access the updated file from different machines?

**Comment by alanshaw** [comment]
Right now this is more difficult in js-ipfs than it should be. We have [IPNS](https://docs.ipfs.io/guides/concepts/ipns/) on the way to allow you to setup a mutable pointer to some content. You could also use pubsub to advertise the fact the content has changed.

For general support like this, please consider using https://discuss.ipfs.io/
