### ISSUE TITLE
Gateway support for browsers

### ISSUE THREAD

**Issue by renne** [ipfs/js-ipfs#1590]
#### Type: Feature

Especially with the [Cloudflare IPFS gateways online now](https://blog.cloudflare.com/distributed-web-gateway/) it would be great if a browser can bootstrap index.html and js-ipfs via HTTPS and then load static content via js-ipfs.

This should be possible with just adding a script-tag in index.html.

**Comment by lidel** [comment]
FYI there is IPFS gateway fully running on a Service Worker:
- https://github.com/ipfs-shipyard/service-worker-gateway

**Comment by renne** [comment]
If I understand [service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway) correctly, it runs on IPFS-HTTP(S) gateways. What I have in mind is

1. loading [js-ipfs](https://github.com/ipfs/js-ipfs) via an IPFS-HTTP(S) gateway
2. run [js-ipfs](https://github.com/ipfs/js-ipfs) as a service worker **in the browser**
3. [js-ipfs](https://github.com/ipfs/js-ipfs) catches all relative links and loads them via IPFS instead of HTTP(S)

**Comment by alanshaw** [comment]
Unless I'm missing something @renne what your describing is pretty much exactly what https://github.com/ipfs-shipyard/service-worker-gateway does...
