### ISSUE TITLE
some time "this.listenersRefs[Object.keys(this.listenersRefs)[0]]" is undefined and throw and error.

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1593]
const sioClient = this
      .listenersRefs[Object.keys(this.listenersRefs)[0]].io

some time "this.listenersRefs[Object.keys(this.listenersRefs)[0]]" is undefined and throw and error.

this line is in libp2p-webrtc-star/src/index.js @line 63

**Comment by achingbrain** [comment]
This might belong in the https://github.com/libp2p/js-libp2p-webrtc-star - could you please open an issue there along with an example that replicates the problem?
