### ISSUE TITLE
Ipfs.setMaxlisteners is not effective

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1597]
warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

though i call Ipfs.setMaxlisteners(1024),it's not effective,throw the above warnings

**Comment by alanshaw** [comment]
Are you using pubsub? If so you'll need to call that on the pubsub component e.g.

```js
ipfs.pubsub.setMaxListeners(1024)
```

https://github.com/ipfs/js-ipfs/blob/549f2f63e19bc8ae9dfcd7a785f083f29d3c069f/src/core/components/pubsub.js#L50-L52

**Comment by valmack** [comment]
I just tried this but got an error that `setMaxListeners` does not exist on the object

Using `"ipfs": "0.52.2"` and creating the ipfs object like so
```js
const ipfs: IpfsApi = await IPFS.create(opts)
ipfs.pubsub.setMaxListeners // throws error here
```
