### ISSUE TITLE
"ready" event is not triggered 

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1598]
Ipfs.on("ready",function(err){

})

if error ,the error event would be triggered but ready would never be triggered which cause the ready not work.
i suggest that if in waiting for "ready" state,after trigger the "error","ready" should be triggerd

**Comment by alanshaw** [comment]
Hmm, I'm not sure I agree. If there was an error starting the node it is not ready and never will be.

**Comment by mccoysc** [comment]
but why "ready"'s callback function has a argument "err"?
and another situation:
i make the on or once function async and i await the async ready like this:
await asyncOnce("ready");

it would be block forever if no any event triggered

**Comment by bingge1** [comment]
不解决问题就把单关了，真的社会！
