### ISSUE TITLE
Uncaught TypeError: sort is not a function

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1599]
Uncaught TypeError: sort is not a function
    at Function.e.exports [as create] (create.js:39)
    at Object.t.deserialize (util.js:75)
    at y (index.js:376)
    at c (waterfall.js:16)
    at f (waterfall.js:23)
    at onlyOnce.js:12
    at getMany (index.js:207)
    at map.js:32
    at once.js:12
    at f (eachOf.js:60)
    at onlyOnce.js:12
    at map.js:29
    at once.js:12
    at f (waterfall.js:21)
    at onlyOnce.js:12
    at e.get (blockstore.js:84)

code:
  const sortedLinks = sort(links, linkSort)
@ipld-dag-pb/src/dag-node/create.js:39

**Comment by mccoysc** [comment]
this maybe caused by the stable.js at line 5 which end with ":".
when loaded,throw an warning:unexpected token

**Comment by alanshaw** [comment]
@mccoysc do you have some example code you can post so that we can reproduce the error?

**Comment by mccoysc** [comment]
the error is not caused by my code using.
it's caused by the bad write code:

  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global.stable = factory());

for no any ";" used,may webpack compile these code in an improper way and then cause a illegal compiled  code.

so,i modify the original code and make a mistake and cause an error.

but still, i suggest you change the code like this:
if (typeof exports === 'object' && typeof module !== 'undefined') {
    module.exports = factory();
  } else {
    if (typeof define === 'function' && define.amd) {
      define(factory);
    }esle{
      global.stable = factory();
    }
  }
