### ISSUE TITLE
Browser: where is ipfs.pubsub?

### ISSUE THREAD

**Issue by klueq** [ipfs/js-ipfs#1605]
It seems `libp2p` doesn't create `pubsub` currently.

Is there a way to enable this locally?

**Comment by VictorBjelkholm** [comment]
Yes, it's not set automatically as pubsub is an experimental feature and you need to explicitly enable it when starting the daemon.

See https://github.com/ipfs/js-ipfs/blob/9a37ac0eefbdab94ef577f35f97b77a8e1594a50/examples/exchange-files-in-browser/public/app.js#L42-L54

**Comment by klueq** [comment]
This works. Thanks a lot!
