### ISSUE TITLE
ipfs.p2p API

### ISSUE THREAD

**Issue by klueq** [ipfs/js-ipfs#1607]
Are there plans to implement p2p API, i.e. sending arbitrary messages to a specific peer?

If not, do you think it's reasonable to extend the pubsub API and say that `ipfs.pubsub.publish(peerid, message)` sends the message directly to that peer?

If not, could you give some hints about the best way to enable this functionality locally in my app? Right now I'm thinking to take a shortcut: find out how `pubsub` sends p2p messages and change it to allow sending arbitrary messages.

**Comment by alanshaw** [comment]
It's not an immediate priority but js-ipfs is aiming to have feature parity with go-ipfs so I wouldn't have thought it was "off the table" so to speak. @diasdavid are you able to comment?
