### ISSUE TITLE
Upgrade to latest `ipld-dag-cbor`

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs#1610]
We made a pretty [big change](https://github.com/ipld/js-ipld-dag-cbor/pull/76) to the `ipld-dag-cbor` API.

Instead of using `{"/": baseEncodedString}` to express links we're just using `CID` instances.

This will probably end up simplifying a bunch of code in `js-ipfs` but it will be a pretty impactful change. For encoding, we still support the old form, so you only need to move to the new way once you find it necessary. But, there's a breaking change on the decoder side because all links are now `CID` instances.

The direct `ipld-dag-cbor` dep is barely used, it's mostly used by deps of deps:
```
├─┬ interface-ipfs-core@0.78.0
│ └── ipld-dag-cbor@0.12.1
├─┬ ipfs-api@24.0.2
│ └── ipld-dag-cbor@0.12.1
├─┬ ipfsd-ctl@0.39.2
│ └─┬ ipfs-api@23.0.0
│   └── ipld-dag-cbor@0.12.1
├─┬ ipld@0.17.3
│ └── ipld-dag-cbor@0.12.1
└── ipld-dag-cbor@0.21.1
```

What's the best strategy for getting all the deps of the deps updated and into a release?

We don't want to release "ProtoSchool 1.0" until this changes is in a `js-ipfs` release. Link creation w/ `ipfs.dag.put` in IPFS is a big part of the basic tutorials and the new API is much nicer and easier to teach and we'd hate to teach people the old API and then change it a month later. But this also means that this dep upgrade will end up being a blocker for ProtoSchool if it lingers for too long.

**Comment by vmx** [comment]
I'm currently working on it. It seems easier than I thought, only flaky tests make it a bit harder.

**Comment by alanshaw** [comment]
The direct dependency on `ipld-dag-cbor` was removed in https://github.com/ipfs/js-ipfs/pull/1626 and IPLD was upgraded to a version including the breaking API changes here https://github.com/ipfs/js-ipfs/pull/1668. This will be in the upcoming js-ipfs 0.33 release.
