### ISSUE TITLE
pubsub: Does it work?

### ISSUE THREAD

**Issue by klueq** [ipfs/js-ipfs#1613]
I'm not able to get any messages in my js-ipfs node. Messages are sent from a go-ipfs node running on the same host:

```
ipfs pubsub pub test 12345
```

This is my JS code:

```js
window.ipfs = new Ipfs({
  EXPERIMENTAL: {
    pubsub: true
  }
});

ipfs.once('ready', () => {
  console.log('ipfs ready');
  ipfs.pubsub.subscribe('test', (...args) => {
    console.log('pubsub:', ...args);
  });
});
```

I've checked `pubsub ls` and `pubsub peers` stats in both nodes - they look ok. The JS node can send a message to itself, however neither go->js nor js->go directions work.

Do I miss anything obvious?

**Comment by klueq** [comment]
I've tried versions 26, 27, 28, 29, 30. Also added the ws-star config. Still doesn't work.

```js
window.ipfs = new Ipfs({
  repo: 'ipfs-' + Math.random().toString(16).slice(2),
  config: {
    Addresses: {
      Swarm: [
        '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
      ]
    }
  },  
  EXPERIMENTAL: {
    pubsub: true
  }
});

ipfs.once('ready', () => {
  console.log('ipfs ready');

  ipfs.pubsub.subscribe('test', (...args) => {
    console.log('pubsub:', ...args);
  }).then(res => {
    console.log('pubsub ready');
  }, err => {
    console.log('pubsub:', err);
  });
});
```

**Comment by klueq** [comment]
I dared to debug it and found this chunk of code:

```js
  _forwardMessages (topics, messages) {
    this.peers.forEach((peer) => {
      if (!peer.isWritable || !utils.anyMatch(peer.topics, topics)) {
        return
      }
```

Basically, it checks if any of the 10 or so peers is interested in the topic I want to publish to, sees that nobody cares about my topic (what a surprise!) and gives up.

I must be misunderstanding how pubsub is supposed to work. I thought the whole point is to deliver messages to nodes that are many hops away: if two nodes are on the opposite poles of the globe and have no way to discover each other, they can still talk to each other via pubsub as long as they are subscribed to the same topic. However the chunk of code above implies that all the nodes in the "pubsub" room must be already connected to each other.

**Comment by alanshaw** [comment]
Possibly related to #1565

**Comment by mccoysc** [comment]
how can i resolve this issue?

**Comment by fazo96** [comment]
As far as I understand, pubsub will deliver messages many hops away but every node on the route has to be subscribed to the topic.

There is a feature that looks in the DHT to try to connect to nodes subscribed to the topic, so your node can discover other interested nodes and connect directly, but this won't work well until the DHT is done for js-ipfs.

The only current solution is that you make sure your nodes are all connected to each other well by doing things at the application level (like get them to connect via WSS to a well known always-online node that is subscribed to the topic) or you need to use something like websocket-star that makes your nodes automatically connect to each other

**Comment by alanshaw** [comment]
@klueq are you able to confirm that the behaviour @fazo96 is describing is what you’re experiencing or is there a bigger issue?

**Comment by klueq** [comment]
@alanshaw, what @fazo96 is saying looks right, but the thing is that `pubsub` doesn't seem to work even in `go-ipfs`: I'm not getting any messages on the `chat` topic. I suspect that if the number of subscribers is low, then even DHT discovery won't work well (though I admit that I very vaguely understand how DHT works in `pubsub`). You can try it yourself - I've never seen any single message on the `chat` topic, despite that topic should be fairly popular.

**Comment by alanshaw** [comment]
We have interop tests that prove pubsub works between go<->js(Node)<->js(browser) so this _must_ be a configuration issue or something similar. If you figure it out and there is a problem in ipfs then please open an new issue.

Also, it might be worth checking out https://github.com/tableflip/ipfs-pubsub-chat-example

**Comment by aphelionz** [comment]
@alanshaw Are those interop tests available? I'm having a heck of a time going between the browser / go / node.js and would love to see how it's properly done.

**Comment by alanshaw** [comment]
https://github.com/ipfs/interop

**Comment by aphelionz** [comment]
Thank you!
