### ISSUE TITLE
The published non-minified build is minified.

### ISSUE THREAD

**Issue by klueq** [ipfs/js-ipfs#1614]
https://unpkg.com/ipfs@0.32.3/dist/index.js

This probably causes troubles with pubsub.

**Comment by klueq** [comment]
This is the latest non-minified build:

https://unpkg.com/ipfs@0.30.1/dist/

Apparently, this was broken recently.

**Comment by VictorBjelkholm** [comment]
This has been resolved but will only appear correct after another release.

**Comment by alanshaw** [comment]
I'm going to close this @klueq - please open a new issue if you see the issue again after the next release is made.
