### ISSUE TITLE
Uncaught Error: unexpected error getting the ipns record  

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#1620]
- **Version**: 0.32.3
- **Platform**: Browser
- **Subsystem**: ?

#### Description:

Error starting IPFS node:

```
Uncaught Error: unexpected error getting the ipns record  �F�W��if4w~}k��*X�%v�5Q3W�AC0t� from datastore
      at _repo.datastore.get (node_modules/ipfs/src/core/ipns/publisher.js:184:35)
      at node_modules/levelup/lib/levelup.js:168:14
      at node_modules/encoding-down/index.js:51:21
```

This doesn't happen in v0.32.2.

#### Steps to reproduce the error:

I start IPFS with the following config options: https://github.com/ipfs-shipyard/peer-star-app/blob/master/src/transport/ipfs.js#L15

**Comment by vasco-santos** [comment]
Hey @pgte 

I debugged this problem and I think that I understood the problem. The way the error `not found` was being handled changed in the new version in an effort to have the errors handled the same way by all our datastores.

[js-ipfs@v0.32.2/core/ipns/publisher.js#L194](https://github.com/ipfs/js-ipfs/blob/v0.32.2/src/core/ipns/publisher.js#L194)
[js-ipfs@v0.32.3/core/ipns/publisher.js#L180](https://github.com/ipfs/js-ipfs/blob/v0.32.3/src/core/ipns/publisher.js#L180)

However, in the `peer-star-app` you are using `levelup`. And they handle the `notfound` error as we did before, [levelup/lib/levelup.js#L160](https://github.com/Level/levelup/blob/master/lib/levelup.js#L160).

@alanshaw what is your opinion here? Should we try to validate both type of errors?

**Comment by alanshaw** [comment]
For now we should check for both error types.

The datastore being used by `peer-star-app` needs to start using the [error codes defined in the interface](https://github.com/ipfs/interface-datastore/blob/master/src/errors.js) and we need to add documentation to the interface-datastore README that states when they should be used.

/cc @jacobheun

**Comment by jacobheun** [comment]
@pgte https://github.com/ipfs-shipyard/peer-star-app/pull/72 should resolve the issue for `peer-star-app`

**Comment by vasco-santos** [comment]
Thanks @jacobheun 🚀 

I also created a PR for checking the other error.

**Comment by alanshaw** [comment]
@jacobheun/@pgte can we close this now?

**Comment by jacobheun** [comment]
Yes, peer-star-app has been updated to reflect the latest datastore changes.
