### ISSUE TITLE
Callback was already called when build with prod flag under angular cli

### ISSUE THREAD

**Issue by mmsqe** [ipfs/js-ipfs#1624]
- **0.32.3**:
- **Mac OS X**:

#### Steps to reproduce the error: 
1. new IPFS()
2. ng build --prod

**Comment by alanshaw** [comment]
@mmsqe thanks for reporting - are you able to provide an example repo we can use to look into the error - I'm not an expert with Angular so I need some more info on the setup to be able to help!

**Comment by mmsqe** [comment]
this issue is related to [uglify]( https://github.com/angular/angular-cli/issues/11439) lib in Angular 6+, no error found after built with Angular CLI: 7.0.0-rc.3, sorry for the wrong reporting, feel free to close this issue.
