### ISSUE TITLE
Uncaught Error: Payload content length greater than maximum allowed: 1048576

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1638]
when write big data to IPFS Node using addReadableStream,got the error:
Uncaught Error: Payload content length greater than maximum allowed: 1048576
    at IpfsApi.js:1
    at t.exports.r (IpfsApi.js:1)
    at t.exports.r.emit (IpfsApi.js:1)
    at t.exports.h._connect (IpfsApi.js:1)
    at IpfsApi.js:1

**Comment by mccoysc** [comment]
the remote node is js-ipfs node

**Comment by mccoysc** [comment]
POST http://XXXX.XXX.XXX:5001/api/v0/add?wrap-with-directory=true&stream-channels=true 413 (Payload Too Large) Error

**Comment by mccoysc** [comment]
how can i change the limit?

**Comment by mccoysc** [comment]
@alanshaw

**Comment by alanshaw** [comment]
I believe this is due to Hapi's `maxBytes` option, which apperas to currently be set at the default (1024 * 1024)

**Comment by mccoysc** [comment]
> I believe this is due to Hapi's `maxBytes` option, which apperas to currently be set at the default (1024 * 1024)

maybe this size should be the one of network options(and also with default 100MB ?)

**Comment by mccoysc** [comment]
@alanshaw

**Comment by olizilla** [comment]
Hi @mccoysc, thanks for chasing this. This is just a friendly nudge that you don't need to explicitly call out `@alanshaw` on your issues. We all receive notifications for issues and comments, and we proactively monitor the issues js-ipfs... there is even a waffle board where they show up.

**Comment by mccoysc** [comment]
i suggest that the hapi work way should be modified.
by default,hapi cache the data in memory which transfering in progress.it makes the high memory usage.
the right way for cache should be cache in disk.
