### ISSUE TITLE
IPFS File Extension Issue

### ISSUE THREAD

**Issue by saimoomsafayet** [ipfs/js-ipfs#1643]
I am using js-ipfs to upload files to IPFS node. **ipfs.add()** is the method that i am using. Problem is that the file extension is not persistent after getting uploaded to the IPFS. Suppose I am uploading an apk file. After uploading, the apk is getting downloaded as a zip from the gateway. What is the solution?

**Comment by phadnisvinay30** [comment]
I assume that the contents of your file would be the same even after it being downloaded as a zip.
Please try the following:
 Use a command line to just change the name to *.apk (this should work as the content in it is the same)
something like this on a bash shell:
```sh
mv name.zip name.apk
```
This might work as a temporary solution but the problem still needs to be fixed

**Comment by fsdiogo** [comment]
You can add the file with the `wrapWithDirectory` option:

```js
ipfs.add(file, { wrapWithDirectory: true })
```

It basically creates a directory that wraps your content and keeps its filename. Give [this link](https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/files-on-ipfs/lessons/wrap-directories-around-content.html) a look.

**Comment by alanshaw** [comment]
Closing as I beleieve @fsdiogo has answered the question (at least that is what I was going to say!).
