### ISSUE TITLE
Files are automatically getting added to my workspace

### ISSUE THREAD

**Issue by leenabhandari** [ipfs/js-ipfs#1654]
- **Version**:
- **Platform**: win10
- **Subsystem**:

#### Severity:
High- since it is not secure anymore. anyone is getting my files.
#### Description:
In the last one day, unknown files are getting added into my workspace.(I am trying the exchange files in browser example) I am not connected to anyone. Similarly, people are getting my files.
#### Steps to reproduce the error:
Just start the node.

**Comment by alanshaw** [comment]
Hey @leenabhandari this expected - the application that runs in that example will actively download content that is added by other nodes. To stop that, navigate away from that page or close your browser. Likewise, all the content in your IPFS repo is accessible to anyone who knows the hash.

Hope that helps - let me know if you have any questions!

**Comment by fsdiogo** [comment]
Check out the last part of the [readme](https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser):

> <img width="912" alt="pubsub" src="https://user-images.githubusercontent.com/33324750/47801782-ce091e80-dd26-11e8-9031-61abcf78e9aa.png">

You're sharing content with people that are on that workspace.

**Comment by leenabhandari** [comment]
But I was not sharing my workspace with anybody. The hash value wasnt shared with anyone. And i had not connected the node with anyone. Earlier, after refreshing, the files used to go. But now, they are coming back.
