### ISSUE TITLE
js-ipfs peer discovery seems not working by default at private net

### ISSUE THREAD

**Issue by gitGksgk** [ipfs/js-ipfs#1658]
- **Version**: 0.32.3
- **Platform**: win 10
- **Subsystem**: unknown

#### Description: 
How do I enable peer discovery in js-ipfs? I've known rendezvous server but I'd like to use peer discovery methods like MDNS, etc.

#### Steps to reproduce the error:
1. use js-ipfs-0.32.3, add private net protect functionality in the code
2. setup several go-ipfs private nodes in virtual machine (to make it private just put swarm.key into .ipfs directory)
3. go-ipfs nodes will discover each other in an instant
4. `node src\cli\bin.js daemon` 
5, repeatedly run  `node src\cli\bin.js swarm peers`
 >  unfortunately see nothing
6. node src\cli\bin.js swarm connect <one of go-ipfs node's CID, set in step 2>
  > success. that means the private verification is success
7. repeat step 5
 > nothing more than the one you connect in step 6
8. -try opening wrtc support: npm install wrtc
    -make it run correct
    -still  nothing
9. -try open p2p-circuit. in .jsipfs\config, add:
```
  "relay": {
    "enabled": true,
    "hop": {
      "enabled": true
    }
```
repeat 5-8, still not get expected result:  expect getting a list of most ipfs nodes' addresses, but get the one manually connected.

my current .jsipfs\config file:
```
{
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4002",
      "/ip4/0.0.0.0/tcp/4003/ws"
    ],
    "API": "/ip4/127.0.0.1/tcp/5002",
    "Gateway": "/ip4/127.0.0.1/tcp/9090"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 0.1
    }
  },
  "Routing": {
    "Type": "dht"
  },
  "Bootstrap": [  ],
  "Identity": {
    "PeerID": "QmXhrk43nHcUXUUYtjQno56665KRtoVFCbfnkQ7AENB6Gt",
    "PrivKey": "CAASpgkwggSiAgEAAoI666CG+WjKFDTkj73XJbRsLLG/rNBxDPt01EziiOR7NIpV0NPbAixZHJDuach6zcPMdCfKSePR2kIsH36YTQQXWlGlTG6A=="
  },
  "datastore": {
    "Spec": {
      "type": "mount",
      "mounts": [
        {
          "mountpoint": "/blocks",
          "type": "measure",
          "prefix": "flatfs.datastore",
          "child": {
            "type": "flatfs",
            "path": "blocks",
            "sync": true,
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2"
          }
        },
        {
          "mountpoint": "/",
          "type": "measure",
          "prefix": "leveldb.datastore",
          "child": {
            "type": "levelds",
            "path": "datastore",
            "compression": "none"
          }
        }
      ]
    }
  },
  "Keychain": {
    "dek": {
      "keyLength": 64,
      "iterationCount": 10000,
      "salt": "XPC9W4JdnV5EkIKriLidoJBC",
      "hash": "sha2-512"
    }
  },
  "relay": {
    "enabled": true,
    "hop": {
      "enabled": true
    }
  }
}

```

**Comment by gitGksgk** [comment]
besides, sometimes it happens to get sth in swarm peer list, maybe been discovered by go-ipfs nodes...
here's relative wrtc code, in http\src\index.js:
    ```
const os = require('os')
const path = require('path')
const fs= require('fs')
const Protector = require('libp2p-pnet')
const keypath = path.join(os.homedir(), '.jsipfs', 'swarm.key')
const protector = new Protector(fs.readFileSync(keypath))
    if (wrtc || electronWebRTC) {
          const using = wrtc ? 'wrtc' : 'electron-webrtc'

          console.log(`Using ${using} for webrtc support`)
          const wstar = new WStar({ wrtc: (wrtc || electronWebRTC) })
          libp2p.modules.transport = [TCP, WS, WStar]
          libp2p.modules.peerDiscovery = [MulticastDNS, Bootstrap] // WStar.discovery can't fit in this context
        }
```
I've tried if(0) to skip this part of code, still giving the same empty outcome in  node ..bin.js swarm peers

**Comment by gitGksgk** [comment]
alright, solved. it's dht's matter

**Comment by AkshitV** [comment]
gitGksgk, i am facing a similar issue, with ipfsd-ctl library,
but it would be great if you could elaborate the solution
Thanks in advance
