### ISSUE TITLE
what is the use of app.js

### ISSUE THREAD

**Issue by leenabhandari** [ipfs/js-ipfs#1659]
- **Version**:
- **Platform**: win10
- **Subsystem**:

#### Type:
Question

#### Severity:
medium
#### Description:
even if i remove that file the application is working(exchange files in browser). some files are getting added in the workspace which i havent uploaded. how do we atomatically get connected to all those peers? In the documentation they have asked to start jsipfs daemon before running. but the application works even without it.

(Please update the documentation. It is a little unclear).

**Comment by alanshaw** [comment]
`app.js` is the source code for that example. When you run  `npm run bundle` it reads `app.js`, bundles in all the dependencies and makes a file called `bundle.js`. The [script tag in `public/index.html`](https://github.com/ipfs/js-ipfs/blob/master/examples/exchange-files-in-browser/public/index.html#L92) runs it. After you've created the bundle it is unused, but it is left there so you can experiment, make changes and create a new bundle if you like. Hope that helps.
