### ISSUE TITLE
CANNOT fetch file( bigger than 256k) in browser.

### ISSUE THREAD

**Issue by LiMoMoMo** [ipfs/js-ipfs#1667]
- **Version**: 0.33.0-rc.3
- **Platform**: chrome 69.0.3497.100 32bit
- **Subsystem**:

#### Description: 
use the [Exchange files between the browser](https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser), upload some files to one page's worksapce, i can fetch the fie which is smaller than 256K by enter the CID in other page, BUT can not fetch the file bigger than 256K.

#### Steps to reproduce the error:
* setup local [signal-server](https://github.com/libp2p/js-libp2p-webrtc-star)
```
npm install --global libp2p-webrtc-star
star-signal --port=9090 --host=127.0.0.1
```
* setup the [Exchange files between the browser](https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser)
* change the js-ipfs config in `app.js`
```
    const options = {
      EXPERIMENTAL: {
        pubsub: true
      },
      repo: repoPath,
      config: {
        Addresses: {
          Swarm: ['/dns4/192.168.1.107/tcp/8010/wss/p2p-webrtc-star'],     
          Bootstrap: []
        }
      }
    }
```
* disable the `pubsub`
```
function appendFile (name, hash, size, data) {
    ...
  // publishHash(hash)
}

```
* set Nginx
```
wss:8010   -----> ws:9090
https:8000 -----> http:12345
```
* start http-server in the example
* open two page `https://192.168.1.107:8000`
the pages' Addresses can appear in other's CONNECTED PEERS area each other. 
Drag some files to one workspace, then fetch the file by enter the cid in other page.
some files that smaller than 256K can be fetched, but the file that is big(500k or bigger) cannot be fetched.

**Comment by LiMoMoMo** [comment]
it looks like the api `node.files.cat(hash)` or `node.files.get(hash)` cannot work well when the node(the hash pointed) contains more than one child.

the files i added into one page's workspace:
1.  
![3](https://user-images.githubusercontent.com/14027218/47486533-277ad480-d873-11e8-942e-2db939977f4d.jpg)
2.
![4](https://user-images.githubusercontent.com/14027218/47486544-2ba6f200-d873-11e8-9bbf-691c4666ba4b.jpg)


i added code to output the wantlist:
```js
setInterval(refreshState, 100)
function refreshState() {
  node.bitswap.stat((err, stats) => console.log('bitswap stat',stats))
}
```
when i fetch the smaller file, i can see the **wantlist**'s value in step:
1. empty
2. `QmSm6d2Cjs3a16Ui6Rda4QSbcgm5Wprz21fXunYS6rUuCy` 
3. `QmV9tSDx9UiPeWExXEeH6aoDvmihvx6jD5eLb4jbTaKGps`
4. empty

but when i fetch the bigger file, the **wantlist**'s value:
1. empty
2. `QmQJbccYkLvyfTnT4SoSKB6WUKqJReXhdW4Dd8jFeyppgo`
3. `QmZrvPiFHEV4GkR1gcAarAfMr3FCoXAhRCws3VaYP3PZFx`
4. `QmPxq9mBhFFbaTAqAS3M3JDXNihMcdpeMxV1Lo2Jd8RAuZ` and 
   `QmTASUiQkzpeis7dTeqPZYWwUTs24MzJwXEQtn8eme66Tz`

when the **wantlist** has more than 1 member, the `files.cat()` or `files.get()` cannot work.

**Comment by alanshaw** [comment]
@vasco-santos would you mind looking into this bug when you have a moment?

**Comment by LiMoMoMo** [comment]
it seems that i made a mistake, i'm sorry.
This problem occurs between tabs that in different browsers,  opera and chrome.

**Comment by alanshaw** [comment]
closing this in favour of #1307
