### ISSUE TITLE
P2P connections with DataChannel

### ISSUE THREAD

**Issue by klueq** [ipfs/js-ipfs#1674]
How does `js-ipfs` connect two web nodes? This usually needs a signalling server/node that would let the two nodes exchange with ICE candidates and SDP messages.

**Comment by alanshaw** [comment]
Yes IPFS can use a signaling server over webrtc or websockets. Please checkout this section of the README: https://github.com/ipfs/js-ipfs#how-to-enable-webrtc-support-for-js-ipfs-in-the-browser
