### ISSUE TITLE
JS-IPFS Logs

### ISSUE THREAD

**Issue by pkafei** [ipfs/js-ipfs#1679]
JS-IPFS Version: 0.32.3

Is there a command that shows you `jsipfs` logs? I looked through all of the available commands via `jsipfs commands` and didn't spot a command for displaying logs.

Additionally, what is the `debug` option for the JS implementation of IPFS. It seems to be slightly different than the different debug methods for the [Go version of IPFS](https://github.com/ipfs/go-ipfs/issues/1816).

**Comment by alanshaw** [comment]
The log command is not yet implemented. We use the [`debug`](https://www.npmjs.com/package/debug) module throughout the codebase so you can use the `DEBUG` environment variable to get debugging logs e.g. `DEBUG=* jsipfs daemon`.
