### ISSUE TITLE
No Tutorial Present for CLI

### ISSUE THREAD

**Issue by pkafei** [ipfs/js-ipfs#1680]
Interact with IPFS directly from your Terminal tutorial is missing content.
https://github.com/ipfs/js-ipfs/tree/master/examples/ipfs-cli-fun

**Comment by alanshaw** [comment]
Good point! Would you be willing to send a PR to either remove it (as it's confusing) or add a simple example for using the JS IPFS CLI?

**Comment by alanshaw** [comment]
This rogue dir was removed in https://github.com/ipfs/js-ipfs/pull/1713
