### ISSUE TITLE
Turn off logger?

### ISSUE THREAD

**Issue by aakilfernandes** [ipfs/js-ipfs#1683]
I'm using js-ipfs as part of a cli. How can I turn off the logger?

**Comment by alanshaw** [comment]
@aakilfernandes I agree this needs fixing - would you be willing to send a PR?

**Comment by aakilfernandes** [comment]
Sure. Just need a little guidance.

https://github.com/ipfs/js-ipfs/blob/52f7aa7183b195c2059a2dd07c8a7cc4034a3717/src/cli/commands/config/show.js#L3

There's a lot of places where `debug` is used, should i just move all these `console.log` into debug?

**Comment by rmisio** [comment]
I'm wondering how to turn it off in a browser version? I'm trying to debug an app I'm working on with some `console.log`s and they're just being washed out by thousands of logs from `bundleCircuit.js`.

**Comment by alanshaw** [comment]
@rmisio https://github.com/ipfs/js-ipfs/pull/1712 will allow you to pass a "silent" option to the IPFS constructor to silence all output.
