### ISSUE TITLE
ipfs.get needs 10 mins to discover new files

### ISSUE THREAD

**Issue by klueq** [ipfs/js-ipfs#1687]
I've added a text file and tried to resolve it via a public gateway - it worked almost instantly. Now I'm trying to do the same with js-ipfs on the same host that added the file via go-ipfs and on my phone which is not using wifi. None of them could resolve it. The file in question:

```
QmXXtHtDwXFbCTzMDjacZxid6CCNY4m5oM6MgBhyPVT3Tr
```

I wonder if this is because js-ipfs doesn't support DHT yet.

How much time would you expect it to take to resolve a new file?

**Comment by klueq** [comment]
Finally it arrived after 770 seconds. Still the question is valid: is it because of DHT and what's the expected delay.

**Comment by alanshaw** [comment]
Possibly related to https://github.com/ipfs/infrastructure/issues/448

**Comment by alanshaw** [comment]
@klueq correct, JS IPFS doesn't have a DHT enabled by default and it isn't yet interoperable with Go IPFS.

When you add content to JS IPFS, it'll "preload" it on 2 dedicated preloading nodes. These are go-ipfs nodes that _do_ have a DHT. It takes a little time to preload content you add to IPFS on the preload nodes and then a little bit more time for that content to be available on the DHT.

If you're trying to get content using a JS IPFS node, then it _has_ to be physically stored on the preload nodes already, or discoverable by the preload nodes i.e. on the DHT. When you try to get some content you don't have locally using JS IPFS, it actually asks the preload nodes to preload it, and they'll either get it locally or from the DHT, and can then give it back to JS IPFS. So basically JS IPFS has access to the DHT via the preload nodes.

The time it takes for this to happen depends on the size of the file you're adding, the preload nodes being available and your network connectivity. I'd not expect it to take 10 minutes unless you added a particulary big file, or have a really slow upstream connection or the preload nodes disappeared for ~10 minutes after your content got preloaded.

Are you able to re-verify this again with the latest release of js-ipfs (0.34)?

**Comment by alanshaw** [comment]
ping @klueq

**Comment by klueq** [comment]
Something must have changed in the API: it now throws some cryptic errors. See klueq.github.io?ipfs=0.34

**Comment by achingbrain** [comment]
I think `libp2p-browser.js` is [missing a DHT module implementation in the browser](https://github.com/ipfs/js-ipfs/blob/748fccfb840d2f96e58bc4eb9f3144b95e24f7f0/src/core/runtime/libp2p-browser.js#L24-L41).

It's [present](https://github.com/ipfs/js-ipfs/blob/748fccfb840d2f96e58bc4eb9f3144b95e24f7f0/src/core/runtime/libp2p-nodejs.js#L41) in `libp2p-node.js`.

It causes the internal config validation in `libp2p` to fail as it's `undefined` when `options.config.dht.enabled` is true - see https://github.com/libp2p/js-libp2p/blob/master/src/config.js#L55-L58.
