### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of null

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1689]
await ipfs.ping("QmZ6YuHZUJd6k9hbJNaNUZBsWfwZGv62piZMU6oxHPBtDx")

collect.js:7 Uncaught TypeError: Cannot read property 'push' of null
    at collect.js:7
    at reduce.js:8
    at drain.js:24
    at f (index.js:84)
    at Function.u [as push] (index.js:44)
    at e.ping (ping-pull-stream.js:79)
    at _getPeerInfo (index.js:339)
    at s (get-peer-info.js:54)
    at setImmediate.js:27
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at r (setImmediate.js:109)

i found the code like this(@ line 6 of node-modules/pull-stream/sinks/reduce.js):

module.exports = function reduce(reducer, acc, cb) {
  if (!cb) cb = acc, acc = null
  var sink = drain(function (data) {
    acc = reducer(acc, data)
  }, function (err) {
    cb(err, acc)
  })
  if (arguments.length === 2)
    return function (source) {
      source(null, function (end, data) {
        //if ended immediately, and no initial...
        if (end) return cb(end === true ? null : end)
        acc = data;
        sink(source)
      })
    }
  else
    return sink
}

at some moment, "acc" would be set to "null",and the error caused by this resaon.
may be ,the code should be "if (!cb) cb = acc, acc = []"

**Comment by mccoysc** [comment]
browser version in google chrome

**Comment by mccoysc** [comment]
and  if i make the code "acc=[]",another error:

Uncaught TypeError: cb is not a function
    at reduce.js:10
    at drain.js:20
    at f (index.js:84)
    at c (index.js:68)
    at Function.a [as end] (index.js:36)
    at e.exports.o.on.e (ping-pull-stream.js:97)
    at e.exports.r.emit (events.js:81)
    at p.swarm.dial [as callback] (ping.js:30)
    at a (dial.js:110)
    at once.js:12
    at f (waterfall.js:21)
    at onlyOnce.js:12
    at a (dial.js:160)
    at once.js:12
    at f (waterfall.js:21)
    at onlyOnce.js:12

it meas that,in module "pull-stream",you can call “reduce(reducer,[],callback)” or “reduce(reducer,callback)” .
but in fact ,neighter of them.

i just update the "pull-stream" to version "3.6.8",is this caused the error?

**Comment by mccoysc** [comment]
if i change the node-modules/ipfs/src/core/componets/ping.js to the following:

module.exports = function ping(self) {
  return function (peerId, opts, cb) {
    return new Promise(function (resp, rej) {
      function _cb() {
        if (cb) {
          return cb.apply(this, arguments);
        }
        if (arguments[0]) {
          return rej(arguments[0]);
        }
        return resp(arguments[1]);
      }
      pull(self.pingPullStream(peerId, opts), pull.collect(_cb));
    });
  }
}


all is ok.

it seems that maybe the module "promisefy-es6" has some bugs

**Comment by alanshaw** [comment]
This is the same error as the second issue reported in #1616 and was resolved by https://github.com/ipfs/js-ipfs/pull/1627
