### ISSUE TITLE
No available transports to dial peer 

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1690]
in jsipfs version 0.33.0 ,await ipfs.ping(QmYSk5mvSfQdniBCNZ1XLkp44Gih8m6kVqPJnCCNRv1rnR) got this error(run in browser):

Uncaught (in promise) Error: No available transports to dial peer QmYSk5mvSfQdniBCNZ1XLkp44Gih8m6kVqPJnCCNRv1rnR! Error: No available transports to dial peer QmYSk5mvSfQdniBCNZ1XLkp44Gih8m6kVqPJnCCNRv1rnR!
    at i (dial.js:369)
    at switch.transport.dial (dial.js:382)
    at dialer.dialMany (transport.js:69)
    at t (once.js:25)
    at n (index.js:61)
    at map.js:32
    at once.js:12
    at f (eachOf.js:60)
    at onlyOnce.js:12
    at Object.callback (map.js:29)
    at queue.js:101
    at onlyOnce.js:12
    at _dialWithTimeout (queue.js:44)
    at timeout.js:74
i know that maybe find the peer by dht,some node don't have the protocol which can be connected by browser node jsipfs,but,why skip this?
maybe browser version dht should skip the node which not supported by browser.

**Comment by alanshaw** [comment]
I don't think this is a bug, like the error message says, there's just no transports that are able to dial to the node you're trying to ping. In the browser we're restricted by same origin policy so can only really dial to websockets or via a relay.

**Comment by gil-air-may** [comment]
Hey I've found the same problem. I am using js-ipfs and created a node on a browser. Can use `ipfs.swarm.connect`, to connect to a node directly? What kind of relay setup is necessary?

**Comment by linonetwo** [comment]
So how can we use this API? Is it useless in browser?

**Comment by linonetwo** [comment]
Hi @gil-air-may  , I got to know that the multiaddress you passed to `ipfs.swarm.connect` have to be like:

```
/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
```

not something like:

```
/ip4/140.123.123.123/tcp/4001/ipfs/QmVtsdfsdfsd7o2Qzxj8RCanEahGUM1mnajaQTi 
```

the former will success , while later will throws `No available transports to dial peer `
