### ISSUE TITLE
 js-ipfs has more connected peers than ipfs-pubsub-room

### ISSUE THREAD

**Issue by caffeinum** [ipfs/js-ipfs#1691]
- **Version**: commit: "", repo: 7, version: "0.32.3"
- **Platform**: Chrome, Mac OS X Mojave (but bug happens on other platforms: Windows, Yandex Browser)
- **Subsystem**: pubsub

#### Description:

_Now, I am thinking the bug could be in https://github.com/ipfs-shipyard/ipfs-pubsub-room/ code, though I am not an expert, so I am filing it both ways._

Sometimes, but very rarely, pubsub loses connected peers and (presumably) calls them offline, while retaining connection for them (see screenshot).

Our app highly relies on online/offline peer status, so we need to know for sure when peer went offline. To track that, we rely on pubsub's `'peer left'` events.

Unfortunately, it seems sometimes message comes when user didn't really went offline. And then we can't know he is online, because pubsub does not send event when user's already online.

#### Steps to reproduce the error:

I can't reproduce it for now, but it happens once in a while.

https://github.com/swaponline/swap.core/blob/master/src/swap.room/SwapRoom.js#L80

```javascript
this.connection = ipfsRoom(...)

this.connection.on('peer joined', this._handleUserOnline) // here we gather data from him
this.connection.on('peer left', this._handleUserOffline) // here we remove his data
```

#### Screenshots:

![image](https://user-images.githubusercontent.com/1909384/47928121-8a005000-dec5-11e8-8ec3-72150cf960ca.png)

**Comment by alanshaw** [comment]
This sounds very much like an issue with pubsub room - it should be investegated there. If the cause is not found to be pubsub-room then please open another issue here with specifics about the issue with JS IPFS.

**Comment by caffeinum** [comment]
OK, I'll put a link to that issue here for connection: [issue](https://github.com/ipfs-shipyard/ipfs-pubsub-room/issues/61)
