### ISSUE TITLE
about p2p 

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1692]
go-ipfs has some p2p commands like "ipfs p2p listen" and so on,this is important for making a new communication layer with peerId other than ip......
which time to add this feature?

**Comment by alanshaw** [comment]
JS IPFS has `ipfs._libp2pNode` which exposes p2p functionality for this purpose. This will hopefully soon be moved to `ipfs.libp2p` as per https://github.com/ipfs/js-ipfs/issues/1664

**Comment by alanshaw** [comment]
If there's anothing missing here that you'd like to see then please open an issue on the libp2p repo https://github.com/libp2p/js-libp2p :)
