### ISSUE TITLE
Bootstrapper 0 and 1 repeatedly failing with 504s

### ISSUE THREAD

**Issue by vitriol-co** [ipfs/js-ipfs#1694]
- **Version**: v0.32.3
- **Platform**: Browser - any
#### Type:
Bug

#### Severity:
High

#### Description:
Repeated 504 Timeout errors from preload nodes 0 and 1:

`index.min.js:1 GET https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=QmSTYia3dXbtFTFZCEYnBFyNXpmED34xYtjkwxocTo1Q2d 504 (Gateway Time-out)`

`index.min.js:1 GET https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmSTYia3dXbtFTFZCEYnBFyNXpmED34xYtjkwxocTo1Q2d 504 (Gateway Time-out)`

#### Steps to reproduce the error:

- Go to https://vitriol.co
- Open the console and see the errors.
- Code of the application is: https://gitlab.com/vitriolum/vitriol-web

**Comment by alanshaw** [comment]
@haadcode are you able to confirm this has been resolved?

**Comment by vitriol-co** [comment]
@alanshaw - what I see now from https://vitriol.co is another error:

`GET https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmcV11zWC2ccMg1kiV7nk1FCSeCVmFZNQWAAkvYzAGWA4R net::ERR_CONNECTION_CLOSED`

So no, it doesn't seems resolved (but the timeouts are gone)

**Comment by vitriol-co** [comment]
I retried and now all seems working. I will retry in a couple of hours to confirm.

**Comment by vitriol-co** [comment]
Nope, node 0 is still closing connections and node 1 is still 504 timing out.

`index.min.js:1 GET https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmaF5QLZJvk2HpCTcbzz4YmCX7xgHo2cyxwYhmCKMZLNbU net::ERR_CONNECTION_CLOSED`

`index.min.js:1 GET https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=QmUx8Yrq7y89BekfMW1swuywFygM5q7uPX2a11jdhCxVhf 504 (Gateway Time-out)`

... for ~100 lines

**Comment by lifeBCE** [comment]
I have switched my app over to using my own bootstrap node for references so I have not been seeing the 504s but I can confirm that no data has been transferred all day. My browser node connects fine and will grab up to 7 or 8 peers as well but will not transfer blocks.

I originally started the day out on version 0.33.0, then dropped back to 0.32.3 and then up to 0.33.1 and all versions show the same. Actually, 0.32.3 would not get peers at all. Everything worked fine yesterday on 0.33.0.

Are the ipfs.io nodes critical in the path of network functionality? That has been my experience over the last couple weeks. I thought redirecting my browser node to my own dedicated bootstrap node would free me up a bit but it seems I am still tethered somehow. Maybe I need to run my own js-ipfs server node[s] to connect the browser node to it via websocket?

**Comment by diasdavid** [comment]
@ipfs/infrastructure team, is anyone looking into this?

**Comment by eefahy** [comment]
I just loaded https://vitriol.co and watched IPFS startup. Closing this issue as it appears to be resolved but please reopen is the problem persists.

<img width="545" alt="screen shot 2018-11-14 at 8 28 42 am" src="https://user-images.githubusercontent.com/1131894/48496672-669fa400-e7e7-11e8-9b12-d7000ca50b00.png">
