### ISSUE TITLE
Cannot get a node.js js-ipfs peer and a browser js-ipfs peer. Config issue? 

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#1714]
- **Version**: { version: '0.33.1', repo: 6, commit: '' }
- **Platform**: Linux ip-172-31-11-196 4.4.0-1069-aws #79-Ubuntu SMP Mon Sep 24 15:01:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
- **Subsystem**: pubsub, libp2p

#### Description:
Please review the following configuration options and let me know what, if anything, I can do to get pubsub to work between them. If the problem isn't pubsub, please let me know what it is. I feel like what I need to change is rather minor but I can't seem to find it.

1. Browser Config. It probably looks like I'm just copying and pasting stuff I dont understand. This is only partly true ;) I've been experimenting with different combinations here for hours now. The node.js config is currently identical.

```javascript
{
  relay: { enabled: true, hop: { enabled: true, active: true } },
  EXPERIMENTAL: {
    pubsub: true,
  },
  config: {
    Bootstrap: [
      "/dns4/mydomain.com/tcp/4003/wss/ipfs/QmU............"
    ],
    Addresses: {
      Swarm: [
        '/dnsaddr/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star',
        '/dnsaddr/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-webrtc-star',
        '/dnsaddr/ws-star-signal-2.servep2p.com/tcp/443/wss/p2p-webrtc-star',
        '/dnsaddr/ws-star-signal-3.servep2p.com/tcp/443/wss/p2p-webrtc-star',
        '/dnsaddr/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
        '/dnsaddr/ws-star-signal-1.servep2p.com/tcp/443/wss/p2p-websocket-star',
        '/dnsaddr/ws-star-signal-2.servep2p.com/tcp/443/wss/p2p-websocket-star',
        '/dnsaddr/ws-star-signal-3.servep2p.com/tcp/443/wss/p2p-websocket-star'
      ]
    }
  }
}
```

I have confirmed that the nodes are indeed peering but they don't appear to be reading each other's pubsub messages. Please note that this is in service of trying to peer two OrbitDB databases and more details can be found here. https://github.com/orbitdb/orbit-db/issues/496

Thank you!

#### Steps to reproduce the error: 
Load the configuration into the browser and the node.js nodes and see if you can get them to peer and pubsub properly. I can't :(

**Comment by alanshaw** [comment]
Your config looks ok. From a browser, both peers will need to be connected to each other via a rendevous server and subscribed to the same topic, or, connected to a known peer who is also subscribed to the topic and can forward on the messages. Simply adding the rendezvous config doesn't necessarily mean the peers have discovered each other.
