### ISSUE TITLE
OOM when importing large directories

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#1736]
[This call](https://github.com/ipfs/js-ipfs/blob/master/src/cli/commands/add.js#L52) to `get-folder-size` can cause OOMs on large directories as the `get-folder-size` module keeps a list of all the files it's seen to make sure it doesn't double-count symlinked files (for example).

We only calculate the directory size to show a progress indicator - I propose we switch to an indeterminate indicator if the number of files being imported  is unreasonable (say, 10k).

What do you think?

**Comment by achingbrain** [comment]
This is a little harder than it seems - the way all these file counter modules seem to work is to call [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) which returns a list of files.  If the directory is too big, it'll explode.

There's an issue on the node.js repo about an [iterative `fs.readdir`](https://github.com/nodejs/node/issues/583) but it needs [support added to libuv first](https://github.com/libuv/libuv/pull/416), which looks like is happening, but slowly.

**Comment by alanshaw** [comment]
I'm hoping that https://github.com/ipfs/js-ipfs/pull/1777 might help a little - if you call `ipfs add --progress=false` then `get-folder-size` won't be used anymore.

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

`@helia/unixfs` doesn't notify on progress in the same way, the user can keep track of the number of files/folders imported if they wish to show feedback.
