### ISSUE TITLE
Strange pubsub behavior - timing issue? duplicate messages?

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#1739]
- **Version**: 0.33.1
- **Platform**: node.js
- **Subsystem**: pubsub

#### Description:

When running [this test](https://github.com/orbitdb/ipfs-log/blob/6f94b0d15006692aae1fa02b64aea52014d98e72/test/replicate.spec.js) the js-ipfs version of "replicates logs" is failing. I was able to finagle output that shows what's going on - seems like a timing issue?

Note that after the third tick, the messages come reliably in groups of 4. As a result of this, counts are duplated and [the assertions here](https://github.com/orbitdb/ipfs-log/blob/6f94b0d15006692aae1fa02b64aea52014d98e72/test/replicate.spec.js#L157) fail.

```
1
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
2
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
3
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
4
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
5
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
6
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
7
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmamizjwVHa3PGuREmPm9ZiCUFRXZtoEFF6UWrJRsSn6xM [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
QmNqzvcBfJVXC8wjDUyDBRPZVFDMotVbp3BkXM2gyWu1iN [ 'XXX' ]
```

#### Steps to reproduce the error:

```bash
$ git clone https://github.com/orbitdb/ipfs-log
$ cd ipfs-log
$ git checkout feat/jupyter-test
$ make clean
$ npm install
$ npx mocha --grep replicate
```

**Comment by aphelionz** [comment]
Update: I thought it might be related to https://github.com/libp2p/js-libp2p-floodsub/pull/59/ but I confirmed that code is in my installed package and did not make a difference. It seems this **only** affects `js-ipfs` and not `go-ipfs`

**Comment by aphelionz** [comment]
In the process now of trying to write a failing test for `js-libp2p-floodsub` but running into some difficulties getting it to fail. 

This is the test I'm running against `js-libp2p-floodsub`: https://gist.github.com/aphelionz/33bef361de03f950547206623188d696, trying to mirror https://github.com/orbitdb/ipfs-log/blob/master/test/replicate.spec.js

Am I correct in my understanding that there are a number of layers in the pubsub implementation:

1. The base `EventEmitter` layer
2. The `FloodSub` layer which is still synchronous `fs.publish` / `fs.subscribe`
3. The `libp2p` layer, which introduces callbacks to those functions
4. The `js-ipfs` layer, which appears to promisify everything

I think based on the test in the gist not failing I've effectively ruled out layers 1-3.

**Comment by alanshaw** [comment]
@aphelionz could you explain what the issue is and how the output you pasted above relates to it? At the moment I can't decipher what the issue is.

**Comment by aphelionz** [comment]
@alanshaw I believe there are duplicate messages being sent, or I just don't know how to handle the timing of the messages. In the test I linked in the OP, the ipfs-log has 132 entries, when it is expecting 129.

**Comment by victorb** [comment]
You'll have to manually look at the `seqno` property in a pubsub message to determine if you already received the message, as you could receive the same message multiple times, this is expected from the floodsub implementation.

**Comment by aphelionz** [comment]
Found the bug! not your problem :)
