### ISSUE TITLE
Programmatically specify which port an IPFS node is going to use

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [ipfs/js-ipfs#1744]
I would like to be able to programmatically set the port that a node is using, something like:

```javascript
const ipfs = new IPFS({
  repo: "reponame",
  port: portNumber
})
```
I am trying to run multiple nodes on the same machine, but this is not possible because they all use the same port, therefore node.js throws an exception.

Reading the doc this doesn't seem to be possible, am I right? is there any particular reason?

thanks!

**Comment by Juanperezc** [comment]
You can use the docker image and specify in which port you want each node to run

**Comment by PierfrancescoSoffritti** [comment]
Sure, but is there a particular reason for this limitation? If there is no technical constraint I could just implement it instead of using containers.

**Comment by alanshaw** [comment]
IPFS nodes run different services on multiple ports. They can all be configured in the `config` section of the constructor options object: https://github.com/ipfs/js-ipfs#optionsconfig

Specifically you'll need to add config that changes the values for these options:

https://github.com/ipfs/js-ipfs/blob/d215502b915c43c3ffe4f6475b38aaa63ec3d7f8/src/core/runtime/config-nodejs.js#L4-L11

**Comment by PierfrancescoSoffritti** [comment]
oh ok, great! thanks for the help!
