### ISSUE TITLE
Update tests in js-ipfs to be less repetative and reduce code duplication

### ISSUE THREAD

**Issue by victorb** [ipfs/js-ipfs#1748]
Tests currently are duplicated and all over the place. Depending on previous test cases and so on.

Need to fix the tests to be treated as production code.

**Comment by ay2306** [comment]
@alanshaw Can I work on this issue?

**Comment by alanshaw** [comment]
@hugomrdias I know you're working on similar things - is there something @ay2306 can help you out with?

**Comment by achingbrain** [comment]
Closing as this is very stale.
