### ISSUE TITLE
Browser tests not runnable locally

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1750]
There's been a report of not being able to run the browser tests locally: https://github.com/ipfs/dev-team-enablement/issues/159

@mikeal would you be able to confirm if this is still the case and provide us with some details of the failure?

**Comment by mikeal** [comment]
I keep thinking that I have time to sit down and verify this and the world keeps proving me wrong! If you want to close this out until I have find the time I'm fine with that :)
