### ISSUE TITLE
The resolve command should work even if the path ends in the middle of an object

### ISSUE THREAD

**Issue by Stebalien** [ipfs/js-ipfs#1763]
Being able to path *into* objects, not just *to* objects is a crucial feature of IPLD.

Given:

```
b = {"c": "some value"}
a = {"b": {"/": cidOf(b) }}
```

`ipfs resolve /ipld/cidOf(a)/b/c` should return `/ipld/cidOf(b)/c`. That is, it should resolve the path as much as it can.

Currently, this simply fails with an error.

See: https://github.com/ipfs/go-ipfs/pull/5704

**Comment by alanshaw** [comment]
Yep agree!

**Comment by Stebalien** [comment]
Wait. It looks like js-ipfs doesn't implement this command at *all*, is that right? In that case, can we just merge https://github.com/ipfs/interface-ipfs-core/pull/385 and https://github.com/ipfs/go-ipfs/pull/5704?
