### ISSUE TITLE
Why is the local file access is so slow ?

### ISSUE THREAD

**Issue by stasbar** [ipfs/js-ipfs#1766]
- **Version**: 0.33.1
- **Platform**: Darwin 18.2.0

#### Type: Question
I'm extedning the example `browser-video-streaming`. I'm storing some videos in my local ipfs, and it's corresponding metadata in dag. I'm wondering why is the video file streaming so slow on my browser local? Isn't it connected to my local node directly? 
When I force the browser node to connect to my local node like:
```
function createNode(): Promise<any> {
    const node = new IPFS();
    return new Promise((resolve, reject) => {
        node.on('ready', () => {
node.swarm.connect("/ip4/127.0.0.1/tcp/4001/ipfs/QmaeUxeAK3N5fyU5o5W8eFeHGy7SUgcxfscewNNGgFak8L");
                resolve(node)
            }
        )
    });
}
```

it throws 
`dial.js:365 Uncaught (in promise) Error: Circuit not enabled and all transports failed to dial peer QmaeUxeAK3N5fyU5o5W8eFeHGy7SUgcxfscewNNGgFak8L!`

When I do:
```
const peers: Peer [] = await node.swarm.peers();
peers.forEach(peer => console.log(multiaddr(peer.addr).toString()));
```
it only shows:
`/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd`
`/dns4/lon-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3`
`/dns4/nyc-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm`
I guess it is not aware of my local node at all, so it tries to resolve files over internet. Is there any way to share my local repo or just connect to my local node ?

**Comment by stasbar** [comment]
Thank you for your answer @daviddias , you showed me where the problem is. But is there any solution?  I would like to watch the video in my browser, even when offline. Is it possible at the moment?

**Comment by daviddias** [comment]
@stasbar it is indeed. You just need to enable a WebSockets listener in your local Desktop node. The tutorial -- https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser -- shows how to do it :)

**Comment by stasbar** [comment]
Thank you, it worked ❤️

**Comment by daviddias** [comment]
Awesome! Glad to help :)
