### ISSUE TITLE
compatibility with end-of-stream/stream.finished methods

### ISSUE THREAD

**Issue by mcollina** [ipfs/js-ipfs#1774]
- **Version**: 0.33.1
- **Platform**: Mac OS X
- **Subsystem**: catReadableStream

#### Description:

Using `node.files.catReadableStream()` returns a stream that is not fully compatible with well-known streams modules such as https://github.com/mafintosh/end-of-stream or https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback. 

#### Steps to reproduce the error:

```js
const eos = require('end-of-stream')
const fileStream = fs.createReadStream(filePath)
const inserted = await peer.files.add(fileStream)
const stream = peer.files.catReadableStream(inserted[0].hash)
stream.resume()
eos(stream, function () {
  // this is never called
})
```

cc @litzenberger

**Comment by AuHau** [comment]
I believe that with the recent upgrade to async generators and hence leaving `pull-stream-to-stream` library that was returning old streams (and I think that was the problem of this issue), this should be resolved.

**Comment by alanshaw** [comment]
I agree. 

Additionally this API call will soon be removed and there will only be `ipfs.cat()` which will return an async iterable.

In the mean time if anyone has an issues related to this then please open a new issue 😀
