### ISSUE TITLE
Consider adding support for a HTTPS gateway

### ISSUE THREAD

**Issue by satazor** [ipfs/js-ipfs#1789]
- **Version**: 0.33.1
- **Platform**: MacOS
- **Subsystem**:

#### Type:

Feature

#### Severity:

Low

#### Description:

It would be awesome if we could (maybe optionally) expose a HTTPS gateway alongside the HTTP one. Sometimes, I want to share a web application built with [peer-base](https://github.com/peer-base/peer-base) within a workshop/talk, but it won't work. The reason is that security context is broken because the URL is something like `http://<my-lan-ip>:8080/ipfs/<cid>` and IPFS fails to boot because `window.crypto` is not defined.

At the moment, we have to use https://github.com/naugtur/https-proxy-cli.

#### Steps to reproduce the error:

1. Clone https://github.com/ipfs-shipyard/workshop-todo-dapp
1. `git checkout with-peer-base`
1. `npm i`
1. `npm run build`
1. `ipfs add -r build`
1. open the folder cid in your local gateway with localhost and see that it works
1. open the folder cid in your local gateway with your lan ip and see that it doesn't work due to `window.crypto` being undefined

**Comment by satazor** [comment]
@pgte I meant the http gateway to also be exposed in https. It would be awesome to add a website into my local gateway and share a dapp built with `peer-base` to people within the same network: http://<my-lan-ip>:8080/ipfs/<cid>. This requires it to be HTTPs otherwise it breaks the security context and `window.crypto` won't be accessible.

The same thing applies to the exposed WS yes! Related: https://github.com/libp2p/js-libp2p-rendezvous/issues/5

**Comment by pgte** [comment]
@satazor ha, gotcha!

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

This is not planned for Helia but a module that implements this could be written that uses Helia behind the scenes.
