### ISSUE TITLE
Installing js-ipfs in a project

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/js-ipfs#1790]
- **Version**: 0.33.1
- **Platform**: CentOS, Fedora, Xubuntu, among others
- **Subsystem**:

#### Type: 

Documentation enhancement

### Severity: 

Very Low

#### Description:

@satazor and myself presented a workshop, `True serverless`  [ipfs/dynamic-data-and-capabilities#59](https://github.com/ipfs/dynamic-data-and-capabilities/issues/59) in the Aveiro University. There were people there with all type of environments and package managers. IIRC, there were people using CentOS, Fedora, Xubuntu, among others. During the workshop people had to install [peer-base](https://github.com/peer-base/peer-base) and had several problems installing it due to `ipfs` / `libp2p` dependencies.

List of common problems that people had in their environments:
- need to have `node-gyp` installed globally
- `node-gyp` requires python2.7, while there were people who only had python3 installed and got issues until switching to python2.7.
- `build-essential` package needed
- `gcc-c++` needed

I would say that we should have a FAQ installing questions with the possible problems installing `ipfs` and how to fix them. What do you think?

#### Steps to reproduce the error:

`npm install peer-base`

**Comment by vasco-santos** [comment]
@jacobheun we should analyze this for `js-libp2p`, as I believe some of these problems may occur with it. I did not create an issue for now.

**Comment by Bacis** [comment]
I'm having issues installing ipfs with npm. If I run *npm i ipfs* I end up with *npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`*
