### ISSUE TITLE
WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/ Error

### ISSUE THREAD

**Issue by Juanperezc** [ipfs/js-ipfs#1798]
- **Version**: 0.33.1
- **Platform**: Linux Manjaro, Chrome, Firefox and Mobile device (Ionic)

#### Description:

I get the following error when I try to try a project I was developing some time ago, and stop for vacation.

`WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

`Init Errors:  Error: websocket error
    at WS.Ipfs../node_modules/engine.io-client/lib/transport.js.Transport.onError`

I did not move anything from the project I just went back to it and I found this

#### Steps to reproduce the error:

When I created new instace ipfs reproduce the error
`     let node =  new (window as any).Ipfs(
          {
          repo: '/ipfs/votto/test',
          EXPERIMENTAL: {
            pubsub: true
          } ,
          config: {
            Addresses: {
              Swarm: [
                '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/'
              ]
            }
          }
        } 
        );`

**Comment by hushino** [comment]
Same problem with chrome and windows last version, node 10.14 and npm 6.4

**Comment by jacobheun** [comment]
Looks like there is an ongoing outage of the server, https://github.com/ipfs/infra/issues/436#issuecomment-451009469. If you are testing out a project I'd recommend running your own rendezvous server https://github.com/libp2p/js-libp2p-websocket-star-rendezvous. There's currently no guarantee of uptime on the hosted server.

**Comment by alanshaw** [comment]
Please track this at https://github.com/ipfs/infra/issues/436
