### ISSUE TITLE
Can I update a img or txt to ipfs and make it private?

### ISSUE THREAD

**Issue by halley801** [ipfs/js-ipfs#1804]

**Comment by VandeurenGlenn** [comment]
I'm not sure this is the place to ask @halley801.
You can create a private network or you can encrypt the file before adding it.

**Comment by alanshaw** [comment]
@halley801 yes best to discuss this on https://discuss.ipfs.io/

There's no best practice or turorial for encrypting content before you add it to IPFS and there's no direct APIs for doing it. However js-ipfs does [export the `libp2p-crypto` module](https://github.com/ipfs/js-ipfs#util) which exposes a bunch of functions that would help you towards that goal.

If you do manage to get this working I would welcome a PR to add a turorial as this is a question asked relatively frequently.

For private networking, you should take a look at https://github.com/libp2p/js-libp2p-pnet
