### ISSUE TITLE
Consider having a js-core repo for the JS Core team

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#1808]
The responsibilities of the JS Core Team are larger than just js-ipfs and today, the entrypoint repo is the repo of the main module of the project. It makes it hard to have discussions that are Working Group related in a repo that is tracking a software project.

Proposal: Adopt a similar strategy to all the other working groups and have your own entry point repo

**Comment by alanshaw** [comment]
This sounds great, I just went to create one but which org would it live under? JS Core is people working on projects in ipfs, libp2p, ipld, multiformats etc. etc.

**Comment by daviddias** [comment]
Should be IPFS org for now.

**Comment by alanshaw** [comment]
@achingbrain @jacobheun @vmx @hugomrdias before I go ahead and create this repo can we get your 👍 or 👎 ?

**Comment by jacobheun** [comment]
👍 from me.

**Comment by alanshaw** [comment]
https://github.com/ipfs/js-core
