### ISSUE TITLE
Merge bundling Browser examples

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#1817]
proposal: let's use merge the "bundling for the browser" examples:
- https://github.com/ipfs/js-ipfs/tree/master/examples/browser-browserify
- https://github.com/ipfs/js-ipfs/tree/master/examples/browser-parceljs
- https://github.com/ipfs/js-ipfs/tree/master/examples/browser-webpack
- https://github.com/ipfs/js-ipfs/tree/master/examples/browser-script-tag

**Comment by alanshaw** [comment]
How do you mean merge? Put in a directory like this?:

```console
/examples/bundling-for-browser/browserify
/examples/bundling-for-browser/parceljs
/examples/bundling-for-browser/webpack
/examples/bundling-for-browser/script-tag
```

**Comment by daviddias** [comment]
My proposal was more on

- One single app example
- One single package.json
- Multiple npm scripts, one for each bundler
- Readme that explains what it is, and which npm script is for which bundler
- remove all the effort of updating 4 individual apps to just update one single app

**Comment by daviddias** [comment]
As a bonus. We can add as part of the tutorial how to see the size of the final bundle and compare (time spent x bundle size) and explain why we use WebPack ourselves for dist vs all the others.

**Comment by achingbrain** [comment]
If each bundler is a separate example, I think people will take the `package.json` contents from the example that features the bundler they want to use as a starting point for their own projects.

If all the bundler examples are bundled (!) into one example, it would be harder to look at the `package.json` and say 'this is the minimum set of deps I need for my project' which adds friction to that usecase.

**Comment by alanshaw** [comment]
I think there's a huge amount of value in the copy/paste-ability of an individual example. Combining them into one will remove that - like @achingbrain said you'd have to figure out what dependencies and config applies to which bundler and that's not something I want to push onto developers trying to use js-ipfs.

Another potential hurdle: I don't know for sure if it'll be possible i.e. conflicting dependencies and `.babelrc` configuation

**Comment by daviddias** [comment]
Understood. Thanks for reviewing the proposal, dropping it based on feedback.
