### ISSUE TITLE
files.ls: no response or error after remove all preload address from bootstrap

### ISSUE THREAD

**Issue by alx696** [ipfs/js-ipfs#1818]
- **Version**: 0.33.1
- **Platform**: Chrome 71.0.3578.98
- **Subsystem**:

##### 1. remove preload.ipfs.io from bootstrap
```
    ipfs.bootstrap.rm('/dns4/node0.preload.ipfs.io/tcp/443/wss/ipfs/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic')
        .then(() => {
          ipfs.bootstrap.rm('/dns4/node1.preload.ipfs.io/tcp/443/wss/ipfs/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6')
              .then(() => {
                ipfs.bootstrap.list()
                    .then(results => {
                      console.debug('bootstrap:', results);
                    });
              });
        });
```
##### 2. execute files.ls()
```
ipfs.files.ls('/ipfs/QmWugc7FyF4HPqyVWhViWy5jWdnAv6hBg6q8swXbBSej7j')
```
no network request, no response, no error.

But if execute `ipfs.files.get()`, error will show:
```
js-ipfs_min.js:1 GET https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmWugc7FyF4HPqyVWhViWy5jWdnAv6hBg6q8swXbBSej7j net::ERR_CONNECTION_TIMED_OUT
```

### Is there anyway to change the preload node address? How to set it?
> `/dns4/node1.preload.ipfs.io/tcp/443` looks like a special server, `https://node0.preload.ipfs.io/api` looks like a normal IPFS HTTP API, but the js node can not connect ipfs node now.

**Comment by alanshaw** [comment]
You can remove preload node addresses setting the [`preload.addresses`](https://github.com/ipfs/js-ipfs#optionspreload) configuration value to `[]`.

You can also remove bootstrap nodes (the proload nodes) by setting your own [`config.Boostrap`](https://github.com/ipfs/js-ipfs#optionsconfig) addresses.

Hope that helps!
