### ISSUE TITLE
feature: p2p stream

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#1828]
Apparently go-ipfs now supports, in its external interface, dialing to a specific peer and protocol.
I'm not sure what are the plans for also adding this to the js-ipfs interface and implementing it.

This would be very helpful, allowing applications to use custom protocols in a standard way that would be usable across IPFS implementations.

**Comment by alanshaw** [comment]
@pgte we're working on [exposing libp2p as `ipfs.libp2p`](https://github.com/ipfs/js-ipfs/issues/1664) but is accessible as `ipfs._libp2pNode` right now.

I think this is really a question for @jacobheun/@vasco-santos.

**Comment by pgte** [comment]
@alanshaw understood, that’s the way I used to do it, but wewould need a standard way to access this, having the same interface whether across HTTP or using embedded js-ipfs. Is this something that can be incorporated in the standard interface?

No dia 18/01/2019, às 13:00, Alan Shaw <notifications@github.com> escreveu:

**Comment by jacobheun** [comment]
@pgte could you elaborate on what you'd like to use the interface for? We are looking at improving the libp2p interfaces and it would be helpful to better understand the use cases you need. We could look at replicating the `ipfs p2p` interfaces from go, but I'd like to have a better understanding of what's needed before we do that.

**Comment by pgte** [comment]
@jacobheun In the browser, after I discover a peer and I have the peer address(es), we need to open a custom libp2p protocol to it, which returns me a duplex stream.
Right now we're using `ipfs._libp2p.dial()`, but that makes this application incompatible with using the HTTP interface with either go or js-ipfs running as daemons.

Instead, we would like to be able to open and use, from the browser, a duplex stream to a specific peer and protocol. It would have to support the browser clients (websockets) and I should be able to use an embedded IPFS node without any code change.

**Comment by pgte** [comment]
Another perhaps interesting aspect of this:
The current go implementation of the p2p command has a native socket interface.
We would require it to run over websockets.. ([see comment](https://github.com/ipfs-shipyard/peer-pad/issues/285#issuecomment-456198970))

**Comment by jacobheun** [comment]
Looking at the go p2p api, unless I am missing something, it looks like opening a stream to a specific peer and protocol for an embedded node isn't really supported. Most of the logic seems to be built around forwarding streams. It feels like a simpler approach would be: 
```js
const stream = ipfs.p2p.open(protocol, targetAddress)
```

**Comment by pgte** [comment]
I was talking about supporting this go-ipfs feature:

<img width="614" alt="1__bash" src="https://user-images.githubusercontent.com/47910/51536076-4a9d2c00-1e42-11e9-8f05-d4d5b1fc8e53.png">

Yes, that JS API would work.

**Comment by pgte** [comment]
(with an optional third argument for the peer address, similarly to the go-ipfs CLI)

**Comment by jacobheun** [comment]
Ah! I'm running a recent build of go-ipfs master (0.4.19-dev) and `dial` is not in there. What version of go-ipfs are you running?

I think we can just stick to that existing go functionality, `ipfs.p2p.streams.dial(...)`, to keep them the same. If dial accidentally got removed I'll create an issue in go-ipfs.

**Comment by jacobheun** [comment]
Yeah, it was removed in https://github.com/ipfs/go-ipfs/pull/4929. @magik6k we're looking at adding the p2p streams dial command that was previously in go into js-ipfs. Is there a reason that was removed? The dial command is really convenient for js-ipfs nodes. It looks like it was removed in favor of an ssh approach.

**Comment by magik6k** [comment]
There was a major refactor of this feature in 0.4.18, see https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md#commands for more details. `p2p stream dial` changed name to `p2p forward`

**Comment by jacobheun** [comment]
Ok, I think we may want to update the docs for the command at some point. Using the cli `--help` to get more information about the commands locally it isn't very clear what the command is doing, or why/when it should be used, and the description is kind of a circular definition.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
