### ISSUE TITLE
ipfs.files.mkdir at one peer and can not see the dir at another peer

### ISSUE THREAD

**Issue by MarkAsir** [ipfs/js-ipfs#1838]
I had made a directory by command "ipfs.files.mkdir" at one peer,and  then i want access the directory at another peer.But it can be not.
Is that normal？
And I want  to more mechanism about mfs. Will changes in mfs be synchronized to other nodes?
version:0.4.18

**Comment by alanshaw** [comment]
> I had made a directory by command "ipfs.files.mkdir" at one peer,and then i want access the directory at another peer

You can use [`ipfs.files.stat('/your-directory')`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filesstat) to get the current CID of the directory and then access it's content from another peer using `ipfs.get('CID')`.

Note that if you add/edit or remove things from the directory it's CID will change.

> Will changes in mfs be synchronized to other nodes?

There is no synchronization in IPFS.

**Comment by its-VSP** [comment]
Hi @alanshaw 
How to get the hash of the root which is keeping track of these references(i mean files and sub-folders)
