### ISSUE TITLE
null error on Safari when using pub/sub

### ISSUE THREAD

**Issue by hazae41** [ipfs/js-ipfs#1846]
- **Version**: 0.34+
- **Platform**: Safari MacOS & iOS
- **Subsystem**: pubsub, libp2p

#### Description: 
![](https://i.imgur.com/iMKkOfv.png)
![](https://i.imgur.com/idZ0EV6.png)

#### Steps to reproduce the error:

Go to CrossBrowserTesting.com to use a macOS environment

Import ipfs 0.34+ from unpkg (minified or not)
`<script src="https://unpkg.com/ipfs@0.34.4/dist/index.js"></script>`

Enable pubsub in node config
`const node = new Ipfs({
  EXPERIMENTAL: { pubsub: true },
  config: {
    Addresses: {
      Swarm: [
        "/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star"
      ]
    }
  }
});`

Use `node.pubsub.publish` or `node.pubsub.subscribe`

**Comment by Hazae41** [comment]
Everything works fine on 0.33.1

**Comment by alanshaw** [comment]
Are you using pubsub before or after the ready event?

**Comment by Hazae41** [comment]
After, of course

Le jeu. 24 janv. 2019 à 23:46, Alan Shaw <notifications@github.com> a
écrit :

**Comment by alanshaw** [comment]
Do you get the same error on other browsers?

**Comment by Hazae41** [comment]
Only on Safari

>
