### ISSUE TITLE
[Critical] ipfs repo is using level down on browser

### ISSUE THREAD

**Issue by x5engine** [ipfs/js-ipfs#1847]
Hello Guys,

I am using the same code in the example browser
 with ipfs 0.34.4
```

    const options = {
      EXPERIMENTAL: {
        pubsub: true
      },
      repo: 'ipfs-' + Math.random(),
      config: {
        Addresses: {
          Swarm: ['/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star']
        }
      }
    }

    node = new IPFS(options)
```
but is giving me this error and I don't know why!

![image](https://user-images.githubusercontent.com/12363020/51794758-d19f2b00-21d9-11e9-822f-83f71df568c5.png)

- **Version**: 
- **Platform**: React, Javscript on Cloud9 

#### Steps to reproduce the error:

Just install ipfs and use it and you will get this error and I dont know why it using leveldown which doesnt work in the browser...

Thank you

**Comment by x5engine** [comment]
Sure I can share some code with you

**Comment by alanshaw** [comment]
@x5engine FYI we use [`level-js` in the browser](https://github.com/ipfs/js-datastore-level/blob/master/package.json#L8)

**Comment by alanshaw** [comment]
@x5engine I need an example I can run that demonstrates the error - I can't help you debug this otherwise.

**Comment by x5engine** [comment]
@alanshaw okay sure, pretty simple clone this repo and use the code we have here

git clone https://github.com/cleverbeagle/pup 

install meteor

https://www.meteor.com/install

then npm install then npm start that's it

thank for your help

**Comment by alanshaw** [comment]
@x5engine where should I put the "code we have here" in that project - I just want to ensure I'm doing the same thing as you.

**Comment by alanshaw** [comment]
ping @x5engine

**Comment by x5engine** [comment]
@alanshaw where ever you want, on the index page(component) or anywhere so you can load that page and see that bug being thrown.

thank you

**Comment by alanshaw** [comment]
I'm getting the following error:

```console
W20190308-17:23:06.736(0)? (STDERR) /Users/alan/Desktop/pup/node_modules/pull-stream-to-async-iterator/index.js:4
W20190308-17:23:06.736(0)? (STDERR)   return (async function * () {
W20190308-17:23:06.736(0)? (STDERR)                          ^
W20190308-17:23:06.736(0)? (STDERR) 
W20190308-17:23:06.737(0)? (STDERR) SyntaxError: Unexpected token *
W20190308-17:23:06.737(0)? (STDERR)     at createScript (vm.js:80:10)
W20190308-17:23:06.737(0)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
W20190308-17:23:06.737(0)? (STDERR)     at Module._compile (module.js:616:28)
W20190308-17:23:06.737(0)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190308-17:23:06.737(0)? (STDERR)     at Module.load (module.js:565:32)
W20190308-17:23:06.737(0)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190308-17:23:06.738(0)? (STDERR)     at Function.Module._load (module.js:497:3)
W20190308-17:23:06.738(0)? (STDERR)     at Module.require (module.js:596:17)
W20190308-17:23:06.738(0)? (STDERR)     at require (internal/module.js:11:18)
W20190308-17:23:06.738(0)? (STDERR)     at Object.<anonymous> (/Users/alan/Desktop/pup/node_modules/async-iterator-to-pull-stream/index.js:2:20)
W20190308-17:23:06.738(0)? (STDERR)     at Module._compile (module.js:652:30)
W20190308-17:23:06.738(0)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190308-17:23:06.739(0)? (STDERR)     at Module.load (module.js:565:32)
W20190308-17:23:06.739(0)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190308-17:23:06.739(0)? (STDERR)     at Function.Module._load (module.js:497:3)
W20190308-17:23:06.739(0)? (STDERR)     at Module.require (module.js:596:17)
W20190308-17:23:06.739(0)? (STDERR)     at require (internal/module.js:11:18)
W20190308-17:23:06.740(0)? (STDERR)     at Object.<anonymous> (/Users/alan/Desktop/pup/node_modules/ipfs-unixfs-importer/src/importer/dir-sharded.js:13:16)
W20190308-17:23:06.740(0)? (STDERR)     at Module._compile (module.js:652:30)
W20190308-17:23:06.740(0)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190308-17:23:06.740(0)? (STDERR)     at Module.load (module.js:565:32)
W20190308-17:23:06.740(0)? (STDERR)     at tryModuleLoad (module.js:505:12)
```

**Comment by alanshaw** [comment]
I added `<script src="https://cdn.jsdelivr.net/npm/ipfs/dist/index.min.js"></script>` to `client/main.html` and the following code to `ui/layouts/App/index.js`:

<img width="816" alt="screenshot 2019-03-08 at 17 45 01" src="https://user-images.githubusercontent.com/152863/54045602-f66bc280-41c9-11e9-8c1c-82dbd87042cf.png">

I didn't get any errors on the client and was able to add/cat data:

<img width="1072" alt="screenshot 2019-03-08 at 17 45 41" src="https://user-images.githubusercontent.com/152863/54045649-18fddb80-41ca-11e9-9976-f4bc56460794.png">

Please let me know if I'm doing something differently from you?

**Comment by daviddias** [comment]
Declaring this one as solved :) Thanks @alanshaw !
