### ISSUE TITLE
Support exposing API/Gateway on multiple multiaddrs

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#1852]
go-ipfs supports listening on multiple multiaddrs if an array is provided instead of a single multiaddr. 

Both snippets are valid in go-ipfs:

#### ipv4+ipv6

```json
	"Addresses": {
		"API": [
			"/ip4/127.0.0.1/tcp/5002",
			"/ip6/::1/tcp/5002"
		],
		"Gateway": [
			"/ip4/127.0.0.1/tcp/9090",
			"/ip6/::1/tcp/9090"
		],
```

#### ipv4 only

```json
	"Addresses": {
		"API": "/ip4/127.0.0.1/tcp/5002",
		"Gateway": "/ip4/127.0.0.1/tcp/9090",
```

Unfortunately js-ipfs does not support arrays, only a single address can be defined ATM. 

cc https://github.com/ipfs/js-ipfs/issues/1563, https://github.com/ipfs/go-ipfs/issues/5905

**Comment by alanshaw** [comment]
@grantlouisherman YES ❤️ it would be awesome if you'd like to take this on. Please ping me if you need any pointers.

**Comment by grantlouisherman** [comment]
hey @alanshaw I opened this PR for this issue:https://github.com/ipfs/js-ipfs/pull/1896
One of the checks failed and I'm also getting the same error locally with master and I'm not really sure why. It's coming from libp2p. I see that there is https://github.com/ipfs/js-ipfs/tree/chore/update-libp2p. Should I not be working off of master?

**Comment by grantlouisherman** [comment]
hey @alanshaw PR is here https://github.com/ipfs/js-ipfs/pull/1903

**Comment by grantlouisherman** [comment]
hey @alanshaw could you assign someone to that PR whenever it is prudent. I just need some help with the test cases.
