### ISSUE TITLE
How to use dist/index.min.js in node-cli

### ISSUE THREAD

**Issue by cloudbitsum** [ipfs/js-ipfs#1859]
Hi,
I am new so please excuse any basic questions? I am student in std-12 and learning IPFS. It looks great.
I want to know if there is any way to use index.min.js in node-cli.
I know that I can simply import ipfs by require("ipfs"). But the require() create a big node_module which is an issue for school project. Also I dont have option to build a browser based app.
So I am looking to use index.min.js in node-cli server side. Or some way to similarly generate a minified fine.

Doing a require of index.min.js gives error that window is missing.

Please help.

**Comment by alanshaw** [comment]
ahhh, my mistake!

**Comment by cloudbitsum** [comment]
Thanks @alanshaw 
I will create one PR

**Comment by jollysean** [comment]
This is very interesting. I can try

**Comment by jollysean** [comment]
@alanshaw This shall need target:'node' in aegir/src/config/webpack.config.js Right?

**Comment by alanshaw** [comment]
Yes I think you can override webpack settings in Aegir config.

Also relavant: https://github.com/zeit/pkg (thanks @hugomrdias)

**Comment by hugomrdias** [comment]
Our aegir build is not meant for node things. Please open an issue in the ipfs/aegir with your use case and i'll have a look. 

In the mean time check either pkg @alanshaw mentioned or https://github.com/zeit/ncc and see if any of these fit your use case.

**Comment by jollysean** [comment]
Oh, well, I see. @cloudbitsum https://github.com/zeit/ncc is your thing. It would give you one require'able index.js
