### ISSUE TITLE
Implement --pin option for block.put and dag.put

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1867]
go-ipfs already has `--pin` for `dag.put` and `--pin` for `block.put` is in a PR https://github.com/ipfs/go-ipfs/pull/5969

**Comment by grantlouisherman** [comment]
@alanshaw Ill take a look at this 💯

**Comment by grantlouisherman** [comment]
Hey @alanshaw do you want the put DAG command added as well?

**Comment by grantlouisherman** [comment]
hey @alanshaw could you take a look at this question I raised on discuss.ipfs.io and let me know if you have any advice? https://discuss.ipfs.io/t/using-jsipfs-pin-add/5044

**Comment by grantlouisherman** [comment]
https://github.com/ipfs/js-ipfs/issues/1953

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

@achingbrain resolving this one for you, as I believe a migration path is available for this.
