### ISSUE TITLE
Keeping passphrase secret in frontends

### ISSUE THREAD

**Issue by luzzif** [ipfs/js-ipfs#1892]
A passphrase is required in order to use the key management functionality offered by the library, which is totally fine with me. 
**But**, I'm using React and I would like to know if there was a way to keep the passphrase completely hidden and secure without hardcoding it in the final bundle. Is that a thing?

**TLDR;** How can I keep my passphrase secret if I'm using React, or any other frontend framework really?

**Comment by alanshaw** [comment]
> I would like to know if there was a way to keep the passphrase completely hidden and secure

If the passphrase must be shared and it is a public service then no.

> How can I keep my passphrase secret if I'm using React, or any other frontend framework really?

Generate it on the client or ask the user for one?
