### ISSUE TITLE
electron update failed

### ISSUE THREAD

**Issue by josselinchevalay** [ipfs/js-ipfs#1897]
Hello 

- 0.35.0-pre.0
- Linux 64
- Debian
#### Type:
Bug

#### Severity:
Critical - My application in electron not works

#### Description:
```
 return acquireLock(file, { ...options, stale: 0 }, callback);
                                               ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .js] (/home/josselin/develop/telescope/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

#### Steps to reproduce the error:

- Update electron and ipfs in package.json
  "electron": "^2.0.0",
   "electron-rebuild": "^1.7.2",
   "ipfs":"js-ipfs"

- run npm install

- run electron start .

**Comment by hugomrdias** [comment]
this is valid js what is your runtime env in electron ? can't you just transpile object spread with babel ?

**Comment by josselinchevalay** [comment]
how to check electron env runtime ?

**Comment by hugomrdias** [comment]
from my limited experience with electron it should be based on chromium which should support object spread unless it is really old version. 
@olizilla or @hacdias can you help here ?

**Comment by elantion** [comment]
Facing same issue. Try to update electron from 2.* to 4.*, but no luck. Occur another error.

`
Uncaught Exception:
Error: Unable to update lock within the stale threshold
    at options.fs.stat (/Users/yinjames/Projects/lc-ipfs/node_modules/proper-lockfile/lib/lockfile.js:121:25)
    at /Users/yinjames/Projects/lc-ipfs/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
`

**Comment by josselinchevalay** [comment]
my pull request solve issue with examples but in my code when a use  elactron in version 4 and use build.sh script i continue to have same issue. :thinking:  weird ....

**Comment by josselinchevalay** [comment]
i created a issue on this project https://github.com/moxystudio/node-proper-lockfile/issues/84

**Comment by alanshaw** [comment]
Lets track this here now https://github.com/ipfs/js-ipfs/issues/2011
