### ISSUE TITLE
Why has js-ipfs been unable to upload recently, but go-ipfs can, and instantly?

### ISSUE THREAD

**Issue by Despoinis** [ipfs/js-ipfs#1898]
If it is a network problem, why is go-ipfs working very well, and js-ipfs is always difficult to upload successfully?
The same is true for updating the latest version.
What is the difference between js-ipfs and go-ipfs?
Go-ipfs, which can be downloaded on ipfs.infura.io the next second after executing ipfs add.
Js-ipfs has to wait a long time after add, but most of them are now 504.

**Comment by alanshaw** [comment]
@Despoinis please follow progress on this issue here https://github.com/ipfs/js-ipfs/issues/1874
