### ISSUE TITLE
UnhandledPromiseRejectionWarning: #<Object> at jsipfs init

### ISSUE THREAD

**Issue by bazquezero** [ipfs/js-ipfs#1900]
- **Version**: Syntax Error thrown
- **Platform**: Darwin
- **Subsystem**:

#### Type:
Bug

#### Severity:
Critical

#### Description:
After installing the latest version of the package, which I'm assuming is the 0.34.4 since the script to retrieve the version failed, the script throws a error about an unhandled rejection on a promise

#### Steps to reproduce the error:
Error initializating jsipfs
![screen shot 2019-02-26 at 13 46 40](https://user-images.githubusercontent.com/38488822/53445180-36ae9200-39cd-11e9-981a-cd909a3bfd23.png)

Error retrieving version
![screen shot 2019-02-26 at 13 47 21](https://user-images.githubusercontent.com/38488822/53445190-3a421900-39cd-11e9-84d4-a998feb1207d.png)

**Comment by UtopiaCreatorX** [comment]
+1

**Comment by alanshaw** [comment]
@bazquezero looks like you're using an old version of Node.js. Please upgrade to v10+ and try again!
