### ISSUE TITLE
 UnhandledPromiseRejectionWarning when jsipfs daemon

### ISSUE THREAD

**Issue by UtopiaCreatorX** [ipfs/js-ipfs#1904]
(node:10724) UnhandledPromiseRejectionWarning: #<Object>
(node:10724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 2)
(node:10724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
![1551379000](https://user-images.githubusercontent.com/43801745/53589668-eac93c00-3bca-11e9-9d53-7667d189746e.png)

**Comment by UtopiaCreatorX** [comment]
It's OK when I use the command 'jsipfs daemon' locally, but it is wrong when on the rented server.

**Comment by alanshaw** [comment]
@UtopiaCreatorX can you enable debug logging and then check the output? `DEBUG=* jsipfs daemon`

My guess is that there's something already listening on the ports js-ipfs is trying to bind to.

**Comment by alanshaw** [comment]
ping @UtopiaCreatorX

**Comment by daviddias** [comment]
Closing for lack of follow up from the user. Reopen if necessary.
