### ISSUE TITLE
last realeased version has security vulnerability in it's dependencies

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#1905]
- **Version**: 0.34.4
- **Platform**: *
- **Subsystem**: *

#### Description: Github reports potential security vulnerability for anything that depends on ipfs package

<img width="763" alt="screen shot 2019-03-01 at 2 05 28 pm" src="https://user-images.githubusercontent.com/21236/53669184-1b40c280-3c2b-11e9-8cc4-2ef29aa6f1b6.png">

#### Steps to reproduce the error:

Create package that depends on ipfs package and push to github. Here is my [`.yarnlock`](https://github.com/Gozala/ipdf/blob/042447b6ab73ac9e0fde388010233eb4bb31d455/yarn.lock) file that triggered the warning.

You can see [hapi depending on cryptiles](https://github.com/Gozala/ipdf/blob/042447b6ab73ac9e0fde388010233eb4bb31d455/yarn.lock#L1404)
and other two packages that are also hapi's dependencies. And hapi is being depended by ipfs and bunch of other it's dependencies.

**Comment by alanshaw** [comment]
Hapi no longer depends on this module and we upgraded from v16 \o/
