### ISSUE TITLE
Please consider exposing multicodec along with other dependencies

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#1913]
I'm working on https://github.com/gozala/ipdf/ where I need to encode codec format in the buffer before encrypting it so during encryption I can figure out what format to use in decoding.

Provided an ipfs node instance implementation has access to everything it needs to do it's job except of [`multicodec`](https://github.com/multiformats/multicodec) that IPFS implementation internally depends upon. Please consider exposing it along with other dependencies in `ipfs.types.` as that would avoid pulling in separately library & any versioning mismatches that could arise from that.

**Comment by alanshaw** [comment]
SGTM, what other dependencies would be useful?

**Comment by Gozala** [comment]
> SGTM, what other dependencies would be useful?

Not sure, have not come across anything else yet, I'll open separate issues if I will.

One thing that might be worth considering is to expose `types / utils` such that they can be accessed without instantiation of IPFS node maybe as static field on the constructor ? In lunet codebase I found myself having to pass IPFS instance to some functions just so I could use `CID`. I could use lazy initialization however that introduces timing and indirection that I would much rather not have to deal with.

**Comment by alanshaw** [comment]
> One thing that might be worth considering is to expose `types / utils` such that they can be accessed without instantiation of IPFS node maybe as static field on the constructor ?

This is how it will be in 0.35 when released :D see https://github.com/ipfs/js-ipfs/pull/1908

**Comment by niinpatel** [comment]
Can I take up this issue @alanshaw

**Comment by alanshaw** [comment]
Yes please!

**Comment by niinpatel** [comment]
PR is ready #1921
