### ISSUE TITLE
Resolving DNSLink Paths: /ipns/<fqdn>

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#1918]
> Part of an effort to run embedded js-ipfs in Brave :lion: https://github.com/ipfs-shipyard/ipfs-companion/issues/716

- **Version**: js-ipfs v0.34
- **Platform**: browser
- **Subsystem**: `ipfs.resolve` and `ipfs.name.resolve`

#### Description:

js-ipfs v0.34 supports `/ipns/<peerid>`, but trying to resolve `/ipns/<fqdn>` produces errors (the error is different for each method).

Calling `ipfs.dns('docs.ipfs.io').then(console.log)` resolves DNSLink correctly, so I assume all pieces are in place and this is just a bug/missing some wiring – is this correct?

Is this on someones TODO or is it up for grabs?

#### Steps to reproduce the error:

- `ipfs.resolve('/ipns/docs.ipfs.io/assets/logo.svg', {recursive: true})`
  - go-ipfs returns `/ipfs/QmY7Yh4UquoXHLPFo2XbhXkhBvFoPwmQUSa92pxnxjQuPU`
  - js-ipfs throws `Error: resolve non-IPFS names is not implemented` ([from  this line](https://github.com/ipfs/js-ipfs/blob/v0.34.4/src/core/components/resolve.js#L22-L25))

- `ipfs.name.resolve('/ipns/docs.ipfs.io/assets/logo.svg', {recursive: true})`
  - go-ipfs returns `/ipfs/QmYz85ubdabSrraMnodhMMosiHv9WURJASEC5D6ojTgm4X/assets/logo.svg`
  - js-ipfs throws `Error: Non-base58 character` ([from  this line](https://github.com/ipfs/js-ipfs/blob/v0.34.4/src/core/ipns/resolver.js#L95))

**Comment by alanshaw** [comment]
Not really a bug, just not implemented yet...although `ipfs.name.resolve` is not handling it well!

**Comment by niinpatel** [comment]
@alanshaw I'll take a look after #1935 is merged.
