### ISSUE TITLE
ipfs.swarm.connect wrong: Circuit not enabled and all transports failed to dial peer

### ISSUE THREAD

**Issue by xialvjun** [ipfs/js-ipfs#1919]
- **Version**: 0.34.4
- **Platform**: Darwin xia.lan 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
- **Subsystem**: Mac Chrome 72.0.3626.119

#### Type:
Bug

#### Severity:
High

#### Description:
Circuit not enabled and all transports failed to dial peer

```
ipfs.on('start', () => {
  ipfs.swarm.connect('/ip4/67.216.192.126/tcp/4001/ipfs/QmY1UPt3yVCBnCD83L3rZXDvFpkUwwE8P4hr15TANDJh4v', (err, res) => {
    if (err) {
      return throw err;
    }
    console.log(res);
  });
});
```
always throw error even run `go-ipfs` with `ipfs swarm connect /ip4/67.216.192.126/tcp/4001/ipfs/QmY1UPt3yVCBnCD83L3rZXDvFpkUwwE8P4hr15TANDJh4v` is ok.

![image](https://user-images.githubusercontent.com/4413712/54173959-08e24680-44bf-11e9-8ad2-1a0ba6bfe2cf.png)
![image](https://user-images.githubusercontent.com/4413712/54173973-1ef00700-44bf-11e9-8d53-1f90d04f0470.png)

#### Steps to reproduce the error:
open this html
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <script src="https://unpkg.com/ipfs@0.34.0/dist/index.js"></script>
    <script>
      const ipfs = new Ipfs({ repo: "ipfs-" + Math.random() });
      ipfs.on("start", () => {
        console.log("Node started!");
        ipfs.swarm.connect("/ip4/67.216.192.126/tcp/4001/ipfs/QmY1UPt3yVCBnCD83L3rZXDvFpkUwwE8P4hr15TANDJh4v", (err, res) => {
          if (err) {
            return console.error(err);
          }
          console.log("peer ok: ", res);
        });
      });
    </script>
  </body>
</html>
```

**Comment by alanshaw** [comment]
@xialvjun you can't connect to tcp addresses in the browser due to same origin policy. You could use websockets instead. Check out this example for more information:

https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser
