### ISSUE TITLE
Getting content from browser node to gateway using 0.35 RC

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#1923]
- **Version**: js-ipfs 0.35 RC
- **Platform**: Browser (Chromium)
- **Subsystem**: ipfs add / ipfs get

#### Description:
I'm running a browser node with js-ipfs 0.35 with DHT enabled. I'm adding content via a simple `ipfs.add` call. I can retrieve the content locally, and via a directly-connected peer via `ipfs.get` but I can't seem to get a public gateway.

What's odd is that I'm fairly certain I used to be able to do this with previous versions of `js-ipfs`, but maybe I'm crazy and I'm not remembering correctly.

#### Steps to reproduce the error:

Here's my IPFS confug on the browser node, let me know if you need any other information.

```javascript
// js-ipfs version 0.35 RC

new IPFS({                                                         
  preload: { enabled: false },                                                  
  relay: { enabled: true, hop: { enabled: true, active: true } },               
  EXPERIMENTAL: { pubsub: true, dht: true },                                    
  repo: "./ipfs",                                                               
  config: {                                                                     
    Addresses: {                                                                
      Swarm: ['/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star']
    }                                                                           
  }                                                                             
});                                                                             
```

Adding content to a browser node using this configuration and then trying to load it via a public gateway like https://ipfs.io causes a content timeout.

**Comment by cryptoquick** [comment]
I think this is related to #1526 and #1942 
Definitely feeling the pain on this one, and I'll do my best to investigate, but I'm not seeing anything obvious pop out at me just yet.

**Comment by vasco-santos** [comment]
This is related with the usage of the `libp2p-kad-dht`. FYI We will be working on rewriting the DHT according to the most recently changes on `go-libp2p-kad-dht`once the Spec is done. After that, we should revisit if this is a problem

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
