### ISSUE TITLE
browser-create-react-app example doesn't work with js-ipfs

### ISSUE THREAD

**Issue by niinpatel** [ipfs/js-ipfs#1924]
- **Version**:
js-ipfs version: 0.35.0-rc.0
- **Platform**:
Windows 10 64-bit
Google Chrome Version 73.0.3683.75
- **Subsystem**: js-ipfs

#### Description:

I tried to run the example implementation from examples/browser-create-react-app. 

It only works correctly when go-ipfs daemon is running. Here's a preview when go-ipfs node is running in the computer. 

![image](https://user-images.githubusercontent.com/31539366/54244387-6ffd0b00-4552-11e9-8f4f-4bd3701aca19.png)

But when I run js-ipfs instead of go-ipfs, it fails: 

![js-ipfs-react-not-working](https://user-images.githubusercontent.com/31539366/54244423-9327ba80-4552-11e9-9157-a15a612846f8.PNG)

#### Steps to reproduce the error:

Step 1: run the js-ipfs daemon
Step 2: cd into examples/create-react-app and run `npm install && npm start`

**Comment by alanshaw** [comment]
Looks like you're using IPFS Companion - was companion connected to the JS IPFS node when you tried this? Companion shouldn't be injecting `window.ipfs` if it doesn't have a connection to a node... @lidel have you seen this before?

**Comment by niinpatel** [comment]
@alanshaw, I just realized it happened because IPFS companion was connected. If I remove the chrome extension, it works fine. IPFS companion was probably injecting its own `window.ipfs` in this.

**Comment by lidel** [comment]
@alanshaw I am afraid that in Chrome `window.ipfs` is always injected. 
This is due to  https://github.com/ipfs-shipyard/ipfs-companion/issues/362#issuecomment-362231167 

I hope this behavior will go away with  https://github.com/ipfs-shipyard/ipfs-companion/issues/589 - after move to async API and removal of `window.ipfs` we won't need the guarantee of being the first script on the page. I plan to remove hardcoded content scripts responsible for injection from the manifest, and do it programmatically like in Firefox.

**Comment by alanshaw** [comment]
Ah yes I remember now!

**Comment by kuabhish** [comment]
Hey @alanshaw @lidel  

I do not understand this problem .. and solution.. 

I was working on windows ..ad i could add the files and view them  somehow.. 

but as i am in ubuntu now --and I see that .. 

1. I am able to add file from running a normal script. like node.add ()..
2. and able to fetch it

but 
1. not able to fetch anything if i do the same thing with a react app. (which i could do in windows .. 
)

**Comment by lidel** [comment]
@kuabhish I don't believe the problems you experience are  related to this issue. 
IPFS Companion is not injecting `window.ipfs` at the moment.

Please create new issue and provide more details about your setup and what you want to archieve.
