### ISSUE TITLE
`ipfs.dns` does not have "recursive" option

### ISSUE THREAD

**Issue by niinpatel** [ipfs/js-ipfs#1931]
Version:
js-ipfs version: 0.35.0-rc.0
Platform:
Windows 10 64-bit
Google Chrome Version 73.0.3683.75
Subsystem: `ipfs.dns`

#### Description:
go-ipfs implementation has `--recursive` option to resolve dns links. 
js-ipfs throws this error: "Not enough non-option arguments: got 0, need at least 1"

#### Steps to reproduce the error:
**go-ipfs**: 
`ipfs dns --recursive ipfs.io`
resolves to: /ipfs/QmTxvVbLQTm9qvh4wsdhehDGPy92LJSYiyAg5sh3X2ZaUE

**js-ipfs**:
`jsipfs dns --recursive ipfs.io`: 
throws: "Not enough non-option arguments: got 0, need at least 1"

**Comment by alanshaw** [comment]
Thanks for reporting @niinpatel, it would be great to get this implemented.

**Comment by niinpatel** [comment]
Yes, once this feature is implemented, I think it'd be much easier to implement #1918. I'll take a shot at implementing this.
