### ISSUE TITLE
IPFS node ready handler not called

### ISSUE THREAD

**Issue by rmisio** [ipfs/js-ipfs#1936]
IPFS versions 0.34.4

When I run the simple initial tutorial code:

```
const IPFS = require('ipfs')

const node = new IPFS()

node.on('ready', async () => {
  const version = await node.version()

  console.log('Version:', version.version)
})
```

It produces no output.

I also added a generic error handler in there in case something would show there, but nothing comes there either:

```
node.on('error', error => {
  console.error(error.message);
});
```

I've tested this in `0.34.4` as well as a few older versions, as well as `#master`. I either get the same behavior or the following error: `version mismatch: expected v6, found v7`

**Comment by rmisio** [comment]
For kicks, I did try to interact with the node 3 seconds later... thinking maybe the node is actually ready, but there's a bug preventing the `ready` handler from firing.

But.. my file add attempt results in an error:

`/Users/rob/develop/ipns-sizzle/node_modules/ipfs-block-service/src/index.js:64
      this._repo.blocks.put(block, callback)`

Here's the related code:

```
setTimeout(() => {
  node.add(Buffer.from('We are the world. We are the children.'))
    .then(theGoods => {
      console.dir(theGoods);
    })
    .catch(e => {
      console.error('add file err');
      console.error(e);
    });
}, 3000);
```

**Comment by alanshaw** [comment]
Can you try running `npm rebuild` and then try again? Post the output here if it doesn't work.

**Comment by rmisio** [comment]
ok, that worked. Yeah, I had to upgrade node because one of the deps had an async generator in it, which my version of node couldn't handle. I didn't realize updating node required an npm rebuild. Good to know and thanks!
