### ISSUE TITLE
Unable to connect to node via relay

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/js-ipfs#1938]
Trying to get js-ipfs working in a basic relay scenario, fetching data from my go-ipfs node. Running into lots of random issues, but currently i'm getting `Error: No available transports to dial peer QmXV9SP77P91TPgysRBQCXmtWfVcecu4fAdbjfSzX2GkZh!`

My code is here: https://gist.github.com/whyrusleeping/bf8160f83f0a614173772010ed0535a2

Note that I explicitly do not want to use the preload servers, or connect to any of our public default bootstrappers. With the normal bootstrappers and prefetch on, this works. But thats really cheating. The code I have in that gist *should* work, theres no need for content routing to fetch the content from the remote peer, it just seems like relaying isnt working.

Any idea what i'm doing wrong?

cc @karalabe as we were talking about this

**Comment by daviddias** [comment]
Checking out the code. I see that there is an expectation that __without Peer Routing enabled__ for a node to always try to use relays it learns about. AFAIK that isn't there today or was never planned.

That said, I did add the first node to check if it would relay through the bootstrapper and it did not happen (see https://codepen.io/daviddias/pen/qvYZGJ?editors=0010)

@alanshaw @jacobheun are bootstrappers active relays?

**Comment by jacobheun** [comment]
This looks like it's an issue with the order of the `connect` call and an expectation that `'ready'` is fired after the bootstrap nodes are connected to.  In an older version of `libp2p-bootstrap`, bootstrapping would take 10 seconds (it was an interval based discovery system, that did not trigger on start). That is likely packaged with the distro version being used here. So when the node is `'ready'`, there aren't actually any peers yet, so when you try to connect via circuit it fails. One way around this is to wait for a peer connection: 

```js
node.libp2p.once('peer:connect', () => {
  // Perform connect request
})
```

> @alanshaw @jacobheun are bootstrappers active relays?

I am not sure if they're active relays, but they should have HOP support.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
