### ISSUE TITLE
Unable to install IPFS using npm

### ISSUE THREAD

**Issue by ukrocks007** [ipfs/js-ipfs#1941]
- **Version**: 0.34.4
- **Platform**: mac
- **Subsystem**: 

#### Description: > keccak@1.4.0 rebuild /Users/utkarshmehta/.npm-global/lib/node_modules/ipfs/node_modules/keccak
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/keccak/src/addon.o
../src/addon.cc:37:34: warning: 'IntegerValue' is deprecated:
      Use maybe version [-Wdeprecated-declarations]
    unsigned int rate = info[0]->IntegerValue();
                                 ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8.h:2570:3: note: 
      'IntegerValue' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version", int64_t IntegerVa...
  ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:38:38: warning: 'IntegerValue' is deprecated:
      Use maybe version [-Wdeprecated-declarations]
    unsigned int capacity = info[1]->IntegerValue();
                                     ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8.h:2570:3: note: 
      'IntegerValue' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version", int64_t IntegerVa...
  ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:56:35: warning: 'IntegerValue' is deprecated:
      Use maybe version [-Wdeprecated-declarations]
    unsigned char bits = info[0]->IntegerValue();
                                  ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8.h:2570:3: note: 
      'IntegerValue' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version", int64_t IntegerVa...
  ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:64:30: warning: 'IntegerValue' is deprecated:
      Use maybe version [-Wdeprecated-declarations]
    size_t length = info[0]->IntegerValue();
                             ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8.h:2570:3: note: 
      'IntegerValue' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version", int64_t IntegerVa...
  ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:75:73: warning: 'ToObject' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
  ...= Nan::ObjectWrap::Unwrap<KeccakWrapper>(info[0]->ToOb...
                                                       ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8.h:2549:10: note: 
      'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Obje...
         ^
/Users/utkarshmehta/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
5 warnings generated.
  CC(target) Release/obj.target/keccak/src/libkeccak/KeccakSponge.o
  CC(target) Release/obj.target/keccak/src/libkeccak/KeccakP-1600-reference.o
../src/libkeccak/KeccakP-1600-reference.c:231:13: warning: 
      unused function 'fromBytesToWords' [-Wunused-function]
static void fromBytesToWords(tKeccakLane *stateAsWords...
            ^
../src/libkeccak/KeccakP-1600-reference.c:242:13: warning: 
      unused function 'fromWordsToBytes' [-Wunused-function]
static void fromWordsToBytes(unsigned char *state, con...
            ^
2 warnings generated.
  SOLINK_MODULE(target) Release/keccak.node

> secp256k1@3.6.2 install /Users/utkarshmehta/.npm-global/lib/node_modules/ipfs/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.6.2 rebuild /Users/utkarshmehta/.npm-global/lib/node_modules/ipfs/node_modules/secp256k1
> node-gyp rebuild

> tiny-secp256k1@1.0.1 install /Users/utkarshmehta/.npm-global/lib/node_modules/ipfs/node_modules/tiny-secp256k1
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/secp256k1/native/addon.o
../native/addon.cpp:17:1: error: unknown type name
      'secp256k1_context'; did you mean 'secp256k1_context_t'?
secp256k1_context* context;
^~~~~~~~~~~~~~~~~
secp256k1_context_t
/usr/local/include/secp256k1.h:50:41: note: 
      'secp256k1_context_t' declared here
typedef struct secp256k1_context_struct secp256k1_context_t;
                                        ^
../native/addon.cpp:53:28: error: unknown type name
      'secp256k1_pubkey'
        bool isPoint (const T& x, secp256k1_pubkey& pubkey) {
                                  ^
../native/addon.cpp:64:32: error: unknown type name
      'secp256k1_ecdsa_signature'
        bool isSignature (const T& x, secp256k1_ecdsa_...
                                      ^
../native/addon.cpp:70:45: error: unknown type name
      'secp256k1_pubkey'
        v8::Local<v8::Object> pointAsBuffer (const secp256k1_p...
                                                   ^
../native/addon.cpp:79:63: error: use of undeclared identifier
      'SECP256K1_EC_COMPRESSED'
  ...<= index) return __isPointCompressed(p) ? SECP256K1_EC...
                                               ^
../native/addon.cpp:79:89: error: use of undeclared identifier
      'SECP256K1_EC_UNCOMPRESSED'
  ...? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                 ^
../native/addon.cpp:80:42: error: use of undeclared identifier
      'SECP256K1_EC_COMPRESSED'
  ...if (info[index]->IsUndefined()) return SECP256K1_EC_CO...
                                            ^
../native/addon.cpp:81:40: error: use of undeclared identifier
      'SECP256K1_EC_COMPRESSED'
  ...return info[index]->BooleanValue() ? SECP256K1_EC_COMP...
                                          ^
../native/addon.cpp:81:66: error: use of undeclared identifier
      'SECP256K1_EC_UNCOMPRESSED'
  ...? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                 ^
../native/addon.cpp:86:38: error: use of undeclared identifier
      'SECP256K1_EC_COMPRESSED'
  ...if (info.Length() <= index) return SECP256K1_EC_COMPRE...
                                        ^
../native/addon.cpp:87:42: error: use of undeclared identifier
      'SECP256K1_EC_COMPRESSED'
  ...if (info[index]->IsUndefined()) return SECP256K1_EC_CO...
                                            ^
../native/addon.cpp:88:40: error: use of undeclared identifier
      'SECP256K1_EC_COMPRESSED'
  ...return info[index]->BooleanValue() ? SECP256K1_EC_COMP...
                                          ^
../native/addon.cpp:88:66: error: use of undeclared identifier
      'SECP256K1_EC_UNCOMPRESSED'
  ...? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                 ^
../native/addon.cpp:99:2: error: unknown type name
      'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:110:2: error: unknown type name
      'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:133:2: error: unknown type name
      'secp256k1_pubkey'
        secp256k1_pubkey a, b;
        ^
../native/addon.cpp:135:19: error: use of undeclared
      identifier 'b'
        if (!isPoint(pB, b)) return THROW_BAD_POINT;
                         ^
../native/addon.cpp:137:8: error: unknown type name
      'secp256k1_pubkey'
        const secp256k1_pubkey* points[] = { &a, &b };
              ^
../native/addon.cpp:137:44: error: use of undeclared
      identifier 'b'
        const secp256k1_pubkey* points[] = { &a, &b };
                                                  ^
fatal error: too many errors emitted, stopping now
      [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/utkarshmehta/.npm-global/lib/node_modules/ipfs/node_modules/tiny-secp256k1
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/utkarshmehta/.npm/_logs/2019-03-16T07_52_24_563Z-debug.log

**Comment by wlegate** [comment]
I'm having the same exact issue.

**Comment by olizilla** [comment]
If you are using node >= v12 the issue is due to the removal of native module apis from node v12 used by the `secp256k1` module

- https://github.com/bitcoinjs/tiny-secp256k1/issues/38
- https://github.com/cryptocoinjs/secp256k1-node/issues/142

js-ipfs has a transative dependency on that module, so won't build on node 12 until we find a fix.

**Comment by satazor** [comment]
They landed a new version with a fix: https://github.com/cryptocoinjs/secp256k1-node/issues/142#issuecomment-490365020

**Comment by agentofuser** [comment]
I still have this problem. Has there been a release of js-ipfs that fixes it?

**Comment by wlegate** [comment]
> I still have this problem. Has there been a release of js-ipfs that fixes it?

After spending a few days trying to work through the source code & various Issues/PRs, I ended up giving up and using [ipfs-mini](https://github.com/silentcicero/ipfs-mini#readme) to connect to a public IPFS node… not ideal, but I got it up & running in minutes

**Comment by alanshaw** [comment]
@agentofuser this should have been fixed in an in range update - can you double check you dont have a lock file that’s causing an older version to be installed? I will also double check this.

**Comment by alanshaw** [comment]
@wlegate I was unaware the http client had issues on Node.js 12 - I’ve not had an issue reported on https://github.com/ipfs/js-ipfs-http-client/issues and I’ve not had a chance to check it myself. I’ll look into this also.

It’s unfortunate it’s taken so long to fix but unfortunately it was upstream dependencies that needed fixing that we have no control over.

**Comment by agentofuser** [comment]
@alanshaw the problem is the lockfile in bitcoinjs-lib, which ipld-bitcoin depends on, which js-ipfs depends on:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/package-lock.json#L1938

I've made a pull request to update it to tiny-secp256k1 v1.1.1:

https://github.com/bitcoinjs/bitcoinjs-lib/pull/1398

I'm not using ipld at all though. It would be nice to use js-ipfs without pulling in all those dependencies.

**Comment by alanshaw** [comment]
@agentofuser I checked checked and I was able to clean install using Node.js 12.2.0. You may have seen a warning message about an _optional dependency_ `rabin` failing to install - which makes it look like it failed but it did not.

`rabin` will be fixed soon - waiting on a publish to npm: https://github.com/datproject/rabin/pull/28

Here's the end of my npm output, showing `rabin` failing to install but ipfs successfully installed (the line `+ ipfs@0.35.0`):

```
3 warnings and 3 errors generated.
make: *** [Release/obj.target/rabin/src/rabin_wrap.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alan/Desktop/test/node_modules/rabin
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN saveError ENOENT: no such file or directory, open '/Users/alan/Desktop/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/alan/Desktop/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rabin@1.6.0 (node_modules/rabin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rabin@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ipfs@0.35.0
added 812 packages from 609 contributors and audited 15325 packages in 48.47s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by alanshaw** [comment]
> the problem is the lockfile in bitcoinjs-lib, which ipld-bitcoin depends on, which js-ipfs depends on

npm doesn't use lockfiles when installing dependencies (only shrinkwrap) - are you using yarn or something?

**Comment by agentofuser** [comment]
Hm, yeah, I'm using yarn. Didn't know of this difference in behavior. Will try with npm.

**Comment by agentofuser** [comment]
@alanshaw yep, worked with npm! Thank you for the tip. I'll pass that instruction along until yarn catches up.
