### ISSUE TITLE
How to use ipfs.get() to download file from IPFS

### ISSUE THREAD

**Issue by LuffySmile** [ipfs/js-ipfs#1945]
ipfs.get() has three parameter : ipfspath , options , callback ,but the api document only introduces two parameter:ipfspath and callback. what is the usage of options parameter? How should I use it?

**Comment by alx696** [comment]
@LuffySmile https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#get

Just two parameter. Maybe document not updated before.

**Comment by Thackermahima** [comment]
Hey, @LuffySmile, were you able to download the file using ipfs. get()?
