### ISSUE TITLE
CLI getIpfs uses wrong args object

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#1947]
- **Version**:
- **Platform**:
- **Subsystem**:

#### Description: 
this line 
https://github.com/ipfs/js-ipfs/blob/master/src/cli/bin.js#L48
passes an argv obj that wasn't created with our yargs config

This makes cmds like `ipfs add --silent ./path/file` to instantiate IPFS with `{ silent :  './path/file' }`

Right now master doesn't fail because `silent` wasn't added to the validation yet, still this behaviour should be fixed.

**Comment by grassias** [comment]
If we changed the line https://github.com/ipfs/js-ipfs/blob/master/src/cli/bin.js#L48
into: `const getIpfs = utils.singleton(cb => utils.getIPFS(cli.argv, cb))`?
That'll do it?

**Comment by alanshaw** [comment]
Sadly no, `argv` is an accessor that causes a handler for the command to be invoked. At the point where `getIpfs` is called we're already in a handler so we need a new yargs which doesn't have the commands handlers. All we're missing is the ability to parse the global options (`--silent` and `--pass`).

I think we just need a new function to create a new yargs with the global options that we can use and assign to `cli` as well as use in `getIpfs`.

**Comment by hugomrdias** [comment]
made some suggestions in the #1955 PR

**Comment by alanshaw** [comment]
Thanks again @grassias ❤️
