### ISSUE TITLE
Using jsipfs pin add

### ISSUE THREAD

**Issue by grantlouisherman** [ipfs/js-ipfs#1953]
- **Version**:
0.35.0-rc.1
- **Platform**:
MacOS Sierra 10.12.6
- **Subsystem**:
Pin( pin add )

#### Description:
I have been trying to pin a block's cid by running `jsipfs pin add QmZjTnYw2TFhn9Nn7tjmPSoTBoY7YRkwPzwSrSbabY24Kp` in the command line and I have also tried doing it in the the code that looks like this 
`ipfs.pin.add(cid, { recursive:true })` 

where the CID is a normal CID like this
```
CID {
codec: 'dag-pb',
version: 0,
multihash:
<Buffer 12 20 a9 48 90 4f 2f 0f 47 9b 8f 81 97 69 4b 30 18 4b 0d 2e d1 c1 cd 2a 1e c0 fb 85 d2 99 a1 92 a4 47> }
```

I have also tried: 
```
await ipfs.pin.add(multihash.toB58String(cid.buffer))
await ipfs.pin.add(cid.toBaseEncodedString())
```

However, every-time I try one of these approaches I get this error: 

> /js-ipfs/node_modules/protons/src/compile/decode.js:193
> throw new Error('Groups are not supported')
> ^Error: Groups are not supported

And Im not sure why this is happening. When you look at the Go code you can see that when pinning a block you simply are passing in the CID: https://github.com/ipfs/go-ipfs/pull/5969/files

#### Steps to reproduce the error:
```
const ipfs = await argv.getIpfs()
const { cid } = await ipfs.block.put(data, argv)
await ipfs.pin.add(cid)
```
or in the command line run:
`jsipfs pin add ` any CID created by a block

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

If you are still having this problem please migrate to Helia.
