### ISSUE TITLE
HTTP Gateway fails to load sharded website

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#1963]
> Part of an effort to run embedded js-ipfs in Brave :lion: https://github.com/ipfs-shipyard/ipfs-companion/issues/716

- **Version**: js-ipfs version: 0.35.0-rc.3
- **Platform**: Linux, Node.js v10.15.0
- **Subsystem**: HTTP Gateway

#### Description:

Tried to open [wikipedia mirror](https://ipfs.io/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/) from js-ipfs's Gateway and got sad. Not sure if a [bug or just not implemented](https://ipfs.io/ipfs/QmVnLkRxWWv2xiPKeQy6re1zCepzX7YXUiq5fESkd1j8bC/bug_or_feature.jpg)?

#### Steps to reproduce the error:

1. Open http://127.0.0.1:9090/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/
2. Get sad

```console
$ curl http://127.0.0.1:9090/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/
{"statusCode":404,"error":"Not Found","message":"no link named \"wiki\" under bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq"}
```

**Comment by alanshaw** [comment]
@achingbrain can you help with this one?

**Comment by achingbrain** [comment]
I think this error comes from [this line](https://github.com/ipfs/js-ipfs-http-response/blob/master/src/resolver.js#L102) in `js-ipfs-http-response` which is called by the gateway.  

It looks like it does a bunch of DAG manipulations assuming it's dealing with a straight `dag-pb` node.  That is I'm not sure this has ever worked with sharded directories.

It should probably use the `unixfs-exporter` instead as that can handle more types of node.

**Comment by achingbrain** [comment]
Actually I've just put a fix together for this, I'll submit a PR.  We should be able to remove `js-ipfs-http-response` as a dep too so hooray for ever so slightly smaller bundle sizes.

**Comment by lidel** [comment]
@achingbrain Thank you for looking into this. 

I think `js-ipfs-http-response` continues to be responsible for generating HTML of directory listings, and it is also a dep of [service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway) as well, so we may need to fix it upstream. 

> That is I'm not sure this has ever worked with sharded directories.

I found [this TODO in libdweb branch of Companion](https://github.com/ipfs-shipyard/ipfs-companion/blob/d6dfc0cfa74a793695f32888c65845ea46f03444/add-on/src/lib/ipfs-protocol-libdweb.js#L155), so it seems it never worked.
