### ISSUE TITLE
Unable to retrieve content outside of my machine

### ISSUE THREAD

**Issue by rmisio** [ipfs/js-ipfs#1978]
- **0.35.0-rc.4**:
- **Darwin Kernel Version 17.3.0**:

#### Description:

I'm able to add a file to IPFS and publish it to IPNS and resolve it locally via IPNS... but I cannot retrieve it via IPFS or IPNS from a public gateway (I've tried multiple and made sure they were online based on https://ipfs.github.io/public-gateway-checker/).

#### Steps to reproduce the error:

```
    const node = window.node = new IPFS({
      EXPERIMENTAL: {
        pubsub: true,
        ipnsPubsub: true,
      }
    });

    console.log(await node.version());

    node.on('ready', async () => {
      const nodeId = await node.id();
      console.log(`my node id is ${nodeId.id}`);

      const gatewayBase = 'https://gateway.ipfs.io';
      const randomToken = Math.random().toString().slice(0, 6);

      const fileAdded = await node.add({
        path: 'happy.times',
        content: Buffer.from(`I am happy. I am good. (${randomToken})`),
      })

      const fileIpfsUrl = `/ipfs/${fileAdded[0].hash}`;
      console.log(`Added file - ${gatewayBase}${fileIpfsUrl}`);
      console.dir(fileAdded);

      console.log(`publishing ${fileIpfsUrl}`);
      const filePublished = await node.name.publish(fileIpfsUrl);

      console.log('File published.');
      console.dir(filePublished);

      const fileIpnsUrl = `/ipns/${nodeId.id}/happy.times`;
      console.log(`resolving via ${fileIpnsUrl}`);
      const nameResolve = await node.name.resolve(fileIpnsUrl);

      console.log('Name resolved. Boom.');
      console.dir(nameResolve);

      console.log(`File published to ipns - ${gatewayBase}${fileIpnsUrl}`);

      const fileCat = await node.cat(nameResolve.path);

      console.log('catted dat file dog. cat.');
      console.log(fileCat.toString());
    });
```

![image](https://user-images.githubusercontent.com/794517/55584739-34cda200-56e2-11e9-99c4-99104b3d5b7d.png)

**Comment by alx696** [comment]
@rmisio Try to set **Swarm**:
```
    const ipfs = new window.Ipfs({
      config: {
        Addresses: {
          Swarm: [
            '/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star',
            '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
          ]
        }
      }
    });
```
My demo run in browser. Can not get anything before set **Swarm**.

**Comment by rmisio** [comment]
@alx696 When I add that to my config, my node 'ready' event never fires and after a few seconds I get this error:

```
transport.js:62 Uncaught Error: websocket error
    at WS.push../node_modules/engine.io-client/lib/transport.js.Transport.onError (transport.js:62)
    at WebSocket.ws.onerror (websocket.js:159)
    at WS.push../node_modules/engine.io-client/lib/transports/websocket.js.WS.doClose (websocket.js:245)
    at WS.push../node_modules/engine.io-client/lib/transport.js.Transport.close (transport.js:92)
    at Socket.push../node_modules/engine.io-client/lib/socket.js.Socket.onClose (socket.js:680)
    at close (socket.js:631)
    at Socket.push../node_modules/engine.io-client/lib/socket.js.Socket.close (socket.js:626)
    at manager.js:265
```

I'm using this as my config:

```
    const node = window.node = new IPFS({
      EXPERIMENTAL: {
        pubsub: true,
        ipnsPubsub: true,
      },
      config: {
        Addresses: {
          Swarm: [
            '/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star',
            '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
          ]
        },
      },
    });
```

I've tried both with and without that `EXPERIMENTAL` key and it's the same behavior.

What's really odd is that before adding the custom swarm above, my node ready fires and outside of my content being available outside of my machine, things seem to work.

Once I add in the swarm, 'ready' doesn't fire and I get the error. Even if I remove the swarm (and entire `config` key), it still errors. I basically need to delete the IPFS related indexed db's and then it works.

@alanshaw Any ideas on what might be happening here. This behavior occurs for me on both `0.36` and `0.35`.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

I would highly recommend checking out https://pl-diagnose.on.fleek.co/, or the older https://check.ipfs.network/, in order to investigate whether your content is accessible.
