### ISSUE TITLE
TypeError: Cannot read property 'Buffer' of undefined

### ISSUE THREAD

**Issue by Despoinis** [ipfs/js-ipfs#1992]
Example:

In the browser, assuming ipfs = new Ipfs(...):

let content = ipfs.types.Buffer.from('ABC');
let results = await ipfs.files.add(content);
let hash = results[0].hash; // "Qm...WW"

It seems that the new version has been changed. Now ipfs.types is undefined, but the documentation is still the old version of the code, how should the new version be written?

version:0.35.0

**Comment by alanshaw** [comment]
Like this: https://github.com/ipfs/js-ipfs/blob/master/README.md#static-types-and-utils

Where is the documentation you’re referencing?

**Comment by Despoinis** [comment]
https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add

**Comment by alanshaw** [comment]
Thanks - I’ll get that fixed

**Comment by Despoinis** [comment]
Example:

In the browser, assuming ipfs = new Ipfs(...):

const content = Ipfs.Buffer.from('ABC')
const results = await ipfs.add(content)
const hash = results[0].hash // "Qm...WW"

Uncaught TypeError: ipfs.Buffer is not a constructor

ipfs.Buffer I have tried it before and it is still undefined?
