### ISSUE TITLE
Uncaught TypeError: ipfs.Buffer is not a constructor

### ISSUE THREAD

**Issue by Despoinis** [ipfs/js-ipfs#1993]
Example:

In the browser, assuming ipfs = new Ipfs(...):

const content = Ipfs.Buffer.from('ABC')
const results = await ipfs.add(content)
const hash = results[0].hash // "Qm...WW"

Uncaught TypeError: ipfs.Buffer is not a constructor

ipfs.Buffer I have tried it before and it is still undefined?

_Originally posted by @Despoinis in https://github.com/ipfs/js-ipfs/issues/1992#issuecomment-483171813_

**Comment by alanshaw** [comment]
This is working for me here: https://jsbin.com/mofade/1/edit?html,console

If it's still not working for you please provide a runnable code example and I'll look into it.

**Comment by Despoinis** [comment]
It is my fault, the case is wrong.
