### ISSUE TITLE
validation problem with libp2p

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#1998]
- **Version**:all
- **Platform**: node
- **Subsystem**:all

#### Description:

these defaults 
https://github.com/ipfs/js-ipfs/blob/5c5d9c4f80dc041ed51bdedce5632a4698cb389b/src/core/runtime/libp2p-nodejs.js#L24-L30 
are **NOT** included in the validation schema here https://github.com/libp2p/js-libp2p/blob/5b0a97e6794b8b343c29035767dd7ad892243bfc/src/config.js#L16

#### Steps to reproduce the error:
run `ipfs daemon`

**Comment by alanshaw** [comment]
cc @jacobheun @vasco-santos

**Comment by hugomrdias** [comment]
ignore this
