### ISSUE TITLE
files stat --with-local=true fails without daemon

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2007]
- **Version**: js-ipfs 0.35.0
- **Platform**: Linux, Node v10.15.0
- **Subsystem**: `files stat`

#### Description:

`jsipfs files stat --with-local=true` produce error when `jsipfs daemon` is not running

#### Steps to reproduce the error:

1. Make sure `jsipfs daemon` is not running
2. Make sure repo is empty (requested CID should not be cached locally)
2. Execute `jsipfs files stat --with-local=true /ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`
3. Get `ENOENT: no such file or directory, open '/home/lidel/.jsipfs/blocks/ZD/AFYBEIGDYRZT5SFP7UDM7HU76UH7Y26NF3EFUYLQABF3OCLGTQY55FBZDI.data'`

**Comment by alanshaw** [comment]
@achingbrain any chance you can take a quick look at this?

**Comment by Prabhakar-Poudel** [comment]
Looks like this issue does not exist in version 0.36.0
Tried in 0.35.0 with above reproduction steps and did see the error.
But the same did not happen when I tried it through dev setup, which is at 0.36.0

@lidel Can you verify?

**Comment by lidel** [comment]
I can confirm, the issue is fixed in 0.36.0! :sparkles: 
Probably due to MFS refactoring pulled in with base32 switch for cidv1 :)
