### ISSUE TITLE
hapi warnings when installing 0.35.0

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#2008]
- **Version**: 0.35.0
- **Platform**: node.js
- **Subsystem**: dependencies

#### Description:

When installing `js-ipfs@^0.35.0` I see the following trace of errors from `hapi` and its submodules.

![image](https://user-images.githubusercontent.com/106148/56745716-dfb50700-6748-11e9-88d6-2c1843e4b8a2.png)

#### Steps to reproduce the error:

Simply running `npm i ipfs` should trigger these warnings

**Comment by alanshaw** [comment]
Thanks for reporting, this should hopefully be easy to fix!

**Comment by alanshaw** [comment]
Fixed for this module in https://github.com/ipfs/js-ipfs/pull/2015 but a couple of dependencies are still using the old version and need to be upgraded. I've opened issues:

* https://github.com/libp2p/js-libp2p-webrtc-star/issues/172
* https://github.com/ipfs/js-ipfsd-ctl/issues/331
