### ISSUE TITLE
Old version of lodash sneaking in via zcash

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#2016]
- **Version**: 0.35.0
- **Platform**: Browser (node.js seems fine)
- **Subsystem**: Dependencies

#### Description:
It seems that when using `js-ipfs` in the browser, it accidentally kicks my `lodash` library back to 3.10.1.

#### Steps to reproduce the error:
1. `git clone https://github.com/ipfs/js-ipfs`
2. `npm install && npm run build`
3. Include `dist/index.min.js` in an html file and open in a browser
4. In the browser's console, check `_.VERSION`

Expected: ~4.17
Actual : **~3.10**

**Comment by alanshaw** [comment]
This is being tracked here https://github.com/ipld/js-ipld-zcash/issues/24 - there's unfortunately not much more we can do about it.

Note as of 0.35 zcash is only included in the pre-built CDN bundle and is not included by default if you `require('ipfs')` in your application.

**Comment by whymarrh** [comment]
Hi, yes. I believe this issue might need to be reopened. This does seem to be `js-ipfs`'s problem even if it isn't `js-ipfs`'s fault.

> Note as of 0.35 zcash is only included in the pre-built CDN bundle and is not included by default if you `require('ipfs')` in your application.

If I'm understanding this correctly, you're saying that using `ipfs` via Nodejs doesn't include zcash? If this is the case, why is the package listed as a production dependency of in the `package.json` file? It seems that `ipld-zcash` is indeed required,<sup>[\[1\]][1][\[2\]][2]</sup> do you mean that the require call isn't _executed_ by default and is only executed at access time?

  [1]:https://github.com/ipfs/js-ipfs/blob/v0.37.0-rc.0/src/core/runtime/ipld-browser-all.js#L23
  [2]:https://github.com/ipfs/js-ipfs/blob/v0.37.0-rc.0/src/core/runtime/ipld-nodejs.js#L34-L36
