### ISSUE TITLE
Docker fails to init

### ISSUE THREAD

**Issue by KeithSSmith** [ipfs/js-ipfs#2018]
- **Version**: latest
- **Platform**: Dockerfile
- **Subsystem**: Node 9.5.0

#### Type:
Bug

#### Severity:
High b/c container fails to start

#### Description:
Attempting to run a Docker instance on my Linux server and when I issue the recommended command the Dockerfile is unable to initialize the IPFS instance and returns `Unexpected token *` this in turn fails to create the config file that is required to start the daemon and reports issues from the `init_and_daemon.sh` bash script.

#### Steps to reproduce the error:

```
$ docker run -it -p 4002:4002 -p 4003:4003 -p 5002:5002 -p 9090:9090 ipfs/js-ipfs:latest
Using /root/.jsipfs as IPFS repository
initializing ipfs node at /root/.jsipfs
Unexpected token *
sed: can't read /root/.jsipfs/config: No such file or directory
```

**Comment by bleonard252** [comment]
I doubt this issue is solely Docker related. When I'm `require()`ing it in NodeJS it crashes with the same error.

**Comment by gil-air-may** [comment]
Experiencing the same `Unexpected token * `

**Comment by alanshaw** [comment]
Node.js 10 is the current minimum compatible version

**Comment by area** [comment]
So why is the latest docker image built on Node 9.5?
