### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#2023]
Since we've started using the [`err-code`](https://www.npmjs.com/package/err-code) module, we can add a string `code` property to JS errors and assert on that in tests, etc.

I notice some people use the form `ERR_OH_NOES` instead of what appears to be the idiomatic (well - node/inherited from Unix) style of `EOHNOES`.

Was there a reason for this or did the first person to use the module just like underscores?

Also, here's a sweet bike shed though am unsure about the colour:

![addition-bike-08](https://user-images.githubusercontent.com/665810/57399462-2c78f300-71c9-11e9-8567-b2e905a63ec8.jpg)

cc @ipfs/repos-javascript

**Comment by alanshaw** [comment]
I don't have strong opinions on the format for naming but we should at least try to be consistent. Node.js uses both, with [`ERR_` prefixed errors reserved for Node.js specific errors](https://github.com/nodejs/node/blob/422e8f762873aef4a37185f3237c0d666c929d8e/lib/internal/errors.js#L619). I believe the majority of codes added so far are `ERR_` prefixed so it would be easier to stick to it at this stage.
