### ISSUE TITLE
config.get() should return a number if a number was set

### ISSUE THREAD

**Issue by dirkmc** [ipfs/js-ipfs#2060]
This [interface-js-ipfs-core test](https://github.com/ipfs/interface-js-ipfs-core/blob/master/src/config/set.js#L62) is currently failing because `config.get()` returns `'11'` as a string instead of `11` as a number

**Comment by Prabhakar-Poudel** [comment]
@alanshaw @dirkmc 
I'll take a look at this.

**Comment by Prabhakar-Poudel** [comment]
@dirkmc 
Does `ipfs-repo` has anything to do with this.
Along [these lines](https://github.com/ipfs/js-ipfs-repo/blob/25cecd7d9b3fcb1d789ad75bb3c309d046344d31/src/config.js#L31-L49)

**Comment by dirkmc** [comment]
It looks like this has actually been fixed now, as the tests are passing on master
