### ISSUE TITLE
ipfs.add fails with TypeError: "can't convert undefined to object"

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2090]
- **Version**: 0.36.0, prebuild browser bundle
- **Platform**: web browser (Chrome & Firefox)
- **Subsystem**: `ipfs.add`

#### Description:

`ipfs.add` with [prebuilt bundle for use in browser](https://unpkg.com/ipfs@0.36.0/dist/index.min.js) produces error:

![2019-05-22--14-46-42](https://user-images.githubusercontent.com/157609/58175727-1b3be600-7ca1-11e9-840f-84589c56318f.png)

#### Steps to reproduce the error:

I prepared two apps to demonstrate the issue:

- `ipfs.add` under 0.35.0 using Buffer: [demo](https://bafkreiel3wwehtmi6zglzu4rrqvov5kaors2sdi2y76y2332ntdrfkqf3i.ipfs.dweb.link/#0.35.0--ok) works ok
  - replace js-ipfs with 0.36.0 and it will fail
- `ipfs.add` under 0.36.0 using File: [demo](https://bafkreibtemdrnw32wryz42beizfksemjcxvkjoky2hasmnnkag6puyy52y.ipfs.dweb.link/#0.36.0-error) fails

**Comment by alanshaw** [comment]
https://github.com/ipld/js-ipld-dag-pb/blob/d02c65918e537380ad2844b2573283def30098b4/src/dag-node/addNamedLink.js#L14 should be `Object.keys(object)` not `Object.keys(this)`.

**Comment by alanshaw** [comment]
@hugomrdias any chance you can look into why this wasn't caught in our browser tests?

**Comment by vmx** [comment]
I've opened https://github.com/ipfs/aegir/issues/362 to track the issue on Browser tests not running against the same code as the dist bundle contains.
