### ISSUE TITLE
Npm error when installing electron example

### ISSUE THREAD

**Issue by BarneyChambers** [ipfs/js-ipfs#2117]
Version:
    Platform: Ubuntu 16.06
    Subsystem: Node 8.1.0

Type: Critical

Severity: High

Description: Running build commands throws permission errors
Steps to reproduce the error:

    Clone repository
    cd run-in-electron
    sudo npm install

result:

```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b feat/smaller git://github.com/hugomrdias/concat-stream.git /home/mooningmarket/.npm/_cacache/tmp/git-clone-1fcceff4
npm ERR! /home/mooningmarket/.npm/_cacache/tmp/git-clone-1fcceff4/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mooningmarket/.npm/_logs/2019-05-25T11_04_11_597Z-debug.log

```

**Comment by Prabhakar-Poudel** [comment]
@BarneyChambers I think it has to do with your npm.
And the fact you have to run npm install using sudo, suggest it is already messed up.

If you still think it is an issue with ipfs, please add more information.

**Comment by Prabhakar-Poudel** [comment]
You may want to look at [this](https://stackoverflow.com/a/16151707/6293468) SO thread.

**Comment by alanshaw** [comment]
> You may want to look at [this](https://stackoverflow.com/a/16151707/6293468) SO thread.

@BarneyChambers please shout if that doesn't help. Also, you should upgrade your Node.js version ;)

**Comment by BarneyChambers** [comment]
Thanks guys, the problem seemed to disappear when I upgraded to node version 8.1.0
