### ISSUE TITLE
IPFS and NAT?

### ISSUE THREAD

**Issue by rayj00** [ipfs/js-ipfs#2119]
Not an issue but a question.   Does IPFS run behind a NAT?  I am using a bridged VM to do some experimenting on and wonder if I can access the IPFS network from behind the NAT?

Thanks,

Ray

**Comment by alanshaw** [comment]
@rayj00 please use the discussion forums for these type of questions next time 😉 https://discuss.ipfs.io/

If you setup your JS IPFS node to use [webrtc-star](https://github.com/ipfs/js-ipfs#how-to-enable-webrtc-support-for-js-ipfs-in-the-browser) or [websocket-star](https://github.com/ipfs/js-ipfs#is-there-a-more-stable-alternative-to-webrtc-star-that-offers-a-similar-functionality) then yes you'll be able to access other nodes via these rendezvous points. In the near future when the DHT is enabled you'll be able to discover relays and nodes connected to relays to enable better access to the network.

js-libp2p will eventually have autonat and autorelay to help with NAT detection and relay discovery.
