### ISSUE TITLE
ERR! for install --global?

### ISSUE THREAD

**Issue by rayj00** [ipfs/js-ipfs#2120]
- **Version**: I believe it is version 0.36.2.  Neither of the command above work.
- **Platform** Ubuntu 16.04.04:
- **Subsystem**:

#### Type: Install failure

[2019-05-25T18_40_02_207Z-debug.log](https://github.com/ipfs/js-ipfs/files/3219628/2019-05-25T18_40_02_207Z-debug.log)

#### Description:
ray@LivepeerIPFS:~$ sudo npm install ipfs --global

npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated content@3.0.7: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
/usr/bin/jsipfs -> /usr/lib/node_modules/ipfs/src/cli/bin.js

> gc-stats@1.3.0 install /usr/lib/node_modules/ipfs/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.3.0 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/ipfs/node_modules/gc-stats/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ipfs/node_modules/gc-stats/build'
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.3.0/Release/node-v64-linux-x64/gcstats.node" "--module_name=gcstats" "--module_path=/usr/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.3.0/Release/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/lib/node_modules/ipfs/node_modules/gc-stats
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.3.0/Release/node-v64-linux-x64/gcstats.node --module_name=gcstats --module_path=/usr/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.3.0/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ipfs/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.4.0-116-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ipfs/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/ipfs/node_modules/gc-stats
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.3.0/Release/node-v64-linux-x64/gcstats.node --module_name=gcstats --module_path=/usr/lib/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.3.0/Release/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> keccak@1.4.0 install /usr/lib/node_modules/ipfs/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild /usr/lib/node_modules/ipfs/node_modules/keccak
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ipfs/node_modules/keccak/build'
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ipfs/node_modules/keccak
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2019-05-25T18_39_58_772Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.7.0 install /usr/lib/node_modules/ipfs/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.7.0 rebuild /usr/lib/node_modules/ipfs/node_modules/secp256k1
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ipfs/node_modules/secp256k1/build'
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ipfs/node_modules/secp256k1
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.7.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2019-05-25T18_39_59_529Z-debug.log
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> tiny-secp256k1-native@1.1.0 install /usr/lib/node_modules/ipfs/node_modules/tiny-secp256k1-native
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ipfs/node_modules/tiny-secp256k1-native/build'
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ipfs/node_modules/tiny-secp256k1-native
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> ursa-optional@0.9.10 install /usr/lib/node_modules/ipfs/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at Object.<anonymous> (/usr/lib/node_modules/ipfs/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.3.0 (node_modules/ipfs/node_modules/gc-stats):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.3.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tiny-secp256k1-native@1.1.0 (node_modules/ipfs/node_modules/tiny-secp256k1-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tiny-secp256k1-native@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2019-05-25T18_40_02_207Z-debug.log
ray@LivepeerIPFS:~$

#### Steps to reproduce the error:

npm install ipfs
nmp install ipfs --global

**Comment by Prabhakar-Poudel** [comment]
@rayj00 Please check your `npm` installation issues.
It is asking for appropriate permission to install the package to the mentioned path.
In most cases doing `sudo npm install ipfs --global` should fix it.
However, I do not recommend doing `sudo` for non-global installs like `npm install ipfs`
Please check for issues with you npm installation.
[This](https://stackoverflow.com/a/16151707/6293468) could be something to try or look for other solutions to npm install permission denied issue.

**Comment by alanshaw** [comment]
Yes, this does look like an issue with permissions on your global install path. You need to give write access to `/usr/lib/node_modules` for your user.
