### ISSUE TITLE
`npm i` on the repo is failing

### ISSUE THREAD

**Issue by satazor** [ipfs/js-ipfs#2125]
- **Version**: N/A
- **Platform**: MacOSX
- **Subsystem**:

#### Description:

Doing `npm i` in the repo gives an error:

```
sh: run-s: command not found
```

@vasco-santos is having the same issue, meaning is something recent. Some transient dependency might be causing the issue.

#### Steps to reproduce the error:

Clone the repo and do `npm i`.

**Comment by alanshaw** [comment]
`npm-run-all` provides that...

**Comment by alanshaw** [comment]
I got round to trying this today and I didn't get the error - can someone confirm this has been resolved?

**Comment by satazor** [comment]
Maybe you have `npm-run-all` installed globally. I didn’t and that was causing the error. After I installed globally it fixed it, but it should work without it.

**Comment by alanshaw** [comment]
I don't have it installed globally - do you have a `package-lock.json` in your repo?

FWIW I've also seen this in CI but when restarting the build I don't see it again.

**Comment by vasco-santos** [comment]
I uninstalled `npm-run-all` now and did a fresh install of `js-ipfs`. Everything looks good again!
