### ISSUE TITLE
Detect node version and show error message if t

### ISSUE THREAD

**Issue by dirkmc** [ipfs/js-ipfs#2126]
Often our users try to run js-ipfs with a node version that is too low. (see for example https://github.com/ipfs/js-ipfs/issues/2122)
Currently they get an error like `Unexpected token *`
We should give them a nice error message instead, asking them to use the required minimum node version.

**Comment by chirag-shinde** [comment]
I'd like to work on this issue if no one else is.

**Comment by alanshaw** [comment]
Yes please @chirag-shinde
