### ISSUE TITLE
[optimization] Use individual methods of async

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#214]
Known culprits:

- [x] this module, fixed in https://github.com/ipfs/js-ipfs/pull/195/commits/255f6d1d5cda4312efd5a7870e4ca834b4b8d466
- [x] https://github.com/ipfs/js-ipfs-block-service/pull/20
- [x] ~~https://github.com/form-data/form-data/pull/204~~
- [ ] https://github.com/ipfs/js-ipfs-bitswap/issues/14

**Comment by diasdavid** [comment]
When I read the title of this issue again my reaction was, "wait, no more async calls?" :D 

async is now modular, not sure if this is an optimization/concern anymore

**Comment by dignifiedquire** [comment]
That is correct, we can now migrate the rest of the modules that use async to use the modular 2.0 version.

**Comment by diasdavid** [comment]
Awesome :) Closing this one, as that is just a 'dep update', it will happen with following releases, naturally.

**Comment by dignifiedquire** [comment]
Sorry, but it's more than that, we have to specifically change our code to use the form of 

```js
const each = require('async/each')
```

to actually get the benefits of this.

**Comment by diasdavid** [comment]
Ok. Can you list out all the cases where async happens (+ run-*) so that we make sure to tackle all of them? Thank you

**Comment by dignifiedquire** [comment]
I'm pretty sure that's nearly every single repo of `libp2p/js-*` and `ipfs/js-*`

**Comment by nginnever** [comment]
async crawl >.<

actually not that many modules depend on async anymore

  - [x] js-ipfs-api [PR](https://github.com/ipfs/js-ipfs-api/pull/350)
  - [ ] js-ipfs-repo (dev only) [PR]()
  - [ ] js-libp2p-kad-routing [PR]()  
  - [ ] js-ipfs-unixfs-engine (dev only) [PR]()

I have set up an example pr, if it looks good i'll iterate over the rest.

Do we care to update this if async is only a dev dep? adding them to the list for now.

**Comment by dignifiedquire** [comment]
I think we should do it for dev as well, as that means the bundles in the test runs are smaller, making it a bit faster :)

**Comment by diasdavid** [comment]
Seems that this has been taken care of with exception of bitswap which has its own issue https://github.com/ipfs/js-ipfs-bitswap/issues/14. Closing this one, reopen if needed
