### ISSUE TITLE
CID disparity between versions

### ISSUE THREAD

**Issue by shamb0t** [ipfs/js-ipfs#2141]
Hi :wave: while upgrading the IPFS version used in OrbitDB, it seems versions `0.34.4` and `0.36.3`  give different cids for the same object when a `next` hash is included. Is this intended?
Steps to reproduce:
```
let obj = { 1: 'hello, world',
               next: [ { '/': 'zdpuAo8EZockio2kzpA78VM8i2EJHVsQdHcs4wPdjGFV4KtFs' }]}

ipfs.dag.put(obj).then(cid => console.log(cid.toBaseEncodedString('base58btc')))
```
`0.34.4` returns the hash  `zdpuAusGgRCQQciEUbjoubz4LwWLKKh14VWnJCiSzC8q6D4jb` while `0.36.3` returns `zdpuAs1fySVVWLUtK1Wc4gQyN6n11uTznpzUbnwHGqrcdpT4H` Am I missing something about how `next` works?

**Comment by Amorn-Kingthong** [comment]
thank you

**Comment by alanshaw** [comment]
@vmx does the `dag-cbor` format still accept `{ "/" : "CID" }` links or do they now have to be `CID` instances?

**Comment by vmx** [comment]
Only CID instances, so `/` isn't a special key anymore.

**Comment by shamb0t** [comment]
Ah, got it. Thanks guys!

**Comment by mikeal** [comment]
> Only CID instances, so / isn't a special key anymore.

Yes and no :) `/` is a still special, it can’t be looked up via paths/selectors and is used internally in the `dag-json` codec for binary and CID encoding.

So, we don’t rely on it anymore in cases like this one, but people still can’t use it as a regular property in things they want to encode into `dag-json`, `dag-cbor` or any other codec that supports the data model.
