### ISSUE TITLE
Feature: progress in get/cat

### ISSUE THREAD

**Issue by sinnlosername** [ipfs/js-ipfs#2144]
There are progress callbacks for all add methods, however there is none for the get methods. It would be great if you could add this functionality. It could look something like this:

 ```
ipfs.get(cid, {
    progress: function(bytes) {
        console.log("Loaded " + bytes + " bytes");
    }
})
```

Combined with the size got trough a ls call this progress callback could be used to calculate the download speed, the remaining time, etc.

**Comment by alanshaw** [comment]
If you use the streaming APIs for `cat` and/or `get` you can just count the bytes in the chunks you receive.

e.g.

```js
const pull = require('pull-stream')
const IPFS = require('ipfs')
const ipfs = new IPFS()

let totalBytes = 0

ipfs.on('ready', () => {
  pull(
    ipfs.catPullStream('QmXEmhrMpbVvTh61FNAxP9nU7ygVtyvZA8HZDUaqQCAb66'),
    pull.through(data => {
      totalBytes += bytes
      console.log("Loaded " + totalBytes + " bytes")
    }),
    pull.collect((err, bufs) => console.log("Done"))
  )
})
```

**Comment by sacredwx** [comment]
> If you use the streaming APIs for `cat` and/or `get` you can just count the bytes in the chunks you receive.
> 
> e.g.
> 
> ```js
> const pull = require('pull-stream')
> const IPFS = require('ipfs')
> const ipfs = new IPFS()
> 
> let totalBytes = 0
> 
> ipfs.on('ready', () => {
>   pull(
>     ipfs.catPullStream('QmXEmhrMpbVvTh61FNAxP9nU7ygVtyvZA8HZDUaqQCAb66'),
>     pull.through(data => {
>       totalBytes += data.length
>       console.log("Loaded " + totalBytes + " bytes")
>     }),
>     pull.collect((err, bufs) => console.log("Done"))
>   )
> })
> ```
> 
> https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#catpullstream

Hey, but how to know the total bytes before the stream ends in order to show up the progress e.g. ?
