### ISSUE TITLE
Allow and deny lists for CIDs

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#2152]
Allow users to configure

- An "allow list" - a list of CIDs they are willing to host or particpate in the discovery of.
- A "deny list" - a list of CIDs they do not want to host or participate in the discovery of.

Meta issue describing the functionality: https://github.com/ipfs/notes/issues/284
Open issue for the same functionality for go-ipfs https://github.com/ipfs/go-ipfs/issues/1070 and a notes issue explaining the scope

**Comment by alanshaw** [comment]
Notes and slides from Deep Dive at IPFS Camp 2019: https://github.com/ipfs/camp/blob/master/DEEP_DIVES/25-do-not-replicate-lists-dnr.md

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

This isn't planned, but you could implement your own blockstore adapter that enforces these lists.
