### ISSUE TITLE
undefined ls-remote -h -t ssh://git@github.com/hugomrdias/concat-stream.git

### ISSUE THREAD

**Issue by anarkrypto** [ipfs/js-ipfs#2154]
I am trying to install:
npm install --save ipfs-http-client

But I get this error:
undefined ls-remote -h -t ssh://git@github.com/hugomrdias/concat-stream.git

My OS: Windows 10 
node v12.3.1
npm  v6.9.0

[2019-06-04T09_07_55_363Z-debug.log](https://github.com/ipfs/js-ipfs/files/3251531/2019-06-04T09_07_55_363Z-debug.log)

**Comment by dirkmc** [comment]
It sounds like maybe you need to install git? In any case if you still have problems, please open an issue against the [ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client) repo
