### ISSUE TITLE
Config validation error: init.log option

### ISSUE THREAD

**Issue by mistakia** [ipfs/js-ipfs#2170]
- **Version**: 
0.36.3
- **Platform**:
Darwin macbook 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
- **Subsystem**:
n/a

#### Type:
Question

#### Severity:
Low

#### Description:
The config validator does not allow an option to be passed in to `options.init.log`. I've been using this undocumented option to get status information when initializing a new repo (especially on mobile where it takes a minute to generate a key). Is this option being dropped? Glad to help out if needed.

https://github.com/ipfs/js-ipfs/blob/master/src/core/components/init.js#L61

#### Steps to reproduce the error:
Start ipfs with a config that passes a value in for `options.init.log`
```
const node = new IPFS({ init: { log: () => {} }})
```

**Comment by alanshaw** [comment]
I don't know why it exists and like you say it's undocumented and you shouldn't use it really. This info needs to be logged in a global logger and be available via `ipfs log` - I wouldn't rely on this function still being available in the future but I think you _could_ work around this temporarily like:

```js
const node = new IPFS({ init: false, start: false })
await node.init({ log: console.log })
await node.start()
```
