### ISSUE TITLE
add ipfs.bitswap.ledger method

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#2172]
I was just trying to answer this SO question https://stackoverflow.com/questions/48641072/programmatically-check-data-transfer-on-ipfs/56530957#56530957

and discovered that js-ipfs has the [plumbing in place](https://github.com/ipfs/js-ipfs-bitswap/blob/f83951c928c8c6165c0737fc6bd00f4d06887fe0/test/decision-engine/ledger.spec.js) in `js-ipfs-bitswap` to track a ledger of blocks to and from each peer, but no method for it is exposed in js-ipfs

from the go-ipfs cli

```console
⨎ ipfs bitswap ledger -h
USAGE
  ipfs bitswap ledger <peer> - Show the current ledger for a peer.

  ipfs bitswap ledger [--] <peer>

  The Bitswap decision engine tracks the number of bytes exchanged between IPFS
  nodes, and stores this information as a collection of ledgers. This command
  prints the ledger associated with a given **peer.**

⨎ ipfs bitswap ledger QmeMKDA6HbDD8Bwb4WoAQ7s9oKZTBpy55YFKG1RSHnBz6a
Ledger for QmeMKDA6HbDD8Bwb4WoAQ7s9oKZTBpy55YFKG1RSHnBz6a
Debt ratio:	0.000000
Exchanges:	0
Bytes sent:	0
Bytes received:	0
```

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Closing as not planned.  This would be implemented in `ipfs-bitswap` - please open an issue there if this is still important!
