### ISSUE TITLE
Blocks used internally by pinner are provided to network by bitswap

### ISSUE THREAD

**Issue by dirkmc** [ipfs/js-ipfs#2179]
### Problem

The pinner uses the BlockStore to store the sets of direct and recursive pins.
At the moment any block `put` to the BlockStore is sent to Bitswap, so these internal blocks are being unnecessarily provided to the network.

In the code we
- [create an IPLD instance](https://github.com/ipfs/js-ipfs/blob/master/src/core/index.js#L76) with a BlockService.
- on start, [set the BlockService's exchange](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js#L63) to be Bitswap.
- in the dag component use the IPLD instance to [store DAG nodes](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/dag.js#L56).
- in the pinner use [the dag component](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/pin.js#L38) to [store objects](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/pin.js#L146)

### Solution

I suggest we
- create an `offline` IPLD instance, which only talks to the local BlockService (not to Bitswap)
- create an `offline` dag component, which uses the `offline` IPLD instance
- in the pinner use the `offline` dag component

**Comment by dirkmc** [comment]
@vasco-santos @alanshaw please let me know your thoughts about this approach

**Comment by vasco-santos** [comment]
Hey @dirkmc 

I have been thinking after our conversation today, and despite not liking the solution of having 2 instances of `ipld`, I am not seeing a nice design for this, as ipld should be agnostic from the network perspective, and an option for not providing is odd. In this way, I would go with that proposal for now

**Comment by dirkmc** [comment]
Thanks @vasco-santos 

The go implementation [creates the second instance](https://github.com/ipfs/go-ipfs/blob/1a32379c998f706c1bc7751fc8326f4f4a63f778/core/node/core.go#L42) of `ipld` in a context where it can only be used by the pinner, so maybe it would make sense for us to do the same thing.

**Comment by dirkmc** [comment]
Just making a note here that @alanshaw suggested we should make sure there aren't any issues with locking or memory usage. In particular check that when IPLD lazy loads formats, it doesn't unnecessarily load formats twice.

**Comment by dirkmc** [comment]
Fixed by https://github.com/ipfs/js-ipfs/pull/2196

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
