### ISSUE TITLE
navigator.useAgent.match(...) is null

### ISSUE THREAD

**Issue by freddi301** [ipfs/js-ipfs#2180]
- **Version**: 0.36.3
- **Platform**: Browser Mobile
- **Subsystem**:

#### Description:

ipfsnode goes offline
at: node_modules/webrtcsupport/index-browser.js line 8

#### Steps to reproduce the

firefox developer edition 68 toggling responsive mode and using Galaxy S5

**Comment by alanshaw** [comment]
https://github.com/HenrikJoreteg/webrtcsupport/issues/35 is the right place for this issue. Would you be willing to send a PR to `webrtcsupport` to fix this @freddi301?
