### ISSUE TITLE
IPFS-go is unable to get a message through to IPFS-js

### ISSUE THREAD

**Issue by rmisio** [ipfs/js-ipfs#2181]
Version:

{
  "version": "0.36.3",
  "repo": 7,
  "commit": ""
}

Platform: Chrome v74
Subsystem: libp2p

I'm working on an IPFS-JS browser based app and it needs to be able to communicate with our existing desktop based IPFS-go app. Both the JS and GO app are configured to use a relay. I believe the relay is working in certain scenarios because:

- We can send direct messages from one JS app to another even when they are in different geographic locations.
- The GO app on a desktop can successfully send messages to our GO app running on an Android.

I don't think either of those two things would be possible if the message wasn't going through the relay.

What we've been unable to get working is having a message from GO make it to JS. The only way it's worked is if JS sends GO a message first. After that GO can send messages to JS. But if we want GO to initiate the connection, it's yet to work for us.

FWIW, while JS can send a message to GO, I have no idea if it's going through the relay or not. It may be possible the GO instance we tested it on allows the direct connection.

Our relay is an IPFS-Go instance available at `/dns4/bootstrap1.openbazaar.org/tcp/443/wss/ipfs/QmWUdwXW3bTXS19MtMjmfpnRYgssmbJCwnq8Lf9vjZwDii`. My colleague that set it up has assured me it follows these instructions:

https://github.com/ipfs/js-ipfs/tree/master/examples/circuit-relaying#setting-up-a-go-ipfs-node

Please let me know what else I can provide to debug this. It's very possible this may be a config / usage issue on our end, but if it is, I think we need a little direction on where we've gone wrong.

**Comment by alanshaw** [comment]
@rmisio just to be clear, when you say "message" we talking about communicating through a stream established via libp2p [`dialProtocol`](https://github.com/libp2p/js-libp2p#libp2pdialprotocolpeer-protocol-callback) and not a pubsub message?

Are you able to share a working example with both the go and js code you're using?

**Comment by rmisio** [comment]
@alanshaw 

> just to be clear, when you say "message" we talking about communicating through a stream established via libp2p dialProtocol and not a pubsub message?

Yes, correct.

> Are you able to share a working example with both the go and js code you're using?

Sorry on the delay on this, but I need support from our GO team for the GO part and they've been slammed with Haven and now ETH integration work. When they could get some cycles I'll look to put together a simplified working example.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
