### ISSUE TITLE
examples README link to Terminal tutorial gives a 404

### ISSUE THREAD

**Issue by MarneeDear** [ipfs/js-ipfs#2190]
The README in the examples directory has a Not Found link to the Terminal tutorial.

https://github.com/ipfs/js-ipfs/tree/master/examples
`Tutorial: Interact with IPFS directly from your Terminal`

This gives a 404
https://github.com/ipfs/js-ipfs/blob/master/examples/ipfs-cli-fun

May be related to #1680

**Comment by alanshaw** [comment]
I've removed this link (the tutorial never existed). If you're interested in creating a basic tutorial like this  then that would be awesome!
