### ISSUE TITLE
Invisible coverage

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2202]
We have test coverage we can't track.

Coverage for tests that run against a JS IPFS daemon (i.e. not an in-process node) is not tracked because the code for the daemon is not instrumented.

It means that when removing duplicate tests that exist both here and in `interface-ipfs-core` test coverage appears to lower even though this is not the case.

**Comment by mikeal** [comment]
`node-tap` has a ton of code in it that instruments subprocesses so that even these kinds of things get test coverage. Maybe there is some code we can steal there.

**Comment by achingbrain** [comment]
Closing as this issue is very stale.  Helia tests in-process so this isn't a problem going forward.
