### ISSUE TITLE
Config file docs

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/js-ipfs#2204]
- **Version**: N/A
- **Platform**: N/A
- **Subsystem**: Documentation

#### Description:

Same way as `go-ipfs` does [ipfs/go-ipfs/master/docs/config.md](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md), `js-ipfs` should have a documentation section for the config file, or at least point to a place where it is documented. There is some information on [ipfs/js-ipfs#optionsconfig](https://github.com/ipfs/js-ipfs#optionsconfig), but we do not document which type of values each configuration property can have, as well as what is the purpose of each one.

**Comment by alanshaw** [comment]
Any chance you'd like to take a stab at this @vasco-santos? 😉 😘

**Comment by vasco-santos** [comment]
I may be able to have that time for you next week!
