### ISSUE TITLE
IPFS dependencies giving warnings

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs#2225]
- **Version**: 0.36.4
- **Platform**: Multiple
- **Subsystem**: Dependencies

#### Description:
During installation or `yarn upgrade` IPFS is generating warnings about deprecated versions. 
Specifically ... 
```
ipfs > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
```
Everything seems to work though when people are installing library, then real problems are getting masked by the warnings. 

#### Steps to reproduce the error:
`yarn upgrade` in any application that has a dependency on IPFS.

**Comment by alanshaw** [comment]
@achingbrain @vasco-santos the offending modules are `ipfs-mfs` and `ipfs-multipart` - would you mind updating deps so we don't get these warnings?

**Comment by vasco-santos** [comment]
`ipfs-multipart` is using a commit from the deprecated `ipfs-api`. Anyone knows why that is happening?

**Comment by alanshaw** [comment]
3 years ago, could probably do with somee updates https://github.com/ipfs/js-ipfs-multipart/commit/0d71ecc00bae3730937bdbd83c7d77a65f81a053

Apologies @vasco-santos I meant to tag @hugomrdias not you!
