### ISSUE TITLE
Document the state of IPFS in the browser

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2231]
People are trying to use JS IPFS in the browser and are not always able to get it working the way they want.

* https://github.com/ipfs/js-ipfs/issues/2219
* https://github.com/ipfs/js-ipfs/issues/2171

A lot of the time it's because people don't understand the limitations of P2P networking in the browser or the limitations of the current JS implementation or sometimes it's just that they need to configure their node to use webrtc or websocket-star or something.

Having a resource to be able to point people at would be greatly beneficial to them and would save us having to write the same things down on every issue.

Perhaps this is a blog post?

**Comment by tapaswenipathak** [comment]
Hi @alanshaw: Can I work on the ticket?

**Comment by tapaswenipathak** [comment]
Hi @alanshaw: Can I work on the ticket?

**Comment by alanshaw** [comment]
@tapaswenipathak you're welcome to have a go at this! I think the document should live in https://github.com/ipfs/js-ipfs/tree/master/doc
