### ISSUE TITLE
Error: Not able to stop from state: stopping

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2257]
- **Version**: v0.36.4
- **Platform**: JS
- **Subsystem**: state machine

#### Steps to reproduce the error:

calling `.stop()` on a node that is already `stopping` produces `Error: Not able to stop from state: stopping`

https://github.com/ipfs/js-ipfs/blob/88f4e264ee14986c2b2eb16263f747631ef58958/src/core/components/stop.js#L16-L17

#### Proposed change

`.stop()` should be idempotent, all subsequent calls should detect `stopping` and return promise that resolves when `stop` event is emited by the very first `.stop()`

Y/n?

cc https://github.com/ipfs/js-ipfs/issues/1061, https://github.com/ipfs/js-ipfs/issues/890, https://github.com/ipfs-shipyard/ipfs-companion/issues/716

**Comment by dirkmc** [comment]
I agree, we throw errors when stop is called twice in some places in libp2p as well. It makes it complicated when you have multiple ways to stop things, for example:
"shut this thing down if the connection closes or if the user clicks stop or if there is a timeout"

**Comment by tapaswenipathak** [comment]
Hi @lidel, @dirkmc: Is the ticket open? Can I work on the ticket?

**Comment by lidel** [comment]
@tapaswenipathak sorry for late reply: yes, you can give it a try
