### ISSUE TITLE
Garbage Collection - create streaming API

### ISSUE THREAD

**Issue by dirkmc** [ipfs/js-ipfs#2266]
The [PR for Garbage Collection](https://github.com/ipfs/js-ipfs/pull/2022) currently does not have a streaming API, because the version of js-ipfs-repo it depends on does not have a streaming block service API.

Once js-ipfs is updated to use the latest version of js-ipfs-repo (with async/await functionality) we should create a streaming API for Garbage Collection.

https://github.com/ipfs/js-ipfs/pull/2022#discussion_r302491911

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Helia does not have a streaming GC API, but it does have onProgress events with every block deleted which is very similar.
