### ISSUE TITLE
Merge js-ipfs-{core pieces} into js-ipfs repo

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#2282]
Following https://github.com/ipfs/js-ipfs/issues/2222, the proposal is to:

Merge into js-ipfs, the following modules:
- js-ipfs-mfs
- js-ipfs-repo
- js-ipfs-block-service
- js-ipfs-unixfs-exporter
- js-ipfs-unixfs-importer

**Comment by hugomrdias** [comment]
@achingbrain do we have another issue to track this ?

**Comment by achingbrain** [comment]
I'm not sure that we want to merge any more modules into the main repo at this time.  

* `ipfs-mfs` is in already
* I don't think `ipfs-repo` is really high-churn enough, though we might fold that and the migration tool into one
* The block service should just go away as it's only purpose is to delegate to either repo.blockstore or bitswap, which delegates to repo.blockstore so let's just configure components with one or the other during init/start (post or as part of #2762)
* The importer/exporter are similarly low churn, kind of happy with them where they are right now

We can, of course revisit these should the above things change.

**Comment by hugomrdias** [comment]
cool lets close this then.
