### ISSUE TITLE
fresh installs of js-ipfs fail to build with browserify. peer-id suspect

### ISSUE THREAD

**Issue by npfoss** [ipfs/js-ipfs#2283]
- **Version**: 0.36.4 and 0.37.0-rc.0 (didn't test others)
- **Platform**: Linux npfoss-yoga-1810 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: [peer-id](https://github.com/libp2p/js-peer-id) suspected

#### Description:
I reported this [here](https://github.com/libp2p/js-peer-id/issues/96) but since it's breaking all of js-ipfs I thought it would be good to draw more attention in the main repo.

Browserify-ing any recent version of js-ipfs fails with:
```
Error: Cannot find module 'babelify' from '/path/to/code/node_modules/peer-id/node_modules/async'
```
I looked into this some and I think the problem is that [`peer-id`](https://www.npmjs.com/package/peer-id) had a semver lapse, because lots of js-ipfs things depend on `~0.12.x` and with `0.12.2` everything is fine, but 10 days ago `0.12.3`, `0.13.0`, `0.13.1`, and `0.13.2` were published in quick succession. Now when installing fresh, `package-lock.json` shows some instances of `0.12.3`. The very close pattern of releases makes me think they realized it wasn't working and pushed some fixes, but forgot to remove the broken versions, especially `0.12.3`.

#### Steps to reproduce the error:
package.json
```json
{
  "scripts": {
    "build": "browserify index.js -o app.js -d"
  },
  "dependencies": {
    "browserify": "^16.3.0",
    "ipfs": "^0.36.4"
  }
}
```
index.js
```js
require('ipfs');
```
run
```bash
npm install
npm run build
```
Also available to be cloned here: https://github.com/npfoss/js-ipfs-bug-code

**Comment by alanshaw** [comment]
Cross posting here for reference:

> This looks like it might be an issue with v3 of async https://github.com/caolan/async/issues/1653#issuecomment-509751609

https://github.com/libp2p/js-peer-id/issues/96#issuecomment-513695049

`async` added a browserify transform (`babelify`) to their `package.json` but do not depend on it themselves. If your project also does not depend on `babelify` you'll get this error because browserify will attempt to use the transform but it is not installed.

You can work around it by adding `ignoreTransform: ['babelify']` for the time being.

**Comment by npfoss** [comment]
That fixed it, thank you so much!

I pushed the fix to that github repo for anyone who's interested

**Comment by alanshaw** [comment]
A new version of peer-id (0.12.4) has been released reverting to `async@2` in order to address this issue.
