### ISSUE TITLE
Peer Friends

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2288]
Can we come up with a solution and track progress on peer "friends" in IPFS?

## What is that?

The idea is that friendly peers maintain a persistent connection with each other that is immune from connection manager GC.

## Why is it useful?

1. Preload nodes used by JS IPFS will preload content but are not useful to the JS IPFS node if it is not connected to them
1. The IPFS gateway could really use a persistent connection to the cluster nodes (currently a cron job calling `swarm.connect`)
1. Probably lots of applications using IPFS would like to stay connected to a minimum set of nodes

## What would need to happen?

Proposal (open to suggestions/changes):

- [ ] Ability to dial a node and flag that the connection is "high priority"
    - Should be established ASAP
    - Always re-establish if dropped
    - Be immune from connection manager GC
- [ ] Config option to specify multiple friendly peers
    - `Addresses.Friends`
- [ ] Startup task to dial all the friendly peers

---

@lidel @Stebalien @daviddias @jacobheun @raulk @olizilla

**Comment by lidel** [comment]
Relevant prior art form go-ipfs: [v0.4.20](https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md#0420-2019-04-16) shipped a concept of "important" connections: 
  > The `ipfs swarm connect` command has a few new features:
  > 
  > It now marks the newly created connection as "important". This should ensure that the connection manager won't come along later and close the connection if it doesn't think it's being used.

**Comment by jacobheun** [comment]
I created an issue in js-libp2p that discusses peer tagging to achieve this, https://github.com/libp2p/js-libp2p/issues/369. We could take the list from `Addresses.Friends` and tag them as "important" so we can get the auto connect and connection "permanence" logic in place.

Another approach I started thinking about was adding support for [definable topologies](https://github.com/libp2p/notes/issues/13). While more generic, I think they could serve this use case as well.

**Comment by daviddias** [comment]
I suggest calling this config value something more informative than Friends. Nothing occurs now though 😅

The Conn Manager should be the piece of code that handles this.

Note, today you can achieve 90% of this today by adding these peers to the Bootstrap list, as it will try to reconnect if the connection got dropped every 10s https://github.com/libp2p/js-libp2p-bootstrap/blob/master/src/index.js#L40 (the other 10% is because the connections do get dropped, which means you need to pay the cost of dialing again)

**Comment by jimpick** [comment]
"Bungee Cord Peers" ?

**Comment by jbenet** [comment]
Related: https://github.com/ipfs/go-ipfs/issues/6097#issuecomment-506964185

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

This can be accomplished by tagging friend peers with the `KEEP_ALIVE` tag imported from `@libp2p/interface-peer-store/tags`.
