### ISSUE TITLE
/dnsaddr support in bootstrap and swarm connect

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2289]
## Motivation 

`/dnsaddr` is like DNSLink, but for multiaddrs.
It is a way of having static peer multiaddrs that do not hardcode PeerID and can point at multiple multiaddrs:

- `/dnsaddr/bootstrap.libp2p.io` resolves to:
  - `/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd`
  - `/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd`

It is already supported by go-ipfs (https://github.com/ipfs/go-ipfs/issues/5522) and feels like "magic" mentioned in https://github.com/ipfs/js-ipfs/issues/1459
In js-ipfs, it could be used in default multiaddrs for things like dns-based bootstrap nodes or preload / delegate nodes, enabling us to scale transparently by adding more multiaddrs without the need for shipping patch release or changing client configs.

## Problem

- `/dnsaddr` multiaddrs are not supported in `swarm connect`
- bootstrap ignores `/dnsaddr` entries 

### Steps to reproduce:

`bootstrap.libp2p.io` has dnsaddr records with port and peerid:

```console
$ dig +short _dnsaddr.bootstrap.libp2p.io txt
"dnsaddr=/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
"dnsaddr=/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
```

Try connecting to peer via dnsaddr:

```console
$ jsipfs swarm connect /dnsaddr/bootstrap.libp2p.io
peer multiaddr instance or string must include peerId
```

Expected:

```console
$ ipfs swarm connect /dnsaddr/bootstrap.libp2p.io
connect QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd success
```

In case dnsaddr disappears from `bootstrap.libp2p.io`, alternative hostname for testing: `ipfs.aergia.eu`

**Comment by GavinDmello** [comment]
@alanshaw Can I work on this ?

**Comment by lidel** [comment]
@GavinDmello would be awesome, give it a try!

I wonder if we could add generic support for "resolving" multiaddrs in [js-multiaddr](https://github.com/multiformats/js-multiaddr)  and `/dnsaddr` would just be an example of that. Check discussion at https://github.com/multiformats/js-multiaddr/issues/94

**Comment by GavinDmello** [comment]
@lidel Thank you for the direction.

I was planning on adding handling directly in this repository and reusing the the dns objects in the core components.

I'll try asking on https://github.com/multiformats/js-multiaddr/issues/94 if anyone has started working on adding support.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
