### ISSUE TITLE
chatty log from network subsystems makes application-level debugging frustrating

### ISSUE THREAD

**Issue by autonome** [ipfs/js-ipfs#2299]
- **Version**: 0.36.4
- **Platform**: Firefox Nightly, Mac OS X
- **Subsystem**: libp2p-mplex, bitswap, mss

#### Type: Developer Experience

This behavio(u)r makes building web applications with IPFS a bit frustrating anytime you need to look at the console.

#### Description:

Chatty log floods the console even though I haven't done anything yet, making debugging difficult.

Should network status messages be off by default? Eg, stuff that isn't a result of developer calling APIs?

#### Steps to reproduce the error:

```html
<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>
<script>
const node = new Ipfs();
</script>
```

**Comment by autonome** [comment]
This might have been because I'd turned off my local node for a bit. I turned it back on and noticed that all the logspam went away.

There was nothing that a non-core-dev in the log would be able to understand as that being the problem.

Maybe we need a higher-level message about it?

**Comment by autonome** [comment]
Hm, nope, still seeing it. It just needed a breather or something.

<img width="704" alt="Screen Shot 2019-07-24 at 9 57 00 PM" src="https://user-images.githubusercontent.com/50103/61847024-0a088480-ae5e-11e9-9921-4e94def02924.png">

**Comment by alanshaw** [comment]
At some point you or an application has set `localStorage.debug = '*'` (or some other non-null value).

Open your console and type `localStorage.debug = null` and then refresh and the "chatty" output will stop 😄

NOTE: debug output is not on by default

Also, that `localStorage` is shared by **all** IPFS sites on the gateway ATM since they're all just in a directory on the same domain (best to use `cid.dweb.link`). So this might not have been your or the application you're working on that set this value - it could have been any site you've visited on this gateway.

**Comment by autonome** [comment]
> Also, that `localStorage` is shared by **all** IPFS sites on the gateway ATM since they're all just in a directory on the same domain (best to use `cid.dweb.link`). So this might not have been your or the application you're working on that set this value - it could have been any site you've visited on this gateway.

In this case, I loaded js-ipfs from unpkg in an html page running on a localhost webserver, and instantiated a node in the page with no configuration options (so all defaults).

So if I understand correctly, that means at some point previous I'd loaded something in this browser profile (where `localStorage` data is stored) from `localhost` origin that had an IPFS node which flipped localStorage.debug = '*'?

**Comment by alanshaw** [comment]
Yes, but the page you loaded did not have to have an IPFS node, it could be _any_ application that set `localStorage.debug` to _any_ value other than `null`.
