### ISSUE TITLE
is it js-ipfs or ipfs.js ?

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#2321]
I think we tend to refer to this project as JS IPFS, but the logo on this README and as shows up in twitter embed cards calls it IPFS.JS

<img width="589" alt="Screenshot 2019-08-02 at 10 49 26" src="https://user-images.githubusercontent.com/58871/62361571-37ff6000-b513-11e9-87b9-fac3d4f0cc47.png">

Right now js.ipfs.io has a log that reads "js ipfs" https://js.ipfs.io/

<img width="583" alt="Screenshot 2019-08-02 at 10 48 34" src="https://user-images.githubusercontent.com/58871/62361521-1d2ceb80-b513-11e9-82be-fd3e152a921e.png">

Let's pick one, and stick to it.

**Comment by autonome** [comment]
From the sticker change in #2322, the conclusion appears to be "JS IPFS"? 

Per the title of this issue... is js-ipfs then considered an alias?

I really like how it flows in a sentence.
