### ISSUE TITLE
Read only access by Http Api

### ISSUE THREAD

**Issue by Jonybang** [ipfs/js-ipfs#2332]
- **Version**: 0.37.0

#### Description:
It is possible to provide read only access by Http Api that located in `/src/http`? Looks like ipld fetching requires `/api/v0/refs` endpoint for fast fetching. It calls that endpoint from preload addresses each time when i'm trying to fetch ipld. I want to provide my Http Api to preload addresses but without write access. It is possible?

**Comment by autonome** [comment]
Access control by IP is typically handled at layers above/outside IPFS, there are lots of ways you can do it. Some conversations in ipfs/notes#376. Closing, but reopen if we misunderstood.
