### ISSUE TITLE
Enable preload on MFS commands that accept IPFS paths

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2335]
Some MFS commands accept IPFS paths as input. When IPFS paths are passed, we should send a preload request so that the content can be retrieved.

Notably, the CID resolver in `ipfs-http-response` switched to using `ipfs.files.stat` instead of `ipfs.object.stat` (https://github.com/ipfs/js-ipfs-http-response/pull/19). This means that a JS IPFS gateway currently does not send preload requests and so is useful only for fetching content the node or the preload nodes already have in their repo.

cc @lidel @achingbrain @vasco-santos

**Comment by lidel** [comment]
I am +1 for this: was experimenting and thinking about adding an explicit preload call for paths requested via [embedded gateway in Brave](https://github.com/ipfs-shipyard/ipfs-companion/issues/716), but  doing it at `ipfs.files.stat` is even better.
