### ISSUE TITLE
Factor out dag component so it can be used without js-ipfs

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#2341]
I would like to propose factoring out [dag component](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/dag.js) into separate module (or maybe it should be part of https://github.com/ipld/js-ipld itself ?) as it makes working with IPLD across formats a lot easier than just `js-ipld` library, while at the same time coupling with rest of IPFS is not ideal.

# Context

I have being working towards making https://github.com/Gozala/ipdf/ transport & storage agnostic so it could be used also in dat & ssb, I do however wish to use IPLD & end up more or less recreating `dag` API to do that.

Also cc @mikeal @vmx as they might have thing or two to say about this

**Comment by vmx** [comment]
So you want the IPFS DAG API, but you don't need the rest of IPFS, like the storage, transport (Bitswap) etc?

If yes, what's missing in js-ipld what is part of the DAG API? Ideally the IPFS DAG API should really mostly forward things to js-ipld, where the actual things are happening.

**Comment by Gozala** [comment]
Mostly compatibility with the API so one could either pass ipfs node or `{dag:new Dag(...) }`, but also I think get behaves different form regular IPLD

**Comment by Gozala** [comment]
To be clear, if we make ipfs.dag just be instance of IPLD that might be even better outcome

**Comment by daviddias** [comment]
> To be clear, if we make ipfs.dag just be instance of IPLD that might be even better outcome

It's is like 90% that already. https://github.com/ipfs/js-ipfs/blob/master/src/core/components/dag.js currently only does some CID parsing magic and callbackifies the API until we have the async/await refactor done.

btw, you mind enjoy experimenting with https://github.com/ipld/js-ipld-graph-builder

**Comment by achingbrain** [comment]
Closing as this issue is very stale.

There are loads of `@ipld/dag-*` modules for working with DAGs and converting them to blocks so this has been done in a roundabout sort of way.
