### ISSUE TITLE
How to add a peer address to bitswap.stat peers list

### ISSUE THREAD

**Issue by hapsody** [ipfs/js-ipfs#2344]
- **Version**: js-ipfs browser-side version with '<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>'

> node.version().then((res)=>console.log(res))
> {version: "0.37.0", repo: 7, commit: ""}

- **Platform**:
Darwin neojuneui-MacBook-Pro-480.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
Chrome browser 75.0.3770.142(official build) (64bit)

- **Subsystem**: bitswap

#### Description: 
I want to add specific peer address to bitswap peer list I can see when I type [ipfs.bitswap.stat](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/BITSWAP.md#bitswapstat) in browser side js-ipfs

example)
![스크린샷 2019-08-08 오후 3 14 59](https://user-images.githubusercontent.com/4454299/62679426-65ef1380-b9ef-11e9-93d5-26e9f99653cd.png)

it's because the sharing speed.
If it can be added to bitswap peers list before '[get](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#get)' some files, it won't need to retrieve that file and it will be that much faster.

This can be happened?

But I couldn't find to add to peer list in browser js-ipfs. I think It's because js-ipfs can't use tcp protocol directly in browser. so it should use relay or signal server via p2p-circuit. and this is reason why the node which want to download can't connect to node that share the file. is this correct?

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Bitswap peers are peers that you are connected to that support the bitswap protocol.  You don't add them to your peer list explicitly, they appear when you have dialed them.
