### ISSUE TITLE
Slow content discovery

### ISSUE THREAD

**Issue by hhfeng** [ipfs/js-ipfs#2348]
I have been experiencing multiple days of failing IPFS connections.

For example: https://gateway.ipfs.io/ipfs/QmdpAidwAsBGptFB3b6A9Pyi5coEbgjHrL3K2Qrsutmj9K
never returns. 

This might be just IPFS infrastructure issue (not specific to js-ipfs). Anyone looking into this? Who should I report to? This makes our apps unusable.

- **Version**: 0.37
- **Platform**: Ubuntu
- **Subsystem**:

#### Description: 
https://gateway.ipfs.io/ipfs/QmdpAidwAsBGptFB3b6A9Pyi5coEbgjHrL3K2Qrsutmj9K
never returns. 
In Chrome DevTools: it is stuck in 

Swarm listening on /p2p-circuit/ipfs/QmcemKtD1bSUcW57rX2d2PgufZwbKzLyMtW8p6GaC6t1fD
index.js:60 Fetching hash for 'QmdpAidwAsBGptFB3b6A9Pyi5coEbgjHrL3K2Qrsutmj9K/master.m3u8'

**Comment by mohe2015** [comment]
For me it works now. Alternatively you could also use https://cloudflare-ipfs.com/ipfs/QmdpAidwAsBGptFB3b6A9Pyi5coEbgjHrL3K2Qrsutmj9K or just run a local instance. But I don't know if there is still a bug somewhere.

**Comment by hhfeng** [comment]
Yes, I can retrieve it from the cloudflare link you sent. However, the
example (also my apps) no longer working (it worked 1 week ago).

For example, https://github.com/moshisushi/hlsjs-ipfs-loader

If you open
https://moshisushi.github.io/ipfs_hls_example.html

It is stuck in
Swarm listening on
/p2p-circuit/ipfs/QmfVavt4vsc9x1Wk3pFYGqc85jf8ihjEWDYTH8Fub3t2Ho

It seems the browser IPFS node doesn't find the hash in the DHT of its peer
nodes?

**Comment by hhfeng** [comment]
It starts to work again today after about 1 week of breakdown. IPFS seems having stability issues. I'm using js-ipfs on browser side. Is there a way from browser side to point to my own IPFS instance (hosted on AWS) as a fallback mechanism when bootstrap nodes fail to find the hash?

**Comment by hhfeng** [comment]
The IPFS is down again! Can anyone take a look why it is so unreliable?

**Comment by autonome** [comment]
@lidel What's the best way to diagnose where this is failing?

Separately, is there a way to configure your own instance as a bootstrap node? IIRC we were talking about this recently - seems to be in line with "centralized and fall back to decentralized until we have true p2p transport in browser".

**Comment by hhfeng** [comment]
@autonome I tried to add my own instance as a bootstrap node by adding my address to the Bootstrap field in ipfs/src/core/runtime/config-nodejs.js. The address is valid because I verified using "ipfs swarm connect <address>", and it worked.

This still doesn't work for me. From Chrome DevTool, it is still stuck in 
Swarm listening on /p2p-circuit/ipfs/QmSGc2GLTDQkkG1sxPNu5Za6JLkCScYdkiM85oKX3YCJtY
waiting for node0.preload.ipfs.io ...

What's the correct way of adding my own instance?

**Comment by lidel** [comment]
@autonome  js-ipfs running in web browser comes with limitations, things that usually break are:
- there is no DHT in js-ipfs (yet): it won't be able to fetch content unless it is already connected to a node that has it (eg. bootstrapper or a preload node)
- unable to open TCP connections, so even if one sets up delegated routing it won't be able to connect to most of peers in the swarm
- connections to websocket ports need to comply with [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) limitations 



@hhfeng  it sounds like you are using default gateway/bootstrap/preload/delegate nodes.

It is fine to use them for prototyping, but if you want more reliable content discovery in web browser it is advised to switch to federated model, ideally running your own instances. Default ones are under high load and YMMV.


Things you may try to improve content discovery speed in browser:

## go-ipfs with websockets as bootstrap node for js-ipfs 

This would give you the biggest speed improvement as it ensures js-ipfs is connected to node with the content

- set up js-ipfs in browser to use your go-ipfs as one of its bootstraps
  - enable websocket transport in go-ipfs (js-ipfs in web browser is unable to use regular TCP transport)
    - add `/ip4/0.0.0.0/tcp/4422/ws` to `Swarm` list in go-ipfs 
  - caveat: js-ipfs running on HTTPS website won't be able to connect to plain `ws://`
    (HTTPS is a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) and requires TLS on the other end)
    - you need to use a server like Nginx for reverse proxying websockets and enable TLS over them
    - the websocket multiaddr of go-ipfs you add to js-ipfs should have `/wss` instead of `/ws`
- make sure the content you want to play is cached on go-ipfs  
  (`pin` or preload CIDs of interest with `refs -r`)


## enable preload and delegate routing

You may also try setting up preload/delegated routing with go-ipfs's api + nginx:

- https://github.com/ipfs/js-ipfs#optionspreload
- https://github.com/ipfs/js-ipfs#configuring-delegate-routers

**Comment by hhfeng** [comment]
@lidel Thanks for the tips. Yes, I wanted to use my own node as the preferred bootstrap. It's not working for me.

Here're the steps I did.
1) Added /ip4/0.0.0.0/tcp/4422/ws to Swarm list in go-ipfs, and restarted go-ipfs daemon
2) In Nginx config file, location /ws is mapped to  server 127.0.0.1:4422, and restarted nginx
3) In the node js code, node_modules/ipfs/src/core/runtime/config-nodejs.js file, added the following multiaddr (real IP address masked with xx) to the top of the Bootstrap field  
'/ip4/xx.xx.xx.xx/wss/4422/ipfs/QmXSYPodxahZPQJKAcL8PS62ciLvtMWfMVT9dQfbAHfHK2'
4) npm start

The content delivery is still very slow. I don't see any speedup. Did I do anything wrong?
Since this is a common question, is there a documented (and verified) steps we can follow to set this up?

Thanks!

**Comment by lidel** [comment]
some ideas:

- potential bug in your setup: 
  in Nginx config file, location `/ws` should not be mapped, it should be `/` on both ends (root, no path)
- instead of modifying js-ipfs sources in step 3, you should either:
  - pass custom  `Bootstrap` list to the [constructor](https://github.com/ipfs/js-ipfs#ipfs-constructor) in [`options.config`](https://github.com/ipfs/js-ipfs#optionsconfig) field:  
    `{ config: { Bootstrap: [<addr1>,<addr2>] } }`
  - or add a boostrap server via [bootstrap API](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/BOOTSTRAP.md#bootstraplist) and then manually connect to it via `swarm connect`
- make sure js-ipfs is actually connected to your go-ipfs peer:
  you can get the list of connected peers via `swarm.peers()`
  if go-ipfs is not on the list, connect to it via `swarm.connect()` and check again
- is `xx.xx.xx.xx` an IP? I think that is a bug, you want to use domain name present in `CN` field of your TLS certificate. you can debug TLS via `openssl s_client -connect xxxx:4422` (try `wikipedia.org:443` to see how valid output looks like)
- make sure you are using js-ipfs 0.37.0 or later

hope this helps

> **Note:** this is an issue tracker and not a support forum. I am closing this issue as it does not seem to identify any actual bug, just configuration issues. In the future please open a topic in https://discuss.ipfs.io/c/help where community members can assist you faster than developers :)
