### ISSUE TITLE
Docs on setting up own bootstrapp node with WebSockets over TLS

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2401]
> potentially part of https://github.com/ipfs/js-ipfs/issues/2231

https://github.com/ipfs/js-ipfs/issues/2348 identified lack of one-stop tutorial(s) for:
- setting up go-ipfs or js-ipfs with TLS-enabled WebSockets transport
- configuring js-ipfs running in web browser to use it as a bootstrapper   
  - it could include section on using bootstrap as a preload/delegate node as well
  - could also include use of it as a [relay](https://github.com/libp2p/specs/tree/master/relay), helping with the [plan to sunset the *-star protocols](https://github.com/libp2p/js-libp2p/issues/385)

This is a good opportunity to create a single primer-style doc that encourages people to run their own nodes, instead of relaying on public ones.

Also:
- preload nodes
- delegated routing? (future, when nodes listen on /wss by default)

#### Prior Art

- Achieving Connectivity Magic https://github.com/ipfs/js-ipfs/issues/1459
- discussion in https://github.com/ipfs/js-ipfs/issues/2348
- ? (please comment below if you are aware of good docs/tutorials/resources on this)

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This sounds like something that should probably exist inside libp2p repo. If there's additional configuration required inside helia to get things to work once libp2p is configured, we will want to open an issue there as well
