### ISSUE TITLE
check what's up with the dns tests in the browser and the gateway ipfs dns cmd 

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#2416]
Dns tests in the browser are failing due to bad json coming from the gateway.

Failing tests for reference https://travis-ci.com/ipfs/js-ipfs/jobs/230141268#L2549

**Comment by alanshaw** [comment]
PR to re-instate skipped tests https://github.com/ipfs/js-ipfs/pull/2417

**Comment by alanshaw** [comment]
It is returning "403 - Forbidden"

**Comment by alanshaw** [comment]
You can use ipfs.io/ipfs/QmNrnVzJT3oQFNFWUSw4v1DxvRQfEzhXUtNk8CdCqhNzTh to check.

I get the following response:

<img width="670" alt="Screenshot 2019-09-03 at 11 05 16" src="https://user-images.githubusercontent.com/152863/64164274-cdf01880-ce3a-11e9-8129-e7f50d0a4953.png">

...yet, if I paste https://ipfs.io/api/v0/dns?arg=ipfs.io into my browser URL bar it works!

**Comment by olizilla** [comment]
not sure I follow you @alanshaw the screenshot shows a 403 on `https://ipfs.io/api/v0/dns?arg=ipfs.io`, do you get a 200 or a 403 on that url? I get a 403

<img width="606" alt="Screenshot 2019-09-03 at 11 18 17" src="https://user-images.githubusercontent.com/58871/64165400-ec571380-ce3c-11e9-95b8-3ffed4eeb444.png">

**Comment by alanshaw** [comment]
Ok this is weird, two windows same URL I get different results:

<img width="1499" alt="Screenshot 2019-09-03 at 11 27 04" src="https://user-images.githubusercontent.com/152863/64165886-d433c400-ce3d-11e9-9f22-f3dab2ebfd5f.png">

One of these nodes is not configured like the others.

**Comment by olizilla** [comment]
oh me oh my... can you see the `x-ipfs-pop` response header on the two requests in the network tab?

**Comment by olizilla** [comment]
hmm could it be related to referer header? If i click the link, i get `403`. If I paste the url into a fresh tab, I get `200`.

**Comment by olizilla** [comment]
ok so, i think this is go-ipfs adding it's extra referer check... @lidel do you know where that check is? Basically go-ipfs adds an extra check for referer if you disable all API CORS headers in config, which we recently changed on the gateways.

**Comment by olizilla** [comment]
See: https://github.com/ipfs/go-ipfs/issues/6204

**Comment by alanshaw** [comment]
Good detective work 🕵️‍♂️ 👍

**Comment by olizilla** [comment]
Thanks! It's unclear to me why this would fail in the tests tho...

**Comment by alanshaw** [comment]
They are browser tests that are failing - they have a referrer.

**Comment by olizilla** [comment]
There is a PR with a fix waiting for review on the gateway infratructure. Will report back here when it gets applied.

**Comment by olizilla** [comment]
@alanshaw the change has been deployed to all the gateways. I now get a `200` with a sensible response on requests to https://ipfs.io/api/v0/dns?arg=ipfs.io with a referer header.
