### ISSUE TITLE
swarm.connect() should override Dial blacklisting

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2424]
- **Version**: v0.37.1
- **Platform**: web, node
- **Subsystem**:  swarm.connect()

#### Description:

It is impossible to manually retry connection if PeerID got blacklisted from dialling. 
The only way is to wait for blacklisting to expire or stop and start node.

#### Steps to reproduce the error:

1. set up go-ipfs somewhere
2. shut it down (needs to be offline)
3. call `swarm.connect()`  with mutiaddr of the node that is offline, get expected connection error
4. start go-ipfs
5. try to connect to it, call `swarm.connect()`  again
6. get error:

> ![dial-is-blacklisted-2019-09-03--14-12-59](https://user-images.githubusercontent.com/157609/64206904-cc0a7180-ce9b-11e9-8199-7bd8bae42a99.png)
> js-ipfs in Brave with TCP transport enabled (https://github.com/ipfs-shipyard/ipfs-companion/issues/716)

This feels like a bug.

#### Expected result

Manual swarm connect should override any automated blacklisting, making it possible to connect as soon as remote node is up, without waiting for blacklisting to expire.

**Comment by jacobheun** [comment]
May not directly be related, but the resolution should help here, is dialing addresses in libp2p https://github.com/libp2p/js-libp2p/issues/451, instead of peers. I've started working on that and will work on making it so that when libp2p receives an address dial request it clears the deny list for the peer. (Ideally we'll have addresses be denied in the future, instead of peers)

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).
