### ISSUE TITLE
Can't connect to HTTP API endpoint when running in node ENV

### ISSUE THREAD

**Issue by Schwartz10** [ipfs/js-ipfs#2465]
- **Version**:
`0.37.1` (node version: `11.9.0`)
- **Platform**:
Darwin MacBook-Pro-228.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

#### Type: 
Bug / Question

#### Severity:
High?

#### Description:

I'm writing some tests for a server that uses the [js-ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client) to connect to a remote node. I'm attempting to setup the tests by instantiating a new instance of `jsipfs` in node (instead of the command line to more easily avoid race conditions), for the server to connect to during testing.

I'm instantiating `jsipfs` in a config file via:

```js
// SETUP TESTS

await IPFS.create()
/*
Which logs in the terminal:
Swarm listening on /p2p-circuit/ipfs/QmX5MWGSSQhsHxeTsLjbr5mF1X4KnU4G3koVPbsvWfBsv4
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmX5MWGSSQhsHxeTsLjbr5mF1X4KnU4G3koVPbsvWfBsv4
Swarm listening on /ip4/192.168.1.162/tcp/4002/ipfs/QmX5MWGSSQhsHxeTsLjbr5mF1X4KnU4G3koVPbsvWfBsv4
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmX5MWGSSQhsHxeTsLjbr5mF1X4KnU4G3koVPbsvWfBsv4


NOTE: no log shows for listening on API, such as:
API listening on /ip4/127.0.0.1/tcp/5002/http
*/
```

In the actual tests, we're attempting to call a method on the jsipfs node's API via the js-ipfs-http-client:

```js
// TEST CODE

cons ipfs = ipfsClient({ port: 5002, protocol: 'http', host: 'localhost' })

ipfs.dag.put({ key: 'value' })
/*
ERROR { Error: connect ECONNREFUSED 127.0.0.1:5002
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
      errno: 'ECONNREFUSED',
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 5003 }
*/
```
Without changing any of the test code (the code above), but running `jsipfs` in the terminal before running the tests (instead of doing it in node), the connection succeeds. I thought this might suggest the discoverability of the node changes depending on how it's instantiated (node vs cli), but logging the `config` of the node in both scenarios return the same result (both enable discoverability). I even tried passing the default config as an option to the `await ipfs.create(config)`, but no luck either.

...

One observation is that instantiating jsipfs from the cli prints a line:
`API listening on /ip4/127.0.0.1/tcp/5002/http`

Whereas instantiating jsipfs from node does not print that line. Could this be a hint into the issue? Is it something with a config or default settings I'm missing or is this just a weird bug? Thanks for any help!

**Comment by achingbrain** [comment]
You're starting the IPFS node up as an in-process node which has a different configuration to a [daemon node](https://github.com/ipfs/js-ipfs/blob/master/src/cli/daemon.js#L30-L83) (notably, there's no HTTP API because it's intended that you'd pass the node instance around within the process and call functions on that).

To do what you're trying to do, use the [`ipfsd-ctl`](https://www.npmjs.com/package/ipfsd-ctl) module - it'll set up a node - daemon, in-process or go, and configure an instance of `ipfs-http-client` to use it.

**Comment by Schwartz10** [comment]
Thanks @achingbrain ! Is it possible to enable the http api as an option when instantiating the jsipfs node? ([seeing this line](https://github.com/ipfs/js-ipfs/blob/master/src/cli/daemon.js#L72))

I took a look at ipfsd-ctl and it seems really helpful, but for this specific use case it feels like it would require us to change our code outside of our tests, just to pass tests. 

For now we added a little `jsipfs daemon` command to the pretest bash script, which does the trick, but it would be nice to do it all in javascript if possible (although i can edit the original ticket to mark severity as low).

**Comment by achingbrain** [comment]
No, the HTTP API is not part of the in-process node, it's only set up by the cli daemon command as you've seen.

You can manually add an HTTP API to a running node by copying the code from the cli daemon command, or you can just use ipfsd-ctl which does all that for you.

If your test setup contains the lines:

```javascript
const IPFS = require('ipfs')
const node = await IPFS.create()

// later
await node.stop()
```

You just need to change them to

```javascript
const df = require('ipfsd-ctl').create()
const node = await df.spawn({
  type: 'js',
  exec: require('ipfs')
})

// later
await node.stop()
```
