### ISSUE TITLE
exchange-files-in-browser install error

### ISSUE THREAD

**Issue by bandoos** [ipfs/js-ipfs#2480]
does anybody have problems installing this example?

I'm on arch linux, and i get the following 
```
make: *** [keccak.target.mk:123: Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory '/home/vimmo/js-ipfs/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.11-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vimmo/js-ipfs/node_modules/keccak
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vimmo/.npm/_logs/2019-09-23T23_52_42_767Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
```
#### Steps to reproduce the error:
cd /path/to/examples/exchange-files-in-browser
npm install

## workaround
i was able to get it working by installing globally _node-gyp_ and _keccackjs_

**Comment by achingbrain** [comment]
Is there any more error output from the console?  It looks like you're having problems compiling native modules but the actual error may be further up.

**Comment by alanshaw** [comment]
This looks like an error installing optional native deps:

> Keccak bindings compilation fail. Pure JS implementation will be used.

I can't see the end of the output here but my guess is that the install actually succeeded and all you're seeing is warnings.

I'm going to close this and assume the above guess is the case but please let us know if not and we can look into it further.
