### ISSUE TITLE
Pin LS: Direct pins should override indirect pins

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/js-ipfs#2518]
We have 3 pin types `recursive`, `direct`, `indirect`. In my eyes the type associated with a pin should follow the priority order recursive/direct then indirect since it seems reasonable that a user should be able to pass the results of `pin ls` filtered by the types `recursive` and `direct` into `pin rm` and clear their repo.

Currently js-ipfs prioritizes  `indirect > direct` and `recusive > indirect`

https://github.com/ipfs/js-ipfs/blob/eefb10fc9a0c084d105642ead30079a9924b3233/src/core/components/pin.js#L226-L227

https://github.com/ipfs/js-ipfs/blob/eefb10fc9a0c084d105642ead30079a9924b3233/src/core/components/pin/pin-manager.js#L95

go-ipfs is currently a bit broken ipfs/go-ipfs#6527, but used to follow (and in the CoreAPI does follow) the same pattern as js-ipfs. In addition to fixing #6527 we're considering moving to `recursive/direct > indirect`.

Is there a reason why this decision was made, or any objections to having everyone move to ` recursive/direct > indirect`?

@Stebalien @daviddias @achingbrain

**Comment by achingbrain** [comment]
The js implementation was modelled after the go implementation so it's probably a bug.

The `recursive/direct > indirect` order of precedence sounds sensible.

**Comment by ef3n9r98** [comment]
Hey @SgtPooki, would you be willing to pay a dev to fix this issue?

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

This issue has been fixed in Helia since it pins by depth rather than having separate recursive, direct, etc.
