### ISSUE TITLE
6 weeks might be too short for a release cycle

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#2525]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1211152/66555563-2e1b5e00-eb4f-11e9-827a-d96356055c65.png">

I'm concerned that all of our dev resources are being spent on release management rather than investing on landing PRs. It might be just what seems from my vantage point. Would like to hear from others.

**Comment by achingbrain** [comment]
I think it's too long!  Most of the tedious stuff has been automated now - the time consuming thing (if we follow the release docs) will be gathering feedback from early testers, but I think if we're running their test suites without breaking anything we can follow a more aggressive release schedule.

**Comment by alanshaw** [comment]
I think we should get a few releases out of the door before we pass judgement on this.

**Comment by daviddias** [comment]
No follow up, I take it that folks are happy. Closing this one.
