### ISSUE TITLE
RFC: generated API docs from typescript declarations

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2548]
I had an idea in https://github.com/ipfs/js-ipfs/pull/651#issuecomment-542132633 that we _could_ add typescript declarations (i.e. **not** convert the project to typescript just a type delcarations file `types.d.ts` with typings information) and **generate our documentation** from them. It would give **us** incentive to keep them up to date **and** make js-ipfs more friendly to our community of typescript users!

The docs would be decoupled from the actual code but we [already have that problem](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC).

Maybe use http://typedoc.org/?

@carsonfarmer might have some ideas if this is possible and might want to be the one to PR the declarations 😝

refs #1166
refs #2320

**Comment by carsonfarmer** [comment]
This is very exciting to hear! I understand from @raulk that the libp2p team is similarly interested in adding declarations files to individual repos, which would likely make the efforts on js-ipfs much easier. I'm not sure what the timeline is for libp2p projects though?

We've used typedoc before (see https://textileio.github.io/js-textile-wallet/ for example) and quite liked it.

**Comment by hugomrdias** [comment]
I have been trying to push this for a long time, nice to know we are open to this now.
ipfsd-ctl already has some typedefs and the next version will have a lot more this is what makes this https://github.com/ipfs/interface-js-ipfs-core/pull/541#issuecomment-543338311 possible.

**Comment by alanshaw** [comment]
I'm somewhat disappointed with typedoc...

I added [type definitions to `abortable-iterator`](https://github.com/alanshaw/abortable-iterator/commit/c3c68a1888a114de64f9e350cf8f725514b08c41#diff-b52768974e6bc0faccb7d4b75b162c99) to try it out and was immediately burnt by https://github.com/TypeStrong/typedoc/issues/1050:

<img width="1217" alt="Screenshot 2019-10-29 at 10 46 41" src="https://user-images.githubusercontent.com/152863/67760732-be0b4400-fa39-11e9-946e-8e2a4ac2ef93.png">

When the "Only Exported" checkbox is checked the list on the right is incorrect. Where's my `sink`, `transorm` and `duplex` exports? Source code:

<img width="399" alt="Screenshot 2019-10-29 at 10 47 01" src="https://user-images.githubusercontent.com/152863/67760762-d0857d80-fa39-11e9-8af8-91ef1ccaaf66.png">

I also have a function called `source` and a type called `Source`. Clicking the links in the menu on the right do not work properly because it generates `<a name="source" />` and `<a name="Source" />`.

For reference, my setup: https://github.com/alanshaw/abortable-iterator/pull/2

**Comment by hugomrdias** [comment]
new iteration in html using typedoc and autogenerated type defs all from vanilla js with jsdoc
https://hugomrdias.keybase.pub/ipfsd-ctl-docs/

**Comment by NatoBoram** [comment]
Wouldn't it be just simpler to migrate everything to TypeScript? Since it's literally just JavaScript with types, you can convert the whole project without changing a thing at first and just add actual types gradually.

**Comment by bluelovers** [comment]
where are the typescript file at? i didn't see it in this repo

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This should be fixed in Helia since it's written in typescript. I believe libp2p is in the process of being updated to typescript as well.
