### ISSUE TITLE
Add Apache 2.0 license

### ISSUE THREAD

**Issue by kryptine** [ipfs/js-ipfs#2552]
With [go-ipfs having switched to dual MIT and Apache 2 licenses](https://github.com/ipfs/go-ipfs/issues/6302), can js-ipfs do the same thing as well?

**Comment by alanshaw** [comment]
Yes please, would you be interested in opening a PR similar to https://github.com/ipfs/go-ipfs/pull/6301?

**Comment by alanshaw** [comment]
ping @kryptine ?

**Comment by ay2306** [comment]
@alanshaw Can I work on this?

**Comment by alanshaw** [comment]
@ay2306 yes please 🙏
