### ISSUE TITLE
sharness not part of CI?

### ISSUE THREAD

**Issue by AuHau** [ipfs/js-ipfs#2561]
Why are not Sharness tests run as part of CI? 

I see in Release checklist mentioned that the sharness tests does not run `jsipfs`, but I believe that it is wrong according to https://github.com/ipfs/js-ipfs/blob/master/test/sharness/Makefile#L47

In `js-ipfs-repo-migrations` I have integrated them as part of CI https://travis-ci.com/ipfs/js-ipfs-repo-migrations/builds/132972299

What is the status of this? I can create PR to integrate same job here...

**Comment by achingbrain** [comment]
I think that's an oversight - please do create a PR for this.

**Comment by achingbrain** [comment]
Actually looking back on it, I meant [ipfs/ipfs-sharness-tests](https://github.com/ipfs/ipfs-sharness-tests) did not run `js-IPFS`...

**Comment by alanshaw** [comment]
+1, the sharness tests in this repo cover anything that isn't already covered on other tests. It would be preferable to get https://github.com/ipfs/ipfs-sharness-tests up and running if anyone would like to contribute on this issue!

**Comment by achingbrain** [comment]
I'm closing this because our testing strategy is unit and interface tests, not sharness at the time being as the functionality is covered by other tests.
