### ISSUE TITLE
browser-browserify is broken on 0.39

### ISSUE THREAD

**Issue by kpp** [ipfs/js-ipfs#2563]
```
$ npm start

> sojsclient-example@1.0.0 start /home/jsclient
> npm run bundle && npm run serve


> jsclient-example@1.0.0 bundle /home/jsclient
> browserify src/index.js > public/bundle.js


/home/jsclient/node_modules/ky-universal/browser.js:1
export {default} from 'ky';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsclient-example@1.0.0 bundle: `browserify src/index.js > public/bundle.js`
npm ERR! Exit status 1
```

(script from https://github.com/ipfs/js-ipfs/blob/master/examples/browser-browserify/package.json#L9)

**Comment by alanshaw** [comment]
To fix this in `ipfs-http-client` I had to [add a browser alias to ky/umd](https://github.com/ipfs/js-ipfs-http-client/blob/c5edccd83ac8a72737c5b13d5a81ad0c64a6619e/package.json#L21).

@hugomrdias do you see any problem with that?

@kpp would you be able to send a PR to fix this?

**Comment by kpp** [comment]
> send a PR to fix this?

I can but I am a node.js newbie

**Comment by hugomrdias** [comment]
this is browserify specific at this point i don't feel we should put too much effort in it, all the modern bundlers are esm first and support this. 
still if you feel like it this should be handled upstream 

`ky` package.json should have 
```
main: "index",
module: "index.js",
browser: "umd.js"
```

`ky-universal` should also have the corresponding files and package.json properties  

we should keep our `browser` property restricted to https://github.com/ipfs/js-ipfs-http-client/blob/c5edccd83ac8a72737c5b13d5a81ad0c64a6619e/package.json#L22-L23 nothing else to avoid problems

**Comment by alanshaw** [comment]
@hugomrdias that way `ky-universal` would be umd first no? Would it be better to just update our browserify examples to use `babelify` so that ky can stay esm first?

**Comment by hugomrdias** [comment]
yes ! actually we would just need to change ky-universal and not ky itself. Or use https://github.com/mattdesl/esmify 
This isomorphic browser swaps plus esm/cjs interop is a big pile of weird stuff...

**Comment by ay2306** [comment]
@alanshaw Can I work on this issue?

**Comment by alanshaw** [comment]
You can, although I just tried to build and run the example and it worked fine...

Perhaps you could verify it's working @ay2306?

**Comment by ay2306** [comment]
@alanshaw we are talking about example `exchange-files-in-browser`? I ran it in an ubuntu docker container. 
`npm run bundle` gives error `Cannot find module 'ipfs/dist' from '/js-ipfs/examples/exchange-files-in-browser/public'`

**Comment by alanshaw** [comment]
nope, the example called "browser-browserify"

**Comment by ay2306** [comment]
@alanshaw scenario is same in "browser-browserify", should I raise another issue for "exchange-files-in-browser"

**Comment by alanshaw** [comment]
Please run `npm install` and `npm run build` in the root of the repository before building the examples.

**Comment by ay2306** [comment]
I am sorry, that was stupid. But I can confirm that it builds. We can close this issue.
