### ISSUE TITLE
dht.provide() doesn't accept strings

### ISSUE THREAD

**Issue by reasv** [ipfs/js-ipfs#2573]
- master:
- Chrome/Windows:
- DHT:

#### Type:
Bug
#### Severity:
Medium
#### Description:
ipfs.dht.provide() doesn't accept a string as input. It exclusively accepts a CID instance object.

This is inconsistent with how dht.findProvs() works, and it's not even hinted at in the documentation.

The error returned for giving it a string is "not a valid CID" which is also very opaque and confusing.

I would suggest to either update the documentation or to modify the function to do something like const cid = new CID(string_argument) in order to support a string-based argument.

**Comment by reasv** [comment]
I would also like to add that the other errors it's giving me are rather opaque.
`Uncaught (in promise) Error: Failed to provide to 7 of 20 peers`
It's not really clear what this means or how it happened

**Comment by reasv** [comment]
I can make a pull request with the fix I proposed if you think that it would be ok

**Comment by alanshaw** [comment]
🙏 yes please @reasv - it would also be good to get an [update to the docs](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/DHT.md#dhtprovide) if you have time! ❤️

**Comment by reasv** [comment]
Ok. I will do this later today or tomorrow.

**Comment by reasv** [comment]
@alanshaw https://github.com/ipfs/js-ipfs/pull/2589

**Comment by alanshaw** [comment]
resolved by https://github.com/ipfs/js-ipfs/pull/2589
