### ISSUE TITLE
Add dotfile file for recursive upload file whitelisting/blacklisting

### ISSUE THREAD

**Issue by rumkin** [ipfs/js-ipfs#2577]
- **Version**: 0.39.0
- **Platform**: all
- **Subsystem**: CLI

#### Description:

Add dotfiles to whitelist/blacklist files inside of directory/subdirectories for recursive upload. It will be useful for save file upload. I suppose there should be `.ipfsignore` and `.ipfslist` files for blacklisting and whitelisting files respectively. If there is whitelist and blacklist files presented in the same time the error should be thrown.

For me whitelisting is more preferable: it preserves private files (like keys or configs) from being uploaded accidentally by running in wrong directory or without proper configuration.

The files could have standard ignore-files format or mixed format.

### Mixed format

Mixed file listing format allows to add files by mask, like standard ignore-files. But as addition to it, if the mask is too wide, it allows to exclude some particular files. For this each pattern should be prepended with plus or minus, thus rules has the next format: `"+"|"-" glob|path`.

Example:

```
+ **.js
+ /assets/
- /config.dev.js
```

**Comment by alanshaw** [comment]
> It will be useful for save file upload

Would you mind expanding on this? I'm not sure I understand.

The [`addFromFs`](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#addfromfs) command accepts an ignore list - just wondering if that covers your use case and if not what's missing?

**Comment by rumkin** [comment]
No. I'm about CLI recursive add command:
```
jsipfs add -r .
```
I looked at the source ([src/cli/commands/add.js](https://github.com/ipfs/js-ipfs/blob/master/src/cli/commands/add.js)) and there is no ignore list option.

But. My I have concerns about security. Uploading files to IPFS you make them available forever, for everyone, without ability to remove something. And ignore files are the worst for security. I couldn't find the research now, but there are several about ssh keys and other security related data uploaded to NPM and Github by accident. People just forget to add such files to ignore list and commit/upload sensitive data to public storages. I think It would be way more secure to select uploading files by specifying certain files before upload.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This is something that should be easily supported with bash/shell/terminal commands and piping of filenames to CLI tools.
