### ISSUE TITLE
chore: test trickle DAG parity with go-ipfs

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#2597]
Once go-ipfs trickle DAG corrects [this issue](https://github.com/ipfs/go-ipfs/issues/3576), test whether the generated hashes are the same.

**Comment by achingbrain** [comment]
We have this interop test that does this: https://github.com/ipfs/interop/blob/master/test/files.js#L314-L327

It doesn't assert the type of leaf node, but it does assert that the generated hashes are the same.

**Comment by alanshaw** [comment]
Sounds like this is resolved! Thanks @achingbrain 👏
