### ISSUE TITLE
Add both 'muxer' and 'streams' properties to 'swarm.peers()'

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/js-ipfs#2601]
Both [`cli commands`](https://docs.ipfs.io/reference/api/cli/#ipfs-swarm-peers) and [`http api`](https://docs.ipfs.io/reference/api/http/#api-v0-swarm-peers) documentation say it's possible to get several details about the set of peers the node is connected to. 

The returned info includes, among other properties:
- [ ] `streams` - information about open streams for each peer
- [x] `muxer` - the type of stream muxer the peer is using

But none of this info is currently available and it needs to be implemented to get consistent with `go-ipfs`.

Moreover, `latency` is always being returned as `n/a` (if `verbose` option is set) and it needs to be properly implemented as well.

**Comment by alanshaw** [comment]
This will become possible with the [new connection interface](https://github.com/libp2p/js-interfaces/tree/master/src/connection#connection-1) coming with the async/await refactor in libp2p. You should be able to query connections for streams and also get the multiplexer info from the `stat` property amongst other things.

cc @jacobheun

**Comment by alanshaw** [comment]
@jacobheun I added muxer in https://github.com/ipfs/js-ipfs/pull/2681 - any way we can get a per stream `protocol`? https://docs.ipfs.io/reference/api/http/#api-v0-swarm-peers

**Comment by jacobheun** [comment]
@alanshaw we keep track of streams on connections now. So you should be able to use the [`Connection.registry`](https://github.com/libp2p/js-interfaces/tree/master/src/connection#connection-streams-registry) Map to get the protocol and any other metadata that is saved to the stream.

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Closing as not planned
