### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by suutaku** [ipfs/js-ipfs#2602]
js-ipfs v0.38.1

I use js-ipfs bundle in my project and process memory has keep going.
there is some analysis did by `easy-monitor`, I think it is a memory leak at dht query or somewhere else.
too many `debug` calls in that node (154287)
![1](https://user-images.githubusercontent.com/4685052/68852340-a6f37400-0712-11ea-885e-15ab58fda41f.PNG)
![2](https://user-images.githubusercontent.com/4685052/68852353-aa86fb00-0712-11ea-80da-3a30d4d252d4.PNG)
![3](https://user-images.githubusercontent.com/4685052/68852362-ad81eb80-0712-11ea-8bc5-fa0070362565.PNG)
![4](https://user-images.githubusercontent.com/4685052/68852372-af4baf00-0712-11ea-8e2a-5efc249f0848.PNG)

please take a look.
thanks.

**Comment by alanshaw** [comment]
cc @jacobheun @vasco-santos
