### ISSUE TITLE
--stream option support for ipfs.name.resolve?

### ISSUE THREAD

**Issue by reardenlife** [ipfs/js-ipfs#2611]
Ad far as I can see, there is no option --stream (see https://github.com/ipfs-shipyard/ipfs-companion/issues/643 ) for IPNS name resolution.

Are there any plans to add a support for it?

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

At the moment `@helia/ipns` does not have a streaming API but it does have `onProgress` callbacks which show the progress of an IPNS query.

Please open an issue against `@helia/ipns` if this is still a desirable feature.
