### ISSUE TITLE
change dht put value to file

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2613]
See changes here: https://github.com/ipfs/go-ipfs/pull/6750

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Closing as not planned.
