### ISSUE TITLE
I lost clients and got homeless while trying to make it work for them

### ISSUE THREAD

**Issue by mnts** [ipfs/js-ipfs#2617]
- **Version**:
- **Platform**:
- **Subsystem**:

**Comment by mnts** [comment]
why its so fucking problematic in all the ways while trying to implement all this js-ipfs stuff

**Comment by mnts** [comment]
and whyyy I still trying to setup it, beliebving it all will work out

**Comment by alanshaw** [comment]
If you have a specific issue let us know. However, please read the code of conduct before interacting again https://github.com/ipfs/community/blob/master/code-of-conduct.md
