### ISSUE TITLE
repo doesn't persist in browser on upgrade from v0.38.1 to v0.39.0

### ISSUE THREAD

**Issue by npfoss** [ipfs/js-ipfs#2629]
- **Version**: js-ipfs 0.38.1 and 0.39.0
- **Platform**: latest Firefox and Brave (Chromium)
- **Subsystem**: js-ipfs

#### Description:
default repo doesn't persist in browser when you upgrade from v0.38.1 to v0.39.0

this is a big problem for serverless apps where the browser is the only place user data is stored :P

#### Steps to reproduce the error:

clone this repo and follow the simple three step readme: https://github.com/npfoss/js-ipfs-bug-2

**Comment by alanshaw** [comment]
<img width="270" alt="Screenshot 2019-11-25 at 09 16 29" src="https://user-images.githubusercontent.com/152863/69527499-5676e480-0f64-11ea-9283-f4ed03781be8.png">

Looks like between the two versions the level datastores gained a "level-js-" prefix.

@achingbrain do you have a sec to look into this?

**Comment by achingbrain** [comment]
The defaults passed to `level-js` changed with the upgrade to [`level`](https://www.npmjs.com/package/level) so a few changes need to be made:

* https://github.com/Level/packager/pull/96
* https://github.com/Level/level-js/pull/184
* https://github.com/ipfs/js-ipfs-repo/pull/215

**Comment by alanshaw** [comment]
fixed in `0.39.1` and `0.40.0`
