### ISSUE TITLE
More use of helpful logs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#265]
We need more logs. Not many, but some enough for development

**Comment by dignifiedquire** [comment]
take a look at a good example in js-ipfs-secio :)

**Comment by noffle** [comment]
@diasdavid can you elaborate? are there particular areas you'd like to see logged?

**Comment by RichardLitt** [comment]
![logs](https://cloud.githubusercontent.com/assets/910753/15536863/39d2970a-226b-11e6-860e-6ad08e871c17.jpg)

**Comment by VictorBjelkholm** [comment]
@diasdavid can we reconsider this for milestone 2 instead of 4? Necessary to have good logging in order to develop, is my five cents.

**Comment by diasdavid** [comment]
@VictorBjelkholm you should not be blocked from adding good logs, we already have `debug` all over the place anyways :)

**Comment by dignifiedquire** [comment]
@VictorBjelkholm try running with `DEBUG=libp2p*,ipfs*` that should give you quite a lot of logging info :)

**Comment by diasdavid** [comment]
Closing this one, it has gotten into our dev practices :)
