### ISSUE TITLE
interface-core pubsub subscribe fails in firefox

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#2662]
- **Version**:
- **Platform**:
- **Subsystem**:

#### Description:
Interface-core pubsub subscribe tests fail only firefox with secondary Go nodes.
We need to make sure JS works and investigate why Go fails. 

look into https://github.com/ipfs/js-ipfs-http-client/blob/master/src/pubsub/subscribe.js#L27-L37 this might be a http-client issue instead

#### Steps to reproduce the error:
https://travis-ci.com/ipfs/js-ipfs/jobs/266025769#L1064

- [ ] Uncomment the tests in the browser https://github.com/ipfs/js-ipfs/blob/32311655d17f5e5eb3a445be9f68b44e6d60a7ef/test/core/interface.spec.js#L107

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This should be resolved in Helia. If you were seeing this error with js-ipfs please try in Helia!
