### ISSUE TITLE
add (real) getters for properties

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#267]
For the convenience of debugging directly in the browser dev tools, we should add real getters for properties the api/classes expose:
`get Hash() => this.toJSON().Data`
`get id() => this.id.toB58String()`

This makes it easy to invoke the getters directly in the dev tools console and the user doesn't need to add any breakpoints or use REPL to check values of objects. (Functions can't be directly invoked).

**Comment by diasdavid** [comment]
Interesting. That makes me thing that now with Chrome DevTools running natively with Node.js, we will see a shift in the Node.js module land to use that pattern more.

**Comment by diasdavid** [comment]
Chrome DevTools is now available with Node.js 6.3.0 https://www.reddit.com/r/node/comments/4yoane/in_case_you_have_missed_it_node_v630_came_out/

@haadcode would you like to lead the effort of making js-ipfs nicer with these dev tools the browser offers?

**Comment by dignifiedquire** [comment]
Before we start work on this, I would like to establish some clear guidelines on when and where to use this pattern.

**Comment by jbenet** [comment]
Wow JavaScript is really turning into Java. What a bummer, it was the
comeback of lisp.

**Comment by haadcode** [comment]
@diasdavid sure I can lead this this, but can't probably put focused effort on it until October :/

> I would like to establish some clear guidelines on when and where to use this pattern

Anything specific you had in mind? 

Imo the guideline is: *use getters to expose read-only, non-async, non-io properties of an object*. Sounds good?

> Wow JavaScript is really turning into Java. What a bummer, it was the comeback of lisp.

Don't worry, JS is definitely not turning into Java :) Getters and setters have been part of JS since ES5, ES6 just kinda made them usable. Getters and setters are an excellent language construct to expose public properties of an object and make a distinction between a member function (method) call and member variable (state).

I, for one, am happy that JS is finally getting the OO side of the language right. Now it has the capabilities of both paradigms!

**Comment by jbenet** [comment]
My comment is not about OOP, it's about the complexity inherent in the language. Simplicity is really hard to get, and javascript had amazingly good simplicity. Interesting they existed already, I hadn't seen them.

**Comment by haadcode** [comment]
> it's about the complexity inherent in the language

Fair point. Javascript definitely has complexity that prolly wouldn't be there without all the legacy. I feel JS has great simplicity (due to its dynamic nature) but I suppose that's in the eye of the beholder...

**Comment by diasdavid** [comment]
> Imo the guideline is: use getters to expose read-only, non-async, non-io properties of an object. Sounds good?

Not quite, although it seems simple, the thing is that for a change like this we need to explain 'why we should change our patterns' (which should be documented so that we have a reference for future discussions) and the plan to change those patterns (list all the modules, ensure that we adopt it across the board, etc), otherwise it will always be half baked with a lot of inconsistencies.

> @diasdavid sure I can lead this this, but can't probably put focused effort on it until October :/

Not a problem, this would be part of the milestone 4 effort :) Thank you.

**Comment by haadcode** [comment]
> Not quite, although it seems simple, the thing is that for a change like this we need to explain 'why we should change our patterns' (which should be documented (examples + benefits) so that we have a reference for future discussions) and the plan to change those patterns

Not sure this is a change in our *patterns*. `node.toJSON().Data` is a property getter much as `node.Data` or `const v = { f: 1 }; v.f;` would be. Where do you see this to change patterns or generally make it confusing as compared to what we have now in terms of the API design of the objects? Can you elaborate what you mean here?

> Not a problem, this would be part of the milestone 4 effort

Sounds good. When is MS4 work expected to happen and what's the estimated completion date for MS4?

**Comment by diasdavid** [comment]
It is a change that has to be communicated through our API plus our code, for e.g: I expect that `node.Data` is a static property and not a getter, the same way that, right now I wouldn't expect that `node.Data = 'banana'` would run any code.

> Sounds good. When is MS4 work expected to happen and what's the estimated completion date for MS4?

October :)

**Comment by haadcode** [comment]
> It is a change that has to be communicated through our API plus our code, for e.g: I expect that node.Data is a static property and not a getter, the same way that, right now I wouldn't expect that node.Data = 'banana' would run any code.

Wouldn't `DAGNode.Data` be a static property? Objects, as in instances in OO terms, don't usually have static properties. Static properties are usually part of classes, ie. they're *static* and can't be instantiated nor mutated.

`node.Data = 'banana'` banana would set the variable, right? As such it "runs code", no? Whether *setters* is good design is a different question (imo they're not).

I'm not trying to disprove you but I want to understand where you're coming from and how you see this, so that all those perspectives can be taken into consideration.

Would be good to get @dignifiedquire thoughts on this too.

**Comment by haadcode** [comment]
> October

Perfect. Sign me up for this goal and I'll make sure to take it into my personal planning for Q4.

**Comment by diasdavid** [comment]
Ok, `node.Data` failed to pass as a good example. Let's think of `node.hash`, if we do

without getters

```
console.log(node.hash) // QmHASH1
node.data = 'new data'
console.log(node.hash) // QmHASH1
```

with getters 

```
console.log(node.hash) // QmHASH1
node.data = 'new data'
console.log(node.hash) // QmHASH2
```

**Comment by haadcode** [comment]
Got it.

Object's variables in JS by default are read + write, so if you defined your `node` as
```javascript
let node = { data: 'old data' }
```
...you are able to assign a value to a (member) variable. Ie. you can do this:
```javascript
console.log(node.hash) // QmHASH1
node.data = 'new data'
console.log(node.hash) // QmHASH2
```

However, getters in JS are read-only by default, so `node.data` assignment would result in no-op as JS silently fails the assignment. A more explicit way would be to throw an error (also possible to do if needed). 

So if you define `node` like this:
```javascript
let node = Object.defineProperties({}, { "data": { value: true, writable: false } } // writable is 'false' by default
```
or ES6
```javascript
let node = {
  get data() { return _data }
}
```
...you can enforce the property to be read-only and the result is:
```javascript
console.log(node.hash) // QmHASH1
node.data = 'new data' // no op
console.log(node.hash) // QmHASH1
```

The idea of getters is to expose a variable as read-only property in the public interface of a class. This makes it available for query from an instance of that class (object) while disallowing assignment to that property. Ie. you can read the state, but you can't change the state directly.

Does that make sense?

Furthermore, I've found it a good pattern to use naming conventions to further distinguish properties by camel-casing them like `node.Data` instead of `node.data` and using `_` to signify "private" properties of an object, ie. `node._data // private` `node.Data // public`. However, we don't have to follow this convention and can enforce the correctness purely via language constructs (get/set) if we want to.

**Comment by jbenet** [comment]
I mean "simplicity" in the Rich Hickey sense. in a less subjective, not qualitative but a more objective, quantifiable way. See https://www.infoq.com/presentations/Simple-Made-Easy -- "the braidedness" of something. How much "braidedness" does the language encourage. How much cognitive load it causes. (eg that evented code causes "[stack ripping](http://berb.github.io/diploma-thesis/original/043_threadsevents.html)" is why events are not simple). anyway, not important right now.

**Comment by haadcode** [comment]
Since we moved to async functions for the DAGNode properties, I don't think this makes sense anymore.

We can re-open this issue if we ever move back to sync properties.

Closing.
