### ISSUE TITLE
Lambda/edge implementation solely for pinning

### ISSUE THREAD

**Issue by posix4e** [ipfs/js-ipfs#2685]
I wonder how hard it might be to start with js-ipfs, and build a simple lambda/worker which runs in the cloud and stores data in a kv or object store?

**Comment by achingbrain** [comment]
On paper this seems reasonable, you can even use [`s3-datastore`](https://github.com/ipfs/js-datastore-s3) to back your repo in the same way as [`ipfs-registry-mirror`](https://github.com/ipfs-shipyard/ipfs-npm-registry-mirror).

I think the problem you may have is that lambdas expect to be spun up, do some processing then get shut down - IPFS runs best as a long-lived daemon process.

So your lambda would start, it'd spawn an IPFS node, you'd pin a CID, then it would shut down and the pin would not be available on the network any more.

**Comment by achingbrain** [comment]
I'm going to close this because it's not describing an issue with `ipfs` - please add a post to https://discuss.ipfs.io/ or visit the IRC channel (#ipfs on Freenode) if you want some feedback on your ideas.
