### ISSUE TITLE
webui redirects to "https://undefined:9090"  

### ISSUE THREAD

**Issue by ggarri** [ipfs/js-ipfs#2697]
- **Version**: 
js-ipfs version: 0.40.0-
Repo version: 7
System version: x64/linux
Node.js version: v11.15.0
- **Platform**: Linux  4.15.0-72-generic #81-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: webui

#### Description:

After running `ipfs daemon`  when user try to access to default webui url(`http://127.0.0.1:5002/webui`) it is redirecting to `http://undefined:9090//ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip`.

#### Steps to reproduce the error:
- Run js-ipfs daemon
```bash
$> jsipfs daemon
Initializing IPFS daemon...
js-ipfs version: 0.40.0
System version: x64/linux
Node.js version: 11.15.0
....
API listening on /ip4/127.0.0.1/tcp/5002/http
Gateway (read only) listening on /ip4/127.0.0.1/tcp/9090/http
Web UI available at http://127.0.0.1:5002/webui
```
- Go to your favorite browser an open a tab with `http://127.0.0.1:5002/webui`
- You are redirected to `http://undefined:9090//ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip`

#### Expected result
- Run js-ipfs daemon
- Go to your favorite browser an open a tab with `http://127.0.0.1:5002/webui`
- You are redirected to `http://127.0.0.1:9090//ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip`

**Comment by alanshaw** [comment]
resolved by https://github.com/ipfs/js-ipfs/pull/2698
