### ISSUE TITLE
Gateway missing translations.json

### ISSUE THREAD

**Issue by ggarri** [ipfs/js-ipfs#2699]
- **Version**: 
js-ipfs version: 0.40.0-
Repo version: 7
System version: x64/linux
Node.js version: v11.15.0
- **Platform**: Linux  4.15.0-72-generic #81-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: webui

#### Description:

Gateway dashboard UI cannot be translated to other than English. Translation snippets appear to be requested but missing.

#### Steps to reproduce the error:

- Run ipfs daemon service
- Open in the browser the Gateway->settings
http://127.0.0.1:9090/ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip/#/settings
- In Language section click on "Change" and select for example "Spanish"
- Dashboard is partially translation (probably due to missing i18n snippets)
- On browser network tab you can see a 500 http error fetching 
http://127.0.0.1:9090/ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip/locales/es/translation.json
- The fact that `translation.json` is missing does not affect the actual partial internationalization of the UI

## Screenshot
![image](https://user-images.githubusercontent.com/2728080/71626188-33d38d80-2bec-11ea-8096-7b8f93fd4a5b.png)

**Comment by achingbrain** [comment]
Please can you open an issue on https://github.com/ipfs-shipyard/ipfs-webui

**Comment by ggarri** [comment]
Done https://github.com/ipfs-shipyard/ipfs-webui/issues/1395
