### ISSUE TITLE
webcrypto

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#27]
# webcrypto
https://github.com/diasdavid/webcrypto

WebCryptoAPI polyfil to work in Node.js in the Browser (so that you don't have to be concerned about moving crypto code between a browser and server side app)

Context: https://github.com/nodejs/node/issues/2833

# How can you help
- The module is still being made, if someone wants to take the lead, it would be great :)

**Comment by autoit4you** [comment]
I'd definitively interested in helping, although I'm not sure where to start.

**Comment by diasdavid** [comment]
@autoit4you we need to create a interface that hopefully takes the most from the overlap of both worlds and then make a shim for the remaining calls that differ from both implementations.

One thing to have in mind is that WebCryptoAPI is promises based, while the Node.js Crypto module is callback based (for now), so we will need to define both interfaces too

**Comment by harlantwood** [comment]
Not sure if it helps, but I've found Bluebird's 

`.promisify( function )`

And

`.promisifyAll( module )`

To be very useful and easy ways to automatically create promises from functions that take callbacks... (though they don't work with all libs).

**Comment by harlantwood** [comment]
For more on that: https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification

**Comment by diasdavid** [comment]
Getting everything more organised, moving libp2p endeavours to js-libp2p, new issue can be found at - https://github.com/diasdavid/js-libp2p/issues/4
