### ISSUE TITLE
ip6 api causes `Failed to construct 'URL': Invalid URL`

### ISSUE THREAD

**Issue by agowa338** [ipfs/js-ipfs#2701]
- **Version**: 0.10.2
- **Platform**: IPFS Desktop on Windows 10 1903 (OS Build 18362.535)
- **Subsystem**:

#### Type:
Bug

#### Severity:
High

#### Description:
An ipv6 address within the ipfsApi triggers a bug when constructing URLs.
![image](https://user-images.githubusercontent.com/2544867/71649899-c2dac580-2d12-11ea-8041-125448645f43.png)

#### Steps to reproduce the error:

1. Set the ipfs api url to `/ip6/::1/tcp/5001`
2. Restart ipfs
3. Open Developer tools (to see the javascript errors)
4. Open the IPFS website and click on "Files".

**Comment by alanshaw** [comment]
@hacdias any chance you can look into this?

**Comment by SgtPooki** [comment]
This is no longer relevant for js-ipfs because js-ipfs is not going to be used in ipfs-desktop nor webui moving forward. Closing this. Please re-open in ipfs-webui / kubo repo if you're still experiencing this issue

cc @tinytb @achingbrain
