### ISSUE TITLE
roadmap / readme dont have listing of modules

### ISSUE THREAD

**Issue by jbenet** [ipfs/js-ipfs#271]
the roadmap and readme have feature listings and links to issues, but there isnt a clear listing of all the sub module repos that make up js-ipfs. would be nice to have that list to quickly access those modules

**Comment by RichardLitt** [comment]
You can get this from `npm ls --depth=0`. However, this doesn't necessarily help. It would be great if we could highlight which ones we think are important for the Roadmap, and link their repos in a Markdown file. What do you think, @diasdavid?

```
$ npm ls --depth=0
ipfs@0.14.1 /Users/richard/src/js-ipfs
├── aegir@3.2.0
├── babel-runtime@6.9.2
├── bl@1.1.2
├── boom@3.2.2
├── bs58@3.0.0
├── buffer-loader@0.0.1
├── chai@3.5.0
├── debug@2.2.0
├── detect-node@2.0.3
├── expose-loader@0.7.1
├── form-data@1.0.0-rc4
├── fs-blob-store@5.2.1
├── glob@7.0.5
├── gulp@3.9.1
├── hapi@13.4.1
├── idb-plus-blob-store@1.1.2
├── interface-ipfs-core@0.3.0
├── ipfs-api@6.0.1
├── ipfs-bitswap@0.4.1 invalid
├── ipfs-block@0.3.0
├── ipfs-block-service@0.4.0
├── ipfs-merkle-dag@0.6.0
├── ipfs-multipart@0.1.0
├── ipfs-repo@0.8.0
├── ipfs-unixfs@0.1.4
├── ipfs-unixfs-engine@0.9.0 invalid
├── isstream@0.1.2
├── joi@8.4.2
├── left-pad@1.1.0
├── libp2p-ipfs@0.11.0 invalid
├── libp2p-ipfs-browser@0.10.0 invalid
├── lodash@4.13.1
├── lodash.get@4.3.0
├── lodash.set@4.2.0
├── mafmt@2.1.1
├── mocha@2.5.3
├── multiaddr@2.0.2
├── multihashes@0.2.2
├── ncp@2.0.0
├── nexpect@0.5.0
├── path-exists@3.0.0
├── peer-book@0.3.0
├── peer-id@0.7.0
├── peer-info@0.7.0
├── pre-commit@1.1.3
├── promisify-es6@1.0.1
├── readable-stream@1.1.13
├── rimraf@2.5.2
├── ronin@0.3.11
├── run-parallel@1.1.6
├── run-parallel-limit@1.0.3
├── run-series@1.1.4
├── run-waterfall@1.1.3
├── stream-to-promise@1.1.1
├── temp@0.8.3
├── through2@2.0.1
└── transform-loader@0.2.3
```

**Comment by dignifiedquire** [comment]
That list is not particularly useful as it contains test dependencies as well as helper modules. To get that list it's roughly searching for anything beginning with `js-` in

- diasdavid
- ipfs
- jbenet
 
public repos.

**Comment by RichardLitt** [comment]
Is there any way to narrow down the 'roughly' to something more useful?

**Comment by nginnever** [comment]
A few modules aren't under ```daviddias, ipfs, or jbenet``` as well. 

I created a list <a href="https://github.com/nginnever/js-ipfs-modules"> here </a> that is every module that I know of that is being used by js-ipfs. I am not too sure of the state of libp2p and what js-ipfs is currently depending on so @diasdavid can edit the list as needed.

**Comment by dignifiedquire** [comment]
thanks a bunch @nginnever I will review it in the morning

**Comment by dignifiedquire** [comment]
Excellent inspiration on how to do this in the readme: https://github.com/cyclejs/cyclejs#packages
