### ISSUE TITLE
require('ipfs') causes unloading of component in React Native 0.61.5

### ISSUE THREAD

**Issue by emclab** [ipfs/js-ipfs#2737]
Version: output of `jsipfs version --0.40.0
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows). Win10/React Native 0.61.5. Nodejs 10.16.0 (via nodejs-mobile-react-native 0.5.0)

Here is the code of initiating IPFS node and the code is called in a React Native component SplashScreen.

var rn_bridge = require('rn-bridge');
const IPFS = require('ipfs');

async function init() {
  const node = await IPFS.create()
  console.log("rn bridge inited!", node.version);
};

init();

// Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  rn_bridge.channel.send(msg);
  console.log("Message from RN : ", msg);
} );

// Inform react-native node is initialized.
rn_bridge.channel.send("Node was initialized.");

As soon as const IPFS = require('ipfs') is executed, the page of component SplashScreen is unloaded. Why require('ipfs') causes the component page unloading?

**Comment by achingbrain** [comment]
Your code looks correct, do you have a runnable example somewhere that replicates the problem?

**Comment by emclab** [comment]
I posted on stackoverflow with code detail. https://stackoverflow.com/questions/60049450/how-to-keep-a-component-mounted. Please let me know if you need anything else. Thanks.

**Comment by emclab** [comment]
Here is the latest code for component SplashScreen. The listener is moved into life cycle method.

import nodejs from 'nodejs-mobile-react-native';

class SplashScreen extends React.Component {

    
    _isMounted = false;
    
    state = {
        idx:1,
    };

    componentWillUnmount() {
        console.log("Unmount splash screen");
        this._isMounted = false;
        nodejs.channel.removeListener("messange");
    }

    componentDidMount() {
        this._isMounted = true;
        console.log("Nodejs obj : ", nodejs);
        nodejs.start("main.js");
        nodejs.channel.addListener(
            "message",
            (msg) => {
                alert("From node: " + msg);
                console.log("Message from nodejs : ", msg);
            },
            this
        );
    }

    render () {
        return (
            <View>
            <Button title="Message Node 1"
              //onPress={() => nodejs.channel.send('A message1!')}
              onPress={() => alert('A message1!')}
            />
            </View>
         )
    }
    
};

**Comment by emclab** [comment]
nodejs-mobile-react-native does not support win10 platform. But the module is functioning before ipfs is installed.
