### ISSUE TITLE
WebSocket Connection Error

### ISSUE THREAD

**Issue by kottackalsulvin** [ipfs/js-ipfs#2752]
Hi,
I am trying to implement a libp2p chat application. While creating a node , I got the below WebSocket connection errors:

> WebSocket connection to ‘wss://ams-1.bootstrap.libp2p.io/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd’ failed: Error during WebSocket handshake: Unexpected response code: 404

> WebSocket connection to 'wss://lon-1.bootstrap.libp2p.io/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

Here is my code:
`const SIGNAL_SERVER = ‘/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/:peer-id’`

**Environment**
Npm version: 6.13.4
Node version: 10.18.1
Os:Ubuntu 18.04
webpack : 3.11.0
libp2p-webrtc-star: 0.13.2
libp2p-websockets: 0.12.2

Anyone please help me to resolve this issue?

**Comment by hugomrdias** [comment]
Seems you are having a libp2p problem rather than a ipfs issue, do you mind opening an issue https://github.com/libp2p/js-libp2p/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc here instead ?

**Comment by alanshaw** [comment]
This seems ok. These are warnings that your IPFS node cannot connect to a couple of bootstrap peers (i.e. it is not related to the websocket star signalling server). Sometimes the bootstrap nodes are unavailable, but your node should operate normally (as long as it can connect to 1 or more of them).

If you have any further problems, please open a new issue :)
