### ISSUE TITLE
ipfs initialization takes forever

### ISSUE THREAD

**Issue by emclab** [ipfs/js-ipfs#2768]
- **Version**:0.40.0
- **Platform**:macOS Catalina
- **Subsystem**:nodes-mobile-react-native 0.5.0. Nodejs: 10.17.0, React Native 0.61.5

#### Type:

I have the following code to init ipfs (0.40.0):

// Rename this sample file to main.js to use on your project.
// The main.js file will be overwritten in updates/reinstalls.

var rn_bridge = require(‘rn-bridge’);

// Echo every message received from react-native.
rn_bridge.channel.on(‘message’, async (msg) => {
switch (msg) {
case “save”:
break;
case “retrieve”:
break;
default:
break;
};
rn_bridge.channel.send(“From node in main.js”)
const IPFS = require(‘ifps’);
const ipfs_node = await IPFS.create();
rn_bridge.channel.send("from Node version " + ipfs_node.version);

} );

// Inform react-native node is initialized.
rn_bridge.channel.send(“Node was initialized.”);

The problem is that I never seen rn_b
ridge.channel.send("from Node version " + ipfs_node.version); get executed. Why ipfs initialization takes so long? Or my code isn’t right How to check if the ipfs is initialized successfully?

**Comment by achingbrain** [comment]
IPFS uses the [debug](https://www.npmjs.com/package/debug) module to do logging - if you can get it to output the logs and paste them here it'd be helpful - either set `DEBUG=ipfs*` as an environmental variable for node-type environments or `localStorage.debug = 'ipfs*'` for browser ones.

**Comment by emclab** [comment]
A little bit more info. Type `jsipfs` in command line did generate responding output. The ipfs is installed globally and I can't make local installation work. 

Will post the log.

**Comment by emclab** [comment]
Here is a log I have:

 LOG  Nodejs obj :  {"channel": {"_currentSubscription": null, "_subscriber": {"_currentSubscription": null, "_subscriptionsForType": [Object]}, "emitLocal": [Function emit], "name": "_EVENTS_"}, "start": [Function start], "startWithScript": [Function startWithScript]}

**Comment by emclab** [comment]
I have hard time to get a debug log. But I did insert a message alert after `const IPFS = require('ipfs')` and didn't get any message. It seems to me that the require('ipfs') did not work. Here is the output of jsipfs in command line:

**Comment by emclab** [comment]
also `require.resolve('ipfs')` didn't throw error and any output. Just nothing and hung.

**Comment by emclab** [comment]
Based on my debug, I think the `ipfs` somehow is not properly installed but not sure why. The `ipfs` was installed globally without any error. But local installation of 'ipfs` failed the launch build (error about gc-stats@1.4.0)

**Comment by achingbrain** [comment]
React Native is not (yet) a supported platform for running js-IPFS - we're working on adding support over at https://github.com/ipfs/js-ipfs/issues/2813

Once that issue is resolved we'll be in a better position to debug and fix problems with IPFS running on RN, so if this problem still occurs after that is complete please re-open this issue.
