### ISSUE TITLE
webui fail open

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#2780]
- **Version**: 0.40.0
- **Platform**: windows 10
- **Subsystem**:

#### Description:

![image](https://user-images.githubusercontent.com/167966/74650358-7bbe6c00-51bc-11ea-967b-2d62a6942851.png)

when open http://127.0.0.1:5002/webui

will goto http://127.0.0.1:8080/ipfs/xxxx or http://undefined:9090/ipfs/xxxx

and all can't open

ERR_CONNECTION_REFUSED
DNS_PROBE_FINISHED_NXDOMAIN

![image](https://user-images.githubusercontent.com/167966/74650654-2040ae00-51bd-11ea-83a2-35c87336e93a.png)

**Comment by alanshaw** [comment]
@bluelovers does 0.41 resolve this issue for you? Should have been fixed in https://github.com/ipfs/js-ipfs/pull/2698

**Comment by bluelovers** [comment]
thx
