### ISSUE TITLE
webui in jsipfs didn't auto set port to 5002

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#2781]
- **Version**: ^0.41.0
- **Platform**: windows 10
- **Subsystem**:

#### Description:

webui in jsipfs didn't **auto** set port to 5002

![image](https://user-images.githubusercontent.com/167966/74654276-ed9ab380-51c4-11ea-94f2-3727cf8ae00e.png)

![image](https://user-images.githubusercontent.com/167966/74654301-fc816600-51c4-11ea-9b76-e173a64bc02e.png)

**Comment by achingbrain** [comment]
@bluelovers the API address is different for js-IPFS vs go-IPFS - as per the first line of the console output you've screenshotted, you need to put the API address into the indicated field in the web UI, like this:

![image](https://user-images.githubusercontent.com/665810/76109477-6e82e900-5fd4-11ea-805d-30d19fcb9d86.png)

Then hit submit, then maybe refresh.

**Comment by bluelovers** [comment]
i mean auto fallback to 5002 when 5001 can't link

**Comment by achingbrain** [comment]
You are quite correct, the user experience here could be a lot smoother.  Could you open an issue on https://github.com/ipfs-shipyard/ipfs-webui please?

**Comment by bluelovers** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/issues/1412
