### ISSUE TITLE
Downgrade `@hapi/ammo` to v3

### ISSUE THREAD

**Issue by Gudahtt** [ipfs/js-ipfs#2782]
This project uses `@happi/ammo` version 4.0.0, which [is not supported and was published by mistake](https://github.com/hapijs/ammo/issues/38#issuecomment-587210588). 

This project should downgrade to v3.0.0, which is still actively maintained, or upgrade to v5.0.0 if you don't mind dropping support for Node.js <v12

**Comment by kumavis** [comment]
looks like it was just greenkeeper https://github.com/ipfs/js-ipfs/pull/2538

**Comment by kumavis** [comment]
motivation:
> v4.0.1 is listed on npm as deprecated, and is listed as vulnerable on this advisory: https://www.npmjs.com/advisories/1474

**Comment by sebastiendan** [comment]
I still get the wrong `@happi/ammo` version when installing the latest `ipfs` npm version (0.41.1).
See my package-lock below:

```
"ipfs": {
      "version": "0.41.1",
      "resolved": "https://registry.npmjs.org/ipfs/-/ipfs-0.41.1.tgz",
      "integrity": "sha512-5UI0WFh7eD2J+niMNrVYOFmUH2bL0iN4VXlVWMnsHyD7qZ6IPqgr7cFa1Z+udpZkQu6uLEcxnHjXyB2XmiibIg==",
      "requires": {
        "@hapi/ammo": "^4.0.0",
```

**Comment by achingbrain** [comment]
The downgrade has not been published yet - we'll hopefully get something out in the next day or two.

**Comment by achingbrain** [comment]
Please try `ipfs@0.41.2`, it should have the ammo downgrade in it.

**Comment by sebastiendan** [comment]
I confirm `ipfs@0.41.2` contains the `@hapi/ammo` downgrade 👍
