### ISSUE TITLE
HTTP query args camelCase not kebab-case

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2802]
Convention in the HTTP API is kebab case query args. I was looking at `mkdir.js` and noticed `mtimeNsecs` is camel case not kebab case. In that same file we have `cidVersion` and `hashAlg` which should be `cid-version` and `hash` according to https://docs.ipfs.io/reference/api/http/#api-v0-files-mkdir

https://github.com/ipfs/js-ipfs-mfs/blob/c7fa4d75d1d72609b5dcfd2863bec43bdc27b105/src/http/mkdir.js#L47-L53

There's other instances where this is happening, `touch.js` for example, so we should check all the HTTP API methods just incase!

**Comment by hugomrdias** [comment]
@achingbrain did we fixed all of these in the cancellable api PR?

i think we did https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/http/api/resources/files/mkdir.js#L32-L51

**Comment by achingbrain** [comment]
Yes, these should all be fixed now.
