### ISSUE TITLE
urlSource.options is ignored

### ISSUE THREAD

**Issue by mariotaku** [ipfs/js-ipfs#2807]
https://github.com/ipfs/js-ipfs-utils/blob/e582304334584c2c076ee87a85063f6e0dd7c740/src/files/url-source.js#L9

Should this `options` to be passed to `ky.get(url, options)`?

**Comment by achingbrain** [comment]
This is blocked on https://github.com/ipfs/js-ipfs/pull/2810

**Comment by jacobheun** [comment]
The latest version of js-ipfs-utils now passes the options, this should no longer be an issue.
