### ISSUE TITLE
Invalid multiaddr: /dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star

### ISSUE THREAD

**Issue by hazae41** [ipfs/js-ipfs#2812]
When using IPFS.create it throws

    Invalid multiaddr: /dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star

at cleanUrlSIO() from file utils.js:12 from module libp2p-webrtc-star

Is it normal?

**Comment by achingbrain** [comment]
The signalling server apps running behind https://star-signal.cloud.ipfs.team/wss/p2p-webrtc-star are sometimes down.

In the short term you could stand up your own [webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star) instance and use that to connect?

In the medium term, @vasco-santos is finishing a refactor of https://github.com/libp2p/js-libp2p-stardust/pull/14 which will be deployed in place of the servers above and will be more reliable/available - please subscribe to that issue for updates.
