### ISSUE TITLE
Reduce js-ipfs* packages size

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#2828]
todo:

- [ ] review what is publish to npm in all repos ipfs, libp2p, multiformats, etc (only include dist and src)
- [ ] reduce `dist` folder by not publishing sourcemaps and un-minified bundles 

Related
https://github.com/ipfs/js-ipfs/issues/2550

**Comment by mikeal** [comment]
Keep me in the loop on what your primary sources of your package sizes are.

We have some work we need to do in the new IPLD `Block` interface that is meant to, optionally, reduce the codecs and hashing functions included to only those that are provided. This work hasn’t been prioritized but if this ends up being a large contributor to your package size I can prioritize it and work with you to migrate to the new `Block` interface.

**Comment by hugomrdias** [comment]
This is mostly done everywhere, with some aegir changes.
