### ISSUE TITLE
mtime and mtime-nsecs multipart headers not sent in browser

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2837]
The [code here](https://github.com/ipfs/js-ipfs-http-client/blob/master/src/add/form-data.browser.js#L37-L39) essentially is doing the following:

```js
const formData = new FormData()
formData.append(
  'file',
  new Blob([], {type: 'application/octet-stream'}),
  'file/path',
  {header:{mtime:5}}
)

const req = new Request('/test', { method: 'post', body: formData })
await req.text()
```

Output (tested in Firefox and Chrome):

```
"-----------------------------227935052110062039083523745638
Content-Disposition: form-data; name=\"file\"; filename=\"file/path\"
Content-Type: application/octet-stream

-----------------------------227935052110062039083523745638--
"
```

Missing `mtime` header. Worryingly, as far as I can see, there's no way to set custom multipart headers using the APIs we have in the browser.

The `form-data` module supports `header` so it's working in Node.js:

https://github.com/form-data/form-data/blob/d7026253e728af9568503dc3dc55cd1a566605e0/lib/form_data.js#L181-L191

Tests for metadata are skipped here since go-ipfs does not support this feature and the tests that use `js-ipfs-http-client` in `js-ipfs` are run from Node.js. This is why we haven't seen failing tests for it.

Maybe we need to test against js-ipfs too, if js-ipfs is going to support features like this before go-ipfs in the future.

I'm not sure how this comment got resolved, I thought I was getting déjà vu! https://github.com/ipfs/js-ipfs-http-client/pull/1186#discussion_r354911143

**Comment by alanshaw** [comment]
@achingbrain does https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/lib/multipart-request.js solve this issue?

**Comment by achingbrain** [comment]
Yes, we're sending mtime etc headers, now, phew.

> Maybe we need to test against js-ipfs too, if js-ipfs is going to support features like this before go-ipfs in the future.

I've added this: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/package.json#L47 so we should catch this sort of thing in future.
