### ISSUE TITLE
Provide typescript type definitions

### ISSUE THREAD

**Issue by rklaehn** [ipfs/js-ipfs#2839]
This would be extremely helpful. I have worked with both flow and typescript. Flow has some theoretical advantages, but typescript has way better tooling support and mindshare, which is why I reluctantly switched to typescript.

Please provide typescript type definitions just for the API. That would be extremely helpful.

**Comment by mfsoftworks** [comment]
> We made typescript support a priority for the next months I'll personally be working on this and would love some help and feedback from you all.
> 
> My primary objective is to find the best way to provide accurate and up to date type definitions. It's really important to not make types generation a big burden so we can keep it always in sync with the code.
> 
> We want a long term solution to provide the best support for the typescript community.
> 
> I have a couple of ideas to do this but I'm gonna need your help to make this work.
> 
> What is the best way to validate that type definitions are accurate? Is `tsc --no-emit` enough? Do we need type definitions tests to actually be useful?

Any progress or ETA? 
I just published a [library](https://www.npmjs.com/package/@mfsoftworks/nestjs-ipfs) for IPFS usage in [NestJS](https://nestjs.com) typescript framework for node.js, so this would be extremely useful

**Comment by hugomrdias** [comment]
its in progress, will happen soon.

**Comment by sr229** [comment]
Can we get an ETA? This has been a blocker for our project and it would be nice if we could get some progress right now.

**Comment by achingbrain** [comment]
This is a high priority item on @hugomrdias's list for this quarter - please follow https://github.com/ipfs/js-ipfs/issues/2945 for updates.

**Comment by hugomrdias** [comment]
Closing this one in favor of https://github.com/ipfs/js-ipfs/issues/2945

Thanks you all 🙏
