### ISSUE TITLE
Missing Stream API causes problems in ReactNative

### ISSUE THREAD

**Issue by oed** [ipfs/js-ipfs#2840]
I'm trying to get the **ipfs-http-client** running in **react-native**, but ran into an issue I wasn't able to easily solve. The problem stems from that the [iso-stream-http](https://github.com/hugomrdias/iso-stream-http) uses the **fetch stream API**, which seems to be available in browsers, but is not in the RN implementation of fetch. 

**The problem** is outlined in [this stackoverflow post](https://stackoverflow.com/questions/56207968/stream-api-with-fetch-in-a-react-native-app). It also seems that the RN team is not very interested in adding support for this. 

I've tried **various fetch replacements**, but none of the seem to support the stream api. Now I'm wondering what the next step could be? Is there some other way around this perhaps? Happy to hear suggestions 🙂

**Comment by pcowgill** [comment]
Thanks for transferring this issue. I think that's a great way to handle open issues now that most of the packages are moving into the `js-ipfs` monorepo.

<img width="248" alt="Screenshot 2020-03-09 15 32 10" src="https://user-images.githubusercontent.com/2731712/76254872-2f92a480-621b-11ea-927c-13749f358b07.png">

For those following this issue for the state of using `ipfs` in React Native, I posted an update on the state of progress on that here:
https://github.com/ipfs/js-ipfs/issues/2813#issuecomment-595018743

**Comment by hugomrdias** [comment]
Closing this one in favor of https://github.com/ipfs/js-ipfs/issues/2813

Thanks you all 🙏
