### ISSUE TITLE
Support js-ipfs-http-client use in React Native env

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2846]
This would involve adding a `react-native` field in the `package.json` equivalent to the `browser` one that already is in there and ensuring that the appropriate react-native-compatible implementations of node core modules are used.

The list of react-native compatible versions can be found [here](https://github.com/tradle/rn-nodeify/blob/master/shims.js) and/or [here](https://github.com/parshap/node-libs-react-native#modules).

It would also involve only using 3rd party deps that also have these criteria met when in a React Native env.

There's [a more specific issue](https://github.com/ipfs/js-ipfs-http-client/issues/1117) about a particular problem one runs into using this lib in a React Native env, but this issue is about the more general need for React Native support, so it should persist even if that issue gets resolved first.

This is a complementary issue to [the one over in the `aegir` repo](https://github.com/ipfs/aegir/issues/437).

**Comment by achingbrain** [comment]
Will be fixed by https://github.com/ipfs/js-ipfs/issues/2813

**Comment by pcowgill** [comment]
I'll close this issue and we can track this issue in the newer one @achingbrain linked to.
