### ISSUE TITLE
Feature detect streaming and fall back to regular request/response reading if not available

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2848]
Feature detect streaming and fall back to regular request/response reading if not available.

This would involve using a helper lib with the response that handles the case where `res.body` is undefined and instead parses the JSON from a vanilla, non-streaming response and transforms it to an iterable in another way rather than through `toIterable`, which assumes a `ReadableStream` from the `fetch` spec as an input.

React Native is one such environment where `res.body` is undefined.

In the long run, hopefully React Native will implement a spec-compatible `fetch` natively rather than using a polyfill on top of XHR, but in the meantime it would be nice not to gate potential users of this lib.

Related discussion here https://github.com/github/fetch/issues/746#issuecomment-573251497 cc @MattiasBuelens

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

I believe this issue should be resolved in Helia.
