### ISSUE TITLE
Windows install missing dependancy

### ISSUE THREAD

**Issue by MasterJames** [ipfs/js-ipfs#285]
Running jsipfs triggered 

`error   Cannot find module 'ipfs-unixfs'`

until manually running 

`npm install -g ipfs-unixfs`

as well.

Just thinking that it should be a dependency when installing ipfs on windows. no?

**Comment by diasdavid** [comment]
@MasterJames Are you using npm 2 or 3 to install js-ipfs? You will need npm 3 (`npm i npm -g`)

**Comment by MasterJames** [comment]
Great it actually won't work properly otherwise.
Was 2? now 3.9.3! Seems working better I could add a file but no init results ;-(
