### ISSUE TITLE
Responses aren't always compatible between different IPFS HTTP API libraries

### ISSUE THREAD

**Issue by bonedaddy** [ipfs/js-ipfs#2851]
# Version Information

I have confirmed this behaviour in different environments both on a local development environment, and a remote development environment. 

IPFS (local):
```
go-ipfs version: 0.4.19-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.5
```

IPFS (remote)
```
go-ipfs version: 0.4.19-83d3f7672
Repo version: 7
System version: amd64/linux
Golang version: go1.12
```
js-ipfs-http-client:
```
ipfs-http-client@30.1.1
```

# Issue

Currently I'm working on writing an IPFS HTTP API reverse proxy server with caching enabled. To test reverse proxy I'm using a [fork](https://github.com/RTradeLtd/go-ipfs-api) of `go-ipfs-api`, the `curl` command (aka, submitting IPFS HTTP API queries via curl), and the `js-ipfs-http-client` library contained in this repository.

What I'm starting to notice is that cached responses returned to `go-ipfs-api`, and  `curl` aren't always backwards compatible with the responses that `js-ipfs-http-client` expects to be received, or how it handles the responses. But cached responses for `js-ipfs-http-client` are compatible with responses expected by `go-ipfs-api` and by `curl`. 

[This](https://gist.github.com/postables/40f5ac95ef65d135e717318f77e6a937) gist contains an example of the error that is generated by `js-ipfs-http-client` when processing a `pin/add` request whose answer is returned from cache. [This](https://gist.github.com/postables/05c749af3f1eac259cb571a076923a10) gist contains an error when serving a response from cache for `dag/get`.

This issue doesn't seem to be present across all requests, and so far I have isolated it to the following calls:

```
		"add"
		"block/put"
		"dag/put"
		"dag/resolve"
                "dag/get"
		"pin/add"
```

**Comment by achingbrain** [comment]
There are a lot of variables that can cause the response format to vary - turning on streaming, for example will result in ndjson being sent instead of a single list of entities.  Some of these are turned on by default in `ipfs-http-client` to simplify the code and to provide a better experience to the user.

Consequently I don't think it's a reasonable expectation to reply responses to requests sent to one client to another.
