### ISSUE TITLE
Filestore support with --nocopy

### ISSUE THREAD

**Issue by obo20** [ipfs/js-ipfs#2852]
Currently there's no way to utilize the IPFS filestore functionality.

I've seen a few other issues related to this:
https://github.com/ipfs/js-ipfs-http-client/pull/843
https://github.com/ipfs/js-ipfs-http-client/pull/564

They all still seem to be "WIP"

I'd really love to have this functionality available if possible. Is there anything that's preventing either of the approaches seen in those two issues from being implemented?

I can look into attempting a PR myself, I just don't want to be reinventing the wheel if the other two approaches would work.

**Comment by autonome** [comment]
Triaged, still a valid request. Not a priority, but would take a PR. If this is a priority for you, share your thoughts on why!
