### ISSUE TITLE
'webpack-dev-server' error

### ISSUE THREAD

**Issue by anarkrypto** [ipfs/js-ipfs#2855]
- npm 6.9.0
-  node v12.4.0
- Ubuntu 18.04 

**_~/js-ipfs-http-client/examples/upload-file-via-browser$ npm install_**

npm WARN upload-file-via-browser@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 9304 packages in 2.807s
found 0 vulnerabilities

_**$npm start**_

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! upload-file-via-browser@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upload-file-via-browser@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2019-06-06T07_44_53_983Z-debug.log](https://github.com/ipfs/js-ipfs-http-client/files/3260506/2019-06-06T07_44_53_983Z-debug.log)

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

If you are still having problems with webpack I'd suggest taking a look at the Helia/webpack example - it has all you need to get started - https://github.com/ipfs-examples/helia-webpack
