### ISSUE TITLE
add --nocopy not supported

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/js-ipfs#2856]
Hi,

I'm trying to use the --nocopy option of the filestore through js-ipfs-api but files added this way are stored in the regular blockstore. After a lot of digging I think it's due to how the file is streamed in the http request:

Capture of the multipart/form-data of a request made with the CLI:
```
 --35471fb491711d32f7a9885e488899d24c6483bd528959cb002c6a6e32b5 
 Abspath: /home/michael/go/src/gx/ipfs/QmaeRR9SpXumU5tYLRkq6x6pfMe8qKzxn4ujBpsTJ2zQG7/go-os-rename/README.md 
 Content-Disposition: file; filename="README.md" 
 Content-Type: application/octet-stream 
  
 # go-os-rename
 ...
```

Capture of the multipart/form-data of a request made with js-ipfs-api:
```
--6ezi3e1udjdvx3sly5t01i3sor 
Content-Disposition: file; filename="README.md" 
Content-Type: application/octet-stream 
 
# go-os-rename
```

The absolute path is missing, so my guess is that the filestore can't file the file on disk and the data is then stored in the regular blockstore. Bad things is that happen silently ...

CC @kevina, is that correct ?

**Comment by autonome** [comment]
Triaged, still a valid request. Not a priority, but would take a PR. If this is a priority for you, share your thoughts on why!

**Comment by achingbrain** [comment]
Closing due to lack of response.

**Comment by markg85** [comment]
Could this be reopened.
I'm adding large files in IPFS and want to keep them as local files. I therefore use `--nocopy` on the command line, which works.
In js-ipfs this options doesn't seem to exist.
