### ISSUE TITLE
Cancellable api request

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/js-ipfs#2862]
Hi,

Is there a way to cancel a request ?

In particular, I'm doing some `ipfs pin add` to trigger a download but the request stay active until completion. There is cases where I no longer want to complete the download. How can I do that ?

Thank you

**Comment by hugomrdias** [comment]
This PR https://github.com/ipfs/js-ipfs/pull/2993 adds this feature.

🙏  Thank you for your input.
