### ISSUE TITLE
Streaming versions of ipfs.files.add buffer entire data in memory before doing HTTP POST

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2863]
```
ipfs.files.addPullStream([options])
ipfs.files.addReadableStream([options])
```

## Problem Summary

As noted [here](https://github.com/ipfs-shipyard/ipfs-webui/issues/762#issuecomment-416879542) streaming over HTTP does not work the way people expect: it ends before HTTP transport and entire thing is buffered in memory before HTTP POST is called with contents of the buffer. 

This means when HTTP POST is sent to `/api/v0/add` browser has entire payload in memory.
Streaming of huge files is impossible over HTTP.

This is bad because:
- breaks progress reporting (https://github.com/ipfs/js-ipfs-api/issues/748)
  (0% until entire thing is received by remote server, then 100% instantly)
- web browsers crash (https://github.com/ipfs/js-ipfs-api/issues/654)
  or return silent errors due to increased  memory allocation
  (https://github.com/ipfs-shipyard/ipfs-companion/issues/464#issuecomment-382446114)

### Option A: Streams API

Use a `fetch` call with  [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API).
Looks like something that will be possible in the future, step 10 from [fetch.spec](https://fetch.spec.whatwg.org/#concept-http-network-fetch) mentions  `ReadableStream`

Blocked missing vendor support (https://caniuse.com/#feat=streams)
  - Chrome: No support for BYOB ("bring your own buffer") stream readers
  - Firefox: No support for [`WritableStream`](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream)

### Option B: Poor Man's Streaming

We could buffer up to a point and then send a chunk as a separate POST call to HTTP API.
Implementation may get ugly very fast, requires increasing complexity of go-ipfs. 

### Option C: (?)

(?)

## Related Issues

cc https://github.com/ipfs/js-ipfs-api/issues/654, https://github.com/ipfs/js-ipfs-api/issues/788, https://github.com/ipfs/js-ipfs-api/issues/748, https://github.com/ipfs-shipyard/ipfs-companion/issues/464

**Comment by thienpow** [comment]
<img width="1040" alt="Screenshot 2020-07-06 at 3 36 11 AM" src="https://user-images.githubusercontent.com/9796623/86540704-faccfa80-bf39-11ea-8ec0-418ad210891c.png">

looks like a particular problem of Chromium based browser having this problem. Safari is ok to upload bigger than 150mb.

**Comment by lidel** [comment]
I believe this was fixed by @Gozala in https://github.com/ipfs/js-ipfs/pull/3184
