### ISSUE TITLE
Problems with adding files over 15MB with progress handler

### ISSUE THREAD

**Issue by salamantos** [ipfs/js-ipfs#2866]
I tried to create progress bar to my file uploading. I used this code:
```
let progress_func_video = function (len) { 
    console.log("video progress:", len); 
}; 
ipfs.files.add(files_video, {progress: progress_func_video}, (err, result) => {...}
```

When I upload 1MB files, it's ok, but on 30MB files I got this error in Chrome:
```
POST https://site.com:81/api/v0/add?progress=true&stream-channels=true net::ERR_INCOMPLETE_CHUNKED_ENCODING
Uncaught (in promise) TypeError: network error at new exports.IncomingMessage (response.js?99b5:67) at module.exports.ClientRequest._connect (request.js?af32:259) at eval (request.js?af32:157)
```

How to fix it?

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can follow the migration plan here https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

If the remote node you are talking to is Kubo, please switch out `ipfs-http-client` for `kubo-rpc-client` - it is a drop-in replacement and is where bug fixes and features will land going forwards.

If the remote node is js, please convert your app to Helia!
