### ISSUE TITLE
Error: multihash too short. must be > 3 bytes.

### ISSUE THREAD

**Issue by obo20** [ipfs/js-ipfs#2867]
If you submit a request to get a file using ipfs.files.cat, and you have a hash that is greater than 3 bytes, you still get the error message: "Error: multihash too short. must be > 3 bytes."

For example:

`ipfs.files.cat(/ipfs/QmUzdHisA7ouM8DM5rVAKursVK7t7tKeqDYGvmaCdJw5jEeesdlfjsldkfjsldkfjsdlkfjskldfj` will return that error message

**Comment by achingbrain** [comment]
Calling 

```js
await all(ipfs.cat('/ipfs/QmUzdHisA7ouM8DM5rVAKursVK7t7tKeqDYGvmaCdJw5jEeesdlfjsldkfjsldkfjsdlkfjskldfj'))
```

now fails with

```
Error: invalid character 'l' in 'QmUzdHisA7ouM8DM5rVAKursVK7t7tKeqDYGvmaCdJw5jEeesdlfjsldkfjsldkfjsdlkfjskldfj'
```

so the error message is at least less cryptic than it used to be.

If a more descriptive error message is desired, a PR should be opened against [multiformats/js-cid](https://github.com/multiformats/js-cid) as that's where the string is [turned into a CID](https://github.com/multiformats/js-cid/blob/master/src/index.js#L75-L94).
