### ISSUE TITLE
Handle cases where http responses have no body with a getter for a ReadableStream

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2871]
Creating a new issue for this issue https://github.com/ipfs/js-ipfs-http-client/pull/1224 now that the old repo is archived.

@hugomrdias When you said this https://github.com/ipfs/js-ipfs-http-client/pull/1224#issuecomment-596709785, which repo did you mean that the PR belongs in? Thanks!

**Comment by achingbrain** [comment]
> ipfs/js-ipfs-http-client#1224 (comment) this needs to be patched in react-native not here

From https://github.com/ipfs/js-ipfs/issues/2813

**Comment by pcowgill** [comment]
@achingbrain Just added a response to that comment here https://github.com/ipfs/js-ipfs/issues/2813#issuecomment-596764105

**Comment by pcowgill** [comment]
We can close this issue though, because it's already covered by https://github.com/ipfs/js-ipfs/issues/2847.

I hadn't seen that you transferred it from the old repo before.
