### ISSUE TITLE
Move ipfs interface methods into a subdir in ipfs-http-client src dir

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2872]
Consider moving ipfs interface methods into a subdir (maybe called `methods`?) in the `ipfs-http-client` `src` directory. That way it will be clear that dirs like `add` and `dag` are logically grouped together in a way that the `lib` dir isn't.

**Comment by pcowgill** [comment]
<img width="264" alt="Screenshot 2020-03-09 14 49 21" src="https://user-images.githubusercontent.com/2731712/76251688-78475f00-6215-11ea-8654-f2b4184f3375.png">

**Comment by achingbrain** [comment]
Thanks for the suggestion. The folder layout is ok for now.
