### ISSUE TITLE
Activate dependabot for this repo 

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2875]
Since the `greenkeeper` PRs are building up and aren't proving to be very helpful, it might be worth considering switching from greenkeeper to a combo of [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates) and automated security alerts from GitHub.

**Comment by hugomrdias** [comment]
We should probably should use dependabot now. 
Gonna change the title for better visibility .

**Comment by achingbrain** [comment]
Done!
