### ISSUE TITLE
ipfs.version(): include version of JS API 

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2878]
In JS land interface-js-ipfs-core is effectively the API.

Unfortunately, unless I know what version of js-ipfs-http-client was used, there is no way to tell what type of JS API (interface-js-ipfs-core) I will get.

I propose we add it to the output of `ipfs.version()`
For example, js-ipfs-http-client connected to go-ipfs would return:

```js
$ await ipfsCompanion.ipfs.version()
{
  commit: "6ce9a35",
  golang: "go1.12.16",
  repo: "7",
  system: "amd64/linux",
  version: "0.4.23",
  jsinterface: "v0.132.0"
​}
```

That way context where  js-ipfs or js-ipfs-http-client versions are unknown (example: https://github.com/ipfs-shipyard/ipfs-companion/issues/852) it is possible to inspect it and make decisions at the runtime.

Knowing `jsinterface` version one could decide to fallback to something more modern, or change  the way the output of  `ipfs.cat` is handled (Uint8Array vs AsyncIterable).

Does this sound ok? Any reason to not do this?

**Comment by achingbrain** [comment]
Sounds good to me, though perhaps better added to the output of the [`ipfs.id()`](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/SPEC/MISCELLANEOUS.md#id) interface call?
