### ISSUE TITLE
A way to sign things using IPFS keys

### ISSUE THREAD

**Issue by mitar** [ipfs/js-ipfs#2880]
So each peer has its own key (and optional additional keys), but it seems there is no API which would allow one to sign messages using those keys (except by storing them inside IPNS).

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

@achingbrain this sounds like something we should probably support in Helia. I'm not sure if it's already there, so assigning to you for either migrating this issue, creating new Helia specific issue for signing messages using keys in helia, or telling us it's already possible!

**Comment by achingbrain** [comment]
When you export a key from the libp2p keychain you can access the raw public/private keys so this is possible without an API change.

Closing as completed 👍
