### ISSUE TITLE
Key import/export  as PEM (interop with go-ipfs 0.13+)

### ISSUE THREAD

**Issue by Stebalien** [ipfs/js-ipfs#2887]
https://github.com/ipfs/interface-js-ipfs-core/blob/v0.103.0/SPEC/KEY.md#keyimport

However, libp2p uses a custom format that may or may not be convertible to PEM.

**Comment by DougAnderson444** [comment]
I'm interested in seeing this implemented for sure! We should be able to store any key type on the keychain, not just rsa-pem, right?

> js-```ipfs.key.import``` comes from [keychain.importKey](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/core/components/key/import.js)

> [keychain.importKey](https://github.com/libp2p/js-libp2p-keychain/blob/9e96dbc50f19b4f3912216f973e36be0d7d3596d/src/keychain.js#L391) calls ```crypto.keys.import(pem, password)``` which [only processes RSA pem](https://github.com/libp2p/js-libp2p-crypto/blob/75d250c87655a6a353ab32b28791227f1251d921/src/keys/index.js#L112) at the moment.

I see ```crypto.keys.unmarshallPrivateKey(buf)``` already decodes the key type then returns the key based on type. We just need import to leverage this heavy lifting right?  

What we could do is

- [ ] rename ```crypto.keys.import(pem, password)```  to ```(privateKey, password)``` 
- [ ] ```crypto.keys.import(privateKey, password)``` determines which key type is given, based on length
- [ ] if there is a password and it's RSA, then ```decryptRsaPrivateKey``` as before
- [ ] perhaps add a symmetrical password cipher for the other two key types (pbkdf2 + AES?)
- [ ] based on which key type, convert ```string``` to ```buf``` for ```crypto.keys.unmarshallPrivateKey```
- [ ] ```crypto.keys.unmarshallPrivateKey``` returns the appropriate key bytes, just like ```import``` did

Does that seem about right? 
Anything I can do to help implement this change?

**Comment by DougAnderson444** [comment]
Ongoing discussion about this also here https://github.com/libp2p/js-libp2p-crypto/issues/145

**Comment by lidel** [comment]
Update:
- go-ipfs 0.13+ will support cleartext PEM format for improved interop – see https://github.com/ipfs/go-ipfs/pull/8616
- filled https://github.com/libp2p/js-libp2p-crypto/issues/244 as the first step towards supporting the same in js-ipfs

**Comment by tinytb** [comment]
backlog grooming: this will be tracked in https://github.com/libp2p/js-libp2p-crypto/issues/244 going forward
