### ISSUE TITLE
Mention implementation level for each spec item?

### ISSUE THREAD

**Issue by andrew** [ipfs/js-ipfs#2889]
I've been slowly getting up to speed with IPFS whilst playing around with js-ipfs. I ran into an issue where the DHT parts aren't fully implemented in js-ipfs (thanks for the heads up @achingbrain).

The docs are slightly confusing [here](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/DHT.md#dhtfindprovs) as it appears that the JS implementation is there but the Go one is WIP, but as I understand it it's actually the other way around.

It would be very handy to have some kind of warning at the top of `SPEC/DHT.md` that mentions that the js implementation isn't fully implemented yet.

This might not be the best repo to describe the completeness of an implementation but it's where I naturally found myself when searching for information on those interaces.

**Comment by achingbrain** [comment]
We have interface tests for every feature - when they are executed in the `ipfs-http-client` package they are run against go-ipfs, when it's done from the `ipfs` package they run against js-ipfs.

Some tests are skipped depending on the tested implementation - it would be really cool to be able to use those skips to determine what's implemented by which version.

There are plans afoot to add typescript comments throughout the API and to generate docs from them (replacing the interface-core SPEC folder, hopefully) - with the combination of the two we could have some really great evergreen information in our docs.

Is this something you can help with?

**Comment by andrew** [comment]
@achingbrain it's not something that I'm really able to help with directly

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

@andrew  @achingbrain  It would be nice if there were a collection of features that we can ensure exist in the DHT implementation for Helia

**Comment by achingbrain** [comment]
I'm a little confused, the `@libp2p/kad-dht` implementation is feature complete, though it wasn't at the time this issue was opened.
