### ISSUE TITLE
DHT put any value?

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2893]
https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DHT.md#put

Does it need to be clarified - any value? Does it mean any primitive? Buffers? Can I store DOM elements in there? 😛

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
