### ISSUE TITLE
Add a restart method to allow config updates to be applied via api

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#2895]
The api allows for the node config to be changed via [`config.set`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/CONFIG.md#configset) and [`config.replace`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/CONFIG.md#configreplace) and for stopping of the daemon process via [`stop`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/MISCELLANEOUS.md#stop) but there is no way to start or reload the service. To get config changes applied you must have some mechanism to restart the node.

A `restart` method would allow the user to make config changes via webui and have them by applied by stopping and restarting the service.

For bonus points `nginx` provides a `reload` command that allows the user to apply the config without stopping the service.

**Comment by ThomasFreedman** [comment]
Apparently this feature is a very low priority.

**Comment by achingbrain** [comment]
Closing as not planned.
