### ISSUE TITLE
Add a "key" flag to the "name.resolve" command

### ISSUE THREAD

**Issue by Stebalien** [ipfs/js-ipfs#2897]
Currently, `ipfs.name.resolve` resolves IPNS paths. At one point, there was some grumbling about supporting keys by *name* (https://github.com/ipfs/go-ipfs/issues/3900). @overbool has volunteered to implement this but this is an addition to a CoreAPI command so it should probably be discussed here first.

Alternatives:

1. Add an `ipfs key show` command that prints out the hash of the key. Users would then call `ipfs name resolve /ipns/$(ipfs key show MyKey)`.
2. Add a `-k` flag: `ipfs name resolve -k MyKey`.
3. Support resolving directly: `ipfs name resolve MyKey`.
---
1. Is the most conservative (don't touch the resolve command).
2. Is a reasonable compromise (although it feels like mixing concerns a bit).
3. Is ambiguous although @whyrusleeping seems to think it presents a nicer UX.

**Comment by jakehemmerle** [comment]
Is this ticket good to go with option 3?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).
