### ISSUE TITLE
FUSE on Windows via dokany okay?

### ISSUE THREAD

**Issue by MasterJames** [ipfs/js-ipfs#290]
I wondered if I can use the new 1.0.0-RC3 from
https://github.com/dokan-dev/dokany/releases
to get FUSE working safely with the GO version on Windows?

**Comment by MasterJames** [comment]
I think this belongs in the Go version, sorry.
https://github.com/ipfs/go-ipfs/issues/2766

**Comment by RichardLitt** [comment]
No worries! Thanks for reopening there.
