### ISSUE TITLE
Standardizing test formats

### ISSUE THREAD

**Issue by travisperson** [ipfs/js-ipfs#2903]
To help reduce some test complexity I want to propose some patterns that I think might help clean up a lot of the tests and make things a bit easier to read and work through.

Here is a gist that shows a bit more of this in code 
https://gist.github.com/travisperson/878610af9c4b3608e36323da191625d1

### Standard the naming convention of ipfs interfaces objects

Its easier to read and understand tests if they references the same kind of objects the same way.

* In single instance contexts the variables `ipfs` should be used.
* In multi instance contexts the variables `ipfsA`, `ipfsB`, `ipfsC`, etc should be used.

The alpha suffix seems to be the way recent tests have beeen written and I think we should standardize around this pattern. There are only a handful of places that need to be fixed.

**Areas of interest**

* `pubsub/peers.js`
* `pubsub/subscribe.js`
* `swarm/peers.js`
* `dht/get.js`
* `dht/findpeer.js`
* `dht/query.js`
* `dht/findprovs.js`

### Using `done` vs `expect` when dealing with errors

When using `done` to check errors, it requires a conditional check which takes up three lines if expand with braces. Usually this is reduced down to a single line. However, I believe using `expect` just looks cleaner

```js
if (err) {
  return done(err)
}

if (err) return done(err)

expect(err).to.not.exist()
```

* Use `expect` when working with errors
* `done` should only be used to signal async completetion
* `done` may also be passed directly as a callback for simplicity

Example
```js
before(done => ipfs.files.add(fixture.smallfile.content, done))

// Note: this test should probably also verify that the disconnect occurred, so semi bad example
it('should disconnect from a peer', (done) => {
  ipfsA.swarm.disconnect(ipfsB.peerId.addresses[0], done)
})
```

### Put fixture objects in their own file `fixtures.js`

Currently almost all fixture objects resides inside of a `utils.js`. Its not immediately clear that fixture data would be in the file. Generally a `utils` contains kitchen sink functions, placing fixture objects in their own file makes it easy to find and suites the purpose better.

### Keep instance setup simple and separate from other test setup

Getting instances really doesn't change much, most of the time it's code that can be glanced over and ignored. However, when other test setup is introduced into this section, more code is required to be parsed on behalf of the read. Placing additional setup in another `before` block will reduce the complexity and make things easier to read.

* The first `before` block should only be used to get ipfs instances
* Connecting should take place in another before
* Adding fixture data should also be separate

_Note: see **getNodes** below_
```js
let ipfsA
let ipfsB
let ipfsC

before('setup', getNodesWithId(3, common, nodes => {
  [ipfsA, ipfsB, ipfsC] = nodes
}))

// A pair of ipfs nodes can easily connected together with `connectNodes`.
before('connect', function(done) {
  parallel([
    (cb) => connectNodes(ipfsA, ipfsB, cb),
    (cb) => connectNodes(ipfsA, ipfsC, cb),
    (cb) => connectNodes(ipfsB, ipfsC, cb),
    (cb) => ipfsA.files.add(fixture.smallfile.content, cb)
  ], done)
})

before(done => ipfs.files.add(fixture.smallfile.content, done))
```

### Keep test setup close to the tests that they are used by

Instead of having a large setup at the top of the file that runs through and does everything in a single `before`, write out a few `before` blocks and place them next to the test using the setup it performs.

The `before` blocks already run in the order they are defined, so they act just like `async/serial`.

**Areas of interest**

* `dag/get.js`
* `dag/tree.js`

### Move test setup outside of the tests

When dealing with `get` like operations, we always see an accompanied `put` wrapped around it to do test setup. Moving the setup outside of the test help highlight what is actually under test. It also helps differentiate between failures. With setup inside of tests it's not immediate clear what actually failed.

**Areas of interest**

* `object/get.js`

### New helper methods to help reduce code duplication

**getNodes**

One of the most common setups we have looks like this

```js
let ipfs

before(function (done) {
  this.timeout(60 * 1000)
  common.setup((err, factory) => {
    expect(err).to.not.exist()
    factory.spawnNode((err, node) => {
      expect(err).to.not.exist()
      ipfs = node
      done()
    })
  })
})
```

I think this can be greatly simplified down quite a bit. Most tests do not use the `factory` outside of the `before` hook, nor do they pass any additional options / arguments to `spawnNode`. This builds off of the `utils/spawn.js` functions introduced in the latest refactor by @alanshaw. I think we can remove this repetitive code, and make single instance and multi instance setup simpler. 

```js
let ipfs

before('setup', getNodes(1, common, nodes => {
  [ipfs] = nodes
}))
```

A variant of `WithId` for multi instance as well to help with connecting. A lot of tests don't need the peerId, so I wouldn't include it by default.

```js
let ipfsA
let ipfsB
let ipfsC

before('setup', getNodesWithId(3, common, nodes => {
  [ipfsA, ipfsB, ipfsC] = nodes
}))
```

**connectNodes**

The way swarms are connect differ a bit through out the code base, some will select the first address, others will search for an address which is listening on `127.0.0.1`. Selecting the first address may not be the best idea. Making sure nodes always connect over the loopback probably is the safest. This function will help keep that simple.

```js
before('connect', function(done) {
  parallel([
    (cb) => connectNodes(ipfsA, ipfsB, cb),
    (cb) => connectNodes(ipfsA, ipfsC, cb),
    (cb) => connectNodes(ipfsB, ipfsC, cb),
  ], done)
})
```

## Change the way tests are written

To help move towards proper test isolation, and makes scoping easier I think we might want to look into moving towards single assertion testing. This is a little tedious and can take a bit of effort to write correctly, but when done testing in isolation is much easier. Every test ends up being written in a `context` that describes the way the ipfs command is being involved. The test then assert the behavior expected to result from the invoked command. This is particularly easy in the single ipfs instance tests.

I've made some example of what this looks like
https://gist.github.com/travisperson/277560b224c48bab9f37a8f2c55f91f4

This one is quite a big change, and will result in a rather large amount of code being rewritten. However, I think a lot of code really does need to have a second pass right now. It also helps keep setup close to the tests that are using them and not dealing with scope issues so people can use fairly generic terms

There are other ways to get around scope as well, such as just creating a new one.

```js
{
  let node
  before((done) => {
    DAGNode.create(someData, (err, resp) => {
      expect(err).to.not.exist()
      pbNode = resp
      done()
    })
  })
  
  let cid
  before((done) => {
    ipfs.dag.put(pbNode, {
      format: 'dag-pb',
      hashAlg: 'sha2-256'
    }, (err, resp) => {
      expect(err).to.not.exist()
      cid = resp
      done()
    })
  })
  
  it('should get a dag-pb node', (done) => {
    ipfs.dag.get(cid, (err, result) => {
      expect(err).to.not.exist()
      const node = result.value
      expect(pbNode.toJSON()).to.eql(node.toJSON())
      done()
    })
  })
}
```

## Additional areas of focus

**Callback and Promise tests**

Every command is going to be accepting callbacks and promises, which means we will have twice as many tests. I spent sometime thinking about how to reduce code duplication, but didn't really come up with anything that seems like a good way forward.

Some ideas though

* **Shared assertions**: There really isn't much different between the callback and promise interfaces, both get the same result object. We could wrap all the assertions in functions and pass the result in.
* **Command runner**: Basically a way to pass in arguments / callback that will invoke the command both as a callback and a promise. Though this isn't much different than just call `promisify` on the command itself, just kind of in reverse.

**"Dependencies" injection**

Every test now has the exact same three lines at the top, and a lot of them import the same functions. Instead of having to deal with a large list of require statements, we could wrap tests up a bit further.

```js
module.exports = test('.system.command', resources => {
  const { it, describe, common } = resources
  ...
})
```

We could also throw in other mocha globals and get rid of them all :smiling_imp: 

@alanshaw @VictorBjelkholm @diasdavid

**Comment by achingbrain** [comment]
Some good suggestions here, I think they deserve writing up as a PR to https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md

**Comment by achingbrain** [comment]
Closing as this issue is now very stale.
