### ISSUE TITLE
ipfs.config.replace

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#2905]
This can't be finished until https://github.com/ipfs/go-ipfs/issues/2927 is resolved

**Comment by achingbrain** [comment]
This needs verifying to make sure it's still an issue.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

I don't think Helia is using the same `~/ipfs/config` file that Kubo uses any longer. Config should all be done via code AFAIK, helia docs to clarify.
