### ISSUE TITLE
files ls -l -r would be really nice to have

### ISSUE THREAD

**Issue by cappelaere** [ipfs/js-ipfs#2907]
It would be a great enhancement to have a recursive capability for files ls [-l]
This would avoid having to call the server repeatedly.
Interestingly, there is a files rm -r
Thank you for this great library.
Pat.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

I believe this, or similar via different methods, should be possible in Helia.
