### ISSUE TITLE
Change Swarm tests with support for multiple multiaddrs with port 0

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#2909]

**Comment by achingbrain** [comment]
For a bit more context, if we spawn a node with three multiaddrs like `/ip4/0.0.0.0/tcp/0`, instead of getting three interfaces back with different ports, we get one.  If that is fixed then we can run tests with multiple interfaces.

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

This has been resolved in Helia, well - in libp2p really, you can configure multiple listen addresses on port 0 and they will all get random high ports.
