### ISSUE TITLE
js-ipfs-http-client terminates node app when retrieving blocks > ~32 K

### ISSUE THREAD

**Issue by chafey** [ipfs/js-ipfs#2917]
OS: Mac OS X 10.15.3
NodeJS: 12.14.0
ipfs-http-client: 42.0.0

NodeJS application is terminated prematurely when trying to retrieve blocks > ~32k.  This happens for both the dag and block apis

The following code will reproduce the problem
``` javascript
const IpfsHttpClientRepository = require('ipfs-http-client')

async function main() {
  const ipfs = new IpfsHttpClientRepository()
  const buffer = Buffer.alloc(32 * 1024)
  const cid = await ipfs.dag.put(buffer, {format: 'raw', hashAlg: 'sha2-256'})
  console.log('cid = ', cid.toString())
  const result = await ipfs.dag.get(cid)
  // never get here
  console.log('result.value.length:', result.value.length)
}

main()
```

The above code will succeed if you reduce the size of the buffer a few bytes

**Comment by hugomrdias** [comment]
can't reproduce, tested it against go-ipfs and js-ipfs and it works.

try this
```js
const ipfs = require('./packages/ipfs-http-client')('http://localhost:62678')

async function main () {
  const buffer = Buffer.alloc(32 * 1024)
  const cid = await ipfs.dag.put(buffer, { format: 'raw', hashAlg: 'sha2-256' })
  console.log('cid = ', cid.toString())
  const result = await ipfs.dag.get(cid)
  // never get here
  console.log('result.value.length:', result.value.length)
}

main()

```

plus your code should error with something like `TypeError: IpfsHttpClientRepository is not a constructor`

Feel free to re-open if you still an issue. 

Thank you.
