### ISSUE TITLE
object.links returns Promise that is never fulfilled or rejected

### ISSUE THREAD

**Issue by tniessen** [ipfs/js-ipfs#2922]
Local API server:
```
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/windows
Golang version: go1.13.7
```

I am using `ipfs-http-client@42.0.0` with Node.js v13.11.0 and npm 6.13.7, also in amd64/windows. All three versions are the latest published versions. Consider this JavaScript code:

```js
const ipfs = require('ipfs-http-client')('http://localhost:5001');

function test(hash) {
  ipfs.object.links(hash)
  .then(() => console.log('fulfilled'))
  .catch(() => console.error('error'));
}
```

This outputs `fulfilled` as expected:

```js
test('QmTLecu8KRTHZ1K9AQCHoHgN8VjEi3Rh3dERRTKwarSYAX')
```

However, this just ends the process, without fulfilling or rejecting the Promise, so neither `fulfilled` nor `error` is printed:

```js
test('QmdiUaSSNNGpimxaGxrJBbb5RJKoRLRqD6qxb8DJ7cRa3R')
```

There are no code changes, just the hash changes.

I am able to access both objects using `ipfs object links` (using go-ipfs), and through `curl http://127.0.0.1:5001/api/v0/object/links/...`.

Am I missing something? Even if I messed up somewhere, I would expect the Promise to at least be rejected.

Please let me know what information I can provide, or how I can approach this problem.

**Comment by hugomrdias** [comment]
can you provide the data for thoses cids ? so we can reproduce the problem.

**Comment by tniessen** [comment]
I am sorry I never got back to you. This was for a larger project, and the dataset consisted of about one hundred gigabytes of linked data that I don't have access to anymore.

I ended up removing `ipfs-http-client` and used the HTTP API provided by Node.js instead to communicate with the HTTP interface directly.
