### ISSUE TITLE
"ERR_CERT_COMMON_NAME_INVALID" in browser

### ISSUE THREAD

**Issue by christopheSeeka** [ipfs/js-ipfs#2923]
Hello, testing the js-ipfs implementation to run node in browser, it works but i keep getting this certificate error:

bundle.js:160414 WebSocket connection to 'wss://node0.preload.ipfs.io/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID

Any pointer?

Thanks

**Comment by alexjc** [comment]
I think this is a server-side problem, likely the SSL certificate expired?

You can disable preloading in the configuration by adding this into your application:
```
preload: { enabled: false }
```

**Comment by christopheSeeka** [comment]
Thanks for the info :)

Not sure if the right place but i dont the info anywhere, when run a node in the browser, where are the files/data stored on client side?

**Comment by achingbrain** [comment]
> where are the files/data stored on client side?

They are stored in indexdb in your browser - if you open the developer tools you should be able to look through the repository structure.

The certificate error should hopefully be fixed next week, I think one of the preload nodes has the wrong wildcart cert installed.

**Comment by christopheSeeka** [comment]
Thank you for this info, i'll check that. Arent we limited with indexdb storage? i thought it was like 50Mb

**Comment by olizilla** [comment]
An SSL certificate for staging was rolled out incorrectly to `node0.preload.ipfs.io`. the alternate preload node `node1.preload.ipfs.io` was unaffected. As such the preload service should have still been usable during this issue. Regardless, it's fixed now. The production certificate is deployed to node0.

**Comment by christopheSeeka** [comment]
Thanks a lot, yes it was working, its just that i wanted be sure all was ok as i prefer not have error in console :D All good now thanks again.

**Comment by olizilla** [comment]
Thanks for flagging it!

**Comment by achingbrain** [comment]
> Arent we limited with indexdb storage? i thought it was like 50Mb

By default yes, but the user can grant permission for an app/page to exceed that limit.

Anyway, the cert problem appears to be resolved, thanks for reporting it - please open another issue if it happens again.
