### ISSUE TITLE
circuit-relaying example+tests don't work

### ISSUE THREAD

**Issue by alexjc** [ipfs/js-ipfs#2925]
**Version**: [bfba76748b8aabc0d66768009ff6f4adb24ff439]
**Type**: bug
**Severity**: medium
**Description**:

Following the steps and building from this example:
https://github.com/ipfs/js-ipfs/tree/master/examples/circuit-relaying

In the UI, the "Addresses:" section is empty and `info.addresses` is an empty list.  Connecting to other peers works, but not dialing `/p2p-circuit/<peerid>`.

**Comment by achingbrain** [comment]
Did you follow all the steps in the readme?  Are you running the relay node for example?

There's a [test](https://github.com/ipfs/js-ipfs/blob/master/examples/circuit-relaying/test.js) in that folder that follows all the steps as part of CI so there must be something different about what you are doing.

**Comment by wolfgang** [comment]
This is a great test and it completely simulates what the example has you do by hand.
However, if you look at the test output, it becomes clear that the value retrieved from the "#addrs" field is always empty, so remotePeerId and localPeerId will be empty.
As a result,  the two assertions on lines 144 and 145  don't detect that a peer is only ever sending a message to itself.
Something like `browser.expect.element('#addrs').text.to.not.equal("");` right before line 102 will make the test fail.
So the test produces the exact same situation as the example does, but the behaviour is not as expected in both cases.

**Comment by achingbrain** [comment]
This has been fixed in the [examples repo](https://github.com/ipfs-shipyard/js-ipfs-examples/tree/master/examples/circuit-relaying), it's been updated to have the user work out what the circuit relay address should be, hopefully it's clearer now and the test is more reliable.
