### ISSUE TITLE
Difficult to use local version of ipfs-http-client in a React app and have it pick up the local version of ipfs-utils as a child dep from this monorepo too

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2927]
As described here https://github.com/hugomrdias/connect-deps/issues/23#issuecomment-600892957

**Comment by achingbrain** [comment]
Can you open a thread on https://discuss.ipfs.io please?

**Comment by pcowgill** [comment]
Sure, will do

**Comment by pcowgill** [comment]
https://discuss.ipfs.io/t/suggestion-document-how-to-use-local-version-of-ipfs-http-client-in-a-react-app-and-have-it-pick-up-the-local-version-of-ipfs-utils-as-a-child-dep-from-the-monorepo-too/7510?u=pcowgill

**Comment by x5engine** [comment]
same issue! was pretty easy to do!

**Comment by pcowgill** [comment]
@x5engine You mean it was pretty easy to reproduce the issue or to get past the issue?
