### ISSUE TITLE
Flaky pubsub tests

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#2930]
This test sometimes fails in CI, running via the http client on node against a js-ipfs backend on OS X in this case:

```
ipfs:       1) should cancel a subscription correctly returning true
ipfs:   906 passing (12m)
ipfs:   56 pending
ipfs:   1 failing
ipfs:   1) interface-ipfs-core over ipfs-http-client tests
ipfs:        .name.pubsub.cancel
ipfs:          should cancel a subscription correctly returning true:
ipfs:      AssertionError: expected [ Array(1) ] to include '/ipns/QmTZWQ6rEYJuPLqXz4rzVu1T8dcWR5pp5DbjKp9EH9KK1Q'
ipfs:       at Context.<anonymous> (/Users/travis/build/ipfs/js-ipfs/packages/interface-ipfs-core/src/name-pubsub/cancel.js:4:1913)
ipfs:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

cc @vasco-santos

**Comment by vasco-santos** [comment]
well, an array with an array inside seems strange. I guess the content is inside that array, I don't know how it is getting a double array though

**Comment by achingbrain** [comment]
It's not getting a double array, the array has the wrong contents.

In the `should cancel a subscription correctly returning true` test we generate a Peer ID but the test fails for certain types of IDs.

For example if you run it with `QmW6mcoqDKJRch2oph2FmvZhPLJn6wPU648Vv9iMyMtmtG` it passes but with `QmQd5Enz5tzP8u5wHur8ADuJMbcNhEf86CkWkqRzoWUhst` it fails.

There's a lot of treating buffers as if they only contain bytes printable as utf8 in the ipns code, it's probably related to that.

**Comment by achingbrain** [comment]
I meant to add, it fails because the pubsub subscription list contains the wrong name.

Try to resolve `QmW6mcoqDKJRch2oph2FmvZhPLJn6wPU648Vv9iMyMtmtG` and the subscription list contains `/ipns/QmW6mcoqDKJRch2oph2FmvZhPLJn6wPU648Vv9iMyMtmtG`

Try to resolve `QmQd5Enz5tzP8u5wHur8ADuJMbcNhEf86CkWkqRzoWUhst` and it has `/ipns/6PJ8ijzznyBjdEAGvgAKPUr1Jooz2QwQMfTdCHs52voc6`
