### ISSUE TITLE
api not match

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#2936]
https://github.com/bluelovers/ws-ipfs/blob/master/packages/ipfs-api-check/test/demo.ts

> TypeError: ipfs.dag.tree is not a function

https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs/src/core/components/dag

![image](https://user-images.githubusercontent.com/167966/77244504-61aafa00-6c50-11ea-8765-e37e74dd6882.png)

https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client/src/dag

![image](https://user-images.githubusercontent.com/167966/77244508-6c658f00-6c50-11ea-8b56-29b4ed1961ed.png)

https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/SPEC/DAG.md#dagtree

![image](https://user-images.githubusercontent.com/167966/77244511-77202400-6c50-11ea-8235-30e0b673d54f.png)

---

and i think should convert source to typescript for avoid api break

**Comment by achingbrain** [comment]
`ipfs.dag.tree` has not been implemented in the HTTP client yet - I'll gladly merge a PR if you submit one.

**Comment by bluelovers** [comment]
i think should not close issue when that is still not implemented

**Comment by achingbrain** [comment]
This is a duplicate of https://github.com/ipfs/js-ipfs/issues/2869
