### ISSUE TITLE
Support for Persistent Storage in Web Browsers

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#2937]
### Context

Right now every js-ipfs repo created in web browser context is created in the default, "temporary" storage space provided by the browser.

This means:
- there is no user prompt asking user to allow js-ipfs to store data (good UX)
- data is stored in a space that is
  - shared with entire Origin (other JS code can eat up the quota)
  - silently GC'd if Origin or global storage hits browser-vendor-specfic limits

### Motivation

This is usually ok, as data cached in js-ipfs is expected to "disappear" (as in: go offline)  when user closes the tab and app developers add some middleware responsible for pinning/persisting user data anyway.

That being said, **there should be a programmatic opt-in to use persistent storage in the browser**, just in case someone really wants data to be around, or expect a lot of data to be downloaded by their web app and don't want it to get GC'd. Imagine a game / VR app which is using IPFS for asset storage etc.

### Note on this being vendor-specific

Below are only initial notes.
Make sure to re-check before starting work, as vendors may have changed it. 

- We probably need to add optional configuration key that gets passed to js-datastore used in browser runtime.
  - Unsure about the value behind this new configuration key. Needs evaluation, could be a function that is called with the result of user decision, providing a way of idiomatic fallback, but needs evaluation of current vendor behavior. 
- Persistent storage requires user to approve. Specific moment when "ask" occurs is browser-specific, at least that was the case ~2017:
   - chrome seems to be global per Origin https://github.com/dfahlander/Dexie.js/issues/467#issuecomment-313831062 
   - firefox supports requesting persistence at the moment IndexedDB is created: https://github.com/dfahlander/Dexie.js/issues/467#issuecomment-313899397
- Upon request a pop-up/prompt will be displayed, and user accepts or rejects.

### What needs to happen?

- [ ] document current behavior in Firefox, Chromium and Safari
- [ ] design configuration option that would work everywhere
- [ ] wire up configuration option to work in every supported browser and throw error otherwise

### References

- https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria
 - some notes on browser-specific behaviours:
   - chrome: https://github.com/dfahlander/Dexie.js/issues/467#issuecomment-313831062
   - firefox: https://github.com/dfahlander/Dexie.js/issues/467#issuecomment-313899397
- https://developers.google.com/web/updates/2016/06/persistent-storage
- Reliable persistence in browser context will be more and more important as more features in ipfs/libp2p stack start to rely on historical data:  https://github.com/libp2p/js-libp2p/issues/582
- Safari purging local storage after 7 days:
  - https://twitter.com/cvanw/status/1242700155180027904

**Comment by magniff** [comment]
Sup. Any progress on that one?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

I think this functionality would make the most sense as a UI plugin / extension of a datastore/blockstore implementation in Helia. Closing this issue, but pinging @achingbrain for awareness.
