### ISSUE TITLE
FILES API doc urlSource typo

### ISSUE THREAD

**Issue by tabcat** [ipfs/js-ipfs#2941]
taken from https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/SPEC/FILES.md#importing-a-file-from-a-url ::

###### Importing a file from a URL

Both js-ipfs and js-ipfs-http-client export a utility to make importing a file from a URL easier.

```js
const IPFS = require('ipfs')
const { globSource } = IPFS

const ipfs = await IPFS.create()

for await (const file of ipfs.add(urlSource('https://ipfs.io/images/ipfs-logo.svg'))) {
  console.log(file)
}

/*
{
  path: 'ipfs-logo.svg',
  cid: CID('QmTqZhR6f7jzdhLgPArDPnsbZpvvgxzCZycXK7ywkLxSyU'),
  size: 3243
}
*/
```

here i believe `const { globSource } = IPFS` should be `const { urlSource } = IPFS`

i can make a PR or someone with access can make the change

**Comment by achingbrain** [comment]
Well spotted - could you create a quick PR please?
