### ISSUE TITLE
mfs file type should return same type

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#2948]
from `stat` is `string`
from `ls` is `number`

this will easy make bug happen when we not check real return value

**Comment by achingbrain** [comment]
The [spec docs say](https://github.com/ipfs/js-ipfs/blob/b18f6e1a791f9c72c9f35ec78c471879bbdc1525/packages/interface-ipfs-core/SPEC/FILES.md#filesls) the `type` returned from `ipfs.files.ls` should be `file` or `directory` so changing this makes sense.

Would you like to create a PR for this that changes it to use strings everywhere?  The HTTP API should remain unchanged but we can translate the types in [core](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/core/components/files/ls.js#L22) & the [client](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/files/ls.js#L46-L50).

You'll most likely have to change the [interface tests](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/files/ls.js) too.  Please make sure HAMT sharded directories are handled correctly.

**Comment by achingbrain** [comment]
Fixed in #3352
