### ISSUE TITLE
How can attach cid to new node

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#2951]
cidA fie
cidB dir with sub cids

how can i make a new is

```
(new root cid)
- name1 = cidA
- dir2 = cidB
```

ipfs.files.write looks like not allow content is cid

**Comment by achingbrain** [comment]
For questions on how to use IPFS, please open a thread on https://discuss.ipfs.io

**Comment by achingbrain** [comment]
https://discuss.ipfs.io/t/how-can-attach-cid-to-new-node/7534
