### ISSUE TITLE
files.stat throws an error when given a CID instance

### ISSUE THREAD

**Issue by mistakia** [ipfs/js-ipfs#2970]
- **Version**: 0.42.0
- **Platform**:  Darwin macbook 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
- **Subsystem**:

#### Description:
Either an issue with the documentation or the implementation, as the [documentation](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#filesstat) allows for the passing of a CID instance to files.stat. 

#### Steps to reproduce the error:
`await ipfs.files.stat(new CID(cid))`

```
TypeError: (path || "").trim is not a function
at /.../ipfs/src/core/components/files/utils/to-mfs-path.js:16:25
at Array.map (<anonymous>)
at toMfsPath (/.../ipfs/src/core/components/files/utils/to-mfs-path.js:15:17)
at async mfsStat (/.../ipfs/src/core/components/files/stat.js:23:9)
at async /.../ipfs/src/core/components/files/utils/create-lock.js:25:18
at async /.../record-node/components/api/routes/file.js:35:22
```

**Comment by hugomrdias** [comment]
Documentation was updated https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsfilesstatpath-options
