### ISSUE TITLE
IPFS package bloats node_modules by depending on old version of itself 

### ISSUE THREAD

**Issue by dkent600** [ipfs/js-ipfs#2986]
- **Version**:
0.40.0

- **Platform**:
Linux, Windows

#### Type:
Packaging problem

#### Severity:
For you to decide. [For us](https://github.com/daostack/alchemy), it is enough to contribute to causing our Heroku build to fail due to exceeding the maximum slug size

#### Description:

The IPFS package bloats node_modules by depending on old version of itself.

#### Steps to reproduce the error:

[We](https://github.com/daostack/alchemy) depend on [3box](https://github.com/3box/3box-js) which itself depends on:

>     "ipfs": "^0.40.0",
>     "ipfs-did-document": "^1.2.3",
>     "ipfs-log": "^4.5.4",
>     "ipfs-mini": "^1.1.5",
>     "ipfs-postmsg-proxy": "^3.1.1",
>     "ipfs-pubsub-room": "^1.4.1",
>     "ipfs-repo": "^0.30.1",

The resulting npm install looks like this:

> npm list ipfs
> alchemy-client@0.10.4 [...]\alchemy
> -- 3box@1.17.1
>    -- ipfs@0.40.0 
>     -- ipfs@0.38.1  extraneous
>
> npm ERR! extraneous: ipfs@0.38.1 [...]\alchemy\node_modules\ipfs\node_modules\ipfs

Possibly due to incorrect use of shrinkwrap?

**Comment by achingbrain** [comment]
This was indeed a problem with the shrinkwrap file and was fixed in `ipfs@0.41.0`. Are you able to upgrade?

**Comment by oed** [comment]
This ticket can be closed. 3Box has been updated to a newer version of js-ipfs :+1:
