### ISSUE TITLE
Question: why do browser example use a random repo string?

### ISSUE THREAD

**Issue by kumavis** [ipfs/js-ipfs#2995]
support / user question:

why do browser examples use a random repo string?
https://github.com/ipfs/js-ipfs/blob/553a65b04d065730ffd7c99370b10d28018b165d/examples/browser-script-tag/index.html#L8

**Comment by achingbrain** [comment]
I believe it's to ensure that blocks created by one test don't interfere with other tests, otherwise you'd have to stop/start the browser for each test which would be really, really slow.

**Comment by achingbrain** [comment]
Also, please consider using https://discuss.ipfs.io for user/support type queries, it's got much better search functionality than GH where issues tend to disappear without a trace.
