### ISSUE TITLE
How do I get ipfs cat data?

### ISSUE THREAD

**Issue by satoshi999** [ipfs/js-ipfs#3002]
I tried ipfs.cat() of latest "ipfs-http-client".
```
download.js

(async() => {
  const chunks = []
  for await (const chunk of node.cat("QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN", {timeout: 1000})) {
    chunks.push(chunk)
  }
  console.log(Buffer.concat(chunks).toString());
})();
```

This is result.
```
$ node download.js
(node:184) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
hello
```

I don't need message of "(node:184) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time".

What should I do?

os:centos7(on docker)
ipfs-http-client ver:44.0.0
go-ipfs:go-ipfs_v0.4.23_linux-amd64

**Comment by achingbrain** [comment]
Please upgrade to a later version of node.

See: https://github.com/nodejs/node/issues/26479

**Comment by satoshi999** [comment]
@achingbrain 
I understand. Thank you.
