### ISSUE TITLE
[ipfs-http-client] - I still have an Alex in my Chrome browser

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs/js-ipfs#3006]
Following the archived report :
https://github.com/ipfs/js-ipfs-http-client/issues/1202
And a ccording to the following screenshot the latest ipfs-http-client still embeds Alex...
![ksnip_20200427-083207](https://user-images.githubusercontent.com/20576132/80330129-fa412500-8861-11ea-9f29-de93b6aaf60d.png)
Thanks

**Comment by achingbrain** [comment]
This is the same issue as https://github.com/ipfs/js-ipfs-http-client/issues/1202 and will be resolved by https://github.com/ipfs/aegir/issues/483

Would you like to open a PR against aegir that makes this change?

**Comment by xmaysonnave** [comment]
Thanks for the update. I was confused with the repo migration and the archived status of my previous bug report. I'm not sure if I can help, I've no skills with aegir. This issue is not critical but need to cleanup. No idea about the overhead it implies too but for sure there is one.

**Comment by achingbrain** [comment]
You almost certainly don't need any deep knowledge of aegir to fix this up.

The webpack configuration that's applied to every build is [here](https://github.com/ipfs/aegir/blob/master/src/config/webpack.config.js), I haven't looked into it but it's probably just a small config tweak to disable source maps for production builds.

**Comment by achingbrain** [comment]
Since https://github.com/ipfs/aegir/pull/549 went in and `ipfs-http-client@44.1.0` shipped this should be resolved.  Can you please check and see if you're still observing this?

**Comment by xmaysonnave** [comment]
@achingbrain Looks good to me. See the screenshot here attached. Thanks

![ipfs-http-client-44 1 0](https://user-images.githubusercontent.com/20576132/82280301-37ee2500-99ac-11ea-92cc-75608ecc8a03.png)

**Comment by achingbrain** [comment]
Great!
