### ISSUE TITLE
Run E2E tests against version at API port's /webui

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#3010]
> Needs #2984  to land first

Thanks to https://github.com/ipfs/js-ipfs/pull/2706 we have E2E tests that check if js-ipfs is compatible with ipfs-webui's `master` branch, but we don't run those tests against the webui version aliased at `/webui` on API port. 

Over time, support for older version at `/webui` may break, while the `master` of webui continues to work with js-ipfs `master`, which means we miss some regressions. 

A fix here would be to run ipfs-webui E2E  test suite against version at `/webui` at well:

- extract CID from `packages/ipfs/src/http/api/routes/webui.js`
- prefetch it and cache  so CI is not slowed down
- make it a separate task in CI with distinct name (eg. ipfs-webui(/webui)) 
- no need to run it twice

**Comment by achingbrain** [comment]
> no need to run it twice

Would we not want to run it on FF & Chrome?

**Comment by lidel** [comment]
Right now E2E run only against Chromium. Running against Firefox should be possible now that puppeteer added support https://github.com/ipfs-shipyard/ipfs-webui/issues/1164#issuecomment-616777954, but its not implemented yet.

What I meant by "running twice" was that E2E is running once against "release" version and then the second time against "PR" version to detect regressions. When we add E2E against `/webui` that needs to run only "once".

**Comment by SgtPooki** [comment]
@BigLep I believe this one is irrelevant for helia because we're detaching js-ipfs from webui

**Comment by BigLep** [comment]
Agreed.  We can close this given webui is detached from js-ipfs and Helia.
