### ISSUE TITLE
Meta: Broken links / links to archived repos

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3031]
Encountering many broken links or links pointing to archived repos. Will report them all here

https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/docs/MODULE.md
-🚫-> https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs/examples/circuit-relaying
-🚫-> https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/docs/docs/config.md

https://js.ipfs.io/
-⚠️-> https://github.com/ipfs-inactive/interface-js-ipfs-core/tree/master/SPEC

**Comment by achingbrain** [comment]
Thanks for pointing these out - could you please open PRs to fix the broken links when you encounter them?
