### ISSUE TITLE
Can’t establish a connection to the server

### ISSUE THREAD

**Issue by mdtanrikulu** [ipfs/js-ipfs#3039]
Hey there,

- commit: "", repo: 7, version: "0.43.3"

- **Platform**:
MacOS Mojave, Firefox 76.01

- **Subsystem**:
Dag API

#### Severity:

I am having `Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic.` error. 
Not able to retrieve object by DAG Api.

#### Steps to reproduce the error:
Basic DAG put/get request;

```js
const testDag = async () => {
    let node = await IPFS.create();
    let cid = await node.dag.put({
        test: 'test'
    })
    let result = await node.dag.get(cid);
    return result
}
```

**Comment by achingbrain** [comment]
This is just a warning. Sometimes the preload nodes are unavailable or unreachable but it shouldn’t affect anything, only your content will take longer to resolve from other parts of the internet.

**Comment by mdtanrikulu** [comment]
> This is just a warning. Sometimes the preload nodes are unavailable or unreachable but it shouldn’t affect anything, only your content will take longer to resolve from other parts of the internet.

Oh right, that was my mistake while debugging. Thanks for clarifying.
