### ISSUE TITLE
Pin.add API - not supported with CIDv0

### ISSUE THREAD

**Issue by mdtanrikulu** [ipfs/js-ipfs#3048]
- **Version**:
`{ ipfs: { version: '0.44.0', repo: 7, commit: '' }`

- **Platform**:
18.7.0 Darwin

- **Subsystem**:
PIN

#### Description:
Hey there!

I am trying to pin MFS folder via `pin.add` with `recursive: true` option;
```js
await this.node.pin.add(cid, { recursive: true });
```
When I use CID of folder, getting the error below.
```js
'not supported with CIDv0, to support different bases, please migrate the instance do CIDv1, you can do that through cid.toV1()'
```
Then used `cids` to convert CID v0 to v1;
```js
await this.node.pin.add(new CID(cid).toV1(), { recursive: true });
```
also tried with several options, like adding `toString()`, `toBaseEncodedString()`
but always getting;
```js
Error {
    message: 'Unsupported encoding',
}
```

Is there something that I missed or is `multibase` library somehow incompatible with current version of js-ipfs ? 

#### Steps to reproduce the error:
- Create MFS folder: `files.mkdir`,
- Write a file into it with `files.write`
- Get hash of created MFS folder via `files.stat`
- Pin it with `pin.add`

**Comment by achingbrain** [comment]
The MFS root is pinned recursively by default so this shouldn't be necessary.

Having said that, it looks like it should work - what's the value of the `cid` variable here?

**Comment by mdtanrikulu** [comment]
> The MFS root is pinned recursively by default so this shouldn't be necessary.

Thanks for the information, I tested it already and the folder seems reachable on other devices.

The `cid` variable was a CIDv0 object returned from `files.stat` api. 
It was for testing purposes. Unfortunately I don't have the content and the hash anymore.

The reason I was trying to pin the MFS folder; I was trying to reach my MFS folder in unit testing but failed for some reason, then stumbled upon [this information](https://stackoverflow.com/a/54180887/1763249) by @daviddias 
> They are not by default Pinned. You will need to pin those files as well if you want them tracked by the Pinner. You can do a ipfs files stat /somePath, get the hash and then pin that hash.

As I mentioned maybe I misunderstood the context, but thought maybe I should manually pin the folder, then faced with the errors above. So for some reason if I try to pin local MFS folder it gives an error.

**Comment by achingbrain** [comment]
I'm having problems replicating this, I've added the following test to the [pin.add interface suite](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/pin/add.js) which I think follows the 'steps to reproduce' above and it passes against js-ipfs and go-ipfs, over http, in process and in the browser:

```javascript
it('should pin an mfs folder', async () => {
   const folder = `/folder-${Math.random()}`
   const path = `/${folder}/file.txt`

  await ipfs.files.mkdir(folder)
  await ipfs.files.write(path, 'Hello world', {
    create: true
  })

  const { cid } = await ipfs.files.stat(path)

  await ipfs.pin.add(cid)

  expect(all(ipfs.pin.ls(cid))).to.eventually.deep.include({
    cid,
    type: 'recursive'
  })
})
```

Can you add a failing test in a PR that demonstrates the problem?

**Comment by mdtanrikulu** [comment]
Sorry for extreme feedback delay, I failed to reproduce my case on that time, it was requiring some more extra steps. After remembering and giving a try later, it seems working with current version I have now. (0.50.2). I am closing this long hanging issue.
