### ISSUE TITLE
Ipfs file uploading issue

### ISSUE THREAD

**Issue by rohail411** [ipfs/js-ipfs#3060]
I'm using IPFS service for file storage. From Node.js application I can initialize IPFS_Node and using this Node upload file.
`var ipfs = ipfsClient({
            // the hostname (or ip address) of the endpoint providing the ipfs api
            host: '*****************',
            // the port to connect on
            port: 443,
            // 'api-path': '/api/v0/',
            // the protocol, https for security
            protocol: 'https',
            // provide the jwt within an authorization header
            headers: {
                authorization:
                    'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ**********************'
            }
        });

 const data = await ipfs.add(file);

 console.log(data);`
it returns (Object [AsyncGenerator] {} ) empty object

**Comment by chelneru** [comment]
https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsadddata-options . There are examples in the documentations on how to use the library. 

In short :

````
for await (const result of ipfs.add(content)) {
  console.log(result)
}

**Comment by achingbrain** [comment]
Please see the docs as @chelneru suggests, they have everything you need.

If you need more help using the module, please ask questions on https://discuss.ipfs.io
