### ISSUE TITLE
How to connect js-ipfs node on browser to go-ipfs node on remote server？

### ISSUE THREAD

**Issue by enochzhao** [ipfs/js-ipfs#3082]
Hello, I encountered a problem and look forward to getting help:
I have 2 ipfs nodes, one is the js-ipfs daemon running on the browser, the other is the go-ipfs running on my remote server,
I used the code to start the js-ipfs daemon on the browser, it only runs on the browser, without installing any software or plug-ins,
I tried to connect the js-ipfs node on the browser to the go-ipfs node on my server, but it failed.

My js-ipfs starts like this:
const node = await Ipfs.create({ repo: userName });

The browser can be connected to the following nodes on the public network:
'/dns4/sgp-1.bootstrap.libp2p.io/tcp/443/wss/p2p/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu',

'/dns4/sfo-3.bootstrap.libp2p.io/tcp/443/wss/p2p/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM',
    '/dns4/node0.preload.ipfs.io/tcp/443/wss/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic',

'/dns4/nyc-1.bootstrap.libp2p.io/tcp/443/wss/p2p/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm',

'/dns4/nyc-2.bootstrap.libp2p.io/tcp/443/wss/p2p/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64',
        '/dns4/node2.preload.ipfs.io/tcp/443/wss/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS',

'/dns4/lon-1.bootstrap.libp2p.io/tcp/443/wss/p2p/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3',

'/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/p2p/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd',
        '/dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN',
        '/dns4/node1.preload.ipfs.io/tcp/443/wss/p2p/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6',

But I can't connect to my own server go-ipfs node, and can only use the form with the domain name above, not the form with IP,
For example:'/ip4/147.75.69.147/tcp/4001/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic', this form is invalid.

I need help, I look forward to you helping me

**Comment by achingbrain** [comment]
This thread is being resolved at https://discuss.ipfs.io/t/how-to-connect-js-ipfs-node-on-browser-to-go-ipfs-node-on-remote-server
