### ISSUE TITLE
ipfs-http-client cat operation doesn't expose X-Content-Size header

### ISSUE THREAD

**Issue by dsemenovsky** [ipfs/js-ipfs#3089]
- **Version**: ipfs-http-client 44.2.0

- **Platform**: Browser/Any

- **Subsystem**: CAT

#### Description:
When using `ipfs.cat(ipfsHash, { progress: progressCallback })` there is no way to access response header X-Content-Size to properly track the progress of downloading, this method returns iterable that only produces chunks of data.

Hence, no way of tracking progress properly.

#### Steps to reproduce the error:
```
const iterable = ipfs.cat(ipfsHash, { progress: progressCallback })
console.log(iterable) // AsyncGenerator
for await (const chunk of iterable) {
 console.log(chunk) // Chunk of data
}
```

**Comment by achingbrain** [comment]
`ipfs.cat` does not support a `progress` option - see [FILES.md](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#options-1)

You can do something similar by using `ipfs.files.stat` to get file stats before starting to cat the file:

```javascript
const { size } = await ipfs.files.stat(`/ipfs/${cid}`)
let downloaded = 0

for await (const chunk of ipfs.cat(cid)) {
  downloaded += chunk.length
  console.log(`Received ${((downloaded / size) * 100).toFixed(2)}%`)
}
```

**Comment by dsemenovsky** [comment]
Noted, will use `files.stat` to get the file size.
