### ISSUE TITLE
how i can get/calculate ipfs hash before add this to ipfs

### ISSUE THREAD

**Issue by viethoanganh79** [ipfs/js-ipfs#3091]
i just want to get hash of response when adding to ipfs before i add this to ipfs

**Comment by achingbrain** [comment]
There is an `onlyHash` parameter you can pass to [ipfs.add](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#options) programatically or on the command line:

```console
$ jsipfs add --only-hash ./file.txt
```

Alternatively use the [ipfs-only-hash](https://www.npmjs.com/package/ipfs-only-hash) module.

If you have 'how do I' type questions, please ask them on https://discuss.ipfs.io

**Comment by viethoanganh79** [comment]
thanks for support 🥇

**Comment by fawazahmed0** [comment]
Sharing this, might help someone:
```js
const IPFS =  require('ipfs-core')
const ipfs = await IPFS.create({start: false})
const { cid } = await ipfs.add('Hello world',{onlyHash:true,cidVersion:1,hashAlg:'blake2b-256'})
console.info(cid.toString())
```
