### ISSUE TITLE
How to create ipfs instance with go-ipfs local node as like "ipfs-http-client"?

### ISSUE THREAD

**Issue by satoshi999** [ipfs/js-ipfs#3094]
I'm creating ipfs application as following.

- local ipfs node
 -> local node as runed by go-ipfs
- nodejs application side
 -> Call ipfs api by ipfs-http-client
 ```
 const ipfsClient = require('ipfs-http-client');
 node = ipfsClient({ host: 'localhost', port: 5001, protocol: 'http'});
 ..
 async function wrapIPFSCat(hash) {
 	return await node.cat(hash);
 }
 ..
 ```
 
I want to use 'timeout' function.
```
await node.cat(hash, {timeout:30000});
```
But it seem is not suporrted  on ipfs-http-client.

I tried replace liblary to ipfs as this project to using timeout function.
so I changed using package as following. but it says "ipfsClient is not a function" error when create instance with host and port and protcol.
How do I create instance with go-ipfs local node?
 ```
 const ipfsClient = require('ipfs');
 node = ipfsClient({ host: 'localhost', port: 5001, protocol: 'http'});
 ..
 async function wrapIPFSCat(hash) {
 	return await node.cat(hash{timeout:30000});
 }
 ..
 ```

**Comment by achingbrain** [comment]
You need to use the [.create](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/docs/MODULE.md#ipfscreateoptions) function exported by the ipfs module:

```javascript
const ipfs = require('ipfs')

const node = ipfs.create()
```

Please use https://discuss.ipfs.io for help with using IPFS.

**Comment by satoshi999** [comment]
@achingbrain 
How can I connect to a node by specifying the host and port using ``js-ipfs`` ?
I tried following code, but it seems build new node and it can not connect to the node of the specified host and port.
```
const ipfs = require('ipfs');
node = ipfs.create({ host: 'localhost', port: 5001, protocol: 'http'});
```
