### ISSUE TITLE
List the remaining IPFS modules to be built, once libp2p is done

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#31]
(repo, config, fs, etc)

**Comment by diasdavid** [comment]
I've added a bunch more, @jbenet can you go through the list and add all the other pieces that can be subsystems that come to your mind? 
https://github.com/ipfs/js-ipfs#roadmap-for-the-full-ipfs-implementation-in-javascript

**Comment by jbenet** [comment]
@diasdavid i think that's comprehensive for the core -- the rest of the go-ipfs modules are extensions i think. 

https://github.com/ipfs/specs/blob/master/overviews/implement-ipfs.md for posterity

**Comment by diasdavid** [comment]
Sounds good, thank you :)
