### ISSUE TITLE
Update pre-async/await js-ipfs usage across PL repos

### ISSUE THREAD

**Issue by andrew** [ipfs/js-ipfs#3104]
There are still a number of repos across ipfs/ipld/libp2p that are using js-ipfs < 0.41 that can be confusing to people looking for examples:

| repo | version | manifest file | issue/pr |
| --- | --- | --- | --- |
| ipfs-shipyard/ipfs-companion | 0.40.0 | package.json  | https://github.com/ipfs-shipyard/ipfs-companion/pull/811 |
| ipld/js-ipld-graph-builder | ^0.32.3 | package.json | https://github.com/ipld/js-ipld-graph-builder/pull/40 |
| ipfs-shipyard/ipfs-share-files | ^0.33.1 | package.json | https://github.com/ipfs-shipyard/ipfs-share-files/issues/75 |
| ipfs/benchmarks | ^0.34.0 | tests/package.json | https://github.com/ipfs/benchmarks/pull/276 |
| ipfs-shipyard/ipld-explorer | ^0.34.4 | package.json | https://github.com/ipfs-shipyard/ipld-explorer/pull/65 |
| ipfs-shipyard/js-idm-wallet | git://github.com/satazor/js-ipfs.git#ipfs-camp | package.json | |
| ipfs-shipyard/js-idm-client | git://github.com/satazor/js-ipfs.git#ipfs-camp | package.json | |
| libp2p/js-libp2p | ~0.34.4 | examples/delegated-routing/package.json | https://github.com/libp2p/js-libp2p/pull/507 |
| ipfs-shipyard/ipfs-npm-registry-mirror | ~0.36.3 | packages/common/package.json | https://github.com/ipfs-shipyard/ipfs-npm-registry-mirror/pull/17 |

**Comment by oed** [comment]
https://github.com/ipfs-shipyard/ipfs-pubsub-1on1/pull/11

**Comment by achingbrain** [comment]
@andrew could you open issues on the affected repos?  Their owners may not check this issue so likely won't know that they should update.

If they aren't maintaining them any more, they should probably be archived or at least a big note should be put in the readme.

Also, some repos have been updated, can you update this table occasionally?

**Comment by andrew** [comment]
I've updated the table, removed rows that have been upgraded and added links to PRs that will update js-ipfs

**Comment by lidel** [comment]
Based on triage discussion, closing as stale: assuming if a project did not update by now, either there is an unrelated blocker, or project is not important enough/maintained.
