### ISSUE TITLE
Intermittent failures: returns 400 if no node is provided

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3105]
Intermittent timeout occurs with this test:

https://github.com/ipfs/js-ipfs/blob/8808abc3aed2cd05cdb152fd17ed351a0db53fd3/packages/ipfs/test/http-api/inject/block.js#L63-L76

```
ipfs:   1 failing
ipfs:   1) /block
ipfs:        /put
ipfs:          returns 400 if no node is provided:
ipfs:      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/test/node.js)
ipfs:       at listOnTimeout (internal/timers.js:549:17)
ipfs:       at processTimers (internal/timers.js:492:7)
ipfs: 
ipfs: Command failed with exit code 1: mocha --ui bdd --timeout 10000 --unhandled-rejections=strict --colors --exit --bail test/node.js test/**/*.spec.js
```

**Comment by achingbrain** [comment]
Is this still a problem?

**Comment by Gozala** [comment]
> Is this still a problem?

I'm not sure, since I have not had any pushes since. I think for all the intermittent failures we could put just anotate tests with pointers to issues and close the issues. If they show again in CI it would be easy enough to reopen.

**Comment by achingbrain** [comment]
Closing as this is very stale.
