### ISSUE TITLE
Tag image 

### ISSUE THREAD

**Issue by Slender1808** [ipfs/js-ipfs#3120]
To add image would it be like this ?

`'use strict'`
`/* global Hls Ipfs HlsjsIpfsLoader */`
`/* eslint-env browser */`
`document.addEventListener('DOMContentLoaded', async () => {`
`  const testHash = 'QmZEQBTF2YGsrfzexpLcmYeZ4QjqciKFC6ZLSDtr8kp8jW'`
`  const repoPath = 'ipfs-' + Math.random()`
`  const node = await Ipfs.create({ repo: repoPath })`
`  Hls.DefaultConfig.loader = HlsjsIpfsLoader`
`  Hls.DefaultConfig.debug = false`
`  if (Hls.isSupported()) {`
`    const video = document.getElementById('img')`
`    const hls = new Hls()`
`    hls.config.ipfs = node`
`    hls.config.ipfsHash = testHash`
`    hls.loadSource('master.m3u8')`
`    hls.attachMedia(img)`
`    hls.on(Hls.Events.MANIFEST_PARSED, () => img.play())`
`  }`
`})`

**Comment by Slender1808** [comment]
I found this example but when I try to run it says variable IPFS has not been set
https://discuss.ipfs.io/t/how-to-load-image-from-ipfs-to-img-html-tag-with-js-ipfs/2695/2

**Comment by achingbrain** [comment]
The discuss post you've found shows you how to do it, but you need to include IPFS in your page somehow - the [examples folder](https://github.com/ipfs/js-ipfs/tree/master/examples) has various ways to do this.

Please use https://discuss.ipfs.io for 'how do I' type questions in future, this issue tracker is for IPFS development.
