### ISSUE TITLE
Safari Version 13.1.1 (15609.2.9.1.2) - Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'F.add')

### ISSUE THREAD

**Issue by adamprocter** [ipfs/js-ipfs#3130]
- **Version**:
0.46.0

- **Platform**:
Safari Version 13.1.1 (15609.2.9.1.2)

#### Severity:
  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
I have set up an IPFS node with js-ipfs within a vue webapp and this works great for uploading files in macOS Firefox, Firefox Dev Edition, Edge and Safari Technology preview  but on the release version of Safari it has a Unhandled Promise Rejection.  This could be my code to be fair, however as its working in other browsers I thought I would pop an issue here.

**Comment by achingbrain** [comment]
Can you please post a full stack trace and preferably put a demo repo together that demonstrates the problem?

**Comment by adamprocter** [comment]
I’ll try FYI all the code is here https://gitlab.adamprocter.co.uk/nn/nodenoggin/-/blob/master/app/src/components/UploadLayer.vue

**Comment by achingbrain** [comment]
You're getting an UnhandledPromiseRejection because the `saveIPFS` handler is async and it's being invoked outside of a `try/catch` block.

Please can you add a `try/catch` around the `for await..of` [here](https://gitlab.adamprocter.co.uk/nn/nodenoggin/-/blob/master/app/src/components/UploadLayer.vue#L102-108) and post the full stack trace here with the error that's being thrown?

**Comment by adamprocter** [comment]
Thanks have added try and catch to those methods as advised but unfortunately for some reason I cant even create the node now, maybe 0.47.0 broke my code completely

Transaction Inactive Error: A request was placed against a transaction which is currently not active, or which is finished.

will reply once I get over this new hurdle

**Comment by achingbrain** [comment]
Does the stack trace for the Transaction Inactive Error contain any ipfs/libp2p code?

**Comment by adamprocter** [comment]
Apologies I am not sure how to do a stack trace can you advise?

**Comment by achingbrain** [comment]
The error in the console may have some lines underneath it:

![image](https://user-images.githubusercontent.com/665810/86390207-92f38700-bc8f-11ea-90a4-f9e1cdee67ab.png)

**Comment by adamprocter** [comment]
I have consoled out the error: I dont think i want more nodes though.... 

LockExistsError: Lock already being held for file: ipfs/repo.lock
    LockExistsError index.js:8
    lock lock-memory.js:23
    _openLock index.js:192
    open index.js:113
UploadLayer.vue:96

**Comment by achingbrain** [comment]
That's a different error to the one above.  Have you got multiple nodes running on your page?

**Comment by adamprocter** [comment]
shouldn’t have… will check

**Comment by adamprocter** [comment]
hmm looks like I am now throwing a first DOMException: A request was placed against a transaction which is currently not active, or which is finished

**Comment by achingbrain** [comment]
That's the error I was interested in - can you paste the stack trace please?

**Comment by adamprocter** [comment]
<img width="1070" alt="Screenshot 2020-07-07 at 20 10 57" src="https://user-images.githubusercontent.com/123951/86830877-2103af00-c08e-11ea-855e-5c5a00e17d90.png">

DOMException: A request was placed against a transaction which is currently not active, or which is finished. UploadLayer.vue:96

Thats all it outputs at the moment

**Comment by thienpow** [comment]
i face the similar problem, 
if i am running the webpage on http://localhost:3000 it works for both Safari & Chrome & Firefox...
however if i am running the webpage on https://mydomain.com only Safari fail to connect to the go-ipfs daemon.  I think the CORS got a different requirements or format that Safari ask for.

**Comment by achingbrain** [comment]
@thienpow I don't think your issue is related, the issue here is around a DOMException thrown when accessing IndexedDB, not CORS headers.

**Comment by adamprocter** [comment]
updating to latest version of IPFS solved this issue
