### ISSUE TITLE
Pubsub support?

### ISSUE THREAD

**Issue by draeder** [ipfs/js-ipfs#3133]
Does js-ipfs support pubsub? 

If not, when? 

If so, is there any documentation for how to use it?

**Comment by achingbrain** [comment]
Yes, please see the [core-api docs for pubsub](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/PUBSUB.md) and the [pubsub browser example](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/examples/browser-pubsub/index.js).

Please use https://discuss.ipfs.io for 'How do I' questions in future, it's got great search & better solution longevity than Github issues.

**Comment by draeder** [comment]
Thanks Alex - I did post to the forum, but no-one seems to respond there.
