### ISSUE TITLE
Implementation bug in normaliseInput

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3138]
I am pretty sure following lines would throw `TypeError: iterator is not iterable` because `yield *` expression expects iterable and not an iterator.  

https://github.com/ipfs/js-ipfs/blob/8cb8c73037e44894d756b70f344b3282463206f9/packages/ipfs-core-utils/src/files/normalise-input.js#L73-L82

https://github.com/ipfs/js-ipfs/blob/8cb8c73037e44894d756b70f344b3282463206f9/packages/ipfs-core-utils/src/files/normalise-input.js#L114-L122

https://github.com/ipfs/js-ipfs/blob/8cb8c73037e44894d756b70f344b3282463206f9/packages/ipfs-core-utils/src/files/normalise-input.js#L191-L199

It is also worrying that no tests seem to catch that.

**Comment by Gozala** [comment]
Also it appears that parenthesis is in the wrong place here

https://github.com/ipfs/js-ipfs/blob/8cb8c73037e44894d756b70f344b3282463206f9/packages/ipfs-core-utils/src/files/normalise-input.js#L52

**Comment by achingbrain** [comment]
Please can you submit a PR with a failing test, and preferably, a fix.

**Comment by Gozala** [comment]
I'm working on the patch that adds tests and fixes.

**Comment by Gozala** [comment]
Here is the example that illustrates the issue:

```js
class IterableOf {
  constructor(...entries) {
    this.entries = entries
  }
  [Symbol.iterator]() {
    return new IteratorOf(...this.entries)
  }
}

class IteratorOf {
  constructor(...entries) {
    this.position = 0
    this.entries = entries
  }
  next() {
    if (this.position < this.entries.length) {
      return { done: false, value: this.entries[this.position++] }
    } else {
      return { done: true }
    }
  }
}

function * test () {
  const iterable = new IterableOf(1, 2, 3)
  const iterator = iterable[Symbol.iterator]()
  
  yield iterator.next().value
  yield * iterator
}

[...test()] // Uncaught TypeError: iterator is not iterable
```

I should note that browser built-ins (including generators) tend to return iterators that effectively have `[Symbol.iterator]() { return this }` and there for this doesn't appear like a problem. That said iterables are not required to return iterators are also iterables.

**Comment by achingbrain** [comment]
I don't think you can use `yield *` like that.  If I run your example I get:

```
  yield * iterator
  ^

TypeError: undefined is not a function
```

If I change it to a `for..of` I get:

```
  for (const thing of iterator) {
                      ^

TypeError: iterator is not iterable
```

Which is true, it's not iterable.  Something is iterable if it has a `[Symbol.iterator]` function that returns an iterator which the value of `iterator` does not.

**Comment by achingbrain** [comment]
Another problem is the iterators can have state, you can't just `yield *` the iterable:

```
function * test () {
  const iterable = new IterableOf(1, 2, 3)
  const iterator = iterable[Symbol.iterator]()

  yield iterator.next().value
  yield * iterable
}

console.info([...test()])
// [ 1, 1, 2, 3 ]
``

If you drop down to the low-level interface you can avoid it, which I guess it the solution here:

```javascript
function * test () {
  const iterable = new IterableOf(1, 2, 3)
  const iterator = iterable[Symbol.iterator]()

  yield iterator.next().value

  while (true) {
    const { value, done } = iterator.next()

    if (done) {
      break
    }

    yield value
  }
}

console.info([...test()])
// [ 1, 2, 3 ]
```

**Comment by Gozala** [comment]
> I don't think you can use `yield *` like that. If I run your example I get:

Yes that was what I was trying to illustrate. You see a different error because I'm guessing you ran it on V8 while I've run it on SpiderMonkey. They produce different error messages but result is the same.

**Comment by Gozala** [comment]
> Another problem is the iterators can have state, you can't just `yield *` the iterable:

That is why I introduced Peekables in #3151

https://github.com/ipfs/js-ipfs/blob/dcedb6654d4c5c151646d4901a8d85a3a657dea2/packages/ipfs-core-utils/src/files/normalise-input.js#L409-L452

**Comment by achingbrain** [comment]
> That is why I introduced Peekables in #3151

Yes, it was a good idea - I broke some similar code out into [it-peekable](https://www.npmjs.com/package/it-peekable)
