### ISSUE TITLE
[request] allow ignore error when not supported address when start ipfs

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#3139]
- **Version**:

- **Platform**:

- **Subsystem**:

#### Description:

> websocket-star swarm addresses are not supported

in 0.47

it is ok if ipfs is running in our env
but !!
is is super hard for update users setting, tell them update the setting

so i hope can have a setting , ignore throw error for this

**Comment by achingbrain** [comment]
It's throwing an error because your configuration is invalid because you are using an unsupported swarm addresses.

If the error is not thrown, the user may think the address is supported and then wonder why it doesn't work.

Can you not just remove the address from your configuration?

**Comment by bluelovers** [comment]
> There are no websocket-star addresses in the default configuration,

the setting already add into setting from old version at user client by my script
they didn't know any about ipfs/coding or how to follow step to fix it

so i hope can have a `option` for ignore it, make it not throw error

**Comment by achingbrain** [comment]
We cannot ignore invalid config on startup because it will cause the node to function in a different way to the users' expectation.

If your upgrades are by script, you can automate it with something like:

```console
$ npx json -I -f ~/.jsipfs/config -e 'this.Addresses.Swarm = this.Addresses.Swarm.filter(addr => !addr.includes("p2p-websocket-star"))'
```

**Comment by bluelovers** [comment]
https://github.com/ipfs/js-ipfs/pull/3163

https://github.com/ipfs/js-ipfs/pull/3164
