### ISSUE TITLE
`--json` options for `stats repo`, `repo stat` output as json

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#3142]
- **Version**:

- **Platform**:

- **Subsystem**:

**Comment by achingbrain** [comment]
Since you want the output in JSON, I'm assuming you're trying to do something programatically, in which case why not just use the HTTP API as it does what you want already?

If you're writing shell scripts you can use wget/curl:

```console
$ curl -X POST http://localhost:5002/api/v0/repo/stat
{"NumObjects":"20","RepoSize":"40944","RepoPath":"/path/to/.jsipfs","Version":"8","StorageMax":"9007199254740991"}
```

**Comment by bluelovers** [comment]
because 

1. server maybe will can't start
2. will not know server port
3. find profile path for edit before start server

**Comment by achingbrain** [comment]
You're trying to get the repo path, right?

`jsipfs repo stat` works offline and the output is of a fixed format, can you not just parse the output of the command with a regex or sed or something?

This works for me:

```console
$ jsipfs repo stat | sed -n "s/^RepoPath:[[:space:]]*\(.*\)$/\1/p"
/Users/me/.jsipfs
```

**Comment by achingbrain** [comment]
I'm going to close this as I assume it's not needed any more.
