### ISSUE TITLE
IPNS not resolvable from other node

### ISSUE THREAD

**Issue by HLK65** [ipfs/js-ipfs#3147]
- **Version**:
js-ipfs {version: "0.41.2", repo: 7, commit: ""}

- **Platform**:
Win 10 Chrome Version 83.0.4103.116
Node.js v12.17.0

- **Subsystem**:
IPNS

#### Severity:
  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
I’ve got a js-ipfs application adding a file and publishing the cid at an ipns address. From the same node I can resolve the ipns entry but not from any other. If I manually copy over the CID however I can retrieve the file.

```
node.name.publish(cid, {
        key: keyName,
        allowOffline: false,
        lifetime: "168h"
    })
```
`node.name.resolve(addr)`

#### Steps to reproduce the error:
Start up two browser nodes, on the first add something and publish, on the second try to resolve

also discussed in the forums https://discuss.ipfs.io/t/ipns-not-resolvable-from-other-node/8624

**Comment by achingbrain** [comment]
@vasco-santos is helping you out in the forum.  I'm going to close this issue, if it turns out to be a bug we can reopen it.
