### ISSUE TITLE
Fix racing condition on adding directories

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#315]
A racing condition was introduced when adding directories 'recursively' 

https://github.com/ipfs/js-ipfs/pull/312#issuecomment-224209639

It doesn't happen always, we need to make a test that always detects it and fix it

**Comment by dignifiedquire** [comment]
This https://github.com/ipfs/js-ipfs/pull/390/commits/ac629eafa97ed94c6d9b82b2a88414be05110a21 should fix the issue, but I am not a 100% sure as I couldn't reproduce the referenced race myself.

**Comment by diasdavid** [comment]
Can you add a test with a lots of tiny files (like 100) and at least 10 levels of nest'ness just to be sure? Thank you!

**Comment by dignifiedquire** [comment]
> Can you add a test with a lots of tiny files (like 100) and at least 10 levels

All the files :D

**Comment by diasdavid** [comment]
Note that sorting on the client should not matter, go-ipfs doesn't expect the things to come sorted through the http-api. Files are hashed first and them the dir nodes are constructed after, once there is no more files to add to the dir (flush: false) or keep getting recreated (flush: true)

**Comment by dignifiedquire** [comment]
I added the sorting to make it easier to test, as it makes the output deterministic.

**Comment by diasdavid** [comment]
A good test to add is to add the same dir, but by a different order.

**Comment by dignifiedquire** [comment]
Race is still there :( seems to be related to how the chunker works rather than how we use it from js-ipfs :(

**Comment by diasdavid** [comment]
@dignifiedquire is this still a bug with the new pull-streams based unixfs engine?

**Comment by dignifiedquire** [comment]
Never seen it in pull-streams land
