### ISSUE TITLE
Test Failure: should add buffer bigger than Hapi default max bytes (1024 * 1024)

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3169]
I noticed that #3151 started to fail in CI following test:

https://github.com/ipfs/js-ipfs/blob/f20cdf153c7364051874f8d3c1fbe2cae007e950/packages/ipfs/test/http-api/inject/files.js#L100-L121

I could not reproduce that locally, until I did fresh `npm install` after which it started to fail. It appears to fail with current master as well. I'm guessing minor update of some library introduced this regression.

**Comment by achingbrain** [comment]
This should be fixed now, please trigger a new build.

**Comment by jacobheun** [comment]
Please reopen if this is still a problem.
