### ISSUE TITLE
TypeError: Cannot read property 'public' of undefined @createFromPrivKey

### ISSUE THREAD

**Issue by VandeurenGlenn** [ipfs/js-ipfs#3175]
**Version**:
0.46
**Platform**:
Windows 10 64-bit

**Subsystem**:

#### Severity:
  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:

Works fine before building with electron-builder.

#### Steps to reproduce the error:
```
ipfs.create({repo})
```

**Comment by achingbrain** [comment]
Can you please give a fuller code example that shows the problem or preferably a link to a repo?

**Comment by VandeurenGlenn** [comment]
@achingbrain Sorry, I was making code example when I started figuring out what the problem was.
I haven'thad the time to look further into, but if I remember correctly has to do with peer-id and libp2p-crypto/keys/rsa.
I'll check tomorrow, think it's a dependency mismatch issue.

**Comment by achingbrain** [comment]
That sounds likely, there have been some changes in libp2p recently around swapping out PeerInfo objects for ones that have less heave crypto deps.

**Comment by jacobheun** [comment]
@VandeurenGlenn were you able to check the dependency issue here? If there is still an issue please provide clearer steps to reproduce this issue.

**Comment by VandeurenGlenn** [comment]
@jacobheun I was, it's a dependency issue, manual updating everything worked, I can give you the exact versions once home, But is basically installing an older version of libp2p-crypto and building/packaging the electron app (doesn't happen when just running from source).

**Comment by jacobheun** [comment]
Okay, I'm going to close this for now. If there's a reproducible dependency list that causes this we can reopen as needed.
