### ISSUE TITLE
ipfs-http-client 0.45.0 add client do not return async iterable anymore

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs/js-ipfs#3177]
Starting from ipfs-httpclient@0.41.0 the client add command returned an async iterable as described in the migration guide:
https://gist.github.com/alanshaw/04b2ddc35a6fff25c040c011ac6acf26
However the latest available:
https://cdn.jsdelivr.net/npm/ipfs-http-client@45.0.0/dist/index.min.js
Changed this behaviour and returns an object { cid, path, size }
Could you confirm this behaviour ?
Thanks

**Comment by achingbrain** [comment]
Yes, please see the [Core API](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsadddata-options) docs for `ipfs.add` - sorry the link to the migration guide was out of date, I've updated it.  You can find the newer version [here](https://github.com/ipfs/js-ipfs/blob/master/docs/MIGRATION-TO-ASYNC-AWAIT.md), but in short `ipfs.add` adds and returns single items, `ipfs.addAll` adds and returns multiple items.

There's also a [blog post](https://github.com/ipfs/blog/blob/post/js-ipfs-0-48-0/content/post/104-js-ipfs-0.48.md) in the wings that's waiting some reviews before it goes live that explains the reasoning behind the change.

**Comment by xmaysonnave** [comment]
@achingbrain Thanks for your feedback. 
I'll take a look to your updated migration guide.
Feel free to close this ticket or keep it live for a while to let other users to be warned.
