### ISSUE TITLE
ipfs faill add to dependencies on windows with node.js 14+

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#3190]
- **Version**:

- **Platform**: 
  - windows 10 x64
  - node v14.5.0

- **Subsystem**:

#### Steps to reproduce the error:

- yarn run test:install:yarn
- npm run test:install:npm

```
ipfs in dependencies false
exists yarn.lock false
exists package-lock.json false
```

[test-install-ipfs.zip](https://github.com/ipfs/js-ipfs/files/4957625/test-install-ipfs.zip)

**Comment by achingbrain** [comment]
We've been waiting on Hapi to support Node 14 - they've only just started to release node 14 compatible modules so please downgrade to node LTS for the time being.

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/88147509-e07c6780-cc2f-11ea-9c56-3acb7b01c7c3.png)

https://github.com/hapijs/hapi

**Comment by achingbrain** [comment]
That file was changed months ago, yes, but they only actually released Hapi with that change in last week and it usually takes a bit of time for the various modules in the ecosystem to catch up.

Please downgrade node LTS for the time being.
