### ISSUE TITLE
Replace node Buffers with Uint8Arrays

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3220]
In order to treat browsers as first-class citizens, we should not use modules from node core unless we can absolutely guarantee that the code we are writing will not run in a browser.

The next generation of multiformats & IPLD modules will also be `Uint8Array`s all the way down so embracing more modern formats will mean the upgrade path easier to follow when they are ready for use.

Modern JavaScript runtimes have `TypedArray`s such as `Uint8Array` backed by `ArrayBuffer`s, as well as `DataView`s that wrap an `ArrayBuffer` and allow you to do bit-twiddly operations like writing little endian 32 bit floats at arbitrary offsets, etc.

Node's `Buffer` module pre-dates all of this but since node v3 it extends the `Uint8Array` class, so we should be able to treat `Buffer`s as `Uint8Array`s internally in our stack, though some dependencies may require `Buffer`s as input until they too can be refactored.

# PRs to modules

## IPFS

- [x] https://github.com/ipfs/js-ipfsd-ctl/pull/531
- [x] https://github.com/ipfs/js-ipfs-block-service/pull/105
- [x] https://github.com/ipfs/js-ipfs-repo/pull/253
- [x] https://github.com/ipfs/js-ipfs-repo-migrations/pull/25
- [x] https://github.com/ipfs/js-ipfs-unixfs/pull/69
- [x] https://github.com/ipfs/js-ipfs-bitswap/pull/251
- [x] https://github.com/ipfs/js-ipns/pull/67
- [x] https://github.com/ipfs/js-ipfs-http-response/pull/55
- [x] https://github.com/ipfs/interop/pull/107
- [x] https://github.com/ipfs/js-ipfs/pull/2771
- [x] https://github.com/ipfs/js-ipfs/pull/3237

## IPLD

- [x] https://github.com/ipld/js-ipld-git/pull/71
- [x] https://github.com/ipld/js-ipld/pull/287
- [x] https://github.com/ipld/ipld-in-memory/pull/18
- [x] https://github.com/ipld/js-ipld/pull/286
- [x] https://github.com/ipld/js-ipld-block/pull/54
- [x] https://github.com/ipld/js-ipld-zcash/pull/60
- [x] https://github.com/ipld/js-ipld-git/pull/70
- [x] https://github.com/ipld/js-ipld-ethereum/pull/69
- [x] https://github.com/ipld/js-ipld-bitcoin/pull/65
- [x] https://github.com/ipld/interface-ipld-format/pull/55
- [x] https://github.com/ipld/js-ipld-dag-cbor/pull/134

## libp2p

- [x] https://github.com/libp2p/js-libp2p-mplex/pull/114
- [x] https://github.com/libp2p/js-libp2p-tcp/pull/135
- [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/106
- [x] https://github.com/libp2p/js-libp2p-secio/pull/124
- [x] https://github.com/libp2p/js-libp2p-record/pull/24
- [x] https://github.com/libp2p/js-libp2p-tcp/pull/134
- [x] https://github.com/libp2p/js-libp2p-utils/pull/9
- [x] https://github.com/libp2p/js-libp2p-interfaces/pull/57
- [x] https://github.com/libp2p/js-libp2p-kad-dht/pull/202
- [x] https://github.com/libp2p/js-peer-id/pull/127
- [x] https://github.com/libp2p/js-libp2p-crypto/pull/180
- [x] https://github.com/libp2p/js-libp2p-floodsub/pull/109
- [x] https://github.com/libp2p/js-libp2p-pubsub/pull/70
- [x] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/118
- [x] https://github.com/libp2p/js-libp2p-mdns/pull/97
- [x] https://github.com/libp2p/js-libp2p-webrtc-star/pull/244
- [x] https://github.com/libp2p/js-libp2p-websockets/pull/115
- [x] https://github.com/libp2p/js-libp2p-interfaces/pull/59
- [x] https://github.com/NodeFactoryIo/js-libp2p-noise/pull/70
- [x] https://github.com/libp2p/js-libp2p-secio/pull/125
- [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/107
- [x] https://github.com/libp2p/js-libp2p-kad-dht/pull/203
- [x] https://github.com/libp2p/js-libp2p-tcp/pull/136
- [x] https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/42
- [x] https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/35
- [x] https://github.com/libp2p/js-libp2p/pull/730
- [x] https://github.com/libp2p/js-libp2p-daemon/pull/41
- [x] https://github.com/libp2p/js-libp2p-daemon-client/pull/42
- [x] https://github.com/libp2p/interop/pull/42

## Multiformats

- [x] https://github.com/multiformats/js-cid/pull/117
- [x] https://github.com/multiformats/js-multiaddr-to-uri/pull/45
- [x] https://github.com/multiformats/js-mafmt/pull/59
- [x] https://github.com/multiformats/js-multiaddr/pull/140
- [x] https://github.com/multiformats/js-multicodec/pull/63
- [x] https://github.com/multiformats/js-multihashing-async/pull/78
- [x] https://github.com/multiformats/js-multihash/pull/92
- [x] https://github.com/multiformats/js-multistream-select/pull/90
- [x] https://github.com/multiformats/js-uri-to-multiaddr/pull/12
- [x] https://github.com/multiformats/js-cid-tool/pull/10

## Other

- [x] https://github.com/ipfs-shipyard/is-ipfs/pull/34
- [x] https://github.com/jacobheun/it-handshake/pull/2
- [x] https://github.com/mikeal/dag-cbor-links/pull/61

**Comment by Weedshaker** [comment]
We could also adjust the examples. Eg.: https://github.com/ipfs/js-ipfs/tree/master/examples/ipfs-101

From
`console.log('Added file contents:', Buffer.concat(chunks).toString())`

To
`console.log('Added file contents:', chunks.toString())`

or at least make a note about the usage within Node/Browser.

**Comment by achingbrain** [comment]
@Weedshaker when this effort bubbles up to this module, yes, the documentation will be updated.

**Comment by jacobheun** [comment]
Some notes on transitioning:

- If `Buffer.allocUnsafe` is being used it should be retained for Node.js. There is no alternative for Uint8Array and there is a significant performance drop switching to Uint8Array only. Hot paths in Node.js should continue to use `Buffer.allocUnsafe`.
- `Buffer.slice(...)` should become `Uint8Array.subarray(...)`. Uint8Array's `slice` does a clone instead of referencing the underlying memory, which Buffer's `slice` and `subarray` does. `subarray` can be used for both Buffer and Uint8Array.

**Comment by achingbrain** [comment]
It's worth noting that `.subarray` cannot be used with [BufferList](https://www.npmjs.com/package/bl)s, which occasionally complicates matters.

**Comment by mikeal** [comment]
BufferList has “shallowSlice” which is roughly what subarray does, just returning a new BufferList instead of Uint8array. But I would imagine that what you often want from BufferList is still .slice() because you probably need a complete binary value.

-Mikeal
________________________________

**Comment by wemeetagain** [comment]
Is `BufferList` usage to be replaced with `Uint8ArrayList` (I don't think it currently exists)?

**Comment by achingbrain** [comment]
The push here is really to have our ecosystem modules accept `Uint8Array`s in place of `Buffer`s and have them work without throwing errors.

For converting `BufferList` to `Uint8ArrayList` I think you'd have to do it for a module if it makes sense, but it may not - lots of our modules wrap other modules (crypto ones in particular) that only accept `Buffer`s/`BufferList`s so from a practical point of view it may not be necessary or desirable until/if these wrapped modules can be refactored to accept `Uint8Array`s.

**Comment by achingbrain** [comment]
This shipped in js-ipfs@0.50.0! We did it!

**Comment by HexaField** [comment]
https://github.com/ipfs/js-datastore-idb seems to have been missed

**Comment by achingbrain** [comment]
@HexaField until https://github.com/ipfs/js-datastore-idb/issues/6 is resolved, that module shouldn't be used anywhere in the stack, instead we should be using [datastore-level](https://github.com/ipfs/js-datastore-level) - are you seeing problems?
