### ISSUE TITLE
Applying mtime with HTTP API /api/v0/files/write doesn't seem to work

### ISSUE THREAD

**Issue by mrh42** [ipfs/js-ipfs#3225]
- **Version**: interface-ipfs-core version: ^0.139.0
ipfs-http-client version: ^46.0.0
Repo version: 8
System version: x64/linux
Node.js version: v12.18.3
Commit: e7396bc883ad5a6620e2f7bc32e7baf4e636e230

- **Platform**: Linux i 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:

#### Description: 
Using curl I can apply an mtime to a MFS file with /api/v0/files/touch but not with /api/v0/files/write.

#### Steps to reproduce the error:
% curl -X POST "http://172.30.16.17:5002/api/v0/files/touch?arg=/users/mrh-i/t.txt&mtime=1697263111"

% curl -X POST -F file=@mrh.txt "http://172.30.16.17:5002/api/v0/files/write?arg=/users/mrh-i/x.txt&mtime=1697263111&create=true"

% jsipfs files ls -l /users/mrh-i/
-rw-r--r--	Oct 13, 2023, 10:58:31 PM PDT	t.txt	QmY1qYmfmwjf9CeB3tMNYcuJaVcHZ7oFXiSDqqPmPQfRrF	0
-rw-r--r--	-	x.txt	Qme8gXcjgesRXRiLcmdDUmupfaaa1yKHYfBbNS6NU7EVGc	945

**Comment by achingbrain** [comment]
`ipfs.files.write` takes args as a multipart request, including specifying the mtime as a header in the multipart part.

See how the http client does it for an example: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/files/write.js
