### ISSUE TITLE
Make `entry.type` consistent arcoss various APIs

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3229]
Following APIs seem to return different thing for `entry.type`:

- `ipfs.files.ls`->  type: 1 (While docs say it's either 'file' | 'dir' https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsfileslspath-options)
- `ipfs.files.stat` -> type: 'directory' 
- `ipfs.ls` -> type: 'dir' (Docs don't specify but given others been document as 'directory' one would assume the same)

This can be very confusing when working with all these APIs as just like ipfs-webui does.

I would like to propose normalizing to a consistent variants for `type`.

**Comment by achingbrain** [comment]
Yes please, this has been on the list for ages.  All type fields should be one of the [UnixFS data types](https://github.com/ipfs/specs/blob/master/UNIXFS.md#data-format), my preference is for lower case, kebab-case strings.

See also:

- https://github.com/ipfs/js-ipfs/issues/2948#issuecomment-603759763
- https://github.com/ipfs/js-ipfs/pull/2939
- https://github.com/ipfs/go-ipfs/issues/5026

**Comment by achingbrain** [comment]
Also see ipfs/go-ipfs#7553 for another stat command that's being added.

**Comment by achingbrain** [comment]
Closing as this issue is very stale.
