### ISSUE TITLE
IPFS.ADD() API cannot be called properly

### ISSUE THREAD

**Issue by abbasogaji** [ipfs/js-ipfs#3230]
// i called the below;
const file = await ipfs.add(globSource('foo.txt', { recursive: true }))
// and getting SyntaxError: await is only valid in async function

- **Version**:

- **Platform**:

- **Subsystem**:

**Comment by achingbrain** [comment]
You need to add the async keyword to your function.

Eg:

```js
async function foo () {
  const bar = await ipfs.add(...)
}
```

**Comment by abbasogaji** [comment]
@achingbrain 

the code block written is an example from 
https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#example
```js
const IpfsHttpClient = require('ipfs-http-client')
const { globSource } = IpfsHttpClient
const ipfs = IpfsHttpClient()

const file = await ipfs.add(globSource('./docs', { recursive: true }))
console.log(file)

/*
{
  path: 'docs/assets/anchor.js',
  cid: CID('QmVHxRocoWgUChLEvfEyDuuD6qJ4PhdDL2dTLcpUy3dSC2'),
  size: 15347
}
{
  path: 'docs/assets/bass-addons.css',
  cid: CID('QmPiLWKd6yseMWDTgHegb8T7wVS7zWGYgyvfj7dGNt2viQ'),
  size: 232
}
...
*/

```

**Comment by achingbrain** [comment]
The wrapping function is omitted to make the example more concise, it's assumed that the reader would be familiar with aync JavaScript, though maybe this is a mistake. Please submit a PR to improve the docs.

**Comment by LouisLiu00** [comment]
You should use the [async] keyword to define a function and use the [await] keyword inside the function.
