### ISSUE TITLE
webrtc-star/simple peer errors, setRemoteDescription

### ISSUE THREAD

**Issue by tabcat** [ipfs/js-ipfs#3231]
- **Version**:
commit: "0425c84bbfb6af75e2dbf5db444ced577f728d23"
interface-ipfs-core: "^0.138.0"
ipfs-http-client: "^45.0.0"
repo: 8
version: "0.48.2"

- **Platform**:
uname -a: Linux xps 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
chromium --version: Chromium 84.0.4147.105 snap

- **Subsystem**:
libp2p-webrtc-star
libp2p-webrtc-peer

shown errors:
![logged errors](https://user-images.githubusercontent.com/36933094/90354554-41207980-e00f-11ea-82da-a4c960c01d5e.png)

js-libp2p-webrtc-star/src/index.js
![js-libp2p-webrtc-star/src/index.js](https://user-images.githubusercontent.com/36933094/90354593-60b7a200-e00f-11ea-8d62-d912839003c3.png)

libp2p-webrtc-peer/index.js:
![libp2p-webrtc-peer/index.js](https://user-images.githubusercontent.com/36933094/90354711-affdd280-e00f-11ea-8cdc-22a3005b0964.png)

#### Severity:
  Low - Everything seems to be working fine as far as webrtc-star discovery

#### Description:
After having https://alpha.sailplane.io open for a while (not sure how long unfortunately, I've had it open overnight idling) it will show ~20k errors logged relating to webrtc-star and simple peer. I've linked screenshots below

#### Steps to reproduce the error:
I've left the website idle for a while, haven't tracked time but it happens consistently.

**Comment by achingbrain** [comment]
`libp2p-webrtc-star` should not be overriding the message property of objects, could you please open an issue on https://github.com/libp2p/js-libp2p-webrtc-star ?

**Comment by tabcat** [comment]
Yes, I will open one now.

**Comment by jacobheun** [comment]
Closing this in favor of https://github.com/libp2p/js-libp2p-webrtc-star/issues/251
