### ISSUE TITLE
interface-ipfs-core: jsipfs doesn't pass .dag.get "should get only a CID, due to resolving locally only" over http

### ISSUE THREAD

**Issue by koivunej** [ipfs/js-ipfs#3242]
- **Version**:

```
$ jsipfs version --all
js-ipfs version: 0.49.0-e7396bc883ad5a6620e2f7bc32e7baf4e636e230
interface-ipfs-core version: ^0.139.0
ipfs-http-client version: ^46.0.0
Repo version: 8
System version: x64/linux
Node.js version: v13.14.0
Commit: e7396bc883ad5a6620e2f7bc32e7baf4e636e230
```

- **Platform**:

```
$ uname -a
Linux joonas-t495 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- **Subsystem**:

js-ipfs http API or **more likely js-ipfs-http-client** or whatever resolver ipfs-http-client calls, I am have trouble following the code once it leaves ipfs-http-client.

#### Severity:

Low, the test case must work without ipfs-http-client or directly.

#### Description:

The test case "should get only a CID, due to resolving locally only" doesn't pass when using jsipfs with ipfs-http-client "^46.0.0". I tried to get this passing in rust-ipfs. When my solution of returning the **destination** (or `cidPb`) similarly as returned for passing `dag/get` and `dag/resolve` test cases didn't work, I checked what does the jsipfs return:

```
{"Cid":{"/":"bafybeibyc73pdv76ycowjbdijjglqfxksrayhj6xl7il2ckeyemrgveppi"},"RemPath":"Data"}
```

(rust-ipfs would return the same value as I understand to be the correct solution: Cid matches the PbCid and RemPath is the remaining path in the next document on.)

The above result looks correct. The `result` in the test (from `ipfs.dag.get`) before assert looks like:

```
{"value":{"type":"Buffer","data":[73,32,97,109,32,105,110,115,105,100,101,32,97,32,80,114,111,116,111,98,117,102]},"remainderPath":""}
```

This is not a CID. After `dag/resolve` request a `block/get?path=pb%2FData&arg=cid&local-resolve=true` is sent and and responded with: `0a164920616d20696e7369646520612050726f746f627566` which corresponds to a single protobuf field 1 with "I am inside Protobuf" so perhaps it's the *whole* dagpb node.

I am quite surprised of the `block/get?path=` parameter on the second request. I would expect that to be ignored as it is being ignored; blocks API shouldn't IMHO be doing any projections as the "dag.get" API does.

#### Steps to reproduce the error:

1. run the interface-ipfs-core `--grep '^.dag.get should get only a CID, due to resolving'` tests against jsipfs by using ipfs-http-client
2. you might need remove timeout from the dag.get test suite as jsipfs takes a bit longer than 2000ms to start at least for me

Exact reproduction:
 1. clone latest rust-ipfs master: https://github.com/rs-ipfs/rust-ipfs.git
 2. enter `conformance/`
 3. run `./setup.sh`
 4. disable `.dag.get` test suite timeout in `conformance/node_modules/interface-ipfs-core/src/dag/get.js`
     * I did this by changing the `describe` second paramter from `() => { ... }` to `function() { ... }` to get access to `this` to call `this.timeout(0);` but there might be better alternatives
 5. run `IPFS_RUST_EXEC=jsipfs npm test -- grep '^.dag.get should get only a CID, due to resolving'`

Replace the `jsipfs` in `IPFS_RUST_EXEC` with whatever local means of starting. For rust-ipfs we don't have any special things going on w.r.t. launching it via js-ipfsd-ctl so this should just do `jsipfs init -p test --bits 2048` or similar followed by `jsipfs daemon`. That's all the command line args we support at least :)

Note the work to support `dag/resolve?local-only=true` is not in our master yet, it is being worked on https://github.com/rs-ipfs/rust-ipfs/pull/332 for a while.

**Comment by achingbrain** [comment]
This test is [skipped](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/test/http-api/interface.js#L42-L43) at the moment because local resolve only is not supported by js-IPFS yet, so it always follows the CID it's supposed to be returning and resolves the `Data` field inside the dag pb node which is why you get a buffer back and not a CID.

If a PR is opened adding support it can be unskipped but at the moment it would be expected to fail if run.

**Comment by koivunej** [comment]
@achingbrain aah apologies, I was not aware of your test config and had assumed all test skips were in the `interface-ipfs-core`. 

Just making sure if I understood the expected response here from the http api to be correct or not, since rust-ipfs does return the same at the moment:

> ```{"Cid":{"/":"bafybeibyc73pdv76ycowjbdijjglqfxksrayhj6xl7il2ckeyemrgveppi"},"RemPath":"Data"}```

Here the Cid is v1 representation of `QmS7cjaxs3Z4SMCLC2BVGWJCE1jVEnphmTRmKKsgDC2MMB` or the `cidPb` in the test case. I've undesrstood that local-resolve means stopping the walk at the first link, or in this case:

 1. open `cidCbor`
 2. follow key `pb` on the root map
 3. find link to `bafybeibyc73pdv76ycowjbdijjglqfxksrayhj6xl7il2ckeyemrgveppi` with `Data` remaining as path

Have I understood the feature correctly, or should the http response in this case be something entirely different?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

Assigning to @achingbrain to answer whether this issue is already resolved in Helia, or if this issue needs to be migrated to that repo!

**Comment by achingbrain** [comment]
Please upgrade to https://github.com/ipfs/js-kubo-rpc-client - it's a drop-in replacement for `ipfs-http-client` and where fixes and compatibility updates for working with Kubo will land.

Please open an issue on the `kubo-rpc-client` repo if the issue persists.
