### ISSUE TITLE
[feature request] a shared package for convert ( daemon / init ) options to ipfs cli argv

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#3254]
- **Version**:

- **Platform**:

- **Subsystem**:

#### Description:

a package for convert ( daemon / init ) options to ipfs cli argv

maybe name is `ipfs-argv`

https://github.com/ipfs/js-ipfsd-ctl/blob/14ad816489ff29800c5c7aae057fa857a0b77809/src/ipfsd-daemon.js#L81
https://github.com/ipfs/js-ipfsd-ctl/blob/14ad816489ff29800c5c7aae057fa857a0b77809/src/ipfsd-daemon.js#L158
https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/cli/parser.js
https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/cli/commands/daemon.js
https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/cli/commands/init.js

#### e.g.

> convert argv object to cli string

```
argv = {
  migrate: true
}
```

=> 

```
--migrate
```

> convert argv object to daemon option

```
argv = {
  migrate: true
}
```

=> 

```
daemonOption = {
   repoAutoMigrate: true
}
```

> convert daemon option to cli object

```
daemonOption = {
   repoAutoMigrate: true
}
```

=>

```
argv = {
  migrate: true
}
```

**Comment by achingbrain** [comment]
This functionality would be added to `ipfsd-ctl` primarily, then pulled out into a module if it's needed elsewhere.

Do you have a use-case outside of `ipfsd-ctl`?

**Comment by lidel** [comment]
Closing as stale, feel free to solve this using a third-party package.
