### ISSUE TITLE
for (await) syntax issue

### ISSUE THREAD

**Issue by duxiaofeng-github** [ipfs/js-ipfs#3259]
- **Version**:
0.49.1

- **Platform**:
iOS 11.1

![image](https://user-images.githubusercontent.com/1694541/91845057-1549f880-ec8b-11ea-8c88-bd5fdcf1069b.png)

#### Description:

mobile safari doesn't support await/async in for loop. so when i use ipfs.min.js directly, i got this error.

**DO NOT use for (await) syntax or transform it to es5 by babel will solve this issue**

![image](https://user-images.githubusercontent.com/1694541/91845104-2e52a980-ec8b-11ea-8332-d006f1feae78.png)

**Comment by achingbrain** [comment]
That's strange - is the version of Mobile Safari the same as the iOS version?

`for await..of` should be supported by [iOS Safari 11+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#Browser_compatibility).

**Comment by duxiaofeng-github** [comment]
> is the version of Mobile Safari the same as the iOS version

yes, but i did the test in the simulator, maybe it won't behave the same in real device.

even though it will still break in iOS safari 10 or below and those browsers not support this syntax.

**Comment by achingbrain** [comment]
iOS 11 was released in 2017, a quick search reveals [98.3% of people are on iOS 11+](https://david-smith.org/iosversionstats/) so I don't know how big of a problem this is.

**Comment by duxiaofeng-github** [comment]
yup, i get it done like you say by now. thanks for reply any way.
