### ISSUE TITLE
urlSource nonsupport  ipfs.addAll ?

### ISSUE THREAD

**Issue by yfs-2000** [ipfs/js-ipfs#3278]
- **Version**:46.1.1

- **Platform**:node

- **Subsystem**:

#### Steps to reproduce the error:
``` async function upImage  (){
        const result = []
        for await (const resultPart of ipfs.addAll([urlSource('https://img.el8v.io/6/1291687008598626304/0.jpg'),urlSource('https://img.el8v.io/6/1291687008598626304/1.jpg')])) {
            result.push(resultPart)
        }
        console.log(result);
    }
```

**Comment by achingbrain** [comment]
Is the intention here to end up with multiple CIDs corresponding to the files or to have a single directory that contains all of the files?

If it's the former, you could do this with:

```javascript
const files = [
  urlSource('http://...'),
  urlSource('http://...'),
  ...
]

const cids = await Promise.all(
  files.map(file => ipfs.add(file))
)
```

If it's the latter, do:

```javascript
const dir = await ipfs.addAll([{
  path: '/file-1',
  content: urlSource('http://...')
}, {
  path: '/file-2',
  content: urlSource('http://...')
}])
```

**Comment by yfs-2000** [comment]
> Is the intention here to end up with multiple CIDs corresponding to the files or to have a single directory that contains all of the files?
> 
> If it's the former, you could do this with:
> 
> ```js
> const files = [
>   urlSource('http://...'),
>   urlSource('http://...'),
>   ...
> ]
> 
> const cids = await Promise.all(
>   files.map(file => ipfs.add(file))
> )
> ```
> 
> If it's the latter, do:
> 
> ```js
> const dir = await ipfs.addAll([{
>   path: '/file-1',
>   content: urlSource('http://...')
> }, {
>   path: '/file-2',
>   content: urlSource('http://...')
> }])
> ```

Thank you for your reply, I am doing the second method because I find addAll is not available

**Comment by VladimirMikulic** [comment]
Hi @achingbrain! Is the `latter` solution code still working/recommended way in v56.0.1? Thanks!
