### ISSUE TITLE
"peerId must be an instance of peer-id" on webpack'd version of js-ipfs

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#3284]
- **Version**: 0.50.2

- **Platform**: Browser via `mocha-headless-chrome`

- **Subsystem**: libp2p

#### Description:
Running the tests for `orbit-db-store`, I find that this test works fine in node.js but when run in the browser (via minified webpack), it gives me the error: `peerId must be an instance of peer-id`

1. Test: https://github.com/orbitdb/orbit-db-store/blob/fix/replication-tests/test/replicator.spec.js
2. Webpack Config: https://github.com/orbitdb/orbit-db-store/blob/fix/replication-tests/conf/webpack.tests.config.js
3. PR (see CircleCI tests) https://github.com/orbitdb/orbit-db-store/pull/98

#### Steps to reproduce the error:

```bash
$ git clone https://github.com/orbitdb/orbit-db-store
$ cd orbit-db-store
$ make rebuild
```

Or you can view the error here in the CircleCI test results. https://app.circleci.com/jobs/github/orbitdb/orbit-db-store/573

**Comment by achingbrain** [comment]
Do you have multiple versions of `peer-id` in your dependency tree?  There should be only `0.14.1`.

**Comment by achingbrain** [comment]
How do I repro this?  I did:

```console
$ git clone https://github.com/orbitdb/orbit-db-store
$ cd orbit-db-store
$ make rebuild
$ npm test
```

It ran the tests in node and mocha-headless-chrome and they passed.  Doing the install has modified the `package-lock.json` file though.

**Comment by aphelionz** [comment]
Also `npm ls peer-id` shows 0.14.1 across the board

**Comment by achingbrain** [comment]
`peerId` is undefined - the tests are trying to get two browser nodes that don't have any listening addresses [to dial each other](https://github.com/orbitdb/orbit-db-test-utils/blob/master/connect-peers.js#L6-L7) (the `.addresses` array is empty).

That this worked previously may be something to do with the upgrade to libp2p@0.29.0 in the latest js-ipfs (cc @vasco-santos).

You may need to spin up a webrtc-star signalling server as part of the test so they can dial each other - we do [something similar](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/.aegir.js#L61-L65) in [our tests](https://github.com/ipfs/js-ipfs/blob/64b7fe41738cbe96d5a9075f0c01156c6f889c40/packages/ipfs/test/core/id.spec.js).

**Comment by aphelionz** [comment]
Ahhhhh of course. This can be closed. I know what to do. Thank you!
