### ISSUE TITLE
Discussion: IPFS.create({ ... }) should return same API regardless of the `init` and `start` options.

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3285]
At the moment `IPFS.create` will return API object that has different interface depending on `init` and `start` options:

https://github.com/ipfs/js-ipfs/blob/3ff833db6444a3e931db9b76bf74c3420e57ee02/packages/ipfs/src/core/index.js#L101-L118

It is kind of cool that one could do that in JS (and even make TS infer it properly), but I think it has enough drawbacks that I would like to make an argument against it:

1. It is difficult to document this kind of behavior. In fact documentation seems to incorrectly suggest that it returned object will implement IPFS Core API. And only vaguely mentions that initialization is different from creating because many special properties are set during initialization.
2. Unsurprisingly (per @lidel) some (of even our) code assumes that returned API object implements same interface.
3. This introduces side effects into the system. Some APIs will not be available before init and will be after init. This specific aspet is impossible to type in TS because types can just change in side effect of a call.
4. I think this is primary reason for `ApiManager` which introduces quite a bit complexity in exchange for unclear (at least to me) benefits.

I understand that IPFS node can not provide all the core functionality when it's not initialized / started. However I would propose to either (or both):

1. Have the same core API and throw error e.g. `not initialized` / `not started` error(s) when specific functionality is in-operational.
2. Have a way to distinguish between `'unitialized | started | initialized'` states so that function that is passed `IPFS API` object can asses what API subset can be used (without try catch or `subapi in`)
3. Have a different factory functions, for different API objects.
4. Remove side effects e.g. `api.init()` can return `InitilaizedAPI` instance,  without mutating the `api` itself.

**Comment by achingbrain** [comment]
This is a bug.  The API should be the same regardless of the node state, and any methods that require initialisation or a running node should throw if invoked.

I did some work to address this in #2762 which will be simpler to land after #3288.

**Comment by Gozala** [comment]
I'll work on this after typescript patches land

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
