### ISSUE TITLE
ipfs.add vs ipfs.addAll input types

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3290]
Currently `ipfs.add` will pass it's input to `ipfs.addAll` and return the last result.

Instead it should detect if it's been passed something that will yield multiple results and throw.

Refs: ProtoSchool/protoschool.github.io#498

**Comment by terichadbourne** [comment]
👋 @achingbrain Just checking in on the status of this one as we still have an open ProtoSchool issue to update the Regular Files API tutorial accordingly when we figure out the plan.

**Comment by achingbrain** [comment]
This will (finally) be fixed by #3900
