### ISSUE TITLE
"Missing IPLD format" error for known/registred format

### ISSUE THREAD

**Issue by simonovic86** [ipfs/js-ipfs#3300]
- **Version**:
0.50.2

- **Platform**:
Darwin XXXX 19.5.0 Darwin Kernel Version 19.5.0: root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

- **Subsystem**:
The affected core module is the `http` part of the`ipfs` core. The code that I pinpointed is [here](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/http/api/resources/dag.js).

#### Severity:
  **High** - The main functionality of the application does not work, API breakage, repo format breakage, etc.
#### Description:

In situation where ipfs-http-client uses dag-jose codec as a format, the IPFS instance cannot respond, since it cannot find the codec even if it's registered on bootstrap of the instance:

```js
{
	ipld: {formats: [dagJoseFormat]}
}
```

Note: formats are added to the`IPFS` node and `ipfs-http-client` both.

#### Steps to reproduce the error:

Creating the `ipfs-http-client`:
```ts
      import dagJose from 'dag-jose'
      import multiformats from 'multiformats/basics'
      import legacy from 'multiformats/legacy'
      
      multiformats.multicodec.add(dagJose)
      const format = legacy(multiformats, dagJose.name)

      const ipfsClient = ipfsClient({
        url: opts.ipfsHost, ipld: { formats: [format] }
      })
```

Creating the `IPFS` instance:

```ts
      import dagJose from 'dag-jose'
      import multiformats from 'multiformats/basics'
      import legacy from 'multiformats/legacy'
      
      multiformats.multicodec.add(dagJose)
      const format = legacy(multiformats, dagJose.name)

      const ipfs = await Ipfs.create({ ipld: { formats: [format] } })
```

**The IPFS instance cannot find the codec for the payload sent via `ipfs-http-client`.**

**Comment by oed** [comment]
So the issue seems to be that only hard coded codecs are used here: https://github.com/ipfs/js-ipfs/blob/3a0db1aa0229ecf6b719cc4eae4a98e5b56e4da3/packages/ipfs/src/http/api/resources/dag.js#L209-L213

When what should happen is that it should use the codecs provided as a config option to the ipfs constructor.

**Comment by simonovic86** [comment]
I've opened a [PR](https://github.com/ipfs/js-ipfs/pull/3309) which enables passing custom formats to solve the issue.

**Comment by jacobheun** [comment]
With custom codec support in 0.52, https://github.com/ipfs/js-ipfs/tree/ipfs%400.52.0/examples/custom-ipld-formats, can this be closed now?

**Comment by oed** [comment]
yep!
