### ISSUE TITLE
cli: doc: OPTIONS output not working

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/js-ipfs#331]
When I run the `--help` command in the CLI for js-ipfs commands, I get the following: 

```
$ node src/cli/bin.js id --help
Usage: bin.js id [OPTIONS]

  Shows IPFS Node ID info
```

What does `[OPTIONS]` mean? Shouldn't it show the options? Let's look at id.js: 

```js
module.exports = Command.extend({
  desc: 'Shows IPFS Node ID infos',

  options: {
    format: {
      alias: 'f',
      type: 'string'
    }
  },

  run: (name) => {
    ...
  }
})
```

Why isn't `[--format | -f]` output?

**Comment by diasdavid** [comment]
Unfortunately that is not a given for free with [ronin](https://www.npmjs.com/package/ronin), the CLI toolkit we use.

**Comment by dignifiedquire** [comment]
We should really fix this and probably switch away from ronin. Which is simply not being maintained anymore.

**Comment by RichardLitt** [comment]
PRed a pretty easy fix for this. However, let's wait until we resolve https://github.com/ipfs/notes/issues/139.

**Comment by diasdavid** [comment]
@dignifiedquire we can collaborate to make it better - https://github.com/vdemedes/ronin/issues/37

**Comment by dignifiedquire** [comment]
Tbh it does not look like anything is happening on ronin. But there is [yargs](https://github.com/yargs/yargs), which looks really awesome and also allows for the command structure that we are after, see [here](https://github.com/yargs/yargs#example-command-hierarchy-using-commanddir) for an example.
