### ISSUE TITLE
interface-ipfs-core link does not work anymore

### ISSUE THREAD

**Issue by imestin** [ipfs/js-ipfs#3311]
- **Version**:
0.50.2

- **Platform**:
Firefox v68

- **Subsystem**:
documentation

#### Severity:
Very low

#### Description:
The link does not work anymore.
I think this is the correct link: https://github.com/ipfs/js-ipfs/tree/master/docs/core-api

#### Steps to reproduce the error:
On this page https://github.com/ipfs/js-ipfs/tree/796d7ef09405689220353388d4b12bb82689633e/examples/ipfs-101
click on interface-ipfs-core

**Comment by achingbrain** [comment]
Thanks for pointing this out - would you like to submit a PR that fixes the link?

**Comment by imestin** [comment]
yes, I will do it.
