### ISSUE TITLE
[feature request] ipfs.addAll directories but use content hash for path names

### ISSUE THREAD

**Issue by tabcat** [ipfs/js-ipfs#3321]
#### Short-ish explanation:
I want ipfs.addAll to optionally upload a directory source WITHOUT the path name for [FileObjects](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#fileobject) in the [FileStream](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#filestream) so that the names of the files 
 and folders are not included in the unixfs structure.

#### Change in behavior:
`/Qm<hash1>/dir2/image.png` -> `/Qm<hash1>/Qm<hash2>/Qm<hash3>`

#### Context:
I want to deterministically hide the names for privacy and this seems like the best way to do that. In [my use case](https://github.com/cypsela/sailplane-node) I already maintain an encrypted db tracking ipfs FILE hashes of encrypted content to human readable paths/names.

**Comment by tabcat** [comment]
I may just use ipfs.add to upload each file from the [FileStream](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#filestream) and rebuild the directory structure with ipfs.object.put afterward.

**Comment by achingbrain** [comment]
If you have a deeply nested directory structure, the names of the files in the directories become baked-in to the DAG so if you know the hashes it's trivial to work out what the folder structure was.

E.g. given:

```
└── foo/
    └── bar/
       └── baz.txt
```

You'd get `/Qm<hash1>/bar/baz.txt`.  If you got `/Qm<hash1>/Qm<hash2>/Qm<hash3>` and used `ipfs.ls` you'd see the folder structure:

```console
$ ipfs ls /Qm<hash1>
Qm<hash2> - bar/
```

```console
$ ipfs ls /Qm<hash2>
Qm<hash3> - baz.txt
```

If you really want to obfuscate the file names, you can use `ipfs.add` and recreate the structure as you've discovered, though you may wish to consider using `ipfs.object.addLink` instead of `ipfs.object.put` as it's a bit simpler.

**Comment by tabcat** [comment]
Thanks, I will look at `ipfs.object.addLink`. I used it for [computing directory addresses](https://github.com/cypsela/sailplane-node/blob/5b56a2f1fa5df6fa4ac120b627f6f70f0ad639fa/src/SharedFS.js#L277) but I switched to `ipfs.object.put` because you can add multiple links at a time. Now I dont think I need to compute ipfs directory structure while uploading so I may not need to touch ipfs.object again for this part.

I think I will have to make a very simple version of the tree-builder from the unixfs-importer that gets `normalizeInput(source<FileStream>)` and is mainly concerned with dir paths and `FileObjects`.

I believe for my use, when uploading, I only need to add file content to ipfs then add the dir and file paths and file cids to the mutable file structure.

**Comment by tabcat** [comment]
here's what I did if anyone has to do something similar. will close issue now.

https://github.com/cypsela/sailplane-node/commit/d41c0dbe9e32a9194773536dcb301d0cd635fb10
takes normalized `FileStream` source as uploader input.
a simple version of the treeBuilder for ipfs.addAll builds the directory structure from source.
single files are uploaded without paths with ipfs.add.
directory structure paths with file paths mapped to file cids are added to a mutable file system.
able to compute mutable file system cids  from paths at later date.
