### ISSUE TITLE
bug: cannot pin dag-cbor nodes with binary values inside them

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs#3323]
@Gozala @rvagg looks like some change we’ve made in the most recent codecs is not readable from the dag-cbor library currently shipping with `js-ipfs`.

I got this error using `ipfs.pin.add()` at the point where it tries to parse the graph recursively for pinning after I loaded a bunch of blocks into `js-ipfs` I created with the latest codec.

```
Error: Extraneous CBOR data found beyond initial top-level object
    at Object.exports.deserialize (/root/dkv/node_modules/dag-cbor-links/node_modules/ipld-dag-cbor/src/util.js:161:11)
    at links (/root/dkv/node_modules/dag-cbor-links/index.js:6:16)
    at /root/dkv/node_modules/dag-cbor-links/index.js:29:21
    at Generator.next (<anonymous>)
    at PinManager._walkDag (/root/dkv/node_modules/ipfs/src/core/components/pin/pin-manager.js:60:30)
    at async all (/root/dkv/node_modules/it-all/index.js:13:20)
    at async PinManager.fetchCompleteDag (/root/dkv/node_modules/ipfs/src/core/components/pin/pin-manager.js:247:5)
    at async PinManager.pinRecursively (/root/dkv/node_modules/ipfs/src/core/components/pin/pin-manager.js:94:5)
    at async pinAdd (/root/dkv/node_modules/ipfs/src/core/components/pin/add-all.js:26:11)
    at async addAll (/root/dkv/node_modules/ipfs/src/core/components/pin/add-all.js:40:7) 
```

If you’re interested in the code that generated there error just comment out this line https://github.com/mikeal/dkv/blob/main/index.js#L79

**Comment by rvagg** [comment]
it'd be good to see the block that it's failing on

I introduced this error but it's a pretty important error.

As a way to debug, maybe edit the dependency @ `/root/dkv/node_modules/dag-cbor-links/node_modules/ipld-dag-cbor/src/util.js` and do this near line 161:

```js
  if (all.length !== 1) {
    console.log(Buffer.from(data).toString('hex'))
    console.log(all)
    throw new Error('Extraneous CBOR data found beyond initial top-level object')
  }
```

It'd be interesting to see if `all.length` is `>1` or maybe even `0` somehow. If it's `>1` then we might have a weird encoding situation.

**Comment by mikeal** [comment]
@rvagg here’s what i’ve got

```
0000080000000000000000000000000000000000000000000000000000000000
[
  0, 0, 8, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0
]
```

**Comment by mikeal** [comment]
btw, the only thing that ever gets created is a `{ hello: ‘world’ }` block and some `iamap` blocks to store a link to that block.

**Comment by rvagg** [comment]
Yeah, that's a weird encode situation. We're going to need to backtrack to see how that block got created in the first place.

As CBOR, before I introduced this "extraneous bytes" error, only the first byte would be decoded and your block would simply be `0` and the remainder of the bytes would be dropped entirely.

```
> borc.decode(Buffer.from('0000080000000000000000000000000000000000000000000000000000000000', 'hex'))
0
```

CBOR is seeing 32 _different_ chunks encoded separately and smushed together, kind of like line-delimited JSON but it's just "valid chunk delimited CBOR" for streaming - which we don't (can't) support for IPLD.

```
> borc.decodeAll(Buffer.from('0000080000000000000000000000000000000000000000000000000000000000', 'hex'))
[
  0, 0, 8, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0
]
```

You might want to do some printing for how the blocks are made in the first place.

**Comment by mikeal** [comment]
figured this out with @rvagg’s help. the fix was in `dag-cbor-links` and the problem is actually on the read side of this, nothing is wrong with the encoding. fixed in https://github.com/mikeal/dag-cbor-links/commit/df0218835ebed6802cc9241fc4b630c9dc69d3ef

note that there is still a bug and we can’t actually fix it without a massive breaking change, which probably isn’t worth making since this library is deprecated and unnecessary w/ the new block interface in `multiformats`.

someone will need to update all the `js-ipfs` packages to the latest `dag-cbor-links` now.

**Comment by achingbrain** [comment]
> someone will need to update all the js-ipfs packages to the latest dag-cbor-links now.

It would be most excellent if you could either:

a) Fix the bug in `dag-cbor-links` in a way that is backwards compatible or
b) Open the PRs that upgrade the dependency version

Best would be to add a test to the interface suite that exposes this bug then fix it and/or refactor the dep away.  Off the top of my head I think ipfs-core is the only module that depends on `dag-cbor-links`.

**Comment by mikeal** [comment]
Sorry, my comment was a bit confusing. The fix is already backwards compatible.

There’s just a minor part of the existing bug that is not fixed by this change. Basically, any binary property will break traversal in the old code. In the new code, binary properties are fixed but you can’t pass in a pre-decoded dag-cbor block that is *only* a binary value. That is broken in the old code and the new code.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

Assigning to @achingbrain to answer whether this issue is already resolved in Helia, or if this issue needs to be migrated to that repo!

**Comment by achingbrain** [comment]
I think this has been resolved, please re-open against `@helia/dag-cbor` or `@ipld/dag-cbor` if that's no the case.
