### ISSUE TITLE
ipfs.files.stat should not support some encodings or return API compatible object

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3325]
At the moment docs claim that `ipfs.files.stat` return the object that has the following keys:

> - `cid` a [CID][cid] instance
> - `size` is an integer with the file size in Bytes
> - `cumulativeSize` is an integer with the size of the DAGNodes making up the file in Bytes
> - `type` is a string that can be either `directory` or `file`
> - `blocks` if `type` is `directory`, this is the number of files in the directory. If it is `file` it is the number of blocks that make up the file
> - `withLocality` is a boolean to indicate if locality information is present
> - `local` is a boolean to indicate if the queried dag is fully present locally
> - `sizeLocal` is an integer indicating the cumulative size of the data present locally

Which is not the case for dag-cbor nodes

https://github.com/ipfs/js-ipfs/blob/3218067c33626782218e336826f459f4ebc80186/packages/ipfs-core/src/components/files/stat.js#L104-L111

**Comment by achingbrain** [comment]
I think ipfs.files.stat should support as many encodings as possible because you can add arbitrary CIDs to your MFS tree.

It may need a mechanism to let the user configure statting DAGs with arbitrary codecs in a similar way to how we let the user configure extra IPLD formats at startup time?

**Comment by Gozala** [comment]
On one hand I really like the idea of allowing non file nodes into file system, but on the other I really don't want a filesystem API that I can't treat as filesystem.

On the relevant note in the https://github.com/Gozala/lunet/ experiment I was projecting encrypted dag nodes as a filesystem and was working towards OP based CRDT documents to do the same. Idea been that consumer of dag can choose what interaction API to use, filesystem, data base, REST, etc... 

I think it would be reasonable to have some baseline API that is not filesystem, and some to filesystem projections (that can be registered somewhat like IPLD codecs). And file API should only work with things that have this projection available and fail otherwise.

Another sensible solution could be to have stat return certain details that it can do for all kind of nodes and have an optional field containing cluster of filesystem related details. That it is far less error prone as on could do `if (stats.file) { ... }` instead of having to most fields.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia by wrapping your Helia instance with the encodings you want to support. Please try it out!
