### ISSUE TITLE
HTTP client factory: Invalid URL

### ISSUE THREAD

**Issue by acostalima** [ipfs/js-ipfs#3331]
- **Version**:

js-ipfs version: 0.49.1-84cfa553ffc717d5d8bf94fdf6a306f182c9aee4
interface-ipfs-core version: ^0.139.1
ipfs-http-client version: ^46.0.1
Repo version: 8
System version: x64/darwin
Node.js version: v14.7.0
Commit: 84cfa553ffc717d5d8bf94fdf6a306f182c9aee4

- **Platform**:

MacOS Catalina 10.15.6

Darwin acostalima 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

React Native v0.63.2 (tracking RN support at https://github.com/ipfs/js-ipfs/issues/2813)

- **Subsystem**:

HTTP client 

#### Severity:

High (?)

#### Description:

Call the HTTP client factory with a valid URL to create a new client. The factory throws with `TypeError` (Invalid URL).

#### Steps to reproduce the error:

```js
import createHttpClient from 'ipfs-http-client';

createHttpClient({ url: 'http://localhost:5002' }); // throws TypeError 'Invalid URL'
```

I've tracked down the issue to: https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-http-client/src/lib/core.js#L28
where `options.url` is `undefined`.

In the client's constructor, input is being normalized twice:
https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-http-client/src/lib/core.js#L116
https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-http-client/src/lib/core.js#L120

where `opts.url` is already a `URL` object from the first pass. `URL`s are not being handled by the [normalization logic](https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-http-client/src/lib/core.js#L21), so `options.url` ends up being `undefined`.

On one hand, this issue does not appear to be related to React Native. On the other, it's kind of odd because the HTTP client factory cannot be used like. 🤔 
Am I missing something?

I'll happily open a PR to address this.

**Comment by achingbrain** [comment]
Interesting, I think this is a quirk of React Native.  In node and the browser this doesn't fail:

```js
const u1 = new URL('http://example.org')
const u2 = new URL(u1)
```

But it looks like it does in RN.  MDN [says](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) the argument to the URL constructor should be a string so I guess RN is technically correct here but other environments are more lax.

Anyway #3351 should fix this, thanks for bringing this up.

**Comment by acostalima** [comment]
> Interesting, I think this is a quirk of React Native. In node and the browser this doesn't fail:
> 
> ```js
> const u1 = new URL('http://example.org')
> const u2 = new URL(u1)
> ```
> 
> But it looks like it does in RN. MDN [says](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) the argument to the URL constructor should be a string so I guess RN is technically correct here but other environments are more lax.
> 
> Anyway #3351 should fix this, thanks for bringing this up.

@achingbrain I missed that, sorry! Thanks for pointing it out. 💪
