### ISSUE TITLE
HTTP client factory: Invalid base URL

### ISSUE THREAD

**Issue by acostalima** [ipfs/js-ipfs#3332]
- **Version**:

js-ipfs version: 0.49.1-84cfa553ffc717d5d8bf94fdf6a306f182c9aee4
interface-ipfs-core version: ^0.139.1
ipfs-http-client version: ^46.0.1
Repo version: 8
System version: x64/darwin
Node.js version: v14.7.0
Commit: 84cfa553ffc717d5d8bf94fdf6a306f182c9aee4

- **Platform**:

MacOS Catalina 10.15.6

Darwin acostalima 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

React Native v0.63.2 (tracking RN support at https://github.com/ipfs/js-ipfs/issues/2813)

- **Subsystem**:

HTTP client

#### Severity:

High (?)

#### Description:

Call the HTTP client factory with a valid URL to create a new client. The factory throws with `TypeError` (Invalid base URL). 

#### Steps to reproduce the error:

Issue #3331 has to be fixed first in order to reproduce this one.

```js
import createHttpClient from 'ipfs-http-client';

createHttpClient({ url: 'http://localhost:5002' }); // throws TypeError 'Invalid base URL'
```

I've traced the issue down to: https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-http-client/src/lib/core.js#L28
and the root cause lies in https://github.com/hugomrdias/iso-url/blob/master/src/url-browser.js#L3 (CC @hugomrdias).
The default value for `base` cannot be resolved to `''`. In fact, as per [spec](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), if left unspecified it should be `undefined`. The statement `new URL('http://localhost:5002', '')` throws in Chrome and Firefox.

I'll gladly open a PR to fix this.

**Comment by hugomrdias** [comment]
Did this change? i thought we discussed this and thr impl was according to spec. Please PR and ping i will review/merge asap.

**Comment by acostalima** [comment]
@hugomrdias I thought as much too! I had a few items noted down to review and I came across this one again. I did read the docs in MDN again and it's stated this much. I don't remember exactly what led us to conclude everything was alright.
