### ISSUE TITLE
Remove redundant has check

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3379]
This has check can be removed as the block service will now throw:

https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/block/rm.js#L67-L68

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
