### ISSUE TITLE
API simplification: remove `ipfs.bitswap.unwant` from the Core API

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3382]
This method is not supported by go-IPFS so is not a hard requirement and I'm not sure we should pull the rug out from under other parts of the codebase by exposing such a low-level API.

Since adding timeouts and AbortSignals, you can remove and CIDs you've added to the wantlist by aborting the context in which they were added, or letting the call time out so it seems redundant.

Suggestion: remove `ipfs.bitswap.unwant` from the Core API

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
