### ISSUE TITLE
Change process name

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3383]
When the daemon is started it runs as a process called `node`, e.g. the default.  We should rename it after startup to jsipfs or something..

Ref: https://stackoverflow.com/questions/64787550/how-can-i-tell-if-my-ipfs-daemon-is-running-the-background

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

@achingbrain i'm closing this but you should open an issue in https://github.com/ipfs/helia-cli if you think we need it.
