### ISSUE TITLE
ipfs.bitswap.stat() should return who's peers are strings instead of CIDs

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3389]
As per discussion here https://github.com/ipfs/js-ipfs/pull/3365/files/fa7c2c13c43bab922052104fe8aff863d9725e9b#r521321206 `peers` should be strings not CIDs

**Comment by lidel** [comment]
@Gozala  Is this still relevant given ongoing work in https://github.com/ipfs/js-ipfs/issues/2945 ?
