### ISSUE TITLE
Three Issues with "exchange-files" example

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#3397]
- **Version**:

Using latest master with the respective example

- **Platform**:

```
» uname -a
Darwin imp16.Home 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```

- **Subsystem**:

Examples

#### Severity:

Medium

#### Description:

Found 3 issues with the exchange examples

## 1) The ipfs node returns every address, even if it failed to set up the listener (actual bug in IPFS)

![image](https://user-images.githubusercontent.com/1211152/99155950-ae968180-26b4-11eb-900f-58c39665771d.png)

## ✅ FIXED | 2) Typo in how addresses are formatted 

![image](https://user-images.githubusercontent.com/1211152/99155955-bd7d3400-26b4-11eb-8f46-b6d003e32136.png)

Why does it attempt to show all addresses as /p2p/? Is there an issue if it displays /ipfs/ addresses? 

Update: Fix at https://github.com/ipfs/js-ipfs/pull/3398

## CLOSED | 3) Workspace functionality doesn't seem to work~~

Might have been a problem on my side. It didn't work for a few times, but now I can't repeat the failure.  

#### Steps to reproduce the error:

Start the example with latest. The errors should be visible too

**Comment by daviddias** [comment]
**🐞 Found an actual 3rd issue. The PubSub messages don't seem to get transferred between peers.**

![image](https://user-images.githubusercontent.com/1211152/99193149-0691be80-276f-11eb-9736-7b31e123ca2e.png)

Tried multiple combinations (chrome <-> firefox, chrome <-> chrome, firefox <-> firefox) and got not results.

I added some debug statements, the messageHandler never sees the message coming from the other peer.

Can someone run the example on their machine and see if it does work?

**Comment by achingbrain** [comment]
Hmm, weird - the tests pass and it works for me locally between FF and Chrome.  The missing `/p2p/` thing is a bug, though it's only a display thing, it shouldn't affect the running of the example.

**Comment by daviddias** [comment]
@achingbrain to distinguish, are you saying that both issue 1) and 4) do not present themselves to you?

**Comment by daviddias** [comment]
@achingbrain today my experience has degraded, I don't even see peers showing anymore

![image](https://user-images.githubusercontent.com/1211152/99258215-21683f80-2810-11eb-8c8e-8e5334a7ee42.png)

Additionally, I'm seeing the browser node connecting to a bunch of TCP peers, which as we know, it is not possible
![image](https://user-images.githubusercontent.com/1211152/99258327-4d83c080-2810-11eb-858e-6bdf1ed792ab.png)

**Comment by achingbrain** [comment]
I am not seeing 4).  Does the test in the example pass for you?  You can comment out [this line](https://github.com/ipfs/js-ipfs/blob/master/examples/test-ipfs-example/nightwatch.conf.js#L27) to see the browsers do the steps in front of you.

.1) is a bit weird, and the tcp peers thing is definitely not right, I think #3400 is reporting a similar issue, how peer addresses are treated by the address book seems to have changed recently

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out! Note that we're migrating js-ipfs-examples to Helia as well. see https://github.com/ipfs/helia/issues/43 for more info.
