### ISSUE TITLE
Browser-Create-React-App example fails

### ISSUE THREAD

**Issue by raphael10-collab** [ipfs/js-ipfs#3415]
After executing the commands yarn -> yarn start I get these errors:

![image](https://user-images.githubusercontent.com/70313067/99876384-9e236100-2bf6-11eb-822f-edd5e3318e7b.png)

Ubuntu 18.04.4 Desktop

**Comment by achingbrain** [comment]
Possibly a duplicate of https://github.com/ipfs/js-ipfs/issues/1388

Are you running in a private browser window?

**Comment by lidel** [comment]
Closing as stale, feel free to reopen if the problem is still present in the latest version.
