### ISSUE TITLE
Can't add data with js-ipfs and can't get it from other browsers.

### ISSUE THREAD

**Issue by ampcpmgp** [ipfs/js-ipfs#3429]
- **Version**:
js-ipfs 0.50.2
https://js.ipfs.io/

- **Platform**:
Windows 10 & Google Chrome 87.0.4280.66

- **Subsystem**:
Nothing

#### Severity:
High

#### Description:
Adding the default data - `Hello, <YOUR NAME HERE>` for the js-ipfs site returns 200 Status, but adding any other data results in Error.

#### Steps to reproduce the error:

* Success
![image](https://user-images.githubusercontent.com/13173632/100505413-1ddd9c80-31b0-11eb-83c7-5915adfbcc16.png)

* Error
![image](https://user-images.githubusercontent.com/13173632/100504964-ff77a100-31af-11eb-8767-6cbd3298807e.png)

**Comment by ampcpmgp** [comment]
Now it was available.
I was not able to use it 4 hours ago, how does this happen and how do I do error handling?

**Comment by achingbrain** [comment]
The preload nodes were probably down, then they probably came back up.

There's a more detailed explanation here: https://github.com/ipfs/js-ipfs/blob/master/docs/FAQ.md#what-are-all-these-refsqmfoo-http-errors-i-keep-seeing-in-the-console

> how do I do error handling?

This is not really an error, nor is there anything you can do to prevent it other than turning off preloading though it's not a great idea for browser nodes (see link above).

Please can you use https://ipfs.discuss.io for 'how do I'-type questions - the ensuing discussion will be more visible than GH issues, which are primarily used to develop the actual protocol.
