### ISSUE TITLE
Can't  resolve IPNS address on https://gateway.ipfs.io/ipns/{address} 

### ISSUE THREAD

**Issue by EmanHerawy** [ipfs/js-ipfs#3430]
Hey all,
I am trying to publish ipfs hash to IPNS. But whenever I try to access this ipns address through https://gateway.ipfs.io/ipns/{address}  it's not resolved and I don't understand why! I guess there is something I misunderstand about ipns :( 
I have followed the doc to publish ipfs hash to IPNS and below is my code
```
async function publishToIPNS(hash) {
			const ipfsAddress = `/ipfs/${hash}`
			try {
				console.log("Starting to publish...");
				const res = await node.name.publish(ipfsAddress, { resolve: true })
				console.log({res},hash,'hash and res');
				// You now have a res which contains two fields:
				//   - name: the name under which the content was published.
				//   - value: the "real" address to which Name points.
				console.log("IPNS Record:");
				console.log(`https://gateway.ipfs.io/ipns/${res.name}`)
				console.log("IPFS Record:");
				console.log(`https://gateway.ipfs.io/${res.value}`)


					return res.name;
			} catch (err) {
				err.message = `Failed to add peer: ${err.message}`
				onError(err)
			}
		}
```
it works and I could resolve the IPNS address and get the ipfs hash using name.resolve  

```
const resolve= await last( await node.name.resolve(`/ipns/${ipnsAddress}`))
				console.log(resolve,'resolve');
```
but couldn't resolve the ipns address on  https://gateway.ipfs.io/ipns/{address} 
Your help is much appreciated

**Comment by achingbrain** [comment]
At a guess I'd say your node is behind a NAT and the rest of the IPFS network (including the gateways) cannot connect to it.

I would:

1. Look at the TCP ports your node is listening on by running `jsipfs id`
2. Open the relevant ports on your router and forward them to your local machine
3. Configure the [Announce](https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md#announce) addresses on your local node as a combination of your external IP and port

Please can you use https://discuss.ipfs.io for general support questions in future - it's way better than github for this as it's got better visibility for questions and more people are looking at it.

**Comment by justinmchase** [comment]
I am having the same issue. Why would I need to open ports on my router if my node is connected to the p2p network? I am able to fetch the file at the hash my ipns address has hashed... so shouldn't ipns also work if the hash is working?
