### ISSUE TITLE
Best way to use IPNS in the browser right now?

### ISSUE THREAD

**Issue by workingtim** [ipfs/js-ipfs#3433]
Is this still the best way to use IPNS in the browser https://github.com/ipfs/js-ipfs/tree/master/examples/browser-ipns-publish ?

**Comment by achingbrain** [comment]
Yes, is there something you're having a problem with?

**Comment by workingtim** [comment]
the example works well, I was just hoping there had been improvements on being able to do `ipfs.name.resolve` without having to run a node, either 100% in the browser or using a delegate node, even if it's slow.

**Comment by achingbrain** [comment]
The problem is you need a node on the network to answer requests from peers for the DHT records associated with an IPNS name you've published - a node running in the browser is a poor candidate for this since as soon as you close the browser or otherwise navigate away from the page the node will stop running.  Even switching away from the tab is enough to have the network and CPU use throttled.

You can use a delegate node, but you'll need to host it yourself as the public delegate nodes only retain DHT records for an hour or so.

**Comment by workingtim** [comment]
> a node running in the browser is a poor candidate for this since as soon as you close the browser or otherwise navigate away from the page the node will stop running.

It seems to work for `ipfs.get`, and from this page IPNS DHT doesn't seem that much different https://docs.ipfs.io/concepts/dht/#routing-particulars

If you have a website with 5-10 concurrent users at all times and they all connect to the same star servers, it seems like it would work well if the IPNS records are cached permanently (maybe LRU) for everyone who visits the website. If a user were to visit the site a few times a day they would probably be able to complete quite a few lookups successfully, and eventually over time they would get almost all of them.

For long term, big files that require high availability it would not work, but there's a lot of applications for short term small files that dont care about high availability. Like a chatroom or message board.

Will you guys be implementing `ipfs.name.publish` and `ipfs.name.resolve` in the browser or do you always expect it to be unreliable and not worth the time?

**Comment by justinmchase** [comment]
I came here to ask the same question as @workingtim.

I was just following the default examples and was surprised to find it doesn't work when other people try to access my published ipns name through the public gateway but they are able to get the files via hash directly. I sort of wanted to be able to make it only available while my app is running on purpose, I don't understand why its not just using the p2p network exactly the same as it does for files.

**Comment by FCO** [comment]
Please, reopen this. I’d also like to know the answers for those questions.

**Comment by kotx** [comment]
This is a blocker for us as well.

**Comment by appleseed-iii** [comment]
same question and experience as @justinmchase
