### ISSUE TITLE
ipfs-http-client method arguments and return types are any

### ISSUE THREAD

**Issue by dapplion** [ipfs/js-ipfs#3451]
**Curent**

All `ipfs` methods arguments and return types are any. See below example for `add`

![ezgif com-gif-maker](https://user-images.githubusercontent.com/35266934/102338852-ad4ac400-3f94-11eb-8240-604f61ddf54a.png)

**Expect**

Arguments and return values to be types properly

----

```
"ipfs-http-client": "^48.1.2",
"typescript": "^3.8.0",
Visual Studio Code: October 2020 (version 1.51)
```

**Comment by achingbrain** [comment]
Please can you try with the latest RC?  The core-api is now fully entyped in the `ipfs-core-types` module and `ipfs-http-client` now implements that API:

```console
$ npm install ipfs-http-client@next
```

![image](https://user-images.githubusercontent.com/665810/113279885-8746f680-92db-11eb-8aa6-a9f2bfc6238b.png)

**Comment by dapplion** [comment]
![Screenshot from 2021-04-01 16-20-52](https://user-images.githubusercontent.com/35266934/113308330-592adc00-9306-11eb-892f-670f52022e28.jpg)

Still any. With this version installed
```json
  "name": "ipfs-http-client",
  "version": "49.0.5-rc.3+1823375a"
```

Hey you could try this new project called Typescript, it has a solid type system with good tooling and community.

**Comment by achingbrain** [comment]
> Now has some types but first argument is still `any`.

Hmm, weird that it's picked up some of the types but not everything.

> Hey you could try this new project called Typescript, it has a solid type system with good tooling and community.

I appreciate that you feel frustration over this issue but this sort of comment is not massively helpful.

**Comment by dapplion** [comment]
> I appreciate that you feel frustration over this issue but this sort of comment is not massively helpful.

I'm sorry to be perceived as negative but I do feel the frustration over the quality of the types in all of protocol lab's JS libs, from IPFS, to libp2p, to utils. I know I'm beating a dead horse now, but I do want to see the JS side succeed. I really wish you could see the return on investment on such a move.

**Comment by lidel** [comment]
Should be fixed soon as part of  https://github.com/ipfs/js-ipfs/issues/2945
Closing to decrease noise.
