### ISSUE TITLE
HTTP client receives own pubsub messages

### ISSUE THREAD

**Issue by stbrody** [ipfs/js-ipfs#3475]
- **Version**:
`"ipfs-http-client": "48.1.1",`

- **Platform**:
`Linux Sonny 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- **Subsystem**:
pubsub

#### Severity:
medium

#### Description:
Subscribing to pubsub via the js-ipfs HTTP client and then publishing a message causes you to receive your own message.  The ipfs core implementation seems to have an `emitSelf` option that controls this behavior, but that doesn't seem to be exposed to the HTTP client.  This behavior makes it very difficult to correctly have multiple ipfs http clients share the same ipfs daemon.  You can't just filter out messages with the same peerId, because the different http clients all are using the same backing ipfs node, and therefore the messages from different clients all have the same peerId.

#### Steps to reproduce the error:
Run a js-ipfs node on port 5011
Run `node repro.js`

repro.js:
```
const ipfsClient = require("ipfs-http-client")

const topic = '/ceramic/testnet-clay'
const ipfsApiUrl = 'http://localhost:5011'

const run = async() => {
    const ipfs = ipfsClient({ url: ipfsApiUrl, emitSelf:false, pubsub: {emitSelf: false}, config: {pubsub: {emitSelf: false}}} )

    const receiveMsg = (msg) => { console.log('GOT MESSAGE') }

    await ipfs.pubsub.subscribe(topic, receiveMsg)

    await ipfs.pubsub.publish(topic, "{'this message': 'is from myself!'}")
}

run()
```

Get output:
`GOT MESSAGE`

Expected:
no output, we shouldn't get notified about our own pubsub messages.

**Comment by stbrody** [comment]
Worth noting here that the ipfs core daemon that the http client is connecting to has `emitSelf:true`.  If that is changed to false, then multiple http clients connected to the same backing ipfs node don't receive *each others* pubsub messages, which is even worse than receiving your own messages extraneously.

**Comment by achingbrain** [comment]
This is an interesting setup.  It sounds like you're using a central IPFS node as a server, and having a bunch of clients talk to that server but they think of themselves as independent nodes.

The intention of the `ipfs-http-client` is to be able to use the HTTP API of a remote IPFS node as if it were a local node, but not really for it to be a many-to-one client/server setup.  There are of course situations where this will work without issue, and it's used within js-IPFS for things like communicating with delegate or preload nodes, but you may end up with weird behaviour around anything more complicated than that as it sounds like you've found.

In a more P2P setup you'd have each client run their own IPFS node and exchange messages that way.  Is there any reason you can't have each client run a node, get them to dial each other and exchange messages that way?

**Comment by stbrody** [comment]
Yeah that's right, and we're working around this by running dedicated ipfs servers for each client we need, but it increases the size and complexity of our infrastructure a bunch more than we need.  Our services are still low-volume enough that we don't need a dedicated ipfs node for each service that depends on ipfs.  Especially in our testing infrastructure, this creates a lot of unnecessary complexity and extra running services that shouldn't be necessary.

**Comment by stbrody** [comment]
Another reason we want to do this is performance related.  We're finding loading records from the IPFS dag to take a long time - if more of our services could share the same IPFS daemon effectively, then more of the records we need to fetch would already be present in the IPFS node's cache.

**Comment by achingbrain** [comment]
The problem here is that `ipfs-http-client` is not supposed to be treated as an 'ipfs-lite' - it's for controlling a remote IPFS daemon in a 1-to-1 relationship and not intended for use in a n-to-1 client/server setup.

Basically this is working as expected.
