### ISSUE TITLE
Client config host breaks url

### ISSUE THREAD

**Issue by valmack** [ipfs/js-ipfs#3476]
- **Version**:

"ipfs-http-client": "^48.1.2"

- **Platform**:

Mac OSX

- **Subsystem**:

ipfs-http-client

#### Severity:

Medium

#### Description:

When I pass host as a config option with the protocol scheme, the Client configuration breaks the url. For example
`https://foo.bar.com` becomes `http://https`.
The source of this issue is this line
https://github.com/ipfs/js-ipfs/blob/fe93ba01a0c62cead7cc4e0023de2d2a00adbc02/packages/ipfs-http-client/src/lib/core.js#L39
The way this code is written assumes that (1) the developer is passing `protocol`, `host`, _and_ `port`, and that (2) `host` does not include the protocol scheme. So these strings work as expected: `foo.com` or `foo.com:5011`
But this does not work: `https://foo.com`

I think this code is confusing because _if_ all 3 options _are_ required there shouldn't be a need to `.split(':')` on a colon at all.

Potential solutions would be:
1. More explicit explanation of what should be passed in documentation
2. Throw an error if only 1 of the 3 options are set
3. Eliminate these options and just use `url` instead

#### Steps to reproduce the error:

```js
  ipfsClient({
      host: 'https://foo.com',
      port: 5011
    });
```

```
FetchError: request to http://https:5011/api/v0/dag/put failed, reason: connect ETIMEDOUT
```

**Comment by lidel** [comment]
@valmack any reason why below do not work for you?

```js
ipfsClient('https://foo.com:5011')
```

```js
  ipfsClient({
      protocol: 'https', 
      host: 'foo.com',
      port: 5011
    });
```

ps. I agree that splitting in mentioned line does not make much sense, unless we leverage `[1]` in `port`.
It is a cosmetic thing, but feel free to open a PR with a fix if you have time and will to clean this up.

**Comment by valmack** [comment]
@lidel yeah I am now passing `ipfsClient({url: https://foo.com:5011})` instead.

Happy to submit a pr but I guess just making it clear in the docs is easier. Doesn't strictly need a code change.

**Comment by achingbrain** [comment]
I've merged https://github.com/ipfs/js-ipfs/pull/3478 which should hopefully make the constructor args clearer, thanks for pointing out the lack of docs.

But yes, TLDR is that you can't include a `protocol` in the `host` field, specify it in the `protocol` field instead, or pass the whole URL in as a string, [multiaddr](https://www.npmjs.com/package/multiaddr) or [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL), or use the `url` field of the options object.
