### ISSUE TITLE
ipfs-core-types causes problems when isolateModules flag is set

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3494]
See following issue for the context https://github.com/ipfs-shipyard/ipfs-webui/pull/1655#issuecomment-763846124

**Comment by achingbrain** [comment]
In the linked thread you say you've [worked around the issue](https://github.com/ipfs-shipyard/ipfs-webui/pull/1655#issuecomment-764028386) - is this still valid?

**Comment by achingbrain** [comment]
Ah, I guess #3495 is the work around?
