### ISSUE TITLE
Control over seeding?

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs#350]
Heya,

I'd like to store ipfs content in a long term store (like S3) and selectively pull content up and seed it. Then I need to be able to stop seeding programmatically. I'm wondering if there is an API to do this or where I should be looking in order to construct an API to do so.

**Comment by jbenet** [comment]
We're looking at doing this with pluggable repo backends (we'll likely
support levels so that you can store stuff wherever).

In the meantime, it should be a matter of writing a repo that first checks
a local cache (memory, disk, whatever) then pulls out of s3. The writes may
be expensive atm, without some batch put.

@diasdavid thoughts?

Cc @whyrusleeping for S3 thoughts.

**Comment by dignifiedquire** [comment]
**Storage backends**

js-ipfs already supports pluggable repo backends through the `abstract-blob-store-interface`. It's just not exposed as an api to change the store at the moment. The relevant code that decides which storage to use is here: https://github.com/ipfs/js-ipfs/tree/master/src/core/default-repo

References:

- https://github.com/ipfs/js-ipfs-repo
- https://github.com/maxogden/abstract-blob-store
- Node.js default store: https://github.com/mafintosh/fs-blob-store
- Browser default store: https://github.com/dignifiedquire/idb-plus-blob-store

**Seeding programatically**

This is currently not implemented in any form, if something is available in the rep other nodes will be able to request that content from you if they are connected to you.

**Comment by achingbrain** [comment]
If you wanted to do this, one way to do it would be:

1. Implement a [datastore](https://github.com/ipfs/interface-datastore) with your logic that returns `true` from [.has(key)](https://github.com/ipfs/interface-datastore#haskey---promiseboolean) when you want to seed something and `false` when you don't
2. Configure an instance of `ipfs-repo` with that datastore as the blockstore - see the [custom-ipfs-repo](https://github.com/ipfs/js-ipfs/tree/master/examples/custom-ipfs-repo) example for how to do this
3. Configure your IPFS node with that repo - instructions here: https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs#optionsrepo

When bitswap receives a request for a block, it'll ask the blockstore which will say 'yes I have it' and it'll be sent or 'no I don't have it' in which case it won't.
