### ISSUE TITLE
ipfs.add TypeError: AbortController constructor: 'new' is required

### ISSUE THREAD

**Issue by ericspt** [ipfs/js-ipfs#3509]
- **Version**:
"ipfs-http-client": "^48.2.2"

- **Platform**:
Mozilla Firefox latest version, using Ganache and MetaMask. For code, reactJs, web3js

- **Subsystem**:
I don't know

#### Severity:
Medium - no files can be uploaded

#### Description:
- What you did: I tried using ipfs.add to add user-uploaded images to the blockchain 
- What happened: I get TypeError: AbortController constructor: 'new' is required
- What you expected to happen: A postResponse variable
-->

#### Steps to reproduce the error:
```
<form onSubmit={ async (event) => {
    event.preventDefault()
    try{
        console.log(buffer)
        const postResponse = await ipfs.add(buffer) 
        console.log("postResponse", postResponse);
    } catch(e){
        console.log("Error: ", e)
    }
}} >
```

It gets to console.log(buffer) and actually prints out an image (uploaded a png through an input field). 
Example console output: `Uint8Array(951674) [ 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, … ]`

The file does not get added and this error is thrown. I don't use AbortController anywhere in my code. 
I genuinely think it has something to do with the js-ipfs implementation because it has been altered a lot of times and in the error message I don't have line numbers from my code, I have no idea what those are. 

At the same time, I am a newbie in IPFS and I apologise if this is not opened correctly.

**Comment by hueimin426** [comment]
Hi there, I am facing the same issue.
I could run without error initially, somehow it doesn't work for now.

**Comment by ericspt** [comment]
Downgrading to ipfs 33.1.1 (which was known as stable) and changing to the old-style adding doesn't work either. 
Any suggestions would be greatly appreciated.

**Comment by achingbrain** [comment]
Is there a repo somewhere with a small project I can run to reproduce this error?

**Comment by hueimin426** [comment]
Perhaps you can try https://github.com/dappuniversity/meme_of_the_day with async and await added to src/component/App.js.

> Is there a repo somewhere with a small project I can run to reproduce this error?

**Comment by achingbrain** [comment]
I think whatever transpilation react-scripts is doing, it doesn't like that `native-abort-controller` extends the built-in AbortController class in order to maintain compatibility with the `abort-controller` module.

This will be fixed by https://github.com/achingbrain/native-abort-controller/pull/1
