### ISSUE TITLE
Retagging and repushing old tags, breaking apps which are using CDN

### ISSUE THREAD

**Issue by zerdos** [ipfs/js-ipfs#3518]
...or apps which are using npm.
for example, bundle is missing from here, 
https://unpkg.com/browse/ipfs@0.54.0/dist/
but it was available a couple of hours ago.

Also noticed this a couple of weeks ago, with the message-port-client package, that time I had a build faulure - the same tag was reused with the latest failed build.

**Comment by xmaysonnave** [comment]
ipfs-http-client is also unavailable from jsdelivr...
https://cdn.jsdelivr.net/npm/ipfs-http-client@49.0.0/dist/index.min.js
Thanks

**Comment by achingbrain** [comment]
Minified bundles were being built in a pre-build step, but then the 'prepare' scripts were being run that deleted the dist folder before publishing.  Oops.

Updated versions have been published, please try again with `ipfs@0.54.1` and `ipfs-http-client@49.0.1`.

> the same tag was reused with the latest failed build.

I'm not sure this is possible, npm [doesn't let you reuse versions](https://www.npmjs.com/policies/unpublish#considerations-) and jsdelivr/unpkg etc pull from npm.

> bundle is missing from here, unpkg.com/browse/ipfs@0.54.0/dist but it was available a couple of hours ago.

`ipfs@0.54.0` has only just been published - the bundle was available for the [previous version](https://unpkg.com/browse/ipfs@0.53.2/dist/), maybe that's what you pulled down last time?
