### ISSUE TITLE
"Uncaught ReferenceError: fs is not defined"

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#353]
Using latest `0.14.1` when initializing IPFS in the browser, I get an error:
"Uncaught ReferenceError: fs is not defined" and
"Uncaught ReferenceError: window.Ipfs is not defined"

Didn't change anything, my webpack configurations used to work at least with `0.13.0`

**Comment by dignifiedquire** [comment]
Can you please add a stacktrace?

**Comment by diasdavid** [comment]
From what I can understand, this is now fixed. @haadcode reopen if necessary
