### ISSUE TITLE
"Uncaught ReferenceError: window.Ipfs is not defined"

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#354]
Using latest version `0.14.1`, I get an error:
"Uncaught ReferenceError: window.Ipfs is not defined"

This used to work at least in `0.13.0`.

If the global instance of IPFS has changed its name/location, it should be documented in the README.

**Comment by dignifiedquire** [comment]
Can you paste/link to the exact code that is loading ipfs?

**Comment by haadcode** [comment]
Just realized this is probably related to https://github.com/ipfs/js-ipfs/issues/353 and because IPFS can't be created, it'll give undefined. 

Leave the issue open for now, let's close it once a fix is confirmed.
