### ISSUE TITLE
ipfs add zero filled uint8 fails against go

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#3542]
This test https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/add.js#L84 fails running the interface tests against go-ipfs in firefox ONLY.

This is the data used in the test https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/utils/index.js#L26, changing the input to something like https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/test/fixtures/test-folder/holmes.txt makes the test pass.

### dag from go-ipfs
chrome
<img width="926" alt="Screenshot 2021-02-09 at 12 19 42" src="https://user-images.githubusercontent.com/314190/107397768-da2fd900-6af6-11eb-9586-1a63143e5bd3.png">

firefox
<img width="435" alt="Screenshot 2021-02-09 at 12 23 25" src="https://user-images.githubusercontent.com/314190/107397794-e1ef7d80-6af6-11eb-9884-ae79f91d6c49.png">

In this PR https://github.com/ipfs/js-ipfs/pull/3528 i changed the input data to make the test pass because it looks like this only happens with 0 filled buffers, but this needs a real fix.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

@achingbrain to ensure that we have tests in helia that confirm this is not a problem

**Comment by achingbrain** [comment]
This is fixed in Helia, please open an issue there if the problem persists.
