### ISSUE TITLE
HTTPError: file argument 'key' is required when using go-ipfs node with ipfs-http-client

### ISSUE THREAD

**Issue by SahidMiller** [ipfs/js-ipfs#3547]
#### Version information:
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4

#### Description:
There's an incompatibility with ipfs-http-client key import using pem and password resulting in an `HTTPError: file argument 'key' is required`

Steps to reproduce the error:

```   
    const ipfsClient = require('ipfs-http-client')
    const ipfs = ipfsClient(await ipfsClient({
	url: __REMOTE_API_ADDRESS__, //Connect with go-ipfs node
	agent: ...
    })
    const key = await crypto.keys.generateKeyPair('rsa', 2048)
    const pem = await key.export("temppassword")
    const { id } = await ipfs.key.import(keyName, pem, "temppassword")
```

**Comment by Stebalien** [comment]
This appears to be an incompatibility between the js-ipfs HTTP API and the go-ipfs HTTP API.

**Comment by achingbrain** [comment]
In a bit more detail, js-IPFS accepts the key as a query string argument, go-IPFS accepts it in the body of the POST request.

The http client [sends it in the query string](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/key/import.js#L19) as I think it may have been done in js-IPFS first as the interface tests for the import operation are [skipped for go-IPFS](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/test/interface-http-go.js#L476), the note says 'TODO not implemented in go-ipfs yet'.

It looks like it's been implemented, and implemented differently - js-IPFS should probably align with go-IPFS here.

**Comment by BigLep** [comment]
When this gets picked up, we should be using POST per verbal conversation on 2021-03-22 with @Stebalien  and @achingbrain .

**Comment by Rinse12** [comment]
Are there any updates regarding this issue? It has been over a year

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

We won't be addressing this issue in ipfs-http-client, but you should look at kubo-rpc-client for handling this.
