### ISSUE TITLE
Warning about dependencies problems

### ISSUE THREAD

**Issue by raphael10-collab** [ipfs/js-ipfs#3548]
During installation of js-ipfs few warnings appear, which might not be a problem at the moment, but may be later can cause some troubles: 

    warning ipfs > ipfs-core > libp2p > @motrix/nat-api > request@2.88.2: request has been deprecated, see https://github.com
    /request/request/issues/3142
    warning ipfs > ipfs-core > libp2p > promisify-es6@1.0.3: Unmaintained
    warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a 
    low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. 
    (https://github.com/visionmedia/debug/issues/797)
    warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > socket.io-parser > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || 
    >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 
    3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
    warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > engine.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 
    <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 
    4.3.1. (https://github.com/visionmedia/debug/issues/797)
    warning ipfs > ipfs-cli > ipfs-daemon > prometheus-gc-stats > gc-stats > node-pre-gyp@0.13.0: Please upgrade to  
    @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will 
    recieve updates in the future
    warning "ipfs > ipfs-cli > ipfs-daemon@0.5.2" has unmet peer dependency "electron-webrtc@^0.3.0".
    warning "ipfs > ipfs-cli > ipfs-daemon@0.5.2" has unmet peer dependency "wrtc@^0.4.6".

- O.S. : Ubuntu 18.04 Desktop
- node: v14.5.0

**Comment by achingbrain** [comment]
None of these modules are direct dependencies of any modules in this repo so there's nothing to be done here.

If you'd like these warnings to go away, please open issues against the modules with dependencies that need upgrading, or better yet - open PRs that do the upgrading.

**Comment by raphael10-collab** [comment]
I'm going to open issues againsta that modules, and if needed, open PRs.

Do I need to do the same for the following?

    warning "ipfs > ipfs-cli > ipfs-daemon@0.5.2" has unmet peer dependency "electron-webrtc@^0.3.0".
    warning "ipfs > ipfs-cli > ipfs-daemon@0.5.2" has unmet peer dependency "wrtc@^0.4.6".

**Comment by achingbrain** [comment]
No, that is by design. See the
FAQ on enabling WebRTC in a daemon process: https://github.com/ipfs/js-ipfs/blob/ba4992ca69d2b3c148ea24833955b5b50003d76f/docs/FAQ.md#is-there-webrtc-support-for-js-ipfs-with-nodejs
