### ISSUE TITLE
err_connection_reset when adding file

### ISSUE THREAD

**Issue by christopheSeeka** [ipfs/js-ipfs#3555]
Hello,

I'm running a web app where users add files to IPFS through infura and while it work for majority of users, i get a good 10% that cannot add anything getting some HTTPError / err_connection_reset

What could this be when it work for most other users? 
This particular user tried on 3 differents devices, no vpn/firewall/antivirus

Here what we get: [](https://imgur.com/OtGHf0Z)
I'm using  "ipfs-http-client": "^48.1.3"

```
let host = "ipfs.infura.io";
const ipfsClient = require("ipfs-http-client");
let ipfs;



async function upload(file, callback) {
  ipfs = ipfsClient({
    host: host,
    port: "5001",
    protocol: "https",
  });

  const files = [{ path: "/"+file.name, content: file }];

  let progress_func = function(len) {
    callback({loaded:len, total: file.size})
  }; 

  try {
    let result = await ipfs.add(files, { progress: progress_func, pin: true, wrapWithDirectory: true })
      let cidv1 = new ipfsClient.CID(result.cid).toV1().toString();
      return { cid: { string: cidv1 } };
    
  } catch (err) {
    console.log("catched err");
    console.log(err);
    return { path: null, error: err };
  }
}
```

Thank you in advance

**Comment by achingbrain** [comment]
The code looks ok, though you should use [ipfs.addAll](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsaddallsource-options) for arrays of files - `ipfs.add` works now but will not in future releases.

I can't replicate the issue - do you have a sample project that shows the problem?

**Comment by christopheSeeka** [comment]
Thank you for the feedback, if i change ipfs.add to ipfs.addAll i get:

```
Error: Invalid version, must be a number equal to 1 or 0
    at Function.validateCID (index.js:346)
    at new CID (index.js:174)
    at _callee$ (ipfs.js:55)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:5)
    at _next (asyncToGenerator.js:27)
```

As for recreate the error, i cannot recreate it mylself, it's a user of our webapp that is having it. Actually around 5% of our users report similare issue when adding: err_connection_reset or sometimes err_empty_response while everyone else is ok.

I guess it's not related to the code then, just wanted check in case.

**Comment by christopheSeeka** [comment]
Ok got it, there is cidVersion in the options. 
Anyway since i only add 1 by 1 in this app, i made it an object only instead of an array and keep add. 

Thanks

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out! If you run some A/B deployment of helia update vs js-ipfs, i think you will be pleasantly surprised with the results =) Let us know if you're not!
