### ISSUE TITLE
On Node 15.x, npm install failure in examples/browser-video-streaming

### ISSUE THREAD

**Issue by Zorlin** [ipfs/js-ipfs#3562]
On the latest Git version, in js-ipfs/examples/browser-video-streaming/, npm install fails:

```
npm ERR! code 1
npm ERR! path /home/wings/projects/js-ipfs/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: 1: node-pre-gyp: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wings/.npm/_logs/2021-02-18T22_40_42_411Z-debug.log

lerna ERR! npm install exited 1 in 'js-ipfs'
npm ERR! code 1
npm ERR! path /home/wings/projects/js-ipfs
npm ERR! command failed
npm ERR! command sh -c lerna bootstrap

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wings/.npm/_logs/2021-02-18T22_40_42_980Z-debug.log
```

**Comment by Zorlin** [comment]
Also, this was on the latest Node.JS 15.x on Ubuntu 20.04 under wslv2. I'm trying 10.x now.

**Comment by Zorlin** [comment]
Indeed works on 10.x - v10.23.3

**Comment by Zorlin** [comment]
Works perfectly on 14.x, which I should be using anyway.

**Comment by achingbrain** [comment]
You may have hit https://github.com/node-webrtc/node-webrtc/issues/658

Try updating node 15 to 15.6.0 or above, failing that, install `@mapbox/node-pre-gyp` globally and try again.

**Comment by vmx** [comment]
It's still an issue with the newest versions of node 15 and npm. Installing `@mapbox/node-pre-gyp` is working though.

```console
$ node --version
v15.11.0
$ npm --version
7.6.0
```

**Comment by vmx** [comment]
In case you don't want to install things globally you can do a `npm install --include=dev @mapbox/node-pre-gyp` before running `npm install`.

**Comment by gabigarcez** [comment]
Also getting this issue and none of the solutions above worked for me.
