### ISSUE TITLE
Node created with IPFS.create() doesn't accept HTTP API requests

### ISSUE THREAD

**Issue by uluhonolulu** [ipfs/js-ipfs#3563]
- **Version**: 0.5.2

- **Platform**: Windows 64bit

#### Description:
I'm creating a node in my NodeJS application using `IPFS.create()`. The node works fine, but I cannot connect to its HTTP API endpoint -- port 5001 is not open (nor is 5002).

#### Steps to reproduce the error:
1. Execute `await IPFS.create()` at startup.
2. Run `curl -L -X POST 'http://127.0.0.1:5001/api/v0/id'` from the command line.

The file ~/.ipfs/api has a single line that says `/ip4/127.0.0.1/tcp/5001/http`

**Comment by achingbrain** [comment]
The HTTP API is separate from the core of IPFS - you need to configure it separately.

See how the `ipfs-daemon` module does it here: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-daemon/src/index.js#L53-L54

**Comment by achingbrain** [comment]
Also `~/.ipfs/api` is used by go-IPFS.  js-IPFS uses `~/.jsipfs`.

**Comment by uluhonolulu** [comment]
Thanks @achingbrain!
