### ISSUE TITLE
How does it work on browsers, with no open ports, using WebRTC?

### ISSUE THREAD

**Issue by guerrerocarlos** [ipfs/js-ipfs#357]
I checked the code but cannot find where does it make use of WebRTC for running standalone in the browser, or what am I missing?

**Comment by dignifiedquire** [comment]
It uses webrtc in the browser yes, the relevant code for this is in this module: https://github.com/libp2p/js-libp2p-webrtc-star

**Comment by diasdavid** [comment]
Here is an example, made by @VictorBjelkholm on how you can set it up, hope it helps :) https://github.com/VictorBjelkholm/js-ipfs-passing-data
