### ISSUE TITLE
CPU consumption peak during node creation: any suggestions to reduce and smooth it?

### ISSUE THREAD

**Issue by raphael10-collab** [ipfs/js-ipfs#3570]
I noticed a CPU consumption peak during node creation : 

    app.on('ready', async () => {
      createMainWindow();
      try {
        const node = await IPFS.create()
        const id = await node.id()
        console.log(id)
      } catch (err) {
        console.error(err)
      }
    })

![image](https://user-images.githubusercontent.com/70313067/108996001-2bff6400-769e-11eb-93fe-14976b448599.png)

![image](https://user-images.githubusercontent.com/70313067/108996154-581ae500-769e-11eb-8763-ce9638894d01.png)

When those lines are commented, and the node is not thus created, and I just import IPFS, 

    app.on('ready', async () => {
      createMainWindow();
      //try {
        //const node = await IPFS.create()
        //const id = await node.id()
        //console.log(id)
      //} catch (err) {
        //console.error(err)
      //}
    })

the CPU consumption at the app start is not that high

![image](https://user-images.githubusercontent.com/70313067/108996994-64ec0880-769f-11eb-8049-74f5ad219056.png)

What do you suggest me to do in order to reduce and smooth that high peek of CPU consumption that I have during the node creation?

**Comment by achingbrain** [comment]
IPFS does some work when it starts up, preparing libp2p, checking the repo, keys, etc, all of which requires use of the CPU.

Is this causing you a problem?

**Comment by raphael10-collab** [comment]
The CPU of the PC I'm using is not the newest technological advance but it's not so bad:

    (base) marco@pc01:~$ lscpu
    Architecture:        x86_64
    CPU op-mode(s):      32-bit, 64-bit
    Byte Order:          Little Endian
    CPU(s):              8
    On-line CPU(s) list: 0-7
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    NUMA node(s):        1
    Vendor ID:           GenuineIntel
    CPU family:          6
    Model:               60
    Model name:          Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Stepping:            3
    CPU MHz:             1571.321
    CPU max MHz:         4400,0000
    CPU min MHz:         800,0000
    BogoMIPS:            7982.13
    Virtualization:      VT-x
    L1d cache:           32K
    L1i cache:           32K
    L2 cache:            256K
    L3 cache:            8192K
    NUMA node0 CPU(s):   0-7

I'm thinking about the end-users of the app I'm developing, who certainly will be not that tech-savvy, and will use the app most of the time with their laptops.
If I'm experiencing a peak of 47% of CPU consumption, what do they will experience in their variable, and not controllable by me, environments?

**Comment by achingbrain** [comment]
If you'd like to do some CPU profiling and propose optimisations to the node startup that can be made, that would be helpful.

Otherwise unless there's sustained high CPU usage over time, I'm not sure there's a problem here.

**Comment by raphael10-collab** [comment]
I tried in a laptop, not a new model, and the CPU's usage peak reached 82%.

If it's not a problem, I close the issue.
