### ISSUE TITLE
Bump multibase to version 4.0.0

### ISSUE THREAD

**Issue by KyleMaas** [ipfs/js-ipfs#3574]
- **Version**:
Current git revision.

- **Platform**:
All

- **Subsystem**:
ipfs-core

#### Severity:
High - presently can't integrate IPFS support into ssb-browser-demo because of library incompatibility

#### Description:
multibase version 4.0.0 was just released containing a fix for an issue that was blocking us from integrating IPFS support into the ssb-browser-demo project (see https://github.com/multiformats/js-multibase/issues/80 for details).  It would be great if multibase could be upgraded to 4.0.0 so we could use IPFS without it crashing.

#### Steps to reproduce the error:
See https://github.com/multiformats/js-multibase/issues/80

**Comment by achingbrain** [comment]
Fixed by #3528

**Comment by KyleMaas** [comment]
Excellent.  Thank you!
