### ISSUE TITLE
No native build was found for platform=win32 arch=x64 runtime=electron abi=85 uv=1 libc=glibc with Electron, Vue and Typescript

### ISSUE THREAD

**Issue by Bholtland** [ipfs/js-ipfs#3582]
- **Version**:
0.5.2

- **Platform**:
Windows 10 64-bit 20H2 build:19042.844

#### Severity:
  High

#### Description:
I'm trying to get ipfs-core to work in my Electron application. Unfortunately upon running `const ipfs = await IPFS.create()` I'm getting the following error:

```UnhandledPromiseRejectionWarning:` Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=85 uv=1 libc=glibc at Function.load.path (webpack:///./node_modules/leveldown/node_modules/node-gyp-build/index.js?:56:9) at load (webpack:///./node_modules/leveldown/node_modules/node-gyp-build/index.js?:20:30) at eval (webpack:///./node_modules/leveldown/binding.js?:1:124) at Object../node_modules/leveldown/binding.js (_path-to-electron-dist-folder_\index.js:10537:1) at __webpack_require__ (_path-to-electron-dist-folder_\index.js:20:30) at eval (webpack:///./node_modules/leveldown/leveldown.js?:3:17) at Object../node_modules/leveldown/leveldown.js (_path-to-electron-dist-folder_\index.js:10570:1) at __webpack_require__ (_path-to-electron-dist-folder_\index.js:20:30) at eval (webpack:///./node_modules/level/level.js?:1:111) at Object../node_modules/level/level.js `(_path-to-electron-dist-folder_\index.js:10526:1)```

I've seen other issues with the same problem, but the problem there seems to be with Webpack

I've created the electron project using Vue-cli with Typescript and I'm running IPFS in main. I'm using Typescript and not Webpack.

#### Steps to reproduce the error:
My package.json contains the following:

```{
    "name": "project-name",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "serve": "vue-cli-service serve",
        "build": "vue-cli-service build",
        "lint": "vue-cli-service lint",
        "electron:build": "vue-cli-service electron:build",
        "electron:serve": "vue-cli-service electron:serve",
        "postinstall": "electron-builder install-app-deps",
        "postuninstall": "electron-builder install-app-deps"
    },
    "dependencies": {
        "@types/electron-devtools-installer": "^2.2.0",
        "axios": "^0.21.1",
        "compressing": "^1.5.1",
        "core-js": "^3.6.5",
        "dotenv": "^8.2.0",
        "form-data": "^4.0.0",
        "ipfs-core": "^0.5.2",
        "uuid": "^8.3.2",
        "vee-validate": "^3.4.5",
        "vue": "^2.6.11",
        "vue-class-component": "^7.2.3",
        "vue-property-decorator": "^9.1.2",
        "vue-router": "^3.4.9",
        "vuetify": "^2.4.3",
        "vuex": "^3.6.2"
    },
    "devDependencies": {
        "@types/node": "^14.14.25",
        "@types/uuid": "^8.3.0",
        "@types/vue": "^2.0.0",
        "@typescript-eslint/eslint-plugin": "^2.33.0",
        "@typescript-eslint/parser": "^2.33.0",
        "@vue/cli-plugin-babel": "~4.5.0",
        "@vue/cli-plugin-eslint": "~4.5.0",
        "@vue/cli-plugin-typescript": "^4.5.11",
        "@vue/cli-service": "~4.5.0",
        "@vue/eslint-config-typescript": "^5.0.2",
        "babel-eslint": "^10.1.0",
        "electron": "^11.0.0",
        "electron-devtools-installer": "^3.1.0",
        "eslint": "^6.8.0",
        "eslint-config-prettier": "^7.2.0",
        "eslint-plugin-prettier-vue": "^2.1.1",
        "eslint-plugin-vue": "^6.2.2",
        "node-sass": "^5.0.0",
        "prettier-eslint": "^12.0.0",
        "sass": "^1.32.6",
        "sass-loader": "^10.1.1",
        "source-map-loader": "^2.0.0",
        "typescript": "^4.1.3",
        "vue-cli-plugin-electron-builder": "~2.0.0-rc.6",
        "vue-cli-plugin-vuetify": "^2.1.0",
        "vue-template-compiler": "^2.6.11",
        "vuetify-loader": "^1.7.2"
    },
    "browserslist": [
        "> 1%",
        "last 2 versions",
        "not dead"
    ]
}
```

**Comment by achingbrain** [comment]
> I'm using Typescript and not Webpack.

This sounds a lot like https://github.com/ipfs/js-ipfs/issues/3530 or maybe https://github.com/ipfs/js-ipfs/issues/3525

`vue-cli-service` is probably using webpack behind the scenes.  Are you trying to run code built for the main process on the renderer thread or vice versa?

**Comment by Bholtland** [comment]
Thanks @achingbrain! I've seen those threads, but I didn't know `vue-cli-service` is running Webpack. I will see if I can tweak those settings through vue config. Regarding your question, I'm not sure what you mean. I'm running the IPFS code on the main thread. Thanks for you help!

**Comment by achingbrain** [comment]
> I didn't know vue-cli-service is running Webpack

It's very much all webpack down there: https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js

> I'm not sure what you mean

What I mean is, sometimes these tools use webpack to build for the browser or electron-renderer.  If you want to run IPFS in the main thread, you should configure it to use the `electron-main` [target](https://webpack.js.org/configuration/target/).

That said, I don't know a whole lot about how vue-cli-service works - you'll have to consult their docs to pick apart how it's invoking webpack and double-check what configuration it's using.

**Comment by Bholtland** [comment]
Ah I see. I think my best bet is to just rebuild the whole app piece by piece instead of using vue-cli and see if that helps. Will post if I find out more, as it may help others. Thanks again for the quick help here.

**Comment by Bholtland** [comment]
Well I've found the fix! I had to add `ipfs-core` in externals in vue.config.js like this:

```
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['ipfs-core'],
        }
    },
};
```

**Comment by julienmalard** [comment]
Thanks @Bholtland ! That fixed it for me as well (though changing `ipfs` for `ipfs-core` for my specific project).
