### ISSUE TITLE
IPNS Publish Does not work in JS-IPFS 0.54.2

### ISSUE THREAD

**Issue by TJKoury** [ipfs/js-ipfs#3584]
Publish doesn't work (`jsipfs name publish $(CID)`) using Ubuntu 18.04 LTS, Node 15, js-ipfs 0.54.2.   

Running two physical servers, both can see each other (`jsipfs swarm peers |grep $(peerID)`), both running RSA keys, both can resolve the IPFS CID for the content, but both report `record requested for $(IPNS_hash) was not found on the network.`

Both can resolve their own IPNS hash.

Go-IPFS can also see the peers but fails after about 30 seconds with the go-equivalent error `Error: could not resolve name`.

I have not tested any other version of js-ipfs.

_Originally posted by @TJKoury in https://github.com/ipfs/go-ipfs/issues/7965#issuecomment-793095839_

**Comment by TJKoury** [comment]
In addition, did force `dht` by setting `Routing.Type` to `dht` (tried `dhtclient` / `dhtserver` as well).

**Comment by TJKoury** [comment]
Also, tried setting `libp2p.config.dht.enabled` to `true`.

**Comment by TJKoury** [comment]
I have not, it’s next in my list.  I have tried everything to be able to
use it without actually changing any code; it’s safe to say that by
“experiment” you mean making code changes, I’m assuming to lib-p2p?

**Comment by vasco-santos** [comment]
> I have not, it’s next in my list.  I have tried everything to be able to

You can have a look in this: https://github.com/ipfs/js-ipfs/tree/master/examples/browser-ipns-publish (it is in the browser though)

> “experiment” you mean making code changes

experiment I mean to try out stuff using the current implementation by manually enabling it like you mentioned. We need to get the DHT updated like go-libp2p DHT was last year and get it properly tested in a larger scale before recommending its usage and eventually have it enabled by default.

Anyway, the insights I have from the go team is that IPNS is performing way better when using pubsub (they also have added a pubsub fallback that we need to add in JS)

**Comment by TJKoury** [comment]
Yup, already checked that out and will try today.  Good to hear about the
performance, makes sense when switching to a reactive model.

**Comment by TJKoury** [comment]
FYI, due to [this issue](https://github.com/parcel-bundler/parcel/issues/5943), need to downgrade parcel-bundler to `1.12.3` for this example to run.  Not submitting a pull because the issue is being actively worked over at parcel, will probably be ok soon.

**Comment by TJKoury** [comment]
API connection works ok, websockets error `Error: No transport available for address'.  Tried manually connecting a socket, was able to open a connection from browser console and telnet.

**Comment by TJKoury** [comment]
Still not working, using the same settings in the example folder.  Before I deconstruct the entire example for debugging, @vasco-santos anything obvious I'm missing?

**Comment by TJKoury** [comment]
Test still failing on fresh install.

```
Browser IPFS ready! Node id: Qmajeh6MvDHucLvyfEEH7cxTKXmxUZyE7h9kTbFxFeAnXx
   Connecting to /ip4/127.0.0.1/tcp/42245
   Success!
   Version go-ipfs/0.8.0/
   Peer ID 12D3KooWGVTSyhvFQVMZQVF55cFhZd9FUpk2RimyxvRY22hXBEZy
   Connecting to peer /ip4/127.0.0.1/tcp/41633/ws/p2p/12D3KooWGVTSyhvFQVMZQVF55cFhZd9FUpk2RimyxvRY22hXBEZy
   Error: No transport available for address /ip4/127.0.0.1/tcp/41633/ws/p2p/12D3KooWGVTSyhvFQVMZQVF55cFhZd9FUpk2RimyxvRY22hXBEZy at c.dial (http://127.0.0.1:57565/browser-ipns-publish.0579e265.js:2039:1958) at l.dialAction (http://127.0.0.1:57565/browser-ipns-publish.0579e265.js:2093:2581) at http://127.0.0.1:57565/browser-ipns-publish.0579e265.js:2091:1283 at async http://127.0.0.1:57565/browser-ipns-publish.0579e265.js:2087:505" (60099ms)
       at AsyncFunction.module.exports.<computed> [as browser-ipns-publish] (/home/tj/software/js-ipfs/examples/browser-ipns-publish/test.js:118:6)
       at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by vasco-santos** [comment]
There is no transport available for that address mean the transports you have configured do not support tcp. 

Browser does not support TCP, so you will need to configure websockets on your `go-ipfs` node. You can add in your configuration file:

```json
"Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip4/0.0.0.0/tcp/4010/ws",
```

This will mean that `go-ipfs` will have a listener for websocket connections on port 4010. Browser nodes will be able to use this for establishing connections with it.

**Comment by TJKoury** [comment]
So does this mean the example is not supposed to run out of the box?  If I get it working by changing the config in the test file using the `go-ipfs` package, should I submit a pull?

**Comment by vasco-santos** [comment]
The example has instructions for setting up the websocket transport on https://github.com/ipfs/js-ipfs/tree/master/examples/browser-ipns-publish#install-and-start-the-go-ipfs-node

**Comment by TJKoury** [comment]
@vasco-santos Talking about the example in the folder that has this in the config:

```
 Swarm: [
            "/ip4/127.0.0.1/tcp/0/ws",
          ]
```

Still failing with this config.

**Comment by TJKoury** [comment]
Even putting in hard-coded ports instead of '0' gets the same error with those ports:

```
Error: No transport available for address /ip4/192.168.1.227/tcp/4010/ws/p2p/12D3KooWNMPCseLnP8GvxuxEDCeTgL7EV1RLdtWBMt6vDwQPiGG6 at c.dial
```
From what I can tell the example just does not work.

**Comment by vasco-santos** [comment]
Ok, so I imagine that when you start your go node now, you can see it is listening on websockets, is this correct?

There is also a problem on the JS side. Apologies for not going directly into this particularity, but I did not realize we did not update this in this example. The websockets transport is not being used and the problem is related to the usage of a local address. Long story short, [browser policies](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#security_considerations) only allow dials when using WSS+DNS addresses, which is a pain because you need to configure that yourself on the go node. More context: https://github.com/protocol/web3-dev-team/pull/70

With the above in mind, we blocked these types of dial by default in libp2p. For local experimenting, you can have this changed. You can check how to do this [here](https://github.com/ipfs/js-ipfs/blob/master/examples/circuit-relaying/src/app.js#L47-L54). This basically allows localhost experimentation. You will probably need to use a localhost address for the `go-ipfs` node, in order to properly dial it.

If you are interested in updating the IPNS example with this configuration, it would be super helpful

**Comment by MisterY** [comment]
I'm getting
```
dial@http://localhost:1234/browser-ipns-publish.e31bb0bc.js:120141:21 dialAction@http://localhost:1234/browser-ipns-publish.e31bb0bc.js:123494:36 parcelRequire<["node_modules/libp2p/src/dialer/dial-request.js"]
```
with the example in it's current state.

**Comment by MisterY** [comment]
>You will probably need to use a localhost address for the `go-ipfs` node, in order to properly dial it.

Thanks for all the tips! I got it working with all of the above and referencing the go node (2nd step) with
```
/ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWSa7rHTYFw7aDmZv6SqosyY8HeLstqhon4nJ68rfVJ7wo
```
