### ISSUE TITLE
501 (Unsupported method ('POST')) in 49.0.4 ipfs-http-client

### ISSUE THREAD

**Issue by dxtr85** [ipfs/js-ipfs#3593]
- **Version**:
49.0.4 (I can not read version number, since for every API query I get 501 response.)

- **Platform**:
Linux ThinkPad 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Brave 1.21.74 Chromium: 89.0.4389.72 
Firefox 86.0 (64-bit)

- **Subsystem**:
ipfs-http-client
#### Severity:
High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
I cloned PubSub example from one of ipfs repos, changed client script to latest from 'https://cdn.jsdelivr.net/npm/ipfs-http-client/dist/index.js', and started it locally after CORS issues.
In response to ipfs.id() issued in console I received 501 - Unsupported method POST.
I expected an id of my local ipfs instance.

#### Steps to reproduce the error:
1. Follow instructions from https://blog.ipfs.io/2019-08-29-pubsub-in-the-browser/
2. Instead of "lite" client use one mentioned earlier from cdn.
3. Run example app in a browser with CORS set properly.
![Screenshot from 2021-03-16 16-02-16](https://user-images.githubusercontent.com/6146558/111334078-8d01d280-8673-11eb-824b-1a88a7612a48.png)

**Comment by BigLep** [comment]
Next steps:
1. Check out the example from the blog post
2. Attempt to replicate it
3. Make any fixes

**Comment by lidel** [comment]
@dxtr85 do you remember what is running on :8000? It does not look like IPFS API.
(Logs show your client sending requests to port `:8000` instead of API `:45005`)

**Comment by dxtr85** [comment]
@lidel You are right! For IpfsHttpClient instantiation I was using `apiUrl: url` instead of `url:url`
My bad, thank you! I do not know the details of how CORS work, and assumed that this POST request was being somehow redirected from 8000 to 5001 or 45005.
But as usual the issue was sitting between chair and keyboard :)
