### ISSUE TITLE
IPFS Repo JavaScript Implementation

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#36]
`ipfs-repo` is the module that implements and offers the functionality offer in [`repo spec`](https://github.com/ipfs/specs/tree/master/repo)

git repo: https://github.com/ipfs/js-ipfs-repo 

It should work natively using the fs or in the browser using local storage

js-ipfs-repo should be able to grab an ipfs repo generated by go-ipfs and manipulate it without breaking interopability.

**Comment by RichardLitt** [comment]
Thanks for this issue: added this to https://github.com/ipfs/ipfs/pull/116.

**Comment by diasdavid** [comment]
### js-ipfs-repo repo https://github.com/ipfs/js-ipfs-repo

Where you can help:
- https://github.com/ipfs/js-ipfs-repo/issues

thank you :)

**Comment by diasdavid** [comment]
Update:

Currently we have a working IPFS Repo implementation and @xicombd has helped getting that working on the browser as well. There is a bug however, which is that values being stored in localStorage are being converted to utf8 strings, adding a lot of information that is not required, making the buffer bigger (breaking the hash, size and so on).

We changed local-storage-blob-store to use hex strings, so that we could encode/decode that binary data, but that made some js-ipfs tests fail in the browser (although it passes all the abstract-blob-store tests). See https://github.com/xicombd/local-storage-blob-store/blob/master/index.js#L28 and run the browser tests in this repo by `npm run test:browser`

**Comment by diasdavid** [comment]
Update: ways you can help

- [ ] Up the code coverage (now at 90%)
- [ ] Tests for storing binary data through the datastore (blocks)
- [ ] Help document the items that are currently stored in go-ipfs levelDB https://github.com/ipfs/js-ipfs-repo/issues/21
- [ ] Create repo init feature (start each repo, put default files in each)
