### ISSUE TITLE
Remote services missing from ipfs-core ?

### ISSUE THREAD

**Issue by piskel** [ipfs/js-ipfs#3626]
- **Version**:
```ts
{
  version: '0.5.4',
  repo: 10,
  commit: '511147bedd51be3151de44a90fefe9425bfbcd50',
  'interface-ipfs-core': '^0.144.2'
}
```
- **Platform**:
Windows 10 Pro x64
Version 20H2 (OS Build 19042.867)

- **Subsystem**:
PIN

#### Severity:
Medium

#### Description:
When trying to use any function under `ipfs.pin.remote`, it says remote does not exist. And looking inside the ipfs-core folder in node_modules, I can't find the remote folder, unlike with ipfs-http-client.

My apologies if it is a duplicate or if I misunderstood something in the docs.

#### Steps to reproduce the error:
Creating a simple project with Typescript and no other dependencies than ipfs-core, ts-node and typescript.

The following code was used:

```ts
import IPFS from 'ipfs-core'

async function test()
{
    const ipfs = await IPFS.create();

    await ipfs.pin.remote.service.add('pinata', {
        endpoint: new URL('https://api.pinata.cloud'),
        key: "test"
    });

    await ipfs.stop();
}

test();
```

**Comment by achingbrain** [comment]
This is not implemented in js-ipfs yet - it's being done in #3588

These methods exist in the http client because you can use it with go-ipfs which has implemented the remote pinning API.
