### ISSUE TITLE
create is not a function

### ISSUE THREAD

**Issue by amitOodles** [ipfs/js-ipfs#3629]
I have set up ipfs on my linux 64 bit system, and i have the ipfs daemon running in the terminal, and the API server listening on /ip4/127.0.0.1/tcp/5001

Now i am trying the example at
https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#example-1

But that results in the following error 

`const ipfs = create()
TypeError: create is not a function at Object.<anonymous> (/home/amit/Projects/IPFS/node-ipfs/src/index2.js:2:14)`

I am using node version 13.14

**Comment by achingbrain** [comment]
Please see the sample code from the [currently released version](https://www.npmjs.com/package/ipfs-http-client#example) - it's different to that from master.
