### ISSUE TITLE
Can we upload .xml file ?

### ISSUE THREAD

**Issue by PradneshShinde** [ipfs/js-ipfs#3631]
I'm tring to upload .xml file  on IPFS via my nodeJS Project.
The file is getting uploaded.
But when i try to access it with the hash, something gets downloaded with extension as `file`.

Can someone let me know the feasibility of uploading .xml file and accessing the same.
Thank you.

**Comment by achingbrain** [comment]
Any file type will work, there's nothing specific required for xml files.

If you want to retain the filename, you will need to wrap your file in a directory - see: https://dweb-primer.ipfs.io/files-on-ipfs/wrap-directories-around-content

Please use https://discuss.ipfs.io for general help questions in future.
