### ISSUE TITLE
[Types] DAGAPI get requires CID but should also be `string|Uint8Array`?

### ISSUE THREAD

**Issue by rvagg** [ipfs/js-ipfs#3637]
Ref: https://github.com/ceramicnetwork/js-ceramic/pull/1194#discussion_r606629195

https://github.com/ipfs/js-ipfs/blob/63b11e5ac9d0b36d89ec23966e4523721878a7c0/packages/ipfs-core-types/src/dag/index.d.ts#L51

->

https://github.com/ipfs/js-ipfs/blob/63b11e5ac9d0b36d89ec23966e4523721878a7c0/packages/ipfs-core/src/components/dag/get.js#L14-L21

But `toCidAndPath()` still allows `string` and `Uint8Array`:

https://github.com/ipfs/js-ipfs/blob/63b11e5ac9d0b36d89ec23966e4523721878a7c0/packages/ipfs-core-utils/src/to-cid-and-path.js#L8-L12

**Comment by CSDUMMI** [comment]
What is the problem here?
