### ISSUE TITLE
Swarm connect doesn't accept arbitrary addresses

### ISSUE THREAD

**Issue by JoranHonig** [ipfs/js-ipfs#3663]
#### Description:
I'm trying to build a script which connects to a particular node. To do so I'm using the swarm connect interface. 

Looking at the documentation, it seems like I should be able to just pass in any valid multi addr, but none seem to work. In the steps to reproduce I've included a minimal example that exhibits the behaviour. 

It'll output: ` Error: multiaddr must have a valid format: "/{ip4, ip6, dns4, dns6}/{address}/{tcp, udp}/{port}".` 

I could very well be misunderstanding how you're supposed to interact with this interface, but the documentation doesn't seem to talk about this.

#### Steps to reproduce the error:
```javascript
// example.js
const IPFS = require('ipfs-core')
const { multiaddr } = require('multiaddr')

const PEER_0 = multiaddr("/ip4/127.0.0.1/tcp/4001/p2p/QmLocalNode")


async function main() {
    const ipfs = await IPFS.create()
    console.log(await ipfs.swarm.addrs())

    console.log("Connecting to peer 0")
    await ipfs.swarm.connect(PEER_0)
    console.log("Done connecting to peer 0")
}

main()
```

`node example.js`

Versions:
`ipfs-core == 0.5.4`
`libp2p == 0.30.12`

**Comment by vasco-santos** [comment]
Hello @JoranHonig 

I just tried using `ipfs-core@0.7.0` and `multiaddr@9.0.1` and this is working for me. This was happening probably for a mismatch of versions of `multiaddr`. Can you try again updating the dependencies?

If this is still problematic, can you run with debug mode `DEBUG=* node example.js`, so that I can have a zoomed in understanding of the underlying issue + multiaddr version

**Comment by lidel** [comment]
Closing – assuming this is no longer an issue in the latest version.
@JoranHonig please reopen with more info if you are able to reproduce.

**Comment by JoranHonig** [comment]
Hey @lidel and @vasco-santos,

Apologies, I had this on the todolist but didn't get to it.
You're totally right, the latest version behaves completely as expected. 

Thanks for the help 🙌, and apologies for not trying this myself first 😓
