### ISSUE TITLE
Add directory list command (files.ls)

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#368]
Add `files.ls(hash)` command so that added directories can be listed.

**Comment by diasdavid** [comment]
@haadcode has mentioned on the last sprint meeting that this is no longer a priority, postponing to the Milestone of Full Feature parity

**Comment by haadcode** [comment]
No, `cat` with offset isn't a priority anymore (it never was, miscommunication in Lisbon).

This would be nice to have asap. I need it to display directories in Orbit (works currently only in the Electron app). However, this *can be* postponed after interop has been done because I can't use it anyways in Orbit until js-ipfs can fetch the added directories from go-ipfs.

**Comment by diasdavid** [comment]
let's track this one in the Files tracking issue: https://github.com/ipfs/js-ipfs/issues/60
