### ISSUE TITLE
E2E Tests for Examples Needed

### ISSUE THREAD

**Issue by logasja** [ipfs/js-ipfs#3691]
- **Version**:

Current master commit

- **Platform**:

Linux (Hostname) 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

- **Subsystem**:

N/A

#### Severity:

Low

#### Description:

I have been running into issues with my Vue project using ipfs-core, in an attempt to see if it was just my configuration I cloned the js-ipfs repository and attempted to compile and run the Vue example. This example also failed to compile. Curious, I attempted to compile other examples and several of those I tested do not work. Here I am proposing that commits to master are tested with tests for the examples. This will have the added benefit of ensuring examples here are up to date as well.

**Comment by achingbrain** [comment]
There are already e2e tests for all examples that are run in CI on every commit - see [these lines](https://github.com/ipfs/js-ipfs/blob/master/.travis.yml#L291-L296) in `.travis.yml`.

What was the compilation error you saw?

**Comment by logasja** [comment]
Using node 16.2.0 I'm getting 

```
ERROR  Failed to compile with 2 errors                                                                       7:56:03 PM
 error  in ./node_modules/ipfs/src/index.js

Module not found: Error: Can't resolve 'ipfs-core' in '/home/*****/source/js-ipfs/examples/browser-vue/node_modules/ipfs/src'

 error  in ./node_modules/vue/dist/vue.runtime.esm.js

Module not found: Error: Can't resolve 'console-browserify' in '/home/*****/source/js-ipfs/examples/browser-vue/node_modules/vue/dist'
```

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

@logasja it seems like your bundler or package.json was misconfigured. Please try Helia going forward and let us know if you have issues!
