### ISSUE TITLE
Cannot find module 'bcrypto.node'

### ISSUE THREAD

**Issue by AbhinavMir** [ipfs/js-ipfs#3696]
Hi, I've tried to initiate `jsipfs daemon` but I get this error:
```
Cannot find module 'bcrypto.node'
```

I've resintalled all files, made sure bcrypto is installed, yet I run into this error. Any solution?

Device: Ubuntu 20.04, npm 7.13.0, node 16.2.0, js-ipfs v0.5.1

**Comment by lidel** [comment]
Triage note: this will soon be solved in near release of js-ipfs (crypto deps improved recently)

**Comment by lidel** [comment]
This should be fixed in latest js-ipfs, please upgrade and fill a new issue if problem is still present.
