### ISSUE TITLE
yarn add ipfs have an unexpected error

### ISSUE THREAD

**Issue by herexu** [ipfs/js-ipfs#3710]
` $yarn add ipfs
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > debug@4.1.1: Debug v
ersions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when u
sed in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (
https://github.com/visionmedia/debug/issues/797)
warning ipfs > ipfs-core > ipfs-bitswap > libp2p-interfaces > sinon@10.0.1: Brea
king change found in this patch version
warning ipfs > ipfs-core > libp2p > @motrix/nat-api > request@2.88.2: request ha
s been deprecated, see https://github.com/request/request/issues/3142
warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > socket.io-parser > d
ebug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDo
s regression when used in a Node.js environment. It is recommended you upgrade t
o 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > engine.io > debug@4.
1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regre
ssion when used in a Node.js environment. It is recommended you upgrade to 3.2.7
 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning ipfs > ipfs-cli > ipfs-daemon > wrtc > node-pre-gyp@0.13.0: Please upgra
de to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated an
d only the @mapbox scoped package will recieve updates in the future
warning ipfs > ipfs-cli > ipfs-daemon > prometheus-gc-stats > gc-stats > node-pr
e-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gy
p package is deprecated and only the @mapbox scoped package will recieve updates
 in the future
warning ipfs > ipfs-core > libp2p > @motrix/nat-api > request > har-validator@5.
1.5: this library is no longer supported
info There appears to be trouble with your network connection. Retrying...
warning ipfs > ipfs-cli > ipfs-daemon > electron-webrtc > electron-eval > electr
on > electron-download > nugget > request@2.88.2: request has been deprecated, s
ee https://github.com/request/request/issues/3142
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://github.com/paulkernfeld/node-headle
ss/tarball/master: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information p
rovided in "D:\\project\\demo\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this comm
and.
`
`$ node -v
v14.17.0
`
`
$ yarn -v
1.22.5
`

**Comment by achingbrain** [comment]
> There appears to be trouble with your network connection. Retrying...

This looks like an intermittent problem with your connection?

**Comment by herexu** [comment]
> > There appears to be trouble with your network connection. Retrying...
> 
> This looks like an intermittent problem with your connection?

you are right , the network error
