### ISSUE TITLE
ipfs daemon is success ,but ipfs swarm peers had a error

### ISSUE THREAD

**Issue by herexu** [ipfs/js-ipfs#3711]
1.

`$ yarn add ipfs
$ jsipfs daemon
`
Initializing IPFS daemon...
js-ipfs version: 0.6.1
System version: x64/win32
Node.js version: 14.17.0
Swarm listening on /ip4/192.168.3.116/tcp/4002/p2p/QmNVpPtEBo6cWM2woVjZBcfPUhitq7PHEoUCzyEcbKJ8kj
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmNVpPtEBo6cWM2woVjZBcfPUhitq7PHEoUCzyEcbKJ8kj
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmNVpPtEBo6cWM2woVjZBcfPUhitq7PHEoUCzyEcbKJ8kj
HTTP API listening on /ip4/127.0.0.1/tcp/5002/http
gRPC listening on /ip4/127.0.0.1/tcp/5003/ws
Gateway (read only) listening on /ip4/127.0.0.1/tcp/9090/http
Web UI available at http://127.0.0.1:5002/webui
Daemon is ready

**then** open http://127.0.0.1:5002/webui in browser ,IPFS API can not connet
i have add the cross-origin (CORS) requests ,the IPFS API cannot connet also

jsipfs add is success, **BUT** i can't open in browser  https://ipfs.io/ipfs/QmWXatpvz7MpQ1WQBd9nGnMewFCkCwV6eww7XhkC5RxPMV 

$ jsipfs add ./hello.txt
added QmWXatpvz7MpQ1WQBd9nGnMewFCkCwV6eww7XhkC5RxPMV hello.txt
Done in 0.92s.

and then i checke the status
$ ipfs swarm peers
Error: this action must be run in online mode, try running 'ipfs daemon' first

so , It's a dead cycle

i don't know what the problem

**Comment by stallingerl** [comment]
same issue

**Comment by mrheat** [comment]
i have that too

**Comment by achingbrain** [comment]
Are you running `js-ipfs` or `go-ipfs`?  You switch between `ipfs` (`go-ipfs`) and `jsipfs` (`js-ipfs`) CLI commands above which is confusing.

This error is important:

> Error: this action must be run in online mode, try running 'ipfs daemon' first

You are running `ipfs swarm peers` without starting the ipfs daemon.  If the daemon is not running, you'll not have any swarm peers and the gateway will not be able to fetch content from you.

Please can you use https://discuss.ipfs.io for these sort of problems in future - it has much better visibility than GitHub issues & this issue tracker is for js-ipfs development.
