### ISSUE TITLE
Feature: Programmatic way to re-initialise repo

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/js-ipfs#3717]
Sometimes the repo corrupts, or can't be migrated (like [here](https://stackoverflow.com/questions/67916277/unhandledpromiserejectionwarning-invalidrepoversionerror-incompatible-repo-ver)), and it needs to be manually deleted. This can be quite unintuitive for a user, and if a programmer wanted to handle it, I believe right now it'd be easiest to just create a new repo with a new name.

What I'm proposing is a function like `IPFS.remove(repo string)` so the error could be caught and handled, with the repo able to be easily removed if necessary.

**Comment by lidel** [comment]
This could be useful porcelain in browser context, but low priority.

**Comment by BigLep** [comment]
Per 2021-11-12, @TheDiscordian may take this as part of BootCamp.  w00t w00t!

**Comment by TheDiscordian** [comment]
@BigLep unfortunately I forgot! (I took on 3 ideas apparently, but I did make one of them :sweat_smile:)

**Comment by lidel** [comment]
@TheDiscordian maybe Launchpad v2  ?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

Helia is not sharing ipfs configuration with Kubo AFAIK, Helia docs to confirm!
