### ISSUE TITLE
Importing with Svelte+Rollup fails with `Failed to resolve module specifier "crypto"`

### ISSUE THREAD

**Issue by kotx** [ipfs/js-ipfs#3721]
- **Version**: Can't import to run it, but version of `ipfs-core` in package.json is `^0.8.0`

- **Platform**: Windows 64-bit, Chromium Edge 91.0.864.48 (Official build) (64-bit)

- **Subsystem**: Core

#### Description:

The following error occurs in the browser after ipfs-core is bundled:
```
Uncaught (in promise) TypeError: Failed to resolve module specifier "crypto". Relative references must start with either "/", "./", or "../".
```
In the browser it specifically fails at
`import crypto$6 from 'crypto';`

No errors occur when bundling.

#### Steps to reproduce the error:
- Create default svelte application from template
- Run `node scripts/setupTypescript.js` - could be unrelated
- `pnpm add ipfs-core`
- In a .svelte file:
```js
import IPFS from "ipfs-core";
```
- Check console in browser

**Comment by kotx** [comment]
Never mind, turns out `transformMixedEsModules: true` is required in the `commonjs()` call in Rollup plugins.

**Comment by phazejeff** [comment]
I am getting a similar problem, but my error says this:
`Uncaught ReferenceError: crypto$6 is not defined`

and setting `transformMixedEsModules: true` in the `commonjs()` function didn't fix it.

**Comment by kotx** [comment]
@phazejeff I ended up using https://github.com/snowpackjs/rollup-plugin-polyfill-node with this rollup.config.js:
```js
import { terser } from "rollup-plugin-terser";
import commonjs from "@rollup/plugin-commonjs";
import css from "rollup-plugin-css-only";
import json from "@rollup/plugin-json";
import livereload from "rollup-plugin-livereload";
import nodePolyfills from "rollup-plugin-polyfill-node";
import resolve from "@rollup/plugin-node-resolve";
import svelte from "rollup-plugin-svelte";
import sveltePreprocess from "svelte-preprocess";
import typescript from "@rollup/plugin-typescript";

const production = process.env.NODE_ENV === "production" || !process.env.ROLLUP_WATCH;

function serve() {
    let server;

    function toExit() {
        if (server) server.kill();
    }

    return {
        writeBundle() {
            if (server) return;
            server = require("child_process").spawn("pnpm", ["start", "--", "--dev"], {
                stdio: ["ignore", "inherit", "inherit"],
                shell: true
            });

            process.on("SIGTERM", toExit);
            process.on("exit", toExit);
        },
        closeWatcher: toExit
    };
}

export default {
    input: "src/main.ts",
    output: {
        sourcemap: !production,
        format: "es",
        name: "app",
        dir: "public/build/"
    },
    plugins: [
        svelte({
            preprocess: sveltePreprocess({ sourceMap: !production }),
            compilerOptions: {
                dev: !production
            }
        }),

        css({ output: "bundle.css" }),
        json(),

        nodePolyfills({
            sourceMap: !production
        }),
        resolve({
            browser: true,
            dedupe: ["svelte"]
        }),
        commonjs(),
        typescript({
            sourceMap: !production,
            inlineSources: !production
        }),

        // In dev mode, call `npm run start` once
        // the bundle has been generated
        !production && serve(),

        // Watch the `public` directory and refresh the
        // browser on changes when not in production
        // WARNING: Breaks service worker
        !production && livereload({ watch: "public" }),

        // If we"re building for production (pnpm build
        // instead of pnpm dev), minify
        production && terser()
    ],
    watch: {
        clearScreen: false
    }
};
```
Hope this helps.

**Comment by phazejeff** [comment]
I'm still getting the same error. Would you happen to have a repository of your project that I could look at?

**Comment by kotx** [comment]
> I'm still getting the same error. Would you happen to have a repository of your project that I could look at?

https://github.com/kotx/yoru

**Comment by kotx** [comment]
My bad, I forgot to mention that I just used the built file in dist/index.min.js.

**Comment by phazejeff** [comment]
It seems to only work using the built in dist/index.min.js. I was able to get it working after some messing around with the rollup.config.js, and made this [template svelte app](https://github.com/phazejeff/IPFS-Svelte-Template) that fetches and displays data from an IPFS hash for anyone to use if they come across this thread due to the same issues.
