### ISSUE TITLE
feat: use preload nodes for delegated IPNS operations

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3722]
The preload nodes will have the new experimental go-ipfs DHT implementation deployed which speeds up IPNS record put/gets.

We should use a delegate to use the preload nodes for ipfs in the browser to speed these operations up in a similar way to how we do content and peer routing.

Refs: https://github.com/libp2p/js-libp2p-delegated-content-routing/issues/49 https://github.com/ipfs/js-ipfs/issues/2921

**Comment by rysiekpl** [comment]
Hey hey, any news/movement on this? This is blocking an issue that is making it impossible to use IPNS/IPFS in a project of mine (#2921).

Thanks!

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This should be handled in Helia once https://github.com/libp2p/js-libp2p-delegated-content-routing/issues/49 is resolved.
