### ISSUE TITLE
Duplicate Messages Received Over PubSub

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/js-ipfs#3724]
**Version**:

0.5.4

 **Platform**:

`Linux TheDesktop 5.10.42-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021 x86_64 GNU/Linux`

Opera: Version:76.0.4017.177

Brave: Version 1.25.68

 **Subsystem**:

Probably libp2p

#### Severity:

High

#### Description:

- What you did

Sent some messages using a chat application I'm developing between me and another user, many nodes connected.

- What happened

Some of those messages were received twice, from two different originating nodes (AFAIK, that should be impossible).

- What you expected to happen

Messages sent once, duplicates ignored. https://github.com/libp2p/specs/tree/master/pubsub#message-identification says origin stamping should be in force, so I assumed this situation is impossible:

> Pubsub requires to uniquely identify messages via a message ID. This enables a wide range of processes like de-duplication, tracking, scoring, circuit-breaking, and others.
>
> The message_id is calculated from the Message struct.
> 
> By default, origin-stamping is in force. This strategy relies on the string concatenation of the from and seqno fields, to uniquely identify a message based on the author.

#### Steps to reproduce the error:

This was discovered in chat software I'm developing: http://portal.thedisco.zone/testing/chat_experiments/

The peers involved were several browsers, some physically in different locations, at least one over a bad VPN. I've been doing a lot of testing between different types of peers.

This bug is incredibly hard to reproduce, and I've not been able to reproduce it yet. However because it happened once, I assume it can happen again. I can add in loggers dumping whatever information is needed, and continue doing my regular testing, I'd just need to know what information would be the most useful to log because again, I haven't been able to reproduce this *at all*, and I've been testing this for weeks.

In the screenshot below, you can see 3 repeated messages with the timestamp 14:15:48, duplicates from messages above. This shouldn't be possible as the usernames are generated by `message.from`, retrieving data related to that ID, and further the colour is also generated from that. The message itself is also identical, so these are repeated messages.

![PubSub-Duplicate-Messages](https://user-images.githubusercontent.com/43145244/122992430-1c560a80-d374-11eb-8f97-d4ae53e72dc8.png)

**Comment by TheDiscordian** [comment]
Alright I was doing some testing and this occurred it seems after the VPN tab I was using lost connection and then got it back, I think a couple times. So that seems to be a good way to replicate it, have an interface go down.

**Comment by fusetim** [comment]
It seems that it is not up to the node to check if messages are duplicated/uniques. The only thing it keeps is a recent list of messages that the node has received (according to a ttl, by default 2 minutes). Thanks to this cache, the node determines if it should send the message to its other peers or not.

> ***We also keep a seen cache***, which is a timed least-recently-used cache of message IDs that we have observed recently. The value of ***"recently" is determined by the parameter seen_ttl, with a reasonable default of two minutes.*** This value should be chosen to approximate the propagation delay in the overlay, within a healthy margin.
> The seen cache serves two purposes. In all pubsub implementations, ***we can first check the seen cache before forwarding messages to avoid wastefully republishing the same message multiple times***. For gossipsub in particular, the seen cache is used when processing an IHAVE message sent by another peer, so that we only request messages we have not already seen before.
> ~ *according to: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#message-cache*

**Comment by TheDiscordian** [comment]
@fusetim To me it would make more sense to not pass a duplicated message onto the application by default, because otherwise everyone would implement the same code to build a `message_id` and then cross-reference it with their own map, which is basically just:

```javascript
var msgIds = new Map();

function recv(msg) {
	let msgid = msg.from + Uint8Array.from(msg.seqno);
	if (msgIds.has(msgid)) { // seen before, reject
		return
	}
	msgIds.set(msgid);
	
	// handle msg here
}
```

Additionally, if someone wanted to change how messages are identified as unique, they're supposed to be able to set a unique `message_id` via `message_id_fn` anyways. However upon re-reading, I don't see what `message_id` is supposed to be used for, or where it's supposed to be stored, just that it "enables a wide range of processes like de-duplication, tracking, scoring, circuit-breaking, and others".

I believe that spec you've quoted is to avoid messages getting republished forever. It's fine if messages get republished sometimes, but my understanding of what I've quoted above is that if a repeated message is received due to a rebroadcast, that it shouldn't be passed onto the application. However I see what you mean (after reading it a couple times...), it looks like if 2mins pass, then gossipsub forgets about the message, and no longer considers it a duplicate :eyes: .

If that's the case, without embedding some sort of timestamp, anyone could pose as anyone if they have enough messages stashed away.

Either way, this isn't don't seem to be a bug with js-ipfs, thanks @fusetim, closing this.
