### ISSUE TITLE
Issue in webui with jsipfs@0.55.4

### ISSUE THREAD

**Issue by ti0** [ipfs/js-ipfs#3726]
- **Version**:

0.55.4

- **Platform**:

Linux p1 5.4.0-1048-aws #50~18.04.1-Ubuntu SMP Tue May 4 17:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 

- **Subsystem**:

#### Severity:

Medium

#### Description:

When I run the jsipfs daemon, I then go to the `webui` endpoint which loads as expected. It shows "Connected to IPFS" for up to 10 seconds, and then says it is unable to connect to IPFS. I did some debugging and discovered the issue is in the `/api/v0/stats/bw` endpoint which is returning a 500 error after a few seconds of the server running:

> `The number 2365.640062119891 cannot be converted to a BigInt because it is not an integer`

This results in the UI saying that IPFS is not connected, even though the daemon runs fine. The only thing that is not working is the webui. Marked as medium severity because it is not "essential" but would be great to have a working webui.

#### Steps to reproduce the error:

Just run the daemon, load the webui, and wait about 15 seconds.

Issue is currently seen on https://ipfs.rauction.house/webui
Note: I have already setup CORS correctly, that is confirmed because the webui shows "Connected to IPFS" for the first 10 seconds of the daemon running. On this site, just open dev tools > Network panel, and you will see a bunch of 500s from the endpoint listed above.

**Comment by lidel** [comment]
Thanks!  So the bug here is not really in ipfs-webui, but js-ipfs:

`/api/v0/stats/bw` sometimes returns error `The number 2365.640062119891 cannot be converted to a BigInt because it is not an integer`.

This is ready to work on, if someone has time to look into it.
