### ISSUE TITLE
Example in documentation for usage with Pinata

### ISSUE THREAD

**Issue by dabit3** [ipfs/js-ipfs#3727]
I've been digging and have not been able to find out how to connect to Pinata with `ipfs-http-client/`. I did see some things [here](https://github.com/ipfs/js-ipfs/blob/9bc2d7ca4fa4adcefd1cb8d95de4711ed4f7861c/docs/core-api/PIN.md) but was still unable to get this to work.

Considering Pinata is such a widely used service, is there any way we can get a code snippet that shows how this would work when calling Pinata from a client application?

If someone here can explain more I'd be happy to either submit the PR myself or comment here with a full code snippet for future reference.

**Comment by lidel** [comment]
@dabit3 try following https://docs.ipfs.io/how-to/work-with-pinning-services/ and https://pinata.cloud/documentation#PinningServicesAPI + make sure you use go-ipfs [0.8.0 or later](https://github.com/ipfs/go-ipfs/releases/v0.8.0). 

fysa we use ipfs-http-client in ipfs-webui, so there seem nothing to do here.
feel free to reopen with more info (eg. steps to reproduce a bug, or bug in docs)
