### ISSUE TITLE
Fix for Node.js 6.3.3

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#373]
Following: https://github.com/ipfs/js-ipfs/pull/355

- [x] rebase latest duplexify in duplexify fork https://github.com/ipfs/js-ipfs/pull/355#issuecomment-231333732
- [x] update all the deps that use duplexify

**Comment by dignifiedquire** [comment]
@diasdavid I think this is finished, please close if you agree

**Comment by diasdavid** [comment]
Looks like it :)
