### ISSUE TITLE
DHT findProvs not working - Nodejs

### ISSUE THREAD

**Issue by JamieRez** [ipfs/js-ipfs#3734]
- **Version**: ```{
  version: '0.8.0',
  repo: '10',
  commit: '81f944163f5a78ef15fdc23b2c488ba7f44af0be',
  'interface-ipfs-core': '^0.147.0'
}```

- **Platform**: Node.js

- **Subsystem**: DHT

#### Description:  cid.toBaseEncodedString is not a function
I'm following the findProvs example from the docs at https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DHT.md#example-1
```
const providers = ipfs.dht.findProvs('QmdPAhQRxrDKqkGPvQzBvjYe3kU8kiEEAd2J6ETEamKAD9')
for await (const provider of providers) {
  console.log(provider.id.toString())
}
```

When the code runs, my nodejs server crashes with this error: 
```
/node_modules/libp2p-kad-dht/src/providers.js:202
      this._log('getProviders %s', cid.toBaseEncodedString())                                    ^
TypeError: cid.toBaseEncodedString is not a function
```

I wasn't sure if this was a personal problem until I found [this](https://stackoverflow.com/questions/67823554/js-ipfs-error-cid-tobaseencodedstring-is-not-a-function) and then I found [this closed issue](https://github.com/ipfs/js-ipfs/issues/3502) and it seems it was closed prematurely. So here it is again, can we solve it?

**Comment by achingbrain** [comment]
The problem is the example is wrong - `ipfs.dht.findProvs` [takes a CID](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DHT.md#parameters-1) not a string.

It's a quick fix to update the docs, would you like to open a PR that does so?

**Comment by JamieRez** [comment]
> The problem is the example is wrong - `ipfs.dht.findProvs` [takes a CID](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DHT.md#parameters-1) not a string.
> 
> It's a quick fix to update the docs, would you like to open a PR that does so?

No. It gives the same error even if you pass a CID. Not a quick fix

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/js-ipfs/issues/3502
