### ISSUE TITLE
Issue with example for ipfs add

### ISSUE THREAD

**Issue by sreeharshar84** [ipfs/js-ipfs#3740]
The example in ipfs.add (https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsadddata-options) lists the following example. 

This is clearly wrong, there is no variable with the name "content"

const file = {
  path: '/tmp/myfile.txt',
  content: 'ABC'
}

const result = await ipfs.add(content)

console.info(result)

/*
Prints:
{
  "path": "tmp",
  "cid": CID("QmWXdjNC362aPDtwHPUE9o2VMqPeNeCQuTBTv1NsKtwypg"),
  "mode": 493,
  "mtime": { secs: Number, nsecs: Number },
  "size": 67
}
*/

- **Version**:

- **Platform**:

- **Subsystem**:

**Comment by TheDiscordian** [comment]
Appears to be a typo in your example:

`const result = await ipfs.add(content)`

should be:

`const result = await ipfs.add(file)`

**Comment by sreeharshar84** [comment]
This worked for me:
var currentDate = new Date().getTime();
      const input = [{
        .....
            {
                "trait_type": "date",
                "value": currentDate
            }
        ]
       }]
      const file = {
        path: '/tmp/myfile.txt',
        content: Buffer.from(JSON.stringify(input))
      }
      
      const result = await ipfs.add(file)
      
      console.info(result)
