### ISSUE TITLE
Issues bundling `ipfs` with browserify

### ISSUE THREAD

**Issue by oliveriosousa** [ipfs/js-ipfs#3742]
- **Version**:
`"ipfs": "^0.55.4"`

- **Platform**:

- **Subsystem**:

#### Severity:
Medium

#### Description:
Error bundling `ipfs` with browserify using the example `browser-browserify`

`Error: Can't walk dependency graph: Cannot find module 'multiformats/hashes/sha2'`

This error may be related to the latest commits to `js-libp2p-crypto` 

#### Steps to reproduce the error:

1. Clone `ipfs`
2. cd examples/browser-browserify
3. npm run bundle

**Comment by achingbrain** [comment]
This is probably related to some of the magic that [multiformats](https://github.com/multiformats/js-multiformats) does around esm/cjs/browser transpilation and bundling.

cc @rvagg @Gozala

**Comment by achingbrain** [comment]
I think there's something messed up with how esbuild handles the `browser` field.

The import is [here](https://github.com/libp2p/js-libp2p-crypto/blob/94966df10f86e3844363780873f03518138cf874/src/keys/ed25519-class.js#L5).  It should be covered by either the `exports` or the `browser` field in the published `package.json`:

```js
//...
  "exports": {
    //...
    "./hashes/sha2": {
      "browser": "./esm/src/hashes/sha2-browser.js",
      "require": "./cjs/src/hashes/sha2",
      "import": "./esm/src/hashes/sha2"
    },
//...
  "browser": {
    //...
    "./hashes/sha2": "./cjs/src/hashes/sha2-browser.js",
```

but I don't think it's using those fields to resolve internal imports, so it tries to load the default `sha2.js` which imports the node `crypto` module.

It starts to work if I change the `browser` field locally to be:

```js
//...
  "browser": {
    //...
    "./hashes/sha2": "./cjs/src/hashes/sha2-browser.js",
    "./esm/src/hashes/sha2.js": "./esm/src/hashes/sha2-browser.js"
```

This field is generated by [ipjs](https://www.npmjs.com/package/ipjs).

To generate the above `browser` field entry [this line](https://github.com/mikeal/ipjs/blob/master/src/package/index.js#L201) needs a new block under it like:

```js
      json.browser[key] = _join('cjs', _browser)
      
      if (_import !== _browser) {
        json.browser[_join('esm', _import)] = _join('esm', _browser)
        json.browser[_join('cjs', _import)] = _join('cjs', _browser)
      }
```

**Comment by achingbrain** [comment]
(nb. I see this with the examples during the post-install bundling of ipfs-core, before it's even got to the browserify bit).

**Comment by achingbrain** [comment]
That said I'm having problems replicating this outside of this repo.

**Comment by achingbrain** [comment]
Actually this is trivial to replicate.  Just do:

```js
const basics = require('multiformats/basics')
```

The `basics` file is found at `esm/src/basics.js` and it imports `./hashes/sha2.js`.

The relevant esbuild logs are:

```
 > verbose: Resolving import "./hashes/sha2.js" in directory "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/esm/src" of type "import-statement"
   note: Read 5 entries for directory "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/esm/src/hashes"
   note: Checking for "esm/src/hashes/sha2.js" in the "browser" map in "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/package.json"
   note:   Checking for "esm/src/hashes/sha2.js"
   note:   Checking for "esm/src/hashes/sha2.js.tsx"
   note:   Checking for "esm/src/hashes/sha2.js.ts"
   note:   Checking for "esm/src/hashes/sha2.js.jsx"
   note:   Checking for "esm/src/hashes/sha2.js.js"
   note:   Checking for "esm/src/hashes/sha2.js.css"
   note:   Checking for "esm/src/hashes/sha2.js.json"
   note:   Checking for "esm/src/hashes/sha2.js/index"
   note:   Checking for "esm/src/hashes/sha2.js/index.tsx"
   note:   Checking for "esm/src/hashes/sha2.js/index.ts"
   note:   Checking for "esm/src/hashes/sha2.js/index.jsx"
   note:   Checking for "esm/src/hashes/sha2.js/index.js"
   note:   Checking for "esm/src/hashes/sha2.js/index.css"
   note:   Checking for "esm/src/hashes/sha2.js/index.json"
   note: Checking for "./esm/src/hashes/sha2.js" in the "browser" map in "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/package.json"
   note:   Checking for "./esm/src/hashes/sha2.js"
   note:   Checking for "./esm/src/hashes/sha2.js.tsx"
   note:   Checking for "./esm/src/hashes/sha2.js.ts"
   note:   Checking for "./esm/src/hashes/sha2.js.jsx"
   note:   Checking for "./esm/src/hashes/sha2.js.js"
   note:   Checking for "./esm/src/hashes/sha2.js.css"
   note:   Checking for "./esm/src/hashes/sha2.js.json"
   note:   Checking for "./esm/src/hashes/sha2.js/index"
   note:   Checking for "./esm/src/hashes/sha2.js/index.tsx"
   note:   Checking for "./esm/src/hashes/sha2.js/index.ts"
   note:   Checking for "./esm/src/hashes/sha2.js/index.jsx"
   note:   Checking for "./esm/src/hashes/sha2.js/index.js"
   note:   Checking for "./esm/src/hashes/sha2.js/index.css"
   note:   Checking for "./esm/src/hashes/sha2.js/index.json"
   note: Failed to find "esm/src/hashes/sha2.js"
   note: Attempting to load "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/esm/src/hashes/sha2.js" as a file
   note:   Checking for file "sha2.js"
   note:   Found file "sha2.js"
   note: Read 5 entries for directory "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/esm/src/hashes"
   note: Ignoring "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/tsconfig.json" because "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/esm/src/hashes/sha2.js" is inside "node_modules"
   note: Primary path is "/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-core/node_modules/multiformats/esm/src/hashes/sha2.js" in namespace "file"
```

So `./hashes/sha2.js` is being resolved to `esm/src/hashes/sha2.js` as that's the directory it is in within the `multiformats` module.

esbuild checks the `browser` map for an override for `esm/src/hashes/sha2.js` but doesn't find one, so tries to transpile `esm/src/hashes/sha2.js` which has the `crypto` import, which it can't resolve and then explodes.

**Comment by achingbrain** [comment]
https://github.com/evanw/esbuild/issues/1443

**Comment by achingbrain** [comment]
https://github.com/browserify/resolve/issues/250#issuecomment-879241002

**Comment by achingbrain** [comment]
https://github.com/mikeal/ipjs/pull/13

**Comment by achingbrain** [comment]
https://github.com/multiformats/js-multiformats/pull/105

**Comment by achingbrain** [comment]
@oliveriosousa this should be fixed now, though you'll need to delete any node_modules folders and lockfiles you have to make sure you get `multiformats@9.4.1` in your dep tree.  Could you try again please?

**Comment by oliveriosousa** [comment]
@achingbrain works like a charm 👍
