### ISSUE TITLE
Outdated example: publishing IPNS records from the browser

### ISSUE THREAD

**Issue by ashutosh1206** [ipfs/js-ipfs#3744]
- **Version**:
`ipfs.version()`:
```json
{ 
    "version":"0.8.0",
    "repo":"10",
    "commit":"81f944163f5a78ef15fdc23b2c488ba7f44af0be",
    "interface-ipfs-core":"^0.147.0"
}
```
go-ipfs version: `0.8.0`

- **Platform**:
`Linux 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 GNU/Linux`
`Google Chrome Version 91.0.4472.114 `

- **Subsystem**: libp2p

#### Severity: 
- Low

#### Description and Steps To Reproduce: 
There are two issues in [Browser IPNS publish](https://github.com/ipfs/js-ipfs/tree/master/examples/browser-ipns-publish) example. I installed and ran the demo web app. There are multiple steps in the app to illustrate publishing IPNS records from the browser. 

In the first step, it asks for API multiaddress of the go-ipfs node to connect to, but throws this error on giving an input (eg. `/ip4/127.0.0.1/tcp/5001`): `ipfsHttpClient is not a function` 
```js
const IpfsHttpClient = require("ipfs-http-client");
ipfsAPI = IpfsHttpClient(url);
```
This can be fixed simply with:
```js
const { create } = require("ipfs-http-client");
ipfsAPI = create(url);
```

In the next step (connecting to go-ipfs node via websocket), inputting a websocket address (as far as I have checked anything of the form `/ip4/<ipv4 address>/tcp/4003/ws/p2p/<PeerIDHash>`), it throws another error: `The dial request has no valid addresses`. This error occurs at [L65 of index.js](https://github.com/ipfs/js-ipfs/blob/master/examples/browser-ipns-publish/index.js#L65), when it tries to connect to the go-ipfs node:
```js
    await ipfsBrowser.swarm.connect(addr);
```
If it helps, I could trace this error message to [libp2p dialer](https://github.com/libp2p/js-libp2p/blob/master/src/dialer/index.js#L124) from console log. 
**Note**: I have tested this by running a go-ipfs node locally, as well as running it on an AWS instance. 

The first is a very minor bug in the example. But with the second step, I am unable to clearly understand what exactly is the problem. In any case, the example seems outdated.

**Comment by lidel** [comment]
I suspect mentioned example got fixed when it was moved to https://github.com/ipfs-examples/js-ipfs-examples/tree/master/examples/browser-ipns-publish
Feel free to open a new issue in https://github.com/ipfs-examples/js-ipfs-examples/ if something new comes up.
