### ISSUE TITLE
Can't find the repo ？

### ISSUE THREAD

**Issue by ZhangPeibin** [ipfs/js-ipfs#3758]
I use ipfs-repo to modify the storage directory, 
but after I Create JS-IPFS, I didn’t find the storage directory on my computer.
code like below:
const ipfs = IPFS.create({ repo :"/var/ipfs/js "})

**Comment by achingbrain** [comment]
Looks like you've got a space in the repo string?

```js
const ipfs = IPFS.create({ repo :"/var/ipfs/js "})
                                              ^ - remove this space
```

should be:

```js
const ipfs = IPFS.create({ repo : "/var/ipfs/js" })
```

Please can you use https://discuss.ipfs.io to ask help questions like this in future.

**Comment by ZhangPeibin** [comment]
3ks。
