### ISSUE TITLE
Multiformats import error in typescript

### ISSUE THREAD

**Issue by NaikAayush** [ipfs/js-ipfs#3776]
- **Version**:

- **Platform**:
Linux fedora 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
ipfs-core-types

#### Severity:
Critical - System crash, application panic.

#### Description:
- Used ipfs-http-client in Angular
- Typechecking while compiling throws an error
- There is a spelling error in the ipfs-core-types files, where "multiformats" is spelt as "multiformts"

#### Steps to reproduce the error:

![image](https://user-images.githubusercontent.com/57558584/127545197-d23d2fbb-d9a6-470f-9934-5f9801e94588.png)

**Comment by rvagg** [comment]
https://github.com/ipfs/js-ipfs/pull/3778
