### ISSUE TITLE
Webpack imports

### ISSUE THREAD

**Issue by amilich** [ipfs/js-ipfs#3783]
- **Version**: 51.0.1

- **Platform**:

- **Subsystem**:

#### Description:

I'm trying to import `ipfs-http-client` from a React project that uses webpack and seeing:
```
➤ YN0000: ERROR in ../node_modules/multiaddr/src/ip.js 4:27-59
➤ YN0000: ℹ ｢wdm｣: Failed to compile.
➤ YN0000: Module not found: Error: Package path ./to-string is not exported from package .../node_modules/uint8arrays (see exports field in .../node_modules/uint8arrays/package.json)
➤ YN0000:  @ ../node_modules/multiaddr/src/convert.js 3:11-26
➤ YN0000:  @ ../node_modules/multiaddr/src/codec.js 3:16-36
➤ YN0000:  @ ../node_modules/multiaddr/src/index.js 3:14-32
➤ YN0000:  @ ../node_modules/ipfs-http-client/src/index.js 5:22-42
```

Any ideas on webpack config? I saw this issue https://github.com/ipfs-inactive/js-ipfs-http-client/issues/968 but unclear if relevant.

**Comment by amilich** [comment]
This seems like a possible incompatibility between versions of multiaddr and uint8arrays: Adding the following exports to uint8arrays `package.json` works:
```
    "./from-string": {
      "browser": "./esm/src/from-string.js",
      "require": "./cjs/src/from-string.js",
      "import": "./esm/src/from-string.js"
    },
    "./toString": {
      "browser": "./esm/src/to-string.js",
      "require": "./cjs/src/to-string.js",
      "import": "./esm/src/to-string.js"
    },
    "./to-string": {
      "browser": "./esm/src/to-string.js",
      "require": "./cjs/src/to-string.js",
      "import": "./esm/src/to-string.js"
    },
```
seems possible different resolutions may be needed?

**Comment by achingbrain** [comment]
There was an experimental `uint8arrays@2.1.9` release that ported the module to esm with cjs fallback - it got published without a pre-release identifier.

I've just republished `2.1.8` as `2.1.10` so this should be resolved, please delete your `node_modules` folder and reinstall deps.

**Comment by achingbrain** [comment]
Closing as this should be fixed. Please reopen if you are still having problems.
