### ISSUE TITLE
Is it possible to use browse indexeddb as a file repository for ipfs?

### ISSUE THREAD

**Issue by aihuawu** [ipfs/js-ipfs#3802]
Is it possible to use browse indexeddb as a file repository for ipfs?

Since in browse, we can't access the system filesystem, if we can use the browse local storage,
it will be very useful.

George Wu

**Comment by achingbrain** [comment]
In the browser IPFS uses [datastore-level](https://www.npmjs.com/package/datastore-level) as the default backend, which uses indexeddb as a backing store.

Please use [discuss.ipfs.io](https://discuss.ipfs.io) for this sort of question in future, this issue tracker is for reporting bugs in IPFS.
