### ISSUE TITLE
'datastore key does not have a valid format' error in ipfs-core

### ISSUE THREAD

**Issue by Aragar199** [ipfs/js-ipfs#3833]
Same issue as here:

https://github.com/ipfs/js-ipfs/issues/1615

Version: 0.10.0
Platform: ipfs-core in Chrome
Subsystem: ipns

Type: Bug
Severity: Low

I was testing a clean install into a new directory while the original was still running and saw this error. Took me a few cycles to figure out what was going on since it was not clear to me from the error message.

Fix referenced above should just be applied to https://github.com/ipfs/js-ipfs/blob/4afd24a84ec3bbcd6ce557af5309a5513496ed68/packages/ipfs-core/src/ipns/publisher.js#L95 or error message changed to be more informative.

Steps to reproduce:
```
git clone https://github.com/austintgriffith/eth.build
npm install
npm start
open localhost:3000 in Chrome
in 'Network' subdirectory, create an ipfs module and wait for it to connect by changing color
mkdir && cd to different directory
git clone https://github.com/austintgriffith/eth.build
npm install
npm start
will prompt to open a different port like 3001
open localhost:3001 in different Chrome window
in 'Network' subdirectory, create an ipfs module and wait for it to connect by changing color
```

**Comment by achingbrain** [comment]
The problem in #1615 was that there were two copies of `interface-datastore` in the dep tree so `key instanceof Key` fails when `key` is instantiated from one copy and `Key` is required from another.

You are running two isolated IPFS processes in the browser with (in theory) only one copy of `interface-datastore` each.

Could you please confirm that you only have one copy of `interface-datastore` in the dependency tree?

I've followed your instructions but am not seeing the error - could you share a stack trace please?

**Comment by Aragar199** [comment]
Huh. Sorry for not including the stack trace, that's how I determined it was coming from publisher.js.

I restarted my comp and am not seeing the error anymore. Guessing my instructions are missing a step or it's just something on my local but I'm also not able to reproduce.

Thank you for taking the time to look in to this, I love submitting phantom issues in a public forum /s

This can be closed.
