### ISSUE TITLE
[ipfs-http-client@52.0.2] Typescript compilation fails when package is imported

### ISSUE THREAD

**Issue by rryter** [ipfs/js-ipfs#3839]
- **Version**:
`"ipfs-http-client": "52.0.2",`

- **Platform**:
Ubuntu 20.04

- **Subsystem**:
Typescript 4.3.5

#### Severity:
Critical - Comilation fails as soon as the package is imported.

#### Description:

```bash
node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:10:20
error TS2307: Cannot find module 'ipfs-unixfs/dist/src/types' or its corresponding type declarations.

10     mtime?: import("ipfs-unixfs/dist/src/types").MtimeLike | undefined;
```

So I checked the package in the `node_modules`, and there is indeed no `dist` folder.

#### Steps to reproduce the error:
```bash
npx typescript-starter
npm i ipfs-http-client
```

1. Create a new file 
2. Import the Options Type

```typescript
import { Options } from 'ipfs-http-client';
export interface InterfaceName {
  options: Options;
}
```
 
3. Try to compile.

### Workaround
Add `postinstall` to the scripts in your npm package:

```json
"postinstall": "npm run generate-types && cd node_modules/ipfs-unixfs && npm i --production"
```

**Comment by slwhitman** [comment]
I could not get workaround to work. Core error still exists. The import path is incorrect.

Currently: `import("ipfs-unixfs/types/src/types")`

Should be: `import("ipfs-unixfs/src/types")`
