### ISSUE TITLE
Broken link in "Look into the examples to learn" in README.md

### ISSUE THREAD

**Issue by gheja** [ipfs/js-ipfs#3848]
- **Version**:
docs

- **Platform**:
docs

- **Subsystem**:
docs

#### Severity:
Medium

#### Description:
The second link in "Next steps" section of readme is broken.

#### Steps to reproduce the error:
Click on the link:
https://github.com/ipfs/js-ipfs/tree/master/examples

Maybe this is the correct one?
https://github.com/ipfs-examples/js-ipfs-examples/tree/master

**Comment by rajan-31** [comment]
I guess this was fixed in #3821
