### ISSUE TITLE
ipfs.dag.get error

### ISSUE THREAD

**Issue by longren610** [ipfs/js-ipfs#3854]
Regarding the BUG in ipfs.dag.get, the sample code in the ipfs.dag.get part of https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DAG.md cannot be run normally.

The following code can run normally and get the hash value: bafyreicyer3d34cutdzlsbe2nqu5ye62mesuhwkcnl2ypdwpccrsecfmjq
```
const { create } = require('ipfs-http-client')
const CID = require('cids');

const ipfs = create({ host: '127.0.0.1', port: '5001', protocol: 'http' })

var cid = async function(obj) {
    return await ipfs.dag.put(obj, { format: 'dag-cbor', hashAlg: 'sha2-256' });
}

const obj = {
  a: 1,
  b: [1, 2, 3],
  c: {
    ca: [5, 6, 7],
    cb: 'foo'
  }
}

cid(obj).then((ret) => {
  console.log(ret.toString())
});
```
![image](https://user-images.githubusercontent.com/26690413/132319474-e931eec9-e179-47dc-800a-5138006bdb63.png)

Then use the hash value obtained and use the code in the example to get the data, and an error will be reported: No codec found for "undefined".code show as below:
```
const { create } = require('ipfs-http-client')
const CID = require('cids');

const ipfs = create({ host: '127.0.0.1', port: '5001', protocol: 'http' })

async function getAndLog(cid, path) {
  const result = await ipfs.dag.get(cid, { path:path })
}

getAndLog('bafyreicyer3d34cutdzlsbe2nqu5ye62mesuhwkcnl2ypdwpccrsecfmjq', '/a').then((ret) => {
  console.log(ret)
});
```
![image](https://user-images.githubusercontent.com/26690413/132319572-f4209d73-6dc1-4652-96c0-ff661ce84aaf.png)

I tried several times and found that it was a cid problem. After modifying the code, I tried to run again, no more errors were reported, but the output value is always: undefined.code show as below:
```
const { create } = require('ipfs-http-client')
const CID = require('cids');

const ipfs = create({ host: '127.0.0.1', port: '5001', protocol: 'http' })

async function getAndLog(cid, path) {
  const result = await ipfs.dag.get(new CID(cid), { path:path })
}

getAndLog('bafyreicyer3d34cutdzlsbe2nqu5ye62mesuhwkcnl2ypdwpccrsecfmjq', 'a').then((ret) => {
  console.log(ret)
});
```
![image](https://user-images.githubusercontent.com/26690413/132319718-23a93269-7903-4eac-a177-1b6415490a4c.png)

Use the cli command directly to obtain the data, and the data can be obtained normally.
![image](https://user-images.githubusercontent.com/26690413/132320244-520b76e8-c92c-4239-8efa-1713b877ba5d.png)

Why is this so?

**Comment by achingbrain** [comment]
The `cids` module is deprecated, please use the `CID` class exported by the `multiformats` module:

```js
const { create } = require('ipfs-http-client')
const { CID } = require('multiformats/cid');

const ipfs = create({ host: '127.0.0.1', port: '5001', protocol: 'http' })

async function getAndLog(cid, path) {
  const result = await ipfs.dag.get(CID.parse(cid), { path })
}

getAndLog('bafyreicyer3d34cutdzlsbe2nqu5ye62mesuhwkcnl2ypdwpccrsecfmjq', 'a').then((ret) => {
  console.log(ret)
});
```

**Comment by longren610** [comment]
> The `cids` module is deprecated, please use the `CID` class exported by the `multiformats` module:
> 
> ```js
> const { create } = require('ipfs-http-client')
> const { CID } = require('multiformats/cid');
> 
> const ipfs = create({ host: '127.0.0.1', port: '5001', protocol: 'http' })
> 
> async function getAndLog(cid, path) {
>   const result = await ipfs.dag.get(CID.parse(cid), { path })
> }
> 
> getAndLog('bafyreicyer3d34cutdzlsbe2nqu5ye62mesuhwkcnl2ypdwpccrsecfmjq', 'a').then((ret) => {
>   console.log(ret)
> });
> ```

Thanks for the answer, the reason is found, there is no return value in the getAndLog function, so "undefined" is always printed. Sorry to bother you.

**Comment by longren610** [comment]
The reason is found, there is no return value in the getAndLog function, so "undefined" is always printed.
