### ISSUE TITLE
error: datastore key does not have a valid format

### ISSUE THREAD

**Issue by oliveriosousa** [ipfs/js-ipfs#3865]
- **Version**: 
0.58.4

- **Subsystem**:
ipfs
js-ipfs-interfaces

#### Severity:
High

#### Description:
- Error when trying to create an IPFS node:

`datastore key does not have a valid format`

#### Steps to reproduce the error:
- Run IPFS.create();

Maybe it is related with js-ipfs-interfaces bump version (currently is in version 6) and IPFS is targeting the 5 version.

cc @hugomrdias @achingbrain

**Comment by achingbrain** [comment]
Please use v5 until https://github.com/ipfs/js-ipfs/pull/3864 is shipped

**Comment by ggcaponetto** [comment]
having the same issue. what does use v5 mean?

**Comment by achingbrain** [comment]
@ggcaponetto interface-datastore@v6 needs a coordinated release with libp2p as it's currently depending on v5.

You shouldn't be pulling it in though - can you provide a way of reproducing the error you are seeing?

**Comment by ggcaponetto** [comment]
@achingbrain while trying to set up the minimal setup to reproduce the example i found out that deleting the package-lock.json and performing a fresh `npm i` it solved the problem. I guess i had separate installations of the ipfs modules.

the only dependency i have now is `"ipfs": "^0.58.4"` and this problem didn't occur anymore. Thanks!
