### ISSUE TITLE
Type Error: using add() and urlSource()

### ISSUE THREAD

**Issue by Faolain** [ipfs/js-ipfs#3867]
**Version**:
"ipfs-http-client": "^52.0.3"

#### Severity:
 Low - An optional functionality does not work.

#### Description:
```
import { create, urlSource } from "ipfs-http-client";
const { path, cid } = await ipfsClient.add(urlSource(fileURL));
```

returns a typescript error:

```
Argument of type '{ path: string; content?: AsyncIterable<Uint8Array>; }' is not assignable to parameter of type 'ImportCandidate'.
  Type '{ path: string; content?: AsyncIterable<Uint8Array>; }' is not assignable to type 'ToDirectory'.
    Types of property 'content' are incompatible.
      Type 'AsyncIterable<Uint8Array>' is not assignable to type 'undefined'.ts(2345)
```

**Comment by BigLep** [comment]
We added this to the maintenance queue, but we also are surprised by this given we have types on this.

**Comment by achingbrain** [comment]
@Faolain I'm having problems replicating this, could you please provide a fuller example?  A link to a github repo that demonstrates the problem would be perfect.

**Comment by achingbrain** [comment]
Closing due to lack of response.  @Faolain please reopen if you can provide a repro case.

**Comment by jdbertron** [comment]
import type ImportCandidate from 'ipfs-core-types';    Is that the way to import the type ?  It's not working for me.
