### ISSUE TITLE
OperationError: The operation failed for an operation-specific reason on IPFS.create() (iOS 14.7.1)

### ISSUE THREAD

**Issue by joe-p** [ipfs/js-ipfs#3878]
- **Version**: 0.10.8

- **Platform**: iPhone 11 running iOS 14.7.1

- **Subsystem**: libp2p-crypto (I think...)

Seems to be a problem stemming from `SubtleCrypto` since the exception is from `SubtleCrypto.decrypt()` or `SubtleCrypto.encrypt()`, so I assume it's somewhere in `libp2p-crypto`

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/decrypt#exceptions
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt#exceptions

#### Description:

When trying to use `ipfs-core` on iOS 14.7.1, `IPFS.create()` fails to run with the following exception shown in the console: 

```
[Error] Unhandled Promise Rejection: OperationError: The operation failed for an operation-specific reason
	(anonymous function) (main.chunk.js:55:82)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

The console log shows the error is from App.js:8 but that isn't reflect when copy/pasting for some reason:

![Screen Shot 2021-09-18 at 6 06 43 PM](https://user-images.githubusercontent.com/50534337/133909744-96f1d169-6a06-4020-b69b-69367ecc283e.png)

#### Steps to reproduce the error:

1. `npx create-react-app ipfs-test && cd ipfs-test`
2. `npm i ipfs-core`
3. Modified contents of App.js
```
import { useEffect } from "react";
import IPFS from 'ipfs-core';

function App() {

  useEffect(() => {
    (async () => {    
      const ipfs = await IPFS.create()
      const { cid } = await ipfs.add('Hello world')
      const { version } = await ipfs.version()
      console.info(cid)
      document.getElementById('cid').innerText = version + ' ' + cid
    })();
  })

  return (
    <div className="App">
      <div id="cid">Waiting for IPFS...</div>
    </div>
  );
}

export default App;
```
4. `npm start`
5. Verify page works on desktop (I'm using Firefox on Mac OS and it works)
6. Attempt to visit page on iOS
7. Look at console log to see the aforementioned exception

[package-lock.json](https://gist.github.com/joe-p/62484882eb9fc1d947b666a7e43fcd59)
[package.json](https://gist.github.com/joe-p/4db1094020bb20b0ac4b1c9e8d5caba3)

Note: I am running this on the `node:14` docker image behind traefik so I am accessing the site via HTTPS

**Comment by joe-p** [comment]
I just updated to iOS 15. which includes a significant update to Safari, and IPFS works as expected with the exact same source code. This bug seems to be specific to iOS/Safari 14.7.1. More testing would be needed to determine if it affects all older iOS versions or just 14.7.1.

**Comment by BigLep** [comment]
Thanks for reporting.  Given new iOS addresses this issue, maintainers aren't going to dig into this issue for 14.7.

**Comment by sebastiendan** [comment]
Hi! I just noticed the same problem on iOS 14.[6|8]. Is there any one working on a solution? It does work on iOS 15, but according to figures from last month ([here](https://www.macrumors.com/2021/12/09/ios-15-adoption-80-days-after-launch/)), only ~60% of iPhone users have upgraded to iOS 15, with still 36% of them on iOS 14.

It seems difficult to me to consider that a critical bug like this one shouldn't be fixed for such a large user base considering the notoriety IPFS has gained over the years.

**Comment by matheus23** [comment]
We're starting to hit these issues at fission as well. Has someone made progress on figuring out where this issue is coming from yet?

In case we can figure out a fix for this, would you be open to merging a fix for this @BigLep?

**Comment by icidasset** [comment]
Workaround, change the crypto algorithm for the peer id keypair:
```ts
IPFS.create({
  init: { algorithm: isSafari ? "RSA" : "Ed25519" }
})
```
