### ISSUE TITLE
Review cli modules to make the cli a nicer experience

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#389]
There are a lot of tools on this list https://github.com/sindresorhus/awesome-nodejs#command-line-utilities that can make the js-ipfs cli a much nicer experience.

**Comment by RichardLitt** [comment]
👍  Good idea.

**Comment by diasdavid** [comment]
This is an excellent idea, thanks for pointing this out, added to my bookmarks.

This is not a issue of js-ipfs in general though, whoever wants to improve the CLI with that can check that list.

**Comment by dignifiedquire** [comment]
Also part of the last cli refactor was adding some of these into js-ipfs. Yargs and the update checker are now being used.
