### ISSUE TITLE
unable to run ipfs-http-client tests

### ISSUE THREAD

**Issue by tabcat** [ipfs/js-ipfs#3904]
- **Version**: https://github.com/ipfs/js-ipfs/tree/04e3cf3f46b585c4644cba70516f375e95361f52

- **Platform**: Ubuntu x64; Node 14

- **Subsystem**: ipfs-http-client

#### Description:
I cloned js-ipfs, navigated to ipfs-http-client and installed the package to run tests. On `npm run test` I get
```
$ npm run test

> ipfs-http-client@53.0.1 test
> aegir test

Test Node.js
Package subpath './files/normalise-input-single' is not defined by "exports" in /home/anders/Documents/dev/github/js-ipfs/packages/ipfs-http-client/node_modules/ipfs-core-utils/package.json imported from /home/anders/Documents/dev/github/js-ipfs/packages/ipfs-http-client/src/add.js

```

#### Steps to reproduce the error:
navigate to the ipfs-http-client package, install it, run its tests

you might know about this and its just a temporary issue while ipfs-core-utils is updated. i wanted to run the ipfs-http-client tests with the go-ipfs rc but was unable to.

**Comment by achingbrain** [comment]
You should run `npm install` from the root of the repo, not from individual packages as you'll get the wrong versions which lead to errors like this.

See the development docs - https://github.com/ipfs/js-ipfs/blob/master/docs/DEVELOPMENT.md
