### ISSUE TITLE
`ipfs.block` API is out of sync with the implementation

### ISSUE THREAD

**Issue by matheus23** [ipfs/js-ipfs#3913]
Here is what I've noticed:
* `ipfs.block.get`
  * docs say it returns a `Block`, but it returns a `Uint8Array`
  * docs are missing the `preload` option
* `ipfs.block.put`
  * docs say it can also take a `Block` as a parameter, but it can only be a `Uint8Array`
  * docs say it can take a `cid` as an option, but the implementation ignores such a parameter
  * docs say it returns a `Block`, but it's just a `Uint8Array`

**Comment by vogdb** [comment]
The return of `ipfs.block.get` has been fixed in #3990. @lidel I can help to fix the rest, if you want.
