### ISSUE TITLE
http-client dag.put failed with invalid byte

### ISSUE THREAD

**Issue by jtsmedley** [ipfs/js-ipfs#3914]
- **Version**: ipfs-http-client 53.0.1, go-ipfs v0.10.0

- **Platform**: Windows

- **Subsystem**:

**Comment by rvagg** [comment]
@achingbrain the DAG API is now out of sync between go-ipfs and js-ipfs-http-client and errors like this are going to start popping up. This particular error is going to be about the codec defaults, and what's more, the arguments have changed. `format` and `input-enc` are now replaced with `store-codec` and `input-codec` and both the defaults and behaviour are different, in subtle (but arguably much more clear, now) ways.

The default `input-enc` here is `raw` and `format` is `dag-cbor` and there's pre-processing done here before it's sent off to the server. So I think what's happening for this error is the JS object `{hello: "world"}` is encoded with dag-cbor and sent as bytes to the server. But the default `input-codec` is `dag-json` on the server and its receiving cbor bytes, so it's getting `0x5a` when it really wants a valid JSON value character.

Defaults and options need to be updated here to match 0.10. I just don't know how you deal with the version mismatch if someone's using 0.9, but maybe you just don't?

https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md#v0100-2021-09-30
