### ISSUE TITLE
IPFS-Core causes process to hang instead of exiting, even after calling stop()

### ISSUE THREAD

**Issue by kebian** [ipfs/js-ipfs#3923]
- **Version**: 0.11.1
- **Platform**: MacOS 10.15.7 running Node v16.7.0
- **Subsystem**: Unknown
#### Description:

IPFS-Core causes process to hang instead of exiting, even after calling `stop()`

#### Steps to reproduce the error:

Each individual test below will succeed, however the test process will not exit after the last test.  The same behaviour happens in live code.

```ts
import chai, { expect } from 'chai'
import chaiAsPromised from 'chai-as-promised'
import * as IPFSCore from 'ipfs-core'

chai.use(chaiAsPromised)

const expectedVersion = '0.11.1'

describe('IPFS', function() {
    let node: IPFSCore.IPFS

    it('node created', async function() {
        node = await IPFSCore.create({ silent: true })
        expect(node).to.be.an('object')
    })

    it(`version is ${expectedVersion}`, async function() {
        const version = (await node.version()).version
        expect(version).to.equal(expectedVersion)
    })

    it('node is online', function() {
        expect(node.isOnline()).to.be.true
    })

    it('node was stopped', function() {
        this.timeout(5000)
        return expect(node.stop()).to.eventually.be.fulfilled
    })

    it('node is offline', function() {
        expect(node.isOnline()).to.be.false
    })
})
```
Example output
```
  IPFS
    ✔ node created (552ms)
    ✔ version is 0.11.1
    ✔ node is online
    ✔ node was stopped
    ✔ node is offline


  5 passing (635ms)
```
This is usually indicative of an async function continuing to run somewhere.  Possible related issues #3800, #3191

**Comment by jtwigg** [comment]
I've found the same thing as others. 

I'm linking a gist here of dump of the the node state using `why-is-node-running` 

https://gist.github.com/jtwigg/6eb8a39d0e4b6aacadd8f136f1fe9e2b

**Comment by achingbrain** [comment]
It looks like libp2p is dialling peers when the node starts up (probably the bootstrap nodes) and those dials are not being torn down when the node is stopped, probably because it's being started and stopped so quickly.

If you're using ipfs in tests like this, I'd suggest using [ipfsd-ctl](https://www.npmjs.com/package/ipfsd-ctl) and the ['test' profile](https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md#profiles) as it will not have bootstrap nodes or peer discovery etc which will make your tests faster and more reliable/predictable as there is less chance some external network connection will cause problems like this.

**Comment by matheus23** [comment]
> If you're using ipfs in tests like this, I'd suggest using ipfsd-ctl and the 'test' profile as it will not have bootstrap nodes or peer discovery etc which will make your tests faster and more reliable/predictable as there is less chance some external network connection will cause problems like this.

It looks like the test profiles you linked are supposed to be applied via the CLI (the `--profile` flag).
Is there a way to do the same from javascript? Or can you perhaps point me to where these profiles are defined, I've tried to find them before with no luck.

**Comment by achingbrain** [comment]
You can specify them as init args for fresh repos:

```js
import { create } from 'ipfs-core'

const node = await create({
  init: {
    profiles: ['test']
  }
})
```

See [the docs](https://github.com/ipfs/js-ipfs/blob/master/docs/MODULE.md#optionsinit).

Alternatively via ipfsd-ctl:

```js
import ipfs from 'ipfs'
import ipfsHttpClient from 'ipfs-http-client'
import { createFactory } from 'ipfsd-ctl'

const factory = createFactory({
  type: 'js',
  test: true,
  disposable: true,
  ipfsHttpModule: ipfsHttpClient,
  ipfsModule: ipfs
})

const node = await factory.spawn()
```

Alternatively if you have pre-existing nodes that you want to convert to the test profile you can either [apply the profile](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/CONFIG.md#ipfsconfigprofilesapplyname-options) while the node is offline:

```js
const node = await create({
  start: false
})
await node.config.profiles.apply('test')
await node.start()
```

or make the same config changes manually - see the [definition of the test profile](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/config/profiles.js#L42-L61) for what needs to change.

**Comment by lidel** [comment]
The init bug remains and needs analysis:
>  This is a bug, but it's probably a bug with libp2p-tcp and/or libp2p-websockets (the transports you seem to be using).
