### ISSUE TITLE
base64 image upload

### ISSUE THREAD

**Issue by ekumahost** [ipfs/js-ipfs#3924]
I am trying to add image via base64, but the script return nothing./

`const file = await ipfs.add(multibase(base64_string));`
what is the best way to do this?
the line of code bellow works well for local image file
`const file = await ipfs.add(globSource(reqObject.file.path));`

**Comment by achingbrain** [comment]
I'm not sure what the `multibase` function in the code above does, but if it's supposed to decode `base64_string` and it doesn't have the multibase prefix it won't work.

You can decode a base64 encoded string and add it to your IPFS node with:

```js
import { fromString } from 'uint8arrays/from-string'

const data = fromString(base64_string, 'base64')
const { cid } = await ipfs.add(data)

console.info(cid)
```

Please ask questions like this on https://discuss.ipfs.io in future - you'll receive responses faster and it's got much better visibility for other users who may have the same problem as you.  This issue tracker is for reporting problems with the core implementation.

**Comment by ekumahost** [comment]
Alex, thanks for clarifying that. Possible I can default to just storing
the string
