### ISSUE TITLE
NPM Readme

### ISSUE THREAD

**Issue by codewithpom** [ipfs/js-ipfs#3928]
The README on npm website for ipfs has some broken links like the example link and I would like to know how you deploy it so that I can help you in fixing it .

**Comment by achingbrain** [comment]
Thanks for offering to help out, it's much appreciated!

The READMEs for each module are in the `packages` folder - e.g. the readme for https://www.npmjs.com/package/ipfs-core is at https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/README.md, the readme for https://www.npmjs.com/package/ipfs-http-client is at https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/README.md and so on - they are deployed when each module is published.

**Comment by codewithpom** [comment]
Ok Thanks

**Comment by codewithpom** [comment]
@achingbrain See #3931

**Comment by achingbrain** [comment]
Fixed by #3931
