### ISSUE TITLE
How can I add image file

### ISSUE THREAD

**Issue by CryptoDogg** [ipfs/js-ipfs#3930]
How can I add a local image file?

I tried the following code and got a cid log, but `ipfs://{cid}` gave me nothing.

```Javascript
import * as IPFS from 'ipfs-core'

const ipfs = await IPFS.create()
const { cid } = await ipfs.add('./sample.png')
console.info(cid)
```

**Comment by achingbrain** [comment]
If you're having problems retrieving content from another node, please use https://ipfs-check.on.fleek.co/ to diagnose your problem.

In future please ask 'how do I' questions on https://discuss.ipfs.io - this issue tracker is for reporting bugs in the implementation.
