### ISSUE TITLE
TypeScript syntax incorrectly used in JavaScript file

### ISSUE THREAD

**Issue by dancingfrog** [ipfs/js-ipfs#3935]
- **Version**:
0.11.1

- **Platform**:
Linux localhost.localdomain 5.8.15-301.fc33.x86_64 (Fedora 33)

- **Subsystem**:

#### Severity:
Medium

#### Description:
Initially I read this as a typo on line 75 of `packages/ipfs-http-gateway/src/index.js` :
https://github.com/ipfs/js-ipfs/blob/5ddd0c555cc6577ee15667f4ef4e7f3a3b17d04c/packages/ipfs-http-gateway/src/index.js#L75
,.. and tried to correct this with pull request https://github.com/ipfs/js-ipfs/pull/3918
Through discussion on that request, it now appears that the author attempted to use valid TypeScript syntax within a JavaScript file. This is not valid JavaScript syntax and this code will throw an error in certain contexts. 

#### Steps to reproduce the error:
The simplest way to reproduce this error is to install ipfs in a project using npm and then run:
```
$ node node_modules/.bin/jsipfs
(node:28639) ExperimentalWarning: The ESM module loader is experimental.
file:///home/revlin/Public/node_modules/ipfs-http-gateway/esm/src/index.js:44
    const gatewayAddrs = addresses?.Gateway || [];
                                   ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:117:18)
```

**Comment by dancingfrog** [comment]
The pull request reviewer also [mentioned](https://github.com/ipfs/js-ipfs/pull/3918#issuecomment-954849815) that this same TypeScript syntax is used in other JS files in this project. So, this pattern seems have become e a convention within this project, but all of these files would contains errors if evaluated as JavaScript.

https://github.com/ipfs/js-ipfs/pull/3918#issuecomment-954849815

**Comment by achingbrain** [comment]
That operator is called the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).  It's not Typescript (see the MDN link), but is only supported by node 14+.  Are you using an older version?

**Comment by dancingfrog** [comment]
Thanks @achingbrain . As you can see in the reviewer's comment linked above, Optional Chaining was explained by way of a [link to the TypeScript Language](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) page, implying that the syntax of that file (and others) was intended to be TypeScript. 

Yes, I'm using Node ~12 because that had the widest adoption on different cloud compute platforms up until recently ([AWS Lambda did not adopt Node 14+ until this year)](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/).

I will consider upgrading in order to make use of `js-ipfs` without major revisions to the source. Thanks!
