### ISSUE TITLE
formData.set is not a function on the  ipfs-http-client lib

### ISSUE THREAD

**Issue by BankNatthapon** [ipfs/js-ipfs#3937]
- **Version**: `54.0.0` from `yarn add ipfs-http-client`

- **Platform**: 
- `M1 Big Sur` with `11.6` version
- `ReactJS` with `17.0.2` version
- `Chrome (Official Build) (arm64)` with `95.0.4638.69` version 

#### Description:
- What you did: I just want to learn how the client upload the image into the `ipfs` and I used the `ReactJS` framework with `ipfs-http-client` library 
- What happened: An error has occurred when I am using the `ipfs.add()` function with `formData.set is not a function` in the `multipart-request.browser.js` file 
- What you expected to happen: I just wonder why this error has occurred? and I struggle with this error for a while and try to change `formData.set` to `formData.append` function, it works! Hence, can you look into this error for inspecting the root cause and providing detail about it?

#### Steps to reproduce the error:
This is an error on the google chrome console:

![alt text](https://ipfs.infura.io/ipfs/QmQtexC99nQZBNQZkB1xMsLy51p3KheMKRmRzY8p1tdgUy)

This is the code in `ipfs-http-client lib` at `multipart-request.browser.js` file that made this error

![alt text](https://ipfs.infura.io/ipfs/QmSYsgs2zt2uQ3Z1UeVuEUmQmrwsg4xBbxZAejvVJ8haBv)

This is my implementation code and it's working now after I changed `formData.set` to `formData.append`

![alt text](https://ipfs.infura.io/ipfs/Qmf1YH53FtGhGjEcrpBvzQueXd3SY3jiT72qRuiSTttVpr)

Thanks in advance!

**Comment by lidel** [comment]
@BankNatthapon  what bundler setup are you using for building your app?
Both `set` and `append` are  in the same spec and supported since Chrome 50: https://developer.mozilla.org/en-US/docs/Web/API/FormData#browser_compatibility

Perhaps you have some custom browser-compatibility setup as part of your build pipeline?

**Comment by lidel** [comment]
Assuming no longer an issue? Feel free to fill new one or ask on discuss forums.
