### ISSUE TITLE
Broken link to 'examples' in BROWSERS.md

### ISSUE THREAD

**Issue by fcbrandon** [ipfs/js-ipfs#3939]
The link in the final sentence on this page, https://github.com/ipfs/js-ipfs/blob/master/docs/BROWSERS.md, is broken.

`More advanced examples and tutorials can be found in the *examples*` - _examples_ currently points to https://github.com/ipfs/js-ipfs/blob/master/examples, which does not exist.

I can't propose a fix as I do not know where this file is or to where it's intended to link.

**Comment by achingbrain** [comment]
Thanks for taking a look - the examples were moved to the https://github.com/ipfs-examples org, the link should point there.
