### ISSUE TITLE
TypeError: isOnline returns the type 'Promise '  instead of type 'boolean'

### ISSUE THREAD

**Issue by jovijovi** [ipfs/js-ipfs#3953]
- **Version**:

ipfs@0.60.2

- **Platform**:

Linux 5.4.0-90-generic x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:

ipfs-core-types@0.8.4

#### Severity:

Medium

#### Description:

```javascript
isOnline: () => boolean;
```

The function `isOnline` defined in `packages/ipfs-core-types/src/root.ts` returns `boolean`. But if you call `isOnline`, you will get a `Promise` return instead of a `boolean`.

#### Steps to reproduce the error:

```javascript

import {create} from 'ipfs-http-client'; // version 54.0.2

const client = create();

function Ping(): boolean {
	const rsp = client.isOnline();  // rsp is type 'Promise'
	console.log(rsp);
	return rsp;
}

```

**Comment by SgtPooki** [comment]
@achingbrain I am still seeing the incorrect type in ipfs-core-types@0.10.2. Can we release this update?

**Comment by achingbrain** [comment]
`ipfs-core-types@0.10.3` is out - please try that

**Comment by BigLep** [comment]
Closing since the unblocking release went out over a month ago.

**Comment by luna-fire-dev** [comment]
This issue re-appears in the latest version (ipfs-core-types@npm:0.11.1)

https://github.com/ipfs/js-ipfs/blob/7a7e091c5d7110542ca7ab6eca1c0c9abb19e54b/packages/ipfs-core-types/src/root.ts#L139
