### ISSUE TITLE
Expose PubSub over WebSockets

### ISSUE THREAD

**Issue by Pandapip1** [ipfs/js-ipfs#3974]
See: https://github.com/ipfs/go-ipfs/issues/8602

**Comment by achingbrain** [comment]
js-ipfs has a gRPC API server that does exactly this.  Have you tried using [ipfs-client](https://www.npmjs.com/package/ipfs-client) with a js-ipfs daemon instead of [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client)?

**Comment by Pandapip1** [comment]
Since gRPC has more browser support than it did in 2021, I am closing this.
