### ISSUE TITLE
listen EADDRINUSE: address already in use 0.0.0.0:4002

### ISSUE THREAD

**Issue by pguardiario** [ipfs/js-ipfs#3975]
- **Version**:
0.60.2

- **Platform**:
Windows 10

#### Description:
script dies with listen EADDRINUSE: address already in use 0.0.0.0:4002
Even though there's nothing listening on 4002 and the go version works fine.

#### Steps to reproduce the error:
IPFS.create()

**Comment by gregarican** [comment]
I too ran into this same exact issue.

**Comment by gregarican** [comment]
I believe that running this on a computer might force it to join the peer node network. So if there isn't an inbound path to port 4002 open on the computer then the error is raised. Haven't taken the time to dig into the source code to confirm this, but just a hunch. I know the error says the port is in use, but I didn't see that really being the case.

**Comment by saricden** [comment]
Hmm, okay. I'll test it on a Heroku server to see if I get any different results, but I have a feeling it'll be much the same.

For me this error is only raised when making multiple IPFS calls, ie: user A uploads something, then user B uploads something.
If I restart it's fine, but I can't really do this in production (using Heroku) AFAIK.

My current "fix" is to kill the process with a SIGINT from my script, then hope that Heroku restarts it (which it seems to _some_ of the time...)

**Comment by saricden** [comment]
@gregarican I got an update on this...

I managed to solve it for my purposes by lifting my root IPFS node (made with a call to `create()`) out of the TWO Express API endpoints where I was defining it, then defining it as a global variable and only calling `create()` once.

That way `create()` is only called once during the lifetime of the process. This for me solved the problem.

**Comment by gregarican** [comment]
Nice! I will have to revisit my code that relied on this. Thanks for the follow-up!

**Comment by achingbrain** [comment]
This error occurs when something else is listening on the port already.  This could be something else in your application or something else on your computer.

If you can provide a repro case I can look into it, but chances are the error message is accurate and that there's something already listening on that port.

If it's another process on your computer you can find out the pid of that process by running `lsof -i :4002` - on MacOS or Linux, I'm not sure what the equivalent is in Windows.

If it's something else in your application as @saricden found, you'll have to debug it yourself.

**Comment by ov-wagle** [comment]
This happens for me when I am running two nodes with different repo name on the CLI. For the first node, IPFS,create() executes successfully, however for the second node, I am facing the above. Note that both the nodes are calling IPFS.create() with a different repo name.

**Comment by achingbrain** [comment]
@ov-wagle specifying separate repos isn't enough - you need to make sure each node is listening on it's own set of ports.

Please see https://github.com/ipfs-examples/js-ipfs-running-multiple-nodes for an example.
