### ISSUE TITLE
ipfs-core-types@0.9.0 - Out of date types for BWOptions

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-ipfs#3985]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ipfs-core-types@0.9.0` for the project I'm working on.

A number is no longer valid for the `interval` property of `BWOptions`. In order to successfully call the `ipfs.stats.bw` endpoint with TypeScript, you must either `//@ts-ignore` or avoid passing `interval`.

See https://docs.ipfs.io/reference/http/api/#api-v0-stats-bw
 
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ipfs-core-types/src/stats/index.ts b/node_modules/ipfs-core-types/src/stats/index.ts
index 43e5f24..30dbf86 100644
--- a/node_modules/ipfs-core-types/src/stats/index.ts
+++ b/node_modules/ipfs-core-types/src/stats/index.ts
@@ -16,7 +16,7 @@ export interface BWOptions extends AbortOptions {
   peer?: string
   proto?: string
   poll?: boolean
-  interval?: number
+  interval?: string
 }
 
 export interface BWResult {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by achingbrain** [comment]
I think it needs to be `number | string` to align with https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/stats/bw.js#L11 which allows you to pass intervals like `'1s'`.

If that works for you, would you like to open a PR that fixes the issue?

**Comment by BigLep** [comment]
@SgtPooki : are you ok to open a PR to fix the issue?

**Comment by SgtPooki** [comment]
@BigLep for sure. I can get a PR out really quick
