### ISSUE TITLE
where can i find the create function api doc in ipfs-core?

### ISSUE THREAD

**Issue by nrz123** [ipfs/js-ipfs#3988]
i can't find the create function api doc any where.

**Comment by amandesai01** [comment]
Yes. Documentation is missing.

Till then, you can find function itself [here](https://github.com/ipfs/js-ipfs/blob/e7f85318517718399ee4dc2e0f240550b900617e/packages/ipfs-core/src/components/index.js#L277).

It takes only one optional argument `options={}`

If you don't provide options, these options are considered [(source)](https://github.com/ipfs/js-ipfs/blob/e7f85318517718399ee4dc2e0f240550b900617e/packages/ipfs-core/src/components/index.js#L260). `You can override any of them by including in options object parameter of create function`:
```Javascript
{
  start: true,
  EXPERIMENTAL: {},
  preload: {
    enabled: !isTest, // preload by default, unless in test env
    addresses: [
      '/dns4/node0.preload.ipfs.io/https',
      '/dns4/node1.preload.ipfs.io/https',
      '/dns4/node2.preload.ipfs.io/https',
      '/dns4/node3.preload.ipfs.io/https'
    ]
  }
}
```

Then, it is passed to IPFS constructor _with some other configs included_. This is where actual instance is created.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

Helia has much better documentation (thanks to typescript with jsdoc comments), which should be a much better experience. Let us know if something is missing!
