### ISSUE TITLE
Track: Remove abort-controller polyfills from stack

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#4001]
`AbortController` and `AbortSignal` are global in browsers and LTS node so we don't need to use [abort-controller](https://www.npmjs.com/package/abort-controller) and/or [native-abort-controller](https://www.npmjs.com/package/native-abort-controller) any more.

- [ ] https://github.com/libp2p/js-libp2p/pull/1095
- [ ] https://github.com/jacobheun/any-signal/pull/15
- [ ] https://github.com/ipfs/js-ipfs-utils/pull/162
- [ ] https://github.com/jacobheun/timeout-abort-controller/pull/17
- [ ] https://github.com/libp2p/js-libp2p-kad-dht/pull/276
- [ ] https://github.com/ipfs/js-ipfs-bitswap/pull/402
- [ ] js-ipfs

**Comment by lidel** [comment]
:partying_face:
