### ISSUE TITLE
Support private networks via shared swarm.key 

### ISSUE THREAD

**Issue by revichnr** [ipfs/js-ipfs#4005]
Hi. I need to connect js-ipfs to a private network.
How can I use my swarm.key during installation?

**Comment by lidel** [comment]
I don't believe js-ipfs supports Private swarms  ([atm it is an experimental feature of go-ipfs](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks)).

If anyone wishes to add this to js-ipfs, PR welcome :pray:

**Comment by AlexMesser** [comment]
It seems that `libp2p` config parameter does not passed to an underlying `libp2p.js` module.

I tried to create a private IPFS network:

```ts
async connect(){
  process.env.LIBP2P_FORCE_PNET = "1" // enable private network
  const swarmKey = await fse.readFile(AppConfig.ipfs.swarmKeyFile)
  const ipfsConfig: any = {
    repo: `./ipfs`,
    EXPERIMENTAL: {
      pubsub: true,
    },
    config: {
      Bootstrap: [],
      Addresses: {
        Swarm: ["/ip4/0.0.0.0/tcp/4002", "/ip4/127.0.0.1/tcp/4003/ws"],
      },
    },
    libp2p: {
      modules: {
        connProtector: new Protector(swarmKey),
      },
    },
  }
  this.node = await IPFS.create(ipfsConfig)
}
```

It gives me an error `Error: Private network is enforced, but no protector was provided`

After digging into `ipfs-core` code i tried to add `options: options.libp2p` in [storage.js](https://github.com/ipfs/js-ipfs/blob/c51b1609f9ba825b14ad1efd0b99f6af6805c4e0/packages/ipfs-core/src/components/storage.js#L229) and `...oprions` in [libp2p.js](https://github.com/ipfs/js-ipfs/blob/c51b1609f9ba825b14ad1efd0b99f6af6805c4e0/packages/ipfs-core/src/components/libp2p.js#L100), under the `modules: {}`. Network successfully started.

**Comment by lidel** [comment]
@AlexMesser thank you for poking at this – please open a PR that works, we can bikeshed details  there, if necessary, but it will be really valuable to have support for private networks in js-ipfs :pray:

**Comment by piboistudios** [comment]
As a workaround, you can just provide a libp2p instance with the `connProtector` module configurations desired. The above snippet is only a problem because IPFS will create a libp2p instance if one is not provided (though, a PR should probably still be made so that IPFS actually creates a libp2p instance mirroring the provided config)

**Comment by tbmcabc** [comment]
hello，it looks like that example running at node.js？can I used at browser with swarm.key？ hope and waiting the answer please。 best wish！

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

@achingbrain to answer if private networks support is available in Helia

**Comment by achingbrain** [comment]
This can be accomplished using the `pnet` module bundled with js-libp2p - please see [the docs](https://libp2p.github.io/js-libp2p/modules/pnet.html) for how to configure this.
