### ISSUE TITLE
ipfs-core ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by xoayxoay** [ipfs/js-ipfs#4007]
import * as IPFS from 'ipfs-core';
const ipfs = await IPFS.create();

Return Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './base' is not defined by "exports" in /node_modules/blockstore-core/package.json
Can you help me, tks so much.

**Comment by deanpress** [comment]
Same issue on any fresh js-ipfs installation since yesterday.

**Comment by deanpress** [comment]
You can work around this by doing `npm install --save blockstore-core@1.0.2` in your project. Version 1.0.3 that released 2 days ago breaks every project that depends on it.

**Comment by xoayxoay** [comment]
tks you so much deanpress ♥️

**Comment by AllanOricil** [comment]
Same issue here

**Comment by AllanOricil** [comment]
@deanpress I installed blcokstore-core. But how can I get create an ipfs node with it?

**Comment by AllanOricil** [comment]
I installed blockstore-core@1.0.2 and have ipfs-core@0.13.0 but it did not work. 

![image](https://user-images.githubusercontent.com/55927613/148593549-6fad98c8-e279-4dc7-a823-ce171257c07c.png)

**Comment by AllanOricil** [comment]
For those using yarn, just add this to your package.json

````json
"resolution":{ "blockstore-core":"1.0.2"}
````

**Comment by xoayxoay** [comment]
@AllanOricil tks you <3

**Comment by redaphid** [comment]
I had to add  `it-all` and `libp2p` to my dependencies,  for whatever reason. Figured I'd chime in. My `package.json` looks like this now:
```
 "dependencies": {
    "ipfs": "^0.61.0",
    "it-all": "^1.0.6",
    "libp2p": "^0.35.8"
  },
  "resolution": {
    "blockstore-core": "1.0.2"
  }
```

**Comment by achingbrain** [comment]
This should be fixed now (months ago 😅 ) please re-open if you're still seeing this.

**Comment by ygit1** [comment]
> import * as IPFS from 'ipfs-core'
import * as IPFS from 'ipfs-core'
^^^^^^
Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import


---------

const ipfs = require('ipfs-core')
const i =ipfs.create()

InvalidValueError: The ipfs-repo-migrations package does not have all migration to migrate from version 11 to 12

code: 'ERR_INVALID_VALUE'

**Comment by ygit1** [comment]
> import * as IPFS from 'ipfs-core' ^^^^^^ Uncaught: SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import
> 
> const ipfs = require('ipfs-core') const i =ipfs.create()
> 
> InvalidValueError: The ipfs-repo-migrations package does not have all migration to migrate from version 11 to 12
> 
> code: 'ERR_INVALID_VALUE'

Maybe I got a solution.

$ rm -rf /home/y/.jsipfs
const IPFS = require('ipfs-core')
const ipfs2 = await IPFS.create()


generating Ed25519 keypair...
to get started, enter:

	jsipfs cat /ipfs/QmRaaUwTNfwgFZpeUy8qrZwrp2dY4kCKmmB5xEqvH3vtD1/readme

Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWLDWGLLd5ausoJJ4jkUvrFUDrk6ofhRCtNUJAG957LsaZ
Swarm listening on /ip4/194.163.183.167/tcp/4002/p2p/12D3KooWLDWGLLd5ausoJJ4jkUvrFUDrk6ofhRCtNUJAG957LsaZ
Swarm listening on /ip4/172.18.0.1/tcp/4002/p2p/12D3KooWLDWGLLd5ausoJJ4jkUvrFUDrk6ofhRCtNUJAG957LsaZ
Swarm listening on /ip4/172.20.0.1/tcp/4002/p2p/12D3KooWLDWGLLd5ausoJJ4jkUvrFUDrk6ofhRCtNUJAG957LsaZ
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWLDWGLLd5ausoJJ4jkUvrFUDrk6ofhRCtNUJAG957LsaZ
