### ISSUE TITLE
Not all pubsub entries reach the subscriber

### ISSUE THREAD

**Issue by artegoser** [ipfs/js-ipfs#4017]
- **Version**: 0.13.0

- **Platform**: Windows

#### Description:
I make a record in pubsub every second. I also run the second ipfs node, which is subscribed to pubsub. On the js version of ipfs, not all entries come to the second ipfs node. Everything is perfect on the go-cli version.

first daemon
```js
import * as IPFS from "ipfs-core";
const ipfs = await IPFS.create({repo: "repo"});

const topic = "secret";
const receiveMsg = (msg) => console.log(new TextDecoder().decode(msg.data));

await ipfs.pubsub.subscribe(topic, receiveMsg);
console.log(`subscribed to ${topic}`);

let i = 0;
setInterval(async () => {
  const msg = new TextEncoder().encode("banana" + i+"\n");
  await ipfs.pubsub.publish(topic, msg);
  i++;
}, 1000);

```

second daemon
```js
import * as IPFS from 'ipfs-core'

const ipfs = await IPFS.create({repo: 'repo2'});


const topic = 'secret'
const receiveMsg = (msg) => console.log(new TextDecoder().decode(msg.data))

await ipfs.pubsub.subscribe(topic, receiveMsg)
console.log(`subscribed to ${topic}`)
```

outputs:

```
banana2
banana5
banana7
banana8
banana12
```

go-cli daemon outputs:
```
banana1
banana2
banana3
banana4
banana5
```

**Comment by lidel** [comment]
cc @wemeetagain

**Comment by lidel** [comment]
Triage: we (@wemeetagain)  will try t reproduce this and decise next steps

**Comment by wemeetagain** [comment]
Not able to reproduce on Ubuntu LTS or Windows 10, using ipfs-core v0.13.0 or v0.14.0. In all cases, the second daemon received all messages.
