### ISSUE TITLE
ReferenceError: AbortController is not defined

### ISSUE THREAD

**Issue by ethdev279** [ipfs/js-ipfs#4019]
- **Version**: 55.0.0

- **Platform**: Nodejs 14.5.0 on macOs

- **Subsystem**: Don't know

#### Description:
Getting error  ```ReferenceError: AbortController is not defined```

Tried to use ```ipfs-http-client``` v55.0.0 in nodejs like below. It seems working fine in client side(reactjs app) but it is throwing error in nodejs backend
```
import { create } from "ipfs-http-client";
const ipfsClient = create({ host: 'ipfs.infura.io', port: 5001, protocol: 'https' });

const { path } = await ipfsClient.add('Hello World');
console.log(path)
```

**Comment by clarkjoao** [comment]
Has one solution in progressing #4015 but still waiting other fix  be finished.

**Comment by achingbrain** [comment]
Please upgrade to node 16 - node 14 is not supported any more.  `AbortController` is global in node 15+ so this should resolve your issue.

**Comment by ethdev279** [comment]
@achingbrain I wonder why it is working on react app of same node(14.5.0) environment?

**Comment by gary02** [comment]
> Please upgrade to node 16 - node 14 is not supported any more. `AbortController` is global in node 15+ so this should resolve your issue.

but aws lambda do not support node 16 yet.

**Comment by OrderAndCh4oS** [comment]
> > Please upgrade to node 16 - node 14 is not supported any more. `AbortController` is global in node 15+ so this should resolve your issue.
> 
> I use ipfs-http-client in aws lambda ( .zip file archives way) which do not support node 16 yet.

I'm also using AWS Lambda with a Node 14 Runtime. I got around the issue by installing `node-abort-controller` and setting it on the `global`. 

```js
import {AbortController} from "node-abort-controller";
global.AbortController = AbortController;
```

Seems to work fine, have been able to add files to IPFS with no trouble. 

https://www.npmjs.com/package/node-abort-controller

**Comment by achingbrain** [comment]
@OrderAndCh4oS that's a decent workaround until AWS allows everyone to use Active LTS versions of node.

**Comment by achingbrain** [comment]
Closing because a solution has been found - either upgrade to node 16 or use a polyfill.

**Comment by gary02** [comment]
> @OrderAndCh4oS that's a decent workaround until AWS allows everyone to use Active LTS versions of node.

aws lambda support node 16 now
