### ISSUE TITLE
Autogenerate JS Core API Docs

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#4021]
## Problem

Right now JS Core API docs are maintained by hand [as a directory with bunch of Markdown files](https://github.com/ipfs/js-ipfs/tree/ipfs-core%400.13.0/docs/core-api).

This is [unsustainable](https://pls.watch/#v=EF_xdvn52As&t=1m28.9s;1m30.5s&UNSUSTAINABLE), docs often get out of date (https://github.com/ipfs/js-ipfs/pull/4013, https://github.com/ipfs/js-ipfs/pull/3990, https://github.com/ipfs/js-ipfs/pull/4014, #3911, [etc](https://github.com/ipfs/js-ipfs/pulls?q=is%3Apr+is%3Aclosed+docs+core-api+)), wasting everyone's time.

## Proposed solution

- Create automation that ensures that JS API docs reflect the API in the latest release
  - We have TypeScript type definitions and could extend existing descriptions in [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)
- It could live at https://docs.ipfs.io/reference/js/api/, 
  - prior art: auto-generated docs for RPC over HTTP at https://docs.ipfs.io/reference/http/api/ are generated by [this CI workflow](https://github.com/ipfs/ipfs-docs/blob/main/.github/workflows/update-on-new-ipfs-tag.yml)

cc @achingbrain  @BigLep + @hugomrdias if there is any prior art for doing this in JS land

**Comment by hugomrdias** [comment]
The end goal was always to use https://typedoc.org/ to gen the docs, we didnt do it because the output wasn't always the best because of legacy cjs code. 
You can check nft.storage client workflow https://github.com/nftstorage/nft.storage/blob/main/.github/workflows/client.yml#L79 and output https://nftstorage.github.io/nft.storage/client

**Comment by galargh** [comment]
I think this might be a pretty interesting task for one of our Dev Productivity Launchpad Cadets. According to the schedule, they'll start working on issues after Feb 21. Would that timeline work here?

**Comment by laurentsenta** [comment]
👋  I took a quick shot at this issue to try to move it forward, without much success yet,

It's not straightforward to point typedoc to `ipfs-core/index.ts` and get a "good looking" documentation,
it looks like typedoc doesn't resolve [references import](https://github.com/ipfs/js-ipfs/blob/6a5ea700/packages/ipfs-core/src/index.js#L9), so all we get are empty API types. (also some of our interfaces seemed to break typedoc's parser)

There is a monorepo configuration with typedoc, but I couldn't get it to work. It looks like our setup confuses typedoc: it tries to load our `index.js` and find its source typescript. Which doesn't exist.

I did manage to generate an equivalent of the current doc by pointing typedoc at the `ipfs-core-types` folder and marking every ts file as an entry point.

- [In Markdown](https://github.com/laurentsenta/js-ipfs/blob/test-doc/packages/ipfs-core-types/docs/md/modules.md)
- [In HTML form](https://test-docs-js-ipfs.netlify.app/interfaces/index.ipfs)
- For comparison:
  - [generated bitswap](https://github.com/laurentsenta/js-ipfs/blob/test-doc/packages/ipfs-core-types/docs/md/interfaces/bitswap.API.md)
  - [original](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/BITSWAP.md)

I see a few options:

- Invest into typedoc to make it work with our codebase and use it /everywhere/,
- Build our own solution, just the minimum that works with this codebase,
- Look into other tools such as jsdoc with better-docs plugin.

**Comment by SgtPooki** [comment]
@laurentsenta @galargh 

Laurent, are you planning on taking this on?

**Comment by laurentsenta** [comment]
@SgtPooki Not right now, feel free to take over,

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
