### ISSUE TITLE
Cannot compile with Typescript Project

### ISSUE THREAD

**Issue by johanneskares** [ipfs/js-ipfs#4029]
In my project in tsconfig.json when `skipLibCheck` is set to `false` or remove the option I can no longer compile the project and I get a bunch of error messages.

**Comment by johnb8005** [comment]
here's a link to a failing build: https://github.com/nexys-system/ipfs-infura-client/actions/runs/1753407843
(which is solved by setting `skipLibCheck=false`)

**Comment by achingbrain** [comment]
`ToJSON` can probably be removed, after a quick search it seems it's not used anywhere - would you like to open a quick PR?

To fix the `"cannot find namespace 'fs'"` error you can add `@types/node` to your project as a dev dep.

You probably want `skipLibCheck: true` in general though, there are lots of modules in the dep tree whose types are broken.

**Comment by johnb8005** [comment]
@achingbrain https://github.com/ipfs/js-ipfs/pull/4031

**Comment by achingbrain** [comment]
@johnb8005 that just removes the circular reference, I mean the whole type can go.

**Comment by johnb8005** [comment]
@achingbrain just edited
