### ISSUE TITLE
Adding directory from multi-file input

### ISSUE THREAD

**Issue by jwarshack** [ipfs/js-ipfs#4038]
Hello.  I am trying to upload a directory to IPFS from a user input.  I know that you can upload local directories but how do you do it from the browser. 

Here is my code:

```
function App() {

  async function handleFile(e) {
    const files = e.target.files

    for await (const file of client.addAll(files)) {
        console.log(file.path)
    }

  }
  return (
    <div className="App">
        <input type="file" webkitdirectory directory multiple accept="audio/*" onChange={handleFile}/>            
    </div>
  );
}
```

This adds the files to IPFS and returns the cid for each individual file.  I want to wrap all files in a directory and return the cid of the directory.

**Comment by amandesai01** [comment]
Hey @jwarshack,
When you select a folder using `input type file`, it creates an iterable of file blobs and passes in reference.
You are using [`addAll` function](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsaddallsource-options). All it does is takes in an iterable of files and adds all files to IPFS and return's their IDs. Which is exactly what happened in you case. 

If you want to store all data together, there are two ways.
1. You can zip it and then send to IPFS and while receiving back to client, unzip it and use.
2. Use [Mutable File System (MFS)](https://docs.ipfs.io/concepts/file-systems/#working-with-files-api).  There, you can make directories and stuff.

I hope this helps.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This functionality should be possible in Helia with https://www.npmjs.com/package/@helia/unixfs
