### ISSUE TITLE
Content Related Gateway Errors

### ISSUE THREAD

**Issue by piboistudios** [ipfs/js-ipfs#4046]
- **Version**:

~~Browser only use case.~~ [`0.62.1`](https://www.npmjs.com/package/ipfs/v/0.62.1)

- **Platform**:

<html>
<body>

Google Chrome | 97.0.4692.99 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 10 Version 20H2 (Build 19042.1466)

</body>
</html>

- **Subsystem**:

Files
#### Severity:

High
#### Description:

Adding content with certain data results in gateway errors.
What I did:
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin is Law")).cid}` - This works
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin -is- Law")).cid}` - This doesn't work (Gateway error)
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin been Law")).cid}` - This works
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin -been- Law")).cid}` - This doesn't work (Gateway error)

This also happens for certain files. I believe it to be related to the encoding as I was intermittently getting an error complaining about the encoding of the hash... but alas I can't get this error anymore (just gateway errors)

This also happens with pretty much all other public gateways. I haven't set up an IPFS (full?) node myself just yet, just testing it out and ran into this. It works _very_ well when it does, but it just doesn't _sometimes_, and it doesn't seem to be related to actual network availability. It seems pretty directly related to the actual content of the data in a way I am unfortunately struggling to explain given the limited knowledge of IPFS I have.

#### Steps to reproduce the error:

Oh, maybe I should've put the above section here. Well
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin is Law")).cid}` - This works
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin -is- Law")).cid}` - This doesn't work (Gateway error)
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin been Law")).cid}` - This works
- go to `https://dweb.link/ipfs/${(await ipfs.add("Dalvin -been- Law")).cid}` - This doesn't work (Gateway error)

**Comment by lidel** [comment]
@piboistudios these API calls look incorrect (see [docs for `ipfs.add`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsadddata- ptions)) – seems that you omitted some context.

Mind telling us more? Namely:

- data or exact CIDs that work / error
- what exact error is returned by HTTP gateway?

Thanks.

**Comment by BigLep** [comment]
Closing because didn't get more info.  Feel free to reopen with the provided info.
