### ISSUE TITLE
Pin a file not working 

### ISSUE THREAD

**Issue by Agin-DropDisco** [ipfs/js-ipfs#4063]
Version: ^52.0.0
sample code
``` 
fetch('https://ipfs.infura.io:5001/api/v0/pin/add?arg=/ipfs/' + hash, {})

```
response: (Failed to load resource: the server responded with a status of 405 (Method Not Allowed) https://ipfs.infura.io:5001/api/v0/pin/add?arg=/ipfs/QmXpPpLvNnGrovM5t3yMQa18NVoG2PvEUhDwbcy7Nwe74Y

**Comment by lidel** [comment]
@Agin-DropDisco the RPC API at `/api/v0` is POST-only, switch  HTTP request from GET to POST.

**Comment by Agin-DropDisco** [comment]
when this happen? i ran my dapp in almost one years, but four days ago  till now suddenly got this error.

**Comment by Agin-DropDisco** [comment]
thx closed!
