### ISSUE TITLE
README examples throw type errors

### ISSUE THREAD

**Issue by Karan-U-Kanthawar** [ipfs/js-ipfs#4072]
- **Version**: 0.11.0
- **Subsystem**: ipfs-http-client

#### Description: 
I tried using an instance of the https client using TS just like how it's in the docs. When I did create the instance my IDE complained about type errors.

#### Steps to reproduce the error:
I created the instance like this by looking at the [README](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/README.md#example)
`const client = create("https://ipfs.provider.io:5001/api/v0");
`

This was the type error: 
> Type '"https://ipfs.provider.io:5001/api/v0"' has no properties in common with type 'Options'.ts(2559)

Turns out `create()` only accepts `Options | undefined` as params.
So I had to pass the URL like this:
`const client = create({ url: "https://ipfs.provider.io:5001/api/v0" });`

Should I raise a PR to update the examples in the [README](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/README.md#example)?

**Comment by lidel** [comment]
> Should I raise a PR to update the examples in the [README](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/README.md#example)?

Yes please :pray:
