### ISSUE TITLE
version tests fail if version is updated

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#409]
@dignifiedquire seems we missed this one: https://github.com/ipfs/js-ipfs/blob/master/test/http-api/test-version.js#L21

The tests fail after release. We need to cache the version number from the package.json to make the validation

**Comment by dignifiedquire** [comment]
uups :blush:

**Comment by diasdavid** [comment]
fixed in https://github.com/ipfs/js-ipfs/pull/407
