### ISSUE TITLE
Version 54.0.2 of ipfs-http-client is not compatible with version 14 of Node.js anymore

### ISSUE THREAD

**Issue by claudiosdc** [ipfs/js-ipfs#4115]
- **Version**: 54.0.2

- **Platform**: any

- **Subsystem**: ipfs-http-client

#### Description:
If one builds an application that includes version 54.0.2 of the ipfs-http-client module and tries to run it on Node.js version 14, the following error will be triggered whenever the application tries to call any of the IPFS API methods exposed by the ipfs-http-client module: ReferenceError: AbortController is not defined.

This is due to the fact that the latest versions (9.0.3+) of the dependent ipfs-utils module assumes that the AbortController class is provided by Node.js, but that is only true for versions 15 and above of Node.js, not for version 14.

The problem is that on the package.json file of the ipfs-http-client module (for ver. 54.0.2) the dependent ipfs-utils module is referenced using the semver expression ^9.0.2, which includes the latest versions of the ipfs-utils module that are not compatible with Node.js ver. 14 anymore, while the engines entry of the package.json file specifies version 14 as the minimum supported Node.js version.

An easy fix would be to generate a patch update for version 54.0 of the ipfs-http-client module that would have its package.json file updated to reference the specific version 9.0.2 of the ipfs-utils module; in other words, change the semver expression from ^9.0.2 to 9.0.2.

#### Steps to reproduce the error:

Write an application that includes version 54.0.2 of the ipfs-http-client module and calls one of the exposed IPFS API methods. Then build it, and try to run it on Node.js version 14.

**Comment by BigLep** [comment]
@claudiosdc : that's correct - it isn't supported.  Our supported versions are documented here: https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md#supported-versions
