### ISSUE TITLE
ipfs/CHANGELOG.md is out of order

### ISSUE THREAD

**Issue by BigLep** [ipfs/js-ipfs#4119]
https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/CHANGELOG.md has "[0.61.0](https://github.com/ipfs/js-ipfs/compare/ipfs@0.60.2...ipfs@0.61.0) (2021-12-15)" at the top of the doc even though it isn't the latest release.  I didn't manually modify because I assume there is automation involved.

**Comment by achingbrain** [comment]
This is probably down to the switch from aegir for releases to release-please.  It's probably safe to edit it manually and move the older release into the right position, as long as the headings/format/etc is also updated to be consistent with the rest of the file.

What's the worst that could happen 😆
