### ISSUE TITLE
Sharness tests

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#412]
In order to improve the quality and robustness of js-ipfs, it is pretty important to reuse the SHarness testing infrastructure against the js-ipfs http-api.

@chriscool could you help us with that? I think the best first step is to have the go-ipfs cli point at the js-ipfs http-api and test the endpoints that js-ipfs already implements (i.e: object, block, bitswap, add, cat, get). We can do that by pulling `go-ipfs` as a devdependency and run it in CI

**Comment by chriscool** [comment]
@diasdavid yeah I started to take a look at that during the Lisbon workshop, but there were a lot of problems, startin with `jsipfs version`.
I will take another look soon.

**Comment by diasdavid** [comment]
I was more thinking in the lines of using go-ipfs cli to point to js-ipfs http api (ipfs --api='') so that we can tell that both behave the same way, avoiding to have to write the entire CLI.

**Comment by diasdavid** [comment]
@chriscool any update about this?

**Comment by chriscool** [comment]
@diasdavid I had a vacation and I am at the LinuxCon in Toronto now until next Monday.
I will try to take a look at it soon. Or maybe we should plan to discuss it, maybe on IRC, at the end of next week.

**Comment by diasdavid** [comment]
@chriscool how are things? Can we look into this again? jsipfs is now interopable with go-ipfs (so we can have tests that use both at the same time) and the CLI is getting the same features + interface :)

**Comment by chriscool** [comment]
@diasdavid great that it's now interoperable! Could we discuss it and try to do something tomorrow morning at around 9 am CEST time or are you available now?

**Comment by diasdavid** [comment]
@chriscool I'm currently in NYC, so 9am CEST would be 4am for me. Can we make it in your afternoon?

**Comment by chriscool** [comment]
@diasdavid then I think 9pm CEST is better for me. That would be 4pm for you.
Is it ok for you?

**Comment by chriscool** [comment]
@diasdavid actually 9pm CEST is not possible today for me. I forgot that I had planned to meet friends. But it's possible tomorrow (Thursday September 15). Would that work for you?

**Comment by diasdavid** [comment]
@chriscool Thank you for handling this, I see you have opened the PR's, let's follow on those ones:

- https://github.com/ipfs/js-ipfs/pull/522
- https://github.com/ipfs/js-ipfs/pull/521
- https://github.com/ipfs/js-ipfs/pull/520
- https://github.com/ipfs/js-ipfs/pull/519
- https://github.com/ipfs/js-ipfs/pull/518
