### ISSUE TITLE
Import of ipfs-http-client crashing in Next.js

### ISSUE THREAD

**Issue by 10dimensions** [ipfs/js-ipfs#4128]
Module not found: Package path . is not exported from package C:\projects\amberfi\dapp\my-dapp\node_modules\ipfs-http-client (see exports field in C:\projects\amberfi\dapp\my-dapp\node_modules\ipfs-http-client\package.json)
   8 |     });
   9 | };
> 10 | import { create as ipfsHttpClient } from 'ipfs-http-client';
     |                                                           ^
  11 | export class IUploadHandler {
  12 |     constructor(initParams) {
  13 |     }

 **Version**:
57.0.1

- **Platform**:
Google Chrome

- **Subsystem**:
Imported in a Next.js component

#### Severity:
  Critical - System crash, application panic.

#### Description:
Imported ipfs-http-client module.
Which is referenced by an internal npm package.
Finally, import inside a Next.js UI component

**Comment by rawatnaresh** [comment]
i'm getting similar issue while using it with cloud functions. i've created an issue with reproducible demo
https://github.com/ipfs/js-ipfs/issues/4180

**Comment by achingbrain** [comment]
`Module not found: Package path . is not exported from package` means you are trying to `require` an ESM module.

Your source code is in ESM but chances are your output settings are producing CJS - please check the output folder for the type of JS being emitted and update your config to emit ESM instead.

**Comment by rafinskipg** [comment]
@achingbrain i'm having the same problem trying to create a github action that uses this package. i use vercel/ncc to build and i have no idea what this package is missing in order to be used.
