### ISSUE TITLE
bug: changelog generator isn't updating package changelogs

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-ipfs#4137]
- **Version**:
All and new versions are impacted by this

- **Platform**:
N/A

- **Subsystem**:
ipfs-http-client

#### Severity:
Low - An optional functionality does not work.

#### Description:
changelog for ipfs-http-client is out of date. Probably similar for other packages in the repo: https://github.com/ipfs/js-ipfs

https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/CHANGELOG.md shows 55.0.0 as the latest, but https://www.npmjs.com/package/ipfs-http-client shows 57.0.1

#### Steps to reproduce the error:
Just visit the links

**Comment by achingbrain** [comment]
> isn't updating package changelogs

Not strictly true, `semantic-release` just puts the latest in an `h2` under the top level `h1`, the previous one used `h1` for the latest.  Just needs a one-time fixup to convert the `h1`s to `h2`s and put them in the correct order.
