### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in package.json

### ISSUE THREAD

**Issue by Schwartz10** [ipfs/js-ipfs#4138]
- **Version**:

`0.63.3`

- **Platform**:

Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

#### Severity:
High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
I've been trying to get a simple typescript nodejs project to import dependencies from `ipfs` on npm, but always results in 
```
[ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in package.json
```

This sounds related to https://github.com/ipfs/js-ipfs/issues/4135 and https://discuss.ipfs.io/t/ts-ipfs-core-example-v0-15-0-causes-error-opposed-to-v0-14-0/14460

#### Steps to reproduce the error:
Clone [this repo](https://github.com/Schwartz10/ipfs-replicate-import-err), `npm i`, and `npm start`

**Comment by rafinskipg** [comment]
@achingbrain I'm really stupid to understand how to solve this. Can you provide some examples on how to use your package now with other packages when bundling? version 56.0.2 seems to work well with everthing

**Comment by woodjs** [comment]
```
async function loadIpfs() {

	const { create } = await import('ipfs');
	const ipfs = create({...});

	return ipfs;
}
```

**Comment by andarocks** [comment]
I am still getting the same error while trying the above code. I am using `ipfs-http-client` and using NestJs. Can anyone please help me out?

**Comment by ikaz-jem** [comment]
[ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in package.json

use type:module and use import {create} instead of requiring http client it , it worked
