### ISSUE TITLE
Can't resolve '@libp2p/crypto/keys'

### ISSUE THREAD

**Issue by kailash360** [ipfs/js-ipfs#4148]
- **Version**:  0.15.4

- **Platform**: Windows (64 bit)

- **Subsystem**: libp2p

#### Description:

On adding the package to my ReactJS application, the entire project breaks with the following error
![image](https://user-images.githubusercontent.com/75155230/175784771-cf30bda3-e951-4d85-a9e3-0d01951e3102.png)

#### Steps to reproduce the error:

1. Add latest release of the package to ReactJS application
2. It would give an error while compilation

**Comment by inspiraluna** [comment]
I can confirm this problem on MacOs Platform too. Downgrading to 0.15.2 doesn't seem to help either. 
I assume the problem is inside libp2p/js-libp2p-crypto/keys  and found something possibly related: 
https://github.com/libp2p/js-libp2p-crypto/issues/256 I am going to fork this and give it a try!

**Comment by inspiraluna** [comment]
This strategy was unfortunately not successful. 
My problem disappeared when
- I created a brand new react project ```yarn create react-app my-blog```
- added latest ipfs-core (0.15.2) ```yarn add ipfs-core util``` <-- is that the same package you added? 
- added this hook to my src directory and referenced it inside App.js like so:
```
import useIpfsFactory from './hooks/use-ipfs-factory.js'

function App() {

  const { ipfs, ipfsInitError } = useIpfsFactory({ commands: ['id'] })
  return (
```

Which version of React you are using and do you have any other modules in your packages .json then the standard ones coming after creating the React project?

I was using 
- React version 17 and 
- react-scripts version 4.0.3 

in order to eliminate a "process not found" problem when I ran into your error message after playing around with the latest orbit-db package.

**Comment by shiyicode** [comment]
<img width="848" alt="Xnip2022-07-16_18-40-08" src="https://user-images.githubusercontent.com/12529091/179351580-6ef70bd0-3643-44e7-ac6b-9eb2828d40ec.png">
I encountered the same situation

**Comment by BigLep** [comment]
Please can we have a reproduction to reproduce the problem?

**Comment by aantaya1** [comment]
Importing the entire `ipfs` library fixed this for me:
```
npm i ipfs
```

**Note**: this will also install the CLI and HTTP server modules.

**Comment by inspiraluna** [comment]
I tried reproducing this problem as described above one more time with ipfs@0.15.4 (instead of 0.15.2) and this problem seems resolved imho! (I don't know about the others having the same issue with different approaches)

**Comment by shaolongcai** [comment]
I also facing same issue,I have tried many ways

**Comment by 2color** [comment]
@shaolongcai Can you share the IPFS dependencies that you have in your `package.json` and their versions?

**Comment by manboy-eth** [comment]
@2color, here you go:
```
➜ npm ls @libp2p/crypto
zodiac-app...
└─┬ ipfs-core@0.15.4
  ├─┬ @chainsafe/libp2p-noise@6.2.0
  │ └── @libp2p/crypto@0.22.14 deduped
  ├── @libp2p/crypto@0.22.14
  ├─┬ @libp2p/kad-dht@1.0.16
  │ └── @libp2p/crypto@0.22.14 deduped
  ├─┬ @libp2p/peer-id-factory@1.0.18
  │ └── @libp2p/crypto@1.0.3
  ├─┬ ipfs-core-config@0.4.1
  │ └─┬ @chainsafe/libp2p-gossipsub@1.2.0
  │   ├── @libp2p/crypto@0.22.14 deduped
  │   └─┬ @libp2p/pubsub@1.3.0
  │     └── @libp2p/crypto@0.22.14 deduped
  ├─┬ ipns@1.0.2
  │ └── @libp2p/crypto@0.22.14 deduped
  └─┬ libp2p@0.37.3
    ├── @libp2p/crypto@0.22.14 deduped
    └─┬ @libp2p/peer-record@1.0.12
      └── @libp2p/crypto@0.22.14 deduped
```

**Comment by BigLep** [comment]
Reopening since input was provided (just not by the original author). 

Does that help with debugging @2color ?

**Comment by 2color** [comment]
Couldn't find any changes that may have caused this in the hotfix range and version provided by @manboy-eth.

Without a full reproduction, it's really hard determining the root cause here.

**Comment by ma68546** [comment]
I still have the same issue with libp2p/logger and with ipfs-http-client. It always looks like that: 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/18228325/193986005-e8d9064c-601e-4daf-9127-d21295823a74.png">
those are the installed packages
<img width="245" alt="image" src="https://user-images.githubusercontent.com/18228325/193986056-77724ed9-07f1-4a81-9c91-359b80941bde.png">

Even when installing the logger globally it wont find it in the npmpackages anymore. 
<img width="227" alt="image" src="https://user-images.githubusercontent.com/18228325/193986116-1cc60e70-f1fb-4ccd-b072-2fd3d37921c6.png">
