### ISSUE TITLE
[CONTENT REQUEST]  Browser Implementation Tools and Frameworks

### ISSUE THREAD

**Issue by MinmoTech** [ipfs/js-ipfs#4153]
Hey! :)

I'd like to request an addition to https://docs.ipfs.io/how-to/browser-tools-frameworks/

I'm interested in using the javascript build tool [esbuild](https://esbuild.github.io/) but don't quite understand how I could get it to work with js-ipfs.

Many thanks already!

(If curious, this [blogpost](https://jvns.ca/blog/2021/11/15/esbuild-vue/) is how I found out about esbuild)

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

There's an example of how to use [Helia with esbuild here](https://github.com/ipfs-examples/helia-esbuild) - hopefully this helps!

For additions/amendments to docs.ipfs.io please open a PR on https://github.com/ipfs/ipfs-docs
