### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dns' imported

### ISSUE THREAD

**Issue by lakshyabatman** [ipfs/js-ipfs#4161]
- **Version**: "^0.15.4"

- **Platform**: macos

- **Subsystem**:

#### Description:

```
import * as IPFS from 'ipfs-core';

const ipfs = IPFS.create();

(async () => { 
    const res = await ipfs.add("hello world")
    console.log(res);
})()
```
This is just I'm trying to achieve, but getting this weird error :/

**Comment by lakshyabatman** [comment]
And the error I got

> node src/index.js  
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dns' imported from /Users/lakshya/Desktop/projects/week-4/ipfs-upload/node_modules/@multiformats/multiaddr/dist/src/resolvers/dns.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'

**Comment by youngnishant** [comment]
@lakshyabatman i'm also getting the same error, have you got any solution for it ?

**Comment by zakariamouhid** [comment]
I also got the same error on NodeJS v14
fixed by upgrading NodeJS to v15+
because **ipfs** is using **multiformats** package that is using **dns/promises** package
https://github.com/multiformats/js-multiaddr/blob/master/src/resolvers/dns.ts#L1
and **dns/promises** works on NodeJS v15+
https://nodejs.org/api/dns.html#dns-promises-api

**Comment by youngnishant** [comment]
@zakariamouhid thanks and when i tried to deploy it on heroku its giving error that not able to bind port, I've tried everything, can you guide me how can i use heroku hosted ipfs using url?

**Comment by zakariamouhid** [comment]
@youngnishant I don't know alot about ipfs,
I think you should open a new issue for that.

**Comment by javaspeak** [comment]
I get the same error:

    javaspeak@Johns-MacBook-Pro server % npm start dev

    > server@1.0.0 start 
    /Users/javaspeak/workspace3/symbiont/permanent_node/server
    > node server "dev"

     (node:19910) UnhandledPromiseRejectionWarning: Error 
     [ERR_MODULE_NOT_FOUND]: Cannot find package 'dns' imported from 
/Users/javaspeak/workspace3/symbiont/permanent_node/server/node_modules/@multiformats/multiaddr/dist/src/resolvers/dns.js
     at packageResolve (internal/modules/esm/resolve.js:650:9)
     at moduleResolve (internal/modules/esm/resolve.js:691:18)
     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
     at Loader.resolve (internal/modules/esm/loader.js:88:40)
     at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
     at link (internal/modules/esm/module_job.js:71:36)

I am using ipfs in node.  Imported it as follows:

    const createIpfs = async () => {

        const { create } = await import('ipfs')

I am using nvm to install node and have tried many different versions:

        v14.17.3
        v15.0.0
        v15.7.0
       v16.17.0
        v18.4.0
        v18.9.0

Anyone know what this is about?

**Comment by javaspeak** [comment]
> I also got the same error on NodeJS v14 fixed by upgrading NodeJS to v15+ because **ipfs** is using **multiformats** package that is using **dns/promises** package https://github.com/multiformats/js-multiaddr/blob/master/src/resolvers/dns.ts#L1 and **dns/promises** works on NodeJS v15+ https://nodejs.org/api/dns.html#dns-promises-api

I tried:

    v15.0.0
    v15.7.0

and still got the error.

**Comment by achingbrain** [comment]
Please update your version of node to a [supported version](https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md#supported-versions) - 16.x.x at the time of writing, this should resolve your issue as some people in this thread have found.
