### ISSUE TITLE
Issue with node-fetch

### ISSUE THREAD

**Issue by ac12644** [ipfs/js-ipfs#4163]
- **Version**:

- **Platform**:

- **Subsystem**:

#### Description:

Current ipfs-http-client version is using node-fetch version 2.6.4 which is vulnerable to exposure of sensitive information to an unauthorized actor. Please update it to the latest 2.6.7.

**Comment by SgtPooki** [comment]
Closing in favor of https://github.com/ipfs/js-ipfs/issues/4243
