### ISSUE TITLE
there is no `assets` subdirectory

### ISSUE THREAD

**Issue by Mithgol** [ipfs/js-ipfs#418]
Currently `README.md` [recommends](https://github.com/ipfs/js-ipfs/blob/17a07363d6212c6fb2ebbac591d533900c1793ad/README.md#use-in-a-browser-using-a-script-tag) the following:

```js
<script type="text/javascript" src="assets/bundled.js"></script>
```

However,

* [HTML5 `script`](https://www.w3.org/TR/html5/scripting-1.html#the-script-element) defaults to `type="text/javascript"` and thus that attribute can be dropped from the example,

* there is no `assets` subdirectory in the results of `npm install ipfs` and thus the path `assets/bundled.js` should be replaced by `dist/index.min.js` if appropriate.

**Comment by diasdavid** [comment]
Seems that his is a leftover of pre 'dist' era. Currently, the installation method is the same for all the ipfs modules, that is:

![image](https://cloud.githubusercontent.com/assets/1211152/17701881/836b170e-63c3-11e6-88e8-cf4faf6495fb.png)

As seen in : https://github.com/multiformats/js-multihash#in-the-browser-through-script-tag

@Mithgol would you like to submit a PR to fix that? 

Thank you

**Comment by Mithgol** [comment]
Ok.
