### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/ipfs-http-client/package.json

### ISSUE THREAD

**Issue by rawatnaresh** [ipfs/js-ipfs#4180]
- **Version**:
57.0.3

- **Platform**:
Darwin Nareshs-MacBook-Air.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

- **Subsystem**:

#### Severity:
High

#### Description:

I'm trying to use `ipfs-http-client` with [Firebase cloud functions](https://firebase.google.com/docs/functions/get-started) but I'm getting an error while importing it.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/ipfs-http-client/package.json
```
#### Steps to reproduce the error:
-  Setup the Firebase project . https://firebase.google.com/docs/functions/get-started
- Install `ipfs-http-client`
- import the package
```js
import * as functions from "firebase-functions";
import { create } from 'ipfs-http-client';
const projectId = '**';
const projectSecret = '**';
const auth =
  'Basic ' + Buffer.from(projectId + ':' + projectSecret).toString('base64');
const ipfs = create({
  protocol: 'https',
  host: 'ipfs.infura.io',
  port: 5001,
  apiPath: 'api/v0',
  // url: 'http://ipfs.infura.io:5001/api/v0/',
  headers: {
    authorization: auth,
  },
});
// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript
//
export const helloWorld = functions.https.onRequest(async (request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  const file = await ipfs.add('hello');
  console.log(file);
  response.send("Hello from Firebase!");
});

```
- Run the app 
- Here's the reproducible demo https://github.com/rawatnaresh/firebase-functions-ipfs

**Comment by king-Alex-d-great** [comment]
I also have this issue.
`
import { create } from "ipfs-http-client";

const client = create();
async function addFiles(arrayOfFiles) {
  //const ipfs = await IPFS.create();
  const result = [];

  for await (const resultPart of client.addAll(arrayOfFiles)) {
    result.push(resultPart);
  }
  }
`

**Comment by rawatnaresh** [comment]
@king-Alex-d-great you would have to change your firebase-functions to use  `ES modules` for this package to work. By default firebase functions use `commonjs`.  In order to do that add `"type": "module"` in your package.json file.

**Comment by markg85** [comment]
```
const { create } = require('ipfs-http-client')
const client = create();
```
where the project type is nothing or commonjs (nothing defaults to commonjs) gives the same error.

Currently that means i **must** convert to a `"type":"module"` or downgrade to the previous release where this was working just fine.

**Comment by kenshyx** [comment]
I'm curious why the `main` attribute from package.json was removed, this would serve as a fallback for cjs imports. Not everyone can easily migrate their project to use `"type":"module"`

**Comment by threshold862543** [comment]
Downgrading to `ipfs-http-client` 56.0.0 fixed this for me.

**Comment by CorpulentBrony** [comment]
Having this same issue.

**Comment by CorpulentBrony** [comment]
Not sure why nobody's come along to let this thread know, but apparently you can use dynamic imports in CJS apps still: https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md

**Comment by silasdavis** [comment]
> Not sure why nobody's come along to let this thread know, but apparently you can use dynamic imports in CJS apps still: https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md

This did not work for me, not sure if it requires additional tsconfig properties, but I get the same `ERR_PACKAGE_PATH_NOT_EXPORTED` thrown from the dynamic import. I'm using `esModuleInterop: true` and running via ts-node, which may be relevant.

**Comment by CorpulentBrony** [comment]
> This did not work for me, not sure if it requires additional tsconfig properties, but I get the same `ERR_PACKAGE_PATH_NOT_EXPORTED` thrown from the dynamic import. I'm using `esModuleInterop: true` and running via ts-node, which may be relevant.

Not working for me either, but I'm not getting the same error.  I'm just getting really buggy errors, like when trying to use addAll after instantiating the client: 

```
ReferenceError: AbortController is not defined
    at Object.addAll (file:///var/www/twifag.com/node_modules/ipfs-http-client/src/add-all.js:22:24)
    at addAll.next (<anonymous>)
```

Thinking this is related.

Would be nice if the dev team would make this compatible again with CJS given that it's still the majority way of including files.  If I switch my entire project to imports, it actually breaks ***other*** packages that don't implement imports but instead CJS (I know it shouldn't, but it does).

**Comment by achingbrain** [comment]
Your tsconfig is [set to output CJS](https://github.com/rawatnaresh/firebase-functions-ipfs/blob/main/functions/tsconfig.json#L3) - it needs to output ESM instead.

Add `"type": "module"` to your `package.json`, and in `tsconfig.json` change `"module"` to `"ES2020"` and add `"moduleResolution": "node"`.

**Comment by CorpulentBrony** [comment]
> Your tsconfig is [set to output CJS](https://github.com/rawatnaresh/firebase-functions-ipfs/blob/main/functions/tsconfig.json#L3) - it needs to output ESM instead.
> 
> Add `"type": "module"` to your `package.json`, and in `tsconfig.json` change `"module"` to `"ES2020"` and add `"moduleResolution": "node"`.

That doesn't fix the issue when your entire codebase is CJS you can't just switch to module without refactoring everything, including other third party packages that simply won't include properly as a module.

**Comment by achingbrain** [comment]
@CorpulentBrony sorry it wasn't clear - I was replying to the OP, who has supplied a repro case that needs an update to it's `tsconfig.json` for it to work.

If you have a repro case I can take a look, but [as you've found](https://github.com/ipfs/js-ipfs/issues/4180#issuecomment-1250182601) if you are using CJS and cannot upgrade, you need to use a dynamic import to load ESM modules.

**Comment by daenamkim** [comment]
@achingbrain As @CorpulentBrony said it does not make sense to me as well because I have tested ESM config breaks everything. 

> If you have a repro case I can take a look, but https://github.com/ipfs/js-ipfs/issues/4180#issuecomment-1250182601 if you are using CJS and cannot upgrade, you need to use a dynamic import to load ESM modules.

I could not understand why and all context of this. I just wonder if there is no possibility to go back to CJS, the ultimate solution is just to keep 56.x at the moment?

**Comment by hubsmoke** [comment]
I figured out a magical incantation of tsconfig.json and package.json that allows us to use ipfs-http-api via typescript import

Example tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2020",
    "lib": [
      "es6"
    ],
    "moduleResolution": "node",
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
  },
  "ts-node": {
    "esm": true
  },
}
```

Example package.json (note this ---> `  "type": "module",`)

```
{
  "name": "ipfs-experiment",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "rimraf ./build && tsc",
    "start:dev": "nodemon",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "type": "module",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^18.11.9",
    "nodemon": "^2.0.20",
    "rimraf": "^3.0.2",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.3"
  },
  "dependencies": {
    "ipfs-http-client": "^59.0.0"
  }
}
```

Run `npm run start:dev` to execute


For reference, here's my src/index.ts

```
import { create } from "ipfs-http-client";

export default (async () => {
  // connect to the default API address http://localhost:5001
  const client = create();

  // call Core API methods
  const data = await client.add("Hello world!");

  console.log(data);
})();
```

**Comment by achingbrain** [comment]
@hubsmoke this almost works but the `npm run build` command in your repo fails.  To get it to work set target and module to `"es2020"` and remove `"lib"`:

```json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "es2020",
    "moduleResolution": "node",
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
  },
  "ts-node": {
    "esm": true
  },
}
```

**Comment by achingbrain** [comment]
There's more info in the [upgrade guide](https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md#typescript-and-esm)

**Comment by hubsmoke** [comment]
Awesome thanks for catching that. Here's the diff following your suggestions, which did improve the situation: https://github.com/hubsmoke/ipfs-typescript-starter/commit/58837da953946bd3b513fb90476b3cb4a5de4c33

However it still results in:

```
> ipfs-experiment@1.0.0 build
> rimraf ./build && tsc

node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:7:20 - error TS2307: Cannot find module 'ipfs-unixfs/types/src/types' or its corresponding type declarations.

7     mtime?: import("ipfs-unixfs/types/src/types").MtimeLike | undefined;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:12:19 - error TS2307: Cannot find module 'ipfs-unixfs/types/src/types' or its corresponding type declarations.

12     mtime: import("ipfs-unixfs/types/src/types").MtimeLike | undefined;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:7
```

I will need to tweak this to fix this issue -- I've run into it in the past just forgot what it needs. Took a look at the upgrade guide, but unclear what I would need to do to fix the above, lmk if you have any ideas. Thanks for your help! IMO would be great to have a community working template to get folks going on IPFS quickly.

**Comment by achingbrain** [comment]
Delete your lock file and reinstall

**Comment by hubsmoke** [comment]
@achingbrain awesome! Had to nuke my node_modules as well. Thanks for your help & attention 💯
