### ISSUE TITLE
HTTPError: not allowed - invalid user agent

### ISSUE THREAD

**Issue by PhillyWebGuy** [ipfs/js-ipfs#4186]
I have the origin below explicitly allowed as well as the user agent. And I still get a 403 ("HTTPError: not allowed - invalid user agent").

My creation string:

```
const client = create({
  host: 'ipfs.infura.io',
  port: 5001,
  protocol: 'https',
  apiPath: '/api/v0',
  headers: {
    Authorization:
      'Basic base64encodedstring',
    Origin: 'http://127.0.0.1:3000',
    'User-Agent':
      'Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19'
  }
});
```

**Comment by PhillyWebGuy** [comment]
A little more info...

I can see via Chrome Dev Tools that the 'User-Agent' header is being ignored and not sent. I could see what my User-Agent was and set to explicitly allow. Now I get a 500 error back with this response:

{"Message":"multipart: NextPart: EOF","Code":0,"Type":"error"}

FWIW, it says `type: 'cors'` in the error object.

<img width="1430" alt="Screen Shot 2022-08-15 at 9 24 57 AM" src="https://user-images.githubusercontent.com/449963/184643815-69a3a7c1-4b19-4f57-a4f7-fb3277202ce9.png">

**Comment by warrior1112** [comment]
same issue here also.
![image](https://user-images.githubusercontent.com/42972418/193424223-8c2ae6b0-b1a2-47a1-8ea0-6a9288744003.png)

**Comment by achingbrain** [comment]
You are making requests to `ipfs.infura.io` - I would suggest you check their documentation or contact them directly to find out what is required as this is unlikely to be a problem with the http client itself.
