### ISSUE TITLE
The CID obtained by the ipfs.add(data, [options]) function got "504 Gateway Time-out"

### ISSUE THREAD

**Issue by LouisLiu00** [ipfs/js-ipfs#4193]
- **Version**: "ipfs-core": "^0.15.4",

- **Platform**: Windows10 + Chrome + Node.js + Vue3.x

- **Subsystem**: ipfs-core

#### Description: I'm learning ipfs-core API. I get a CID via ipfs.add(data, [options]) but I get "504 Gateway Time-out" in browser access. How can I create the json data at the same time and put it in the specified directory?

Below is my code:

let ipfs = await this.$ipfs.create();
let metadata = {
    "description": "Hello IPFS, I'm Louis from China.",
    "image": "ipfs://QmTh7cULTdCrPQkzKBMXzLuZwjQFXp4c3TAJ6dAxR64PJP",
    "name": "Louis",
    "collection": "Louis's Album"
}

const param = {
      path: '/myfile/1',
      content: JSON.stringify(metadata),
}

const result = await ipfs.add(param);

console.info(result)
console.info(result.cid)
console.info(result.cid.path)
console.info(result.cid.toString())

if(ipfs.isOnline()) {
    ipfs.stop();
}

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

In order for the gateway to show data from your node it must be dialable from the public internet.

Are you able to use the https://ipfs-check.on.fleek.co/ website to confirm your node is routable from outside of your network?
