### ISSUE TITLE
init

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#42]
What are the things that occur during a `ipfs init`? (From key generation, if those base files are c&p or fetched from the network, etc). It would be good to make this part of IPFS spec itself.

#### Implementation roadmap

- [x] define/list what happens on an ipfs init
- [x] jsipfs init
  - [x] core
  - [x] http-api
  - [x] cli

**Comment by diasdavid** [comment]
**updated this issue**

**Comment by noffle** [comment]
First pass on this!

---

# input
```
 -f|--force: whether to overwrite an existing repo config
 -e|--empty: whether to add+pin ipfs info help files to the repo
 -b|--bits: # of bits to use in the generated RSA private key (default 2048)
```
# steps

1. check if config file is already locked by a daemon process
2. parse input flags
3. stdout: `"initializing ipfs node at %s", repoRoot`
4. ensure the repo root dir is writeable
5. bail if the repo root already exists & `--force` is not supplied
6. generate rsa keypair
 1. bail if < 1024 bits
 2. stdout: `"generating %v-bit RSA keypair...", nbits`
 3. if no error, write `"done"` to stdout
 4. compute private key as a base64 string
 5. compute public key as IDB58Encode'd
 6. stdout: `"peer identity: %s\n", ident.PeerID`
7. if the repo root already exists, remove it
8. write the new config at the repo root
9. if `--empty` is not provided, add the default ipfs help assets
 1. these are pre-loaded; stored in `assets/init-doc/`
 2. add+pin them to the new node
 3. if `!--empty`, stdout
```
to get started, enter:

  ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme
```
10. initialize the keyspace
 a. open the repo
 b. start up a new node (/w offline routing)
 c. set the ipns record for the pubkey to point to the empty dir

**Comment by noffle** [comment]
Draft for a "real" spec: https://github.com/ipfs/specs/pull/83

**Comment by diasdavid** [comment]
This is done! :D thank you @noffle

**Comment by noffle** [comment]
Does this still need to be open?

**Comment by diasdavid** [comment]
just missing https://github.com/ipfs/js-ipfs/pull/96 to be merged, right?

**Comment by diasdavid** [comment]
🎉🎉🎉🎉 one more issue that can be closed! :D 

Thank you @noffle :D
