### ISSUE TITLE
IPFS API 127.0.0.1:5002 Doesn't work

### ISSUE THREAD

**Issue by wwwhickup** [ipfs/js-ipfs#4205]
- **Version**: 0.64.0
- **Platform**: MacOS, Node: 16.13.1

#### Description:
I am going to create the IPFS node and going to use this IPFS endpoint to the another project.
I created the IPFS node by using `ipfs` module. And wanted to create ipfs client by using `ipfs-http-client` module. But can't connect to 127.0.0.1:5002

Please check the below code snap and error message

#### codesnap
```
import * as IPFS from 'ipfs'
import { create } from 'ipfs-http-client'

const CID = 'QmPWvpJcJrGPYNw1XDQtujyFrvqYfSNEGAmDZ2PtEZCR4q'

async function app () {
  const node = await IPFS.create({ repo: './ipfs/data'})
  const config = await node.config.get('Addresses')
  console.log('config: ', config)

  const client = create({ url: '/ip4/127.0.0.1/tcp/5002'})
  const resp = await client.cat(CID)
  for await (const chunk of resp){
    content = [...content, ...chunk]
  }
  const raw = Buffer.from(content)
  console.log('file content: ', raw.toString())
}

app()
```

#### package.json
```
{
  "name": "ipfs-node",
  "version": "1.0.0",
  "description": "ipfs node",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ipfs",
    "node",
    "nodejs"
  ],
  "author": "wwwhickup",
  "license": "ISC",
  "dependencies": {
    "ipfs": "^0.64.5",
    "ipfs-http-client": "^58.0.0"
  },
  "type": "module"
}
```

#### `console.log('config: ', config)` output

```
config:  {
  Swarm: [ '/ip4/0.0.0.0/tcp/4002', '/ip4/127.0.0.1/tcp/4003/ws' ],
  Announce: [],
  NoAnnounce: [],
  API: '/ip4/127.0.0.1/tcp/5002',
  Gateway: '/ip4/127.0.0.1/tcp/9090',
  RPC: '/ip4/127.0.0.1/tcp/5003',
  Delegates: [
    '/dns4/node0.delegate.ipfs.io/tcp/443/https',
    '/dns4/node1.delegate.ipfs.io/tcp/443/https',
    '/dns4/node2.delegate.ipfs.io/tcp/443/https',
    '/dns4/node3.delegate.ipfs.io/tcp/443/https'
  ]
```
#### Error message

`FetchError: request to http://127.0.0.1:5002/api/v0/cat?arg=QmPWvpJcJrGPYNw1XDQtujyFrvqYfSNEGAmDZ2PtEZCR4q failed, reason: connect ECONNREFUSED 127.0.0.1:5002`

**Comment by lidel** [comment]
@wwwhickup when you initialize node programmatically, you need to manually start API/Gateway.
See https://github.com/ipfs/js-ipfs/blob/89aeaf8e25320276391653104981e37a73f29de9/packages/ipfs-daemon/src/index.js#L36-L43
