### ISSUE TITLE
How to send pubsub message from Browser node to terminal node?

### ISSUE THREAD

**Issue by satoshi999** [ipfs/js-ipfs#4208]
I tried to sending pubsub message from Browser node to terminal node via websockets with following code.
It seems that has succeeded connection via websockets because opponent node id is in peer list
But, it can not receive pubsub message.

Is it possible that sending pubsub message between browser and terminal node?

On browser side.
- "ipfs-core": "0.15.4",
- "@libp2p/websockets": "3.0.2",
- Node.js : 14.18.0
```JavaScript
import {WebSockets} from '@libp2p/websockets'
import { all } from '@libp2p/websockets/filters'
import {create} from 'ipfs-core'

window.addEventListener('load', async() => {
  const ipfs = await create({
    repo:'IPFS-' + Math.random(),
    libp2p: {
      transports: [new WebSockets({filter:all})],
      config: {
        pubsub: {
          emitSelf:false
        }
      }
    }
  })
  
  await ipfs.swarm.connect('/ip4/127.0.0.1/tcp/4003/ws/p2p/QmVpoLX9Us7AF39vWsFFHSz274ShJfHaVY5VWoVsuAzpdb')

  await ipfs.pubsub.subscribe('message', (msg)=> {
    const data = new TextDecoder().decode(msg.data)
    console.log(data)
  })

  const id = await (await ipfs.id()).id

  setInterval(async() => {
    await ipfs.pubsub.publish('message', new TextEncoder().encode(`Hello from ${id}`))

    const peers = await ipfs.swarm.peers()
    for(const peer of peers) {
      console.log(peer.peer.toString())
    }
  }, 1000)
})
```

On terminal side
- "ipfs": "0.54.0"
- Node.js 14.18.0
```JavaScript
const { create } = require('ipfs');

(async() => {
  const ipfs = await create({
    repo: 'IPFS',
    EXPERIMENTAL: {
      pubsub: true
    },
    libp2p: {
      config: {
        pubsub: {
          emitSelf:false
        }
      }
    }
  })
  const id = await (await ipfs.id()).id

  await ipfs.pubsub.subscribe('message', async(msg)=> {
    const data = new TextDecoder().decode(msg.data)
    console.log(data)
  })

  setInterval(async() => {
    await ipfs.pubsub.publish('message', new TextEncoder().encode(`Hello from ${id}`))

    const peers = await ipfs.swarm.peers()
    for(const peer of peers) {
      console.log(peer.peer.toString())
    }
  }, 1000)
})()
```

**Comment by threshold862543** [comment]
I'm having a similar issue #4206

**Comment by satoshi999** [comment]
@threshold862543 
It issue seems that my case is different from this issue

This issue as linked describes the behavior when accessing by http from a browser using ipfs-http-client to a local node.
The pubsub keyword is used, but it seems irrelevant since it is ipfs-http-client

I understand that in my case it is an issue related to the pubsub communication between IPFS node in the browser and the daemon node, In other words, it seems to be a websockets communication issue between the browser node and the daemon nod

**Comment by threshold862543** [comment]
Yes, that's the issue I'm having as well.
Browser ipfs-http-client isn't communicating pubsub information with the daemon.

**Comment by SgtPooki** [comment]
Hello @satoshi999,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. There are examples at https://github.com/ipfs-examples/helia-examples and our guide for migrating to helia from js-ipfs can be found at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
