### ISSUE TITLE
Invalid IP address while running IPFS.create() command in NodeJS file

### ISSUE THREAD

**Issue by Shreyash1601** [ipfs/js-ipfs#4213]
I have made an expressJS server to handle http requests to store and retrieve data from IPFS.  Most of the time the swarm connectivity fails and throws an error "not a valid IP address. Please guide me on this. It's an importatnt element  of my project
![issue1](https://user-images.githubusercontent.com/59273958/191024227-8576f61c-77b0-4878-a187-f13bc2f00d04.png)
![issue2](https://user-images.githubusercontent.com/59273958/191024296-7539b9a3-820a-49e1-86b4-7355832ec478.png)

**Comment by achingbrain** [comment]
Do you have a minimal reproduction that we can run to see the problem?

**Comment by Shreyash1601** [comment]
Kindly clone the repository [https://github.com/Shreyash1601/IPFS-server.git](url)
Run the following commands
npm install
nodemon ipfs1.js

**Comment by achingbrain** [comment]
I have observed something very similar in CI on Windows only, then recently again on Mac OS.  It seems the regular expressions used by [is-ip](https://www.npmjs.com/package/is-ip) may get optimised at runtime to an invalid state.

We've [removed](https://github.com/multiformats/js-multiaddr/pull/280) `is-ip` from `@multiformats/multiaddr` in favour of `@chainsafe/is-ip` which doesn't use regex.

It's an in-range semver update so could you please try removing any lockfiles and reinstalling the deps?

If it still happens can you please paste the output of `npm ls is-ip` in your project root?

**Comment by Shreyash1601** [comment]
Sir the issue is resolved. But it has initiated a new issue and that is
"it's not able to generate a unique Hash ID each time a new data is stored.
It's giving same Hash ID everytime"
