### ISSUE TITLE
JS-ipfs-http-client / Go-IPFS does not support files.cp multiple files a time? [HTTPError: cp: cannot put node in path /ipfs/...: file does not exist]

### ISSUE THREAD

**Issue by tx0c** [ipfs/js-ipfs#4223]
- **Version**: Go-IPFS/0.15.0 (current latest)

- **Platform**: Linux

- **Subsystem**: js-ipfs-http-client/latest

#### Description:
1. `ipfs.files.cp(['/ipfs/<CID1>', '/ipfs/<CID2>', '/ipfs/<CID3...>'], '/dest-dir')`
2. it errors `[HTTPError: cp: cannot put node in path /ipfs/...: file does not exist]`
3. files.cp multiple files (including ipfspath) to a single directory is documented https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsfilescpfrom-to-options but seems not supported by Go-IPFS server

with some debugging logs printing, I got this:

    [Symbol(Response internals)]: {
      url: 'http://<go-ipfs-host>:5001/api/v0/files/cp?arg=%2Fipfs%2F<CID1...>&arg=%2Fipfs%2F<CID2...>&
     arg=%2Fipfs%2F<CID3...>&arg=...&arg=%2F/dest-dir',
      status: 500,
      statusText: 'Internal Server Error',
      headers: [Headers],
      counter: 0
    }

it seems just translate all from paths as `arg`, and `/dest-dir` as the last `arg`, but from https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-files-cp it seems support only a single file/dir/ipfspath at a time

#### Steps to reproduce the error:

Similar to #3547 there are many implementation details different between Js-IPFS vs Go-IPFS, but Js-IPFS has a poor performance if running as daemon server, in most cases call JS-ipfs-http-client interact'ing with Go-IPFS daemon server

**Comment by achingbrain** [comment]
This is something js-ipfs supports that go-ipfs does not. If you'd like to add support, please open a PR against the [kubo repo](https://github.com/ipfs/kubo).  You can also switch to [kubo-rpc-client](https://www.npmjs.com/package/kubo-rpc-client) which will be kubo-only going forward so will not support the extra niceties that js-ipfs does.
