### ISSUE TITLE
No "exports" main defined: ipfs and ipfs-core 

### ISSUE THREAD

**Issue by ReggieRumsfeld** [ipfs/js-ipfs#4235]
const IPFS = require('ipfs')

import * as IPFS from 'ipfs-core'

Lead to "No "exports" main defined" error for bot packages.

**Comment by Vilchynskyi** [comment]
> const IPFS = require('ipfs')
> 
> import * as IPFS from 'ipfs-core'
> 
> Lead to "No "exports" main defined" error for bot packages.

Same issue

**Comment by achingbrain** [comment]
These modules as ESM-only, you cannot `require` them, only `import`.

Please see: https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md#esm
