### ISSUE TITLE
DisableNatPortMap incorrectly documented?

### ISSUE THREAD

**Issue by Sjord** [ipfs/js-ipfs#4236]
In [CONFIG.md](https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md#disablenatportmap):

> By default when running under nodejs, libp2p will try to use [UPnP](https://en.wikipedia.org/wiki/Universal_Plug_and_Play) to open a random high port on your router for any TCP connections you have configured.
> 
> Set DisableNatPortMap to false to disable this behaviour.

However, I think this behaviour is disabled by setting `DisableNatPortMap` to true. Is that right? The `Disable` part of this setting inverses the setting.

**Comment by achingbrain** [comment]
Yes, this is incorrect - would you like to submit a quick PR that corrects the docs?
