### ISSUE TITLE
No "exports" main defined in ... package.json

### ISSUE THREAD

**Issue by michael-spengler** [ipfs/js-ipfs#4238]
Following the instructions given here: 
https://github.com/ipfs/js-ipfs#install-as-an-application-developer

... and then starting the program containing the example code leads to: 
No "exports" main defined in ... package.json 
... ERR_PACKAGE_PATH_NOT_EXPORTED

![Screenshot 2022-10-20 at 17 39 12](https://user-images.githubusercontent.com/43786652/196994610-ca496ad0-0d72-47a0-ae6a-48108c4e931c.png)

**Comment by achingbrain** [comment]
These modules as ESM-only, you cannot `require` them, only `import`.

Please see: https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md#esm

**Comment by achingbrain** [comment]
Please see the [upgrade guide](https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md#esm) and also [similar closed issues for solutions](https://github.com/ipfs/js-ipfs/issues?q=is%3Aissue+%22No+%22exports%22+main+defined+in+...+package.json%22+is%3Aclosed).

Here's one: https://github.com/ipfs/js-ipfs/issues/4180

**Comment by jwachtel96** [comment]
I believe they closed it because the latest version is es6 only, so  technically there is no bug. I am using version 34.0.0 and it works as it should.
