### ISSUE TITLE
feature request: remove `node-fetch` and use nodejs provided `fetch` API (via undici) 

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-ipfs#4243]
We should update to use the `fetch` provided by LTS node (which comes from [nodejs/undici](https://github.com/nodejs/undici))

## Related

* https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental
* https://github.com/ipfs/js-ipfs/pull/3835
* #4163 

## Usage

* https://github.com/ipfs/js-ipfs/blob/e8b7b66bfa98c2a1c0d0bfc19f698d7d00b6c888/packages/ipfs-daemon/package.json#L79
* https://github.com/ipfs/js-ipfs/blob/74aee8b3d78f233c3199a3e9a6c0ac628a31a433/packages/ipfs-daemon/test/index.spec.js#L5
* https://github.com/ipfs/js-ipfs/blob/0cee4a4c55767022584dcbade0b0b9b43326f9c9/package.json#L63

## Referenced in
* https://github.com/ipfs/js-ipfs/blob/62d8ecbc723e693a2544e69172d99c576d187c23/packages/ipfs/test/interface-http-js.js#L30
* https://github.com/ipfs/js-ipfs/blob/74aee8b3d78f233c3199a3e9a6c0ac628a31a433/packages/ipfs-core-utils/src/multipart-request.node.js#L76

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

This will not be fixed here, please upgrade to Helia which will get fixes and features moving forwards.
