### ISSUE TITLE
ipfs-core allow content read while node is booting

### ISSUE THREAD

**Issue by streamich** [ipfs/js-ipfs#4245]
When using `ipfs-core` in a browser it takes seconds to wait for `await create()` call to instantiate an IPFS node, connect to peers, etc..

However, during that time the locally cached content from IndexDB could be already used, at least in read-only mode. Is there a way to at least do reads, maybe writes, towards the IndexDB cache while the node is booting up?

**Comment by streamich** [comment]
Would be great if `create()` call returned "repo" as soon as storage is initialized, for example:

```ts
await create({
  onRepo: repo => {
    // Repo is ready...
  },
});
```

**Comment by streamich** [comment]
Also, would be good to support "offline" mode in ipfs-core, at least read requests can be served from the local block store.

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

With Helia (and js-IPFS tbh) you can pass `start: false` to the `create` factory which essentially makes it offline - you can then access the repo/blockstore etc and call `node.start()` at your leisure to make it online.
