### ISSUE TITLE
ReferenceError: global is not defined using "await ipfs.files.write('/' + file.name, file, { create: true })" in browser

### ISSUE THREAD

**Issue by scenaristeur** [ipfs/js-ipfs#4248]
i got this message using `await ipfs.files.write('/' + file.name, file, { create: true })` in browser as mentionned in https://proto.school/mutable-file-system/04

```
Uncaught (in promise) ReferenceError: global is not defined
    toAsyncIterator to-async-iterator.js:44
    mfsWrite write.js:99

```
a workaround that can help is 
`if (typeof window !== "undefined") window.global = window;`
as in this file https://github.com/scenaristeur/browser-vue/blob/64f58a9843b26b9794c370cd163d586369b67437/src/plugins/vue-ipfs.js#L12

**Comment by achingbrain** [comment]
Do you see the problem on protoschool or your own project?

**Comment by scenaristeur** [comment]
Hi, in my own project, code is up, root of project with demo  here https://github.com/scenaristeur/browser-vue/tree/64f58a9843b26b9794c370cd163d586369b67437
