### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in node_modules/ipfs/package.json

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#4256]
`js-ipfs@0.63` made the jump to become ESM-only.  If you are seeing the error message above, it's because you are trying to load ESM code using `require` from a CJS environment.

Instead you need to either convert your code to ESM and use `import`, or use the [dynamic `import` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) if you cannot convert to ESM.

Please see the [upgrade guide](https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md#esm) for more information.

Note if you are authoring TypeScript and using `import` you also need to ensure that your `tsc` settings result in ESM and not CJS.

Please see the [TypeScript section of the upgrade guide](https://github.com/ipfs/js-ipfs/blob/master/docs/upgrading/v0.62-v0.63.md#typescript-and-esm) for more information.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).
