### ISSUE TITLE
Taking over maintenance as part of the IPFS => web-modules spec standard transformation migration

### ISSUE THREAD

**Issue by lemanschik** [ipfs/js-ipfs#4261]
# Taking over maintenance Hardfoking 
- [ ] https://github.com/lemanschik/web-module-ipfs-src/issues/1

This gets partial migrated merged into the web-modules standard which got designed to superseed IPFS as a whole project

it is based on the same concepts but has Web Implementer support so this runs in the current browser eliminates all blockers and also gets directly added in its first version into code-oss / vscode

and vscode will in fact be the first web-module around including all concepts from the beaker browser project.

cheers thanks for attention.

## direct integration into v8
- [ ] https://github.com/unlicense-code/awesome/issues/4

**Comment by lemanschik** [comment]
Thanks i will try to get support for this your a good bot

**Comment by achingbrain** [comment]
Thanks for opening this issue but from what I can see there's no action here to be taken by the `js-ipfs` maintainers or contributors so I'm going to close this.

If you wish to track work items for your project, please use the issues on your repo.

Good luck!

**Comment by lemanschik** [comment]
@achingbrain if you would want to get a part of it this would request as action able item that you refactor your stuff into clean loadable modules directly out of the git repo.
