### ISSUE TITLE
js ipfs MP4 video streaming player requirements

### ISSUE THREAD

**Issue by Aiaminm** [ipfs/js-ipfs#4264]
- **Version**:

```
commit: "d1f1e75b2060c5c2e64d133a7a6bbabd2641e5ef"
interface-ipfs-core: "^0.156.1"
ipfs-core: "0.16.1"
repo: "12"
version: "0.16.1"

```

- **Platform**:

`Windows 11 22h2  Chrome 108.0.5359.99  64bit (cohort: Stable) `

- **Subsystem**:

https://github.com/ipfs-examples/js-ipfs-examples/blob/master/examples/browser-readablestream/package.json

#### Severity:

Low - An optional functionality does not work.

#### Description:

git clone repo
cd to browser-readablestream folder
npm install
npm start

#### Steps to reproduce the error:

![屏幕截图(1)](https://user-images.githubusercontent.com/70017178/206914399-ed58433e-1459-450d-b099-be5b36bf348c.png)

I'm not good at stream operations. How to import ipfs mp4 video to web page in easier way, without using gateway

**Comment by achingbrain** [comment]
Please could you open an issue against the [examples repo](https://github.com/ipfs-examples/js-ipfs-examples)?  I can't move this issue, but it should be opened there.
