### ISSUE TITLE
Encryption & connection errors when using Ed25519 PeerId

### ISSUE THREAD

**Issue by aewing** [ipfs/js-ipfs#4269]
- **Version**:

```json
{
  "version": "0.17.0",
  "commit": "e8b7b66bfa98c2a1c0d0bfc19f698d7d00b6c888",
  "repo": "12",
  "ipfs-core": "0.17.0",
  "interface-ipfs-core": "^0.157.0"
}
```

- **Platform**:

Darwin 21.6.0 arm64 & latest chrome

- **Subsystem**:

libp2p?

#### Severity:

Critical

#### Description:

I generated an Ed25519 PeerId (either using `createFromPrivKey` or `createEd25519PeerId` from `@libp2p/peer-id-factory` [`^1.0.20`]), called `create` from `ipfs-core`, passing the peerId to `init.privateKey` with `init.algorithm` set to `Ed25519` and passing the `peerId` to `libp2p.peerId`.
When connecting to a node process via swarm, I see encryption errors. (`'ERR_ENCRYPTION_FAILED'` from @chainsafe/libp2p-noise)
With the same setup but a default peerId, I do not see errors and the peers are connecting without issue.

#### Steps to reproduce the error:

See description.

**Comment by SgtPooki** [comment]
Hello @aewing,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. It seems like this may be an issue related to js-ipfs using non-default peerIds.

 However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. There are examples at https://github.com/ipfs-examples/helia-examples and our guide for migrating to helia from js-ipfs can be found at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia or https://github.com/libp2p/js-libp2p repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
