### ISSUE TITLE
Rollup compilation exporting error

### ISSUE THREAD

**Issue by francesco-gaglione** [ipfs/js-ipfs#4271]
- **Version**: 59.0.0
- **Platform**: Windows 10
- **Node version**: v18.12.1

#### Description:
I'm using ipfs-http-client into my custom react components library. In detail I created a .ts script that use the `.create()` method. The library dir structure is this:

```
rootFolder
    |_ src
        |_ web3
            |_ manager
                - index.ts
                - manager.ts
        - index.ts
```

The manager script is this:
```typescript
import { create, IPFSHTTPClient } from 'ipfs-http-client'

class Manager {....}

export default Manager;
```

The `src/web3/manager/index.ts` is this:
```typescript
export { default } from "./manager";
```

And into the `src/index.ts`:
```typescript
....
import Manager from "./web3/manager";

export {
    ....
    Manager,
    ....
}

```

The library is compiled using rollup and these is my configurations:

rollup.config.js
```typescript
import peerDepsExternal from "rollup-plugin-peer-deps-external";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "rollup-plugin-typescript2";
import postcss from "rollup-plugin-postcss";
import copy from "rollup-plugin-copy";

const packageJson = require("./package.json");

export default {
  input: "src/index.ts",
  output: [
    {
      file: packageJson.main,
      format: "cjs",
      sourcemap: true
    },
    {
      file: packageJson.module,
      format: "esm",
      sourcemap: true
    }
  ],
  plugins: [
    peerDepsExternal(),
    resolve({
      browser: true
    }),
    commonjs(),
    typescript({ useTsconfigDeclarationDir: true }),
    postcss(),
    copy({
      targets: [
        {
          src: "src/index.css",
          dest: "build",
          rename: "index.css"
        }
      ]
    })
  ]
};

```

tsconfig.json
```json
{
  "compilerOptions": {
    "rootDir": "src",
    "declaration": true,
    "declarationDir": "build",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"],
  "exclude": [
    "node_modules",
    "build",
    "storybook-static",
    "src/**/*.stories.tsx",
    "src/**/*.test.tsx"
  ]
}

```

package.json
```typescript
{
 ....
 "main": "build/index.js",
  "module": "build/index.esm.js",
  "files": [
    "build"
  ],
"peerDependencies": {
    "@pinata/sdk": "^2.1.0",
    "alchemy-sdk": "^2.2.1",
    "colors": "^1.4.0",
    "ethers": "^5.7.2",
    "ipfs-http-client": "^59.0.0", <- ipfs dependecy
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^4.9.4"
  },
  ....
}

```

I compile the library with `rollup -c` and the build process is ok, the build is done. But, when I try to use this library (both with `npm install /libPath` and `npm install @scope/libname`) into a next.js frontend I have this error:

```
../../projectlib/build/index.js
Module not found: Package path . is not exported from package C:\{path}\projectlib\node_modules\ipfs-http-client (see exports field in  C:\{path}\projectlib\node_modules\ipfs-http-client\package.json)

Import trace for requested module:
../../projectlib/build/index.js
```

Why this error? And how to solve it?

**Comment by pablomendezroyo** [comment]
I have been dealing with a similar issue and finally fix it.

**Error**
```
Module not found: Error: Package path . is not exported from package /home/dappnode/CORE/DNP_DAPPMANAGER/node_modules/ipfs-http-client (see exports field in /home/dappnode/CORE/DNP_DAPPMANAGER/node_modules/ipfs-http-client/package.json)
```

**Versions**
```
"ipfs-http-client": "^59.0.0",
"webpack": "^5.52.0",
```

**My solution**
Change the `module` and `target` fields in the `tsconfig.json` from `commonjs` to `EsNext`. Watch out, this can break other parts of your code
```
{
...
"module": "ESNext",
"target": "ESNext"
...
}
```

**Comment by richtera** [comment]
It looks like things are referring to MODULE/src/.... during import of types but ./src is not in the exports declaration of each module. I am not quite sure where this should be posted or as a new issue, but when using ipfs within a type=module environment each export needs to be mentioned. For example `import { ImportCandidate } from 'ipfs-core-types/src/utils'` should work in spirit, but won't work, if the environment is completely ESM, because the src folder is not exported inside of the package.json. At least that's what I am seeing with the latest versions and I can't switch because of this.
So it looks like ESNext would fix the one but not the other. So you can use the client just fine, but can't import the types from core.

**Comment by SgtPooki** [comment]
Hello @francesco-gaglione, @pablomendezroyo, & @richtera,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. There are examples at https://github.com/ipfs-examples/helia-examples and our guide for migrating to helia from js-ipfs can be found at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
