### ISSUE TITLE
ipfs-core does not connect with peers listed in the bootstrap field of config file

### ISSUE THREAD

**Issue by RebekkalPangras** [ipfs/js-ipfs#4273]
- **Version**:

version : ipfs-core 0.17.0
- **Platform**:

Ubuntu
- **Subsystem**:

#### Description:

I am starting IPFS node programmatically using ipfs-core with custom repository. Have written an implementation of js-datastore following the implementation of js-datastore-s3. The node is started, but it does not connect with the peers mentioned in the bootstrap field of the config file. When tried with 0.15.4, the node connects with peers on startup. But that does not happen for the latest version.

**Comment by 2color** [comment]
@RebekkalPangras

Can you share more reproduction information on how you're setting the bootstrap field and instantiating ipfs?


Also, I recommend checking out the following video to get a bit more insight into debugging the problem: https://youtu.be/sHHJAVVFYAA?t=209

**Comment by SgtPooki** [comment]
Hello @RebekkalPangras,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. There are examples at https://github.com/ipfs-examples/helia-examples and our guide for migrating to helia from js-ipfs can be found at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
