### ISSUE TITLE
ipfs.files.get throws error on multiaddr

### ISSUE THREAD

**Issue by somebody1234** [ipfs/js-ipfs#430]
I'm using `ipfs = new IPFS()` to initialize, and when I use `ipfs.files.get` with a multiaddr it rejects the Promise with `Error: not valid multihash`. I'm not exactly sure what I'm doing wrong.

**Comment by diasdavid** [comment]
You are using it with a `multiaddr` and not a `multihash`?

**Comment by somebody1234** [comment]
Yes

**Comment by diasdavid** [comment]
Ups, its a typo, sorry about that @somebody1234  -- https://github.com/ipfs/interface-ipfs-core/commit/dad7f81e98f2035040a4c50c3b44b1ae2fa0586e

**Comment by somebody1234** [comment]
Okay, how would I get a specific file?

**Comment by somebody1234** [comment]
Also, I'm using the `multihash` format shown in the API and I'm still getting an error saying it's not a valid `multihash`

**Comment by diasdavid** [comment]
@somebody1234 could you provide a snippet on how to reproduce?

**Comment by somebody1234** [comment]
Snippet:

    const IPFS = require('ipfs'),
        ipfs = new IPFS();
    ipfs.files.get('/ipfs/QmNhFJjGcMPqpuYfxL62VVB9528NXqDNMFXiqN5bgFYiZ1', (err, fole) => console.log(file)||file.content.pipe(process.stdout))

**Comment by diasdavid** [comment]
You need to [`init`](https://github.com/ipfs/js-ipfs/blob/master/test/utils/temp-node.js#L32), [`load`](https://github.com/ipfs/js-ipfs/blob/master/test/utils/temp-node.js#L37) and start the node if you would like it to fetch data from other nodes.

One important question, where did you get that hash from?

**Comment by somebody1234** [comment]
It's Neocities' hash, I was using it for testing

**Comment by diasdavid** [comment]
Got it, we don't have both networks connected (yet), so you won't be able to resolve hashes from go-ipfs in js-ipfs. This will change soon.
