### ISSUE TITLE
Missing function in ipfs-core that is in kubo: Getting a list of child blocks that make up a cid

### ISSUE THREAD

**Issue by AwesomeKalin** [ipfs/js-ipfs#4300]
- **Version**:

v0.18.0
- **Platform**:

64-bit Windows 11, Node.js 16.18.1
- **Subsystem**:

#### Severity:

Low-Medium (Depends on what you are doing)
#### Description:

In my code, I need to get all the child blocks of a file. However, ipfs-core doe not contain the functionality necessary to get the blocks that make up a cid. In kubo, there is ipfs ls <cid> which will get all the blocks that make up a cid, but no ipfs-core
#### Steps to reproduce the error:

N/A

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

To list all the CIDs in a block, see [dagPbWalker](https://github.com/ipfs/helia/blob/main/packages/helia/src/utils/dag-walkers.ts#L15-L22).  You will need to call `helia.blockstore.get` with each yielded CID and recursively invoke the DAG walker until you've traversed the entire graph.
