### ISSUE TITLE
Ipfs http client node server connection issue.

### ISSUE THREAD

**Issue by sanjay-del** [ipfs/js-ipfs#4306]
I have a separate ipfs node running created through ipfs core.
This is the config used to create the node
let ipfsConfig: any = {
repo: AppConfig.ipfs.repo,
EXPERIMENTAL: {
pubsub: true,
},
config: {
Bootstrap: ,
Addresses: {
API: “/ip4/0.0.0.0/tcp/5001”,
Swarm: [
“/ip4/0.0.0.0/tcp/4002”,
“/ip4/0.0.0.0/udp/4002/quic”,
“/ip4/0.0.0.0/tcp/4003/ws”,
],
},
},
libp2p: {
connectionProtector: preSharedKey({
psk: swarmKey
})
},
}
It has as event handler via libp2p connectionManager.
If I try to create a simple client server through ipfs-http-client create module connection refused error is being thrown. Is there something I am missing??
Ipfs version 0.66 is being used.

**Comment by SgtPooki** [comment]
Hello @sanjay-del,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. There are examples at https://github.com/ipfs-examples/helia-examples and our guide for migrating to helia from js-ipfs can be found at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
