### ISSUE TITLE
IPFS.create is not working with node 12 version. 

### ISSUE THREAD

**Issue by chaincodedev** [ipfs/js-ipfs#4311]
I am trying to run IPFS version 0.52 version with node version 12 and suddenly it stopped working. IPFS.create function is not showing any errors but it is not working. It just hangs and doesn't even return anything. Please refer to the attached screenshots
![Screenshot from 2023-02-02 22-03-02](https://user-images.githubusercontent.com/25425829/216384699-b717e679-dc36-4996-be3b-e5c1510bebef.png)

Can someone please help me in this.

**Comment by chaincodedev** [comment]
can anyone help me here to solve this issue?

**Comment by achingbrain** [comment]
Please upgrade to LTS node - v18.x at the time of writing.  Node 12 is long unsupported and will not receive security fixes.
