### ISSUE TITLE
 No "exports" main defined  while using Babelrc for Node js 16

### ISSUE THREAD

**Issue by HariApplogiq** [ipfs/js-ipfs#4313]
- **Version**: Node js 16.19

- **Platform**:
MacOS (Big Sur)

#### Severity:
Critical 

#### Description:
 No "exports" main defined  in while running with babelrc 

#### Steps to reproduce the error:
Install Npm i ipfs-core ;
Then try import as Mentioned in npm docs
import * as IPFS from "ipfs-core";

async function loadIpfs(file) {
  // const { create } = await import("ipfs");
  const ipfs = await IPFS.create().catch((e) => {
    throw new ApiError(400, e);
  });
  const { cid } = await ipfs.add(file);
  const data = {
    cid,
    ipfs,
  };

  return data;
}

Error:

node:internal/modules/cjs/loader:499
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/hariganesh/Desktop/Hariganesh/HariBackup/Projects/Crypto-pets/Source/crypto-pets-admin-api/node_modules/ipfs-core/package.json

**Comment by rolandsaven** [comment]
@HariApplogiq does this help? https://github.com/ipfs/js-ipfs/issues/4256

**Comment by SgtPooki** [comment]
Hello @HariApplogiq,

We'd like to inform you that we are currently deprecating js-ipfs. Regarding the issue you raised, it seems to be stale. We recommend trying our other library, helia, to see if it addresses your use case. If helia doesn't resolve the issue, please open a new issue at https://github.com/ipfs/helia.

Thank you!

Best Regards,
@ipfs/helia-dev
