### ISSUE TITLE
The file is broken when using AsyncIterable in addAll .

### ISSUE THREAD

**Issue by jclab-joseph** [ipfs/js-ipfs#4344]
- **Version**: js-ipfs `60.0.0`

```
{
  version: '0.17.0',
  commit: '',
  repo: '12',
  system: 'amd64/linux',
  golang: 'go1.19.1',
  'ipfs-http-client': '1.0.0'
}
```

- **Platform**: `Linux 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

#### Description:

The file is broken on the addAll & wrapWithDirectory & AsyncIterable combination.
It seems to me that the first result of the yield is being ignored, and the second result is being inserted twice.

#### Steps to reproduce the error:

Minimal Reproduce: https://github.com/jclab-joseph/js-ipfs-bug-1

Result:

```
expected hash:  34b3ab5f0bf3a5c304b68fbc9e52be1263087734b6a7b2bdc185647eb402c1b4
{
  path: '1.txt',
  cid: CID(QmYWgUMxqX64PRp3YFaTkLu4sSepgy3uHJQiLxmaJzSA9x),
  size: 8330243
}
{
  path: '2.txt',
  cid: CID(QmSEd2vc9fSiMuR7kWJrRV56eZbzbjfMKbtBiF7WzZrWEy),
  size: 8330243
}
{
  path: '',
  cid: CID(QmRwz7KDSnKq39Bt939afCknChAfvByM5y5yrqwrgRNis8),
  size: 16660590
}
rootCid:  QmRwz7KDSnKq39Bt939afCknChAfvByM5y5yrqwrgRNis8
downloaded hash:  f3a4bad0eafa0fc1ae12bb796da3c23079ae990ade97bda59f76f685c1ae9f5e
```

**Comment by SgtPooki** [comment]
Hello @jclab-joseph,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. Our migration guide is available at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

Specifically, you will want to look into `@helia/unixfs` for the .add, .addAll and other similar functionality. Specifically mentioned in our migration guide at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS#files

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
