### ISSUE TITLE
Use interface-ipfs-core tests for files API over http

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#438]
Uncomment https://github.com/ipfs/js-ipfs/blob/master/test/http-api/interface-ipfs-core-over-ipfs-api/test-files.js#L5-L24 and make it work.

Needs:
- [x] https://github.com/ipfs/js-ipfs/pull/323
- [x] https://github.com/ipfs/js-ipfs/pull/469

**Comment by VictorBjelkholm** [comment]
#323 closed in favor of #469 which includes the interface-ipfs-core changes

**Comment by diasdavid** [comment]
woot! This is done, thank you @VictorBjelkholm et all :D
