### ISSUE TITLE
Use interface-ipfs-core tests for the Swarm API

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#439]
Uncomment https://github.com/ipfs/js-ipfs/blob/master/test/http-api/interface-ipfs-core-over-ipfs-api/test-swarm.js#L5-L23 and make it work.

Needs:

- [x]  https://github.com/ipfs/js-libp2p-ipfs-browser/issues/83

**Comment by diasdavid** [comment]
Ok, since https://github.com/ipfs/go-ipfs/issues/3218, what we needs is to fix the test swarm.connect in interface-ipfs-core to add the peer-id to the end of the multiaddr

**Comment by dignifiedquire** [comment]
@VictorBjelkholm doing this now

**Comment by VictorBjelkholm** [comment]
@dignifiedquire :+1:

**Comment by diasdavid** [comment]
Thank you both :)
