### ISSUE TITLE
Missing requirements in readme

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs#453]
Would be good to include the requirements in the readme, node version, tested OSes, npm version and so on.

**Comment by dignifiedquire** [comment]
Quick list 

- npm@3
- node >= 4
- tested on OS X & linux, expected to work on Windows

**Comment by RichardLitt** [comment]
Should be in the Install section.

**Comment by diasdavid** [comment]
Not anymore :) https://github.com/ipfs/js-ipfs#ipfs-javascript-implementation
