### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#46]
I've started working on this on https://github.com/ipfs/js-ipfs/pull/45, but as the HTTP API is in flux/being written (between a RPC vs REStful discussion), I'm going to defer this until that part is spec.

Whole spec https://github.com/ipfs/specs/pull/65
HTTP API spec - https://github.com/ipfs/api

- add
  - [x] core
    - [x] tests
  - [x] http-api
    - [x] tests
  - [x] cli
    - [x] tests
- rm
  - [x] core
    - [x] tests
  - [x] http-api
    - [x] tests
  - [x] cli
    - [x] tests
- list
  - [x] core
    - [x] tests
  - [x] http-api
    - [x] tests
  - [x] cli
    - [x] tests

**Comment by RichardLitt** [comment]
Ahh, so this is why you've been trying to get the API moving faster. ;)

**Comment by diasdavid** [comment]
It definitely helps everyone. js-ipfs-api and the other client libraries keep getting broken

**Comment by jbenet** [comment]
> but as the HTTP API is in flux/being written (between a RPC vs REStful discussion),

I thought we agreed that it was going to remain as is (a rest like thing) and we would only _add_ a "single endpoint json rpc" api as _another_ thing.

**Comment by diasdavid** [comment]
**This is now complete**
