### ISSUE TITLE
Create pull-multipart module

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#479]
As mentioned in https://github.com/ipfs/js-ipfs/pull/469#discussion_r78388191 we are using pull-streams internally now and would like to have a pull-stream version of the [multipart parser](https://github.com/xicombd/ipfs-multipart). 

cc @xicombd @diasdavid

**Comment by diasdavid** [comment]
Closing this one:
- not a priority
- not needed

**Comment by dignifiedquire** [comment]
Should still happen, so why closing?
