### ISSUE TITLE
[cli] ipfs files add is broken in online mode

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#480]
I don't know why the tests didn't caught this, but running `ipfs files add <file>` throws. The reason is that it uses `.createAddPullStream` which does not exist on the js-ipfs-api only on js-ipfs. 

This is one of the reasons pull-streams need to be added in a sensible way to interface-ipfs-core. For now we will have to fall back to the super inefficient thing of converting to a node-stream, and then back to a pull-stream :/

cc @diasdavid

**Comment by diasdavid** [comment]
> pull-streams need to be added in a sensible way to interface-ipfs-core

Exactly. It seems more like a misunderstanding of interface-ipfs-core, since that is what the CLI should be consuming.
