### ISSUE TITLE
bitswap is 'requesting one block at a time'

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#498]
In an experiment to fetch orbit (700Mb), js-ipfs hung at 650KiB, checking bitswap wantlist showed that bitswap is only requesting a block at a time.

![image](https://cloud.githubusercontent.com/assets/1211152/18570253/5fc48fe0-7b76-11e6-8446-0585f8019117.png)

**Comment by dignifiedquire** [comment]
Working on this, including some fixes need to be made to `files.get`

**Comment by dignifiedquire** [comment]
Short update while I am head down in this:

- Parallelised the block requests in ipfs-unixfs-engine, fixing the original issue mentioned here, that only a single block would be requested at once.
- While testing found a bug in js-ipfs-api, for `get` which resulted in not properly handling more than one or two files. I was able to fix this as well.
- Fixed the code in `cli/commands/files/get.js` to actually store files and directories to disk as expected.
- Now working on actual issues inside bitswap. The current problem is that after receiving some blocks things come to a halt, and it never finishes.

**Comment by dignifiedquire** [comment]
Found some more details. 

- Sometimes js-ipfs will request a hash from go-ipfs that go-ipfs does not know about, even though the whole requested object was added on go-ipfs, so where are those coming from?

**Comment by dignifiedquire** [comment]
Most of the time, it will just stop, with one or two entries in the wantlist and never receive them from go-ipfs, even though the entry is in the wantlist from go

**Comment by dignifiedquire** [comment]
Not a bug in bitswap anymore. For details on interop transfer issues see: https://github.com/libp2p/js-libp2p-spdy/issues/48
