### ISSUE TITLE
block

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#50]
Interact with raw blocks in the datastore. It uses IPFS-repo to store and get blocks

#### To learn more about the Block API, you can

- check out the go impl https://github.com/ipfs/go-ipfs/tree/master/blocks
- read datastore spec https://github.com/ipfs/specs/tree/master/repo#datastore

#### Implementation Roadmap

- [x] ipfs-blocks JavaScript implementation https://github.com/ipfs/js-ipfs-blocks
- jsipfs block get <key>  - Get a raw IPFS block.
  - [x] core
  - [x] http-api
  - [x] cli
- jsipfs block put <data> - Stores input as an IPFS block.
  - [x] core
  - [x] http-api
  - [x] cli
- jsipfs block del <data> - Deletes a stored block.
  - [x] core
  - [x] http-api
  - [x] cli
- jsipfs block stat <key> - Print information of a raw IPFS block.
  - [x] core
  - [x] http-api
  - [x] cli

**Comment by diasdavid** [comment]
need `remove` in [js-ipfs-repo](https://github.com/ipfs/js-ipfs-repo) for `del`

**Comment by diasdavid** [comment]
blocks http-api spec - https://github.com/ipfs/http-api-spec/pull/25

**Comment by RichardLitt** [comment]
Let me know if I can help.

**Comment by RichardLitt** [comment]
Why isn't `del` in go-ipfs?

**Comment by diasdavid** [comment]
@RichardLitt go-ipfs doesn't expose it (yet). But it is what gc does internally. Exposing it is nice for testing and convenience.

**Comment by diasdavid** [comment]
Booooom! :D done, thank @RichardLitt and @xicombd for getting this done ! :D
