### ISSUE TITLE
Interop tests with go-ipfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#505]
Following https://github.com/ipfs/js-ipfs-bitswap/issues/13, we need to have in place interop tests with go that at least do:
- spawn a bunch of nodes
- test swarm
- test bitswap (with small and big files + nested directories)

We can use ipfsd-ctl to fetch go-ipfs and test it in CI. Note: we have to use go-ipfs master due to the changes in spdy that weren't yet released.

**Comment by diasdavid** [comment]
https://github.com/ipfs/js-ipfs/pull/674

**Comment by dignifiedquire** [comment]
Merged
