### ISSUE TITLE
Getting js-ipfs to load in browser

### ISSUE THREAD

**Issue by nikuda** [ipfs/js-ipfs#509]
Issues I've found (so far) that prevent js-ipfs from loading in the browser.
1. `package.json` attribute `main` pointing to a non-existing path
   
   Fixed in https://github.com/ipfs/js-ipfs/pull/508
2. Use of `fs.readFileSync` with `.proto` files.  
   
   Proposed solution https://github.com/ipfs/js-ipfs-merkle-dag/pull/50 would need to be applied to the following libraries:
   - ipfs-bitswap
   - ipfs-merkle-dag
   - ipfs-unixfs
   - libp2p-crypto
   - libp2p-identify
   - libp2p-secio
3. `node-forge` library uses AMD modules which doesn't work with `browserify`
   
   Most severe of the issues, more detail:
   - https://github.com/digitalbazaar/forge/issues/126
   - https://github.com/digitalbazaar/forge/issues/294
   - https://github.com/theoephraim/node-google-spreadsheet/issues/133.
   
   Affected libraries:
   - libp2p-crypto
   - libp2p-identify
   - libp2p-secio

**Comment by diasdavid** [comment]
Hi @nikuda thanks for digging deap into the roots of the problem, really nice sum up, looking forward to see you tinkering with the code too :D 

> 1.

Solved - https://github.com/ipfs/js-ipfs/pull/508

> 2.

We are working on it, however there is one more change that needs to happen, which is changing libp2p-ipfs to libp2p-ipfs-browser, they offer the same API, but need to be replace for in browser used, this is currently achieved through the build process.

> 3. 

We are working on stop using node-forge, although we hoped it became CommonJS -- https://github.com/libp2p/js-peer-id/issues/5 -- 

Follow - https://github.com/ipfs/js-ipfs/pull/508

**Comment by nikuda** [comment]
Not a problem ☺️  @diasdavid 

>change that needs to happen, which is changing libp2p-ipfs to libp2p-ipfs-browser

Are there any issues/PRs open that relate to changes that need to happen here?

>We are working on stop using node-forge

Have you considered any alternatives? Maybe native browser WebCrypto API could do the job? https://diafygi.github.io/webcrypto-examples/

These two libraries also look good. They both seem to be under 10Kb minified which is a lot better than `node-forge` 100Kb+. The size of `js-ipfs` is a bit of a concern, it's coming in at 500Kb+ minified for me.

* https://github.com/dchest/tweetnacl-js
* https://github.com/bitwiseshiftleft/sjcl

**Comment by diasdavid** [comment]
> change that needs to happen, which is changing libp2p-ipfs to libp2p-ipfs-browser
Are there any issues/PRs open that relate to changes that need to happen here?

That is just how it works, libp2p-ipfs is the libp2p build that has the transports for Node.js (TCP, WebSockets, UTP, libp2p-ipfs-browser is the build with the transports for Browser (WebRTC + WebSockets).

In the near future, Routing will be added (DHT) and that will behave interally different in the browser and in Node.js.

> Have you considered any alternatives? Maybe native browser WebCrypto API could do the job? https://diafygi.github.io/webcrypto-examples/

If you go through https://github.com/ipfs/js-ipfs/pull/485, you'll see that is what we are doing :) 

> These two libraries also look good. They both seem to be under 10Kb minified which is a lot better than node-forge 100Kb+.

We have had some discussions (https://github.com/diasdavid/webcrypto/issues/1), but we ended up picking node-forge in the beginning because it had the primitives we needed.

**Comment by dignifiedquire** [comment]
@nikuda all of this work is pretty much done, it was one of the things I have been working on in the last weeks, see #485 for a list of PRs that 
- do switch all crypto webcrypto in the browser where possible
- remove the use of `fs` in the browser
- use the `browser` field to map things like `libp2p-ipfs`t o `libp2p-ipfs-browser` in an independent way

**Comment by nikuda** [comment]
>If you go through #485, you'll see that is what we are doing :)

Ah the ref to #485 was missing before. Thanks!

>all of this work is pretty much done

Great! 🏆 It seems libp2p/js-libp2p-crypto#10 has been supplanted by libp2p/js-libp2p-crypto#12 which most of the other PRs rely on. I noticed that the PR has the backlog tag, is there anything I can help with it to get it merged in sooner?

**Comment by dignifiedquire** [comment]
> . I noticed that the PR has the backlog tag, is there anything I can help with it to get it merged in sooner?

The `backlog` currently just means that it is not part of a specific milestone. I am trying to get it merged as soon as possible, as it will be very painful to keep these PRs up to date across all the repos if too much happens. 

If you want to help out, I've added a `TODO` list of things that need to be done at the top of https://github.com/ipfs/js-ipfs/pull/485. The current next step is to replace `multihashing` with `multihashing-async` on all PRs that depend on it.

**Comment by dignifiedquire** [comment]
> It seems libp2p/js-libp2p-crypto#10 has been supplanted by libp2p/js-libp2p-crypto#12 which most of the other PRs rely on.

Yes, just updated the reference.

**Comment by nikuda** [comment]
>The current next step is to replace multihashing with multihashing-async on all PRs that depend on it.

Seems easy enough https://github.com/libp2p/js-libp2p-crypto/compare/webcrypto...nikuda:webcrypto

Progress:

- [x] libp2p/js-libp2p-crypto

**Comment by dignifiedquire** [comment]
Thanks @nikuda, most of these pull it in as an indirect dependency. I just updated the issue with a better overview table of ALL THE PRs 😉

**Comment by diasdavid** [comment]
Hi @nikuda js-ipfs 0.18.0 has been released and it includes all of the changes of the async crypto PR https://github.com/ipfs/js-ipfs/pull/485 🎉 

These should be all problems of the past, try it out :D

**Comment by nikuda** [comment]
Good stuff @diasdavid! Will try it soon :)

**Comment by diasdavid** [comment]
also, check out the examples folder: https://github.com/ipfs/js-ipfs/tree/master/examples

**Comment by nikuda** [comment]
All working @diasdavid. 👍

**Comment by nikuda** [comment]
Spoke too soon.

In `bundle-browserify` example `node.load()` fails with an unhandled rejection. The problem seems to be around the `dexie` indexedDB library. I'll open up a new issue when I get have more info.

**Comment by nikuda** [comment]
Fixed the issue in https://github.com/libp2p/js-libp2p-crypto/pull/47. 

Now the node  in `bundle-browserify` example initialises successfully with a 'IPFS node is ready' message – although no peers seem to connect.

**Comment by diasdavid** [comment]
thank you @nikuda !! :)
