### ISSUE TITLE
js-IPFS API stopped working'Access-Control-Allow-Origin' on code that was previously working

### ISSUE THREAD

**Issue by stuffyvater** [ipfs/js-ipfs#512]
Hi I'm working on a demo to show how users can share a file between each other with a smart contract using Ethereum, Meta Mask and IPFS. @miista and I are working on this and both had a stable version working before Devcon that 
1. could create a contract, 
2. whitelist stakeholders, 
3.. send the hash of a file uploaded with the IPFS API to whitelisted stakeholders.
We ran into a bug in MetaMask and got a lot of help there, but appearantly IPFS is also not responding ( we fairly certain it is not related to the MetaMask update )

When uploading files the API does not seem to be responding
![image](https://cloud.githubusercontent.com/assets/11940919/19115848/bb1cb3ca-8b13-11e6-8d0a-ed0748de1a2d.png)

![image](https://cloud.githubusercontent.com/assets/11940919/19115865/c7fd1d78-8b13-11e6-9200-730283403885.png)

This is the code in the contract that implements the IPFS API
```
  var file = files[0];
        var reader = new FileReader();

        reader.readAsText(file);
        // If we use onloadend, we need to check the readyState.
        reader.onloadend = function(evt) {
            var i = IpfsApi("/ip4/127.0.0.1/tcp/5001");
            i.add(i.Buffer(reader.result), function (err, res){
                if(err || !res)
                  return console.error("ipfs add error", err, res);

                var storedDoc = res[0];
                var fingerprint = storedDoc.hash;

                $("#hashResult").show();
                $("#hashResult").html(fingerprint);
                console.log("fingerprint: "+ fingerprint);
                contract = web3.eth.contract(abi);

                var contractAddress = $("#contractAddress1").val();
                evt.preventDefault();
                var contractInstance = contract.at(contractAddress);

                contractInstance.amendDocument(1234, fingerprint, {from: web3.eth.coinbase, gas: 1000000}, function(e,r){
                  if(e){
                      alert("An error occurred: " + e);
                  }
                  else {
                      if(r){
                          console.log("The document has been uploaded (fingerprint: " + fingerprint + ")");
                      }
                      console.log(r);
                  }
                });
            });
        };
      })
    });
```
Here's the demo html. 

https://github.com/stuffyvater/M-rskG2/blob/metamask-bug/mm1.html

Did something change with the js-IPFS after Devcon ? Thanks in advance!

**Comment by nycoliver** [comment]
Did you try https://github.com/ipfs/js-ipfs-api#cors?

**Comment by stuffyvater** [comment]
Hi. Thanks for answering:

ipfs config --json API.HTTPHeader.Access-Control-Allow-Origin "[\"http:localhost:3000/mm1.html\"]"
Error: Failed to get config value: API key has no attributes

**Comment by stuffyvater** [comment]
i am running ver 0.3.12 and unable to update:

´Error: %!s(MISSING) not installed.´

**Comment by lgierth** [comment]
@stuffyvater please update to v0.4.3 -- what you're running is ancient and hasn't been supported for half a year.

**Comment by lgierth** [comment]
> `Error: %!s(MISSING) not installed.`

This error is likely because v0.3.12 didn't have the `ipfs config` command or so.

**Comment by dignifiedquire** [comment]
@stuffyvater also make sure to use the latest version of js-ipfs-api.

**Comment by stuffyvater** [comment]
hi thanks for the answers. If i cannot use the ipfs update cl how do i then update (sorry if this is a stupid question I am not experienced with linux, but am using it because it makes everything else easier :-)

**Comment by Kubuxu** [comment]
You can download binary distribution at https://dist.ipfs.io/#go-ipfs

**Comment by stuffyvater** [comment]
It works! despite being old
 ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://localhost:3000"]'
First answer was right.. I didn't have the access control set properly.. Being dumb sure is hard work! Thank you for all your help :-) !
