### ISSUE TITLE
Opening sequence in node or browser?

### ISSUE THREAD

**Issue by compsocial** [ipfs/js-ipfs#513]
I'm just getting started and I apologize for the beginner's question: What sequence of steps is necessary to get a functional ipfs instance running in Node and/or (but hopefully and) the browser? I can do the following: 

var IPFS = require('ipfs')
var node = new IPFS()

as in README, but after that ... I'm not sure. I've been reading through the Orbit code, but from what I can tell it's connecting to a daemon running locally.

Can someone share a set of initialization steps ending with adding or getting a file? Would be nice to add that to the guide.

**Comment by interfect** [comment]
In Node at least it looks like you can crib some initialization from https://github.com/ipfs/js-ipfs/blob/c8dbf6ba16017103b29589bb6d4173f954b4325f/src/http-api/index.js where an IPFS node gets set up as part of the HTTP API setup.

**Comment by diasdavid** [comment]
Hey @compsocial, sorry for the delay, meanwhile we shipped examples to help people get started, hope they help, find them here: -> https://github.com/ipfs/js-ipfs/tree/master/examples

Let me know if you find any trouble :)
