### ISSUE TITLE
Force option to init not respected

### ISSUE THREAD

**Issue by interfect** [ipfs/js-ipfs#515]
I'm passing `{force: true}` in the `options` for the `init` method on the `IPFS` class, and it's still complaining that the repo already exists.

It looks like [the force option isn't actually checked](https://github.com/ipfs/js-ipfs/blob/a07f16e3b09001d3a88b4b78b9dcab0d5826abb4/src/core/components/init.js#L38) despite it being [passed in from the front end](https://github.com/ipfs/js-ipfs/blob/a07f16e3b09001d3a88b4b78b9dcab0d5826abb4/src/cli/commands/init.js#L46) when `-f` is specified. So there's no way to clobber an existing repo.

**Comment by diasdavid** [comment]
An update on this: We long removed the option for 'force init' in go-ipfs and with that, we also removed it from js-ipfs, we should take it out from documentation/examples.

However, I do understand that cleaning a repo in the browser is painful, far from just `rm -rf`, which makes me think that there should be a repo-clean utility.

**Comment by diasdavid** [comment]
I've removed this from everywhere, as this is not really an option anymore. Apologies for the confusion!
