### ISSUE TITLE
feat: expose Buffer on the dist version

### ISSUE THREAD

**Issue by interfect** [ipfs/js-ipfs#523]
According to [the API spec](https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#javascript---ipfsfilesadddata-callback), you're supposed to pass a node `Buffer`, a node `Readable` stream, or an object containing one of those to the `ipfs.files.add` method. However, this project advertises the ability to use the implementation by including a `<script>` tag: 

```
<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>
```

If you do include that tag, you get a global `Ipfs` object, and you can indeed start up a node and go online. But since in the global namespace there is no `Buffer` or `Readable` stream implementation, what are you supposed to pass to `ipfs.files.add`? It would seem to be requiring types that can't be created outside it's fancy webpack module that hides all the node globals.

**Comment by diasdavid** [comment]
@interfect fair point. Would you like to submit a PR that exposes Buffer under `ipfs.Buffer`, so that it doesn't force users to bundle Buffer as a separate blob?

**Comment by diasdavid** [comment]
since it is being handled here: https://github.com/ipfs/js-ipfs/pull/525
closing this issue :)
