### ISSUE TITLE
monorepo?

### ISSUE THREAD

**Issue by heavyk** [ipfs/js-ipfs#533]
as I've begun to use js-ipfs more and more, one of the majorly annoying things is how many different repos there are. I understand that it's good to separate things out to remove duplication and stuff (you don't have to sell me on the advantages of having a module that does only one thing and does it well -- I'm already convinced of this) however, much like babel, there is so much interconnectedness between modules -- in order to get a new thing working, various PRs need to be made across multiple repositories -- and, consequently, all of the PRs must be merged at around the same time, and any one of them could leave things in an unworking state.

https://github.com/babel/babel/blob/master/doc/design/monorepo.md

in that article, it mentions the pros:

 - *Single lint, build, test and release process.*
 - *Easy to coordinate changes across modules.*
 - Single place to report issues.
 - *Easier to setup a development environment.*
 - *Tests across modules are ran together which finds bugs that touch multiple modules easier.*

anyway just a thought... however, if a monorepo is decided against, it would be nice to have some sort of script which checks out all relevant repos and links them all together to make it easier to get a dev environment setup

**Comment by VictorBjelkholm** [comment]
Thanks for the feedback! It has come up before, so it'll be good if we continue the discussion over here: https://github.com/ipfs/community/issues/174

**Comment by heavyk** [comment]
ah! my apologies! I didn't know it'd come up before...

dang, well it'd be cool if github could search for issues in all related repos as well. :/ lol

**Comment by VictorBjelkholm** [comment]
@heavyk you can search across organizations ;)

`org:ipfs is:issue monorepo`

https://github.com/search?utf8=%E2%9C%93&q=org%3Aipfs+is%3Aissue+monorepo&type=Issues&ref=searchresults

Might help in the future!
