### ISSUE TITLE
fix build on nodejs stable - update hapi when it is released

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#541]
`os.tmpDir` was deprecated in favor of `os.tmpdir`, resulting in failing tests on CI as we are checking  against console output in our tests.

see https://travis-ci.org/ipfs/js-ipfs/jobs/170467892

**Comment by VictorBjelkholm** [comment]
Not sure a deprecation warning should break are tests here, but I do agree we should change it.

The error is a bit weird though.

```AssertionError: expected '(node:3832) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.' to deeply equal ''```

Why would we check that the output is "deeply equal" to empty string? Not sure if it's the test cases that are bad, or just printing of the error, but something is wrong here.

**Comment by dignifiedquire** [comment]
@VictorBjelkholm the checks do make sense as it is testing the cli interface and checking stdout is the way to do it. Similar many of the sharness tests will run into this.

**Comment by VictorBjelkholm** [comment]
@dignifiedquire checking that there is no output doesn't feel like a very stable way of testing a CLI. Maybe we could turn on verbose/debug output and make assertions on that?

**Comment by diasdavid** [comment]
@VictorBjelkholm the other we test it is with sharness, any other way you would recommend?

**Comment by diasdavid** [comment]
I'm trying to see where the `os.tmpdir` is being called? But the [Silver Searcher](http://geoff.greer.fm/ag/) is not [saving this world from getting devoured](https://en.wikipedia.org/wiki/Silver_Surfer)

**Comment by dignifiedquire** [comment]
Fixed but not released in hapijs: https://github.com/hapijs/hapi/pull/3368

**Comment by diasdavid** [comment]
-> https://github.com/ipfs/js-ipfs/pull/603
