### ISSUE TITLE
Change introduction text when doing `jsipfs init`

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs#572]
Today, when running `jsipfs init`, you get the following message:

```shell
initializing ipfs node at /Users/phil/.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmeLtmb2QUkm5DAVZKANV7YydAFBP6ATiZATD1UzvhAwYE
to get started, enter:

     jsipfs files cat /ipfs/QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC/readme
```

But that command will not work because subfiles are not implemented yet (https://github.com/ipfs/js-ipfs/issues/478)

In the meantime, we should change the hash to point directly to the file (instead of hash/file it should just be hash), to prevent more confusion from this.

**Comment by chovy** [comment]
Is there a working command I can run to test it?

**Comment by diasdavid** [comment]
I've done this :)

@chovy `npm i ipfs -g && jsipfs init && jsipfs daemon` should get you rolling :)
