### ISSUE TITLE
object

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#58]
The object API enables IPFS users to create graph structures with IPFS were links are MerkleLinks (multihashes)

#### To learn more about the object API, you can

- check go implementation of the MerkleDAG https://github.com/ipfs/go-ipfs/tree/master/merkledag
- check the MerkleDAG spec https://github.com/ipfs/specs/tree/master/merkledag
- see the http-api spec for the object API https://github.com/ipfs/http-api-spec/pull/32

#### Implementation Roadmap

- [x] MerkleDAG JS implementation https://github.com/vijayee/js-ipfs-merkle-dag
- [x] jsipfs object new [template] - Creates a new object from an ipfs template.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object get <key>        - Get and serialize the DAG node named by <key>.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object put <data>       - Stores input as a DAG object, outputs its key.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object stat <key>       - Get stats for the DAG node named by <key>.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object data <key>       - Outputs the raw bytes in an IPFS object.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object links <key>      - Outputs the links pointed to by the specified object.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object patch append-data <root> <data>    - Append data to the data segment of a dag node.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object patch add-link <root> <name> <ref> - Add a link to a given object.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object patch rm-link <root> <link>        - Remove a link from an object.
  - [x] core
  - [x] http-api
  - [x] cli
- [x] jsipfs object patch set-data <root> <data>       - Set data field of an ipfs object.
  - [x] core
  - [x] http-api
  - [x] cli

**Comment by diasdavid** [comment]
**updated this issue**

**Comment by xicombd** [comment]
Started working on this on [feature/object](https://github.com/ipfs/js-ipfs/tree/feature/object) branch :)

**Comment by diasdavid** [comment]
@xicombd :+1: :D

**Comment by xicombd** [comment]
Started working on the object patch commands on the [feature/object-patch](https://github.com/ipfs/js-ipfs/tree/feature/object-patch)

Their spec is now available at https://github.com/ipfs/http-api-spec/pull/68 \o/

**Comment by RichardLitt** [comment]
Woo! Thanks @xicombd!
