### ISSUE TITLE
track: `Pinning`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#59]
The pin command let's you control what hashes (blocks) are not garbage collected, meaning that they are not removed unless you specifically tell the IPFS node to do so.
#### To learn more about the pinning, you can
- check go implementation https://github.com/ipfs/go-ipfs/tree/master/pin
#### Implementation Roadmap
- [x] complemente core object implementation https://github.com/ipfs/js-ipfs/issues/58
- [ ] jsipfs pin add <ipfs-path>...  - Pins objects to local storage.
- [ ] jsipfs pin rm <ipfs-path>...   - Removes the pinned object from local storage. (By default, recursively. Use -r=false for direct pins).
- [ ] jsipfs pin ls [<ipfs-path>]... - List objects pinned to local storage.

**Comment by diasdavid** [comment]
**Updated this issue**

**Comment by AdamStone** [comment]
Hi, really interested in the possibilities of fully browser-based IPFS apps so I wanted to try to contribute. I started a pin implementation [here](https://github.com/AdamStone/js-ipfs/tree/feature/pin). Let me know if you see any obvious problems with what I have so far, I'm basically trying to figure out the infrastructure as I go. Thanks!

**Comment by diasdavid** [comment]
Hi @AdamStone , welcome! :D 

My apologies for the time to reply, wanted to get back to you faster. This is great, thank you for contributing! Pinning is one of the things it would be really nice to have for the js-ipfs milesone 1 :):)

It would really help the process if you could submit a PR, making it very obvious what code you have changed (and also CI will run the tests per commit). Would you mind working in that way?

**Comment by AdamStone** [comment]
Sure, no problem.

**Comment by diasdavid** [comment]
The whole endeavour is happening on https://github.com/ipfs/js-ipfs/pull/107
