### ISSUE TITLE
Create examples of how to use js-ipfs with browserify and WebPack

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#598]
ref: https://github.com/ipfs/js-ipfs/issues/429#issuecomment-260361076

**Comment by diasdavid** [comment]
we have examples now wooot! https://github.com/ipfs/js-ipfs-api/tree/master/examples

**Comment by VictorBjelkholm** [comment]
Wait a minute @diasdavid, now you're confusing js-ipfs and js-ipfs-api :dancer:

**Comment by diasdavid** [comment]
ahaha the url xor didn't come through (https://github.com/ipfs/js-ipfs-api/issues/428) thank you for catching

**Comment by diasdavid** [comment]
Aaaand they are there :) https://github.com/ipfs/js-ipfs/tree/master/examples
