### ISSUE TITLE
Signalling Server for WebRTC-Star - https://star-signal.cloud.ipfs.team/

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#614]
Now, that we have WebRTC support both in the browser (Chrome + Firefox) and Nodejs in libp2p-webrtc-star, it becomes interesting and useful to have a signalling server hosted by us that IPFS developers can rely on for their tinkering with IPFS, of course, the option to choose which signalling server to use still relies on the user, but for demos and quick hacks, this can be extremely useful.

The need for a hosted signalling server will be obliviated once IPFS does relay.

The tricky bit is that in order for a WebSockets connection to happen within a WebApplication that is being served behind HTTPS, the WebSockets, even if within a different domain, needs to be hosted behind HTTPS as well, which makes us do a little bit more work in order to host this signalling server, namely:

- [x] Support for WebSockets Secure (HTTPS) in libp2p-webrtc-star https://github.com/libp2p/js-libp2p-webrtc-star - issue https://github.com/libp2p/js-libp2p-webrtc-star/issues/36
- [x] Once a TLS is supported, the multiaddr will have to point to a DNS name instead of just an IP, meaning that we need DNS support in multiaddr //cc @lgierth 
- [x] Host the signalling server

**Comment by lgierth** [comment]
(I can't find the other issue you're keeping about this one.)

If you wanna be a real protocolian hero, you integrate [siimon/prom-client](https://github.com/siimon/prom-client) and make one or two metrics, e.g. number of signallings done :tulip: 

This is *not critical from the start* but monitoring is generally super useful.

**Comment by diasdavid** [comment]
Update

- We have a signalling server behind a static IP
- If we get DNS support in multiaddr, we don't need TLS anymore because then I can just use webrtc-connect (and bypass WSS all together, which is pretty sweet btw!)

**Comment by dignifiedquire** [comment]
@diasdavid what's that ip?

**Comment by diasdavid** [comment]
Logged here: https://github.com/libp2p/js-libp2p-webrtc-star#hosted-signalling-server

**Comment by diasdavid** [comment]
We now have a hosted Signalling Server available and it is behind https too! :D 

See everything here: https://github.com/libp2p/js-libp2p-webrtc-star#hosted-signalling-server

Last TASK:
- [ ] Document this stuff in js-ipfs README

**Comment by lgierth** [comment]
It would be reaaalllly useful if the signalling server exported metrics for prometheus. At the latest when we promote it to a domain under libp2p.io.

**Comment by AquiGorka** [comment]
Is there a way to execute the `star-signal` server with `ssl` from the cli?
