### ISSUE TITLE
Question: how to create a file hash

### ISSUE THREAD

**Issue by jcalfee** [ipfs/js-ipfs#641]
Could you please direct me to the code or spec on how to create the IPFS file hash?

Looks like it is not as simple has encoding the sha256 in a multi-hash sha2-256.  Here is my first try:  http://stackoverflow.com/questions/40998621/how-to-create-an-ipfs-compatible-multihash

thank you..

**Comment by diasdavid** [comment]
@jcalfee answered to your question. For future questions, please open issues at https://github.com/ipfs/faq or https://github.com/ipfs/support
