### ISSUE TITLE
Change default ports back to the ones from go-ipfs

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#653]
@diasdavid changed these in https://github.com/ipfs/js-ipfs/commit/a355c9e23ed252a7c2405b00d8a75104b242a645 which breaks tooling which works with the default ports. 

> Changing those defaults means that all tools that use go-ipfs default ports fail with js-ipfs now. I was just trying my benchmark setup and it doesn't work anymore because the js-ipfs ports suddenly changed.
> 
> Most users will not want to run go-ipfs and js-ipfs side by side, but it's much more probably that they want to run either one with the same tools that expect the api on the same port. So I don't think it's good to change these defaults at all.

**Comment by diasdavid** [comment]
I've added a note to the README https://github.com/ipfs/js-ipfs/commit/1af30c1a1ce972bd47e02ea3d0609d48071afef2 as discussed on the commit:

https://github.com/ipfs/js-ipfs/commit/a355c9e23ed252a7c2405b00d8a75104b242a645

> It was a huge pain to handle to change the IPFS repo every single time, it made demos look less smoth and make people that did jsipfs init confused why it is messing with their goipfs init.
> I'll add a note of the default values of jsipfs to the README.
