### ISSUE TITLE
jsipfs ls?

### ISSUE THREAD

**Issue by yxliang01** [ipfs/js-ipfs#689]
I am looking for jsipfs ls. But, it seems like it's not implemented yet. Hope that it's going to be implemented soon. Thanks.

**Comment by VictorBjelkholm** [comment]
Yeah, it's a part of the files + mfs API that you can track over here: https://github.com/ipfs/js-ipfs/issues/60

If you hit the "Subscribe" button on the right under "Notifications", you'll get notified when there are any updates.
