### ISSUE TITLE
No routes for HTTP Gateway

### ISSUE THREAD

**Issue by harshjv** [ipfs/js-ipfs#693]
Currently, HTTP gateway has no routes so even if `daemon` is listening to `9090` isn't useful.

    Gateway (readonly) is listening on: http://127.0.0.1:9090

Is there any progress on this part? I would like to help in implementing gateway functionality for `js-ipfs`

**Comment by diasdavid** [comment]
Hi @harshjv, we haven't made any development with regards to the IPFS gateway in js-ipfs, however, a lot of the groundwork is done for the HTTP API, which shares a lot of the same endpoints with the gateway.

Having the HTTP Gateway in the JS implementation is not a core priority, so it might take a while until we take a stab at it, however, if you are available, that would be awesome and I'm happy to provide all the feedback you might need :)

**Comment by harshjv** [comment]
Hey @diasdavid I can help in this issue as currently, I am using `js-ipfs` for [Buffet (Cross platform IPFS application with built-in managed IPFS-node)](https://github.com/harshjv/buffet) and in that, I've already implemented file `cat/get` gateway functionality with directory node browsing and mime-type support.

It can also add files with `wrap-with-directory` option (using empty buffer for parent directory)

It would be great if you can review these two files (and related other project files), and let me know if everything looks good to you so that I can port it to `js-ipfs`.

https://github.com/harshjv/buffet/blob/master/app/gateway/routes.js
https://github.com/harshjv/buffet/blob/master/app/utils/ipfs.js

Cheers 🍻

**Comment by diasdavid** [comment]
Overall LGTM, but it will get more review as it will be easier once there is a PR against js-ipfs :)

**Comment by harshjv** [comment]
Cool then. I'll send a PR soon :)

**Comment by harshjv** [comment]
@diasdavid Hey, I've sent a PR #698 for this. :)

**Comment by diasdavid** [comment]
Let's continue the discussion on your PR #698, @harshjv :)
