### ISSUE TITLE
No peers and addresses

### ISSUE THREAD

**Issue by harshjv** [ipfs/js-ipfs#694]
`ipfs.swarm.peers` and `ipfs.swarm.addrs` return empty array.

    ipfs.swarm.peers((err, peerInfos) => console.log(peerInfos)) // []
    ipfs.swarm.addrs((err, peerInfos) => console.log(peerInfos)) // []

Tried to do NAT with UPNP random public port, but still didn't work.

    {
      "Addresses": {
        "Swarm": [
          "/ip4/0.0.0.0/tcp/4002",
          "/ip4/192.168.0.3/tcp/4002",
          "/ip4/<my_public_ip>/tcp/4002"  // mapped 4002 -> some random public port
        ],
        // ...

**Comment by diasdavid** [comment]
@harshjv That is because js-ipfs doesn't pack libp2p-dht yet, you have to manually dial or use `libp2p-webrtc-star`  which offers some discovery functionality.

**Comment by diasdavid** [comment]
Hope the answer was clear enough, let me know if you have any other question :) 

Be sure to check out our latest examples:
- https://github.com/ipfs/js-ipfs/pull/714
- https://github.com/ipfs/js-ipfs/pull/716

**Comment by ido-ran** [comment]
From walking through the code it looks like `js-ipfs` still doesn't have DHT and support only WebSocket. If that is the case it means it cannot connect to command line daemon?
