### ISSUE TITLE
wrap-with-directory option approach

### ISSUE THREAD

**Issue by harshjv** [ipfs/js-ipfs#696]
I was wondering if I were to implement `wrap-with-directory` option, is it a good approach to append a wrapper parent directory before adding it to preserve file name and implement `ipfs add --wrap-with-directory` option for `js-ipfs`?

### Example

    jsipfs add --wrap-with-directory /some/dir/example.jpg

### Approach

    node.files.add([
      {
        path: `/wrapper/example.jpg`,
        content: fs.createReadStream('/some/dir/example.jpg')
      }
    ], (err, data) => {
      if (err) throw err

      const directoryHash = data[0].hash
      const fileHash = data[1].hash

      console.log(`added ${fileHash} example.jpg`)
      console.log(`added ${directoryHash}`)
    })

### Output

    added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH example.jpg
    added QmaG4FuMqEBnQNn3C8XJ5bpW8kLs7zq2ZXgHptJHbKDDVx

If this looks good, I can send a PR for `--wrap-with-directory`

**Comment by diasdavid** [comment]
@harshjv it is indeed! I've no idea why it took me so much to review this issue. Go ahead with the PR :)

**Comment by harshjv** [comment]
@diasdavid done. https://github.com/ipfs/js-ipfs/pull/798

**Comment by diasdavid** [comment]
Thank you so much @harshjv :) I've already using it today!
