### ISSUE TITLE
Add /ip6 addresses to bootstrap

### ISSUE THREAD

**Issue by lgierth** [ipfs/js-ipfs#706]
Same as https://github.com/ipfs/go-ipfs/pull/3523

Related to https://github.com/ipfs/infrastructure/issues/191

**Comment by diasdavid** [comment]
You are welcome to get a PR in :) Will gladly take it

**Comment by diasdavid** [comment]
ping @lgierth :)

**Comment by lgierth** [comment]
Wbe great if someone else could take it on

**Comment by paulogr** [comment]
Hey, I would like to help.
I using IPFS for a while now, but new diving into code.

I think is there I have to change, right?
 https://github.com/ipfs/js-ipfs/blob/d16a129956bfce191dbfce48c92f99a9717feeaf/src/core/runtime/config-nodejs.json#L19

May I copy the ipv6 entries from @lgierth PR?

Thank you!

**Comment by diasdavid** [comment]
@paulogr exactly :)
