### ISSUE TITLE
Clarify purpose & status of js-ipfs in Readme & Roadmap

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/js-ipfs#710]
This question came up on discourse. Is there anything we can change in the Readme and/or in the Roadmap to make it easier for someone like martha to find the answer to those questions?

http://ipfs.trydiscourse.com/t/what-is-ipfs-js-js-ipfs/70

> IPFS implementation is in Go, right? What's the reason and purpose or re-implementing all of it in javascript?
> [...]
> does this mean that I (the website developer) can use any IPFS URI, and the user (browser) will retrieve the file from IPFS instead of from my HTTP server? How does this work on the client side, technically speaking? Does the user need to have a local running IPFS node, and the ipfs.js somehow magically connects to it?

**Comment by diasdavid** [comment]
Answered here:
- https://github.com/ipfs/faq/issues/97

Other related questions/issues:
- https://github.com/ipfs/faq/issues/180
- https://github.com/ipfs/faq/issues/60
- https://github.com/ipfs/specs/issues/145
