### ISSUE TITLE
js/go interop not working

### ISSUE THREAD

**Issue by dryajov** [ipfs/js-ipfs#718]
I've been trying to get ipfs-go and js-ipfs to work together, but so far I haven't been able to. Here is what I've done:

(I'm on a Mac book pro version 10.11.6 (15G1212))

- run the ipfs go daemon
- run the ipfs js daemon
- add a file in ipfs go (`ipfs add hello.txt`)
- cat a file in ipfs js (`jsipfs cat <hash of file>`)

After hanging for close to 1 minute jsipfs crashes with:

```
/Users/m90570/.nvm/versions/node/v6.5.0/lib/node_modules/ipfs/src/cli/commands/files/cat.js:27
        throw err
        ^

Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

From what I understand, interop has been implemented and it is working, has it not been released or is this is bug?

What I'm trying to accomplish is running IPFS inside a service worker and proxying requests over to IPFS to bootstrap a web app (almost) completely over IPFS #127.

**Comment by dignifiedquire** [comment]
What version of go-ipfs are you using? Interop is currently only working with `master`, not with `0.4.4`. Also you need to manually connect the two instances via `swarm connect <id>`

**Comment by dryajov** [comment]
Here are the versions.

```
$ ipfs --version
ipfs version 0.4.4
```

```
$ jsipfs version
js-ipfs version: 0.21.0
```

That must be the issue. 

Also, do I have to connect both as in:

`ipfs swarm connect <js ipfs id>`
`jsipfs swarm connect <go ipfs id>`

**Comment by diasdavid** [comment]
@dryajov you just need to connect one of the sides and you have to use a valid multiaddr (not just the Id).

The reason why they don't connect to each other is because of this: https://github.com/libp2p/go-libp2p/issues/176

You will find some issues with larger files from js to go, due to https://github.com/libp2p/js-libp2p-spdy/issues/48. We are putting a lot of energy into solving this issue, expect for updates soon.

**Comment by dryajov** [comment]
Thanks @diasdavid. 

I was able to get the go and js implementations to talk to each other, I also ran in the the file limit issue. Thanks for pointing this out. 

I'll file separate bugs for it, but so far the issues I've ran into trying to run `ipfs` in a `ServiceWorker` are related to the WebCrypto API, which are being looked up in the `window` global object explicitly, however `window` is not defined inside a service worker, although it does expose the `crypto` API as a `WebWorker` global, my solution so far has been to remove the explicit `window` lookup. I think in the context of the browser it should be pretty safe to just do `if(crypto)/if(typeof crypto !== 'undefined')`, rather than relying on `window` explicitly. Also, this is helpful #720 👍

**Comment by dignifiedquire** [comment]
re webcrypto there was some work regarding this done already

- https://github.com/dignifiedquire/webcrypto-shim/pull/1
- https://github.com/libp2p/js-libp2p-crypto/pull/59

**Comment by diasdavid** [comment]
Also, keep an eye on: 

- https://github.com/ipfs/js-ipfs/pull/716
- https://github.com/ipfs/js-ipfs/pull/714

They will be complete tutorials on how to get everything to work smoothly :)

**Comment by dryajov** [comment]
@dignifiedquire Yep... that should take care of it, thanks.

**Comment by dignifiedquire** [comment]
@dryajov `master` now is now transferring files with go-ipfs `0.4.6-rc.1` happily if you enable multiplex. Can we close this issue?

**Comment by dryajov** [comment]
Yep, closing.

**Comment by diasdavid** [comment]
![](https://media.giphy.com/media/5xJIIRPC23yZG/giphy.gif)
