### ISSUE TITLE
Solving the Stream Muxer interoperability between Go and JS implementations

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#721]
> I'm creating this issue to keep track of all the work that has been put towards this endeavour, as it is becoming harder to have a clear picture of what is left.

- Available Stream Muxers
  - js-libp2p-multiplex
  - js-libp2p-spdy
  - spdystream (Go) - equivalent to js-libp2p-spdy
  - yamux (Go)
  - muxado (Go)
  - go-multiplex (Go) - equivalent to js-libp2p-multiplex
  
With https://github.com/libp2p/interface-stream-muxer, we got a standard interface for Stream Multiplex and with it, a very comprehensive battery of tests, which can be found:

- JS - https://github.com/libp2p/interface-stream-muxer/tree/master/src
- Go - https://github.com/jbenet/go-stream-muxer/blob/master/test/ttest.go

The following table presents the current state of each multiplex:

| Module | interface tests | stress tests | mega stress test | interop |
|--------|----------------|-------------|------------------|---------|
| js-libp2p-spdy | ✔️ | ✔️ | ✔️ | 𝙓 |
| js-libp2p-multiplex | ✔️ | ✔️ | ✔️ | 𝙓 |
| spdystream | ✔️ | ?? | ?? | 𝙓 |
| yamux | ✔️ | ✔️ | ✔️ | N/A |
| muxado | ✔️ | ?? | ?? | N/A |
| go-multiplex | ✔️ | ?? | ?? | 𝙓 |

Threads with information about this issue:

- Interop Tests available in js-ipfs repo https://github.com/ipfs/js-ipfs/pull/715
- SPDY diagnostics https://github.com/libp2p/js-libp2p-spdy/issues/48
- @VictorBjelkholm TODO https://hackmd.io/CwJghgrBzGC0A2ApgTgMx2ARhUuLgl4BjCAIwQQgBMAzLWiYoA==#

**Comment by diasdavid** [comment]
@VictorBjelkholm how is the state of testing? Have we confirmed that go-multiplex actually passes all the tests like yamux? 

What about the tests just between `js-libp2p-ipfs-node.js` and `go-libp2p`, do those show any interesting behaviour?

**Comment by VictorBjelkholm** [comment]
@diasdavid 

> @VictorBjelkholm how is the state of testing? Have we confirmed that go-multiplex actually passes all the tests like yamux?

I cannot confirm that either go-multiplex or yamux is passing the tests since I cannot run them. Wrote a comment about this here: https://github.com/jbenet/go-stream-muxer/issues/10#issuecomment-274450927

Gonna skip muxando for now.

> What about the tests just between js-libp2p-ipfs-node.js and go-libp2p, do those show any interesting behaviour?

So, with spdy everything is fine and seemingly working, when testing the `echo` example, however, when using multiplex, libp2p-nodejs fails with:

```
/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
      ^

Error: already piped
    at sink (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/pull-pair/index.js:11:13)
    at Connection.consume (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/pull-defer/sink.js:7:17)
    at pull (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/multistream-select/src/dialer/index.js:47:5)
    at protocolHandshake (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/libp2p-swarm/src/dial.js:183:10)
    at attemptMuxerUpgrade (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/libp2p-swarm/src/dial.js:60:11)
    at ms.select (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/libp2p-swarm/src/dial.js:147:17)
    at f (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/once/once.js:25:25)
    at select (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/multistream-select/src/dialer/index.js:76:16)
    at pullLP.decodeFromReader (/Users/user/projects/ipfs/js-libp2p-ipfs-nodejs/node_modules/multistream-select/src/select.js:25:14)
```

I'm now on a OS where I can reproduce the test-failures we saw with libp2p-swarm and libp2p-nodejs when multiplex is activated, so gonna look into and see if I can figure out why.

**Comment by diasdavid** [comment]
Started a 'how to repro' issue to help everyone debug here: https://github.com/ipfs/js-libp2p-ipfs-nodejs/issues/59

**Comment by diasdavid** [comment]
https://github.com/ipfs/in-web-browsers/issues/19#issuecomment-280281313

**Comment by jackkleeman** [comment]
Any news on the status of this in browsers? I have no issues from node in spdy, but in browser both spdy and multiplex (after enabling multiplex on the go listener) fails during the handshake, after `selecting /spdy/3.1.0` or `selecting /mplex/6.7.0`. Well, it doesn't fail with an error, it just stalls.

**Comment by dignifiedquire** [comment]
The version on `master` is fully interoperable with go using multiplex on node.js. I am still working through testing multiplex in the browser.

**Comment by jackkleeman** [comment]
Yes it looks like my problem is the outdated ipfs fork used by OpenBazaar. Thanks!

**Comment by diasdavid** [comment]
@jackkleeman keep us up to date with OB on top of js-ipfs and go-ipfs. If there are tests we can run before releasing new versions, that would be sweet to make sure we don't break anything by mistake (the same way we do with orbit) :)

**Comment by jackkleeman** [comment]
Will do, I am in the early stages of porting to JS. We have a dht relay for offline messaging, but aim to build online messaging with js ipfs for outbound and the new relay circuit for inbound. I doubt we will have a friendly test suite for some time :p

**Comment by diasdavid** [comment]
all right :) Considering this issue done then :)
