### ISSUE TITLE
stable candidate?

### ISSUE THREAD

**Issue by chovy** [ipfs/js-ipfs#727]
I know I shouldn't ask but I'm just curious -- last I checked there was some major pieces missing in js-ipfs to get it to work on its own. Is there a timeline for when 1.0.0 will be released with full api 1-2-1 with the Go implementation?

**Comment by diasdavid** [comment]
Hi @chovy, you are totally welcome to ask, in fact, we keep our [ROADMAP](https://github.com/ipfs/js-ipfs#project-status) open just to make sure the community knows where we are headed.

Right now, we are facing a issue with the Stream Multiplexer we have available, you should be able to fetch files from go-ipfs through js-ipfs, but not the vice versa (until we solve it), nevertheless js-ipfs to js-ipfs works super fine. Follow the stream issue here: https://github.com/ipfs/js-ipfs/issues/721

Hope this gives you an answer.
