### ISSUE TITLE
Proposal: use self instead of window for WebWorker compatibility

### ISSUE THREAD

**Issue by dryajov** [ipfs/js-ipfs#728]
As part of achieving #725, I would like to propose that we switch from using `window` to `self`, everywhere possible, since `window` is missing in Service and Web workers. It should be pretty safe, as long as we don't need to modify `window`, since `self` is readonly. What I'm trying to avoid  is checking for `window` everywhere since you could be potentially running inside a WebWorker and doing the check is tedious and error prone.

**Comment by diasdavid** [comment]
@dryajov sounds good, nevertheless please have in mind that WebRTC is not available in webworkers, we will need some special way to fully support a js-ipfs node in a WebWorker

**Comment by dignifiedquire** [comment]
Are you sure all browsers expose self in the same way they support window?

**Comment by dryajov** [comment]
According to MDN it is - https://developer.mozilla.org/en-US/docs/Web/API/Window/self & https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self.

**Comment by dryajov** [comment]
@diasdavid We should be able to use web sockets AFAIK? I've asked a question here #729, I understand that currently there is no discoverability built into the js-ipfs, but we can dial directly, can we?

**Comment by diasdavid** [comment]
> but we can dial directly, can we?

Yes, I've answered your question on #729

**Comment by diasdavid** [comment]
All right, all the work happening and being tracked here: https://github.com/ipfs/js-ipfs/issues/725 closing this one :)
