### ISSUE TITLE
DNS support for Bootstrapper nodes

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#739]
Following: https://github.com/multiformats/js-multiaddr/issues/37

Here is the list of remaining tasks:

- [ ] Migrate repo/.config to have:
  - [ ] libp2p key to isolate all libp2p config specifically
  - [ ] addrs to listen (listen)
  - [ ] addrs to announce (broadcast)
  - [ ] addrs to not announce (filter)
  - [ ] Add these distinctions to the peerInfo object too
- [ ] Test that a js-ipfs node can dial do a node behind DNS
  - [ ] Deploy a node using the dokku thing
  - [ ] Test it out
  - [ ] Ensure that Identify sends the right addrs

**Comment by lgierth** [comment]
While speccing out the relay I noticed we don't really have a pressing need for specifying addresses *not to announce*. I'm probably going to leave it out in go-ipfs.

>  Add these distinctions to the peerInfo object too

What are they needed for in PeerInfo?

**Comment by diasdavid** [comment]
@lgierth re: PeerInfo

This is js-ipfs specific :)

**Comment by diasdavid** [comment]
Almost all done, last mile is https://github.com/ipfs/js-ipfs/pull/740

**Comment by VictorBjelkholm** [comment]
>  addrs to listen (listen)
> addrs to announce (broadcast)

How can I set this up? Tried finding how, but the config format is not the same as what go-ipfs is doing with `Announce` and `NoAnnounce`
