### ISSUE TITLE
Add orbit tests to js-ipfs release

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/js-ipfs#747]
This is the natural extension of https://github.com/ipfs/pm/issues/345. In short:

> Add orbit, orbit-db, ipfs-log tests to js-ipfs(-api)
> orbit-db and ipfs-log tests should be run as part of CI tests

In that issue, @diasdavid:
> I don't believe adding to CI to be always run will be good (our poor CI already takes so long) and it will be a cat and mouse game because then we have to be updating as you go (and when to update what)
> I do believe though that it should be part of the release process as we did -- ipfs/js-ipfs#712 -- it just needs to be formalized.

So, this issue is to track how we want to make it part of the release process.

**Comment by diasdavid** [comment]
Can we create a RELEASE_CHECKLIST.md document at the root of js-ipfs?

**Comment by haadcode** [comment]
> Can we create a RELEASE_CHECKLIST.md document at the root of js-ipfs?

I like the idea of a release checklist :+1: Is there any existing list to base it on? Or is this information still in the heads of you and @dignifiedquire?

**Comment by diasdavid** [comment]
Creating it here: https://github.com/ipfs/js-ipfs/pull/757
