### ISSUE TITLE
Seeing a `zlib` error between browser nodes and node.js nodes?

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#758]
This is a known issue and we do have more than just a solution for it \o/

The problem is that the default shim for zlib that is available for webpack and browserify is simply incomplete, we've fixed this by upgrading that shim and implementing the remaining features, however, since the PR -- https://github.com/devongovett/browserify-zlib/pull/18 -- hasn't been merged for the course of almost a year, we have to shim it manually every time.

The complete zlib shim is available at: https://www.npmjs.com/package/browserify-zlib-next

Just add to your webpack config: `zlib: 'browserify-zlib-next',` or you can check an example on how to do it at: https://github.com/ipfs/js-ipfs/tree/master/examples

We are also working on getting this shim to be the default of both browserify and webpack, so that we don't have to wait for the PR above to be merged, see the developments here:

- https://github.com/webpack/node-libs-browser/issues/51
- https://github.com/substack/node-browserify/issues/1672

**Comment by diasdavid** [comment]
This shouldn't be a problem anymore \o/ 

@dignifiedquire could you confirm that:

- [ ] Webpack config no longer has this substitution
- [ ] README has been updated to reflect this change
- [ ] Have examples been updated?

**Comment by dignifiedquire** [comment]
@diasdavid I did not have time to do a new release for browserify-zlib I am afraid

**Comment by dignifiedquire** [comment]
browserify-zlib@0.2.0 was just released :tada:

**Comment by diasdavid** [comment]
Finished this with https://github.com/ipfs/js-ipfs/pull/882
