### ISSUE TITLE
🌟 Parity to IPFS

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#763]
> Update: I rewrote this first post to make it more useful for tracking the developments of this.

Goal: Add a 'Storage Backend' for js-ipfs that backed by Parity, the Rust implementation of Ethereum. This will enable js-ipfs nodes to fetch content from the Ethereum Network as if it was just a big bucket with all the blocks from the chain.

TASKS

- [x] rust-cid
- [x] Implement an http endpoint in Parity that lets us retrieve the blocks
- [ ] Implement the datastore backend that mounts on top of parity
- [ ] Try it out, a lot :)

**Comment by kumavis** [comment]
from parity `mh-ipfs branch`
```
cargo build --release
./target/release/parity
```
while thats running, you can make requests by cid
```
curl 'http://localhost:5001/api/v0/block/get?arg=z45oqTRzb9a5xyvx5RbfSXH1K5jibyZ4AxnXyYReuLw7KU5veYw'
```

**Comment by kumavis** [comment]
i made this util to help with this https://github.com/kumavis/eth-ipld

**Comment by diasdavid** [comment]
@kumavis let's pick up on this again, now that we have datastore bubbling up all the way :)

**Comment by kumavis** [comment]
whee~

**Comment by kumavis** [comment]
seems simple enough

https://github.com/ipfs/js-datastore-level
https://github.com/ipfs/interface-datastore

how do you mount multiple stores? and can you mount one as read-only?

**Comment by kumavis** [comment]
also - do you have a preferred isomorphic xhr module? otherwise ill use what i usually do

**Comment by diasdavid** [comment]
We shim `stream-http` in js-ipfs-api https://github.com/ipfs/js-ipfs-api/blob/master/package.json#L10

The code for reaching to the block store, given that it exposes the same API as go-ipfs does for blocks, is exactly what js-ipfs-api does https://github.com/ipfs/js-ipfs-api/blob/master/src/api/block.js

On `read-only`, it means that essentially when it calls write, you say 'All good folks', but in reality does nothing.

Right now, ipfs-repo is mounting a single datastore for the blockstore (blocks folder) https://github.com/ipfs/js-ipfs-repo/blob/master/src/index.js#L136-L139, which is them used throughout blockstore code: https://github.com/ipfs/js-ipfs-repo/blob/master/src/blockstore.js#L34-L137

Tasks:

- [ ] Ability to mount more than one datastore for blockstore (make it an array essentially)
- [ ] Make ./blockstore check if there is an array of this.store and issue the get/put to all of them.

Note: blockstore will pass a base32 encoded CID to your parity-datastore, which you then have to decode to send through the js-ipfs-api block.get.

**Comment by kumavis** [comment]
would be nice if js-ipfs-repo's data store could be specified externally somehow
seems hardcoded in with a lot of other config https://github.com/ipfs/js-ipfs-repo/blob/master/src/index.js#L136-L139

**Comment by diasdavid** [comment]
Agreed, right now the decision is being made inside the ipfs-repo module by signalling through the browser property in the package.json, here:

https://github.com/ipfs/js-ipfs-repo/blob/master/package.json#L8

I would rather have those options passed in, so that we can hot swap it per application basis, just like libp2p bundles.

**Comment by kumavis** [comment]
would be nice if we could boot the http api by passing in an instance of an ipfs node, instead of it needing to boot its own

**Comment by kumavis** [comment]
for now, i think this will work but NotAGoodIdea™
```js
node.on('ready', () => {
  console.log('node ready!')
  // hacky late add to MountStore
  console.log('Adding mount to Parity')
  repo.store.mounts.push({
    prefix: new Key('/'),
    datastore: new RemoteIpfsDataStore({host: 'localhost', port: '5002', protocol: 'http'})
  })
  setupHttpApi()
})
```

**Comment by kumavis** [comment]
hmmm seems bitswap is somehow not using my late-mounted datastore

**Comment by kumavis** [comment]
https://github.com/ipfs/js-ipfs-api/pull/550

**Comment by kumavis** [comment]
ipfs-api uses POST for all requests, parity only implements GET for `block.get`

**Comment by kumavis** [comment]
PR for the http method fix here https://github.com/ipfs/js-ipfs-api/pull/551

**Comment by kumavis** [comment]
Remaining IPFS todo's
- [ ] fix js-ipfs-api http method ipfs/js-ipfs-api#551
- [ ] publish `datastore-ipfs-http-api` (is there a less horrible name to use?)

optional:
- [ ] fix js-ipfs-api cid serialization ipfs/js-ipfs-api#550 
- [ ] change the http-api server api to accept an ipfs instance instead of a ipfs repo location
- [ ] change the ipfs-repo datastore config to be easier to configure at the app level

**Comment by kumavis** [comment]
i have it working and deployed (via patched deps) https://github.com/kumavis/ipfs-eth-bridge

**Comment by diasdavid** [comment]
Checked the boxes that are already done

> publish datastore-ipfs-http-api (is there a less horrible name to use?) 

Yeah, just call it`js-datastore-ipfs`, it is an IPFS adapter for the datastore. Kind of a mobius strip datastore, but that is what it is :) Just make it clear in the Readme

--- 

@kumavis did you manage to figure out the bug of the other day?

**Comment by kumavis** [comment]
because of the GET/POST mismatch, ended up making a "read-only-hooked datastore" module, used here: https://github.com/kumavis/ipfs-eth-bridge/blob/master/index.js#L24-L39

**Comment by diasdavid** [comment]
@kumavis What are the next steps?

**Comment by b1u3h4t** [comment]
how can I find the block data in IPFS format when i use parity with --ipfs-api --ipfs-api-hosts all?
It also return the error block not found, anyone can help me?

**Comment by 5chdn** [comment]
Currently, you can only get block headers, block lists, uncles, transactions, and the state-trie node.

See https://github.com/paritytech/parity/wiki/IPFS

**Comment by b1u3h4t** [comment]
Do i need an ipfs instance running? if not, how the eth data is encode to ipfs data format?

**Comment by 5chdn** [comment]
You need a Parity node running with IPFS enabled. There is no need for an additional IPFS node unless you want to access other content/APIs via IPFS.

**Comment by b1u3h4t** [comment]
Is the eth data not saved in ipfs format?  Is there no ipfs store indeed? I can't get any data directory about ipfs info, but when i start an additional ipfs node, i can find data in ~/.ipfs/ directory, so where is partiy's ipfs data store?

**Comment by diasdavid** [comment]
It would be amazing to have a package on npm that downloads the Parity client and exposes the datastore with it to access the Eth network so that we can create a quick example on how to set it up. Does this sound like something you can handle in the near future, @kumavis @hermanjunge?

**Comment by hermanjunge** [comment]
That's right @diasdavid. This is one of our main pain points for the ethereum browser light client currently. I am working on extracting the functions I need from go-ethereum to store the K-V data into a Redis DB cluster.

It would be nice to have a slim parity client version that synchronizes to the network, to store the data into a database we can easily mount as an IPFS client datastore.

For now, we have this docker compose package to do the trick, is a js-ipfs client that mounts the parity HTTP IPFS, that way we can access eth dag nodes one by one. The ideal, of course, is unleash more capabilities.

https://github.com/kumavis/ipfs-eth-bridge/blob/master/mustekala/docker-compose.yml

**Comment by jualy007** [comment]
Great works

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Helia accepts implementations of `interface-blockstore` and `interface-datastore` in a similar way to js-IPFS so this would still be possible, someone just needs to finish the work here and publish the modules!

Closing as not planned but I would love to see this in a usable state still.
