### ISSUE TITLE
Finding hash on gateway.ipfs.io

### ISSUE THREAD

**Issue by compsocial** [ipfs/js-ipfs#771]
I succeeded in obtaining js-ipfs via an npm install on Mac OS 10.12.3, after a decent amount of debugging of a few underlying dependencies. I then added files using both the jsipfs command line tool, as well as via both the browserify and webpack examples. Everything looks good in the terminal and the browser. For example: 

```
$ echo "scofield" > sco
$ jsipfs add scofield
added [hash]
$ jsipfs cat [hash]
scofield
```
Similar results with the browser (that I'm actually more interested in). My assumption at this point--and this may be a misunderstanding on my part--is that this data would be available to others via gateway.ipfs.io. That is, that http://gateway.ipfs.io/ipfs/[hash] would return "scofield". However, it only times out. 

What am I missing? How can verify that my data is accessible to other ipfs nodes? 

Thanks!

**Comment by thisconnect** [comment]
I have the same issue. not sure if I do something wrong, firewall issue, or if js-ipfs already supports that.

**Comment by dignifiedquire** [comment]
js-ipfs does not support connecting to the gateways out of the box currently. The reason for that is that the gateways run go-ipfs and that js-ipfs has not implemented all features yet that are needed to easily fetch content on the gateways from it. 

The latest release improves on things a little bit, as it now enables content transfer between two nodes directly. To test this you can connect to `/ip4/178.62.158.247/tcp/80/ws/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd` manually (one of the gateway nodes) you should be able to pull content from it via `earth.i.ipfs.io/ipfs`. 

For being able to do what you want to do we are missing any form of routing on the js-ipfs side, specifically content routing via a dht. We are planning to work on this in a couple of weeks, so it is not too far out anymore. The work there is tracked in https://github.com/libp2p/js-libp2p-dht/pull/1

**Comment by thisconnect** [comment]
@dignifiedquire thanks! I will play with go-ipfs and js-ipfs-api
Where is the best place to see the current state of js-ipfs, the waffle board?

**Comment by VictorBjelkholm** [comment]
@thisconnect there is a "Project Status" section in the ROADMAP.md file that might help you getting an overview: https://github.com/ipfs/js-ipfs/blob/master/ROADMAP.md#project-status

The Waffle board is more for day-to-day organization and also to find something to work on. Issues that are under the "Ready" column, should be ready to be picked up and worked on without any further information.

Hope that helps you navigate a bit! Otherwise, just ask if something is unclear :)
