### ISSUE TITLE
Awesome Datastore Endeavour

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#787]
As described in https://github.com/ipfs/js-ipfs-repo/issues/112 we need and want to upgrade our storage game. So here comes another awesome endeavour 🌟 

The general goal is to create a datastore interface and implementations to match the way go handles storage and matching features like `query` that we need down the line. The new library has been implemented in [interface-datastore](https://github.com/ipfs/interaface-datastore). 

### New Modules

| Name | Ready for Review | Merged | Published | 
|-------|-------------------|---------|-----------|
|[interface-datastore](https://github.com/ipfs/interface-datastore) | ✅ |✅ | ✅|
|[datastore-core](https://github.com/ipfs/js-datastore-core) | ✅ |✅ | ✅|
|[datastore-fs](https://github.com/ipfs/js-datastore-fs) | ✅ |✅ | ✅|
|[datastore-level](https://github.com/ipfs/js-datastore-level)  | ✅ |✅ | ✅|

### Modules that need updating

| Name | Ready for Review | Reviewed | Merged | Published | 
|-------|-------------------|---------|---------|-----------|
|[ipfs-repo](https://github.com/ipfs/js-ipfs-repo) | ✅ | ✅ | ✅ | ✅ |
|[ipfs-block](https://github.com/ipfs/js-ipfs-block) | ✅ | ✅ | ✅ | ✅ |
|[ipfs-block-service](https://github.com/ipfs/js-ipfs-block-service) | ✅ | ✅ | ✅ | ✅ |
|[ipfs-bitswap](https://github.com/ipfs/js-ipfs-bitswap) | ✅ | ✅ | ✅ | ✅ |
| ipld-dag-pb | ✅ | ✅ | ✅ | ✅ |
| ipld-dag-cbor | ✅ | ✅ | ✅ | ✅ |
| ipld-dag-eth-x | ✅ | ✅ | ✅ | ✅ |
| ipld-resolver | ✅ | ✅ | ✅ | ✅ |
| ipfs-unixfs-engine | ✅ | ✅ | ✅ | ✅ |
|[interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core) | ✅ | ✅ | ✅ | ✅
|[ipfs-api](https://github.com/ipfs/js-ipfs-api) | ✅ | ✅ | |
|[ipfs](https://github.com/ipfs/js-ipfs) | ✅ | ✅ | | |

**Comment by diasdavid** [comment]
the ipfs-repo update and block-service should be part of this endeavour as well :)

**Comment by diasdavid** [comment]
//cc @kumavis @SidHarder that might be interested in following this one

**Comment by dignifiedquire** [comment]
> the ipfs-repo update and block-service should be part of this endeavour as well :)

added

**Comment by diasdavid** [comment]
@dignifiedquire do you feel that you will have the 3 remaining PR's tomorrow? I think we can pull this one all together tomorrow :)

**Comment by diasdavid** [comment]
I'm really happy with the way we figured to make this big code changes `\o/ awesome endeavours`
