### ISSUE TITLE
webui fails to load properly

### ISSUE THREAD

**Issue by lhenocque** [ipfs/js-ipfs#79]
On a mac, el capitan. IPFS installed fine. All command line tests run fine.
Video streaming works fine
Only ada.jpg loads on the photo demo (I may not have tried all)

Trying to load http://localhost:5001/webui. It stalls on
http://localhost:5001/ipfs/QmRyWyKWmphamkMRnJVjUTzSFSAAZowYP4rnbgnfMXC9Mr/#/?_k=***
It fails on three browsers : Firefox, Safari and Chrome. Chrome reports "waiting for localhost".
I have this error: 
12:23:08.514 ERROR core/serve: Path Resolve error: context deadline exceeded gateway_handler.go:472

Regards
Laurent

**Comment by diasdavid** [comment]
Hi @lhenocque , this repo is focused on the JavaScript implementation of IPFS. For the webui repo, visit https://github.com/ipfs/webui

Tagging @dignifiedquire which can follow up and provide help to you. Closing this one

**Comment by lhenocque** [comment]
ok, thanks David
