### ISSUE TITLE
Local subnet offline file system

### ISSUE THREAD

**Issue by baimurzin** [ipfs/js-ipfs#816]
Is it possible to run IPFS locally(on local network), for example for only my devices: laptop, pc, android. And sharing files between

**Comment by diasdavid** [comment]
- ✅  Run IPFS locally
- ✅  Devices: 
  - ✅  laptop
  - ✅  pc
  - ✅  android (inside Chrome)
- ✅  share files

Absolutely! Now it is all about UX, if you are looking for something like Dropbox or Google Drive, that is something we haven't built yet, the closest we have is https://github.com/ipfs/station

**Comment by baimurzin** [comment]
@diasdavid ok, thanks a lot for the answer, but I do not need this like dropbox, I just learning how to build my local network IPFS, can you suggest where to look?

**Comment by diasdavid** [comment]
Have you checked the transfer-files tutorial https://github.com/ipfs/js-ipfs/tree/master/examples/transfer-files ?

**Comment by baimurzin** [comment]
@diasdavid using this solution I can communicate only with my nodes, correct me if I mistaken?

**Comment by diasdavid** [comment]
It should not be seen as a solution, it is just an starting point that shows you how stuff works.

**Comment by baimurzin** [comment]
@diasdavid Ok, I got it, thanks. But it is just a approach to transfer a file from one device to another. 
But my question is is there any solution to use IPFS as default distributed fs, but among my devices which have ipfs daemon or something else.  For example, when I run one instance of API and upload the file it's file is available from [https://gateway.ipfs.io/ipfs/](url) for all users, because it stored on all devices in this network. But I want try to do the same but this local network :)

**Comment by dryajov** [comment]
@baimurzin if your ipfs network is isolated from the outside world, then you should be able to, just don't let it connect to anything outside that network.

**Comment by baimurzin** [comment]
@diasdavid ok, I'm grateful for your help. Now it's more clearly, but what of this library I should use for it and how my device found another one in network?

**Comment by diasdavid** [comment]
@baimurzin just starting the daemon should suffice, it uses MulticastDNS for that local discovery :)

**Comment by baimurzin** [comment]
@diasdavid ok, good, And how can I find the devices what "connected" with me?
