### ISSUE TITLE
install failed on ubuntu 16.04

### ISSUE THREAD

**Issue by josselinchevalay** [ipfs/js-ipfs#819]
Hi all 

i install js-ipfs on my project by that command 

```
npm install --save ipfs
```

i use : 
- npm 3.10.10
- node v6.10.1
- OS ubuntu 16.04 

when run  : 

```
 node node_modules/ipfs/examples/basics/index.js
```` 

i have this error :  

````
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
module.js:471
    throw err;
    ^

Error: Cannot find module '/root/finder/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v48-linux-x64/wrtc.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/finder/node_modules/wrtc/lib/peerconnection.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
````

**Comment by VictorBjelkholm** [comment]
Are you getting any errors when running npm install? Seems like wrtc wasn't
installed correctly

**Comment by josselinchevalay** [comment]
no i haven't error aout wrtc

**Comment by diasdavid** [comment]
Seems like wrtc is missing indeed, could you try a fresh install? Also see: https://github.com/ipfs/js-ipfs/issues/619

@VictorBjelkholm anytime to handle https://github.com/ipfs/js-ipfs/issues/619#issuecomment-289234926 ?

**Comment by VictorBjelkholm** [comment]
So, tried installing js-ipfs on a completely fresh Ubuntu 16.04 box, with same node and npm version as you.

### Install Dependencies + nodejs
```
    1  apt update && apt install curl git vim build-essential python
    2  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    3  . ~/.nvm/nvm.sh
    4  nvm install 6.10.1
```
### Temporary application path
```
    5  mkdir -p /usr/src/app
    6  cd /usr/src/app
    7  npm init --force --yes
```
### Installing js-ipfs, no errors
```
    8  npm install --save ipfs
   18  vim index.js
```
### Contents of `index.js`
```
const IPFS = require('ipfs')

const node = new IPFS()

node.on('ready', () => {
	console.log('Node ready')
})

node.on('error', (err) => {
	console.log(err)
})
```
### Running
```
   19  node index.js
```
Output:
```
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/src/app/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v48-linux-x64/wrtc.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/wrtc/lib/peerconnection.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
### Reinstalling wrtc again and then run it again
```
   29  npm install wrtc
   30  node index.js
```
Output:
```
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/usr/src/app/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/src/app/node_modules/leveldown/build/leveldown.node
 → /usr/src/app/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/src/app/node_modules/leveldown/build/Release/leveldown.node
 → /usr/src/app/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/src/app/node_modules/leveldown/Debug/leveldown.node
 → /usr/src/app/node_modules/leveldown/out/Release/leveldown.node
 → /usr/src/app/node_modules/leveldown/Release/leveldown.node
 → /usr/src/app/node_modules/leveldown/build/default/leveldown.node
 → /usr/src/app/node_modules/leveldown/compiled/6.10.1/linux/x64/leveldown.node
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/src/app/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/ipfs-repo/src/default-options.js:6:10)
```
### Manually reinstall leveldown and run again
```
   31  npm install leveldown
   32  node index.js
```
Output:
```
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmVDnWzpF9J9mBBRsnvoQoVJDyNpErLWpZvBuvx58DL8cQ
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmVDnWzpF9J9mBBRsnvoQoVJDyNpErLWpZvBuvx58DL8cQ
Swarm listening on /ip4/172.17.0.2/tcp/4002/ipfs/QmVDnWzpF9J9mBBRsnvoQoVJDyNpErLWpZvBuvx58DL8cQ
Node ready
```

## Summary

Seems like npm is not actually building all the modules that are required to be built, not exactly sure why yet.

```
$ npm version
{ app: '1.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.1',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.95',
  zlib: '1.2.8' }
```

@josselinchevalay could you try following the steps I've put above and see if that fixes your problem temporary?

**Comment by josselinchevalay** [comment]
after your process when run index .js have this output : 

`̀``
assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: The libp2p node is not started yet
    at Node.dialByPeerInfo (/home/josselin/waiting/js-ipfs/node_modules/libp2p/src/index.js:219:5)
    at EventEmitter.self._libp2pNode.discovery.on (/home/josselin/waiting/js-ipfs/node_modules/ipfs/src/core/components/libp2p.js:37:32)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Railing.discovery.on (/home/josselin/waiting/js-ipfs/node_modules/libp2p/src/index.js:70:26)
    at emitOne (events.js:96:13)
    at Railing.emit (events.js:188:7)
    at PeerInfo.create (/home/josselin/waiting/js-ipfs/node_modules/libp2p-railing/src/index.js:52:16)
    at Function.PeerInfo.create (/home/josselin/waiting/js-ipfs/node_modules/peer-info/src/index.js:115:3)
    at bootstrapers.forEach.e (/home/josselin/waiting/js-ipfs/node_modules/libp2p-railing/src/index.js:45:18)
```

**Comment by josselinchevalay** [comment]
my npm version 

```
{ 'js-ipfs': '1.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.10.1',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.95',
  zlib: '1.2.8' }
```

**Comment by diasdavid** [comment]
Not being able to replicate locally:
```
» node index.js
IPFS Version: 0.23.1
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmQ4PTxgJAYUbxJzCKsyVuwL56fFiee6Gxbj9Se4uRU6xy
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmQ4PTxgJAYUbxJzCKsyVuwL56fFiee6Gxbj9Se4uRU6xy
Swarm listening on /ip4/192.168.2.110/tcp/4002/ipfs/QmQ4PTxgJAYUbxJzCKsyVuwL56fFiee6Gxbj9Se4uRU6xy
Swarm listening on /ip4/192.168.2.156/tcp/4002/ipfs/QmQ4PTxgJAYUbxJzCKsyVuwL56fFiee6Gxbj9Se4uRU6xy

Node is now ready and online

Added file:
{ path: 'hello.txt',
  hash: 'QmSQ8UNccvQPYDmZDMYK1JDcyPC9WTas2jiferS4BpdgbK',
  size: 66 }

File content:
Hello, how are you today? Welcome to the Distributed Web!

```

@VictorBjelkholm can you verify in your machine?

**Comment by VictorBjelkholm** [comment]
@josselinchevalay sorry, made a mistake with listening to `ready` instead of `start`. Try changing to

```
node.on('start', callback)
```

instead and see if everything works.

**Comment by diasdavid** [comment]
@VictorBjelkholm any luck on those docs?

**Comment by josselinchevalay** [comment]
@diasdavid @VictorBjelkholm i propose to change that into the README.md

**Comment by diasdavid** [comment]
@josselinchevalay it is the other way around, you should always check for the `start` event

**Comment by Jacodelange** [comment]
@VictorBjelkholm I had the same problem, your steps fixed it.

**Comment by josselinchevalay** [comment]
@Jacodelange  you talk about replace ready by start ?

**Comment by diasdavid** [comment]
Updated the readme to clarify this.

- `start` means that the node has been booted (with listeners)
- `ready` means that whatever were the steps you used as options, they are completed and it is ready to go. So if you didn't set "start: false", it means it also started.

**Comment by josselinchevalay** [comment]
👍  @diasdavid  it's more clear thanks a lot ! =)

**Comment by Jacodelange** [comment]
@josselinchevalay the issue with the Cannot find module wrtc

**Comment by josselinchevalay** [comment]
@Jacodelange  ok thx a lot

**Comment by VictorBjelkholm** [comment]
I don't think reinstalling two modules manually is a acceptable fix, just a debugging step. Something is clearly wrong with how to modules are being installed, but I'm still unsure about the reason for it. I'll reopen this for tracking that.

**Comment by josselinchevalay** [comment]
@VictorBjelkholm  ok let me know if you need some help for test =)

**Comment by shuangjj** [comment]
Have the same problem, fixed after `npm install wrtc --build-from-source`

**Comment by josselinchevalay** [comment]
hey @shuangjj , could you try that 

`npm install --save wrtc leveldown`

regards

**Comment by diasdavid** [comment]
Hi all! I've removed wrtc as a default dependency in Node.js, you should not see this issue anymore.

To bring WebRTC back, either by wrtc or electron-wrtc, see https://github.com/ipfs/js-ipfs#cli

**Comment by ElMehdiBouamama** [comment]
I keep getting a similar error, even though i followed the same steps as described above :

`[04:49:48]  Error: ./node_modules/datastore-level/src/index.js Module not found: Error: Can't resolve 'leveldown' in 
            'C:\Ionic\clusteredSchools\node_modules\datastore-level\src' resolve 'leveldown' in 
            'C:\Ionic\clusteredSchools\node_modules\datastore-level\src' Parsed request is a module using description 
            file: C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json (relative path: ./src) aliased 
            from description file C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json with mapping 
            'leveldown' to 'level-js' Parsed request is a module using description file: 
            C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json (relative path: .) after using 
            description file: C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json (relative path: .) 
            resolve as module looking for modules in C:\Ionic\clusteredSchools\node_modules using description file: 
            C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules) Field 'browser' doesn't contain a 
            valid alias configuration after using description file: C:\Ionic\clusteredSchools\package.json (relative 
            path: ./node_modules) using description file: C:\Ionic\clusteredSchools\package.json (relative path: 
            ./node_modules/level-js) no extension Field 'browser' doesn't contain a valid alias configuration 
            C:\Ionic\clusteredSchools\node_modules\level-js doesn't exist .ts Field 'browser' doesn't contain a valid 
            alias configuration C:\Ionic\clusteredSchools\node_modules\level-js.ts doesn't exist .js Field 'browser' 
            doesn't contain a valid alias configuration C:\Ionic\clusteredSchools\node_modules\level-js.js doesn't exist 
            .json Field 'browser' doesn't contain a valid alias configuration 
            C:\Ionic\clusteredSchools\node_modules\level-js.json doesn't exist as directory 
            C:\Ionic\clusteredSchools\node_modules\level-js doesn't exist 
            [C:\Ionic\clusteredSchools\node_modules\level-js] [C:\Ionic\clusteredSchools\node_modules\level-js.ts] 
            [C:\Ionic\clusteredSchools\node_modules\level-js.js] [C:\Ionic\clusteredSchools\node_modules\level-js.json] 
            [C:\Ionic\clusteredSchools\node_modules\level-js] @ ./node_modules/datastore-level/src/index.js 35:17-37 @ 
            ./node_modules/ipfs-repo/src/default-options-browser.js @ ./node_modules/ipfs-repo/src/index.js @ 
            ./node_modules/ipfs/src/core/boot.js @ ./node_modules/ipfs/src/core/index.js @ 
            ./src/app/services/IpfsService.ts @ ./src/app/app.module.ts @ 
            ./src/app/main.ts,./node_modules/libp2p-crypto/src/webcrypto.js Module not found: Error: Can't resolve 
            'webcrypto-shim' in 'C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\src' resolve 'webcrypto-shim' in 
            'C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\src' Parsed request is a module using description 
            file: C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\package.json (relative path: ./src) after using 
            description file: C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\package.json (relative path: ./src) 
            resolve as module looking for modules in C:\Ionic\clusteredSchools\node_modules using description file: 
            C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules) Field 'browser' doesn't contain a 
            valid alias configuration after using description file: C:\Ionic\clusteredSchools\package.json (relative 
            path: ./node_modules) using description file: C:\Ionic\clusteredSchools\package.json (relative path: 
            ./node_modules/webcrypto-shim) no extension Field 'browser' doesn't contain a valid alias configuration 
            C:\Ionic\clusteredSchools\node_modules\webcrypto-shim doesn't exist .ts Field 'browser' doesn't contain a 
            valid alias configuration C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.ts doesn't exist .js Field 
            'browser' doesn't contain a valid alias configuration 
            C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.js doesn't exist .json Field 'browser' doesn't contain 
            a valid alias configuration C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.json doesn't exist as 
            directory C:\Ionic\clusteredSchools\node_modules\webcrypto-shim doesn't exist 
            [C:\Ionic\clusteredSchools\node_modules\webcrypto-shim] 
            [C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.ts] 
            [C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.js] 
            [C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.json] 
            [C:\Ionic\clusteredSchools\node_modules\webcrypto-shim] @ ./node_modules/libp2p-crypto/src/webcrypto.js 
            8:4-29 @ ./node_modules/libp2p-crypto/src/hmac/index-browser.js @ ./node_modules/libp2p-crypto/src/index.js 
            @ ./node_modules/ipfs/src/core/index.js @ ./src/app/services/IpfsService.ts @ ./src/app/app.module.ts @ 
            ./src/app/main.ts,./node_modules/libp2p-webrtc-star/src/index.js Module not found: Error: Can't resolve 
            'webrtcsupport' in 'C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\src' resolve 'webrtcsupport' 
            in 'C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\src' Parsed request is a module using 
            description file: C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\package.json (relative path: 
            ./src) Field 'browser' doesn't contain a valid alias configuration after using description file: 
            C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\package.json (relative path: ./src) resolve as 
            module looking for modules in C:\Ionic\clusteredSchools\node_modules using description file: 
            C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules) Field 'browser' doesn't contain a 
            valid alias configuration after using description file: C:\Ionic\clusteredSchools\package.json (relative 
            path: ./node_modules) using description file: C:\Ionic\clusteredSchools\package.json (relative path: 
            ./node_modules/webrtcsupport) no extension Field 'browser' doesn't contain a valid alias configuration 
            C:\Ionic\clusteredSchools\node_modules\webrtcsupport doesn't exist .ts Field 'browser' doesn't contain a 
            valid alias configuration C:\Ionic\clusteredSchools\node_modules\webrtcsupport.ts doesn't exist .js Field 
            'browser' doesn't contain a valid alias configuration 
            C:\Ionic\clusteredSchools\node_modules\webrtcsupport.js doesn't exist .json Field 'browser' doesn't contain 
            a valid alias configuration C:\Ionic\clusteredSchools\node_modules\webrtcsupport.json doesn't exist as 
            directory C:\Ionic\clusteredSchools\node_modules\webrtcsupport doesn't exist 
            [C:\Ionic\clusteredSchools\node_modules\webrtcsupport] 
            [C:\Ionic\clusteredSchools\node_modules\webrtcsupport.ts] 
            [C:\Ionic\clusteredSchools\node_modules\webrtcsupport.js] 
            [C:\Ionic\clusteredSchools\node_modules\webrtcsupport.json] 
            [C:\Ionic\clusteredSchools\node_modules\webrtcsupport] @ ./node_modules/libp2p-webrtc-star/src/index.js 
            17:22-46 @ ./node_modules/ipfs/src/core/runtime/libp2p-browser.js @ 
            ./node_modules/ipfs/src/core/components/libp2p.js @ ./node_modules/ipfs/src/core/components/index.js @ 
            ./node_modules/ipfs/src/core/index.js @ ./src/app/services/IpfsService.ts @ ./src/app/app.module.ts @ 
            ./src/app/main.ts 
Error: ./node_modules/datastore-level/src/index.js
Module not found: Error: Can't resolve 'leveldown' in 'C:\Ionic\clusteredSchools\node_modules\datastore-level\src'
resolve 'leveldown' in 'C:\Ionic\clusteredSchools\node_modules\datastore-level\src'
  Parsed request is a module
  using description file: C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json (relative path: ./src)
    aliased from description file C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json with mapping 'leveldown' to 'level-js'
      Parsed request is a module
      using description file: C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json (relative path: .)
      after using description file: C:\Ionic\clusteredSchools\node_modules\datastore-level\package.json (relative path: .)
        resolve as module
          looking for modules in C:\Ionic\clusteredSchools\node_modules
            using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules)
              Field 'browser' doesn't contain a valid alias configuration
            after using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules)
              using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules/level-js)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  C:\Ionic\clusteredSchools\node_modules\level-js doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  C:\Ionic\clusteredSchools\node_modules\level-js.ts doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  C:\Ionic\clusteredSchools\node_modules\level-js.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  C:\Ionic\clusteredSchools\node_modules\level-js.json doesn't exist
                as directory
                  C:\Ionic\clusteredSchools\node_modules\level-js doesn't exist
[C:\Ionic\clusteredSchools\node_modules\level-js]
[C:\Ionic\clusteredSchools\node_modules\level-js.ts]
[C:\Ionic\clusteredSchools\node_modules\level-js.js]
[C:\Ionic\clusteredSchools\node_modules\level-js.json]
[C:\Ionic\clusteredSchools\node_modules\level-js]
 @ ./node_modules/datastore-level/src/index.js 35:17-37
 @ ./node_modules/ipfs-repo/src/default-options-browser.js
 @ ./node_modules/ipfs-repo/src/index.js
 @ ./node_modules/ipfs/src/core/boot.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/services/IpfsService.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts,./node_modules/libp2p-crypto/src/webcrypto.js
Module not found: Error: Can't resolve 'webcrypto-shim' in 'C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\src'
resolve 'webcrypto-shim' in 'C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\src'
  Parsed request is a module
  using description file: C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\package.json (relative path: ./src)
  after using description file: C:\Ionic\clusteredSchools\node_modules\libp2p-crypto\package.json (relative path: ./src)
    resolve as module
      looking for modules in C:\Ionic\clusteredSchools\node_modules
        using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules)
          using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules/webcrypto-shim)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webcrypto-shim doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.json doesn't exist
            as directory
              C:\Ionic\clusteredSchools\node_modules\webcrypto-shim doesn't exist
[C:\Ionic\clusteredSchools\node_modules\webcrypto-shim]
[C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.ts]
[C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.js]
[C:\Ionic\clusteredSchools\node_modules\webcrypto-shim.json]
[C:\Ionic\clusteredSchools\node_modules\webcrypto-shim]
 @ ./node_modules/libp2p-crypto/src/webcrypto.js 8:4-29
 @ ./node_modules/libp2p-crypto/src/hmac/index-browser.js
 @ ./node_modules/libp2p-crypto/src/index.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/services/IpfsService.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts,./node_modules/libp2p-webrtc-star/src/index.js
Module not found: Error: Can't resolve 'webrtcsupport' in 'C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\src'
resolve 'webrtcsupport' in 'C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\src'
  Parsed request is a module
  using description file: C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Ionic\clusteredSchools\node_modules\libp2p-webrtc-star\package.json (relative path: ./src)
    resolve as module
      looking for modules in C:\Ionic\clusteredSchools\node_modules
        using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules)
          using description file: C:\Ionic\clusteredSchools\package.json (relative path: ./node_modules/webrtcsupport)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webrtcsupport doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webrtcsupport.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webrtcsupport.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Ionic\clusteredSchools\node_modules\webrtcsupport.json doesn't exist
            as directory
              C:\Ionic\clusteredSchools\node_modules\webrtcsupport doesn't exist
[C:\Ionic\clusteredSchools\node_modules\webrtcsupport]
[C:\Ionic\clusteredSchools\node_modules\webrtcsupport.ts]
[C:\Ionic\clusteredSchools\node_modules\webrtcsupport.js]
[C:\Ionic\clusteredSchools\node_modules\webrtcsupport.json]
[C:\Ionic\clusteredSchools\node_modules\webrtcsupport]
 @ ./node_modules/libp2p-webrtc-star/src/index.js 17:22-46
 @ ./node_modules/ipfs/src/core/runtime/libp2p-browser.js
 @ ./node_modules/ipfs/src/core/components/libp2p.js
 @ ./node_modules/ipfs/src/core/components/index.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/services/IpfsService.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (C:\Ionic\clusteredSchools\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\Ionic\clusteredSchools\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (C:\Ionic\clusteredSchools\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\Ionic\clusteredSchools\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\Ionic\clusteredSchools\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\Ionic\clusteredSchools\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\Ionic\clusteredSchools\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Ionic\clusteredSchools\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Ionic\clusteredSchools\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (C:\Ionic\clusteredSchools\node_modules\webpack\lib\Compiler.js:365:9)`

I am using this package.json :
` "dependencies": {
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@ionic/storage": "2.1.3",
    "ajv": "^5.5.0",
    "buffer-compare": "^1.1.1",
    "chai": "^4.1.2",
    "ionic-angular": "3.9.2",
    "ionic-native": "^2.9.0",
    "ionicons": "^4.1.2",
    "ipfs": "^0.29.3",
    "ipfs-pubsub-room": "^1.3.0",
    "leveldown": "^4.0.1",
    "rxjs": "^5.5.0",
    "sw-toolbox": "3.6.0",
    "wrtc": "^0.1.4",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.9",
    "typescript": "2.4.2"
  },`

Any fixe to this problem? Does anyone have a clue about how to solve this issue?
