### ISSUE TITLE
How can I run node as daemon?

### ISSUE THREAD

**Issue by Vladislav719** [ipfs/js-ipfs#820]
Is it alternative for **jsipfs daemon** command?
```
// Create the IPFS node instance
const node = new IPFS()

node.on('start', () => {
  // Your now is ready to use \o/

  // stopping a node
  node.stop(() => {
    // node is now 'offline'
  })
})
```

If yes, how can I start it and working with API
**node index.js** ?

**Comment by diasdavid** [comment]
@Vladislav719 'almost', starting that way you get an instance, if you want the HTTP API you need to start an HTTP API with https://github.com/ipfs/js-ipfs/blob/master/src/http-api/index.js. You can see code that does that here: https://github.com/ipfs/js-ipfs/blob/master/test/utils/ipfs-factory-daemon/index.js

**Comment by diasdavid** [comment]
@Vladislav719 let me know if you had any trouble, otherwise, closing this issue :)
