### ISSUE TITLE
Connect to running "ipfs daemon"

### ISSUE THREAD

**Issue by nxtpool** [ipfs/js-ipfs#829]
Is it possible to connect to already running daemon instance not creating new one?

**Comment by diasdavid** [comment]
Absolutely, have you tried it? Let me know if you have hit any obstacle.

**Comment by diasdavid** [comment]
You can check examples of this here https://github.com/ipfs/js-ipfs-api/tree/master/examples

Let me know if you ran into any issue, closing this one for now :)
