### ISSUE TITLE
Runtime Support: Cordova

### ISSUE THREAD

**Issue by xSkyripper** [ipfs/js-ipfs#834]
Hello.

Is it possible to start a js-ipfs daemon properly in a cordova app on android ?

More exactly, I used the script tag in my main html and added the js code for the daemon to start.
The app starts fine, the daemon seems to start too but I have no discovery at all.
Swarm peers returns an empty array and I also cannot find the specific device's ID from a linux machine connected to the same router.

EDIT 1: The linux machine uses go-ipfs and the android device uses js-ipfs. Is this a problem ... ?
EDIT 2: Can 2 js-ipfs browser nodes communicate ? I tested this locally and it seems there is no trace of discovery or connection ... I don't know if I didn't understand completely but what exactly does and doesn't work in this implementation ?

The purpose of this issue is to find a way of implementing an Android app using IPFS. One of the most important things is that I NEED it to work in LANs.

**Comment by diasdavid** [comment]
Same suggestion I made for https://github.com/ipfs/js-ipfs/issues/802#issuecomment-326580387, if you come up with an example of how to do the set up, I'm happy to help you figure out the rest.

**Comment by inspiraluna** [comment]
It could be a classic "Content-Security-Policy" problem which you could try to solve in cordovas index.html or in the whitelist plugin? I am just wondering because, I am planing to try js-ipfs in Cordova for a project.

**Comment by SgtPooki** [comment]
Hello @xSkyripper & @DecentraSol,

We regret to inform you that the issue you reported will not be resolved in js-ipfs as we are in the process of deprecating it. However, it is highly likely that the issue has been addressed in our new library, [helia](https://github.com/ipfs/helia). Although we haven't explicitly tested this particular issue, [helia](https://github.com/ipfs/helia) is designed to improve upon the limitations of js-ipfs. Our migration guide is available at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

We kindly request you to attempt using https://github.com/ipfs/helia to address your specific use case. If you encounter any further issues or require additional assistance, please feel free to open an issue in the helia repository.

We appreciate your understanding and cooperation during this transition period. Thank you for considering helia as a potential solution.

Best regards,
@ipfs/helia-dev
