### ISSUE TITLE
Unable to get / put objects sequentially

### ISSUE THREAD

**Issue by gaieges** [ipfs/js-ipfs#836]
This may be a noob question, but for some reason I'm unable to `put` and object into the store, and then simply `get` it right after. Here's what I'm working with as a simple demo:

```js
var IPFS = require('ipfs');

var ipfs = new IPFS({start: true, init: true})

var obj = {
  Data: new Buffer('awesome data here 123556'), 
  Links:[]
};


var meh = ipfs.on('ready', () => {
  ipfs.object.put(obj,(putErr,putNode) => { 
    if( putErr )
      return console.error(putErr)

    var hash = putNode.toJSON().multihash

    console.log("successfully put: %s", hash );

    ipfs.object.get(hash,(gotErr, gotNode) => {
      if( gotErr )
        return console.error(gotErr)

      console.log( "successfully got: %s", gotNode.toJSON() ); 
    })
  })

})
```

Theoretically based on my understanding, this should work fine - it should put the object (which it does successfully) and then spit it out again.  However what I'm seeing is that it hangs when `get`'ing the object, even when running on the same host.  

Any thoughts?

**Comment by diasdavid** [comment]
Hi @gaieges, there was indeed a bug that was fixed with https://github.com/ipfs/js-ipfs/pull/849 by @kenshyx, you should not see this problem anymore. Thanks for the report :)

**Comment by gaieges** [comment]
Confirmed this fixed it, thank you! (Sorry for the delay)

**Comment by diasdavid** [comment]
Thanks! :)
