### ISSUE TITLE
object.patch.addLink not returning

### ISSUE THREAD

**Issue by kenshyx** [ipfs/js-ipfs#838]
If no encoding is specified, ex `{enc: 'base58'}`, this method never returns.
`Node version: 7.4.0`

**Comment by kenshyx** [comment]
Same issue for `object.links`

**Comment by diasdavid** [comment]
Thanks for reporting! Would you like to help us fixing it by adding some tests to https://github.com/ipfs/interface-ipfs-core/blob/master/src/object.js#L668 ?

**Comment by kenshyx** [comment]
Can you guide me to some docs, where can I find an `IPFSFactory` simple example? I found something on `js-ipfs-api` but there should be something out of the box available that I can plug and write the tests :)

**Comment by diasdavid** [comment]
Absolutely, the simplest way is to:

```
# git clone https://github.com/ipfs/js-ipfs
# git clone https://github.com/ipfs/interface-ipfs-core
# inside interface-ipfs-core folder
> npm install
> npm link
# inside js-ipfs folder
> npm install
> npm link interface-ipfs-core
# then simply modify the tests on the interface-ipfs-core object.js file --
 https://github.com/ipfs/interface-ipfs-core/blob/master/src/object.js#L17-L35 -- and then to run the do `npm test` in the js-ipfs folder.
```

**Comment by kenshyx** [comment]
I found the problem, when I'm passing an ipfs hash as string and I'm not specifying any encoding it silent fails. [This](https://github.com/kenshyx/js-ipfs/commit/7b3caefcee1a6fab9bd40b40459d2353dbe5a374) solves the problem. Should I open a pull request? Also I'm preparing some tests for interface-ipfs-core regarding this issue.

**Comment by diasdavid** [comment]
@kenshyx yes please :) thanks for catching that!

**Comment by diasdavid** [comment]
@kenshyx I believe this all got fixed and tests are https://github.com/ipfs/interface-ipfs-core/pull/139, correct?

Closing this issue, let me know if I missed something.
