### ISSUE TITLE
Chrome slowdown (WebRTC)

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#840]
Noticed a serious communication speed degradation when window is on a background tab.

Here is a video demonstrating this, where I used the example [here](https://github.com/pgte/ipfs-iiif-db/tree/master/examples/simple-producer-consumer) : https://youtu.be/dnlNOxDQ3H0

[Here you can find the IPFS config](https://github.com/pgte/ipfs-iiif-db/blob/master/src/start.js#L6-L18).

Using Chrome 58.0.3029.96 (64-bit) on macOS 10.12.4

**Comment by VictorBjelkholm** [comment]
Hm, noticed some slowness in Chrome as well, filled here: https://github.com/ipfs/js-ipfs/issues/611

Also, when tabs are in the background, Chrome slows everything down, and I don't think there is a workaround for that, unless you use a webworker.

**Comment by diasdavid** [comment]
@pgte investigated more of this and concluded that this is due to Chrome's aggressive resource throttling policies

https://thenextweb.com/apps/2017/01/26/chrome-throttle-background-tabs-google/#.tnw_WzhZt1q4

**Comment by diasdavid** [comment]
Let's close this one and continue the convo here: https://github.com/ipfs/js-ipfs/issues/611
