### ISSUE TITLE
electron-rebuild error

### ISSUE THREAD

**Issue by kenshyx** [ipfs/js-ipfs#842]
I tried to use js-ipfs from my electron app and everytime I try to rebuild it using `electron-rebuild` I get this [error](https://gist.github.com/kenshyx/08aa6d7df0fd4a23f382a4fd411ff359). It might be a dependency of js-ipfs which uses `execSync`, similar issue [here](https://github.com/mgutz/execSync/issues/20). Any thoughts?

**Comment by diasdavid** [comment]
Electron uses it's own version build of Node.js, causing a disparity in the binaries compiled by your own Node.js version and the one it uses.

This solved @kyledrake's issues https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md let me know if it works for you.

**Comment by kenshyx** [comment]
I have a proper build environment for electron, the problem is that package that can't be built(execSync).

**Comment by kenshyx** [comment]
I found it, it's from [aegir](https://github.com/dignifiedquire/aegir) package, it uses this old [execSync](https://github.com/mgutz/execSync) package, deprecated a long time ago. Also this package should be a dev dependency of [ipld-eth-storage-trie](https://github.com/ipld/js-ipld-eth-storage-trie/blob/master/package.json)

**Comment by diasdavid** [comment]
Hi! I started working on electron support, track it in https://github.com/ipfs/js-ipfs/issues/843

**Comment by kumavis** [comment]
@kenshyx the aegir dep should be resolved. moved ethereum resolvers to new repo github.com/ipld/js-ipld-eth-star

**Comment by diasdavid** [comment]
Let's keep tracking it here: https://github.com/ipfs/js-ipfs/issues/843#issuecomment-317236407
