### ISSUE TITLE
pubsub scheme subject to timing?

### ISSUE THREAD

**Issue by shuangjj** [ipfs/js-ipfs#846]
When node A subscript to TOPIC, nodes B, C, D are online and they can publish to TOPIC so that A can receive. If node E goes online after A subscribe to TOPIC, even E publishes message to TOPIC, A can not receive the message in this case. Is this correct for current development of pubsub protocol on ipfs? Is there a way to store and relay subscriptions like mqtt's broker scheme?

**Comment by diasdavid** [comment]
@shuangjj subscriptions are being propagated on connect, but it is an async operation, you are probably just seeing that happening on a 'warm up period'. Try use a setTimeout to double check.

**Comment by shuangjj** [comment]
@diasdavid Thanks! It makes sense A doesn't get the message since E haven't updated its subscriber including A. Then there's a great chance A misses the message if E publishes message without checking the number of the subscribers.

**Comment by diasdavid** [comment]
Correct. The current implementation of PubSub (FloodSub) doesn't guarantee delivery. We are looking for ways to do that, see more on https://github.com/libp2p/research-pubsub
