### ISSUE TITLE
ipfs-address in the browser

### ISSUE THREAD

**Issue by ticruz38** [ipfs/js-ipfs#847]
I am using ipfs in the browser, I just figured out that my browser node does not connect to peers except when I explicitly connect with ipfs.swarm.connect(address). After that I got one peer connected to my browser node.
I am also unable to get my browser node address, the field multiaddress is always an empty list.

Is that a normal behaviour, is there any configuration needed to get my browser node discoverable by the ipfs network? How could I get my browser node address?

**Comment by VictorBjelkholm** [comment]
Take a look at the example "Transfer Files" which shows how you can use a Signaling Server to help nodes to find each others: https://github.com/ipfs/js-ipfs/blob/637250d0faca4f50025e48397149afbd0d99588b/examples/transfer-files/public/js/app.js#L37-L46

There is also bootstrap nodes on the way, which would help as well.

**Comment by diasdavid** [comment]
Following on what @VictorBjelkholm already explained.

> browser node does not connect to peers 

If you try the latest js-ipfs from github master, it will auto connect to bootstraper nodes, this feature hasn't been released yet

> discover other nodes

As @VictorBjelkholm suggested, you need to enable the WebRTC transport for that

> I am also unable to get my browser node address, the field multiaddress is always an empty list.

That is because you are just using WebSockets in the browser, which doesn't have a listener, it can only dial.

**Comment by ticruz38** [comment]
thank you for your helpful answer, I couldn't find a suitable example in the test folder to up and download file from ipfs, the one you shared works just as expected.

**Comment by ticruz38** [comment]
I've enabled webRTC, so now my peers do have address and browser nodes connect directly to each other.
But it seems like webRTC enabled node can't share data via block or file api. Only the pubsub seems to work.
Is this a normal behaviour? Something in the configuration to enable block and file sharing via webRTC?

**Comment by diasdavid** [comment]
They should be able to share it, see the example https://github.com/ipfs/js-ipfs/tree/master/examples/transfer-files

Note, if you are using Chrome, you might need to open two windows due to Chrome's throttling policy https://github.com/ipfs/js-ipfs/issues/611

**Comment by ticruz38** [comment]
they do open a connection through the file api, but it's as if the stream object were damaged. it either never ends or ends up with such error.
```console
DOMException: The JWK's "y" member defines an octet string of length 31 bytes but should be 32
index.js:27 Error: Stream ended prematurely
```
I'm trying to transfer image files (png, jpg) as shown in this [sample](https://github.com/ipfs/js-ipfs/blob/637250d0faca4f50025e48397149afbd0d99588b/examples/transfer-files/public/js/app.js#L37-L46) 
the files resolve when they are already stored in the node repo, but not when transferring from other nodes.

**Comment by diasdavid** [comment]
Do you have success using the example? As in, did you manage to transfer files using it?

**Comment by ticruz38** [comment]
I just tried the transfer file sample. I do have the same problems. I opened 2 chrome windows and launched a desktop websocket enabled node. connected my two browser node together and with the desktop node.
Uploading and fetching file in the same window works. Fetching a file from the other window dont.
I tried with different connection, wifi and mobile data, the result is the same.
### When fetching data from the other window:
The ipfs.files.get function does resolve with a stream full of data, but I can't sink it without error. it sink eternally or send an error.
