### ISSUE TITLE
Question about application management utilities for IPFS

### ISSUE THREAD

**Issue by prettydiff** [ipfs/js-ipfs#854]
I have this application distribution utility that I have written: https://github.com/prettydiff/biddle .  In an upcoming version I plan to fully transition from HTTP to IPFS https://github.com/prettydiff/biddle/issues/50 .  All this work will be unnecessary if a better solution is already present.  A solution to application management already exist for IPFS?

Here is a brief run down of biddle design goals:
* Identical commands cross operating systems
* complete management of applications by name, version, local file system location
* publication of applications in various forms
* application installation: fetch the data, run any specified install/configuration steps as defined in an application's package.json file
* simplified status checks (determine if an installed application is out of date by a simple command and only update as necessary)
* no central repository

**Comment by diasdavid** [comment]
Hi @prettydiff, apologies for the silence here. This is not the best repo for that question, could you open this issue on https://github.com/ipfs/notes/issues ? 

Thank you!
