### ISSUE TITLE
webRTCStar discovery disabled by default

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#858]
Against current master, to use webRTCStar discovery I had to set `config.Discovery.webRTCStar.Enabled` to `true`, even though I had `config.Addresses.Swarm` set to `['/libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss']`.

I think this wasn't necessary before.
If not a bug, perhaps it should be added to the instructions.

**Comment by diasdavid** [comment]
@pgte could you check your repo to see if this flag is correctly set? https://github.com/ipfs/js-ipfs/blob/master/src/init-files/default-config-browser.json#L15

**Comment by diasdavid** [comment]
I can see there is something, although discovery seems to be working:

![image](https://cloud.githubusercontent.com/assets/1211152/26285247/d42a3aae-3e19-11e7-81de-ee3c4fee438e.png)

I don't get to have two nodes in different Chrome windows (or even one using Firefox) to see each other. This could be related with the new SS set up https://github.com/libp2p/js-libp2p-webrtc-star/pull/111. Do you see the same behaviour?

**Comment by diasdavid** [comment]
Interesting, it might be my current network configuration (in a coffee shop). The ICE is not working between browser to browser but browser to `wrtc` works flawlessly.

**Comment by VictorBjelkholm** [comment]
@diasdavid 
> @pgte could you check your repo to see if this flag is correctly set? https://github.com/ipfs/js-ipfs/blob/master/src/init-files/default-config-browser.json#L15

Seems like in that file, the property `Discovery` is overwritten with `{}`

**Comment by diasdavid** [comment]
You have to check what is the loaded config. Note, Discovery works, just to show added a console log on peers found:

![image](https://cloud.githubusercontent.com/assets/1211152/26286657/a3dccbb8-3e38-11e7-85dd-b0789dff7f76.png)

**Comment by diasdavid** [comment]
Still, no clue why 2 peers in the same machine are not finding each other. If we dial manually using connect, they dial successfully and exchange files.

**Comment by diasdavid** [comment]
yeah, WebRTCStar Discovery is not being enabled :( hte whole Discovery disappears

**Comment by diasdavid** [comment]
Ok, so I narrowed down the problem to this:

![image](https://cloud.githubusercontent.com/assets/1211152/26286837/62b5a41c-3e3c-11e7-99bd-24423da8bef3.png)

For some reason, the `require('location of config')` is yielding a config that has no keys on the Discovery property

**Comment by diasdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/1211152/26286858/b80992f2-3e3c-11e7-9715-1403ff188059.png)

**Comment by VictorBjelkholm** [comment]
<img width="845" alt="image" src="https://cloud.githubusercontent.com/assets/459764/26286863/18dda294-3e6f-11e7-8db2-2359015671bf.png">

;)

**Comment by diasdavid** [comment]
When I read "overwritten" I understood that somewhere in the code that was happening. thanks :)
