### ISSUE TITLE
node js ipfs on windows 

### ISSUE THREAD

**Issue by nezzard** [ipfs/js-ipfs#861]
Hi, i'm tried to install ipfs from npm on windows 10, but i always get an errors. So i have question, can i install ipfs on windows, or it's only for linux?

**Comment by VictorBjelkholm** [comment]
Don't think there is something that should stop it from working, but not sure how well tested js-ipfs is on windows. It'll help a lot of you post a full log of the errors and also the output from `npm version`

**Comment by nezzard** [comment]
`npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.3',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.101',
  zlib: '1.2.11' }`

And npm install log
`npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\Yura\AppData\Roaming\npm\jsipfs -> C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\src\cli\bin.js

> fs-ext@0.6.0 install C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\node_modules\fs-ext
> node-gyp configure build


C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  fs-ext.cc
  win_delay_load_hook.cc
..\fs-ext.cc(196): error C2079: 'lk' uses undefined struct 'EIO_Fcntl::flock' [C:\Users\Yura\AppData\Roaming\npm\node_m
odules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(197): error C2228: left of '.l_start' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\node
_modules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(197): note: type is 'int'
..\fs-ext.cc(198): error C2228: left of '.l_len' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\node_m
odules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(198): note: type is 'int'
..\fs-ext.cc(199): error C2228: left of '.l_type' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\node_
modules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(199): note: type is 'int'
..\fs-ext.cc(200): error C2228: left of '.l_whence' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\nod
e_modules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(200): note: type is 'int'
..\fs-ext.cc(201): error C2228: left of '.l_pid' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\node_m
odules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(201): note: type is 'int'
..\fs-ext.cc(204): error C2065: 'F_GETLK': undeclared identifier [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\n
ode_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(204): error C2065: 'F_SETLK': undeclared identifier [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\n
ode_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(204): error C2065: 'F_SETLKW': undeclared identifier [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\
node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(205): error C2065: 'F_SETLK': undeclared identifier [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\n
ode_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(205): error C2065: 'F_SETLKW': undeclared identifier [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\
node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(206): error C2228: left of '.l_whence' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\nod
e_modules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(206): note: type is 'int'
..\fs-ext.cc(207): error C2228: left of '.l_type' must have class/struct/union [C:\Users\Yura\AppData\Roaming\npm\node_
modules\ipfs\node_modules\fs-ext\build\fs-ext.vcxproj]
  ..\fs-ext.cc(207): note: type is 'int'
..\fs-ext.cc(209): error C3861: 'fcntl': identifier not found [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\node
_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(211): error C3861: 'fcntl': identifier not found [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\node
_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(391): error C3861: 'fcntl': identifier not found [C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\node
_modules\fs-ext\build\fs-ext.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Yura\AppData\Roaming\npm\node_modules\ipfs\node_modules\fs-ext
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\Yura\AppData\Roaming\npm
`-- ipfs@0.23.1
  +-- async@2.4.1
  +-- glob@7.1.2
  +-- ipfs-repo@0.13.0
  | `-- level-js@2.2.3  (git://github.com/timkuijsten/level.js.git#18e03adab34c49523be7d3d58fafb0c632f61303)
  +-- ipld-resolver@0.11.0
  | `-- ipld-eth-storage-trie@1.0.1
  |   `-- aegir@9.4.0
  |     +-- gulp-uglify@2.1.2
  |     | `-- make-error-cause@1.2.2
  |     |   `-- make-error@1.3.0
  |     +-- istanbul@0.4.5
  |     | `-- handlebars@4.0.10
  |     `-- mocha@3.4.1
  |       `-- glob@7.1.1
  +-- libp2p-floodsub@0.7.5
  | `-- libp2p-crypto@0.8.8
  |   `-- webcrypto-shim@0.1.1  (git://github.com/dignifiedquire/webcrypto-shim.git#effe03d3401ccbfb4837191bc393bb347e0c0f0a)
  +-- libp2p-ipfs-browser@0.20.1
  | +-- libp2p-multiplex@0.4.3
  | | `-- multiplex@6.7.0  (git://github.com/dignifiedquire/multiplex.git#b5d5edd30454e2c978ee8c52df86f5f4840d2eab)
  | `-- libp2p-webrtc-star@0.8.10
  |   `-- wrtc@0.0.61
  |     `-- download@5.0.3
  |       `-- decompress@4.2.0
  |         `-- decompress-targz@4.1.0
  |           `-- file-type@4.3.0
  `-- uglify-es@3.0.10  extraneous (git://github.com/mishoo/UglifyJS2.git#a658cd84a53f7d4320eeb3c8747087ef38ed3d10)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ipfs\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.6.0 (node_modules\ipfs\node_modules\fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.6.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1`

**Comment by diasdavid** [comment]
Hi @nezzard, thanks for reporting. This is a known issue with some proposed PR changes:

- https://github.com/ipfs/interface-datastore/pull/5
- https://github.com/ipfs/interface-datastore/pull/6

Wanna help us fix this issue? I need to get a Windows VM set up and won't have fast enough connectivity this week to download the full image.

**Comment by nezzard** [comment]
I tried to make fix from ipfs/interface-datastore#5 but nothing work, i have the same error like before

**Comment by mkg20001** [comment]
> Wanna help us fix this issue? I need to get a Windows VM set up and won't have fast enough connectivity this week to download the full image.
Or you can try https://www.appveyor.com/

**Comment by diasdavid** [comment]
There has been a fixed pushed, merged and released for interface-datastore. Could you confirm if this works now for you?

**Comment by nezzard** [comment]
Just npm install ipfs?
If yes, it's not working

**Comment by diasdavid** [comment]
Oh, that is because I never released the new interface-datastore, shame on me. Try again now :)

**Comment by nezzard** [comment]
Did npm uninstall ipfs than install and now get the same error Invalid key: \SHARDING

**Comment by download13** [comment]
Hey, I'd really like to help get js-ipfs running on windows.

To that end I made a pull request to update the dependency of a dependency of this project: https://github.com/ipld/js-ipld-resolver/pull/83

Once that's merged and published the dependency version on here can be updated and we can start looking at whatever the next windows-related bug will be.

**Comment by diasdavid** [comment]
@download13 which version of npm are you using? You shouldn't have this issue since `interface-datastore` was published as a patch version and ipld-resolver is using semver for that dep.

Could you try doing a fresh npm install on this repo?

**Comment by download13** [comment]
I tried it just now. Still getting

```
Error: Invalid key: \SHARDING
    at new Key (C:\Users\download\Desktop\js-ipfs\node_modules\datastore-core\node_modules\interface-datastore\src\key.js:42:13)
    at Object.<anonymous> (C:\Users\download\Desktop\js-ipfs\node_modules\datastore-core\src\sharding.js:12:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\download\Desktop\js-ipfs\node_modules\datastore-core\src\index.js:5:27)
```

**Comment by download13** [comment]
Isn't this using a package-lock.json file? I thought you had to update them somehow as the dependencies specified there will always be installed.

**Comment by diasdavid** [comment]
Which version of npm are you using?

**Comment by download13** [comment]
5.0.3

I tried directly replacing `interface-datastore@0.2.1` with 0.2.2 in the `package-lock.json` file.

It turns out `datastore-fs` and `datastore-core` both depend on an old version of `interface-datastore` (0.1.1) so I swapped those out for the new entry as well.

Now the interface-datastore package seems to work fine, but it's giving the following error when I try to build:

```
Error: Cannot find module 'catbox-memory'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\download\code\open_source\js-ipfs\node_modules\hapi\lib\server.js:6:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Which doesn't make a lot of sense as I checked that `catbox-memory` does exist in both the `package-lock.json` file and in the `./node_modules/hapi/node_modules` directory,

**Comment by diasdavid** [comment]
@download13 that is npm 5 doing its thing, you can delete the local cache or just simply delete the package-lock.json for now.

**Comment by nezzard** [comment]
I still get the same error

**Comment by yaananth** [comment]
+1
npm version `5.3.0`
> const IPFS = require('ipfs')
Error: Invalid key: \SHARDING
    at new Key (E:\test\node_modules\datastore-core\node_modules\interface-datastore\src\key.js:42:13)
    at Object.<anonymous> (E:\test\node_modules\datastore-core\src\sharding.js:12:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\test\node_modules\datastore-core\src\index.js:5:27)

**Comment by yaananth** [comment]
bump in` ipfs-repo` happened just two days ago
https://github.com/ipfs/js-ipfs/commit/bc8ffee85c9468813278e0d2f5890c0c3d5f2678

**Comment by diasdavid** [comment]
@yaananth could you try running directly from the repo?

```
> git clone https://github.com/ipfs/js-ipfs
> cd js-ipfs
> npm install
# then try one of the examples
```

**Comment by yaananth** [comment]
I guess so, atleast I didn't get that `SHARDING `error
```
 MINGW64 /d/Github Repositories/js-ipfs/examples/basics (master)
$ node index.js
D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:90
                    throw err0;
                    ^

Error: EEXIST: file already exists, mkdir 'C:\Users\testUser\AppData\Local\Temp'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:71:13)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:77:24)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
    at sync (D:\Github Repositories\js-ipfs\node_modules\mkdirp\index.js:78:17)
```

**Comment by nezzard** [comment]
`      throw new Error(`Invalid key: ${this.toString()}`)
      ^

Error: Invalid key: /CIQFX22I3H5YK5MYQ4PI63M2UKZVJOP5K63QSXHXEIWE4GSQ6LC4UMQ
    at new Key (C:\ipfs\node_modules\interface-datastore\src\key.js:45:13)
    at keyFromBuffer (C:\ipfs\node_modules\ipfs-repo\src\blockstore.js:20:10)
    at cidToDsKey (C:\ipfs\node_modules\ipfs-repo\src\blockstore.js:30:10)
    at Object.has (C:\ipfs\node_modules\ipfs-repo\src\blockstore.js:129:17)
    at waterfall (C:\ipfs\node_modules\ipfs-bitswap\src\index.js:237:31)
    at nextTask (C:\ipfs\node_modules\async\waterfall.js:16:14)
    at exports.default (C:\ipfs\node_modules\async\waterfall.js:26:5)
    at Bitswap.put (C:\ipfs\node_modules\ipfs-bitswap\src\index.js:236:5)
    at BlockService.put (C:\ipfs\node_modules\ipfs-block-service\src\index.js:61:28)
    at waterfall (C:\ipfs\node_modules\ipld-resolver\src\index.js:351:28)`

**Comment by diasdavid** [comment]
[Windows Support main issue](https://github.com/ipfs/js-ipfs/issues/1017)

**Comment by download13** [comment]
Just to make sure, these keys are only over used on one computer, correct?

I mean, a key isn't constructed on one machine, then sent to another machine.

**Comment by diasdavid** [comment]
@download13 correct. Key is used as the path and it is only known to the repo.

**Comment by download13** [comment]
@diasdavid So repos are not intended to be moved between machines? In that case is there a way to import/export all the important data in a repository? I know about the `ipfs key` commands, but can you easily bring over pinned hashes/ipns bindings/etc?

Sorry that's a little off topic, it just seems like something to consider if you can't assume a repo created on one machine will work on another.

**Comment by diasdavid** [comment]
@download13 a repo from a machine should be usable in another machine if the OS is the same or if some migration happens.

`ipfs key` is not related to Repo keys. an IPFS Repo uses internally multiple instances of storage drivers that use interface-datastore which is an interface for a key value store, the _key_ in IPFS Repo comes from Key Value Store

**Comment by download13** [comment]
@diasdavid So if I wanted to move a repo from a windows computer over to a linux vps, I'd be outta luck?

**Comment by diasdavid** [comment]
@download13 you work out of the box

**Comment by diasdavid** [comment]
## Windows support is here! Celebrate with us at https://github.com/ipfs/js-ipfs/issues/1017#issuecomment-343568369
