### ISSUE TITLE
Needed documentation: Begin with js-ipfs cli 

### ISSUE THREAD

**Issue by mathpunk** [ipfs/js-ipfs#871]
Hi, I've been interested in this project very near the beginning, but it's only recently that I've skilled up enough as a dev to have a hope of helping out.

I decided I wanted to experiment with ipfs nodes on my machines, and so I went to the [basic example](https://github.com/ipfs/js-ipfs/tree/master/examples/basics) page, and while the code has been touched recently there's no story about what it means.

I ran js-ipfs and got the readme to `cat` out, but I don't know how to get the other files mentioned in the readme. So, I'm stuck there too.

If I can get a hint on what to do next, I would be happy to write up what I learn and submit a pull request to the examples, or wherever else such documentation should go.

**Comment by diasdavid** [comment]
Hi @mathpunk, welcome!

You aren't being able to cat subfiles due to https://github.com/ipfs/js-ipfs/issues/837, wanna try take a stab at it?

**Comment by mathpunk** [comment]
Stabbing away!

**Comment by diasdavid** [comment]
Oh, forgot to update this one. Now you can cat subfiles! :D 

https://github.com/ipfs/js-ipfs/pull/875

Closing! :)
