### ISSUE TITLE
expose repo directly

### ISSUE THREAD

**Issue by wanderer** [ipfs/js-ipfs#876]
if application have a minumal set of information they need to store outside of ipfs, it might make sense for them to use the repo.store, instead of creating a seperate db.

**Comment by diasdavid** [comment]
I wouldn't recommend anyone to do that, you would be messing IPFS usage of the repo, things like delete/move keys that IPFS is using, messing with the locks, or even lock the repo indefinitely could happen if the developers aren't really careful.

**Comment by wanderer** [comment]
kk
