### ISSUE TITLE
in pubsub self initialized with ._pubsub undefined

### ISSUE THREAD

**Issue by alienatorZ** [ipfs/js-ipfs#877]
I am experimenting with ipfs and orbitdb but encountering some errors on pubsub. It seems that under the 'subscribe' function it uses self._pubsub which is undefined. below is my code for a test case.

Thanks,
AlienatorZ

const IPFS = require('ipfs');
const OrbitDB = require('orbit-db');

const ipfs = new IPFS();
const orbitdb = new OrbitDB(ipfs);

ipfs.on('ready', () => {

        const db = orbitdb.kvstore('application.settings')
	
	db.load()

  // Your now is ready to use \o/

  // stopping a node
 // ipfs.stop(() => {
    // node is now 'offline'
 // })
})

**Comment by diasdavid** [comment]
@alienatorZ I believe that is due to orbit being out of date. You probably have to use js-ipfs 0.22 still. 

I've opened this issue https://github.com/orbitdb/orbit-db/issues/221 (leads to others) to report the need to update. Wanna take a stab at updating orbit? @haadcode what do you think?

**Comment by AshlessCinder** [comment]
It's set to undefined on master.
https://github.com/ipfs/js-ipfs/blob/master/src/core/index.js#L72

**Comment by VictorBjelkholm** [comment]
Yeah, it's `undefined` unless you set the correct config when starting the node. See https://github.com/ipfs/js-ipfs/blob/7e21054c3a6ea7baf49be515ecb1cc31d926384f/src/core/components/start.js#L53

**Comment by alienatorZ** [comment]
I was able to get it to work, finally. I manually connected to swarm peers and it seems to be working now.

Here is my code:

'''
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS({
  init:true,
  // init: false,
  // init: {
  //   bits: 1024 // size of the RSA key generated
  // },
  start: true,
  // start: false,
  EXPERIMENTAL: { // enable experimental features
    pubsub: true,
    sharding: true, // enable dir sharding
    wrtcLinuxWindows: true, // use unstable wrtc module on Linux or Windows with Node.js,
    dht: true // enable KadDHT, currently not interopable with go-ipfs
  },
  config: { // overload the default config
    Addresses: {
      Swarm: [
        '/ip4/0.0.0.0/tcp/1337'
      ]
    }
  }
})

ipfs.on('error', (e) => console.error(e))
ipfs.on('ready', (e) => {

  ipfs.swarm.connect('/ip4/192.168.56.102/tcp/1337/ipfs/QmcKh1YKwkQP1rjhF8HnzfRDhpDzXgF2HjceE1sw6yC4tw', function (err) {
    if (err) {
        console.log('error:'+err);
    }
    
  })

 ipfs.swarm.connect('/ip4/192.168.56.1/tcp/4001/ipfs/QmfTbMXoBVzYxxV8w6XG34im8QQnDmWSZ7uTVRqpnGx9hr', function (err) {
    if (err) {
    }
   
  })


  const orbitdb = new OrbitDB(ipfs)
 
  const db = orbitdb.docstore("application",{ indexBy: 'name' })
  db.load();
  db.events.on('synced', function(){
    console.log('synced')
     
 })


 //Database is Ready... Do stuff..
 	db.events.on('ready', () => {
    console.log('db ready')
    
    const all = db.query((doc) => doc.followers >= 5)
      console.log(all)
        db.put({ _id: 'QmAwes345345fsdfdf2', name: 'dsdfdfq34ffs2', followers: 222 }).then((hash) => {
        console.log('put:'+hash);
        orbitdb._pubsub.publish(db.dbname, db._oplog.heads)
   })

  })
  

    //Constant replication
     setInterval(function(){
     //   orbitdb._pubsub.publish(db.dbname, db._oplog.heads)
      },5000)
    
    


})
'''


I recommend closing this issue. Thank you all for your support and contributing to these awesome projects!

**Comment by diasdavid** [comment]
Nice! Make sure to also check the work at https://github.com/pgte/ipfs-iiif-db done by @pgte, I think you will be interested!
