### ISSUE TITLE
examples/transfer-files doesn't work

### ISSUE THREAD

**Issue by jmc265** [ipfs/js-ipfs#905]
The transfer-files example fails in Chrome when you click the Start button with this error:

```
Uncaught TypeError: createServer is not a function
    at module.exports (ipfs.js:86708)
    at WebSockets.createListener (ipfs.js:86675)
    at ipfs.js:83956
    at ipfs.js:35190
    at eachOfArrayLike (ipfs.js:25480)
    at exports.default (ipfs.js:25424)
    at _parallel (ipfs.js:35189)
    at parallelLimit (ipfs.js:10477)
    at Object.listen (ipfs.js:83976)
    at each (ipfs.js:83605)
```

There are the steps to reproduce:
```
git clone https://github.com/ipfs/js-ipfs.git js-ipfs
cd js-ipfs
npm install
npm run build
cd examples/transfer-files/
npm install
npm start
In browser navigate to http://127.0.0.1:12345/
In web app, click 'Start IPFS' button
Observe error in web console
```

**Comment by jmc265** [comment]
Replacing
`<script src="js/ipfs.js"></script>`
with
`<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>`
in examples/transfer-files/index.html
is a work-around.

**Comment by diasdavid** [comment]
thanks for the report @jmc265, looking into this! :)

**Comment by diasdavid** [comment]
found the issue. It should have been `.json` and not `.js` at https://github.com/ipfs/js-ipfs/blob/master/package.json#L11. Pushing a fix :)

**Comment by diasdavid** [comment]
fix here https://github.com/ipfs/js-ipfs/pull/906
