### ISSUE TITLE
Linting issues

### ISSUE THREAD

**Issue by sktt** [ipfs/js-ipfs#917]
```
$ node -v
v6.11.1

$ npm -v
3.10.10

$ DEBUG=* npm run lint                                           

> ipfs@0.25.0 lint /home/jnes/code/ipfs/js-ipfs
> aegir-lint

[19:18:24] Starting 'lint'...
  eslint:ignored-paths Looking for ignore file in /home/jnes/code/ipfs/js-ipfs +0ms
  eslint:ignored-paths Could not find ignore file in cwd +2ms
  eslint:config Using command line config /home/jnes/code/ipfs/js-ipfs/node_modules/aegir/tasks/../config/eslintrc.yml +1ms
  eslint:config-file Loading YAML config file: /home/jnes/code/ipfs/js-ipfs/node_modules/aegir/config/eslintrc.yml +1ms
  eslint:config-file Loading standard +66ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /home/jnes/code/ipfs/js-ipfs/node_modules/eslint-config-standard/index.js +0ms
  eslint:plugins Failed to load plugin eslint-plugin-node. +37ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

running `npm install --save-dev eslint-plugin-{standard,node}` appears to solve the problem.

After linting runs I get alot of 
```
error  'new Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead  node/no-deprecated-api
```
What's your opinion on this? 

a. ignore or move to warning
b. drop <4.5 support and replace `new Buffer()` instances with `alloc()` and `from()`
c. install safe-buffer

**Comment by diasdavid** [comment]
`npm run lint` is successful for me without having to install any other module. Using:

```
» node -v
v7.10.0
» npm -v
4.2.0
```

CI is also fine.

We have been using `const Buffer = require('safe-buffer').Buffer` to support Node.js 4, did we miss it somewhere?

**Comment by sktt** [comment]
Oh! I only got those errors because I manually installed deps manually and thus got a later version of eslint-config-standard...... https://github.com/ipfs/js-ipfs/pull/918 that adds safe-buffer everywhere.. but the linter doesn't check for it so not really necessary.
