### ISSUE TITLE
Tests failing randomly

### ISSUE THREAD

**Issue by rasmuserik** [ipfs/js-ipfs#935]
- **Version**: latest github as of 2017-07-24
- **Platform**: travis and local (slow) linux computer
- **Subsystem**: testing

#### Type: 
chore
#### Severity: 
medium
#### Description:

Tests fails randomly, both for pull requests (#933) on travis, i.e. https://travis-ci.org/ipfs/js-ipfs/builds/256931792, and when running tests during development.

The actual point of failing varies, but it looks as if it is due to timeouts, or processes that have not had time to start, before getting connected to. I think it would be fixed by increasing the test timeouts, and the delay before connecting to started jobs.

Rerunning the test usually works (which makes sense, as it becomes faster, due to files in cache).

#### Steps to reproduce the error: 

`npm run test` and be (un-)lucky ;)

-----

I don't plan to look into this right now, but if it annoys me enough, I might do it later, if nobody else does.

**Comment by diasdavid** [comment]
@rasmuserik thank you for the bug report, investigation is happening here: https://github.com/ipfs/js-ipfs/issues/932
