### ISSUE TITLE
WebSocket connection failed, Error 403

### ISSUE THREAD

**Issue by milankragujevic** [ipfs/js-ipfs#941]
- **Version**: 0.25.1
- **Platform**: Browser, Windows 10, Chrome 60.0.3112.78
- **Subsystem**: Not sure?

#### Description: I receive a websocket error. 

VM44:161 WebSocket connection to 'wss://ams-1.bootstrap.libp2p.io/' failed: Error during WebSocket handshake: Unexpected response code: 403

#### Steps to reproduce the error: https://milankragujevic.com/temp/ipfs/test.html

**Comment by lightninglu10** [comment]
I'm getting the same error here. Seems like there's no error handling on a failed wss reconnect so it tries a bunch and then eventually IPFS crashes which crashes my browser.

**Comment by lgierth** [comment]
Are you getting the same 403 error with other bootstrap.libp2p.io nodes too, and is this only on reconnect? I'm seeing a couple dozen peers connected to these nodes so from my point of view all is good.

**Comment by lightninglu10** [comment]
This happens to me whenever I load up my web page and I have IPFS running in the page.

<img width="337" alt="screen shot 2017-08-08 at 5 07 59 pm" src="https://user-images.githubusercontent.com/2453737/29100155-cc3845ba-7c5e-11e7-9966-9a0fe6d546ae.png">

**Comment by ya7ya** [comment]
I'm seeing the same issue too.  

![403](https://user-images.githubusercontent.com/932163/29142708-0fe2942e-7d53-11e7-8f3b-eeb9d88390c4.jpg)

**Comment by VictorBjelkholm** [comment]
@lgierth some nodes seems to work, but others not...

For example, nodes I can connect to (get status code `101`):

- sgp-1.bootstrap.libp2p.io
- nyc-{1,2}.bootstrap.libp2p.io
- lon-1.bootstrap.libp2p.io

Nodes that don't work (get status code `403`):

- sfo-{1,3}.bootstrap.libp2p.io
- ams-1.bootstrap.libp2p.io

**Comment by lgierth** [comment]
> Nodes that don't work (get status code `403`):
>
> - sfo-{1,3}.bootstrap.libp2p.io
> - ams-1.bootstrap.libp2p.io

Great, these are the ones running go-ipfs master using the new websocket lib :/

**Comment by VictorBjelkholm** [comment]
We have now rolled back the bootstrap nodes with the new websocket library so things should work correctly now.

Sorry for the temporary hiccup with this.

**Comment by milankragujevic** [comment]
Still getting a similar issue as I got before
`WebSocket connection to 'wss://sfo-2.bootstrap.libp2p.io/' failed: Error during WebSocket handshake: Unexpected response code: 502`

Only sfo-1 and sfo-2.

**Comment by diasdavid** [comment]
@milankragujevic confirm if this makes the node unusable. If I understand correctly, the browser itself will log an error if a connection fails, which doesn't mean that all the other connections won't work.

**Comment by joeltg** [comment]
Also getting this - after a while (~5 minutes) the page crashes.
<img width="472" alt="screen shot 2017-08-25 at 10 47 24 pm" src="https://user-images.githubusercontent.com/8454646/29738044-7dd4f292-89e7-11e7-9364-bcfafcca56ae.png">
<img width="535" alt="screen shot 2017-08-25 at 10 55 10 pm" src="https://user-images.githubusercontent.com/8454646/29738089-7aa02ece-89e8-11e7-8834-339401e68a80.png">

**Comment by JohnAllen** [comment]
I get exactly what @joeltg gets so won't repost unless requested.  I am also unable to `ipfs cat` content added after this so has made IPFS in the browser not very useful for the time being.

**Comment by mitra42** [comment]
I get these errors as well, BUT not many of them and it doesn't crash the page. However - the page crashing after about 5 mins is something we are seeing all the time, and is something reported on https://github.com/ipfs/js-ipfs/issues/950 and by Orbit on https://github.com/ipfs/js-ipfs/issues/942

**Comment by lightninglu10** [comment]
@joeltg check these issues on the browser crashing. 

https://github.com/ipfs/js-ipfs/issues/950

I think we solved our IPFS browser crashing issue by disabling webRTC by here: https://github.com/ipfs/js-ipfs/issues/942#issuecomment-325043835

before the # of listeners continually increased, but now they stay at a reasonable state without webRTC (which is default enabled)

**Comment by merlox** [comment]
What kind of solution is that? I just can't disable webRTC because my dapp needs it.

**Comment by mitra42** [comment]
Yes - same for us, disabling WebRTC seems to disable IIIF (both PubSub and retrieving annotation lists) which means without WebRTC our demos are non-functional

**Comment by merlox** [comment]
Here is the solution for me, I removed those 2 nodes that were emmiting the error:
BEFORE:
` const ipfs = new Ipfs({
  init: true,
  start: true,
  repo: 'ipfs-testing',
  config: {
    Bootstrap: [
      "/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
      "/dns4/sfo-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx",
      "/dns4/lon-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
      "/dns4/sfo-2.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
      "/dns4/sfo-3.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
      "/dns4/sgp-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
      "/dns4/nyc-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
      "/dns4/nyc-2.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64"
    ]
  }
})`

AFTER (note that those nodes are gone):
`         window.ipfs = new IPFS({
            init: true,
            start: true,
            config: {
               Bootstrap: [
                  "/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
                  "/dns4/lon-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
                  "/dns4/sfo-3.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
                  "/dns4/sgp-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
                  "/dns4/nyc-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
                  "/dns4/nyc-2.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64"
               ]
            }
         })`

**Comment by diasdavid** [comment]
This is no longer an issue in js-ipfs 0.25.3. Fixed with https://github.com/ipfs/js-ipfs/commit/5ec27a376a4f2e25878686b3bf4bdf08da10831c

**Comment by rstormsf** [comment]
it's still the issue
@diasdavid 
![image](https://user-images.githubusercontent.com/9360827/46648396-d6b46d80-cb49-11e8-9497-2ee774fd5889.png)

**Comment by sriharrsha** [comment]
I'm on 0.33.1 

![error](https://user-images.githubusercontent.com/5179687/50440217-c8f5c500-08ba-11e9-8abc-d5de7f41fe9d.png)

Never used wss1 or wss0 but somewhere the dependency libraries are hardcoded calling these servers.

Any Help?

**Comment by sriharrsha** [comment]
> This is no longer an issue in js-ipfs 0.25.3. Fixed with [5ec27a3](https://github.com/ipfs/js-ipfs/commit/5ec27a376a4f2e25878686b3bf4bdf08da10831c)

This is still an ongoing issue.

**Comment by sriharrsha** [comment]
> it's still the issue
> @diasdavid
> ![image](https://user-images.githubusercontent.com/9360827/46648396-d6b46d80-cb49-11e8-9497-2ee774fd5889.png)

Any Update?

**Comment by hushino** [comment]
same issue here with ipfs 0.33.1

**Comment by Juanperezc** [comment]
Rt

**Comment by hushino** [comment]
use this solve the problem
```
 Bootstrap: [
        "/dns4/ams-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
        "/dns4/lon-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
        "/dns4/nyc-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
        "/dns4/nyc-2.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64"
      ]
```

**Comment by tomnyson** [comment]
thank for problem

**Comment by AravDalwani** [comment]
![image](https://user-images.githubusercontent.com/47558750/86981310-d2483900-c1a3-11ea-9705-ffcab461410b.png)
 
Hi, I am getting similiar websocket error but with the localhost IP address. Can anyone please please help me out?
IPFS is not connecting because of this

JS-IPFS version: 0.47.0

**Comment by GiraffeKey** [comment]
I am getting that localhost error too, on version 0.48.1.

**Comment by zhgromov** [comment]
again this problem... how I can fix this?

**Comment by d4mr** [comment]
We are having the same problem. Any updates?

**Comment by zhgromov** [comment]
> We are having the same problem. Any updates?

we cancel this lib and use     "ipfs-core": "^0.2.0",

next, 
initialize node from ipfs via window

```
    const node = window.IpfsCore.create({
      repo: "projectName",
      init: {
        emptyRepo: true,
        algorithm: "ed25519",
      },
    });
    node.then((i) => this.setState({nodeIPFS: i}))
```
    
    
    after that, upload files to connected ipfs node from first code example
    
```
  const addToIpfs = async (file) => {
    const {path} = await node.add(file);

    if (path) {
      console.log(path);
      // await node.stop();
      // setSNode(false)
      return path
    }
  };
```

**Comment by d4mr** [comment]
@zhgromov thanks a ton, let me try this
