### ISSUE TITLE
IPFS crashes, and then crashes the browser

### ISSUE THREAD

**Issue by lightninglu10** [ipfs/js-ipfs#942]
- **Version**: 0.25.0
- **Platform**: JS
- **Subsystem**:

#### Description: After a certain amount of time running, IPFS crashes at some point in the browser which then our app to crash. Not sure exactly what's going on, but we see memory continuously being allocated.

Also, if you have internet, and then turn your internet off, our app crashes as well. So whenever IPFS disconnects, there seems to be some error state that kills the whole app. How should we handle this?

#### Steps to reproduce the error:

Will setup JSBIN later

**Comment by VictorBjelkholm** [comment]
Trying to reproduce this with the example that is inside the `examples/exchange-files-in-browser` directory, by doing the following: (I'm on commit `07228a022bff4d9630132c649d92017c3e7f1a68`)

- Start the example node
- Start a node with the CLI
- Add a file with the CLI node
- Connect the example node with the CLI node
- Try to get the file from the browser

And everything is working as expect. Could be something else with your application that creates the crashes? Would be interesting to know why you think js-ipfs is behind the crashes.

Also, tried turning off my connectivity as well during testing, but saw no difference.

**Comment by lgierth** [comment]
Even if #941 fixed it, it'd be good to have test case for this -- a simple 403 shouldn't crash the browser

**Comment by lightninglu10** [comment]
This is still an issue. I'm going to post something soon that shows the issue.

**Comment by magik6k** [comment]
I had this happen with my app when sending a series of dag-cbor objects between browsers.

* open https://ipfs.io/ipfs/QmVXyT5LexveeRws3quvEwzRz3YE9kuXwEy2wCKK4UC8ob/ in firefox and in chromium incognito (chromium has broken caching, this is likely thing for a different issue), this uses js-ipfs v0.25.1 from npm.
* When drawing things is one window, they should appear in the other
* When drawing short lines fast one of the browser tabs will crash (usually chromium one)
* Relevant source: https://github.com/magik6k/milky-whiteboard/blob/master/src/main/scala/eu/devtty/mboard/canvas/Chain.scala

**Comment by lightninglu10** [comment]
So I'm trying to put an example online, but getting a different error now:

http://ipfstest.quantfive.org/

```
Uncaught TypeError: Cannot read property 'generateKey' of undefined
    at Object.exports.generateKey (ipfs.min.js:29)
    at Object.generateKeyPair (ipfs.min.js:155)
    at Object.exports.generateKeyPair (ipfs.min.js:155)
    at cb (ipfs.min.js:4)
    at nextTask (ipfs.min.js:2)
    at exports.default (ipfs.min.js:2)
    at Function.exports.create (ipfs.min.js:4)
    at waterfall (ipfs.min.js:226)
    at nextTask (ipfs.min.js:2)
    at next (ipfs.min.js:2)
```
Anyone know what's up with this?

@VictorBjelkholm @lgierth

**Comment by haadcode** [comment]
This might be the same bug as https://github.com/ipfs/js-ipfs/issues/950 (Firefox - crashes with excessive thread activity), so cross posting here to make sure all the information is available.

*As a side, the bug report re. generateKey() has also been observed in the orbit-web bug linked in the issue ^*

**Comment by lightninglu10** [comment]
@haadcode thanks for alerting. This is exactly the same behavior I've been seeing. Gonna join in on that thread when I have more info.

**Comment by diasdavid** [comment]
Hi @lightninglu10, see both:
- https://github.com/ipfs/js-ipfs/issues/950#issuecomment-324586070
- https://github.com/ipfs/js-ipfs/issues/950#issuecomment-324701771

The tl;dr; is that there are two main issues: a) WebRTC consumes too much resources and b) We don't close connections. I propose there some ways to mitigate the issue while we get a robust solution for everyone. Thanks for the patience and the bug report! :)

**Comment by lightninglu10** [comment]
Hey @diasdavid I looked more into it and I'm not using webRTC but getting similar behavior in the crashing to the other issue. 

In that case not sure what the problem is!

**Comment by diasdavid** [comment]
@lightninglu10 are you sure you are not using WebRTC at all? Could you show your config file (just the part that has Addresses.Swarm)?

**Comment by lightninglu10** [comment]
I'm not using any config. I init IPFS with just IPFS(). I also disconnect (or try -- idk if it works) from all peers and only connect to my local IPFS go node.

**Comment by diasdavid** [comment]
@lightninglu10 if you are not touching the config it means you are indeed using WebRTC (which is the default).

Check how to config your IPFS node in this readme section -- https://github.com/ipfs/js-ipfs#advanced-options-when-creating-an-ipfs-node.

Also, visit the examples -- https://github.com/ipfs/js-ipfs/tree/master/examples -- they will help you understand the inner workings.

Please do keep questions coming with anything that is not clear, it helps us think how to improve docs! :)

**Comment by lightninglu10** [comment]
Oh really? I thought because of this: https://github.com/ipfs/js-ipfs#is-there-webrtc-support-for-js-ipfs-with-nodejs

that we would have to specify webRTC with modules and addresses. I'll look into the master examples to understand better.

**Comment by diasdavid** [comment]
https://github.com/ipfs/js-ipfs#is-there-webrtc-support-for-js-ipfs-with-nodejs is just for Node.js, in the Browser it runs by default. You can disable WebRTC in the browser with:

```js
const node = new IPFS({
  config: {
    Addresses: {
      Swarm: []
    }
  }
})
```

Just this :) It will overload the default config file https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/config-browser.json

**Comment by lightninglu10** [comment]
For now, disabling WebRTC in the browser seems to work. I think we lose some of the functionalities of JS-IPFS but going to close the issue for now.

**Comment by mitra42** [comment]
Did you figure out what JS-IPFS features get disabled ? When I try it, it clearly disables IIIF, I think its disabling pubsub, but also the IIIF retrieval.

**Comment by diasdavid** [comment]
@mitra42 It doesn't disable PubSub, only disables that automatic connection between Browser Peers as there is no other transport that the browser can use to connect directly to another browser.

Another route is to use WebSockets and Relay creating 2 hop connections.

**Comment by mitra42** [comment]
We don't really care what transport we are using - that should be something for IPFS to figure out not the app - BUT the problem does seem to be that if there is no direct browser-browser connection, then IPFS is no longer being a decentralized file system. Can we have that call you suggested on another thread.

**Comment by mitra42** [comment]
I'm fully aware how IP & Routing works, and that isn't my point. Its that if we go through a fixed relay then its no longer decentralized. There is a single point of failure.   

I don't have a problem doing that as an interim while other things are fixed, except that I have no way to understand what you mean by "Another route is to use WebSockets and Relay creating 2 hop connections."
