### ISSUE TITLE
Intermittent "ipfs-pubsub-room/v1" not supported

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs#944]
- **Version**: ipfs 0.25.1 (output of npm list | grep ipfs) 
- **Platform**: Mac OSX 10.11.6 (i.e. not current)
- **Subsystem**: Pubsub I think
#### Description: 

After starting IPFS it crashed - intermittent, doesn't happen every time.
"ipfs-pubsub-room/v1" not supported

#### Steps to reproduce the error:

I'm running my code in github.com/internetarchive/dweb-transport, following README.md instructions, and then running "npm js/test.js" , have seen intermittent crashes, and now that the core code is more stable I'm trying to track them down.

Note the string "room" or "v1" does not appear in my code at all.

**Comment by diasdavid** [comment]
Thank you for reporting this issue, @mitra42 :) 

This sounds like a race condition on the `ipfs-pubsub-room` code, where a node tries to handshake on the protocol `ipfs-pubsub-room/v1` but the other node hasn't mounted the protocol yet. This should not crash the node though. Do you see an actual error coming out of it or just a log?

@pgte can you check what is going on on ipfs-pubsub-room?

**Comment by pgte** [comment]
Should be fixed in version 0.1.4 of `ipfs-pubsub-room` by  https://github.com/ipfs-shipyard/ipfs-pubsub-room/commit/866b063eea6b208638c7a334b6f94f5e47116e6a

**Comment by pgte** [comment]
Updated dep on y-ipfs-connector, so if you're using it directly please update that to v1.2.1.

@mitra42 thanks for the report!

**Comment by mitra42** [comment]
Looks like there are some issues with the dependency chain ... 
On node when I try npm install ipfs-iiif-db 
I get 
npm ERR! notarget No matching version found for ipfs-pubsub-room@^0.1.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'y-ipfs-connector'
npm ERR! notarget 
Is ipfs-pubsub-room pushed to wherever npm gets it from, or is that just a matter of time (because at the moment it breaks installation of anything in node that depends on y-ipfs-connector. 

For the browser version, I'm using 
<script src="https://unpkg.com/ipfs-iiif-db/dist/browser.js">

Will that get auto-updated ? 

The bug is intermittent, so waiting is an option, though i'm concerned that ipfs-iiif-db is requesting an old version of y-ipfs-connector either directly or indirectly ?

**Comment by mitra42** [comment]
P.S. I don't know how to reopen this bug, either that or I don't have sufficient permissions to do so. So I'm not sure if you'll see the comment above ?

**Comment by mitra42** [comment]
Update: 
npm install y-ipfs-connector
also fails so looks like the problem is there, rather than in ipfs-iif-db

**Comment by unibitlabs** [comment]
confirmed. same issue.

**Comment by mitra42** [comment]
Confirmed that fixes npm install y-ipfs-connector etc
