### ISSUE TITLE
Error: Stream ended prematurely 

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs#949]
- **Version**: ipfs 0.25.1 (output of npm list | grep ipfs)
- **Platform**: Mac OSX 10.11.6 (i.e. not current)
- **Subsystem**: Pubsub I think

#### Description:

Running ipfs-iiif-db in the browser I'm seeing "Stream ended prematurely"

I've been seeing it intermittently for a while, just now trying to track down these intermittent bugs.

#### Steps to reproduce the error:
Its hard to reproduce, but happens frequently enough in my test. 

#### Stacktrace
Error: Stream ended prematurely
Stack trace:
IpfsIiifDb</handshake/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:97667:15
_parallel/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:34895:9
once/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:25967:9
iterateeCallback@https://unpkg.com/ipfs-iiif-db/dist/browser.js:34796:17
onlyOnce/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:11503:9
_parallel/</<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:34892:13
IpfsIiifDb</propose/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:97710:14
once/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:25967:9
next@https://unpkg.com/ipfs-iiif-db/dist/browser.js:3869:20
onlyOnce/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:11503:9
IpfsIiifDb</readFixedMessage/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:140163:14
drain@https://unpkg.com/ipfs-iiif-db/dist/browser.js:52565:9
more/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:52582:18
maxDelay/</<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:52543:7
IpfsIiifDb</module.exports/reader.read/</<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:52633:13
IpfsIiifDb</module.exports/reader.read/</<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:52633:13
drain@https://unpkg.com/ipfs-iiif-db/dist/browser.js:25666:7
read1/<@https://unpkg.com/ipfs-iiif-db/dist/browser.js:25687:5
IpfsIiifDb</EventEmitter.prototype.emit@https://unpkg.com/ipfs-iiif-db/dist/browser.js:2430:7
IpfsIiifDb</</Peer.prototype._destroy@https://unpkg.com/ipfs-iiif-db/dist/browser.js:144693:3
IpfsIiifDb</</Peer.prototype._onIceStateChange@https://unpkg.com/ipfs-iiif-db/dist/browser.js:144863:7
IpfsIiifDb</</Peer/self._pc.oniceconnectionstatechange@https://unpkg.com/ipfs-iiif-db/dist/browser.js:144472:5

**Comment by diasdavid** [comment]
@mitra42 mind reporting this bug in ipfs-iiif-db repo? Seems that the error is coming from there https://github.com/ipfs-shipyard/ipfs-iiif-db

**Comment by mitra42** [comment]
Let me find a new one - I'm still seeing the error, and we aren't using IIIF any more (we are using YJS with the y-ipfs-connector, so next time it reappears I'll post it there.
