### ISSUE TITLE
util module for repo setup/teardown

### ISSUE THREAD

**Issue by noffle** [ipfs/js-ipfs#95]
[Via @diasdavid](https://github.com/ipfs/js-ipfs/pull/91#discussion_r57087894):

> It would be pretty sweet to grab this func and also the logic to 'inject' a go-ipfs repo (found in index.js and browser.js) and make a utils file that can be used across tests that can 'create and teardown a go-ipfs generated repo' and 'create and teardown a fresh baked repo.

**Comment by diasdavid** [comment]
- [x] util module https://github.com/ipfs/js-ipfs/blob/master/test/utils/temp-repo.js
- [ ] make tests use it across the board
