### ISSUE TITLE
"jsipfs swarm peers" listening all known address instead of used address to connect to that peer

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs#956]
- **Version**: 0.25.0
- **Platform**: macOS
- **Subsystem**: libp2p

#### Description:
`swarm peers` command (on CLI at least) seems to not be returning the right peers. First problem is that every peer that is connected is being added with each listener, for example, node `QmVeWHZtuF2fMWDNF8ef2XoToLdyzuH9nwBexKqi4FmXop` would show up as:

```
/ip4/127.0.0.1/tcp/4002/ipfs/QmVeWHZtuF2fMWDNF8ef2XoToLdyzuH9nwBexKqi4FmXop
/ip4/10.185.197.146/tcp/4002/ipfs/QmVeWHZtuF2fMWDNF8ef2XoToLdyzuH9nwBexKqi4FmXop
/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmVeWHZtuF2fMWDNF8ef2XoToLdyzuH9nwBexKqi4FmXop
/ip4/127.0.0.1/tcp/4002/ipfs/QmVeWHZtuF2fMWDNF8ef2XoToLdyzuH9nwBexKqi4FmXop
/ip4/10.185.197.146/tcp/4002/ipfs/QmVeWHZtuF2fMWDNF8ef2XoToLdyzuH9nwBexKqi4FmXop
```

Instead of just being listed once as expected. Which means `swarm peers | wc -l` will return addresses the node is connected to, instead of peers.

#### Steps to reproduce the error:

- Initialize two nodes
- Start one of the nodes
- Print out `jsipfs swarm peers` and `jsipfs swarm peers | wc -l`, note down the number
- Start the other node and wait five seconds for them to connect automatically
- Print out `jsipfs swarm peers` and `jsipfs swarm peers | wc -l`, compare with previous number

**Comment by diasdavid** [comment]
Seems that issue is here: https://github.com/ipfs/js-ipfs/blob/master/src/core/components/swarm.js#L12-L45

The filtering is being done by asserting if we are connected, when instead we should be picking the used address from that same call -- see https://github.com/libp2p/js-peer-info/blob/master/src/index.js#L32-L34 --.

Looks like a small patch, wanna push a PR?

**Comment by VictorBjelkholm** [comment]
@diasdavid I'll be happy to :)

**Comment by VictorBjelkholm** [comment]
Since https://github.com/ipfs/js-ipfs/pull/960 was merged, this has been fixed

**Comment by diasdavid** [comment]
wwoot! Thank you @VictorBjelkholm for handling this one :)
