### ISSUE TITLE
502 Error for SFO-1 & SFO-2

### ISSUE THREAD

**Issue by ConnorGutman** [ipfs/js-ipfs#969]
- **Version**: 0.25.2
- **Platform**: ChromeOS Version 59.0.3071.134 (Official Build) (64-bit)
- **Subsystem**: N/A

#### Description:
When running js-ipfs in a browser I'm unable to access **wss://sfo-1.bootstrap.libp2p.io/** and **wss://sfo-2.bootstrap.libp2p.io/** . I'm given the following error: 

![screenshot 2017-08-29 at 10 10 52 am](https://user-images.githubusercontent.com/2351549/29825434-5fa632aa-8ca2-11e7-8981-9fdcb632a7cb.png)

The error is happening on this [Codepen](https://codepen.io/daviddias/pen/MvqEbq) running 0.25.1, as well as my local copy on 0.25.2. All other bootstrap connections are fine.

![screenshot 2017-08-29 at 10 15 56 am](https://user-images.githubusercontent.com/2351549/29825727-3f98aec4-8ca3-11e7-861b-42908aa60f7c.png)

#### Steps to reproduce the error:
Running this [Codepen](https://codepen.io/daviddias/pen/MvqEbq) will replicate the error on my device. I've tested it on multiple wifi networks, disabled all chrome extensions, and don't believe the problem is on my end of the connection. Please let me know if there's more I can provide. :)

**Comment by diasdavid** [comment]
From all my testing what I've concluded is:

- this means that there is some issue reaching those bootstrappers //cc @lgierth 
- there is no problem with seeing that error, we handle the error graciously, it is fine that a Bootstrap dial fails.

Do you experience something different? Does it affect js-ipfs behavior? I understand that it is annoying to see _red messages_ in the log, but that is what the browser does when it fails a connection.

**Comment by ConnorGutman** [comment]
Good to know! Js-ipfs works as expected when receiving this error. I wasn't sure if the failed connections indicated a larger problem with SFO-1&2 or if the error was being handled properly. Thanks!

**Comment by mitra42** [comment]
This is happening elsewhere, I reported it on the shared text app  https://github.com/ipfs-shipyard/shared-editing-demo/issues/4 and am seeing it on our app as well. Sometimes messages still seem to get through but other times it seems to be accompanied by messages not getting through and I haven't yet figure out which conditions mean failed connectivity and which are just normal.

**Comment by ConnorGutman** [comment]
@mitra42 Thank you for looking into this, and makes sense! Let me know if there's anything I can provide you with to better understand what's going on. I only ever receive the error on SFO-1&2.
