### ISSUE TITLE
Require ipfs.min.js

### ISSUE THREAD

**Issue by lightninglu10** [ipfs/js-ipfs#976]
Hey guys, is there any way to require ipfs.min.js in javascript code?

I want to use IPFS in a package, but it won't bundle with webpack because of Uglify issues. In the past I've just included the CDN code in the browser, but I don't want to include any HTML in this package, just a pure JS package. 

Anyway to do this?

**Comment by diasdavid** [comment]
@lightninglu10 you can do require('ipfs/dist/ipfs.min.js') and that will expose an `Ipfs` global variable which is the IPFS class

**Comment by diasdavid** [comment]
@lightninglu10 did it work for you?

**Comment by lightninglu10** [comment]
I didn't try it but will soon.

**Comment by diasdavid** [comment]
Closing for now, let me know if it doesn't work :)
