### ISSUE TITLE
about example ipfs-101

### ISSUE THREAD

**Issue by kappabooom** [ipfs/js-ipfs#977]
- **Version**: 0.25.4
- **Platform**: macOS X
- **Subsystem**:

#### Description:
I operated the ipfs-101 by the tutorials, but when I key `npm install ipfs async` , the error appear
![image](https://user-images.githubusercontent.com/22300748/29995277-83bcf93e-9018-11e7-9e63-c3ab77527a3e.png)

**Comment by diasdavid** [comment]
Looks like that is a new npm feature. more info here: http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/

Try doing npm init inside that folder and check if it works. If that is the case, I'll add a package.json to the example.

**Comment by kappabooom** [comment]
yes! I can `npm install ipfs async` after npm init. 
But when I run `node 1.js`, found that I can't cat the hello.txt
![image](https://user-images.githubusercontent.com/22300748/30001996-5959db12-90d1-11e7-8aea-d8bd8d70ba57.png)
it has run about 10 mins, but nothing appear.

**Comment by diasdavid** [comment]
@kappabooom my bad. Fixed in https://github.com/ipfs/js-ipfs/pull/982/files

**Comment by kappabooom** [comment]
thanks! it work!!!

**Comment by kappabooom** [comment]
@diasdavid I have another question. In example ipfs-101, did I really put the file on the distributed web? because I can cat hello.txt on `https://ipfs.io/ipfs/QmXgZAUWd8yo4tvjBETqzUy3wLx5YRzuDwUQnBwRGrAmAo`.
but when I add another file to ipfs, I can't cat my new text on `https://ipfs.io/ipfs/QmfLEdmhPkPexiQ5JxFiXwgY4MHCWXP2D4m5WoX8jvPdFo`

**Comment by diasdavid** [comment]
yes, you really shared a file to the distributed web :) if this was the first, congratulations! 🎉

When you add another file to IPFS, do you leave your node running? Remember, IPFS is not like Cloud Storage, it is a FileSystem that uses Content Addressing to find data on the network, but it doesn't replicate data automatically for you, you need to ensure there are copies accessible.

**Comment by kappabooom** [comment]
@diasdavid I am not sure that did I keep my node on,but I vim 1.js `//stream.on('end', process.exit)`,so I think it is still on.
