### ISSUE TITLE
Awesome Endeavour - unsafe-eval no more!

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#991]
To make sure js-ipfs runs in all environments safely we want to get rid of all unsafe eval instances. The first round will be moving from [protocol-buffers](https://github.com/mafintosh/protocol-buffers) to ~~[protobufjs](https://github.com/dcodeIO/protobuf.js)~~ [protons](https://github.com/dignifiedquire/protons). 

- [x] libp2p-crypto - ~~https://github.com/libp2p/js-libp2p-crypto/pull/107~~ https://github.com/libp2p/js-libp2p-crypto/pull/110
- [x] libp2p-identify - https://github.com/libp2p/js-libp2p-identify/pull/42
- [x] libp2p-secio - https://github.com/libp2p/js-libp2p-secio/pull/93
- [x] libp2p-record - https://github.com/libp2p/js-libp2p-record/pull/5
- [x] libp2p-swarm - https://github.com/libp2p/js-libp2p-swarm/pull/230
- [x] ipld-dag-pb - ~~https://github.com/ipld/js-ipld-dag-pb/pull/39~~ https://github.com/ipld/js-ipld-dag-pb/pull/42
- [x] ipfs-unixfs - ~~https://github.com/ipfs/js-ipfs-unixfs/pull/18~~ https://github.com/ipfs/js-ipfs-unixfs/pull/19
- [x] ipfs-bitswap - https://github.com/ipfs/js-ipfs-bitswap/pull/149
- [x] libp2p-floodsub - https://github.com/libp2p/js-libp2p-floodsub/pull/48
- [x] libp2p-kad-dht - https://github.com/libp2p/js-libp2p-kad-dht/pull/16
- [x] peer-id deps update - https://github.com/libp2p/js-peer-id/pull/67

**Comment by diasdavid** [comment]
Code coverage is dropping dramatically with this change because it is trying to check if we test the newly generated code:
- https://github.com/ipld/js-ipld-dag-pb/issues/40
- https://github.com/ipfs/js-ipfs-unixfs/pull/18#issuecomment-327133784

**Comment by dignifiedquire** [comment]
Just published a release of aegir which allows to ignore files from coverage: `aegir coverage --ignore src/somefile.js`

**Comment by diasdavid** [comment]
Needs this to get done - https://github.com/ipld/js-ipld-dag-pb/issues/41

**Comment by dignifiedquire** [comment]
Good news, we don't need to migrate, just use this version of protocol-buffers I made which switches to regular functions instead of generating them and evaling: 

https://github.com/dignifiedquire/protocol-buffers/tree/fixes

perf is a bit worse, but not that bad

```
npm (encode) x 482,202 ops/sec ±3.14% (85 runs sampled)
npm (decode) x 1,863,500 ops/sec ±1.23% (91 runs sampled)
npm(encode + decode) x 349,692 ops/sec ±1.66% (82 runs sampled)
local (encode) x 423,864 ops/sec ±1.51% (88 runs sampled)
local (decode) x 1,042,350 ops/sec ±1.19% (94 runs sampled)
local(encode + decode) x 294,290 ops/sec ±1.39% (89 runs sampled)
```

**Comment by diasdavid** [comment]
Awesome @dignifiedquire !

Might make it a real module and not a fork (i.e maintained, CI, published to npm, etc)?

**Comment by dignifiedquire** [comment]
Probably yes

**Comment by dignifiedquire** [comment]
Renamed to protons: https://github.com/dignifiedquire/protons publish coming soon

**Comment by dignifiedquire** [comment]
Just published https://www.npmjs.com/package/protons

**Comment by diasdavid** [comment]
Awesome. Make sure to have a reference in the README to the original module and the reason that lead to the fork, other people will find useful.

**Comment by dignifiedquire** [comment]
there already is?

**Comment by dignifiedquire** [comment]
@diasdavid PRs are ready for you to review

**Comment by diasdavid** [comment]
Ok, everything merged, released and all the deps in the middle were also updated to make sure that npm always installs the latest patch version.

Test away :)

**Comment by diasdavid** [comment]
**Tracking results:**

- Results in ipfs-companion https://github.com/ipfs/ipfs-companion/issues/269#issuecomment-327788374
- Results in brave integration https://github.com/diasdavid/browser-laptop/pull/1#discussion_r135616832

**Comment by dignifiedquire** [comment]
Missed two modules
```
npm ls protocol-buffers
ipfs@0.25.4 /Users/dignifiedquire/opensource/ipfs/js-ipfs
├─┬ libp2p-floodsub@0.11.0
│ └─┬ libp2p-crypto@0.9.4
│   └── protocol-buffers@3.2.1  deduped
└─┬ libp2p-kad-dht@0.5.0
  └── protocol-buffers@3.2.1
```

**Comment by diasdavid** [comment]
```
ipfs@0.25.4 /Users/imp/code/js-ipfs
└── (empty)
```

**Comment by dignifiedquire** [comment]
Closing?

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/30185698-869783da-941a-11e7-991a-4bee69ffa5f2.png)
